### ISSUE TITLE
return onErrors at initialization

### ISSUE THREAD

**Issue by xero88** [rjsf-team/react-jsonschema-form#1016]
I want to have the errors throught onError when the form is rendered.
Is this possible ?

**Comment by loganvolkers** [comment]
I think that one is hard to solve, but there are a few options:

 - You could start by looking at this example: https://jsfiddle.net/spacebaboon/g5a1re63/ It uses a custom submit button and `ref` to trigger a submission. You could trigger the submit button on load.
 - You could use `liveValidate` to continuously validate
 - You could set `noValidate` to true, and then directly use `ajv` (the validation library used in this project) to create custom validation
