### ISSUE TITLE
List of things, unknown type, no type for any value

### ISSUE THREAD

**Issue by gadzet** [rjsf-team/react-jsonschema-form#1017]
### Prerequisites

- [ x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

When getting list of items like in the https://mozilla-services.github.io/react-jsonschema-form/ arrays example, i don't know if the value I'm getting is string or an integer. So after submiting a form I am getting validation error for wrong type.

### Steps to Reproduce

1. [First Step]
Make schema where you specify string as a type for input
2. [Second Step]
Get integer value in formValue as an integer for the and add it to the input with type string
3. [and so on...]
submit the form

#### Expected behavior

[What you expected to happen]
Specify type any which allows multiple types
#### Actual behavior

[What actually happened]
There is no "any" type

### Version

current

**Comment by loganvolkers** [comment]
I believe that this is already [answered in the FAQ](https://github.com/mozilla-services/react-jsonschema-form#q-does-rjsf-support-oneof-anyof-multiple-types-in-an-array-etc).

![image](https://user-images.githubusercontent.com/1157086/44743637-e440f700-aab7-11e8-9986-8badcbe913d0.png)
