### ISSUE TITLE
Field with only hours

### ISSUE THREAD

**Issue by xero88** [rjsf-team/react-jsonschema-form#1019]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I'm trying to set a hours fields. All I want is "date-time" field without the date. Only hours.

**Comment by MatejMazur** [comment]
You can build your own widget for hours. Inspire by [existing widgets](https://github.com/mozilla-services/react-jsonschema-form/tree/master/src/components/widgets) and include your widget like this:
```js
const widgets = { hours };
const uiSchema = {
 entityWithHours: { 'ui:widget': 'hours' } 
};
<Form widgets={widgets} {...} />
```
[Related docs](https://github.com/mozilla-services/react-jsonschema-form#custom-widget-components).

**Comment by epicfaace** [comment]
Related PR: #894
