### ISSUE TITLE
Cannot default array of objects to an empty array

### ISSUE THREAD

**Issue by conord33** [rjsf-team/react-jsonschema-form#1026]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

When creating an array of objects using minItems there is no way to default the array to an emtpy array. If the array is empty the package with fill it with the structure of the object with all of its keys having values of `undefined`.

### Steps to Reproduce

[Shared playground](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsibGlzdE9mT2JqZWN0cyJdLCJwcm9wZXJ0aWVzIjp7Imxpc3RPZk9iamVjdHMiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJBIGxpc3Qgb2Ygc3RyaW5ncyIsImRlZmF1bHQiOltdLCJtaW5JdGVtcyI6MSwiaXRlbXMiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiaWQiOnsidHlwZSI6InN0cmluZyJ9fSwicmVxdWlyZWQiOlsiaWQiXX19fX0sInVpU2NoZW1hIjp7Imxpc3RPZlN0cmluZ3MiOnt9LCJtdWx0aXBsZUNob2ljZXNMaXN0Ijp7InVpOndpZGdldCI6ImNoZWNrYm94ZXMifSwiZml4ZWRJdGVtc0xpc3QiOnsiaXRlbXMiOlt7InVpOndpZGdldCI6InRleHRhcmVhIn0seyJ1aTp3aWRnZXQiOiJzZWxlY3QifV0sImFkZGl0aW9uYWxJdGVtcyI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24ifX0sInVub3JkZXJhYmxlIjp7InVpOm9wdGlvbnMiOnsib3JkZXJhYmxlIjpmYWxzZX19LCJ1bnJlbW92YWJsZSI6eyJ1aTpvcHRpb25zIjp7InJlbW92YWJsZSI6ZmFsc2V9fSwibm9Ub29sYmFyIjp7InVpOm9wdGlvbnMiOnsiYWRkYWJsZSI6ZmFsc2UsIm9yZGVyYWJsZSI6ZmFsc2UsInJlbW92YWJsZSI6ZmFsc2V9fSwiZml4ZWROb1Rvb2xiYXIiOnsidWk6b3B0aW9ucyI6eyJhZGRhYmxlIjpmYWxzZSwib3JkZXJhYmxlIjpmYWxzZSwicmVtb3ZhYmxlIjpmYWxzZX19fX0=)

#### Expected behavior

When an array of objects has a `default` value of `[]` and `minItems` set higher than 1 it should default to an empty array with a validation error saying that the array must have at least `minItems`.

#### Actual behavior

`minItems` number of empty objects are injected into the array to satisfy the `minItems` constraint. If the object has any required fields validation with throw an error about the empty object not having that field instead of the array not having enough items.

### Version

`1.0.4`

**Comment by llamamoray** [comment]
I think the underlying problem here is actually that the defaults weren't being applied to form correctly. The PR #1034 which was merged yesterday fixes this (you can test by checking out master and running the playground locally).

@glasserc when do you think 1.0.5 will be pushed to NPM?

**Comment by glasserc** [comment]
I can probably cut a release today. I am trying to figure out how to handle #991.

**Comment by conord33** [comment]
I am still getting the same issue on master 😞

**Comment by anand24816** [comment]
I am still facing this issue in 2025.
