### ISSUE TITLE
Can't render custom field

### ISSUE THREAD

**Issue by w-** [rjsf-team/react-jsonschema-form#1030]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I have a jsonschema form defined as below. I followed the docs here
https://github.com/mozilla-services/react-jsonschema-form#custom-field-components

in the schema `lessons` is defined as type `array`.

```
const widgets = {
        // Title case is convention for these widgets
        DynamicSelectWidget: customDSW,
        TextareaWidget: customTAW,
    }

const fields = {
    DynamicMultipleSelectField: customDMSF,
}


const uiSchema = {
    uiSchema: {
        lessons: {            
            'ui:field': "DynamicMultipleSelectField",                        
        },
        
    }    
}


const blah = props => <CustomForm
                        schema={props.schema}
                        onSubmit={onSubmit}
                        onChange={props.onChange}
                        formData={props.formData}
                        onError={props.errorHandler}
                        uiSchema={uiSchema}
                        widgets={widgets}
                        fields={fields} />

```

with this code, the default field for array is rendered.

if, however in `uiSchema` I change

```
'ui:field': "DynamicMultipleSelectField",
```

to 

```
'ui:field': customDMSF,
```

(i.e. instead of passing a string which is the key for the `fields` object, i pass in my component directly)

My custom field renders as expected. 
Am I doing something incorrectly or are the docs incorrect?

#### Expected behavior

my custom field component renders

#### Actual behavior

the default field component renders

### Version

1.0.3

**Comment by epicfaace** [comment]
I'm trying to replicate this with the same code here: https://jsfiddle.net/epicfaace/twbuk85r/2/

However, everything seems to be working fine. @w- maybe you can send me the full sample of your code to see what is wrong?
