### ISSUE TITLE
formData return empty properties as undefined

### ISSUE THREAD

**Issue by 3dw1np** [rjsf-team/react-jsonschema-form#1035]
I am using the last package "react-jsonschema-form": "^1.0.4".
Below my profile schema :
```
const jsonFullSchema = {
  type: 'object',
  required: ['firstname', 'lastname'],
  properties: {
    identity_id: { type: 'string' },
    firstname: { type: 'string' },
    lastname: { type: 'string' },
  },
};
```

When I submit the form without any uiSchema and an empty value for identity_id, the result of formData will be:

```
{
  identity_id: undefined, 
  firstname: "John", 
  lastname: "Doe"
}
```

Why do I get an object with the key identity_id as undefined instead of an object without this key ?

**Comment by nmatsumoto4** [comment]
I have encounter the same issue.

**Comment by glasserc** [comment]
I don't think there's a reason we set undefined. I think it's an artifact of a long and complicated process of trying to handle empty fields correctly (see #289, #539). I'd be happy to review a patch.

**Comment by epicfaace** [comment]
Replicating this in this fiddle: https://jsfiddle.net/epicfaace/9p17e2qx/
