### ISSUE TITLE
ui:emptyValue does not work with selects

### ISSUE THREAD

**Issue by elyobo** [rjsf-team/react-jsonschema-form#1041]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

`ui:emptyValue` is ignored for select widgets, requiring messy workarounds to resolve due to the way that the empty value option is injected.

The workaround that works is to specify a non-falsy empty value (e.g. `"0"`) as the default for the form input (required in order to prevent the empty `<option>` from being injected), add your own empty value to the enum / enumNames (e.g. `"0"` as the value, "None" as the name), then reprocess to treat that empty value appropriately in the code dealing with the form (if `"0"` is OK then that's fine, but if you want a falsy default, e.g. an empty string, more work is required).

Obviously this is much more complex than just specifying `ui:emptyValue` with the desired value.

### Steps to Reproduce

1. Specify an enum field
1. Specify it as a select field
1. Give it a `ui:emptyValue` setting
1. Select the empty option - the `ui:emptyValue` is not used

[Simple playground reproduction](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJwcm9wZXJ0aWVzIjp7ImlkIjp7ImRlc2NyaXB0aW9uIjoiQW4gb3B0aW9uYWwgYWdlbnQgZm9yIHRoaXMgZG9jdW1lbnQuIiwiZW51bSI6WyIxIiwiMiJdLCJlbnVtTmFtZXMiOlsiSmFuZSBBZ2VudCIsIkpvZSBBZ2VudCJdLCJ0aXRsZSI6IkFnZW50IiwidHlwZSI6InN0cmluZyJ9fSwidHlwZSI6Im9iamVjdCJ9LCJ1aVNjaGVtYSI6eyJpZCI6eyJ1aTplbXB0eVZhbHVlIjoiIiwidWk6cGxhY2Vob2xkZXIiOiJObyBhZ2VudCIsInVpOndpZGdldCI6InNlbGVjdCJ9fX0=)

#### Expected behavior

The formData value should be the `ui:emptyValue` when the empty option is selected.

#### Actual behavior

There is no formData value for the field when the empty option is selected.

### Version

Current playground version.

**Comment by diogoweb2** [comment]
Same problem here... 
This problem triggers the warning:
"Warning: `value` prop on `select` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components."

    "@material-ui/core": "3.2.2"

**Comment by abhishekpdubey** [comment]
I have similar issue with the enums. Here is the playground [link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJpc0FjdGl2ZSI6dHJ1ZSwiX25hbWUiOiJTYW1wbGUgbmFtZS4ifSwic2NoZW1hIjp7InRpdGxlIjoiU2FtcGxlIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkNyZWF0ZSBhIG5ldyBTYW1wbGUuIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiaXNBY3RpdmUiOnsidHlwZSI6ImJvb2xlYW4iLCJ0aXRsZSI6IlN0YXR1cyIsImRlZmF1bHQiOiIiLCJlbnVtIjpbdHJ1ZSxmYWxzZV0sImVudW1OYW1lcyI6WyJhY3RpdmUiLCJpbmFjdGl2ZSJdfSwiX25hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiTmFtZSJ9fSwicmVxdWlyZWQiOlsiX25hbWUiLCJpc0FjdGl2ZSJdfSwidWlTY2hlbWEiOnsidWk6b3JkZXIiOlsiaXNBY3RpdmUiLCJfbmFtZSJdLCJpc0FjdGl2ZSI6eyJ1aTplbXB0eVZhbHVlIjoiIiwidWk6cGxhY2Vob2xkZXIiOiJjaG9vc2UiLCJ1aTp3aWRnZXQiOiJzZWxlY3QifX19)

Based on the documentation here - https://react-jsonschema-form.readthedocs.io/en/latest/validation/#the-case-of-empty-strings
when enum is used with select widget, an empty option is added in the dropdown. This is not happening  in the playground link I shared above.
And yes, ui:emptyValue does not work for me.
Also, ui:placeholder not working for me. I don't see "choose" in the Status dropdown.
Am I missing anything?

**Comment by oncletom** [comment]
As far as I can see, the `processValue()` method of `SelectWidget` returns `undefined` if a field is an empty string. Is that it?

**Comment by heath-freenome** [comment]
Fixed in v5 beta via https://github.com/rjsf-team/react-jsonschema-form/pull/3026
