### ISSUE TITLE
Validation errors when using refs in dependencies

### ISSUE THREAD

**Issue by albertosanchez-natgeo** [rjsf-team/react-jsonschema-form#1044]
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Hi 👋🏻everyone.
I understand that there is no fully support for `oneOf`, nevertheless, on the README it says that except for a special case where we can use oneOf in schema dependencies.
I search on the issues and couldn't find something related. My issue is when inside the oneOf I have $refs. Looks like it doesn't match any of the options. I attached a shared playground link showing it.

### Steps to Reproduce

1. Open the [shared playground example](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJwZXJzb24iOnsiRG8geW91IGhhdmUgYW55IHBldHM/IjoiTm8ifX0sInNjaGVtYSI6eyJ0aXRsZSI6IlNjaGVtYSBkZXBlbmRlbmNpZXMiLCJ0eXBlIjoib2JqZWN0IiwiZGVmaW5pdGlvbnMiOnsib3B0aW9uMSI6eyJwcm9wZXJ0aWVzIjp7IkRvIHlvdSBoYXZlIGFueSBwZXRzPyI6eyJlbnVtIjpbIk5vIl19fX0sIm9wdGlvbjIiOnsicHJvcGVydGllcyI6eyJEbyB5b3UgaGF2ZSBhbnkgcGV0cz8iOnsiZW51bSI6WyJZZXM6IE9uZSJdfSwiSG93IG9sZCBpcyB5b3VyIHBldD8iOnsidHlwZSI6Im51bWJlciJ9fSwicmVxdWlyZWQiOlsiSG93IG9sZCBpcyB5b3VyIHBldD8iXX0sIm9wdGlvbjMiOnsicHJvcGVydGllcyI6eyJEbyB5b3UgaGF2ZSBhbnkgcGV0cz8iOnsiZW51bSI6WyJZZXM6IE1vcmUgdGhhbiBvbmUiXX0sIkRvIHlvdSB3YW50IHRvIGdldCByaWQgb2YgYW55PyI6eyJ0eXBlIjoiYm9vbGVhbiJ9fSwicmVxdWlyZWQiOlsiRG8geW91IHdhbnQgdG8gZ2V0IHJpZCBvZiBhbnk/Il19fSwicHJvcGVydGllcyI6eyJwZXJzb24iOnsidGl0bGUiOiJQZXJzb24iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJEbyB5b3UgaGF2ZSBhbnkgcGV0cz8iOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiTm8iLCJZZXM6IE9uZSIsIlllczogTW9yZSB0aGFuIG9uZSJdLCJkZWZhdWx0IjoiTm8ifX0sInJlcXVpcmVkIjpbIkRvIHlvdSBoYXZlIGFueSBwZXRzPyJdLCJkZXBlbmRlbmNpZXMiOnsiRG8geW91IGhhdmUgYW55IHBldHM/Ijp7Im9uZU9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9vcHRpb24xIn0seyIkcmVmIjoiIy9kZWZpbml0aW9ucy9vcHRpb24yIn0seyIkcmVmIjoiIy9kZWZpbml0aW9ucy9vcHRpb24zIn1dfX19fX0sInVpU2NoZW1hIjp7fX0=)
2. Select any option on the **Do you have any pets?** question.

#### Expected behavior

For this example I took the working example and just moved the options to the definitions and add the refs. So I would expect to work as usual and is not.

#### Actual behavior

When moving the possible options to the definitions section. It does not match any of them showing the errors:
- should be equal to one of the allowed values
- should match exactly one schema in oneOf

### Version
Playground

I was thinking in resolving the full schema first but I would like to know your opinion about it.

Thank you

**Comment by glasserc** [comment]
This definitely looks like a bug and it's definitely an interaction between refs and dependencies. I think it's because we don't resolve the schemas in `oneOf`. I'd be happy to review a patch to fix it.

**Comment by heath-freenome** [comment]
@albertosanchez-natgeo I believe this issue is fixed in 5.x. Can you verify?
