### ISSUE TITLE
Filtering/Dependency handling on Array Field items

### ISSUE THREAD

**Issue by sahithi2018** [rjsf-team/react-jsonschema-form#1047]
### Prerequisites

- [ yes] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [yes ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
How to set dependency bewteen the nested fields
I have a schema defined as 

```
const jsonSchema = {
  type: "object",
  required: ["name", "age"],
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    age: {
      type: "string",
      title: "Age"
    },

    countries: {
      type: "array",
      items: {
        type: "object",
        required: [],
        properties: {
          country: {
            type: "string",
            title: "Country",
            enum:[],
            enumNames:[]
          },
          states: {
            type: "string",
            title: "State",
            enum: [],
           enumNames:[]
          },
          zipcode: {
            type: "string",
            title: "Zipcode",
            enum: [],
            enumNames: []
          }
        }
      }
    }
  }
};
```

In this, countries is array field
Based on what you select on country, you will have different options for your states and zipcode
How can we achieve this behavior on jsonschema form

I have tried to this at onchange, as what ever you field you change onChange gets triggered, but i have noticed two issues here

1. How do we get the array index that is changed (i could do a deep compare and get the index, but it is too complex)

2. Even if get the index, for each index i would like to set the options differently as they are dependent on the contry they have picked . With the curent setup i dont see i can define the items enum options at the schema level 
as i can just access it as schema.properties.countries.items.properties.states but not through index 

### Steps to Reproduce

Run this  https://codesandbox.io/s/xrkp754r1q
Click on Test Simple Form
It tries to open up a modal with a form , on that Click on add new item, you would see that it comes up with three fileds Country,States and ZipCode

Now if you select Country as USA you can see that states are filtered as CA and Washington
and now if you click on add new item and now in the new item , select coutnry as india you would see that states are still CA and Washington.
#### Expected behavior

Filtering has to work . For each index of array, i should be able to see the appropriate options.

#### Actual behavior

Filtering is not working for array field items

### Version

version: 1.0.4

**Comment by sahithikol** [comment]
Please suggest any thing here
