### ISSUE TITLE
no icons for demo pages

### ISSUE THREAD

**Issue by alexrqs** [rjsf-team/react-jsonschema-form#1064]
### Description
Demo page doesn't render the icons when the theme is solarized
![selection_469](https://user-images.githubusercontent.com/1099589/47430831-0f666080-d760-11e8-8794-01cf8fd878f4.png)

### Steps to Reproduce

1. go to https://mozilla-services.github.io/react-jsonschema-form/
2. click `Schema dependencies` button
3. change the theme to solarized]

#### Expected behavior
render up and down and close icons

#### Actual behavior

empty boxes

**Comment by zek0faws** [comment]
Seems to be the CDN : 
![image](https://user-images.githubusercontent.com/5436815/47667540-8d829700-dba6-11e8-8caa-0cef66bac5b2.png)

**Comment by v1vendi** [comment]
It's a problem with the theme itself, it doesnt have fles inside any more. I'd recommend to remove it completely as it might break later on
