### ISSUE TITLE
Option to omit all field labels

### ISSUE THREAD

**Issue by namya-r** [rjsf-team/react-jsonschema-form#1070]
Is there an option to omit field labels for all form fields, or do I need to add 'ui:options': { label: false } to each property?

I'm looking for an option like this:
```
const uiSchema = {
  'ui:label': false,
};
```

Right now I have,

```
const schema = {
  title: 'My Form',
  type: 'object',
  properties: {
    firstName: { type: 'string', title: 'First Name' },
    lastName: { type: 'string', title: 'Last Name' },
    email: { type: 'string', title: 'Email' },
  },
};

const uiSchema = {
  'ui:readonly': true,
  firstName: {
    'ui:options': {
      label: false,
    },
  },
  lastName: {
    'ui:options': {
      label: false,
    },
  },
  email: {
    'ui:options': {
      inputType: 'email',
      label: false,
    },
  },
};
```

**Comment by glasserc** [comment]
I don't think there's a system-wide option for it. I'd love to see a general way to transform schemas into uiSchemas for use cases like this -- see https://github.com/mozilla-services/react-jsonschema-form/issues/854#issuecomment-377773188 -- but for the time being, we don't have one.

**Comment by namya-r** [comment]
Thanks for your reply @glasserc!

**Comment by epicfaace** [comment]
@glasserc Can you elaborate more on what you mean by "a general way to transform schemas into uiSchemas"?

**Comment by glasserc** [comment]
I think there's been a few different times when users wished they could do certain kinds of programmatic traversal of a JSON Schema and either alter it, or produce a UI Schema from it. It would be really cool to see some kind of function, class or module that let you say "Here is a schema and some rules about what to do with the schema" and took care of the recursion.

This isn't a real API but maybe this will communicate the idea better:

```
let uiSchema = traverseSchema(schema, {
  onProperty: function(currentPath, schema) {
    if (schema.type === "string") {
      return { "ui:options": { label: false } };
    }
  }
});
```

**Comment by epicfaace** [comment]
> Is there an option to omit field labels for all form fields

You could also use CSS!

```css
legend {
    display: none;
}
```
