### ISSUE TITLE
Adding Items in the top of existing items in an array

### ISSUE THREAD

**Issue by sneu012** [rjsf-team/react-jsonschema-form#1073]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Currently, when we add a new item to an array, it gets added to the bottom of the list. <br /> [ArrayField.js](https://github.com/mozilla-services/react-jsonschema-form/blob/6cb26d17c0206b610b130729db930d5906d3fdd3/src/components/fields/ArrayField.js#L228-L231) 

I am trying to new add items before/above existing ones. I could not find a way to do that. I am wondering if any of y'all have run into similar issues and have any idea about it.

Thanks!

**Comment by epicfaace** [comment]
Unfortunately, I don't think there's a way to do that, but we'd welcome a PR that does implement that!
