### ISSUE TITLE
Display image in form

### ISSUE THREAD

**Issue by 245449** [rjsf-team/react-jsonschema-form#1076]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I want image (jpg/png) to be displayed after question in form. So do we have any example or schema details for same?

**Comment by epicfaace** [comment]
Adding an image component would be an excellent feature to add.

In the meantime, you can work around this by either:
1. Adding a custom widget that displays an image https://github.com/mozilla-services/react-jsonschema-form#custom-widgets-and-fields
2. Using `className` to assign a CSS class to a widget and then adding in a background image to that CSS class.

**Comment by iseth** [comment]
> Adding an image component would be an excellent feature to add.
> 
> In the meantime, you can work around this by either:
> 
> 1. Adding a custom widget that displays an image https://github.com/mozilla-services/react-jsonschema-form#custom-widgets-and-fields
> 2. Using `className` to assign a CSS class to a widget and then adding in a background image to that CSS class.

That link doesnt work because the readme was updated since, here is the correct link:
https://github.com/rjsf-team/react-jsonschema-form/tree/4a1f75486b94732111e570e5dc1e600e3a6130d3#custom-widgets-and-fields

**Comment by epicfaace** [comment]
Thanks @iseth ! Here's the same content at the latest version of the documentation site, as well: https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/
