### ISSUE TITLE
Issue with a custom SelectWidget used within an Array field

### ISSUE THREAD

**Issue by Muntaner** [rjsf-team/react-jsonschema-form#1079]
### Prerequisites

- [V] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I implemented a custom SelectWidget which allows the user to search with a search bar inside the options (useful when you have a lot of options). 
This custom widget isn't working when used inside an array with various instances of it. Its functionalities are working (options search, options selection and propagation to formData via props.onChange callback), but up/down buttons are messing up its state and delete button always deletes the last item of the array (not the item where I actually click the X).

### Steps to Reproduce

1. Implement a custom SelectWidget.
2. Replace default SelectWidgets with this.
3. Those widgets should be used by a schema which has an array of them. Place some widgets in various array items and try to play with up/down/delete buttons.

#### Expected behavior

Array up/down buttons and delete functionality should work correctly.
**The issue seems to be linked to the "key" property that React uses for re-renders.**

`        const widgets = {
            SelectWidget: this.searchableInput
        }
`

`    searchableInput = (props) => {
        return <SearchableInput key={props.id} {...props}  i18n={this.props.i18n}/>
    }
`

`
class SearchableInput extends React.Component {
    constructor(props) {
        super(props)
        this.state = {
            fields: {
                selected: props.value,
                search: '',
                data: props.options.enumOptions.map((field) => (field.value))
            },
 ...       }
    }
`

If I set it to a random value "key = {Math.random()}" array functionalities are working but it messes up with the state of my custom components (since the Form is recreating them from props, then the state get reset).
Setting the key to props.id isn't working either.

#### Actual behavior

Array up/down button mess up with my custom widget, delete button always deletes the last element of the array.

### Version    
"react-jsonschema-form": "^1.0.5"

**Comment by epicfaace** [comment]
@Muntaner can you please provide a reproducible example on codepen or jsfiddle?
