### ISSUE TITLE
Custom errors messages with transformErrors demo link is broken.

### ISSUE THREAD

**Issue by deepan-itela** [rjsf-team/react-jsonschema-form#1110]
### Prerequisites

- [ ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

The [JsFiddle link](https://jsfiddle.net/revolunet/5r3swnr4) given for "Custom errors messages with transformErrors" demo in the Readme is not working anymore.

**Comment by epicfaace** [comment]
@revolunet Would you be willing to fix your fiddle? Otherwise I can fork it and link to that fork instead.

**Comment by revolunet** [comment]
Hi; im away from keyboard atm so feel free to fork if you can. Thanks

**Comment by epicfaace** [comment]
Let's merge this into #1584.
