### ISSUE TITLE
OnFocus event is not working for radio widgets

### ISSUE THREAD

**Issue by manirikhi** [rjsf-team/react-jsonschema-form#1116]
### Description

OnFocus event is not working for radio widgets

### Steps to Reproduce

not able to register onFocus event for radio widget and focus always goes to to 1st input field?  

reproducing fiddle
https://jsfiddle.net/manjitsingh1261/6u4bfg95/17/

#### Expected behavior

could you please add onFocus at generic level for all widgets?

**Comment by epicfaace** [comment]
Thanks for the bug report. onBlur is also missing.

onBlur and onFocus are missing for the following widgets:
RadioWidget
CheckboxWidget
CheckboxesWidget

**Comment by epicfaace** [comment]
Reopening because onFocus is still not working for `CheckboxesWidget`
