### ISSUE TITLE
multiple oneOf dependency on one field

### ISSUE THREAD

**Issue by parsapordel** [rjsf-team/react-jsonschema-form#1127]
### Prerequisites

- [yes] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [yes] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
dependencies in schema should be type array so it can support multiple oneOf on same field [like this](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ4IjoiZm9vIiwieSI6ImZvb195MSJ9LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsieCI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJmb28iLCJiYXIiXX19LCJkZXBlbmRlbmNpZXMiOnsieCI6W3sib25lT2YiOlt7InByb3BlcnRpZXMiOnsieCI6eyJlbnVtIjpbImZvbyJdfSwieSI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJmb29feTEiLCJmb29feTIiXX19fSx7InByb3BlcnRpZXMiOnsieCI6eyJlbnVtIjpbImJhciJdfSwieSI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJiYXJfeTEiLCJiYXJfeTIiXX19fV19LHsib25lT2YiOlt7InByb3BlcnRpZXMiOnsieCI6eyJlbnVtIjpbImZvbyJdfSwieiI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJmb29fejEiLCJmb29fejIiXX19fSx7InByb3BlcnRpZXMiOnsieCI6eyJlbnVtIjpbImJhciJdfSwieiI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJiYXJfejEiLCJiYXJfejIiXX19fV19XX19LCJ1aVNjaGVtYSI6e319).
but it is actually [like this](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ4IjoiZm9vIiwieSI6ImZvb195MSJ9LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsieCI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJmb28iLCJiYXIiXX19LCJkZXBlbmRlbmNpZXMiOnsieCI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJ4Ijp7ImVudW0iOlsiZm9vIl19LCJ5Ijp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbImZvb195MSIsImZvb195MiJdfX19LHsicHJvcGVydGllcyI6eyJ4Ijp7ImVudW0iOlsiYmFyIl19LCJ5Ijp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbImJhcl95MSIsImJhcl95MiJdfX19XX19fSwidWlTY2hlbWEiOnt9fQ==) so you can't add a third field like `z` that depends on `x`
I know it can be handled [like this](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ4IjoiZm9vIiwieSI6ImZvb195MSIsInoiOiJmb29fejEifSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7IngiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiZm9vIiwiYmFyIl19fSwiZGVwZW5kZW5jaWVzIjp7IngiOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsieCI6eyJlbnVtIjpbImZvbyJdfSwieSI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJmb29feTEiLCJmb29feTIiXX0sInoiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiZm9vX3oxIiwiZm9vX3oyIl19fX0seyJwcm9wZXJ0aWVzIjp7IngiOnsiZW51bSI6WyJiYXIiXX0sInkiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiYmFyX3kxIiwiYmFyX3kyIl19LCJ6Ijp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbImJhcl96MSIsImJhcl96MiJdfX19XX19fSwidWlTY2hlbWEiOnt9fQ==) but in large cases [like this](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ4Ijp7InR5cGUiOiJudW1iZXIiLCJlbnVtIjpbMSwyLDMsNCw1LDYsNyw4LDksMTBdfX0sImRlcGVuZGVuY2llcyI6eyJ4Ijp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7IngiOnsiZW51bSI6WzFdfSwieSI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJsZXNzIHRoYW4gb3IgZXF1YWwgNSJdfSwieiI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJvZGQiXX19fSx7InByb3BlcnRpZXMiOnsieCI6eyJlbnVtIjpbMl19LCJ5Ijp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbImxlc3MgdGhhbiBvciBlcXVhbCA1Il19LCJ6Ijp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbImV2ZW4iXX19fSx7InByb3BlcnRpZXMiOnsieCI6eyJlbnVtIjpbM119LCJ5Ijp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbImxlc3MgdGhhbiBvciBlcXVhbCA1Il19LCJ6Ijp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIm9kZCJdfX19LHsicHJvcGVydGllcyI6eyJ4Ijp7ImVudW0iOls0XX0sInkiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsibGVzcyB0aGFuIG9yIGVxdWFsIDUiXX0sInoiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiZXZlbiJdfX19LHsicHJvcGVydGllcyI6eyJ4Ijp7ImVudW0iOls1XX0sInkiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsibGVzcyB0aGFuIG9yIGVxdWFsIDUiXX0sInoiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsib2RkIl19fX0seyJwcm9wZXJ0aWVzIjp7IngiOnsiZW51bSI6WzZdfSwieSI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJtb3JlIHRoYW4gNSJdfSwieiI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJldmVuIl19fX0seyJwcm9wZXJ0aWVzIjp7IngiOnsiZW51bSI6WzddfSwieSI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJtb3JlIHRoYW4gNSJdfSwieiI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJvZGQiXX19fSx7InByb3BlcnRpZXMiOnsieCI6eyJlbnVtIjpbOF19LCJ5Ijp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIm1vcmUgdGhhbiA1Il19LCJ6Ijp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbImV2ZW4iXX19fSx7InByb3BlcnRpZXMiOnsieCI6eyJlbnVtIjpbOV19LCJ5Ijp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIm1vcmUgdGhhbiA1Il19LCJ6Ijp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIm9kZCJdfX19LHsicHJvcGVydGllcyI6eyJ4Ijp7ImVudW0iOlsxMF19LCJ5Ijp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIm1vcmUgdGhhbiA1Il19LCJ6Ijp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbImV2ZW4iXX19fV19fX0sInVpU2NoZW1hIjp7fX0=) it requires to get all intersection of fields and its hard

#### Expected behavior
I want to be able to use multiple fields that depend on one field

#### Actual behavior
I can only use one dependency for each field

### Version
version==1.1.0

**Comment by KailasRJ-Neoito** [comment]
@epicfaace  Is it possible to have multiple dependencies?.. If two fields or two checkboxes are checked..only then will a field or check box come up...

**Comment by epicfaace** [comment]
Yes, but in that case you might not be able to use dependencies, but you might need to use oneOf instead (https://json-schema.org/understanding-json-schema/reference/combining.html#oneof).
