### ISSUE TITLE
Use uiSchema to customize oneOf/anyOf with different types

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#1141]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I would like to use oneOf with different types. (another way of solving the problem in issue #282)

### Steps to Reproduce

Use this schema:
```
{
  "type": "object",
  "properties": {
    "name": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "number"
        }
      ]
    }
  }
}
```

[Playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJuYW1lIjp7Im9uZU9mIjpbeyJ0eXBlIjoic3RyaW5nIn0seyJ0eXBlIjoibnVtYmVyIn1dfX19LCJ1aVNjaGVtYSI6e319)

#### Expected behavior

Want to be able to select different types.

#### Actual behavior

I get this:
![image](https://user-images.githubusercontent.com/1689183/51443965-f1989100-1ca5-11e9-91a6-51c02742593d.png)

### Version

1.2.0

**Comment by Rasstrelnikov** [comment]
I have encountered nearly the same issue in that I would like to use oneOf with an object and a basic type. I also want to use this oneOf inside an array. The oneOf works differently inside and outside of an array.

Here is the oneOf schema by itself:


```
{
  "oneOf": [
    {
      "type": "integer"
    },
    {
      "type": "object",
      "properties": {
        "elt1": {
          "type": "integer"
        },
        "elt2": {
          "type": "string"
        }
      },
      "required": [
        "elt1",
        "elt2"
      ]
    }
  ]
}
```

With a [playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJvbmVPZiI6W3sidHlwZSI6ImludGVnZXIifSx7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImVsdDEiOnsidHlwZSI6ImludGVnZXIifSwiZWx0MiI6eyJ0eXBlIjoic3RyaW5nIn19LCJyZXF1aXJlZCI6WyJlbHQxIiwiZWx0MiJdfV19LCJ1aVNjaGVtYSI6e319). 

This works fairly well although it is a little glitchy. 

And the same schema within an array:

```
{
  "type": "object",
  "properties": {
    "myArray": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "type": "integer"
          },
          {
            "type": "object",
            "properties": {
              "elt1": {
                "type": "integer"
              },
              "elt2": {
                "type": "string"
              }
            },
            "required": [
              "elt1",
              "elt2"
            ]
          }
        ]
      }
    }
  }
}
```

With a [playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJteUFycmF5Ijp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7Im9uZU9mIjpbeyJ0eXBlIjoiaW50ZWdlciJ9LHsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZWx0MSI6eyJ0eXBlIjoiaW50ZWdlciJ9LCJlbHQyIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbImVsdDEiLCJlbHQyIl19XX19fX0sInVpU2NoZW1hIjp7fX0=)


This displays completely different behavior from the previous schema and does not allow input for the second option.

**Comment by LucianBuzzo** [comment]
@Rasstrelnikov Since you have reported a separate problem, I've opened a new issue to track it https://github.com/mozilla-services/react-jsonschema-form/issues/1168
