### ISSUE TITLE
Adding a block of text or image

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#1146]
It would be nice to be able to add a "block" which contains a title / image / text / custom JSX. Kind of like how in Google forms, you can add these kinds of blocks.

![image](https://user-images.githubusercontent.com/1689183/51483947-2a407500-1d4f-11e9-8663-3a621c0d6aa3.png)

Is there a way to specify this in the JSON Schema spec? Or perhaps we would need a modification in the UISchema?

**Comment by loganvolkers** [comment]
## JSON Schema spec

There is nothing in the JSON schema spec that provides such capabilities for custom blocks.

One thing that I have seen done is providing Markdown support in the `title` and `description` fields, such as in the [Open API Specification](https://swagger.io/specification/).

We have implemented this using a custom `FieldTemplate` property, but the easiest is via a Markdown-supported `DescriptionField`. See: https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/#custom-descriptions


## Custom blocks

I'd rather see this provided as a plugin than as part of the core library. For example this can be done with custom spin on the `ui:order` property in object field templates.

I have done something similar here using just templating: https://codesandbox.io/s/0y7787xp0l

**Comment by epicfaace** [comment]
Thanks @loganvolkers , that makes sense -- and once https://github.com/mozilla-services/react-jsonschema-form/pull/1152 is merged, it will be easier to create custom `FieldTemplate`s for each description.

**Comment by heath-freenome** [comment]
With the 5.x implementation of the `TitleFieldTemplate` and `DescriptionFieldTemplate` adding Markdown should be very easy. Closing as this is a feature and a special use case that people can now easily implement themselves.

**Comment by quazgar** [comment]
Note to self and other users: This is what *Null fields* can be used for (see [example in the playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJoZWxwVGV4dCI6bnVsbCwiZmlyc3ROYW1lIjoiQ2h1Y2sifSwic2NoZW1hIjp7InRpdGxlIjoiTnVsbCBmaWVsZCBleGFtcGxlIiwiZGVzY3JpcHRpb24iOiJBIHNob3J0IGZvcm0gd2l0aCBhIG51bGwgZmllbGQiLCJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsiZmlyc3ROYW1lIl0sInByb3BlcnRpZXMiOnsiaGVscFRleHQiOnsidGl0bGUiOiJBIG51bGwgZmllbGQiLCJkZXNjcmlwdGlvbiI6Ik51bGwgZmllbGRzIGxpa2UgdGhpcyBhcmUgZ3JlYXQgZm9yIGFkZGluZyBleHRyYSBpbmZvcm1hdGlvbi5cblxuRXNwZWNpYWxseSB3aXRoIG1hcmtkb3duLlxuXG4hW2ltYWdlIHJlZl0oaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL3Jqc2YtdGVhbS9yZWFjdC1qc29uc2NoZW1hLWZvcm0vNTlhODIwNmUxNDg0NzRiZWE4NTRiYmIwMDRmNjI0MTQzZmJjYmFjOC9wYWNrYWdlcy9jb3JlL2xvZ28ucG5nKSIsInR5cGUiOiJudWxsIn0sImZpcnN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJBIHJlZ3VsYXIgc3RyaW5nIGZpZWxkIiwiZGVmYXVsdCI6IkNodWNrIn19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiJ9LCJoZWxwVGV4dCI6eyJ1aTplbmFibGVNYXJrZG93bkluRGVzY3JpcHRpb24iOnRydWV9fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGVkIjpmYWxzZSwibm9IdG1sNVZhbGlkYXRlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlLCJleHBlcmltZW50YWxfY29tcG9uZW50VXBkYXRlU3RyYXRlZ3kiOiJjdXN0b21EZWVwIiwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjoicG9wdWxhdGUiLCJhbGxPZiI6InNraXBEZWZhdWx0cyIsImNvbnN0QXNEZWZhdWx0cyI6ImFsd2F5cyIsImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyIsIm1lcmdlRGVmYXVsdHNJbnRvRm9ybURhdGEiOiJ1c2VGb3JtRGF0YUlmUHJlc2VudCJ9LCJ1c2VGYWxsYmFja0ZpZWxkIjpmYWxzZSwidXNlRmFsbGJhY2tVaUZvclVuc3VwcG9ydGVkVHlwZSI6ZmFsc2UsImxpdmVWYWxpZGF0ZSI6ZmFsc2UsImlkUHJlZml4Ijoicm9vdCIsImlkU2VwYXJhdG9yIjoiXyJ9LCJ2YWxpZGF0b3IiOiJBSlY4Iiwic2FtcGxlTmFtZSI6Ik51bGwgZmllbGRzIn0=)).
