### ISSUE TITLE
Google autofill overwriting existing data

### ISSUE THREAD

**Issue by mabeabe28** [rjsf-team/react-jsonschema-form#1153]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

JSfiddle: https://jsfiddle.net/woahpaolo/z6tsp8ru/

Manually type firstname and lastname...then ensure you have a Google Autofill saved for email, which consists of a first name and last name. 

Select that email from Autofill. and it will overwrite the manually typed Firstname and lastname

### Description

When I fill out a form, and then use autofill on one field...it will update all previously filled in data if those fields have auto fill data relating to it.  In other non-react forms, this does not do this, and only fills in empty fields.

This means if i want to autofill an Email address, but that email address has different information on saved autofill data, it will overwrite my manually filled in fields. It should only autofill empty fields. Critcial if previous fields have been scrolled out of view, and we can't see that autofill has changed this data.

Perhaps this is due to the input 'value' attribute being updated as we type (which is usually used as just a default value) non-react apps don't update this attribute as we type...to Google autofill it sees it as an 'empty' field and it overwrites it.

### Steps to Reproduce

1. Fill out form e.g Firstname and Lastname
2. Go to an email field and using Google autofill select an email you want to fill the field with
3. Any other fields attributed to that email also gets updated, including the previously manually filled out firstname and lastname

#### Expected behavior

Autofill will only autofill related empty fields and not overwrite fields with a value

#### Actual behavior

Autofill fills every related information regardless if it already has a value or not.

**Comment by epicfaace** [comment]
Do you mind making a codepen that reproduces this issue?

**Comment by mabeabe28** [comment]
> Do you mind making a codepen that reproduces this issue?

Sure, here you go:
JSfiddle: https://jsfiddle.net/woahpaolo/z6tsp8ru/

Manually type firstname and lastname...then ensure you have a Google Autofill saved for email, which consists of a first name and last name. 

Select that email from Autofill. and it will overwrite the manually typed Firstname and lastname

**Comment by epicfaace** [comment]
Thanks @mabeabe28 , I'm wondering how you are saving the email through autofill on jsfiddle? If you could share your method of doing that it'd be easier for me to reproduce.

**Comment by mabeabe28** [comment]
@epicfaace it's more so Google Chromes auto fill feature, it just saves form data for me automatically as i browse/fill out forms.

However, to manually create one, if you go into saved addresses on your Chrome Browser and add one, you'll be able to replicate the issue and have a suggested email on the fiddle.

**Comment by epicfaace** [comment]
I see, thanks. Here's a jsfiddle with a regular HTML form with the expected behavior (in contrast): https://jsfiddle.net/epicfaace/1my3f9n4/1/

**Comment by epicfaace** [comment]
When I fill out the form, then manually change the "value" attribute of the firstname and lastname inputs to nothing in the Chrome HTML inspector, then the autofill works as expected.

**Comment by epicfaace** [comment]
Can confirm that this problem exists in regular React as well, so it's not specific to rjsf. https://jsfiddle.net/epicfaace/9p17e2qx/20/

**Comment by mabeabe28** [comment]
Yeah it seems to be a general react issue... figured there would be a way round that rjsf could implement. setting autocomplete=off doesnt work...but autocomplete="anystringetcetc" (making it equal to any value but off) seems to work, and Google doesnt overwrite it. 

So my way around was in 'components/widgets/BaseInput.js' to add autocomplete={value == null ? "" : value} to the input component. 

This way onChange, it adds a value to autocomplete which Google will not overwrite a field in a value now. Autofill will work if the value is empty so autocomplete="", which is the expected behaviour.

I'll probably fork the project for my own project, since not sure if it'll be something that'll be included in rjsf master.

**Comment by epicfaace** [comment]
@mabeabe28 Your solution works (this jsfiddle: https://jsfiddle.net/epicfaace/9p17e2qx/28/).

I think it's worth it to add it to the library, unless you can think of any undesirable consequences of doing this? One thing is, the code will need to set `autoComplete={value == null ? "" : value}` *only if* the autocomplete attribute of the `<Form>` is not set to `"off"`. Can you make a PR?

**Comment by epicfaace** [comment]
Actually, one thing to keep in mind is how adding this fix may interact with implementing a `ui:autocomplete` property as in #906.
