### ISSUE TITLE
Infinite $ref recursive error via computeDefaults

### ISSUE THREAD

**Issue by dok** [rjsf-team/react-jsonschema-form#1160]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I'm able to consistently reproduce a maximum callstack error. Here is an image of the error.

<img width="1440" alt="screen shot 2019-01-30 at 10 55 21 am" src="https://user-images.githubusercontent.com/1214868/52005239-11863c80-247e-11e9-9deb-8768d1eece50.png">

I believe this is due to the `utils.computeDefaults` method, that recursively follows a $ref.

### Steps to Reproduce

Copy and paste these snippets into their respective input fields in the [playground](https://mozilla-services.github.io/react-jsonschema-form/).

***JSONSchema***
```json
{
  "definitions": {
    "node": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "children": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/node"
          }
        },
        "otherNode": {
          "$ref": "#/definitions/node"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "tree": {
      "title": "Recursive references",
      "$ref": "#/definitions/node"
    }
  }
}
```

***UISchema***
```json
{
  "ui:order": [
    "tree"
  ]
}
```

***FormData***
```json
{
  "billing_address": {
    "city": "Babel",
    "state": "Neverland"
  },
  "shipping_address": {
    "street_address": "221B, Baker Street",
    "city": "London",
    "state": "N/A"
  },
  "tree": {
    "name": "root",
    "children": []
  }
}
```

#### Expected behavior

I'm not sure what the expected behavior for this type of behavior is. Since the `$ref` object does not have a `.default` property, should it exit out of the recursive loop?

#### Actual behavior

```
Uncaught RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at findSchemaDefinition (utils.js:489)
    at computeDefaults (utils.js:228)
    at utils.js:246
    at Array.reduce (<anonymous>)
    at computeDefaults (utils.js:243)
    at computeDefaults (utils.js:229)
    at utils.js:246
    at Array.reduce (<anonymous>)
    at computeDefaults (utils.js:243)
```

### Version

***1.2.0***

**Comment by glasserc** [comment]
This is an old weakness in rjsf. See #557 and #820. In principle it isn't necessary to instantiate the entire schema, but we do at the moment.

**Comment by crubier** [comment]
Gigantic blocker for me.
