### ISSUE TITLE
oneOf and anyOf are not working if property can be string or array of strings

### ISSUE THREAD

**Issue by betalb** [rjsf-team/react-jsonschema-form#1176]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

If we have schema that allows property to be a `primitive type` or array of the same `primitive type`, I'm not able to create array.

If I change the order of definitions inside of anyOf/oneOf and place array first, everything works as expected.

Also there are no issues if value type is not primitive.

### Steps to Reproduce

https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJzdHJpbmdPckFycmF5T2ZTdHJpbmciOnsidGl0bGUiOiJTdHJpbmcgT3IgQXJyYXkgb2YgU3RyaW5ncyIsIm9uZU9mIjpbeyJ0aXRsZSI6IlN0cmluZyIsInR5cGUiOiJzdHJpbmcifSx7InRpdGxlIjoiQXJyYXkgb2YgU3RyaW5ncyIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmcifX1dfX19LCJ1aVNjaGVtYSI6e319

#### Expected behavior

I am able to create field with primitive value and array of primitive values

#### Actual behavior

I am able to create only primitive value

### Version

1.2.0

**Comment by adrianriddle** [comment]
@betalb - do you have an example of this working with a non-primative setup? I am having the same issue but with a $ref to a definition or an array of the same $ref to a definition.

**Comment by adrianriddle** [comment]
This looks to be coming from the getMatchingOption function in the MultiSchemaField.js file.
When adding a value to the array it's not seen as a valid value according to the check "isValid" (uses ajv and checks that the formData is valid according to the schema). The initial value in the array is null, so the select will fall back to the first option. 

This is also an issue when using an object with required fields. The initial formData that gets added in from the "Add" button will not have the required fields so the validation is false and it can't determine which option needs to be used.

@LucianBuzzo - thinking you might have the most insight into this as it's similar to the anyOf and oneOf updates that you added lately.

**Comment by epicfaace** [comment]
@adrianriddle Thanks for isolating the issue. Would you be able to make a PR to fix this?
