### ISSUE TITLE
References inside oneOf breaks form UI.

### ISSUE THREAD

**Issue by arthas702** [rjsf-team/react-jsonschema-form#1182]
### Prerequisites

- [ x ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ x ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ x ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
references do not work well with oneOf. 

### Steps to Reproduce
I've created a fiddle here. Navigate to Option 2 then try to edit the string value. 
https://jsfiddle.net/6ptuvxw8/

#### Expected behavior
The string value of TypeB should be modified as you type.

#### Actual behavior
The UI reset and Option 1 is displayed. If you continue editing the number field of Option 1 the Data becomes invalid as it contains both TypeA and TypeB fields.

### Version

1.2.1

**Comment by arthas702** [comment]
Did some debugging, isValid from ajv is used only by AnyOfField. And it doesn't seem to be able to validate object type.

**Comment by KDederichs** [comment]
I'm facing the same issue trying to build a logic filter system, example:

https://jsfiddle.net/wrp648bt/1/

Instead of glitching the UI though it gives me this error:
```
Unsupported field schema for field root_root_nodes_0: Unknown field type undefined.
```

**Comment by epicfaace** [comment]
@arthas702 I believe you're on the right track to fixing this. Could you make a PR fixing this issue?

**Comment by arthas702** [comment]
I'm not familiar enough with the code base. But feel free to see my fork.
also formContext wasn't passed into MultiSchemaField. I fixed that on my fork too.

**Comment by munybt** [comment]
I'm having the same issue, are there any news on this?

**Comment by munybt** [comment]
I think I figured it out.
I solved the issue by replacing
` 
    { ...refSchema , ...$localSchema},
`
by
`
    { ...localSchema, ...$refSchema },
`

on utils.js line 49 (return statement of the `function resolveReference(schema, definitions, formData)`)

I don't know if this fix is going to break any other features, but it is working for me by now

**Comment by kikonejacob** [comment]
@epicfaace  Any update on this bug?

**Comment by Steffan-Ennis** [comment]
So I've noticed help has gone dark on this Issue. I've been having a bit of troubles with references in oneOf blocks in a dependancy. See #2201
