### ISSUE TITLE
noHtml5Validate should be true by default

### ISSUE THREAD

**Issue by alexose** [rjsf-team/react-jsonschema-form#1184]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

The default HTML5 validation makes for a confusing UX. For end users, the styling and behavior is inconsistent with the rest of the library (see n1k0's comment [here](https://github.com/mozilla-services/react-jsonschema-form/issues/350#issuecomment-255025017)).  For developers who are new to react-jsonschema-form, it makes for a puzzling situation when you try to customize how errors are displayed.

### Steps to Reproduce

In Chrome:
1. Create a react-jsonschema-form with a single required field
2. Submit the form
3. Observe the 'Please fill out this field' box that appears.

#### Expected behavior

react-jsonschema-form should have displayed its normal error handling.

#### Actual behavior

The default html5 form validation overrode the normal error handling.

### Version

1.2.1

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by epicfaace** [comment]
That's a good point. What do you think @glasserc @edi9999 @LucianBuzzo ?

**Comment by edi9999** [comment]
I think like you, it is a good idea but since it is backwards incompatible, it should be done in v2 only

**Comment by LucianBuzzo** [comment]
@edi9999 @epicfaace This interaction is pretty horrible, especially for checkbox/boolean fields. It's definitely a breaking change though, so it should coincide with a major version bump of the npm package.

**Comment by sbusch** [comment]
+1 for disabling html5 validation by default in V2

I wonder if there's a legitimate need for HTML5 validation? If no, the `noHtml5Validate` prop and DOM attributes related to HTML5 form validation could be removed completely.

**Comment by glasserc** [comment]
I would be OK with disabling HTML5 validation in V2.
