### ISSUE TITLE
Duplicate items in Select widget without the Error: "enum should NOT have duplicate items"

### ISSUE THREAD

**Issue by hangaritaPaymentez** [rjsf-team/react-jsonschema-form#1185]
### Prerequisites

- [ X ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ X ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Hello! I'm very new at using this library and I've been loving it so far but I have the next problem.

I'm using the next JSON:

`{
  "properties": {
    "bank": {
      "uniqueItems": false,
      "items": {},
      "enum": [
        "0",
        "1552",
        "1040",
        "1081",
        "1080",
        "10322",
        "1032",
        "1019",
        "1078",
        "1052",
        "1061",
        "1016",
        "1051",
        "10512",
        "1039",
        "1001",
        "1023",
        "1062",
        "1010",
        "1012",
        "1060",
        "1002",
        "1058",
        "1203",
        "1101",
        "1065",
        "1035",
        "1004",
        "1005",
        "1022",
        "1055",
        "1055",
        "10072",
        "10071",
        "1007",
        "1013",
        "1009",
        "1292",
        "1551",
        "1006",
        "1508",
        "121212"
      ],
      "enumNames": [
        "A continuación seleccione su banco",
        "BAN.CO",
        "BANCO AGRARIO",
        "BANCO AGRARIO DESARROLLO",
        "BANCO AGRARIO QA DEFECTOS",
        "BANCO CAJA SOCIAL",
        "BANCO CAJA SOCIAL DESARROLLO",
        "BANCO COLPATRIA DESARROLLO",
        "BANCO COLPATRIA UAT",
        "BANCO COMERCIAL AVVILLAS S.A.",
        "BANCO COOMEVA S.A. - BANCOOMEVA",
        "BANCO COOPERATIVO COOPCENTRAL",
        "BANCO DAVIVIENDA",
        "BANCO DAVIVIENDA Desarrollo",
        "BANCO DE BOGOTA",
        "BANCO DE BOGOTA DESARROLLO 2013",
        "BANCO DE OCCIDENTE",
        "BANCO FALABELLA",
        "BANCO GNB COLOMBIA (ANTES HSBC)",
        "BANCO GNB SUDAMERIS",
        "BANCO PICHINCHA S.A.",
        "BANCO POPULAR",
        "BANCO PROCREDIT COLOMBIA",
        "BANCO PRODUCTOS POR SEPARADO",
        "Banco PSE",
        "BANCO SANTANDER COLOMBIA",
        "BANCO TEQUENDAMA",
        "Banco union Colombia Credito",
        "Banco union Colombia credito FD",
        "BANCO UNION COLOMBIANO",
        "Banco Web Service ACH",
        "Banco Web Service ACH WSE 3.0",
        "BANCOLOMBIA DATAPOWER",
        "BANCOLOMBIA DESARROLLO",
        "BANCOLOMBIA QA",
        "BBVA COLOMBIA S.A.",
        "CITIBANK COLOMBIAS.A.",
        "CONFIAR COOPERATIVA FINANCIERA",
        "DAVIPLATA",
        "ITAU",
        "NEQUI CERTIFICACION",
        "Prueba Steve"
      ],
      "title": "form-bank",
      "type": "string"
    },
    "fiscal_number": {
      "title": "form-fiscal_number",
      "type": "integer"
    },
    "fiscal_number_type": {
      "enum": [
        "CC",
        "CE",
        "NIT",
        "TI",
        "PP",
        "IDC",
        "CEL",
        "RC",
        "DE"
      ],
      "enumNames": [
        "Cédula de ciudadanía",
        "Cédula de extranjería",
        "Número de identificación tributario",
        "Tarjeta de identidad",
        "Pasaporte",
        "Identificador único de cliente",
        "línea del móvil",
        "Registro civil de nacimiento",
        "Documento de identificación extranjero"
      ],
      "options": {
        "CC": "Cédula de ciudadanía",
        "CE": "Cédula de extranjería",
        "CEL": "línea del móvil",
        "DE": "Documento de identificación extranjero",
        "IDC": "Identificador único de cliente",
        "NIT": "Número de identificación tributario",
        "PP": "Pasaporte",
        "RC": "Registro civil de nacimiento",
        "TI": "Tarjeta de identidad"
      },
      "title": "form-fiscal_number_type",
      "type": "string"
    },
    "last_name": {
      "title": "form-last_name",
      "type": "string"
    },
    "name": {
      "title": "form-name",
      "type": "string"
    },
    "type": {
      "enum": [
        "N",
        "J"
      ],
      "enumNames": [
        "Natural",
        "Juridica"
      ],
      "options": {
        "J": "Juridica",
        "N": "Natural"
      },
      "title": "form-type",
      "type": "string"
    }
  },
  "required": [
    "name",
    "last_name",
    "fiscal_number_type",
    "fiscal_number",
    "type",
    "bank"
  ],
  "title": "form_test",
  "type": "object",
  "uniqueItems": false
}`

and it's showing the next error:

.properties['bank'].enum should NOT have duplicate items (items ## 30 and 31 are identical)

How can I continue repeating ids (It's needed for the project) and not see this error? Sorry if it is somewhere else the answer, I couldn't find it and I'm also new at using this.

### Version
"react-jsonschema-form": "1.2.1"

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by epicfaace** [comment]
According to JSON Schema, values in an enum must be unique (see https://json-schema.org/understanding-json-schema/reference/generic.html#enumerated-values). Since "1055" is repeated twice, it does not work.

Maybe a workaround would be that you could try two different values such as "1055", "1055 " -- and then do some processing before the form is submitted to convert all "1055 " values to "1055"?
