### ISSUE TITLE
Better logging for schema issues

### ISSUE THREAD

**Issue by paintedbicycle** [rjsf-team/react-jsonschema-form#1188]
### Description

When using a large schema, it can be hard to find the specific schema issue from the log warnings. I recently received:

> ignoring oneOf in dependencies because there isn't exactly one subschema that is valid

I know there is an issue with the dependency schema for my form, but unfortunately I have several oneOf dependencies for several refs and I'm having trouble tracking down which one this refers to.

### Steps to Reproduce

Create a form with an invalid dependency schema using oneOf

#### Expected behavior

I'd love to know which schema key this refers to in the console log that outputs when the form knows there is an issue. An external validator tool could be another solution.

#### Actual behavior

Generic warning in console: 

> ignoring oneOf in dependencies because there isn't exactly one subschema that is valid

### Version

`1.2.1`

**Comment by chinds185a** [comment]
Just better errorHandling in general would be better.

I'm working on a live form builder.

Existing formSchema is loaded into a json editor a user can then edit/add to that jsonSchema, however when adding a new property in the json editor it starts by creating an empty object, the live preview form updates and throws an error instantly.

```
utils.js:232 Uncaught TypeError: Cannot use 'in' operator to search for 'default' in null
    at computeDefaults (utils.js:232)
    at eval (utils.js:256)
    at Array.reduce (<anonymous>)
    at computeDefaults (utils.js:253)
    at getDefaultFormState (utils.js:291)
    at Form.getStateFromProps (Form.js:178)
    at Form.componentWillReceiveProps (Form.js:160)
    at callComponentWillReceiveProps (react-dom.development.js:11826)
    at updateClassInstance (react-dom.development.js:12039)
    at updateClassComponent (react-dom.development.js:15071)
    at beginWork (react-dom.development.js:16064)
    at performUnitOfWork (react-dom.development.js:20084)
    at workLoop (react-dom.development.js:20125)
    at HTMLUnknownElement.callCallback (react-dom.development.js:147)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:196)
    at invokeGuardedCallback (react-dom.development.js:250)
    at replayUnitOfWork (react-dom.development.js:19308)
    at renderRoot (react-dom.development.js:20238)
    at performWorkOnRoot (react-dom.development.js:21162)
    at performWork (react-dom.development.js:21072)
    at performSyncWork (react-dom.development.js:21046)
    at interactiveUpdates$1 (react-dom.development.js:21331)
    at interactiveUpdates (react-dom.development.js:2268)
    at dispatchInteractiveEvent (react-dom.development.js:5086)
```

it would be nice if the form would continue to render ignoring the invalid property

**Comment by epicfaace** [comment]
@paintedbicycle @chinds185a Can you please give me playground links to the particular scenarios that caused confusing error messages?

**Comment by paintedbicycle** [comment]
Hi @epicfaace I'm sure there are other examples, but the exact one I came up against was [this](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJzaW1wbGUiOnsibmFtZSI6IlJhbmR5In0sImNvbmRpdGlvbmFsIjp7IkRvIHlvdSBoYXZlIGFueSBwZXRzPyI6Ik5vIn0sImFycmF5T2ZDb25kaXRpb25hbHMiOlt7IkRvIHlvdSBoYXZlIGFueSBwZXRzPyI6IlllczogT25lIiwiSG93IG9sZCBpcyB5b3VyIHBldD8iOjZ9LHsiRG8geW91IGhhdmUgYW55IHBldHM/IjoiWWVzOiBNb3JlIHRoYW4gb25lIiwiRG8geW91IHdhbnQgdG8gZ2V0IHJpZCBvZiBhbnk/IjpmYWxzZX1dLCJmaXhlZEFycmF5T2ZDb25kaXRpb25hbHMiOlt7IkRvIHlvdSBoYXZlIGFueSBwZXRzPyI6Ik5vIn0seyJEbyB5b3UgaGF2ZSBhbnkgcGV0cz8iOiJZZXM6IE9uZSIsIkhvdyBvbGQgaXMgeW91ciBwZXQ/Ijo2fSx7IkRvIHlvdSBoYXZlIGFueSBwZXRzPyI6IlllczogTW9yZSB0aGFuIG9uZSIsIkRvIHlvdSB3YW50IHRvIGdldCByaWQgb2YgYW55PyI6dHJ1ZX1dfSwic2NoZW1hIjp7InRpdGxlIjoiU2NoZW1hIGRlcGVuZGVuY2llcyIsImRlc2NyaXB0aW9uIjoiVGhlc2Ugc2FtcGxlcyBhcmUgYmVzdCB2aWV3ZWQgd2l0aG91dCBsaXZlIHZhbGlkYXRpb24uIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsic2ltcGxlIjp7InNyYyI6Imh0dHBzOi8vc3BhY2V0ZWxlc2NvcGUuZ2l0aHViLmlvL3VuZGVyc3RhbmRpbmctanNvbi1zY2hlbWEvcmVmZXJlbmNlL29iamVjdC5odG1sI2RlcGVuZGVuY2llcyIsInRpdGxlIjoiU2ltcGxlIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsibmFtZSI6eyJ0eXBlIjoic3RyaW5nIn0sImNyZWRpdF9jYXJkIjp7InR5cGUiOiJudW1iZXIifX0sInJlcXVpcmVkIjpbIm5hbWUiXSwiZGVwZW5kZW5jaWVzIjp7ImNyZWRpdF9jYXJkIjp7InByb3BlcnRpZXMiOnsiYmlsbGluZ19hZGRyZXNzIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbImJpbGxpbmdfYWRkcmVzcyJdfX19LCJjb25kaXRpb25hbCI6eyJ0aXRsZSI6IkNvbmRpdGlvbmFsIiwiJHJlZiI6IiMvZGVmaW5pdGlvbnMvcGVyc29uIn0sImFycmF5T2ZDb25kaXRpb25hbHMiOnsidGl0bGUiOiJBcnJheSBvZiBjb25kaXRpb25hbHMiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9wZXJzb24ifX0sImZpeGVkQXJyYXlPZkNvbmRpdGlvbmFscyI6eyJ0aXRsZSI6IkZpeGVkIGFycmF5IG9mIGNvbmRpdGlvbmFscyIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjpbeyJ0aXRsZSI6IlByaW1hcnkgcGVyc29uIiwiJHJlZiI6IiMvZGVmaW5pdGlvbnMvcGVyc29uIn1dLCJhZGRpdGlvbmFsSXRlbXMiOnsidGl0bGUiOiJBZGRpdGlvbmFsIHBlcnNvbiIsIiRyZWYiOiIjL2RlZmluaXRpb25zL3BlcnNvbiJ9fX0sImRlZmluaXRpb25zIjp7InBlcnNvbiI6eyJ0aXRsZSI6IlBlcnNvbiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7IkRvIHlvdSBoYXZlIGFueSBwZXRzPyI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJObyIsIlllczogT25lIiwiWWVzOiBNb3JlIHRoYW4gb25lIl0sImRlZmF1bHQiOiJObyJ9fSwicmVxdWlyZWQiOlsiRG8geW91IGhhdmUgYW55IHBldHM/Il0sImRlcGVuZGVuY2llcyI6eyJEbyB5b3UgaGF2ZSBhbnkgcGV0cz8iOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsiRG8geW91IGhhdmUgYW55IHBldHM/Ijp7ImVudW0iOlsiTm8iXX19fSx7InByb3BlcnRpZXMiOnsiRG8geW91IGhhdmUgYW55IHBldHM/Ijp7ImVudW0iOlsiWWVzOiBPbmUiXX0sIkhvdyBvbGQgaXMgeW91ciBwZXQ/Ijp7InR5cGUiOiJudW1iZXIifX0sInJlcXVpcmVkIjpbIkhvdyBvbGQgaXMgeW91ciBwZXQ/Il19LHsicHJvcGVydGllcyI6eyJEbyB5b3VyIGhhdmUgYW55IHBldHM/Ijp7ImVudW0iOlsiWWVzOiBNb3JlIHRoYW4gb25lIl19LCJEbyB5b3Ugd2FudCB0byBnZXQgcmlkIG9mIGFueT8iOnsidHlwZSI6ImJvb2xlYW4ifX0sInJlcXVpcmVkIjpbIkRvIHlvdSB3YW50IHRvIGdldCByaWQgb2YgYW55PyJdfV19fX19fSwidWlTY2hlbWEiOnsic2ltcGxlIjp7ImNyZWRpdF9jYXJkIjp7InVpOmhlbHAiOiJJZiB5b3UgZW50ZXIgYW55dGhpbmcgaGVyZSB0aGVuIGJpbGxpbmdfYWRkcmVzcyB3aWxsIGJlIGR5bmFtaWNhbGx5IGFkZGVkIHRvIHRoZSBmb3JtLiJ9fSwiY29uZGl0aW9uYWwiOnsiRG8geW91IHdhbnQgdG8gZ2V0IHJpZCBvZiBhbnk/Ijp7InVpOndpZGdldCI6InJhZGlvIn19LCJhcnJheU9mQ29uZGl0aW9uYWxzIjp7Iml0ZW1zIjp7IkRvIHlvdSB3YW50IHRvIGdldCByaWQgb2YgYW55PyI6eyJ1aTp3aWRnZXQiOiJyYWRpbyJ9fX0sImZpeGVkQXJyYXlPZkNvbmRpdGlvbmFscyI6eyJpdGVtcyI6eyJEbyB5b3Ugd2FudCB0byBnZXQgcmlkIG9mIGFueT8iOnsidWk6d2lkZ2V0IjoicmFkaW8ifX0sImFkZGl0aW9uYWxJdGVtcyI6eyJEbyB5b3Ugd2FudCB0byBnZXQgcmlkIG9mIGFueT8iOnsidWk6d2lkZ2V0IjoicmFkaW8ifX19fX0=)

Inside the the `person` ref, I simply changed:

```
              "properties": {
                "Do you have any pets?": {
                  "enum": [
                    "Yes: More than one"
                  ]
                },
```
to
```
              "properties": {
                "Do **your** have any pets?": {
                  "enum": [
                    "Yes: More than one"
                  ]
                },
```

If you open the console, you'll see:

> ignoring oneOf in dependencies because there isn't exactly one subschema that is valid

**Comment by epicfaace** [comment]
Makes sense, thanks for the report.

Code pointer is here: https://github.com/mozilla-services/react-jsonschema-form/blob/d9bcf1acfa3fd15814654129054b3c65501f5271/src/utils.js#L607

@paintedbicycle would you have the bandwidth to submit a PR improving the warning message here?

**Comment by paintedbicycle** [comment]
@epicfaace Ok, you can reference https://github.com/mozilla-services/react-jsonschema-form/pull/1224

I tried to do a very small change here, but it might be beneficial to update other warnings around the  lib. But I don't know the code well enough.
