### ISSUE TITLE
Enhancement: Allow MultiSelect to render CheckBoxWidget.

### ISSUE THREAD

**Issue by bockelie93** [rjsf-team/react-jsonschema-form#1193]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

For all cases so far, I would rather render the CheckBoxesWidget than the SelectWidget for when I have to choose multiple values in an array. It's tedious having to update each UiSchema, so I would rather want to override the widget for MutliSelect.

### Steps to Reproduce

1. https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/utils.js#L52
2. Change "SelectWidget" to "CheckboxesWidget"
3. Multi Select will now render the CheckBoxesWidget.

### Suggestion
Add a new Widget type, i.e. "MultiSelectWidget", which defaults to SelectWidget. Line 52 from earlier would then be select: "MultiSelectWidget". 

You can then customize MultiSelectWidet to use the CheckBoxESWidget.

### Version
1.2.1

**Comment by epicfaace** [comment]
That sounds good! Feel free to make a PR implementing this.
