### ISSUE TITLE
Support for styles (in addition to className)

### ISSUE THREAD

**Issue by justtonytone** [rjsf-team/react-jsonschema-form#1200]
Are there any issues/objections for adding support for `styles` in addition to `className` here https://github.com/mozilla-services/react-jsonschema-form/blob/aebfab9baa94d35176b7197ecf080e2fc1258dcf/src/components/fields/SchemaField.js#L143 ?

**Comment by epicfaace** [comment]
I don't think so -- maybe it should be called `style` and accept an object, just like in React. Feel free to make a PR!

**Comment by justtonytone** [comment]
thanks @epicfaace, i've included a pr here: https://github.com/mozilla-services/react-jsonschema-form/pull/1256
