### ISSUE TITLE
Constructor onChange breaks container components that sync state with onChange

### ISSUE THREAD

**Issue by pushred** [rjsf-team/react-jsonschema-form#1201]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

https://github.com/mozilla-services/react-jsonschema-form/pull/1034 introduced a breaking change for a case of mine that involves an external container/wrapper component that has state including `formData` synchronized via the onChange handler. I haven't updated my fork in awhile but in doing so I encountered this error across many instances of this container:

> Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`

Example: https://codepen.io/pushred/pen/pYgJbq?editors=0011#0

### Steps to Reproduce

1. Mount container component with onChange wired to setState
2. Observe console error

#### Expected behavior

I'm expecting onChange to be called only on changes, not on mount. I understand that this call is conditioned on a change between the initial react-jsonschema-form state and what's passed as a prop. But for that to apply seems to require providing an initial data object that matches the schema / react-jsonschema initial state. An empty or undefined object doesn't work.

I think this conflicts with [some examples out there](https://react-jsonschema-form.readthedocs.io/en/latest/#usage) and definitely with my real world usage in creating new records or dealing with resources that provide incomplete data.

I will workaround this in my fork by simply removing the feature but wanted to document what I ran into. I think [the root decision](https://github.com/mozilla-services/react-jsonschema-form/pull/1034#issuecomment-424849836) was incorrect as an external setState is a reasonable side effect of an event handler, especially onChange. I think componentDidMount should be reconsidered as the appropriate lifecycle method.

#### Actual behavior

:boom:

### Version

1.2.1

**Comment by epicfaace** [comment]
That makes sense @pushred , thanks for the report. Is there a way to make onChange called only on componentDidMount but also still keep #1033 from resurfacing?

**Comment by CodeGains** [comment]
Ran into this problem too. Instead of calling `onChange` when it mounts, which is behavior that users would not expect, would it suffice to just recalculate the state in `onSubmit` like in `onChange`, call `setState`, and then return the new state in `onSubmit`?

**Comment by timothyallan** [comment]
I'm making a form designer which animates a "save" button when the user has made changes to their form. Depending on the formData I pass in initially (i.e. if they are editing an existing form), onChange() can be triggered internally by the Form itself, which of course triggers my animation! 

Even if we could know if it was the user, or an internal function that called onChange(), we could repsond accordingly and make life so much easier.

**Comment by epicfaace** [comment]
@pushred since you have already changed this in your fork, would you mind making a PR with those changes to `master` so we could release it on v2?
