### ISSUE TITLE
Use Object Field Template with additionalProperties

### ISSUE THREAD

**Issue by YingXue** [rjsf-team/react-jsonschema-form#1230]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I am playing with Object Field Template, trying to customize the titles and descriptions etc. 
My schema includes additionalProperties. However there is no 'onAddClick' props like the Array Field Template does, so I am losing my 'Add' button if I overwrite the Object Field Template.

### Steps to Reproduce

1. [First Step]
Defined my schema using additionalProperties
2. [Second Step]
The following is my code to overwrite Object Field Template
```
import {
    IconButton,
} from 'office-ui-fabric-react';
import * as React from 'react';
import { ObjectFieldTemplateProps } from 'react-jsonschema-form';

export const ObjectTemplate = (props: ObjectFieldTemplateProps) => {
    return (
        <div key={props.title}>
            <div style={{ fontSize: '14px'}}>
                {props.title} (we can make the title collapsible later)
            </div>
            <div style={{ fontSize: '14px', fontStyle: 'italic', marginLeft: '4px'}}>
                {props.description}
            </div>
            {props.properties.map((element, index) =>
                <div key={index} style={{ marginLeft: '25px'}} >{element.content}</div>
            )}
            {props.schema.additionalProperties &&
                (
                    <IconButton
                      onClick={props.onAddClick(props.schema)} // !! there is no onAddClick props available
                    />
                )
            }
        </div>
    );
};
```
where props.onAddClick doesn't exist yet

If I don't overwrite the originally expandable block
```      
{canExpand() && (
        <AddButton
          className="object-property-expand"
          onClick={props.onAddClick(props.schema)}
          disabled={props.disabled || props.readonly}
        />
)}
```
I would lose the add button as shown in the following screenshot:
![image](https://user-images.githubusercontent.com/5489222/54855046-144d2300-4cb2-11e9-88da-e04a318b0253.png)

3. A side note, as you can see from the screenshot, I have used customized widgets (for example the additional property). However the key input box is not using customed widgets for some reason, is it currently not supported?

#### Expected behavior

The ability to overwrite the originally canExpand() block

#### Actual behavior

Not able to or I couldn't find the right way. Can anyone help sharing some ideas here?

### Version

1.3.0

**Comment by epicfaace** [comment]
Hi @YingXue , could you make a sample JSFiddle with the exact schema and objectfieldtemplate you are using? That will help us to get to the problem faster.

**Comment by epicfaace** [comment]
Oh, I see -- this issue is that an ObjectFieldTemplate should have an onAddClick prop, in the case that there are additionalProperties defined for the object. This is definitely something that would be nice to have, but we don't have it yet in rjsf.

**Comment by ValYouW** [comment]
@epicfaace I think this issue is solved, writing custom `ObjectFieldTemplate` I do get an `onAddClick` prop... Where it's missing is from the documentation and [index.d.ts](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/index.d.ts#L202) also missing are `disabled` and `readonly`.

**Comment by epicfaace** [comment]
thanks for looking into this @ValYouW -- do you mind adding a PR to update the documentation and typings accordingly?

**Comment by ValYouW** [comment]
@epicfaace PR-1979
