### ISSUE TITLE
type is undefined but have allOf 

### ISSUE THREAD

**Issue by joneldiablo** [rjsf-team/react-jsonschema-form#1237]
Hi, I have a very long jsonschema which I want see as form.
Using the live demo, have this error:

![image](https://user-images.githubusercontent.com/13206502/55036267-b4bb8400-4fdf-11e9-8d0d-b69608434b11.png)

doing some test using the live demo, I found that if type is not declared, throw the error, its possible use allOf without type?

**Comment by epicfaace** [comment]
@joneldiablo 
Can you please send a playground link demonstrating this issue? https://mozilla-services.github.io/react-jsonschema-form/

**Comment by joneldiablo** [comment]
https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJuZXdSZWxlYXNlTWVzc2FnZSI6e319LCJzY2hlbWEiOnsidGl0bGUiOiJDcmVhdGUgbmV3IHJlbGVhc2UgbWVzc2FnZSIsImRlc2NyaXB0aW9uIjoiZGRleCB2My44LjIiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJuZXdSZWxlYXNlTWVzc2FnZSI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9OZXdSZWxlYXNlTWVzc2FnZSJ9fSwiZGVmaW5pdGlvbnMiOnsiTmV3UmVsZWFzZU1lc3NhZ2UiOnsidHlwZSI6Im9iamVjdCIsInRpdGxlIjoiTmV3UmVsZWFzZU1lc3NhZ2UiLCJyZXF1aXJlZCI6WyJtZXNzYWdlSGVhZGVyIiwicmVzb3VyY2VMaXN0IiwicmVsZWFzZUxpc3QiLCJtZXNzYWdlU2NoZW1hVmVyc2lvbklkIl0sInByb3BlcnRpZXMiOnsibWVzc2FnZUhlYWRlciI6eyJ0aXRsZSI6Im1lc3NhZ2VIZWFkZXIiLCJhbGxPZiI6W3siJHJlZiI6IiMvZGVmaW5pdGlvbnMvTWVzc2FnZUhlYWRlciJ9XSwicHJvcGVydHlUeXBlIjoiZWxlbWVudCIsImVsZW1lbnROYW1lIjp7ImxvY2FsUGFydCI6Ik1lc3NhZ2VIZWFkZXIiLCJuYW1lc3BhY2VVUkkiOiIifX0sInVwZGF0ZUluZGljYXRvciI6eyJ0aXRsZSI6InVwZGF0ZUluZGljYXRvciIsImFsbE9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9VcGRhdGVJbmRpY2F0b3IifV0sInByb3BlcnR5VHlwZSI6ImVsZW1lbnQiLCJlbGVtZW50TmFtZSI6eyJsb2NhbFBhcnQiOiJVcGRhdGVJbmRpY2F0b3IiLCJuYW1lc3BhY2VVUkkiOiIifX0sImlzQmFja2ZpbGwiOnsidGl0bGUiOiJpc0JhY2tmaWxsIiwiYWxsT2YiOlt7IiRyZWYiOiJodHRwOi8vd3d3Lmpzb25peC5vcmcvanNvbnNjaGVtYXMvdzNjLzIwMDEvWE1MU2NoZW1hLmpzb25zY2hlbWEjL2RlZmluaXRpb25zL2Jvb2xlYW4ifV0sInByb3BlcnR5VHlwZSI6ImVsZW1lbnQiLCJlbGVtZW50TmFtZSI6eyJsb2NhbFBhcnQiOiJJc0JhY2tmaWxsIiwibmFtZXNwYWNlVVJJIjoiIn19LCJjYXRhbG9nVHJhbnNmZXIiOnsidGl0bGUiOiJjYXRhbG9nVHJhbnNmZXIiLCJhbGxPZiI6W3siJHJlZiI6IiMvZGVmaW5pdGlvbnMvQ2F0YWxvZ1RyYW5zZmVyIn1dLCJwcm9wZXJ0eVR5cGUiOiJlbGVtZW50IiwiZWxlbWVudE5hbWUiOnsibG9jYWxQYXJ0IjoiQ2F0YWxvZ1RyYW5zZmVyIiwibmFtZXNwYWNlVVJJIjoiIn19LCJ3b3JrTGlzdCI6eyJ0aXRsZSI6IndvcmtMaXN0IiwiYWxsT2YiOlt7IiRyZWYiOiIjL2RlZmluaXRpb25zL1dvcmtMaXN0In1dLCJwcm9wZXJ0eVR5cGUiOiJlbGVtZW50IiwiZWxlbWVudE5hbWUiOnsibG9jYWxQYXJ0IjoiV29ya0xpc3QiLCJuYW1lc3BhY2VVUkkiOiIifX0sImN1ZVNoZWV0TGlzdCI6eyJ0aXRsZSI6ImN1ZVNoZWV0TGlzdCIsImFsbE9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9DdWVTaGVldExpc3QifV0sInByb3BlcnR5VHlwZSI6ImVsZW1lbnQiLCJlbGVtZW50TmFtZSI6eyJsb2NhbFBhcnQiOiJDdWVTaGVldExpc3QiLCJuYW1lc3BhY2VVUkkiOiIifX0sInJlc291cmNlTGlzdCI6eyJ0aXRsZSI6InJlc291cmNlTGlzdCIsImFsbE9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9SZXNvdXJjZUxpc3QifV0sInByb3BlcnR5VHlwZSI6ImVsZW1lbnQiLCJlbGVtZW50TmFtZSI6eyJsb2NhbFBhcnQiOiJSZXNvdXJjZUxpc3QiLCJuYW1lc3BhY2VVUkkiOiIifX0sImNvbGxlY3Rpb25MaXN0Ijp7InRpdGxlIjoiY29sbGVjdGlvbkxpc3QiLCJhbGxPZiI6W3siJHJlZiI6IiMvZGVmaW5pdGlvbnMvQ29sbGVjdGlvbkxpc3QifV0sInByb3BlcnR5VHlwZSI6ImVsZW1lbnQiLCJlbGVtZW50TmFtZSI6eyJsb2NhbFBhcnQiOiJDb2xsZWN0aW9uTGlzdCIsIm5hbWVzcGFjZVVSSSI6IiJ9fSwicmVsZWFzZUxpc3QiOnsidGl0bGUiOiJyZWxlYXNlTGlzdCIsImFsbE9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9SZWxlYXNlTGlzdCJ9XSwicHJvcGVydHlUeXBlIjoiZWxlbWVudCIsImVsZW1lbnROYW1lIjp7ImxvY2FsUGFydCI6IlJlbGVhc2VMaXN0IiwibmFtZXNwYWNlVVJJIjoiIn19LCJkZWFsTGlzdCI6eyJ0aXRsZSI6ImRlYWxMaXN0IiwiYWxsT2YiOlt7IiRyZWYiOiIjL2RlZmluaXRpb25zL0RlYWxMaXN0In1dLCJwcm9wZXJ0eVR5cGUiOiJlbGVtZW50IiwiZWxlbWVudE5hbWUiOnsibG9jYWxQYXJ0IjoiRGVhbExpc3QiLCJuYW1lc3BhY2VVUkkiOiIifX0sIm1lc3NhZ2VTY2hlbWFWZXJzaW9uSWQiOnsidGl0bGUiOiJtZXNzYWdlU2NoZW1hVmVyc2lvbklkIiwiYWxsT2YiOlt7IiRyZWYiOiJodHRwOi8vd3d3Lmpzb25peC5vcmcvanNvbnNjaGVtYXMvdzNjLzIwMDEvWE1MU2NoZW1hLmpzb25zY2hlbWEjL2RlZmluaXRpb25zL3N0cmluZyJ9XSwicHJvcGVydHlUeXBlIjoiYXR0cmlidXRlIiwiYXR0cmlidXRlTmFtZSI6eyJsb2NhbFBhcnQiOiJNZXNzYWdlU2NoZW1hVmVyc2lvbklkIiwibmFtZXNwYWNlVVJJIjoiIn19LCJidXNpbmVzc1Byb2ZpbGVWZXJzaW9uSWQiOnsidGl0bGUiOiJidXNpbmVzc1Byb2ZpbGVWZXJzaW9uSWQiLCJhbGxPZiI6W3siJHJlZiI6Imh0dHA6Ly93d3cuanNvbml4Lm9yZy9qc29uc2NoZW1hcy93M2MvMjAwMS9YTUxTY2hlbWEuanNvbnNjaGVtYSMvZGVmaW5pdGlvbnMvc3RyaW5nIn1dLCJwcm9wZXJ0eVR5cGUiOiJhdHRyaWJ1dGUiLCJhdHRyaWJ1dGVOYW1lIjp7ImxvY2FsUGFydCI6IkJ1c2luZXNzUHJvZmlsZVZlcnNpb25JZCIsIm5hbWVzcGFjZVVSSSI6IiJ9fSwicmVsZWFzZVByb2ZpbGVWZXJzaW9uSWQiOnsidGl0bGUiOiJyZWxlYXNlUHJvZmlsZVZlcnNpb25JZCIsImFsbE9mIjpbeyIkcmVmIjoiaHR0cDovL3d3dy5qc29uaXgub3JnL2pzb25zY2hlbWFzL3czYy8yMDAxL1hNTFNjaGVtYS5qc29uc2NoZW1hIy9kZWZpbml0aW9ucy9zdHJpbmcifV0sInByb3BlcnR5VHlwZSI6ImF0dHJpYnV0ZSIsImF0dHJpYnV0ZU5hbWUiOnsibG9jYWxQYXJ0IjoiUmVsZWFzZVByb2ZpbGVWZXJzaW9uSWQiLCJuYW1lc3BhY2VVUkkiOiIifX0sImxhbmd1YWdlQW5kU2NyaXB0Q29kZSI6eyJ0aXRsZSI6Imxhbmd1YWdlQW5kU2NyaXB0Q29kZSIsImFsbE9mIjpbeyIkcmVmIjoiaHR0cDovL3d3dy5qc29uaXgub3JnL2pzb25zY2hlbWFzL3czYy8yMDAxL1hNTFNjaGVtYS5qc29uc2NoZW1hIy9kZWZpbml0aW9ucy9zdHJpbmcifV0sInByb3BlcnR5VHlwZSI6ImF0dHJpYnV0ZSIsImF0dHJpYnV0ZU5hbWUiOnsibG9jYWxQYXJ0IjoiTGFuZ3VhZ2VBbmRTY3JpcHRDb2RlIiwibmFtZXNwYWNlVVJJIjoiIn19fSwidHlwZVR5cGUiOiJjbGFzc0luZm8iLCJwcm9wZXJ0aWVzT3JkZXIiOlsibWVzc2FnZUhlYWRlciIsInVwZGF0ZUluZGljYXRvciIsImlzQmFja2ZpbGwiLCJjYXRhbG9nVHJhbnNmZXIiLCJ3b3JrTGlzdCIsImN1ZVNoZWV0TGlzdCIsInJlc291cmNlTGlzdCIsImNvbGxlY3Rpb25MaXN0IiwicmVsZWFzZUxpc3QiLCJkZWFsTGlzdCIsIm1lc3NhZ2VTY2hlbWFWZXJzaW9uSWQiLCJidXNpbmVzc1Byb2ZpbGVWZXJzaW9uSWQiLCJyZWxlYXNlUHJvZmlsZVZlcnNpb25JZCIsImxhbmd1YWdlQW5kU2NyaXB0Q29kZSJdfSwiTWVzc2FnZUhlYWRlciI6eyJ0eXBlIjoib2JqZWN0IiwidGl0bGUiOiJNZXNzYWdlSGVhZGVyIiwicmVxdWlyZWQiOlsibWVzc2FnZUlkIiwibWVzc2FnZVNlbmRlciIsIm1lc3NhZ2VSZWNpcGllbnQiLCJtZXNzYWdlQ3JlYXRlZERhdGVUaW1lIl0sInByb3BlcnRpZXMiOnsibWVzc2FnZVRocmVhZElkIjp7InRpdGxlIjoibWVzc2FnZVRocmVhZElkIiwiYWxsT2YiOlt7IiRyZWYiOiJodHRwOi8vd3d3Lmpzb25peC5vcmcvanNvbnNjaGVtYXMvdzNjLzIwMDEvWE1MU2NoZW1hLmpzb25zY2hlbWEjL2RlZmluaXRpb25zL3N0cmluZyJ9XSwicHJvcGVydHlUeXBlIjoiZWxlbWVudCIsImVsZW1lbnROYW1lIjp7ImxvY2FsUGFydCI6Ik1lc3NhZ2VUaHJlYWRJZCIsIm5hbWVzcGFjZVVSSSI6IiJ9fSwibWVzc2FnZUlkIjp7InRpdGxlIjoibWVzc2FnZUlkIiwiYWxsT2YiOlt7IiRyZWYiOiJodHRwOi8vd3d3Lmpzb25peC5vcmcvanNvbnNjaGVtYXMvdzNjLzIwMDEvWE1MU2NoZW1hLmpzb25zY2hlbWEjL2RlZmluaXRpb25zL3N0cmluZyJ9XSwicHJvcGVydHlUeXBlIjoiZWxlbWVudCIsImVsZW1lbnROYW1lIjp7ImxvY2FsUGFydCI6Ik1lc3NhZ2VJZCIsIm5hbWVzcGFjZVVSSSI6IiJ9fSwibWVzc2FnZUZpbGVOYW1lIjp7InRpdGxlIjoibWVzc2FnZUZpbGVOYW1lIiwiYWxsT2YiOlt7IiRyZWYiOiJodHRwOi8vd3d3Lmpzb25peC5vcmcvanNvbnNjaGVtYXMvdzNjLzIwMDEvWE1MU2NoZW1hLmpzb25zY2hlbWEjL2RlZmluaXRpb25zL3N0cmluZyJ9XSwicHJvcGVydHlUeXBlIjoiZWxlbWVudCIsImVsZW1lbnROYW1lIjp7ImxvY2FsUGFydCI6Ik1lc3NhZ2VGaWxlTmFtZSIsIm5hbWVzcGFjZVVSSSI6IiJ9fSwibWVzc2FnZVNlbmRlciI6eyJ0aXRsZSI6Im1lc3NhZ2VTZW5kZXIiLCJhbGxPZiI6W3siJHJlZiI6IiMvZGVmaW5pdGlvbnMvTWVzc2FnaW5nUGFydHkifV0sInByb3BlcnR5VHlwZSI6ImVsZW1lbnQiLCJlbGVtZW50TmFtZSI6eyJsb2NhbFBhcnQiOiJNZXNzYWdlU2VuZGVyIiwibmFtZXNwYWNlVVJJIjoiIn19LCJzZW50T25CZWhhbGZPZiI6eyJ0aXRsZSI6InNlbnRPbkJlaGFsZk9mIiwiYWxsT2YiOlt7IiRyZWYiOiIjL2RlZmluaXRpb25zL01lc3NhZ2luZ1BhcnR5In1dLCJwcm9wZXJ0eVR5cGUiOiJlbGVtZW50IiwiZWxlbWVudE5hbWUiOnsibG9jYWxQYXJ0IjoiU2VudE9uQmVoYWxmT2YiLCJuYW1lc3BhY2VVUkkiOiIifX0sIm1lc3NhZ2VSZWNpcGllbnQiOnsidGl0bGUiOiJtZXNzYWdlUmVjaXBpZW50IiwiYWxsT2YiOlt7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL01lc3NhZ2luZ1BhcnR5In0sIm1pbkl0ZW1zIjoxfV0sInByb3BlcnR5VHlwZSI6ImVsZW1lbnQiLCJlbGVtZW50TmFtZSI6eyJsb2NhbFBhcnQiOiJNZXNzYWdlUmVjaXBpZW50IiwibmFtZXNwYWNlVVJJIjoiIn19LCJtZXNzYWdlQ3JlYXRlZERhdGVUaW1lIjp7InRpdGxlIjoibWVzc2FnZUNyZWF0ZWREYXRlVGltZSIsImFsbE9mIjpbeyIkcmVmIjoiaHR0cDovL3d3dy5qc29uaXgub3JnL2pzb25zY2hlbWFzL3czYy8yMDAxL1hNTFNjaGVtYS5qc29uc2NoZW1hIy9kZWZpbml0aW9ucy9kYXRlVGltZSJ9XSwicHJvcGVydHlUeXBlIjoiZWxlbWVudCIsImVsZW1lbnROYW1lIjp7ImxvY2FsUGFydCI6Ik1lc3NhZ2VDcmVhdGVkRGF0ZVRpbWUiLCJuYW1lc3BhY2VVUkkiOiIifX0sIm1lc3NhZ2VBdWRpdFRyYWlsIjp7InRpdGxlIjoibWVzc2FnZUF1ZGl0VHJhaWwiLCJhbGxPZiI6W3siJHJlZiI6IiMvZGVmaW5pdGlvbnMvTWVzc2FnZUF1ZGl0VHJhaWwifV0sInByb3BlcnR5VHlwZSI6ImVsZW1lbnQiLCJlbGVtZW50TmFtZSI6eyJsb2NhbFBhcnQiOiJNZXNzYWdlQXVkaXRUcmFpbCIsIm5hbWVzcGFjZVVSSSI6IiJ9fSwiY29tbWVudCI6eyJ0aXRsZSI6ImNvbW1lbnQiLCJhbGxPZiI6W3siJHJlZiI6IiMvZGVmaW5pdGlvbnMvQ29tbWVudCJ9XSwicHJvcGVydHlUeXBlIjoiZWxlbWVudCIsImVsZW1lbnROYW1lIjp7ImxvY2FsUGFydCI6IkNvbW1lbnQiLCJuYW1lc3BhY2VVUkkiOiIifX0sIm1lc3NhZ2VDb250cm9sVHlwZSI6eyJ0aXRsZSI6Im1lc3NhZ2VDb250cm9sVHlwZSIsImFsbE9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9NZXNzYWdlQ29udHJvbFR5cGUifV0sInByb3BlcnR5VHlwZSI6ImVsZW1lbnQiLCJlbGVtZW50TmFtZSI6eyJsb2NhbFBhcnQiOiJNZXNzYWdlQ29udHJvbFR5cGUiLCJuYW1lc3BhY2VVUkkiOiIifX0sImxhbmd1YWdlQW5kU2NyaXB0Q29kZSI6eyJ0aXRsZSI6Imxhbmd1YWdlQW5kU2NyaXB0Q29kZSIsImFsbE9mIjpbeyIkcmVmIjoiaHR0cDovL3d3dy5qc29uaXgub3JnL2pzb25zY2hlbWFzL3czYy8yMDAxL1hNTFNjaGVtYS5qc29uc2NoZW1hIy9kZWZpbml0aW9ucy9zdHJpbmcifV0sInByb3BlcnR5VHlwZSI6ImF0dHJpYnV0ZSIsImF0dHJpYnV0ZU5hbWUiOnsibG9jYWxQYXJ0IjoiTGFuZ3VhZ2VBbmRTY3JpcHRDb2RlIiwibmFtZXNwYWNlVVJJIjoiIn19fSwidHlwZVR5cGUiOiJjbGFzc0luZm8iLCJ0eXBlTmFtZSI6eyJsb2NhbFBhcnQiOiJNZXNzYWdlSGVhZGVyIiwibmFtZXNwYWNlVVJJIjoiaHR0cDovL2RkZXgubmV0L3htbC9lcm4vMzgyIn0sInByb3BlcnRpZXNPcmRlciI6WyJtZXNzYWdlVGhyZWFkSWQiLCJtZXNzYWdlSWQiLCJtZXNzYWdlRmlsZU5hbWUiLCJtZXNzYWdlU2VuZGVyIiwic2VudE9uQmVoYWxmT2YiLCJtZXNzYWdlUmVjaXBpZW50IiwibWVzc2FnZUNyZWF0ZWREYXRlVGltZSIsIm1lc3NhZ2VBdWRpdFRyYWlsIiwiY29tbWVudCIsIm1lc3NhZ2VDb250cm9sVHlwZSIsImxhbmd1YWdlQW5kU2NyaXB0Q29kZSJdfX19LCJ1aVNjaGVtYSI6e319

**Comment by joneldiablo** [comment]
I had to eliminate many definitions because the url was very long,   I leave the NewReleaseMessage and MessageHeader definitions, so just the first error have sense

**Comment by travisdahl** [comment]
running into the same problem, it looks like `allOf` isnt supported yet...
https://github.com/mozilla-services/react-jsonschema-form/issues/52

**Comment by joneldiablo** [comment]
checking anyOf and allOf, the same error is thrown when _type_ its not declared in the property element, I think the solution is take the _type_ from the $ref or from the object in array anyOf or allOf to validate the type.  check this other example:
https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6IkNyZWF0ZSBuZXcgcmVsZWFzZSBtZXNzYWdlIiwiZGVzY3JpcHRpb24iOiJkZGV4IHYzLjguMiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im5ld1JlbGVhc2VNZXNzYWdlIjp7InR5cGUiOiJvYmplY3QiLCJhbnlPZiI6W3siJHJlZiI6IiMvZGVmaW5pdGlvbnMvYSJ9LHsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvYiJ9XX19LCJkZWZpbml0aW9ucyI6eyJhIjp7InRpdGxlIjoidGhlIEEgb3B0IiwidHlwZSI6InN0cmluZyJ9LCJiIjp7InRpdGxlIjoidGhlIEIgb3B0IiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsieSI6eyJ0aXRsZSI6InRoZSBZIiwidHlwZSI6InN0cmluZyJ9fX19fSwidWlTY2hlbWEiOnt9fQ==

**Comment by travisdahl** [comment]
> simplified:
> https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJuZXdSZWxlYXNlTWVzc2FnZSI6NX0sInNjaGVtYSI6eyJ0aXRsZSI6IkNyZWF0ZSBuZXcgcmVsZWFzZSBtZXNzYWdlIiwiZGVzY3JpcHRpb24iOiJkZGV4IHYzLjguMiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im5ld1JlbGVhc2VNZXNzYWdlIjp7ImFsbE9mIjpbeyJ0eXBlIjoibnVtYmVyIn0seyJ0eXBlIjoiaW50ZWdlciJ9XX19fSwidWlTY2hlbWEiOnt9fQ==

not sure what you expected in the first `allOf` example. Why would you create something and define 2 different types? or are you just expecting it to cascade and use the last type defined?

In any case `allOf` doest work even if you have a single val....

https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJuZXdSZWxlYXNlTWVzc2FnZSI6NX0sInNjaGVtYSI6eyJ0aXRsZSI6IkNyZWF0ZSBuZXcgcmVsZWFzZSBtZXNzYWdlIiwiZGVzY3JpcHRpb24iOiJkZGV4IHYzLjguMiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im5ld1JlbGVhc2VNZXNzYWdlIjp7ImFsbE9mIjpbeyJ0eXBlIjoibnVtYmVyIn1dfX19LCJ1aVNjaGVtYSI6e319

**Comment by travisdahl** [comment]
I was able to work around the current limitations with a couple extra libraries.First I resolve all the refs then I merge all the `allOf`...

```
import deref from 'json-schema-deref-sync';
import mergeAllOf from 'json-schema-merge-allof';
...
const resolvedSchema = deref(schema);
const mergedSchema = mergeAllOf(resolvedSchema);
export default mergedSchema;
```

not ideal, but could get you by in a pinch and easy enough to remove once these issues are resolved.
