### ISSUE TITLE
Enable $data reference usage for AJV validation

### ISSUE THREAD

**Issue by nitishdhar** [rjsf-team/react-jsonschema-form#1255]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description
Looking at the docs for [AJV](https://github.com/epoberezkin/ajv#data-reference), it enables us to write validation rules using `$data` reference to an existing schema field's value, like 

```
var ajv = new Ajv({$data: true});

var schema = {
  "properties": {
    "smaller": {
      "type": "number",
      "maximum": { "$data": "1/larger" }
    },
    "larger": { "type": "number" }
  }
};

var validData = {
  smaller: 5,
  larger: 7
};

ajv.validate(schema, validData); // true
```

But the default [setup](https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/validate.js) for AJV in RJSF does not enable `$data=true`

Is this an opinionated design choice for some reason or we can somehow enable it. I couldn't find documentation that lets us override the AJV setup.

Having the `$data` reference will enable us to write more complex schema based validations.

Is this something you will be open to enabling or letting users override this option somehow?

Thanks

**Comment by epicfaace** [comment]
I'm open to enabling this! This library was initially created without AJV, so not all the possible features of AJV were enabled by default. Please make a PR and I'll take a look.

**Comment by nitishdhar** [comment]
Thanks. 

I will start working on a PR to enable `$data` reference.

Meanwhile, can you also share your thoughts on adding a new dependency to [ajv-keywords.](https://github.com/epoberezkin/ajv-keywords)

This will enable the proposed keywords `switch, patternRequired, formatMaximum / formatMinimum and formatExclusiveMaximum / formatExclusiveMinimum` from `JSON Schema extension proposals` allowing us to do format based comparisons during validation. e.g. Defining schema validation to validate if a date should be minimum of another date attribute in the schema - 

```
startDate: {
  type: "string",
  format: "date",
  title: "Start Date",
},
endDate: {
  type: "string",
  format: "date",
  title: "End Date",
  formatMinimum: {
    "$data": "1/startDate"
  }
}
```
If this makes sense, I will make this part of the PR.

**Comment by epicfaace** [comment]
Great, thanks!

> Meanwhile, can you also share your thoughts on adding a new dependency to [ajv-keywords.](https://github.com/epoberezkin/ajv-keywords)

Hmm, I'd be wary of adding in keywords that are not yet part of the JSON schema specification. For example, the ajv-keywords repository mentions that switch is deprecated and they suggest using if/then/else, which is part of the spec instead.

I'd be open to adding in functionality that is part of the JSON schema spec such as if/then/else (see #885 and #996), but otherwise it might take only a very good reason to add in additional keywords that are not part of the spec.

**Comment by epicfaace** [comment]
Actually, given that $data is not yet part of the JSON Schema spec (it's just a proposal as of now -- see #51), it might be better to wait until we see if and/or how it is incorporated into the JSON schema spec before implementing it in rjsf.

**Comment by charlysotelo** [comment]
I could use this feature pls

**Comment by epicfaace** [comment]
Closing this issue -- can reopen if https://github.com/json-schema-org/json-schema-spec/issues/51 is accepted

**Comment by zeddotes** [comment]
Hey, I've created a fix for this waiting to be approved by the team: https://github.com/rjsf-team/react-jsonschema-form/pull/1668
