### ISSUE TITLE
Allow default values to be ignored

### ISSUE THREAD

**Issue by fsteger** [rjsf-team/react-jsonschema-form#1271]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Feature request - introduce option to ignore default values for a form.
Use case - for new instances of the form, the default values should always be present. When loading previously saved form data, if a default is not present, the user intentionally removed the value, and therefore defaults should not be populated.

Adding a flag will allow users to decide if default values should be honored on a per-form-data basis, while still using a single schema that contains the defaults.

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by epicfaace** [comment]
Good idea -- what do you think this option might be called?

**Comment by fsteger** [comment]
ignoreDefaults

**Comment by epicfaace** [comment]
ignoreDefaults intuitively sounds like it might ignore default values for _all_ cases, though, even for a new submission.

**Comment by epicfaace** [comment]
Repro of this issue: https://jsfiddle.net/8dm6t3ns/

**Comment by fsteger** [comment]
Yes; I was leaning towards keeping it more generic. For my use case, I'd set it to true when setting up the form with existing formData, and false for new submissions (or omit as this would be the default).
Part of the struggle otherwise is coming up with a concise, descriptive name-- ignoreDefaultsForExistingFormData is a bit of a mouthful. And someone may have a need for the other case, which could lead to ignoreDefaultsForNewFormData.

**Comment by epicfaace** [comment]
@fsteger Could we make ignoreDefaults ignore defaults, unreservedly, for all cases?

Then to implement the behavior you wanted, you could do something like this:
```
<Form
    formData={formData}
    ignoreDefaults={!!formData}
/>
```

Not sure if this approach is more intuitive, though, so would like to hear your thoughts on this.

**Comment by fsteger** [comment]
After setting this down and coming back to it a few months later, I realize I had completely overlooked the array use cases.... In my case, any existing array data that comes in to the form via formData should _not_ have the defaults assigned. However, if the user adds new rows, then the new rows should be populated with the defaults.

So, I don't think one flag to unreservedly ignore will work after all. It would solve my use case, but I still haven't come up with a better name than "ignoreDefaultsForExistingFormData".

**Comment by fsteger** [comment]
I didn't realize that the library calculates and populates *every* default value on *every* change made by the user, which greatly complicates this. For instance, if a user adds a new row to an array, the library will plop in defaults for every other field. The same is true for dependent schemas; if the user changes the trigger field, the newly displayed fields should have their defaults populated, but the rest of the form should not. Unfortunately, the logic is really tightly coupled.

Does anyone have any suggestions here on how best to proceed with the implementation? I started down a couple different paths for a pull request already, and abandoned each due to the amount of refactoring or hacky logic that was being done just to separate out these concerns. I don't want to invest a significant amount of time in a wrong approach that's not going to be accepted back into the project, so some guidance here would be greatly appreciated.

**Comment by fsteger** [comment]
I think I've come up with a reasonable approach. Instead of ignoring the defaults outright, I ended up setting them to undefined initially, similar to how a user manually clearing a default is handled.

**Comment by FunkMonkey** [comment]
I am also looking forward to this feature.

Additionally, it would be nice to control this behaviour per property, e.g. by specifying it in the UISchema...
