### ISSUE TITLE
Requiring React 16

### ISSUE THREAD

**Issue by sbusch** [rjsf-team/react-jsonschema-form#1275]
I'm working on a PR on `react-jsonschema-form` for passing an Ajv instance from outside (allowing custom keywords etc.), and I need to use the Context API which has been introduced in [React 16.3](https://reactjs.org/blog/2018/03/29/react-v-16-3.html).

Even better would be availability of `contextType` for React class components, introduced in [React 16.6](https://reactjs.org/blog/2018/10/23/react-v-16-6.html).

Would you accept a PR which bumps up React version to 16.3, 16.6 or even current 16.8.6? and peerDependency to >= 16.3 or >= 16.6, respectively?

**Comment by epicfaace** [comment]
Would bumping up the React version cause incompatibility with earlier React versions?

**Comment by sbusch** [comment]
If we're using newer API features like Context API as intended, yes. But there's a workaround that doesn't require bumping up the React version:

In my case, I'll use [mini-create-react-context](https://github.com/StringEpsilon/mini-create-react-context) as a ponyfill. It supports React "^0.14.0 || ^15.0.0 || ^16.0.0" as its peer dependency. I think using that package is also perfectly acceptable for a PR (if I get to finish that).

Nevertheless, I would opt for dropping React 15 support [because of many subtleties changed](https://reactjs.org/blog/2017/09/26/react-v16.0.html), making support for both versions potentially tricky in case of bugs. React 16.0 has been released in September 2017.

But I don't know about the internal requirements of maintainers and Mozilla, and npm unfortunately [doesn't provide download stats per version](https://github.com/npm/download-counts/issues/6) or how many projects are still relying on React 15.

**Comment by sbusch** [comment]
Closed (for new), for #1286 I use the ponyfill mentioned above. Due to the lack of contextType support, the code is slightly more verbose than necessary, but I managed to restrict the changes in this regard, see `render/renderWithContext` wrapper for class-based components:

* original `render` renamed to `renderWithContext`
* new `render` is just a wrapper that gets the context and calls `renderWithContext` with it

**Comment by epicfaace** [comment]
It should probably be ok to upgrade to React 16, as you said anyway that it was released back in September 2017.

**Comment by v1vendi** [comment]
what about not upgrading to React 16, but at least migrate from componentWillReceiveProps, which is deprecated?

**Comment by epicfaace** [comment]
@v1vendi that would be nice -- we use it a bunch, so if you would like to refactor some of that usage and submit a PR, feel free to do so.

**Comment by epicfaace** [comment]
I've updated the peer dependency to 16, but would it be better to make it 16.3 or 16.6 as you suggested? I'm not sure if doing so would cause issues with upgrading (because not everyone may be on newer versions of React 16)

**Comment by sbusch** [comment]
I would choose the latest 16.x (16.9 for now) so we can use context, contextType and hooks in RJSF.

And React is in my experience very compatible, never had any problems upgrading 16.x releases, so every project using RJSF may have problems updating React 15.x to 16.x but whether 16.0, 16.6 or 16.9 shouldn't matter.

Just my 2ct

**Comment by epicfaace** [comment]
Good point. Let's bump up the peer dependency to 16.9 then.
