### ISSUE TITLE
Question: how are errors sorted?

### ISSUE THREAD

**Issue by an-aessid** [rjsf-team/react-jsonschema-form#1290]
### Description

I am trying to show a list of errors in the same order in which they appear in the form.
In our application the schemas are sent by a backend, so the returned jsonschema can differ in structure, due to the nature of json. This results in an order of error messages which is for the most part pretty random.
My guess is that the errors are ordered based on the order of the properties in the formSchema, and that the uiOrder fields of the uiSchema, have no say in this.

I added a link to the playground below. It's essentially the "Errors" tab with a minimal uischema passed in (by default there is no uischema for this page). The question "active" is placed before the "firstName" property, but the error messages for "firstName" are placed at the top.

So my question is if this should be a feature of RJSF, or if not, if anybody can tell me how they solved this in their project? We have a very old function which we implemented back in RJSF version 0.51.0 (I'm currently updating that...). This function I need to replace now, since the error message structures changed.

### Steps to Reproduce

https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImFjdGl2ZSI6Indyb25nIiwic2tpbGxzIjpbImthcmF0ZSIsImJ1ZG8iLCJhaWtpZG8iXSwibXVsdGlwbGVDaG9pY2VzTGlzdCI6WyJmb28iLCJiYXIiLCJmdXp6Il19LCJzY2hlbWEiOnsidGl0bGUiOiJDb250ZXh0dWFsaXplZCBlcnJvcnMiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRmlyc3QgbmFtZSIsIm1pbkxlbmd0aCI6OCwicGF0dGVybiI6IlxcZCsifSwiYWN0aXZlIjp7InR5cGUiOiJib29sZWFuIiwidGl0bGUiOiJBY3RpdmUifSwic2tpbGxzIjp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJtaW5MZW5ndGgiOjV9fSwibXVsdGlwbGVDaG9pY2VzTGlzdCI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6IlBpY2sgbWF4IHR3byBpdGVtcyIsInVuaXF1ZUl0ZW1zIjp0cnVlLCJtYXhJdGVtcyI6MiwiaXRlbXMiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiZm9vIiwiYmFyIiwiZnV6eiJdfX19fSwidWlTY2hlbWEiOnsidWk6b3JkZXIiOlsiYWN0aXZlIiwiZmlyc3ROYW1lIiwiKiJdfX0=

#### Expected behavior

The error for the "active" property should be above those of the "firstName" property.

#### Actual behavior

The errors seem to be sorted in the order they appear in the formSchema.

### Version

Current release.

**Comment by epicfaace** [comment]
@Gurkenschreck I'm not sure how exactly errors from JSON schema validation are ordered; it must be the same order from [ajv](https://github.com/epoberezkin/ajv). Given that JS objects don't really have a key order, though, I'm not sure if this order can be intuitively gotten from just looking at the schema. So, I think your proposal of ordering these errors based on ui:order makes sense.

**Comment by Gurkenschreck** [comment]
I'll spend some time adding this functionality to this project.

* should it be part of `Form.js` as a function that orders the errors by uischema in `onSubmit` before passing it down to `this.props.onError`?
* should it be standard behaviour (or should there be a prop in the forms proptypes?)?

I'm adding a bunch of tests.

**Comment by epicfaace** [comment]
Thanks!

@Gurkenschreck 
- You should probably add it to `validateFormData`: https://github.com/mozilla-services/react-jsonschema-form/blob/fba5bee2ba4dae0b057a1a6f19c408ef2af427fb/src/validate.js#L167
- I think it's ok for it to be standard behavior. Although it's technically backwards incompatible, we don't provide any guarantees currently of the error order, so it makes sense for it to be like this by default.
- For ui:orders with oneOfs, you just include the order of all the fields like in [this example](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0Iiwib25lT2YiOlt7InByb3BlcnRpZXMiOnsibG9yZW0iOnsidHlwZSI6InN0cmluZyJ9LCJpcHN1bSI6eyJ0eXBlIjoic3RyaW5nIn19LCJyZXF1aXJlZCI6WyJsb3JlbSJdfSx7InByb3BlcnRpZXMiOnsiaXBzdW0iOnsidHlwZSI6InN0cmluZyJ9fSwicmVxdWlyZWQiOlsiaXBzdW0iXX1dfSwidWlTY2hlbWEiOnsidWk6b3JkZXIiOlsibG9yZW0iLCJpcHN1bSJdfX0=).

**Comment by Gurkenschreck** [comment]
I created a WIP pull request for this. Smiley.

I also asked two questions in it, I need some advice.
