### ISSUE TITLE
Duplicate error messages are shown inline when anyOf is used

### ISSUE THREAD

**Issue by abhishekpdubey** [rjsf-team/react-jsonschema-form#1295]
While studying the features offered by this library on [Live play ground](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJjdXJyZW50Q29sb3IiOiIjMDBmZjAwIiwiY29sb3JNYXNrIjpbIiMwMDAwZmYiXSwiY29sb3JQYWxldHRlIjpbbnVsbF0sImJsZW5kTW9kZSI6InNjcmVlbiJ9LCJzY2hlbWEiOnsiZGVmaW5pdGlvbnMiOnsiQ29sb3IiOnsidGl0bGUiOiJDb2xvciIsInR5cGUiOiJzdHJpbmciLCJhbnlPZiI6W3sidHlwZSI6InN0cmluZyIsImVudW0iOlsiI2ZmMDAwMCJdLCJ0aXRsZSI6IlJlZCJ9LHsidHlwZSI6InN0cmluZyIsImVudW0iOlsiIzAwZmYwMCJdLCJ0aXRsZSI6IkdyZWVuIn0seyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyIjMDAwMGZmIl0sInRpdGxlIjoiQmx1ZSJ9XX0sIlRvZ2dsZSI6eyJ0aXRsZSI6IlRvZ2dsZSIsInR5cGUiOiJib29sZWFuIiwib25lT2YiOlt7InRpdGxlIjoiRW5hYmxlIiwiY29uc3QiOnRydWV9LHsidGl0bGUiOiJEaXNhYmxlIiwiY29uc3QiOmZhbHNlfV19fSwidGl0bGUiOiJJbWFnZSBlZGl0b3IiLCJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsiY3VycmVudENvbG9yIiwiY29sb3JNYXNrIiwiYmxlbmRNb2RlIl0sInByb3BlcnRpZXMiOnsiY3VycmVudENvbG9yIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL0NvbG9yIiwidGl0bGUiOiJCcnVzaCBjb2xvciJ9LCJjb2xvck1hc2siOnsidHlwZSI6ImFycmF5IiwidW5pcXVlSXRlbXMiOnRydWUsIml0ZW1zIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL0NvbG9yIn0sInRpdGxlIjoiQ29sb3IgbWFzayJ9LCJ0b2dnbGVNYXNrIjp7InRpdGxlIjoiQXBwbHkgY29sb3IgbWFzayIsIiRyZWYiOiIjL2RlZmluaXRpb25zL1RvZ2dsZSJ9LCJjb2xvclBhbGV0dGUiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJDb2xvciBwYWxldHRlIiwiaXRlbXMiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvQ29sb3IifX0sImJsZW5kTW9kZSI6eyJ0aXRsZSI6IkJsZW5kIG1vZGUiLCJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJzY3JlZW4iLCJtdWx0aXBseSIsIm92ZXJsYXkiXSwiZW51bU5hbWVzIjpbIlNjcmVlbiIsIk11bHRpcGx5IiwiT3ZlcmxheSJdfX19LCJ1aVNjaGVtYSI6eyJibGVuZE1vZGUiOnsidWk6ZW51bURpc2FibGVkIjpbIm11bHRpcGx5Il19LCJ0b2dnbGVNYXNrIjp7InVpOndpZGdldCI6InJhZGlvIn19fQ==) I came across this example where duplicate error messages were displayed. 
Please click on above link to see the example on the site. 

Notice that when we select empty value for Color palette's color field duplicate errors are shown. Here is the list of errors only for one field - 
should be string
should be string
should be equal to one of the allowed values
should be string
should be equal to one of the allowed values
should be string
should be equal to one of the allowed values
should match some schema in anyOf

Is this an expected behavior?

### Version
1.5.0

**Comment by epicfaace** [comment]
Looks like a bug to me. Thanks for reporting.

**Comment by mzvast** [comment]
So 2 years went by, any progress?

**Comment by heath-freenome** [comment]
This still looks like an issue, but it is caused by the ajv validation pointing all of the errors at the color field. It may really be an AJV issue.
