### ISSUE TITLE
Enum with select widget does not add a blank option at the top

### ISSUE THREAD

**Issue by abhishekpdubey** [rjsf-team/react-jsonschema-form#1296]
### Prerequisites

- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

I facing an issue with the enums. Here is the [playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJpc0FjdGl2ZSI6dHJ1ZSwiX25hbWUiOiJTYW1wbGUgbmFtZS4ifSwic2NoZW1hIjp7InRpdGxlIjoiU2FtcGxlIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkNyZWF0ZSBhIG5ldyBTYW1wbGUuIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiaXNBY3RpdmUiOnsidHlwZSI6ImJvb2xlYW4iLCJ0aXRsZSI6IlN0YXR1cyIsImRlZmF1bHQiOiIiLCJlbnVtIjpbdHJ1ZSxmYWxzZV0sImVudW1OYW1lcyI6WyJhY3RpdmUiLCJpbmFjdGl2ZSJdfSwiX25hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiTmFtZSJ9fSwicmVxdWlyZWQiOlsiX25hbWUiLCJpc0FjdGl2ZSJdfSwidWlTY2hlbWEiOnsidWk6b3JkZXIiOlsiaXNBY3RpdmUiLCJfbmFtZSJdLCJpc0FjdGl2ZSI6eyJ1aTplbXB0eVZhbHVlIjoiIiwidWk6cGxhY2Vob2xkZXIiOiJjaG9vc2UiLCJ1aTp3aWRnZXQiOiJzZWxlY3QifX19)

Based on the documentation here - https://react-jsonschema-form.readthedocs.io/en/latest/validation/#the-case-of-empty-strings
when enum is used with select widget, an empty option is added in the dropdown. This is not happening in the playground link I shared above.

Notice that the Status dropdown does not have an empty option in it.
I tried adding ui:emptyValue and ui:placeholder to the UI scheme but even this did not work for me.
Am I missing anything?

### Version
Latest version in playground

**Comment by epicfaace** [comment]
Related to #1041.

It looks like both ui:emptyValue and ui:placeholder are not working for your example, because the type is a boolean. So this may be a different (but related) bug to #1041.

**Comment by abhishekpdubey** [comment]
Boolean is just an example, It happens with string values as well.

**Comment by Gurkenschreck** [comment]
If you remove the `"default": ""` from the playground links schema, it adds the empty option/placeholder.

I'm not sure if this is the expected behaviour for the `default` property.
