### ISSUE TITLE
Not possible to double-click in field using "updown" widget

### ISSUE THREAD

**Issue by Eric24** [rjsf-team/react-jsonschema-form#1298]
### Description

Fairly simple: A field with no specified widget allows you to double-click in the field to "select all" (as is fairly common), but when using the "updown" widget for numeric values, it is necessary to double-click directly on top of the displayed text.

### Steps to Reproduce

This can be seen on the playground "Number" page on any of the "updown" widget fields. Simply double-click somewhere in the "updown" widget fields vs. double-clicking in a plain field.

#### Expected behavior

Double-clicking anywhere in the field should "select all".

#### Actual behavior

Nothing happens unless you double-click directly on top of the text in the field.

### Version

1.5.0

**Comment by epicfaace** [comment]
Why should double-clicking on a range slider cause a "select all"? I'm wondering because the default behavior of the range field does not include a label -- for example, see https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_range

**Comment by Eric24** [comment]
Sorry, I misread the playground ui-schema. It's the "updown" widget I'm referring to, not the "range" slider. I'll edit the issue accordingly.

**Comment by epicfaace** [comment]
@Eric24 However, even a regular `<input type=number>` also has this behavior in which double-clicking anywhere in the field does _not_ "select all": https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_number_get
