### ISSUE TITLE
Support for grouped enums

### ISSUE THREAD

**Issue by fsteger** [rjsf-team/react-jsonschema-form#1299]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description - New Feature Request

Add support for grouping sets of values given via enum / enumNames. For select fields, group titles are rendered inside <optgroup> tags.

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by epicfaace** [comment]
Interesting idea! How would you envision this widget would look like? (the native `<select>` element doesn't support grouping of enums, right) I'm thinking this could also be implemented by an option in the uiSchema -- any thoughts as to how that might be structured?
