### ISSUE TITLE
Check for type of array in default

### ISSUE THREAD

**Issue by domharrington** [rjsf-team/react-jsonschema-form#1300]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
When the `default` of an array type is `null` it causes an unrecoverable error:

https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJhcnJheSI6eyJ0eXBlIjoiYXJyYXkiLCJkZWZhdWx0IjpudWxsLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIn19fX0sInVpU2NoZW1hIjp7fX0=

### Steps to Reproduce

1. Go to playground link
2. Check console

#### Expected behavior

Maybe disregard the default value if `!Array.isArray(formData)`?
https://github.com/mozilla-services/react-jsonschema-form/blob/cc7e1b4f29ef5d18eb2c595daa186131426e0d49/src/components/fields/ArrayField.js#L296

#### Actual behavior

Unrecoverable error

### Version
Latest on playground.

**Comment by essonjon** [comment]
And there's a related issue, which is that the customer did not enter `null` as the default value but rather we automatically created it when converting their YAML file to JSON:

Details here:
https://app.asana.com/0/681252538274980/1125231582822105

**Comment by rmdevos** [comment]
Is this related to #1238 ?

I'm currently also running into an issue where we define null as default value which causes a render issue.

**Comment by domharrington** [comment]
I dont think it's related to that, this refers to when an array type has a default value of `null`.

**Comment by epicfaace** [comment]
This issue might be fixed by https://github.com/rjsf-team/react-jsonschema-form/pull/2154 but not sure -- need to check
