### ISSUE TITLE
I don't know what version of JSON Schema is currently supported

### ISSUE THREAD

**Issue by agilliam-cmg** [rjsf-team/react-jsonschema-form#1307]
Thank you for this wonderful project.  Please have the JSON Schema version number currently supported readily displayed either the README.md or the first page of the docs.

Much appreciated.

**Comment by epicfaace** [comment]
Thanks for pointing that out.

We currently support JSON Schema-07 by default, but we also support other JSON schema versions through this feature: https://react-jsonschema-form.readthedocs.io/en/latest/validation/#custom-schema-validation

It might be better to have that more prominently displayed, though.

**Comment by agilliam-cmg** [comment]
Thanks @epicfaace. Yes, it would be nice to have a link to this feature in the README.md, also maybe a one-liner stating "Supports up to v7.0" or something like that.

**Comment by epicfaace** [comment]
@agilliam-cmg sounds good, would you be able to make a PR adding this info in the docs?
