### ISSUE TITLE
Clear form fields/widgets data with button.

### ISSUE THREAD

**Issue by mravenash** [rjsf-team/react-jsonschema-form#1321]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
Is there a clear button for each fields that we can use to clear for forms fields? 
I am looking for a button on each field/widget that would either reset the field or set it to default.
Any help would be appreciated.

**Comment by epicfaace** [comment]
No, there currently isn't. You could make a custom widget for it though.
