### ISSUE TITLE
Default values doesn't work for properties of objects in array

### ISSUE THREAD

**Issue by ketysek** [rjsf-team/react-jsonschema-form#1327]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] I'm providing a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJwYXJhbWV0ZXJzIjp7ImNsaWVudF9zZWNyZXQiOiJTZWNyZXQiLCJzb21ldGhpbmciOnsibmFtZSI6Ik1vbnN0ZXIifSwic2VhcmNoIjpbeyJuYW1lIjoiQmxlaCJ9XX19LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsicGFyYW1ldGVycyI6eyJ0eXBlIjoib2JqZWN0IiwidGl0bGUiOiJQYXJhbWV0ZXJzIiwicHJvcGVydGllcyI6eyJjbGllbnRfc2VjcmV0Ijp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkNsaWVudCBzZWNyZXQiLCJkZWZhdWx0IjoiIn0sInNvbWV0aGluZyI6eyJ0eXBlIjoib2JqZWN0IiwidGl0bGUiOiJCdWxscyIsInByb3BlcnRpZXMiOnsibmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJOYW1lIiwiZGVmYXVsdCI6IiJ9fX0sInNlYXJjaCI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6IlNlYXJjaGVzIiwiaXRlbXMiOnsidHlwZSI6Im9iamVjdCIsInRpdGxlIjoiU2VhcmNoIiwicHJvcGVydGllcyI6eyJuYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6Ik5hbWUiLCJkZWZhdWx0IjoiIn19fX19fX19LCJ1aVNjaGVtYSI6e319) demonstrating the issue.

### Description
Default value doesn't work for properties of objects in array, they get erased from the formData instead.

### Steps to Reproduce
I've created a playground [here](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJwYXJhbWV0ZXJzIjp7ImNsaWVudF9zZWNyZXQiOiJTZWNyZXQiLCJzb21ldGhpbmciOnsibmFtZSI6Ik1vbnN0ZXIifSwic2VhcmNoIjpbeyJuYW1lIjoiQmxlaCJ9XX19LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsicGFyYW1ldGVycyI6eyJ0eXBlIjoib2JqZWN0IiwidGl0bGUiOiJQYXJhbWV0ZXJzIiwicHJvcGVydGllcyI6eyJjbGllbnRfc2VjcmV0Ijp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkNsaWVudCBzZWNyZXQiLCJkZWZhdWx0IjoiIn0sInNvbWV0aGluZyI6eyJ0eXBlIjoib2JqZWN0IiwidGl0bGUiOiJCdWxscyIsInByb3BlcnRpZXMiOnsibmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJOYW1lIiwiZGVmYXVsdCI6IiJ9fX0sInNlYXJjaCI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6IlNlYXJjaGVzIiwiaXRlbXMiOnsidHlwZSI6Im9iamVjdCIsInRpdGxlIjoiU2VhcmNoIiwicHJvcGVydGllcyI6eyJuYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6Ik5hbWUiLCJkZWZhdWx0IjoiIn19fX19fX19LCJ1aVNjaGVtYSI6e319), where you are free to try it.

#### Expected behavior
Once you remove a values from fields `Client secret` or `Bulls -> Name`, it works as expected and you can see the default empty strings in `formData` for these properties. But when you erase the value from `Search -> Name` field, you'll get empty object in search array instead of object with default `name` as empty string (as specified).

**Comment by epicfaace** [comment]
Thanks for reporting. Do you know if this worked before 1.6?

**Comment by ketysek** [comment]
@epicfaace I can tell you only that it doesn't work even in version `1.1.0` which we have installed in our app.

**Comment by fsteger** [comment]
This doesn't appear to be actually populating with the default when the value is removed. If you use a non-empty value for the default, the formData is still left with an empty string when the value is removed.

Defaults only get applied if the property does not initially exist when the form is created. For array items, when a new row is added, the defaults for the new item are added to the formData as well.

**Comment by fsteger** [comment]
Some related discussion:
* #476 
* #471

**Comment by heath-freenome** [comment]
@ketysek I cannot reproduce this with the latest 5.x playground. Can you verify if this is fixed?
