### ISSUE TITLE
Option to auto-remove/clean formData properties not found in Schema?

### ISSUE THREAD

**Issue by MatinF** [rjsf-team/react-jsonschema-form#1329]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

We currently use rjsf to enable users to load a Schema and a formData file for each of our electronics device firmwares. When we release new firmwares, we'd like the users to be able to load a new Schema - and their old formData (in order to quickly update their formData to the structure of the new Schema).

This works for the most part. However, if an update removes a property in the Schema, which was still present in the formData, this property is not removed upon submitting the updated formData using the new Schema and the old config. 

We can partially "solve" this by enforcing requirements on additionalProperties and minimum properties - but then the user is unable to directly edit their old formData in the editor as the validation will block the submission due to "outdated" fields still present in his formData. To fix it, the user has to manually remove the redundant fields to get past the validation issues.

Ideally, instead, the form could have an option to clean the formData of any properties that are not part of the Schema file. This would work similar to setting additionalPropertes: false and minProperties: X - but with the advantage that the form is able to process the removal of redundant properties on behalf of the user, minimizing errors.

### Steps to Reproduce

I've added  a playground link to illustrate the issue. In this, the formData input contains firstName, yet this property is not part of the Schema. Regardless, firstName is still included in the submitted formData - here we'd ideally want to have it excluded.

[Playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCJ9LCJzY2hlbWEiOnsidGl0bGUiOiJBIHJlZ2lzdHJhdGlvbiBmb3JtIiwiZGVzY3JpcHRpb24iOiJBIHNpbXBsZSBmb3JtIGV4YW1wbGUuIiwidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbImxhc3ROYW1lIl0sInByb3BlcnRpZXMiOnsibGFzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiTGFzdCBuYW1lIn0sImFnZSI6eyJ0eXBlIjoiaW50ZWdlciIsInRpdGxlIjoiQWdlIn0sImJpbyI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJCaW8ifSwicGFzc3dvcmQiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiUGFzc3dvcmQiLCJtaW5MZW5ndGgiOjN9LCJ0ZWxlcGhvbmUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiVGVsZXBob25lIiwibWluTGVuZ3RoIjoxMH19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoidXBkb3duIiwidWk6dGl0bGUiOiJBZ2Ugb2YgcGVyc29uIiwidWk6ZGVzY3JpcHRpb24iOiIoZWFydGhpYW4geWVhcikifSwiYmlvIjp7InVpOndpZGdldCI6InRleHRhcmVhIn0sInBhc3N3b3JkIjp7InVpOndpZGdldCI6InBhc3N3b3JkIiwidWk6aGVscCI6IkhpbnQ6IE1ha2UgaXQgc3Ryb25nISJ9LCJkYXRlIjp7InVpOndpZGdldCI6ImFsdC1kYXRldGltZSJ9LCJ0ZWxlcGhvbmUiOnsidWk6b3B0aW9ucyI6eyJpbnB1dFR5cGUiOiJ0ZWwifX19fQ==)

#### Expected behavior

Property fields in the loaded formData that are not part of the Schema should be removed from the submitted formData.

#### Actual behavior

The property fields remain included in the submitted formData

### Version

Release 1.6.1

**Comment by epicfaace** [comment]
See #1283
