### ISSUE TITLE
Initialize Ajv validator with option verbose:true

### ISSUE THREAD

**Issue by nkarip** [rjsf-team/react-jsonschema-form#1337]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description
Request new feature to initialize Ajv validator with option verbose: true (default is false). This provides parentSchema object in error and makes it easier to create a user-friendly error message (using field title). In validate.js would need to modify createAjvInstance to add option verbose: true to new Ajv instance.

**Comment by heath-freenome** [comment]
FYI, the v5 refactor of the validator code now supports this
