### ISSUE TITLE
TransformErrors happens before custom validate rule is run

### ISSUE THREAD

**Issue by CauchyAbel** [rjsf-team/react-jsonschema-form#1339]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

TransformErrors happens before custom validate rule is run, making it impossible to run transformerror on custom validate errors.

### Steps to Reproduce

1. Define custom validate rules and pass them to form
2. Define transformError function and pass it to form
3. Violate the custom validate rule on the form and you will see transformError function is not able to pick it up
4. This logic could be find in src/validate.js line 227-229 and 244-254, where transformError is run first and custom validate happens after

#### Expected behavior

TransformError should happen after validate rule runs since it should be a function which takes care of all errors on the form

#### Actual behavior

Described in steps to reproduce

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by epicfaace** [comment]
Unfortunately, this isn't something we can change in the current version due to backwards compatibility issues. Maybe in v2?

For now, you could just call your transform error transformations in the customValidate function as well, as a workaround.
