### ISSUE TITLE
How to create an form of an array of objects horizontally?

### ISSUE THREAD

**Issue by rogierverkaik** [rjsf-team/react-jsonschema-form#1344]
### Description

See a simple example at JSFiddle: https://jsfiddle.net/p862ufvr/22/
I've created a simple form with an array of objects. Each object has 3 fields. The fields are now shown vertically as you can see. But I'd like to show them horizontally, so next to each other. As you can see the form is now shown like this:

[id,
name,
description]
[id,
name,
description]

How can I present the form like this:

[id, name, description]
[id, name, description]

I've tried to use uiScheme and ObjectFieldTemplate, but none of them I am able to accomplish the form I would like to have. May someone help me out how to create this type of form?

**Comment by timothyallan** [comment]
What if you use the inline feature? https://react-jsonschema-form.readthedocs.io/en/latest/form-customization/#multiple-choice-list

```
By default, checkboxes are stacked. If you prefer them inline, set the inline property to true:

const uiSchema = {
  "ui:widget": "checkboxes",
  "ui:options": {
    inline: true
  }
};
```

**Comment by rogierverkaik** [comment]
I've tried this inline feature, but I think it only works for checkboxes. I tried it here: https://jsfiddle.net/utnr8svj/10/.

**Comment by timothyallan** [comment]
Ahh right, indeed it does. The `fieldset` used with yours won't pick that up.

**Comment by epicfaace** [comment]
Yeah the way I worked around this was to override the ObjectFieldTemplate in order to allow for objects to be on the same row. Having `"ui:options": { inline: true }` apply to objects is a great idea, though.

**Comment by rogierverkaik** [comment]
@epicfaace, is it possible you can add your ObjectFieldTemplate override workaround into https://jsfiddle.net/p862ufvr/22/ ? I tried to implement it, but I couldn't get it working yet. Thanks!

**Comment by epicfaace** [comment]
@rogierverkaik you can take a look here: https://github.com/epicfaace/CFF/blob/master/scripts/src/form/form_templates/ObjectFieldTemplate.tsx
