### ISSUE TITLE
Incorrect new value when adding object key with nullable type

### ISSUE THREAD

**Issue by mazikeens** [rjsf-team/react-jsonschema-form#1347]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Incorrect new value when adding object key with nullable type

### Steps to Reproduce

1. Open [playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0ZXN0Ijp7Im5ld0tleSI6W119fSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InRlc3QiOnsidHlwZSI6Im9iamVjdCIsImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjp7InR5cGUiOlsiYXJyYXkiLCJudWxsIl0sIml0ZW1zIjp7InR5cGUiOlsic3RyaW5nIiwibnVsbCJdfX19fX0sInVpU2NoZW1hIjp7fX0=)
2. Click bottom "+" button

#### Expected behavior

New key/value should be added with proper array widget rendered
"newKey-1": []

#### Actual behavior

New key/value is added with incorrect type and no array widget rendered
"newKey-1": "New Value"

### Version

1.6.1

**Comment by epicfaace** [comment]
This seems to have been fixed in the latest playground:

![image](https://user-images.githubusercontent.com/1689183/74461190-fd23a080-4e42-11ea-8e7c-123548013004.png)
