### ISSUE TITLE
Show all options in an AnyOf or OneOf when printing

### ISSUE THREAD

**Issue by nathfy** [rjsf-team/react-jsonschema-form#1348]
### Prerequisites

- [x ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [n/a ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

We are using the project to show a web form as well as printing to pdf for paper use. For the printed version we would like to show all the options in a `oneOf`/`anyOf` section. As far as I can see this would mean overriding the `MultiSchemaField.js` (https://github.com/mozilla-services/react-jsonschema-form/blob/c5e8899701279a2ab1ac75551824ff24b8d187a4/src/components/fields/MultiSchemaField.js) field to show all the options passed to it.
Or maybe replace the Field template do it there.

See the `OneOf` and `AnyOf` on the playground, and then imagine that printed to pdf with all the options listed one under the other... https://mozilla-services.github.io/react-jsonschema-form/ 

Anyone got any pointers on how to sort it?

### Steps to Reproduce

see description

#### Expected behavior

see description

#### Actual behavior

see description

### Version

Latest

**Comment by epicfaace** [comment]
@nathfy you should actually be able to override the `SelectWidget` because it is now used for OneOf/AnyOf since #1220.

**Comment by nathfy** [comment]
@epicfaace thanks, so if I override the select dropdown as per https://codesandbox.io/embed/6wxv10mz2k  can I then force all of the options to show at once? In the example above `Person` and `Dog` inputs need to show at the same time (for printing). Any pointers on how? Thanks.

**Comment by epicfaace** [comment]
Hmm, I see what you're asking -- you want all the inputs to show at once, right? Right now we don't support that, unless you create your own custom field and then set `OneOfField` to the custom field. It may be good for react-jsonschema-form to have an option to show all of the oneOf options though, perhaps by a built-in field.

**Comment by nathfy** [comment]
Thanks @epicfaace for the info - I tried to override the `OneOfField` as described with:

```
render() {
const customFields = {
      OneOfField: CustomOneOfField
    };
return (
<JsonSchemaForm
                schema={x.formJson}
                uiSchema={x.formJsonUiSchema}
                formData={x.formData}
                fields={customFields}
              />
);
}
```
But it isn't being picked up and used, the JsonSchemaForm is continuing to use the old `OneOfField` instead.

My custom OneOfField is attached, based on the existing:
https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/components/fields/MultiSchemaField.js 

Any pointers to what I am doing wrong to override it?
[customOneOfField.zip](https://github.com/mozilla-services/react-jsonschema-form/files/3533167/customOneOfField.zip)
