### ISSUE TITLE
Logo for react-jsonschema-from

### ISSUE THREAD

**Issue by LorenzHenk** [rjsf-team/react-jsonschema-form#1349]
### Description

Despite json-schema having a logo (https://json-schema.org/assets/logo.svg), it seems like this project does not have a logo at all. 

I'd like to dedicate this issue to sharing logo ideas and drafts.

This is @PhilipTrauner's and my take on it:

![logo](https://user-images.githubusercontent.com/10603631/60896656-01615d00-a267-11e9-9fee-1f6896d0130e.png)

**Comment by welkang** [comment]
It is a bit too monotonous in color.

**Comment by timothyallan** [comment]
Can you make it pop a bit more?


j/k I dig it. The only thing that bugs me is the check mark. I think possibly because everything else is so even/symmetrical and it's not. Perhaps if it was a bit more like so? https://www.kisspng.com/png-check-mark-symbol-icon-black-checkmark-112455/

**Comment by epicfaace** [comment]
It looks great! Perhaps removing the shadow from the check mark would help it fit in better?

**Comment by PhilipTrauner** [comment]
Hey folks, thanks for the feedback!

Here are a couple variations that should address the points raised thus far:
1. No drop-shadow (@epicfaace)

    ![Logo](https://user-images.githubusercontent.com/9287847/61175969-8b3b5e00-a5b8-11e9-8a06-f3adaea86251.png)

2. Alternative check-mark (with drop-shadow) (@timothyallan)

    ![logo1](https://user-images.githubusercontent.com/9287847/61176007-3f3ce900-a5b9-11e9-9bac-9e1114fadda9.png)

3. Alternative check-mark (without drop-shadow) (@timothyallan)

    ![logo3](https://user-images.githubusercontent.com/9287847/61176010-60053e80-a5b9-11e9-81ad-8cbc511fe332.png)

4. Alternative color scheme (@welkang)

    ![logo4](https://user-images.githubusercontent.com/9287847/61176022-b4a8b980-a5b9-11e9-89ef-dca345da193a.png)

**Comment by timothyallan** [comment]
Bump up the size of the check a bit, and It's #3 for me! Something like this perhaps?
![tacheck](https://user-images.githubusercontent.com/1995135/61176072-cb2e2100-a577-11e9-9eb1-80e7252c09e8.png)

**Comment by epicfaace** [comment]
> Bump up the size of the check a bit, and It's #3 for me! Something like this perhaps?
> ![tacheck](https://user-images.githubusercontent.com/1995135/61176072-cb2e2100-a577-11e9-9eb1-80e7252c09e8.png)

Let's use this. Can you contribute an SVG version of this image in a PR? @timothyallan

**Comment by timothyallan** [comment]
I just took a screenshot of #3 and enlarged the checkbox manually :) I don't have a source copy at all.
