### ISSUE TITLE
why live playground support object hidden?

### ISSUE THREAD

**Issue by RobitYadda** [rjsf-team/react-jsonschema-form#1363]
### Prerequisites

- [v ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ v] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [v ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
Doc says not support object hidden,  but I found live playground support this feature,so I am confused.

**Comment by epicfaace** [comment]
Where does it say that in the doc?

**Comment by epicfaace** [comment]
> Where does it say that in the doc?

@robityadda?
