### ISSUE TITLE
Root schema of type string shows defaults when cleared

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#1369]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When the root schema is of type `string`, with `ui:emptyValue` set to `""`, clearing the text box does not properly set the formData to an empty string; thus, default values show back up when clearing it.

### Steps to Reproduce

1. Go to this [playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6ImEiLCJzY2hlbWEiOnsidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJhIn0sInVpU2NoZW1hIjp7InVpOmVtcHR5VmFsdWUiOiIifX0=).
2. Type in something.
3. Clear the textbox.

#### Expected behavior

The textbox is cleared.

#### Actual behavior

The textbox is not cleared, and the default value is set to "a".

To fix this, we need to make sure that when a text box is cleared, the formData becomes `""` instead of `undefined`. This is currently how string inputs work when they are properties of an object; this behavior should be consistent even when a schema is of type `string`.

### Version

1.7.0

**Comment by Kexin-Li** [comment]
@epicfaace Hey, I've made a PR for this issue, please check it out, thanks :) https://github.com/rjsf-team/react-jsonschema-form/pull/1505
