### ISSUE TITLE
add extraErrors prop

### ISSUE THREAD

**Issue by thijssteel** [rjsf-team/react-jsonschema-form#1381]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue. -> https://jsfiddle.net/ThijsSteel/cbg4juem/9/

### Description

Sorry if this isn't the right place to put this, but i have thought of a neat way to handle async errors.

Instead of making the validator asynchronous like some PR's i've seen, we could supply an extraErrors prop to the Form. These errors are then added to the regular errors on every validation call.
The only other thing that is needed would be to run the validation every time the extraErrors prop changes.

I think this would both be easier to implement and more powerfull to use. Most big projects have some global request sending/error handling implementation in place. In my case the component would not have access to the request/result itself, but would react to changes in the error prop.

To make this idea a little more clear i have the following jsfiddle https://jsfiddle.net/ThijsSteel/cbg4juem/9/
because this is a simple mockup, some things have been simplified
- to simulate the extraErrors prop, i have the myCustomErrors variable
- to simulate adding the extra errors to the normal errors, i use the validate prop of the form
- the form does not revalidate after myCustomErrors has changed

If you think this is a good idea i'm happy to make a PR (and if you don't, i probably still will 😛 , i really need this feature)

### Version

1.7.0

**Comment by epicfaace** [comment]
Thanks for the explanation! It looks like someone did a similar approach (#874) but it's been stalled. Feel free to either work off of that existing PR, or make a new PR yourself implementing it.

Why would this approach (as opposed to making an async validate method) be more powerful?

**Comment by thijssteel** [comment]
#874 appears to be very similar to my idea, but differs in two ways
- it runs the async validation every time the regular validation runs, the extraErrors prop gives the developer the choice to either run async validation on validation or on submit
- it exposes the entire errorSchema, which makes the developer responsible for the integrity of the other errors in the schema. I don't believe this is really desirable. An extra errors prop could potentially have different format, allowing for future internal changes in the errorSchema without breaking changes

The reason i believe this method to be very powerful is that it doesn't require developers to rewrite business logic to conform to the async validate method. Just pass along the errors that are likely already available to the component.

Will make a PR soon.

**Comment by epicfaace** [comment]
@thijssteel thanks for the PR. I'm still not sure whether using extraErrors instead of, say, an asynchronous `validate` function would make it more intuitive / easy for developers to use. I created #1389 so people can discuss further on what solution might be the best!

**Comment by epicfaace** [comment]
This is now added!
