### ISSUE TITLE
custom widget for array fields with no `enums` or `uniqueItems` set to true

### ISSUE THREAD

**Issue by ghigt** [rjsf-team/react-jsonschema-form#1385]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Why is it not possible to specify a custom widget for array fields with no `enums` or `uniqueItems` set to true? I would like to create 2 widgets:
 - A multiSelect with the possibility to add new entries (no `enum`).
 - A multiSelect with the possibility to select an entry multiple times (`uniqueItems = false`).

### Steps to Reproduce

1. Having an array without `enum` or `uniqueItems` in its `items`.
```js
const schema = {
  type: "array",
  items: {
    "type": "string"
  },
};

const uiSchema = {
  "ui:widget": "myCustomWidget"
}
```

#### Expected behavior

Widget `myCustomWidget` to be used.

#### Actual behavior

Widget used is the default rendered by [`this.renderNormalArray()`](https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/components/fields/ArrayField.js#L439)

### Version

v1.7.0

**Comment by epicfaace** [comment]
You can't use a widget for array fields. Try either the `ArrayFieldTemplate` prop or the `ui:ArrayFieldTemplate` attribute in the uiSchema.

**Comment by ghigt** [comment]
We have to serialize the uiSchema and "ui:ArrayFieldTemplate" doesn't take strings.

**Comment by ghigt** [comment]
We thought about using an arrayFieldTemplate in the case where there is no enum attribute but our issue is that it doesn't seem possible to reference an ArrayFieldTemplate with its name in the uiSchema.

As opposed to widgets that supports something like { ui:widget: 'MyWidget' }, arrayFieldTemplate only accepts a component which is quite problematic when you want to serialize the uiSchema.

Would it be interesting to extend the way widgets are handled to arrayFieldTemplates ?

**Comment by Sankluj** [comment]
Hi!

I'm working in the same team as @ghigt. 

We would be pretty happy to propose a PR to implement the use case he explained above if you think it is interesting for the project, i.e. 
> Allowing the customizations of non `enums`, non `uniqueItems` array fields in the ui:schema while keeping it serializable.

However it is not clear what would be the best way to do this between:
* Leveraging the `ui:ArrayFieldTemplate` attribute and creating a util function similar to [`getWidget`](https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/utils.js#L91) named `getArrayFieldTemplate` that will supports both components and templates registered in the registry.
* Modify [`renderNormalArray `](https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/components/fields/ArrayField.js#L442) to support the definitions of a custom widget through `ui:widget` the same way it is done in [`renderMultiSelect`](https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/components/fields/ArrayField.js#L518)

Thanks :)

**Comment by epicfaace** [comment]
Oh, I see -- although it's possible to do this using a custom ArrayFieldTemplate, allowing for `ui:widget` would parallel the current use of `ui:widget` when having an array field with enums or uniqueItems.

So please go ahead with doing that! The second option (modifying `renderNormalArray`) seems like it would definitely work and be the most straightforward way to do so.

**Comment by OleksiL** [comment]
Hello guys. Has this been implemented?
I serialize schemas to json and save them to database.
At the moment setting of array template at field level doesn't work for me - obviously component can't be serialized:
"ui:ArrayFieldTemplate": MyArrayFieldTemplate

**Comment by alfonsoar** [comment]
@epicfaace to add on to the point above ☝🏾 

Is https://github.com/rjsf-team/react-jsonschema-form/pull/2125 the right approach to resolve this issue? If yes, are you accepting PRs? Maybe we can pick it up to close this one out.

**Comment by epicfaace** [comment]
I think so -- made a review to #2125.

**Comment by alfonsoar** [comment]
@epicfaace - Not a huge fan of the approach on https://github.com/rjsf-team/react-jsonschema-form/pull/2125 so created https://github.com/rjsf-team/react-jsonschema-form/pull/2697. Would you mind taking a look?

**Comment by epicfaace** [comment]
Thanks -- do you mind adding it to the weekly meeting agenda? I think a synchronous review would be easiest -- https://github.com/rjsf-team/react-jsonschema-form/issues/2677
