### ISSUE TITLE
Discuss - Asynchronous validation

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#1389]
There have been many attempts to implement async validation in the past, and it seems like it merits a discussion on what the best approach is to implement this. Making this issue as a wrapper issue for async validation in general.

Possible solutions that have been proposed / tried so far:
- Allow `validate()` to return a promise (#197, #198 - @n1k0 , #401 - @Kyr , #757 -@olzraiti )
- Allow `errors` to be passed into a form as a prop (#155, #874 - @davidbarratt, #1383 - @thijssteel)
- Use ajv's asynchronous validation functionality (#1210)
- Create a separate `onAsyncValidate` prop (#855 - @laithalissa)

It would be good to discuss the benefits and drawbacks of these approaches (such as: ease of use, backwards compatibility, etc.), and see what would be the best option to do going forward. I've tagged the people who've tried to implement async validation before on this issue, but would appreciate any feedback or thoughts!

**Comment by a-b-r-o-w-n** [comment]
I just ran into this limitation today. My initial thought is to support `validate()` returning a promise. However, thinking about more use-cases makes me lean towards an `errors` prop. This is a more declarative approach and would enable many other scenarios. I still think there is value in exposing the errors generated by AJV, but via a callback (`onValidate(errors)`). This could be added incrementally as well essentially allowing `errors` to be controlled (`errors` prop + `onValidate(errors)`) or uncontrolled (`validate()`).

**Comment by thijssteel** [comment]
Another point to discuss is the specific format of the errors prop (if we decide to go that route).
We could use the ajv format, which is more standardised and is likely to integrate better with the validation result by some backend.
We could also use the more 'objecty' format used internally.

**Comment by thijssteel** [comment]
Something that definitely should be considered as well is whether the async validation should block form submission.

I think a very common use case for async validation is displaying errors from a failed request to some backend and hence should not block submission.
However, another example could be validation of some hash of format that calls an async library client side and this might well require blocking.

**Comment by hmvp** [comment]
I am currently researching if we can use this project as a replacement for something home grown and I have the following issue that would probably be solved by adding a prop:

We have extra validation on the backend which is returned as JSON with 400 http status on the submit request. I have not yet found a way to show these errors in the form. Adding a prop would probably solve my problem.

**Comment by epicfaace** [comment]
@thijssteel @beskhue continuing the conversation from #1444 on this thread, as it seems more appropriate

Here's the concern I have about using an `extraErrors` prop as done in #1444: for the common scenario in which a server-side request is sent to do validation, it takes a lot of code to get this right. A good solution must:
- In `onSubmit`, call the server-side request, get the errors, then set the `extraErrors` prop if there are errors; otherwise, submit.
- Make sure that someone cannot call `onSubmit` once again before the previous server-side request, to avoid a race case.

Here's how that might look in practice:
```
class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      validating: false,
      extraErrors: null
    }
  }
  async onSubmit(e) {
    if (this.state.validating) {
      return;
    }

    this.setState({validating: true});
    const response = await fetch("/validate");
    if (response.body.success) {
      // Now we've submitted the form.
      console.log("submitted form");
    }
    else {
      this.setState({
        validating: false,
        extraErrors: response.body.extraErrors,
      });
    }
  }
  render() {
    return <Form
      onSubmit={this.onSubmit}
      extraErrors={this.props.extraErrors}
    />
  }
}
```

Note that because of these constraints, we have to use a class-based component. Additionally, `onSubmit` is not just called on submission; it's essentially used to perform async validation as well.

Whereas, if we just allow for an async validate function, it seems more intuitive -- `onSubmit` is called only on form submission, and `validate` is used for form validation:
```
const onSubmit = () => {
  console.log("submitted form");
}
const validate = async (formData, errors) => {
  const response = await fetch("/validate");
  if (!response.body.success) {
    errors = {...errors, response.extraErrors};
  }
  return errors;
}
const App = () => <Form
  onSubmit={onSubmit}
  validate={validate}
/>;
```


@a-b-r-o-w-n 
> @epicfaace one advantage is that it allows the caller to fully control the validation cycle. Giving control to the library to invoke a `validate()` function limits my ability to control when that gets invoked.
> 
> For instance, if I have an expensive operation to validate (i.e a network request), I may only want to do that under certain conditions.
I see your point here -- I think it makes sense to have an `errors` and `onValidate(errors)` prop. It would allow for full flexibility, although perhaps for the common use case of async validation it might be simpler for the user to implement it using the async `validate` function.

**Comment by thijssteel** [comment]
@epicfaace i don't know anyone that uses a separate validation endpoint before sending a request. So calling validation multiple times would give you the same problem of multiple submissions.

And any large project i have worked on has some shared logic for loading and error handling, this would not all be required by the component

**Comment by Beskhue** [comment]
@epicfaace In general I like the idea of async validation. Note there is also a race condition between validation and submission: e.g. a sign up form could validate a username for availability, but between successful validation and submission the username can be taken by someone else. Submission errors and validation errors are separate kinds in that respect. 

When interacting with APIs, submission errors are almost always available. I don't know of many APIs providing validation endpoints.

As a separate thought: perhaps for ease of use, validation can be made to be more granular: e.g. declaring validation callbacks for individual fields/objects.

**Comment by epicfaace** [comment]
@thijssteel @Beskhue good points! Let's go ahead with this and we can clarify in the documentation / future updates if the need arises.

**Comment by airtonix** [comment]
Still need you guys to treat ajv.validate as an async function because of async keywords.

example from ajv themselves:

```
var ajv = new Ajv;
// require('ajv-async')(ajv);

ajv.addKeyword('idExists', {
  async: true,
  type: 'number',
  validate: checkIdExists
});


function checkIdExists(schema, data) {
  return knex(schema.table)
  .select('id')
  .where('id', data)
  .then(function (rows) {
    return !!rows.length; // true if record is found
  });
}

var schema = {
  "$async": true,
  "properties": {
    "userId": {
      "type": "integer",
      "idExists": { "table": "users" }
    },
    "postId": {
      "type": "integer",
      "idExists": { "table": "posts" }
    }
  }
};

var validate = ajv.compile(schema);

validate({ userId: 1, postId: 19 })
.then(function (data) {
  console.log('Data is valid', data); // { userId: 1, postId: 19 }
})
.catch(function (err) {
  if (!(err instanceof Ajv.ValidationError)) throw err;
  // data is invalid
  console.log('Validation errors:', err.errors);
});
```

But we can't do any of this because  you treat ajv.validate as a synchronous call.

**Comment by ronnyek** [comment]
Unless I am missing something, I actually don't see how the "fix" for this one is actually a fix. Here is an example of a case I've got...

I want to validate ahead of time that a specific name a person is providing is available server side before allowing it to be submitted. Making that network call basically requires a promise. 

With the associated "fix" for this, I need to determine when to call validate on my server method, and take the response of that and add errors to `extraErrors` and hope that timing is right and gets there before rjsf tries to continue with submission. And per the comments in the documentation it sounds like rjsf will present this information, but not actually block anything etc?

Am I understanding all this correctly? Is there a reason why rjsf couldn't just take `function(formdata, errors) that returns errors` OR a function that returns a Promise with the errors, so we could just make the validation method an async method and go forward with that?

I'm not trying to be overly critical, I'm just trying to understand a use case the "fix" actually makes sense for, and if there are limitations with the way the library was implemented or javascript that would prevent doing things the other way.

**Comment by epicfaace** [comment]
I recall having the same question "why can't we just make `validate` return a Promise" earlier but it was resolved, but reading back through these comments I honestly don't remember how it was resolved. @thijssteel would you be able to help give more context?

**Comment by thijssteel** [comment]
The code was designed for endpoints that combine validation and request handling. This is, in my opinion, the most common use case for asynchronous validation errors. For example, you submit a form, the name is taken and the request fails with errors. You want to show this to the user, that is what `extraerrors` is for. This error does not block submission, because the only way to check whether the new name is valid, is to submit the form again.

> Here's the concern I have about using an extraErrors prop as done in #1444: for the common scenario in which a server-side request is sent to do validation, it takes a lot of code to get this right.

Async validation just before submission seems like bad practice to me. Imagine two people trying to snag the same popular name at the same time... You always need validation on the submission as well, so at that point you're just duplicating code.

A separate endpoint does make sense if you want to check as the user types. These errors should block submission. This is currently possible by including those errors via `transformErrors` instead of the JSON schema. A cleaner way to handle that use case is a validation that returns a promise or some other form of async validation, but that has disadvantages as well. For speed, you probably want to have the local validation separate from the async validation. You probably want to avoid revalidating the same fields if they haven't changed, ...

**Comment by ronnyek** [comment]
I am confused what you are suggesting here... that anything that needs to be validated server side, should happen as a part of the post, and we'd just return errors? So even though I validate everything else live, this would be one of those things where they type in a name, fix all the required/length limitations, it'd show as valid, submit and error because name was actually NOT valid?

I get that it'd need to be validated on the server as well because of timing / parallelism etc

**Comment by thijssteel** [comment]
> A separate endpoint does make sense if you want to check as the user types. These errors should block submission. This is currently possible by including those errors via transformErrors instead of the JSON schema.

**Comment by ronnyek** [comment]
So I see in the documentation, `transformErrors` but it looks like its primarily used to take an existing error, and reword or something. Doesn't look like the hook passes in anything but the existing error list (at least in the example in the docs).

**Comment by thijssteel** [comment]
That is indeed its primary use, but you could validate on state change, do your async validation, and patch the errors in on the next call to `transformErrors` ( i know its a hacky fix, but its the best i know of with the current version).

**Comment by ronnyek** [comment]
Oh that's fine...  I was just trying to understand your suggestion... 

To be clear, I actually do understand the reasoning for trying to keep `validate` the way it is, and that it should execute quickly and therefore really doesn't make sense to include some potentially LONGER running operation with a promise in the rest of quick client side validation... I just think this niche case is something I do run into from time to time (certainly not the majority of the forms that rjsf handles for me). I think if I can execute the regular `validate` stuff and at least TRIGGER async methods to fire and update validation rules when we get a response, that would be fine (blocking a submit if we get a taken prior to submit, but not waiting if someone were to very quickly submit before errors would added). I'll give that a whirl

I appreciate entertaining the question even if it may not be the intended function of the library. Thanks =)
