### ISSUE TITLE
Define the title of the items of the parent list in a nested array

### ISSUE THREAD

**Issue by mjozan** [rjsf-team/react-jsonschema-form#1391]
Hello,

I saw in the live playground [https://mozilla-services.github.io/react-jsonschema-form/] that one can create nested lists like this:

    "nestedList": {
          "type": "array",
          "title": "PARENT LIST",
          "items": {
            "type": "array",
            "title": "CHILD LIST",
            "items": {
              "title": "GRANDCHILDREN ITEMS"
              "type": "string",
              "default": "lorem ipsum"
            }
          }
        },

However, I see that the children of the parent list can only contain fixed title (ie: here "CHILD LIST"). How could a user define the title of the `CHILD LIST`? Thank you

**Comment by epicfaace** [comment]
@mjozan It seems like `title: "CHILD LIST"` is the piece that is defining the title of the child list. Are you trying to have a different title for each element of the array?

**Comment by mjozan** [comment]
@epicfaace I would like the title to be different for each element of the array but also defined by the user in an input just like the grandchildren items.

**Comment by epicfaace** [comment]
You can't define a title in a json schema form, as it is part of the schema itself. Perhaps you can try making an object with a `title` and `array` properties as the child item. See [this playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6IlBBUkVOVCBMSVNUIiwiaXRlbXMiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidGl0bGUiOnsidHlwZSI6InN0cmluZyJ9LCJhcnJheSI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6IiIsIml0ZW1zIjp7InRpdGxlIjoiR1JBTkRDSElMRFJFTiBJVEVNUyIsInR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoibG9yZW0gaXBzdW0ifX19fX0sInVpU2NoZW1hIjp7fX0=) for what I mean.
