### ISSUE TITLE
Creating dropdown list with option groups

### ISSUE THREAD

**Issue by pedramtalebi** [rjsf-team/react-jsonschema-form#1393]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I've been trying to understand if it's possible to create a dropdown list containing option groups. I've attached an image to show the visual representation of what I'm trying to achieve.

I read in a previous issue that this might be solved by adding "something" to the uiSchema, but I can't see how this can be done. 

### Steps to Reproduce

Irrelevant

#### Expected behavior

![image](https://user-images.githubusercontent.com/8910725/62634678-9757d880-b936-11e9-8b17-5ff828d7e7ec.png)

#### Actual behavior

Irrelevant

### Version

Latest

**Comment by epicfaace** [comment]
@pedramtalebi you would need to make your own custom widget as described in https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/#custom-widgets-and-fields. You could start with an existing React/CSS library (or just plain html with [optgroups](https://www.w3schools.com/tags/tag_optgroup.asp)) as a starting point for what the widget renders.
