### ISSUE TITLE
Allow array of types for Widget options (TypeScript)

### ISSUE THREAD

**Issue by samueldepooter** [rjsf-team/react-jsonschema-form#1397]
**I'm logging it here so it doesn't get lost in DefinitelyTyped!**

### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

WidgetProps is missing some type functionality. Since you can define custom `options` per field (defined by ui:schema) you should be able to type it properly depending on your own interface. Currently the `options` type is fixed.

### Steps to Reproduce

1. Extend a component's interface with WidgetProps
2. Access an `options` key that is e.g. an array of strings

#### Expected behavior

Since `options` should be able to contain any value/type, I'm expecting it to also allow array of types:
1. Create a component which has an interface that extends WidgetProps
2. Be able to have options of type array (string, number, ...) - ideally it should be a generic so you can set it yourself thus allowing better typing

#### Actual behavior

The interface only allows a select number of types:
`options: { [key: string]: boolean | number | string | object | null };`

See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/78ac91a5503a5c3018e040d548fad6edfd5a7520/types/react-jsonschema-form/index.d.ts#L90

### Version

`@types/react-jsonschema-form@1.6.2`

**Comment by epicfaace** [comment]
Thanks. I think it's probably best to create an issue in DefinitelyTyped though, since it relates to the types in there?
