### ISSUE TITLE
Q: Backend suggestion for saving UI schema and with fields/data?

### ISSUE THREAD

**Issue by rrjanbiah** [rjsf-team/react-jsonschema-form#1398]
Are there any recommended approaches to:

1. Save form UI schema in backend
2. Save form with data in backend

(Preferably in NoSQL and Postgres)

IOW, are there any libraries or something that act as helper for the purpose?

(One approach is that we may push form with data to Elasticsearch and display it using https://github.com/searchkit/searchkit)

Few libs noted:

1. https://github.com/better/jsonschema2db
2. https://docs.mongodb.com/manual/reference/operator/query/jsonSchema/

Edit: Noted few libs, but don't look perfect. Still better to get insights from the horse's mouth. TIA

**Comment by epicfaace** [comment]
Maybe Kinto? http://docs.kinto-storage.org/en/stable/ @glasserc

**Comment by rrjanbiah** [comment]
@epicfaace Thank you. Checking Kinto now!

**Comment by rrjanbiah** [comment]
@glasserc Thank you so much for your valuable input.

**Comment by rrjanbiah** [comment]
BTW, Fourmilieres is now available at https://github.com/Kinto/formbuilder with a demo at https://kinto.github.io/formbuilder/

**Comment by epicfaace** [comment]
I also work on a system called [CFF](https://github.com/epicfaace/CFF) that uses react-jsonschema-form on the frontend, but saves form configuration / responses in MongoDB.
