### ISSUE TITLE
v2 branch and roadmap

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#1409]
We should get out a v2 soon so we can resolve some of the issues that require backwards-compatible changes. Let's use this issue for discussion of a roadmap, plans, and issues.

Tracking some of the things we might want in v2 [in this GitHub Project board](https://github.com/mozilla-services/react-jsonschema-form/projects/1). Feel free to suggest what you think should / shouldn't be on this board.

I've also created a [v2 branch](https://github.com/mozilla-services/react-jsonschema-form/tree/v2). If you are able to help out with some of those changes, please make PRs to the v2 branch. As we continue with work on v1, we can periodically merge master in v2. 

Once v2 is released, we will rename the current master branch to v1 and rename v2 to master. In the future, v1 may only be updated with bugfixes and/or security enhancements.

**Comment by cefn** [comment]
I am currently using react-jsonschema-form from npm.

What's the compatibility status of the following?
* npm version
* repo master
* repo v2 

I am wondering if any of them have Bootstrap4 support as such, or if you're just expecting that Bootstrap3 will mostly work with Bootstrap4 (excepting glyphicons ...  https://github.com/rjsf-team/react-jsonschema-form/issues/1434#issuecomment-529235555 ) and that v2 is heading in the general direction of increased Bootstrap4 compatibility.

I've assumed there are no versioning issues with React although I'm using mainly hooks-based functional components which render to include a react-json-schema Form component.

**Comment by epicfaace** [comment]
react-jsonschema-form is going in the direction of being UI-framework-agnostic, with themes being able to be added through the `withTheme` component. So, in the future, there will be a bootstrap 3 theme and a bootstrap 4 theme.

Support for bootstrap 4 isn't blocked by a v2 version as such; it could be implemented now if someone made a bootstrap 4 theme (like the material-ui theme in #1420). v2 is more a way to add in breaking changes (such as requiring React 16 instead of React 15).

**Comment by white54503** [comment]
Any sense of the approximate timeline for a v2 release?

**Comment by epicfaace** [comment]
v2 is now out. Thanks to all who helped get this out!

**Comment by kim1882** [comment]
Thanks for this release. However I'm having some issues while updating the version with npm.
"No matching version found for react-jsonschema-form@2.0.0." Can you publish to https://www.npmjs.com/package/react-jsonschema-form ? Thanks in advance.

> v2 is now out. Thanks to all who helped get this out!

**Comment by epicfaace** [comment]
@kim1882 `@rjsf/core` is now a drop-in replacement for `react-jsonschema-form` -- you'll need to update your imports accordingly.
