### ISSUE TITLE
additionalProperties' type-guessing does not work when value is false

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#1412]
### Steps to Reproduce

1. Create a schema with `additionalProperties: true` and with an additional property equal to `true` ([playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhc2Rhc2QiOnRydWV9LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjp0cnVlfSwidWlTY2hlbWEiOnt9fQ==)).
2. Uncheck the checkbox.

#### Expected behavior

Unchecking a checkbox should result in an unchecked checkbox.

#### Actual behavior

The checkbox turns into an empty textbox!

### Version

1.7.0 (latest playground)

### Discussion

The issue seems to be this block of code: https://github.com/mozilla-services/react-jsonschema-form/blob/6728977b0085ef37c310b4d40d076a2622664ba7/src/utils.js#L545-L550

The idea of using `{ type: guessType(formData[key]) }` is that, when `additionalProperties` is set to `true`, it should guess the input type based on existing form data. Somehow, unchecking a checkbox ends up sending a value to `guessType` that returns "string".

It's probably caused by this piece of code, which sets `value` to an empty string if it is equal to false: https://github.com/mozilla-services/react-jsonschema-form/blob/310b8a5309bd55fd1c3e1533c93b3ce135b03dda/src/components/fields/ObjectField.js#L85-L94

**Comment by rbrishabh** [comment]
Hey, I would love to take this up!
