### ISSUE TITLE
oneOf title does not pull from $ref

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#1417]
### Description

When I have oneOf with a $ref, the title within the $ref does not show on the select widget.

### Steps to Reproduce

Check [this playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJkZWZpbml0aW9ucyI6eyJsb3JlbSI6eyJ0aXRsZSI6IkxvcmVtIiwicHJvcGVydGllcyI6eyJsb3JlbSI6eyJ0eXBlIjoic3RyaW5nIn19LCJyZXF1aXJlZCI6WyJsb3JlbSJdfX0sInR5cGUiOiJvYmplY3QiLCJvbmVPZiI6W3siJHJlZiI6IiMvZGVmaW5pdGlvbnMvbG9yZW0ifSx7InByb3BlcnRpZXMiOnsiaXBzdW0iOnsidHlwZSI6InN0cmluZyJ9fSwicmVxdWlyZWQiOlsiaXBzdW0iXX1dfSwidWlTY2hlbWEiOnt9fQ==) -- it should say "Lorem" instead of "Option 1" in the select widget.

[Here's an example](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0Iiwib25lT2YiOlt7InRpdGxlIjoiTG9yZW0iLCJwcm9wZXJ0aWVzIjp7ImxvcmVtIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbImxvcmVtIl19LHsicHJvcGVydGllcyI6eyJpcHN1bSI6eyJ0eXBlIjoic3RyaW5nIn19LCJyZXF1aXJlZCI6WyJpcHN1bSJdfV19LCJ1aVNjaGVtYSI6e319) of the expected behavior, which happens when not using a $ref.

### Version

1.7.0

**Comment by ropc** [comment]
Same issue with [`anyOf`](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJkZWZpbml0aW9ucyI6eyJsb3JlbSI6eyJ0aXRsZSI6IkxvcmVtIiwicHJvcGVydGllcyI6eyJsb3JlbSI6eyJ0eXBlIjoic3RyaW5nIn19LCJyZXF1aXJlZCI6WyJsb3JlbSJdfX0sInR5cGUiOiJvYmplY3QiLCJhbnlPZiI6W3siJHJlZiI6IiMvZGVmaW5pdGlvbnMvbG9yZW0ifSx7InByb3BlcnRpZXMiOnsiaXBzdW0iOnsidHlwZSI6InN0cmluZyJ9fSwicmVxdWlyZWQiOlsiaXBzdW0iXX1dfSwidWlTY2hlbWEiOnt9LCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOnRydWUsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

**Comment by TheMagicCat** [comment]
I'm experiencing this issue as well, would like to clean up a schema using `$ref`'s, but in the process I'm losing the titles.

**Comment by aydrian** [comment]
Hi. I'm also experiencing this issue.

**Comment by santiago-pat** [comment]
Hello, I solved this problem by putting a title in the referenced schema
