### ISSUE TITLE
react 16: array keys keep regenerating

### ISSUE THREAD

**Issue by zepatrik** [rjsf-team/react-jsonschema-form#1427]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

With react 16 the component lifecycle of `ArrayField` is different that with react 15.
The `getDerivedStateFromProps` method is first called with an the old props but updated state (e.g. adding a single item) and then recomputes all the keys because the lengths do not match. After that the props update and the keys get regenerated again because the lengths do not match.

Here you can see a log of `nextProps` and `prevState` args of `getDerivedStateFromProps`:

react 15:
![Screenshot from 2019-08-22 12-25-02](https://user-images.githubusercontent.com/5354445/63507384-e7f33800-c4d7-11e9-9eef-56a13334f188.png)

react 16:
![Screenshot from 2019-08-22 12-23-06](https://user-images.githubusercontent.com/5354445/63507385-e7f33800-c4d7-11e9-9a75-6fc2a0038dc8.png)

### Steps to Reproduce

1. add a console.log statement
1. open the array example on the playground
1. click the add button twice

#### Expected behavior

The keys should update the same way as they are doing with react 15.

### Version

v2 branch

**Comment by epicfaace** [comment]
So, what do you think the difference is in terms of how React 15 handles this? Is it that the lengths still do not match, but it does not recompute the keys?

**Comment by zepatrik** [comment]
I assume the polyfill of `getDerivedStateFromProps` is behaving differently than the actual implementation. If both updates would happen at once everything would work.
I already played with a functional component using hooks and that worked flawlessly.
But it actually requires a bit of refactoring.

**Comment by fsteger** [comment]
Can confirm something changed with regards to order of operations between React 15 v 16 here. In `onAddClick`, the new generated row is added to state with an assigned key. `setState` gets called with the new item and a call back to `onChange`. The `onChange` would trigger the re-render, so by the time `getDerivedStateFromProps` was hit, the state had the new item. I haven't dug in much further, but I'm guessing there's another change event that's causing the re-render that is now happening earlier in React 16; or the `onChange` callback from `onAddClick` is causing the component to update before the state change is available.

**Comment by epicfaace** [comment]
Maybe this: https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops

> Note that this method is fired on every render, regardless of the cause. This is in contrast to UNSAFE_componentWillReceiveProps, which only fires when the parent causes a re-render and not as a result of a local setState.

**Comment by epicfaace** [comment]
Fixed the issue, I've described it in further detail in 78139fd4c93c600dab6b5c2733205166daa4a53d.

**Comment by igor-vldk** [comment]
Applied fix should be improved for the case when an item is removed. Otherwise it will cause this issue: https://github.com/rjsf-team/react-jsonschema-form/issues/1479
