### ISSUE TITLE
can I use this without nodejs server running?

### ISSUE THREAD

**Issue by eyesmoker** [rjsf-team/react-jsonschema-form#1430]
I understand there is dependency on npm module but it doesn't mean that I should've nodejs server running. My codebase is on apache/php. Can I react-jsonschema-form without nodejs server running and somehow include npm libraries?
I am backend developer and very new to UI space. Please excuse me if this is dumb question.

**Comment by epicfaace** [comment]
You can use react-jsonschema-form with PHP. You would still need to use node/npm to develop your code, but when you finally deploy it, you can use webpack to bundle your code into a single javascript file. This file can then be loaded by PHP.

See https://medium.com/@davisonpro/an-advanced-guide-on-setting-up-a-react-and-php-web-app-acaedb21ab3a for an example.

**Comment by eyesmoker** [comment]
Thank you for quick response.
