### ISSUE TITLE
dispatchEvent submit does not work in ie11

### ISSUE THREAD

**Issue by martsie** [rjsf-team/react-jsonschema-form#1431]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
In Internet Explorer when attempting to submit the form, the following error occurs:

![image](https://user-images.githubusercontent.com/11308291/63561152-3a962800-c59c-11e9-8043-c030756e6a35.png)

### Steps to Reproduce
Submit a form.

#### Expected behavior
The form to submit.

#### Actual behavior
Error in ie11.

### Version
Latest

I'll probably have to come up with a way of polyfilling the Event on the form but I'm wondering why dispatchEvent was chosen in the first place over calling `.submit` directly on the form element?

**Comment by epicfaace** [comment]
Not sure, it seems to have been added in by @sunweiye #1058.

If we can just call `.submit` directly and not lose any functionality, then I'm all for it.

**Comment by martsie** [comment]
I'm having a deeper look now - looks like Internet Explorer 11 doesn't support creating Event's ... I'll get back to this issue once (if) I've got a neat solution.

**Comment by KKS1** [comment]
Thanks for looking into the fix. Is there an ETA on when this is targeted for merge and release creation ?

**Comment by KKS1** [comment]
For anyone else having this issue, this is how I am resolving it
`(function () {
  if (typeof Event !== 'function') {
    window.Event = CustomEvent;
  }
})();`
