### ISSUE TITLE
Additional Properties icons are not working when using Bootstrap 4

### ISSUE THREAD

**Issue by pedroth** [rjsf-team/react-jsonschema-form#1434]
### Description

Additional Properties icons are not working when using Bootstrap 4.

This happens because Bootstrap 4, removed glyphicons.

### Steps to Reproduce

1. Use Bootstrap  4, instead of 3
2. Create a form with Additional Properties

#### Expected behavior

Icons should appear when creating a form with Additional Properties

#### Actual behavior

Icons don't appear when creating a form with Additional Properties

### Version

"react-jsonschema-form": "^1.6.1"

**Comment by C-odes** [comment]
My project uses bootstrap 4,  this library requires bootstrap 3.  Is there any way to make it work with only 4?

**Comment by cefn** [comment]
I was able to add glyphicons by including this in my source. That doesn't mean it is 'working' as I have only tested it in a limited way.

```html
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">

```

**Comment by epicfaace** [comment]
There are other issues with using bootstrap 4 with the current default react-jsonschema-form theme, such as the array buttons not showing up either. I'm merging this issue with #1455.
