### ISSUE TITLE
Array with empty elements is invalid

### ISSUE THREAD

**Issue by rob1709** [rjsf-team/react-jsonschema-form#1439]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I have a schema that inclues an array of strings. Neither the array nor its items are required in the schema.

I've followed the [docs](https://react-jsonschema-form.readthedocs.io/en/latest/validation/#the-case-of-empty-strings) to convert an empty element into an empty string, which causes the data to be form data to be valid against the schema if the user doesn't enter a value - e.g. if I take the schema and form data and run this [here](https://www.jsonschemavalidator.net/) I get no errors back.

However, the UI states "Please fill in this field" when I click submit.

For my scenario, the array allows 1-5 items. I'd ideally like to display all 5 entries automatically (and so the user would just leave positions blank if they don't require these). This [example](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhZGRyZXNzTGluZSI6WyIiLCIiLCIiLCIiLCIiXX0sInNjaGVtYSI6eyJwcm9wZXJ0aWVzIjp7ImFkZHJlc3NMaW5lIjp7InR5cGUiOiJhcnJheSIsInRpdGxlIjoiQWRkcmVzcyIsIm1pbkl0ZW1zIjoxLCJtYXhJdGVtcyI6NSwiaXRlbXMiOlt7InRpdGxlIjoiTGluZSAxIiwidHlwZSI6InN0cmluZyJ9LHsidGl0bGUiOiJMaW5lIDIiLCJ0eXBlIjoic3RyaW5nIn0seyJ0aXRsZSI6IkxpbmUgMyIsInR5cGUiOiJzdHJpbmcifSx7InRpdGxlIjoiTGluZSA0IiwidHlwZSI6InN0cmluZyJ9LHsidGl0bGUiOiJMaW5lIDUiLCJ0eXBlIjoic3RyaW5nIn1dLCJhZGRpdGlvbmFsSXRlbXMiOmZhbHNlfX19LCJ1aVNjaGVtYSI6eyJhZGRyZXNzTGluZSI6eyJpdGVtcyI6W3sidWk6ZW1wdHlWYWx1ZSI6IiJ9LHsidWk6ZW1wdHlWYWx1ZSI6IiJ9LHsidWk6ZW1wdHlWYWx1ZSI6IiJ9LHsidWk6ZW1wdHlWYWx1ZSI6IiJ9LHsidWk6ZW1wdHlWYWx1ZSI6IiJ9XX19LCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6dHJ1ZSwibGl2ZU9taXQiOnRydWV9fQ==)  renders the UI exactly as I'd like, but the array elements are all required in the UI.

If I use an [amended schema](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhZGRyZXNzTGluZSI6WyIxIFN0cmVldCIsbnVsbCwiVG93biJdfSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImFkZHJlc3NMaW5lIjp7InR5cGUiOiJhcnJheSIsInRpdGxlIjoiQWRkcmVzcyIsIm1pbkl0ZW1zIjoxLCJtYXhJdGVtcyI6NSwiaXRlbXMiOnsidHlwZSI6InN0cmluZyJ9fX19LCJ1aVNjaGVtYSI6eyJhZGRyZXNzTGluZSI6eyJpdGVtcyI6W3sidWk6ZW1wdHlWYWx1ZSI6IiJ9LHsidWk6ZW1wdHlWYWx1ZSI6IiJ9LHsidWk6ZW1wdHlWYWx1ZSI6IiJ9LHsidWk6ZW1wdHlWYWx1ZSI6IiJ9LHsidWk6ZW1wdHlWYWx1ZSI6IiJ9XX19LCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6dHJ1ZSwibGl2ZU9taXQiOnRydWV9fQ==) in which the user adds/removes elements, the same scenario comes up if I try to add a blank line. So I can't (for example) add data in positions 1 and 3 whilst leaving position 2 blank (and we do have scenarios in which users need to do this).

Is this intended behaviour? And if so, is it possible for me to override or disable this behaviour?

**Comment by heath-freenome** [comment]
Is this still an issue for you with the 5.x release?
