### ISSUE TITLE
Bootstrap collisions?

### ISSUE THREAD

**Issue by C-odes** [rjsf-team/react-jsonschema-form#1445]
### Prerequisites

- [x ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

Im using bootstrap 4 on the project. While also using this library so I also use bootstrap 3 on this . Could they cause problem by overlapping? Or?

**Comment by epicfaace** [comment]
Probably; the right solution is to make a Bootstrap 4 theme. I'm merging this issue with #1455.
