### ISSUE TITLE
demo page not found

### ISSUE THREAD

**Issue by wwsun** [rjsf-team/react-jsonschema-form#1448]
demo page is lost

**Comment by stp-ip** [comment]
Due to the team change this should be available under: https://rjsf-team.github.io/react-jsonschema-form/

**Comment by epicfaace** [comment]
The link has been fixed by #1449. 

Meanwhile, I've contacted GitHub support to see if there is any way to redirect an old GitHub pages site to this one.

**Comment by vse-volod** [comment]
Link fixed by #1449 only affects docs pages, but this project **description** you can still see old link:
"A React component for building Web forms from JSON Schema. https://mozilla-services.github.io/re…"

**Comment by epicfaace** [comment]
@vse-volod thanks for noticing, I've fixed it.
