### ISSUE TITLE
default Value not working anyOf of Schema

### ISSUE THREAD

**Issue by jairock97** [rjsf-team/react-jsonschema-form#1452]
{
  "title": "",
  "properties": {
    "table_name": {
      "title": "Form Name",
      "type": "string",
      "default": "16"
    },
    "slug": {
      "title": "Field Name",
      "type": "string",
      "default": "Hello"
    },
    "required": {
      "title": "Required",
      "type": "string",
      "enum": [
        "",
        "true",
        "false"
      ],
      "default": ""
    },
    "null_field": {
      "title": "Select Field Type",
      "type": "null"
    }
  },
  "required": [
    "required",
    "slug"
  ],
  "anyOf": [
    {
      "title": "Text Form",
      "description": "",
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "title": {
          "title": "Title",
          "type": "string"
        }
      }
    },
    {
      "title": "Select Form",
      "description": "",
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "title": {
          "title": "Title",
          "type": "string"
        }
      }
    },
    {
      "title": "Date Time Form",
      "description": "",
      "type": "object",
      "required": [
        "title",
        "format"
      ],
      "properties": {
        "title": {
          "type": "string",
          "title": "Date Time Title"
        },
        "format": {
          "title": "Format",
          "type": "string",
          "enum": [
            "date",
            "date-time"
          ]
        }
      }
    }
  ]
}

### Prerequisites

- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by epicfaace** [comment]
Hey, can you post a playground link?

**Comment by Antonhansel** [comment]
Hey, I think we have the same issue, any update on that ?

**Comment by epicfaace** [comment]
Yeah, seems to be an issue. [Here's the playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwidGl0bGUiOiIiLCJwcm9wZXJ0aWVzIjp7InRhYmxlX25hbWUiOnsidGl0bGUiOiJGb3JtIE5hbWUiLCJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6IjE2In0sInNsdWciOnsidGl0bGUiOiJGaWVsZCBOYW1lIiwidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJIZWxsbyJ9LCJyZXF1aXJlZCI6eyJ0aXRsZSI6IlJlcXVpcmVkIiwidHlwZSI6InN0cmluZyIsImVudW0iOlsiIiwidHJ1ZSIsImZhbHNlIl0sImRlZmF1bHQiOiIifSwibnVsbF9maWVsZCI6eyJ0aXRsZSI6IlNlbGVjdCBGaWVsZCBUeXBlIiwidHlwZSI6Im51bGwifX0sInJlcXVpcmVkIjpbInJlcXVpcmVkIl0sImFueU9mIjpbeyJ0aXRsZSI6IlRleHQgRm9ybSIsImRlc2NyaXB0aW9uIjoiIiwidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbInRpdGxlIl0sInByb3BlcnRpZXMiOnsidGl0bGUiOnsidGl0bGUiOiJUaXRsZSIsInR5cGUiOiJzdHJpbmcifX19LHsidGl0bGUiOiJTZWxlY3QgRm9ybSIsImRlc2NyaXB0aW9uIjoiIiwidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbInRpdGxlIl0sInByb3BlcnRpZXMiOnsidGl0bGUiOnsidGl0bGUiOiJUaXRsZSIsInR5cGUiOiJzdHJpbmcifX19LHsidGl0bGUiOiJEYXRlIFRpbWUgRm9ybSIsImRlc2NyaXB0aW9uIjoiIiwidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbInRpdGxlIiwiZm9ybWF0Il0sInByb3BlcnRpZXMiOnsidGl0bGUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRGF0ZSBUaW1lIFRpdGxlIn0sImZvcm1hdCI6eyJ0aXRsZSI6IkZvcm1hdCIsInR5cGUiOiJzdHJpbmciLCJlbnVtIjpbImRhdGUiLCJkYXRlLXRpbWUiXX19fV19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==). The default value for object properties are not populated when anyOf is present.

@Antonhansel might you be able to look into it?
