### ISSUE TITLE
Rendering custom components for HTML elements (apart from BaseInput)

### ISSUE THREAD

**Issue by gbgdev** [rjsf-team/react-jsonschema-form#1453]
I've read in the documentation that there is a way of replacing the default behavior on how input fields are rendered using the [custom widget definition](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/#customizing-widgets-text-input) (overriding the `BaseInput` definition). I was wondering if it would be possible to do the same for other HTML elements like select, radio, text area, etc.

I've checked the source code and found [this list](https://github.com/rjsf-team/react-jsonschema-form/blob/9e4693abfc97c2b76d0e600531f09be6b4857d9c/src/components/widgets/index.js#L21) of widgets defined by default. But since the documentation doesn't say anything about them I am not sure if it would be a good practice to override widgets like `SelectWidget`.

Could someone shed some light on this?

**Comment by epicfaace** [comment]
Yes, you can do that. They're actually documented here (although perhaps not very clearly / easily to find!) https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/#customizing-the-default-fields-and-widgets -- if you have suggestions or improvements to the documentation, that would be welcome.

**Comment by gbgdev** [comment]
Hey @epicfaace, thanks for the feedback!

There actually no problem with the documentation. It was my bad. I probably missed this part when I was reading it.

Will close the issue, as the question was resolved 🙂
