### ISSUE TITLE
Support bootstrap 4

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#1455]
Could someone make a theme for bootstrap 4 using `withTheme`? That would be great 😃

**Comment by exKAZUu** [comment]
Here are related repos.
- https://github.com/danbalarin/react-jsonschema-form-theme-bs4
- https://github.com/peterkelly/react-jsonschema-form-bs4

**Comment by abeMedia** [comment]
Are there any plans to support bootstrap 4 in the core?

**Comment by epicfaace** [comment]
Yes -- see https://github.com/MLH-Fellowship/react-jsonschema-form/tree/integration/react-bootstrap-4
