### ISSUE TITLE
UI Plugin-System

### ISSUE THREAD

**Issue by domhaas** [rjsf-team/react-jsonschema-form#1461]
### Prerequisites

- [ x ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

Hi there. First of all: great lib - thanks a lot for your work!
Currently I'm using this project inside a very rich-ui-project, together with a symfony api-backend (using [Liform](https://github.com/Limenius/Liform) to generate form definitions from symfony forms).
So far so good, but I needed to spent much time to make it work together with native [blueprintjs](https://github.com/palantir/blueprint) controls.
I've found some postings here that there is really no focus on implementing other UI-Libs than bootstrap, because it can be done by overriding the default widgets - and that's for sure, true. But sharing is caring - currently I can share my code, but it would be very nice to have something like a plugin-system to offer people creating some kind of "official" support for those brilliant ui-libs out there, like blueprintjs.

Any interests about that?
Thank you in advance.

#### Expected behavior

Plugin-System to easy make this project work together with different UI-Libs, like blueprintjs or antd.

#### Actual behavior

Currently it works by overloading the default renderers. But it took much time to make it work.

### Version

1.8.0

**Comment by epicfaace** [comment]
Yes, it was for this reason that we added the `withTheme` HOC. We would greatly appreciate a contribution to add a theme for blueprintjs!

**Comment by domhaas** [comment]
> Yes, it was for this reason that we added the `withTheme` HOC. We would greatly appreciate a contribution to add a theme for blueprintjs!

Thanks for the hint. I'm going to check that out.

**Comment by domhaas** [comment]
> Yes, it was for this reason that we added the `withTheme` HOC. We would greatly appreciate a contribution to add a theme for blueprintjs!

@epicfaace I've created a first initial version of a blueprintjs-theme:
[https://github.com/domhaas/react-jsonschema-form-theme-blueprintjs](https://github.com/domhaas/react-jsonschema-form-theme-blueprintjs)

Currently there is just a checkbox and text-widget, but I'm trying to complete it in the next days. The rest will follow of course, like validation.
I just wanted to show that there is something happening with this pre-release, maybe there are people out there who want to contribute or having a need for this implementation.

**Comment by epicfaace** [comment]
Combining this issue into #1473.
