### ISSUE TITLE
Issue using anyOf with omitExtraData

### ISSUE THREAD

**Issue by ostyn** [rjsf-team/react-jsonschema-form#1463]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
[Playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6W3sibWV0YWRhdGFUeXBlIjoiSEVBREVSIiwic3RhdGljRGF0YSI6WyJUZXN0SGVhZGVyIl19LHsibWV0YWRhdGFUeXBlIjoiRk9PVEVSIiwiZGF0YVNvdXJjZUlkIjoyfV0sInNjaGVtYSI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJtZXRhZGF0YVR5cGUiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiSEVBREVSIiwiRk9PVEVSIl19fSwicmVxdWlyZWQiOlsibWV0YWRhdGFUeXBlIl0sImFueU9mIjpbeyJ0aXRsZSI6IkRhdGFTb3VyY2UtYmFzZWQiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJkYXRhU291cmNlSWQiOnsidHlwZSI6ImludGVnZXIifSwiZ3JvdXBDb2x1bW5zIjp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmcifX19LCJyZXF1aXJlZCI6WyJkYXRhU291cmNlSWQiXX0seyJ0aXRsZSI6IlN0YXRpYyBNZXRhZGF0YSIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InN0YXRpY0RhdGEiOnsidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidHlwZSI6InN0cmluZyJ9fX0sInJlcXVpcmVkIjpbInN0YXRpY0RhdGEiXX1dfX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIifSwiYWdlIjp7InVpOndpZGdldCI6InVwZG93biIsInVpOnRpdGxlIjoiQWdlIG9mIHBlcnNvbiIsInVpOmRlc2NyaXB0aW9uIjoiKGVhcnRoaWFuIHllYXIpIn0sImJpbyI6eyJ1aTp3aWRnZXQiOiJ0ZXh0YXJlYSJ9LCJwYXNzd29yZCI6eyJ1aTp3aWRnZXQiOiJwYXNzd29yZCIsInVpOmhlbHAiOiJIaW50OiBNYWtlIGl0IHN0cm9uZyEifSwiZGF0ZSI6eyJ1aTp3aWRnZXQiOiJhbHQtZGF0ZXRpbWUifSwidGVsZXBob25lIjp7InVpOm9wdGlvbnMiOnsiaW5wdXRUeXBlIjoidGVsIn19fSwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjp0cnVlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6dHJ1ZSwibGl2ZU9taXQiOmZhbHNlfX0=)

**With** the schema in the playground (a fairly uncomplicated schema using anyOf), 
**And with** the data in the playground(It should match the schema)

**When** omitExtraData is turned on(for the playground or in actual development),
**I get** validation messages that I shouldn't be seeing given that my data matches the schema

**When** omitExtraData is turn off
**I DO NOT get** validation messages

### Steps to Reproduce

1. Go to playground
2. Press Submit

#### Expected behavior

The form should not give me validation errors

#### Actual behavior

I get a TON of validation errors

### Version

My version is 1.8.0 
This was not present in 1.6.1, prior to omitExtraData.

**Comment by Nishit-Kakkad** [comment]
I also have the same issue with latest version. Did you found any alternative for this?

**Comment by heath-freenome** [comment]
@ostyn @Nishit-Kakkad I cannot reproduce this with the given example against the 5.x playground. I believe that means it is fixed. Can you verify?
