### ISSUE TITLE
[Question] How to disable move up/down

### ISSUE THREAD

**Issue by ktalebian** [rjsf-team/react-jsonschema-form#1466]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

My uiSchema looks something like:

```json
{
    "items": {
         "hasMoveDown": false,
         "hasMoveUp" :false,
         "ui:field":"collapsibleObject",
         "ui:collapsibleObject":{
            "viewableCollapsed":[
               "id"
            ]
         },
         "classNames":"col-lg-12",
         "description":{
            "ui:widget":"textarea"
         }
   }
}
```

but the move up and down keys still show up on the rendered component; how do I remove them?

**Comment by tuunanen** [comment]
As far as I know, hasMoveUp/hasMoveDown are only being used internally in the ArrayField component. The correct option to use is `orderable`.

https://react-jsonschema-form.readthedocs.io/en/latest/form-customization/#orderable-option

Your uiSchema should look like:

```js
{
  "items": {
     // removed for brevity ...
  },
  "ui:options": {
    "orderable": false
  }
}
```

**Comment by ktalebian** [comment]
@tuunanen thanks! That worked great.

**Comment by epicfaace** [comment]
thanks @tuunanen !
