### ISSUE TITLE
[Question] references are only dereferenced from `#/definitions/`?

### ISSUE THREAD

**Issue by royling** [rjsf-team/react-jsonschema-form#1467]
Checking the source code - https://github.com/rjsf-team/react-jsonschema-form/blob/v1.8.0/src/utils.js#L486, it seems the references are only dereferenced from `#/definitions/...` statically, but this is not forced in [json schema spec](http://json-schema.org/latest/json-schema-core.html#rfc.section.8.3).

Is there any plan to enhance this to be compliant with the spec? or I just missed anything about the `$ref` in the spec.
Thanks!

**Comment by epicfaace** [comment]
This will be fixed by #1506.
