### ISSUE TITLE
[Question] How to make add new item to array append to beginning (shift)

### ISSUE THREAD

**Issue by ktalebian** [rjsf-team/react-jsonschema-form#1468]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

It is possible for the `+` button that adds a new item into an array, to add the new entry to the beginning of the array as opposed to the end of the array?

**Comment by saketkumar** [comment]
@ktalebian any updates? Have you got any solution for this?

**Comment by epicfaace** [comment]
You could create a custom ArrayFieldTemplate and then call `props.onAddIndexClick(0)` when the add button is pressed in order to insert an item at the beginning of an array. See https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/#array-field-template

**Comment by mqliutie** [comment]
@epicfaace Can `ArrayFieldTemplate`'s data  control by updating `formData`, Now I don't know how can I update the data by code like `props.onChange(['some text', ...originData])`.

If I call this.setState({formData:...}), I don't know current ArrayFiledTemplate's key, which data should be updated that I don't know

**Comment by ktalebian** [comment]
@epicfaace is there a way to just customize the button? If I pass `ArrayFieldTemplate`, I need to customize the entire array rendering; I still want the default rendering, except I want the `canAdd` behvaior to change

**Comment by epicfaace** [comment]
@mqliutie 
> If I call this.setState({formData:...}), I don't know current ArrayFiledTemplate's key, which data should be updated that I don't know

Each element in `props.items` has an `index` prop that should give you the index of which data needs to be updated.

**Comment by epicfaace** [comment]
> @epicfaace is there a way to just customize the button? If I pass `ArrayFieldTemplate`, I need to customize the entire array rendering; I still want the default rendering, except I want the `canAdd` behvaior to change

As of now, no.
