### ISSUE TITLE
how to change one input once another one changed?

### ISSUE THREAD

**Issue by videni** [rjsf-team/react-jsonschema-form#1469]
I have two auto complete selects , once the first one changed, the second one need to be cleared.  what is the proper way to do this?  since they all subscribe the same onChange method of `src/components/Form.js`.

**Comment by epicfaace** [comment]
You can make the form a controlled component -- i.e., set the `formData` attribute through a value in the state, and then you can change things. Here's an example: https://jsfiddle.net/c70x9zLs/1/

**Comment by videni** [comment]
@epicfaace  thanks, your example is very useful.
