### ISSUE TITLE
support string type ui:ArrayFieldTemplate and customTemplates

### ISSUE THREAD

**Issue by lomocc** [rjsf-team/react-jsonschema-form#1471]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

Can we use **string** **"ui:FieldTemplate"** with **customTemplates** ? just like **'ui:widget'**, because we need to custom the **array field**（such as select users multiple，files，and others）
and now I use this instead
```js
uiSchema['ui:ArrayFieldTemplate'] = getTemplateByName(uiSchema['ui:ArrayFieldTemplate'])
```

#### Expected behavior

**support string type ui:ArrayFieldTemplate and customTemplates**

### Version

1.8.0

**Comment by epicfaace** [comment]
That would be great -- feel free to make a PR implementing this.

Ashwin Ramaswami
Student
*Find me on my:* LinkedIn <https://www.linkedin.com/in/ashwin-r> | Website
<https://epicfaace.github.io/> | GitHub <https://github.com/epicfaace>

**Comment by heath-freenome** [comment]
I believe the `templates` implementations in 5.x provide what you are needing
