### ISSUE TITLE
formData for two fields align at same line. 

### ISSUE THREAD

**Issue by saketkumar** [rjsf-team/react-jsonschema-form#1477]
I wanted to create a form with two fields, **Key** and **Values**
Suppose like this.

<img width="591" alt="Screenshot 2019-10-01 at 3 11 03 AM" src="https://user-images.githubusercontent.com/21558765/65919177-2a723380-e3f9-11e9-8d1a-8f294ba1d864.png">

I wanted the **formData** to be something like this: 

<img width="390" alt="Screenshot 2019-10-01 at 3 13 26 AM" src="https://user-images.githubusercontent.com/21558765/65919281-79b86400-e3f9-11e9-9f74-43d178370a37.png">

I tried custom array but didn't any result. Custom array was creating something like this.
<img width="394" alt="Screenshot 2019-10-01 at 3 15 38 AM" src="https://user-images.githubusercontent.com/21558765/65919393-c865fe00-e3f9-11e9-8263-09ce492b38c2.png">

Can anyone please help in this? I want a **jsonSchema** and **uiSchema** for this type of formData.
@n1k0 @epicfaace ?

**Comment by epicfaace** [comment]
@saketkumar try the additionalProperties example in https://rjsf-team.github.io/react-jsonschema-form/ -- that helps you to create custom keys and values.

**Comment by Ocular9104** [comment]
@epicfaace I want my form data to look like this : 

<img width="390" alt="1" src="https://user-images.githubusercontent.com/57208529/68465651-db5dc080-0238-11ea-91c5-859e4e01b8ee.png">

How to do that?

**Comment by Mohammed-Nasif** [comment]
@epicfaace Hi epic, did you know if there is an option to display a title for the key field in the additionalProperties ?
