### ISSUE TITLE
onChange callback gets obsolete after an array item is removed

### ISSUE THREAD

**Issue by igor-vldk** [rjsf-team/react-jsonschema-form#1479]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

In react < 16.4 removing an array item due to using generated keys correctly doesn't cause unaffected items to be rerendered, so the onChange callback keeps an obsolete index.

(Due to this bug https://github.com/rjsf-team/react-jsonschema-form/issues/1427 react > 16.4 regenerates keys preventing this issue) 

### Steps to Reproduce

1. Add an array item to have at least 3 items (Reproducible in react-jsonschema-form playground)
2. Remove an item to have at least 2 items left next to the removed one
3. Type anything in the item that replaced the removed one. 

#### Expected behaviour

Typed text appears in the field it was typed

#### Actual behaviour

Typed text appears in the next field it was actually typed

### Version
1.8.0^

**Comment by epicfaace** [comment]
Thanks for reporting. Is there a way to fix this for react > 16.4?

**Comment by epicfaace** [comment]
Thanks for reporting. Does this still happen in the v2 branch (which includes a fix for #1427)?
