### ISSUE TITLE
anyOf field incorrectly updating after change

### ISSUE THREAD

**Issue by SuriGill** [rjsf-team/react-jsonschema-form#1486]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Since updating to react 16, the anyOf field doesn't correctly update after receiving props. It will override the selected option incorrectly. This can be resolved by migrating to the componentDidUpdate method instead of the componentWillReceiveProps that's currently marked unsafe. componentWillReceiveProps will update state synchronously and componentDidUpdate will update state asynchronously.

### Steps to Reproduce

1. Go to anyOf field in storybook of the latest version of master
2. Add a new entry and keep it selected as option 1 and enter some text in the input field
3. Add another entry and select option 2 and enter some text in the input field
4. Move the option 2 up in the array.
![anyOfError](https://user-images.githubusercontent.com/6132338/66960065-b4e1a680-f039-11e9-93b3-694e812f9d07.gif)

#### Expected behavior

The array should have the two positions switched.

#### Actual behavior

The array only has one position switched correctly, while the other has the wrong selected option even though the state has been changed.

### Version

v.1.8.0

**Comment by epicfaace** [comment]
Just confirming -- is the same issue is happening with the latest code on the master branch (https://rjsf-team.github.io/react-jsonschema-form/)? We added in a few changes that might have fixed it in https://github.com/rjsf-team/react-jsonschema-form/pull/1352

**Comment by SuriGill** [comment]
Yes, when running the devserver playground of the latest version on the master branch with the changes from #1352, I still run into this problem.

**Comment by SuriGill** [comment]
After looking into the codebase for the anyOf field, I found that the function for computing the matching option in the utils file returns 0 for the first index selection and for formdata that is not available in a selection component. 

The function for computing the matching option in the multiSchemaField file uses that util function but then resolves a 0 value by using the previous state instead of the first option (0) if available. This is where the problem lies. By trying to resolve to the previous state without differentiating formdata that is not available and the first option, we can get errors. We can either trying returning a -1 in the util function and in the line mentioned below, change it to `if (option !== -1) {` OR we can try always resolving to the first option if there is an error in formData.

https://github.com/rjsf-team/react-jsonschema-form/blob/master/src/components/fields/MultiSchemaField.js#L41

**Comment by SuriGill** [comment]
I've also found another issue that is related to the anyOf schema incorrectly rendering. I was unsure if I should make another ticket or include it in this issue. The steps to reproduce:

1. Go to anyOf field in storybook of the latest version of master
2. Add two new entries in the items
3. Move item one down
4. Try typing in the second item
![anyOfError2](https://user-images.githubusercontent.com/6132338/67306528-1d5ed680-f4c5-11e9-9d79-ea6ad25a8b16.gif)

This issue has to do with the schema not re-rendering after a change because the only prop that is changing is the idSchema which is not resolved in shouldComponentUpdate here:
https://github.com/rjsf-team/react-jsonschema-form/blob/master/src/components/fields/SchemaField.js#L413

**Comment by epicfaace** [comment]
Fixed by #1491 and #1493.
