### ISSUE TITLE
How to validate formData without rendering Form?

### ISSUE THREAD

**Issue by MatinF** [rjsf-team/react-jsonschema-form#1489]
### Prerequisites
- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
I would like to perform a validation of my formData based on a schema - but I don't want to render a Form to do so. 

I assume it's fairly simple to perform such a validation and e.g. return the result in the console - but I am unable to find it anywhere in the documentation.

Is this possible - and if so, can you guide me to where the docs describe how to achieve it?

**Comment by MatinF** [comment]
I kind of solved this using the guide for programmatic access, combined with simple CSS to hide the Form component. While a bit funky, it works as per my requirements - though happy to hear if there's a more proper solution for this.

**Comment by epicfaace** [comment]
Maybe just use the ajv library?
