### ISSUE TITLE
Fail with large schema

### ISSUE THREAD

**Issue by shenenya** [rjsf-team/react-jsonschema-form#1492]
### Prerequisites

- [-] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [-] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [-] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I tried react-jsonschema-form with schema more than 10,000 lines, most of which is optional. Could we only display items based on input data? 
I tried to find answer in git and stackoverflow. And I only found the docs said "If you have a priori knowledge of your data and want a toolkit for generating forms for it, you might look elsewhere."
Is there any way to do that? Thanks.

**Comment by epicfaace** [comment]
You can do this, but you would have to store the schema in the component's state, and then modify the schema on-the-fly in the form's `onChange` handler. See, for example, https://jsfiddle.net/69z2wepo/88541/

**Comment by eeyshen** [comment]
Thanks. Is it possible to display items based on the input data and autocomplete based on the whole schema? For example, if user want to add element to existing data, the tool can recommend what to add based on the whole schema.

**Comment by epicfaace** [comment]
You might be able to use autocomplete with the `examples` keyword (functionality pending in #1517)
