### ISSUE TITLE
Allow object selection in dropdowns

### ISSUE THREAD

**Issue by tdamsma** [rjsf-team/react-jsonschema-form#1494]
I want to present a dropdown with options that when selected populate the formData with an object. 

Consider this schema:

```json
{
  "type": "object",
  "title": "Location",
  "required": [
    "name",
    "latitude",
    "longitude"
  ],
  "oneOf": [
    {
      "const": {
        "name": "Home",
        "latitude": 12.4,
        "longitude": 2.8
      },
      "title": "Home"
    },
    {
      "const": {
        "name": "Work",
        "latitude": 62.4,
        "longitude": 4
      },
      "title": "Work"
    }
  ]
}
```

I would like a dropdown that gives the options `Work` and `Home` but that doesn't store a string but the entire object with name, lat, lon. The schema above does not render properly at all. 

The closest I could get to the intended behavior is the following:
```json
{
  "type": "object",
  "title": "Location",
  "required": [
    "name",
    "latitude",
    "longitude"
  ],
  "oneOf": [
    {
      "properties": {
        "name": {
          "const": "Home",
          "default": "Home",
          "readOnly": true
        },
        "latitude": {
          "const": 12.4,
          "default": 12.4,
          "readOnly": true
        },
        "longitude": {
          "const": 2.8,
          "default": 2.8,
          "readOnly": true
        }
      },
      "title": "Home"
    },
    {
      "properties": {
        "name": {
          "const": "Work",
          "default": "Work",
          "readOnly": true
        },
        "latitude": {
          "const": 62.4,
          "default": 62.4,
          "readOnly": true
        },
        "longitude": {
          "const": 4,
          "default": 4,
          "readOnly": true
        }
      },
      "title": "Work"
    }
  ]
}
```
This renders all the fields disabled. What I would want is to nut render the name/lat/lon fields at all (only the title dropdown), but do pass them to the formData.

**Comment by KKS1** [comment]
Hi @tdamsma , how about if you use `"ui:widget": "hidden"` in uiSchema instead of `readOnly: true` in schema.

**Comment by tdamsma** [comment]
@KKS1 that would work as a work around to hide the fields, thanks! Still makes using this option slightly cumbersome, as the jsonschema's I use are dynamically generated so this would require generating an accompanying uiSchema. Would be nice if the uiSchema could be merged with the jsonschema, but that is a another discussion

**Comment by epicfaace** [comment]
Yeah, merging this into #701 then.
