### ISSUE TITLE
Validation error anyOf in alternatives example

### ISSUE THREAD

**Issue by Benni2808** [rjsf-team/react-jsonschema-form#1495]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

It looks like, there is a bug with the anyOf schema validation, when used instead of enum/enumNames.

### Steps to Reproduce

1. open [playground](https://rjsf-team.github.io/react-jsonschema-form/)
2. choose Alternatives example 
3. In Color palette choose the color item and change its value to empty

#### Expected behavior

Form validation should only show one error message if one the items in anyOf do not match it's requirement.

#### Actual behavior

Form validation shows one error for each anyOf item.

![image](https://user-images.githubusercontent.com/26364566/67403828-c800f300-f5b2-11e9-83b9-0f3db120649a.png)

### Version

1.8.0

**Comment by KKS1** [comment]
HI @Benni2808 , one thing you can try is have a transformErrors handler, which does something like `_.uniqBy(errors, 'property')`. This will eliminate any redundant errors from your fields. Ensure to return the errors list back, for validations to keep working.
