### ISSUE TITLE
Additional properties are not submitted when nested and omit data enabled

### ISSUE THREAD

**Issue by hutch120** [rjsf-team/react-jsonschema-form#1497]
### Prerequisites

- [ x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Additional properties are not submitted when nested and omit data enabled. This only happens when it is nested.

### Steps to Reproduce

1. Goto [Playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJuZXN0ZWQiOnsibmV3S2V5IjoiTmV3IFZhbHVlIn19LCJzY2hlbWEiOnsidGl0bGUiOiJXcmFwcGVyIiwiZGVzY3JpcHRpb24iOiJBbiBleGFtcGxlIG9mIE5PVCB3b3JraW5nIGFkZGl0aW9uYWxQcm9wZXJ0aWVzIHdoZW4gbmVzdGVkIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsibmVzdGVkIjp7InR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6Ik5lc3RlZCIsImRlc2NyaXB0aW9uIjoiRW5hYmxlIE9taXQgZXh0cmEgZGF0YSwgYWRkIGEgcmVjb3JkIGFuZCBjbGljayBzdWJtaXQuLi4gc3VibWl0dGVkIGZvcm1EYXRhIGluIGNvbnNvbGUgaXMgZW1wdHkhIiwiYWRkaXRpb25hbFByb3BlcnRpZXMiOnRydWV9fX0sInVpU2NoZW1hIjp7InRhc2tzIjp7Iml0ZW1zIjp7ImRldGFpbHMiOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifX19fSwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjp0cnVlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6dHJ1ZSwibGl2ZU9taXQiOmZhbHNlfX0=)
2. Open console so you can see submit data when you click submit button.
3. Enable Omit extra data checkbox
4. Add an additional property (click plus button) 
5. Click submit
6. Check submitted formData in console ... it is empty (why?)

#### Expected behavior

Additional Properties submitted in form data.

#### Actual behavior

Nothing submitted.

### Version

Used online playground version.

![image](https://user-images.githubusercontent.com/1034955/67918396-47647700-fbf0-11e9-88f0-cc18e8f56102.png)

**Comment by epicfaace** [comment]
@CodeGains any thoughts on why this might be happening?

**Comment by achendrick** [comment]
@hutch120 did you ever find a workaround for this?

I'm having what I believe is the same issue as you can see with this [Playground Link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJvcHRpb25zIjp7fX0sInNjaGVtYSI6eyIkc2NoZW1hIjoiaHR0cDovL2pzb24tc2NoZW1hLm9yZy9kcmFmdC0wNy9zY2hlbWEiLCIkaWQiOiJodHRwOi8vZXhhbXBsZS5jb20vZXhhbXBsZS5qc29uIiwidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbIm9wdGlvbnMiXSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7Im9wdGlvbnMiOnsiJGlkIjoiIy9wcm9wZXJ0aWVzL29wdGlvbnMiLCJ0eXBlIjoib2JqZWN0IiwidGl0bGUiOiJPcHRpb25zIiwiZGVzY3JpcHRpb24iOiIiLCJhZGRpdGlvbmFsUHJvcGVydGllcyI6eyJ0eXBlIjoic3RyaW5nIn19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjp0cnVlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6dHJ1ZSwibGl2ZU9taXQiOnRydWV9fQ==).

I've traced it down to this line https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/Form.js#L164
Given when adding a new entry to an object it comes in with default, and of course if my form pre-populates with many entries for this field, the `_isEmpty` check at this line will never pass and the accumulator won't end up with this field.

#1419 introduced this line and may be worth looking at further.

If there is an alternative approach to have a key/value field in a form with JSON Schema I'd be happy to go that route instead but this is the only one I've seen (this is new to me).

**Comment by epicfaace** [comment]
here's a test I was writing for this:

```
    it.only("should rename formData key if key input is renamed in a nested object with omitExtraData=true and liveOmit=true", () => {
      const { node, onChange } = createFormComponent({
        schema: {
          type: "object",
          properties: {
            nested: {
              additionalProperties: { type: "string" }
            }
          }
        },
        formData: { nested: { key1: "value" } }
      }, {omitExtraData: true, liveOmit: true});

      const textNode = node.querySelector("#root_key1-key");
      Simulate.blur(textNode, {
        target: { value: "key1new" },
      });

      sinon.assert.calledWithMatch(onChange.lastCall, {
        formData: { nested: { key1new: "value" } }
      });
    });
```

**Comment by hutch120** [comment]
@achendrick Hi. so we applied this to a bunch of existing JSON configuration files and the config would not fit the schema correctly without using nested additional properties. So the workaround was to leave omitExtraData set to false. This is a shame because it means our saved configs are quite messy because when we do migrations, etc, they retain the old data. Anyway, it worked, so we left it. I'd be keen to revisit/test an update if it was available.

**Comment by saswat3115** [comment]
Please re check this fix. as when we implment if-else-then in rjsf few issues arising on additionalProperties + liveOmit
