### ISSUE TITLE
CSS problem when implementing rjsf to project

### ISSUE THREAD

**Issue by Johnnywashere** [rjsf-team/react-jsonschema-form#1500]
### Prerequisites
[x] I have read the documentation;

### Description
Hello! We have just added schema validation to our project, and after looking at the demo we wanted to implement rjsf as a second option of editing files next to our code editor.  
Sadly i have an issue where the form uses no more or less then the full window height. Either taking up more space then necessary or causing form to overflow past submit button.

#### Expected behavior

As shown in the demo:
![image](https://user-images.githubusercontent.com/18138409/68021935-12fdc300-fca3-11e9-8c2a-531646dcad46.png)

#### Actual behavior
Simple example showing wasted space:
![image](https://user-images.githubusercontent.com/18138409/68022170-d1b9e300-fca3-11e9-8cc8-136c87541bc0.png)

overflow example:
![image](https://user-images.githubusercontent.com/18138409/68022092-93bcbf00-fca3-11e9-833d-886d319e3d31.png)

### Version

1.8.0

**Comment by Johnnywashere** [comment]
First time creating a new issue. Please let me know if there's you want me to add.

**Comment by epicfaace** [comment]
Do you have a reproducible example you could share? This might have to do with the other CSS present in your project.

**Comment by Johnnywashere** [comment]
Ah i found the error on my end. We had moved from css to stylesheets month ago, but 1 file had not been removed and was interfering. I don't know how i missed that...

Thanks for the help!
