### ISSUE TITLE
Array of Custom Field Components does not get proper IDs

### ISSUE THREAD

**Issue by nabeards** [rjsf-team/react-jsonschema-form#1503]
### Description

The [1.8.0](https://github.com/rjsf-team/react-jsonschema-form/commit/20796c20383980a8b62b66221cc03b3d6b0e7539#diff-443373237a67e0fe395c3da27e3595ebR115) fix does not work on Arrays of Custom Field Components.

### Steps to Reproduce

1. Create a custom field component to display a number
2. Add an array of these to your form
3. Attempting to delete any entry in the array only removes the last item in the array

#### Expected behavior

Delete the matching array item (which works if you don't use a custom field component).

#### Actual behavior

The last entry in the array is deleted. There are no IDs assigned to the custom field components when they are added to the DOM.

### Version

1.8.0

**Comment by epicfaace** [comment]
Why did you expect "IDs assigned to the custom field components when they are added to the DOM"? #1335 just makes sure that keys are assigned to the components. Did thhis behavior change since the fix was added?

**Comment by nabeards** [comment]
@epicfaace no, it has been broken for a long time. I guess I just hoped it was fixed throughout. The documentation for [Custom Field Components](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/#custom-field-components) has no mention that we need to manage the IDs ourselves, nor does it show the IDs being assigned in the example. Am I missing the documentation section that shows proper ID handling for these components?

**Comment by epicfaace** [comment]
Yeah, there is no section explaining this. I think the thing is, many times in React you don't necessarily need to assign IDs to input components because their values are already controlled by React. Could you explain a use case for needing to assign IDs @nabeards ? (this would make for a good example to add in the documentation)

**Comment by nabeards** [comment]
@epicfaace please read the bug description. That’s my use case.

**Comment by epicfaace** [comment]
I don't get it, what does needing to assign IDs have to do with "Delete the matching array item"?

**Comment by nabeards** [comment]
I'm not sure how else to describe the bug. Using Custom Field Components in an array doesn't work properly (clicking on the red X next to any element only deletes the last entry in the array), so adding properly managed IDs to arrays of Custom Field Components will fix it.

**Comment by epicfaace** [comment]
Can you create a sample reproduction on jsfiddle (https://jsfiddle.net/5wgq2noj/)? That would help to reproduce the issue.

**Comment by nabeards** [comment]
After testing this with a generic fiddle, I found that it does work properly. There must have been something else causing it in my code, but now the issue has completely disappeared and I am at a loss. Thanks for your help and patience!
