### ISSUE TITLE
Programmatic submit using Material-ui theme

### ISSUE THREAD

**Issue by andrew-oreshko** [rjsf-team/react-jsonschema-form#1504]
Hello )
I'm using material-ui version and I can't manage to submit form programmatically, because react ref doesn't contain .submit() method for some reason. 

This is how I import it
![image](https://user-images.githubusercontent.com/56826270/68429691-9f3a4980-01bf-11ea-9cbc-fb0028c96780.png)

This is how I use it

![image](https://user-images.githubusercontent.com/56826270/68429777-cd1f8e00-01bf-11ea-94ea-d21ad65aa743.png)

But when i tried to use regular version of library without basically using the material theme, i found .submit() method in ref

Why do I need this ? I have to do different things depending on the button, so that one button make one request and another button make another request (essentially i try to emulate behavior of two submit buttons here)

Please help )

**Comment by andrew-oreshko** [comment]
Ah, i found this https://github.com/rjsf-team/react-jsonschema-form/issues/1405

I guess, that explains my problem )

**Comment by epicfaace** [comment]
Closing this so we can track the issue in #1405 then.
