### ISSUE TITLE
Form not get re-rendered, any changes made in schema definitions

### ISSUE THREAD

**Issue by baskar383** [rjsf-team/react-jsonschema-form#1509]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
### Description

Once `Form` Rendered with schema definition, after any changes made in the schema definition, 
Form not re-rendered with the changed definition of props  

### Steps to Reproduce

1. Load the simple form with select input contain `enum` option empty 
```
{
  "type": "object",
  "title": "Number fields & widgets",
  "properties": {
    "numberEnum": {
      "type": "number",
      "title": "Number enum",
      "enum": []
    }
  }
}
```

2. After I have changed the schema definition, by giving the `enum values` for the select input 
```
{
  "type": "object",
  "title": "Number fields & widgets",
  "properties": {
    "numberEnum": {
      "type": "number",
      "title": "Number enum",
      "enum": [1,2,3]
    }
  }
}
```

3. Form not get re-rendered, It shows the options as empty.

#### Expected behavior

Any changes made in schema definition as, like the above example, Form needs to get rendered with newly changed schema definition, it helps to use the form more effectively

#### Actual behavior

In Existing, Any changes made in schema definition, after Form loaded, Forms not re-rendered with new props

### Version
1.8.0

**Comment by epicfaace** [comment]
How are you changing the schema definition? Could you make a reproducible example on something like jsfiddle (https://jsfiddle.net/epicfaace/9p17e2qx/)?

**Comment by baskar383** [comment]
Thnx for help us. We added the sample demo in JsFiddle (https://jsfiddle.net/john0075081/cuxfzLv4). In the demo, we have used setTimeout but in our original code, we used ajax call to get data from the database.

**Comment by chargrove** [comment]
I'm having a related issue with the uiSchema.

https://codepen.io/logicpill/pen/YzzJLjW

The changes to the uiSchema are updated through an individual form field until the SchemaField component.  The DefaultTemplate beneath the SchemaField is where the first place that the uiSchema is not updated.

Selecting the SchemaField and triggering a forceUpdate() on the console will allow the dropdown to update.  Sending a forceUpdate() on the top level of the form itself does not update the dropdown.

**Comment by baskar383** [comment]
Did you get any chance to check this issue?

**Comment by chargrove** [comment]
@baskar383 Try replacing the setTimeout and initialization of schema following it.  I've added lodash but you could replace _.cloneDeep() with another method to recreate the data in an entirely new object like JSON.parse(JSON.stringify()).

```
setTimeout(function () {
            const { schema } = _.cloneDeep(this.state);
```

**Comment by baskar383** [comment]
Thnx for the solution, Its working fine for **single select option**. But not working for **Multiple options** in a schema definition. Try this (https://jsfiddle.net/john0075081/7k26dyvz/),  we updated the sample code in JSFiddle.

**Comment by chargrove** [comment]
The example with multiple is running the callback at the same time.  Each version of the function makes a new copy of state and then saves own updated version (overwriting whichever came first). 

If you modify the function to use the callback form of setState, you can make it work.  The other option is to just update the part of the schema that has changes.

```
   const UpdateShopOption = ()=>{
     setState((prevState)=>{
         const { basicSchema } =  _.cloneDeep(prevState);
         for (let i = 0; i <= 10; i++) {
           basicSchema.schema.properties.categories.enum.push(`shop{i}`); // Options assign
         }
         return {...state, basicSchema};
			});
   }
```

**Comment by baskar383** [comment]
Thanks again for your help. It's working fine in that case. But we're getting a new issue when we use **multiple forms** on that page. Please check this URL (https://jsfiddle.net/john0075081/acjue40w/)  and let me know.

**Comment by jmaister** [comment]
It worked for me by using the cloneDeep from lodash. The schema must be a new object for React to fire a repaint of the form, otherwise it will not.

    const [schema, setSchema] = useState(initialSchema);

    fetch(...).then((values) => {
        const s = _.cloneDeep(schema);
        const oneOf = values.map(v => { 
             return {type: "number", enum: [v], title: v.name};
        });
        s.properties.clients.entityId.oneOf = 
        setSchema(s);
    });

    return <Form
                schema={schema} 
                 ...>;

**Comment by baskar383** [comment]
@jmaister 

Thnx for the solution, Its working fine for single form in a state, but not working for multiple forms in a single state. can you kindly refer sample code (https://jsfiddle.net/john0075081/acjue40w/), which i updated in JSFiddle.

**Comment by jmaister** [comment]
I've found that for multiple updates of "oneOf" was not working for me either.

The problem was a race condition of multiple fetch() modifying the schema at the same time, so only one of the was visible.

I created a function to execute all fetch promises, then update the schema:

	export function useOneOf(schema, setSchema, lookups) {
	    useEffect(() => {
		Promise.all(lookups.map((lookup) => {
                    // Fire all requests
		    const url = lookup[0];
		    return fetch(url).then((response) => { return response.json() });
		})).then((allValues) => {
                    // Receive values and update oneOf
		    const schemaCopy = cloneDeep(schema);
		    allValues.forEach((values, index) => {
		        const oneOf = values.map(v => { 
		            return {type: "number", enum: [v.entityId], title: v.name};
		        });
		        const path = lookups[index][1];
		        const property = get(schemaCopy, path)
		        property.oneOf = oneOf;
		    });
		    setSchema(schemaCopy);
		})
	    }, [lookups[0][0]]);
	};

Then I call it from the form:

    const [schema, setSchema] = useState(initialSchema);
    useOneOf(schema, setSchema, [
        ['/api/clients', 'properties.client.properties.entityId'],
        ['/api/products', 'properties.billLines.items.properties.product.properties.entityId'],
        ['/api/taxes', 'properties.billLines.items.properties.tax.properties.entityId']
    ]);

    <Form schema={schema} ... />

I hope this helps.

**Comment by baskar383** [comment]
@jmaister 
Thnx for the help, We are using **Apollo GQL** for fetching data, So we need to change some logic in the solution which you have given, We will check and update you...
