### ISSUE TITLE
2 forms submitted by one submit button

### ISSUE THREAD

**Issue by ITsolution-git** [rjsf-team/react-jsonschema-form#1510]
I have 2 forms, 1 is in main page, 1 is in modal box.

When submitting by clicking button in modalbox, modal form is submitted successfully but weird thing is to submit main page form. 

How can I submit a form separately?

**Comment by epicfaace** [comment]
This was fixed by #1336 -- what version of rjsf are you using?

**Comment by ITsolution-git** [comment]
I am using this one. 
react-jsonschema-form@1.6.1

**Comment by ITsolution-git** [comment]
2.0.0 is working fine. 

Thanks.
