### ISSUE TITLE
ExtraErrors prop doesn't merge with error schema

### ISSUE THREAD

**Issue by Andi24** [rjsf-team/react-jsonschema-form#1516]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
Hi,

@Skyscanner we have a fairly complex use case of your library and have been trying to harness asynchronous error via the `extraErrors` prop. I've debugged the behaviour in Chrome and it looks like the `errors` array [here](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/Form.js#L76) doesn't end up containing the errors passed in.

The props we're using on the form are:
- `showErrorList={false}`
- `additionalMetaSchemas={JsonSchemaDraft4}`
- `highlightFirstError={true}`
- `noHtml5Validate={true}`

This means that the code path wouldn't hit [this line](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/Form.js#L69) due to `liveValidate` being `false`. However, even when enabling `liveValidate` we don't get the errors array with the fields we've passed in. We've tried invalidating completely different fields and that doesn't work either. We do have an extra layer of custom validation but we don't believe this would be interfering with the internal errors output by the library.

The feature seems to work fine in your playground with or without live validation enabled so at this point I'm reaching out to understand whether we are doing something wrong or whether this is a genuine bug. 

#### Expected behavior

`extraErrors` are merged into `errorSchema` and output as an array of errors.

#### Actual behavior

The `errors` array is empty.

### Version
`1.8.0`

**Comment by epicfaace** [comment]
Could you make a jsfiddle example (https://jsfiddle.net/epicfaace/9p17e2qx/)? That would help to isolate the issue.

**Comment by somay** [comment]
The `extraErrors` feature doesn't include in the version of 1.8.0.
See the release note of the version 2.0.0-alpha.1.

**Comment by thclark** [comment]
Definitely a bug. It's not related to the `liveValidate` prop; I can reproduce with and without that prop [in this fiddle](https://jsfiddle.net/afLp8cre/)
