### ISSUE TITLE
Dependency in a nested schema object

### ISSUE THREAD

**Issue by zmeecer** [rjsf-team/react-jsonschema-form#1520]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Dependency in a nested object and in a plain object works differently

### Steps to Reproduce

1. Open a typical example from https://react-jsonschema-form.readthedocs.io/en/latest/dependencies/#dynamic in Playground by the following [link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6IlBlcnNvbiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7IkRvIHlvdSBoYXZlIGFueSBwZXRzPyI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJObyIsIlllczogT25lIiwiWWVzOiBNb3JlIHRoYW4gb25lIl19fSwicmVxdWlyZWQiOlsiRG8geW91IGhhdmUgYW55IHBldHM/Il0sImRlcGVuZGVuY2llcyI6eyJEbyB5b3UgaGF2ZSBhbnkgcGV0cz8iOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsiRG8geW91IGhhdmUgYW55IHBldHM/Ijp7ImVudW0iOlsiTm8iXX19fSx7InByb3BlcnRpZXMiOnsiRG8geW91IGhhdmUgYW55IHBldHM/Ijp7ImVudW0iOlsiWWVzOiBPbmUiXX0sIkhvdyBvbGQgaXMgeW91ciBwZXQ/Ijp7InR5cGUiOiJudW1iZXIifX0sInJlcXVpcmVkIjpbIkhvdyBvbGQgaXMgeW91ciBwZXQ/Il19LHsicHJvcGVydGllcyI6eyJEbyB5b3UgaGF2ZSBhbnkgcGV0cz8iOnsiZW51bSI6WyJZZXM6IE1vcmUgdGhhbiBvbmUiXX0sIkRvIHlvdSB3YW50IHRvIGdldCByaWQgb2YgYW55PyI6eyJ0eXBlIjoiYm9vbGVhbiJ9fSwicmVxdWlyZWQiOlsiRG8geW91IHdhbnQgdG8gZ2V0IHJpZCBvZiBhbnk/Il19XX19fSwidWlTY2hlbWEiOnt9LCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19)

    And change the dropdown value to "Yes, %something%" - the validation works only for the dependent field and that's totally fine

2. Open the same schema, but with a wrapper object by the following [link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ3cmFwcGVyIjp7IkRvIHlvdSBoYXZlIGFueSBwZXRzPyI6IlllczogT25lIn19LCJzY2hlbWEiOnsidGl0bGUiOiJQZXJzb24iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ3cmFwcGVyIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7IkRvIHlvdSBoYXZlIGFueSBwZXRzPyI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJObyIsIlllczogT25lIiwiWWVzOiBNb3JlIHRoYW4gb25lIl19fSwicmVxdWlyZWQiOlsiRG8geW91IGhhdmUgYW55IHBldHM/Il0sImRlcGVuZGVuY2llcyI6eyJEbyB5b3UgaGF2ZSBhbnkgcGV0cz8iOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsiRG8geW91IGhhdmUgYW55IHBldHM/Ijp7ImVudW0iOlsiTm8iXX19fSx7InByb3BlcnRpZXMiOnsiRG8geW91IGhhdmUgYW55IHBldHM/Ijp7ImVudW0iOlsiWWVzOiBPbmUiXX0sIkhvdyBvbGQgaXMgeW91ciBwZXQ/Ijp7InR5cGUiOiJudW1iZXIifX0sInJlcXVpcmVkIjpbIkhvdyBvbGQgaXMgeW91ciBwZXQ/Il19LHsicHJvcGVydGllcyI6eyJEbyB5b3UgaGF2ZSBhbnkgcGV0cz8iOnsiZW51bSI6WyJZZXM6IE1vcmUgdGhhbiBvbmUiXX0sIkRvIHlvdSB3YW50IHRvIGdldCByaWQgb2YgYW55PyI6eyJ0eXBlIjoiYm9vbGVhbiJ9fSwicmVxdWlyZWQiOlsiRG8geW91IHdhbnQgdG8gZ2V0IHJpZCBvZiBhbnk/Il19XX19fX19LCJ1aVNjaGVtYSI6e30sImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

    And change the dropdown value to "Yes, %something%" - the validation works for both fields and it looks pretty weird error message

#### Expected behavior

The same behavior for nested schema - an error message only for the dependent field

#### Actual behavior

Different validation handling for nested/plain schema 

### Version

1. Reproduced in Playground
2. Or from my react project: `"react-jsonschema-form": "^1.8.0"`

**Comment by epicfaace** [comment]
Thanks for reporting. Interestingly, the error messages go away once a number is typed in the "How old is your pet?" textbox...

**Comment by jgroth** [comment]
Any news on this? I'm having the same issues

**Comment by jensgustafsson** [comment]
What's the status on this issue? I'm having the same issue :/

**Comment by magnusfagerlund** [comment]
I am also having the same issue. Would be great if this got some attention!
