### ISSUE TITLE
Help with Uischema

### ISSUE THREAD

**Issue by kimFrost** [rjsf-team/react-jsonschema-form#1524]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I'm trying to create a custom widget, but it doesn't render when nested in an object. I know this is an issue with the uischema, but I don't understand if it is not possible to declare a global type for the entire tree?

### Steps to Reproduce
[Link to playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJzb21ldGhpbmciOnt9fSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJyZXF1aXJlZCI6W10sInByb3BlcnRpZXMiOnsidGVzdCI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJUZXN0In0sInNvbWV0aGluZyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0ZXN0Ijp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlRlc3QifX19fX0sInVpU2NoZW1hIjp7InRlc3QiOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifX0sImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

#### Expected behavior

Both widgets would render as textarea

#### Actual behavior

Only the shallow nested are rendered as textarea

**Comment by epicfaace** [comment]
No, you can't. For now, you'd have to do this in the uiSchema:

```json
{ "something": {
  "test": {
    "ui:widget": "textarea"
  }
}
}
```
