### ISSUE TITLE
Definition in $ref via files

### ISSUE THREAD

**Issue by FBurner** [rjsf-team/react-jsonschema-form#1533]
### Prerequisites

- [x ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

In Most format definitions types are imported from files via $ref, this module should allow this because its fairly standard and to rework a schema to have everything in one file would contradicts the extensability and also the proper use of the external definition.

To expect it in a field definitions is not best practice.

**Comment by epicfaace** [comment]
Hi @FBurner , JSON schema does not handle working with multiple files because it does not come with the logic of how to fetch another file. If you have suggestions for the JSON Schema spec, I'd suggest you propose it at https://github.com/json-schema-org/json-schema-spec/. There _is_ an issue about fetching schemas over HTTP URLs, though, which might fit your purpose (#1512).

**Comment by FBurner** [comment]
URLs would help also but in general maybe i was quite new to json schema but i want to resolve external references.

Its uses here in this project https://hropenstandards.org/download/7646/
I mean i could merge it but that would make an update really heavy.

**Comment by epicfaace** [comment]
Can you give an example of what such a schema with external references might look like?

**Comment by FBurner** [comment]
I had put it into my last comment https://hropenstandards.org/download/7646/

**Comment by epicfaace** [comment]
Yeah, you'll need to resolve it yourself, because there's no way for the schema to know where / how to retrieve `codelist`.
