### ISSUE TITLE
full material-ui playground for all feature

### ISSUE THREAD

**Issue by mnlbox** [rjsf-team/react-jsonschema-form#1536]
Hi guys,
It seems that material-ui theme is ready to use but it seems the playground still not complete and many examples not available in [material-ui playground](https://cybertec-postgresql.github.io/rjsf-material-ui/). Any plan to fix this?

**Comment by epicfaace** [comment]
Yes, ideally we would show the material UI playground in https://rjsf-team.github.io/react-jsonschema-form/ and have an option to switch themes between Bootstrap / Material UI.
