### ISSUE TITLE
Add support for React Semantic UI

### ISSUE THREAD

**Issue by jacqueswho** [rjsf-team/react-jsonschema-form#1537]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I see you now support Material-UI, would you be interested in supporting [React Semantic UI](https://react.semantic-ui.com/). We currently make use of your component but use Semantic UI. If you want we could also make use of your With Theme component to wrap React Semantic UI components and include it for you in the future

### Steps to Reproduce

Will look at how Material UI theme was done and replicate

#### Expected behavior

Still, use your core library but represent the components using React Semantic UI

#### Actual behavior

Still, use your core library but represent the components using React Semantic UI

### Version

2.0.0-alpha.1

**Comment by epicfaace** [comment]
Yeah, that would be great!

**Comment by thclark** [comment]
@jacqueswho one tip is to look at the way it's done in the [rjsf-material-ui](https://github.com/cybertec-postgresql/rjsf-material-ui) project, as opposed to a lot of the other rjsf/material projects out there, since this one properly uses the newer `withTheme()` abilities of rjsf!

**Comment by epicfaace** [comment]
Yes, the aforementioned project was actually added to this repo here: https://github.com/rjsf-team/react-jsonschema-form/tree/master/packages/material-ui

**Comment by thclark** [comment]
Aha, thank you @epicfaace - is that now being maintained here as opposed to the original location? If so, I'll get them to add a note in the README to prevent others making the same mistake...

**Comment by jacqueswho** [comment]
@epicfaace Hi do I update your playground as an option to use the semantic package option or do you after I have pushed the semantic-ui package

**Comment by rlingineni** [comment]
I think this is a great idea! I had the same requirement to use Semantic UI. However, my project doesn't use the `semantic-react` project. And I didn't want to add it as a dependency. I just use the `semantic.css` directly.   

If anyone else is in the same boat - here's a [super simple gist](https://gist.github.com/rlingineni/bf8f615d83f1724959fe84e395df0f8e)  that you can use to get started with overriding some of the builtin templates and use semantic-ui.

**Comment by epicfaace** [comment]
@rlingineni hmm... couldn't you still use the `semantic-ui-react` package without necessarily using `semantic-ui-css` -- I believe you can still use it with your own `semantic.css` just by importing it.

**Comment by rlingineni** [comment]
@epicfaace -  I wanted to use ‘semantic.min.css’ without the react package. [instead of custom semantic react components, I just wanted the css].  So all I wanted to do was override the div classes with semantic ones. This library seems well written with extensibility in mind, so I was able to do that for my use case with passing in via Template Props.

**Comment by epicfaace** [comment]
Fixed by #1585. Thanks for all your work @jacqueswho !
