### ISSUE TITLE
Remove all array buttons in schema

### ISSUE THREAD

**Issue by aarizti** [rjsf-team/react-jsonschema-form#1538]
### Prerequisites

- [ x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I would like to achieve the same functionality as using:

`"ui:options": {
      "addable": false,
      "orderable": false,
      "removable": false
    }`

On all array fields (including nested array fields), based on a prop.
Is there any support for it? If not, how could it be implemented, given a json and ui schema?

I don't want to hide the buttons through css, as that would not accommodate the template in the best responsive way (inputs taking more space due to the missing button controls).

Thanks!

**Comment by epicfaace** [comment]
For now, you would have to make your own custom `ArrayFieldTemplate` to do this.

**Comment by aarizti** [comment]
Makes sense, thanks for the quick answer!
