### ISSUE TITLE
Some Questions about Styles and adding custom items to form.

### ISSUE THREAD

**Issue by sali1982** [rjsf-team/react-jsonschema-form#1540]
I have Questions not really an issue.
####
1. Is it possible to style all the forms fields as we want?
2. Is it possible to add more form attributes to it if it is missing some sort of form item? Or we are really limited to what exist?
3. Can we use CSS mudules to send styles to it?

**Comment by epicfaace** [comment]
1. You can add the `classNames` property in the uiSchema for each field you want to style. Alternatively, you could make a custom widget or field.
2. You would need to create a custom widget or field to do this.
3. By default, you can only use css classes, but you could use css modules with a custom widget / field.

**Comment by sali1982** [comment]
What kind of validation it has? 
I can see minLenght and so on. But I do not see any regex, multiplicity validation, relational validation, or a way to do formula validation or Custom validation?

**Comment by sali1982** [comment]
And also, if we do want to use custom widget so we can have the CSS Modules and so on, will this make the code longer? because we are really trying to generate everything (textbox and so on) one by one. Then what is the point of using this library? Will it be still useful? In what terms?

**Comment by epicfaace** [comment]
You can use all kinds of validation that JSON Schema supports: https://json-schema.org/understanding-json-schema/

And yes, you would need to use custom widgets, but you could base it off of the existing widgets in this codebase. What this library gives is the JSON schema validation and actually dynamically _rendering_ your custom widgets at the right place based on your JSON schema.
