### ISSUE TITLE
Formdata data is not passed to custom field

### ISSUE THREAD

**Issue by taspapak** [rjsf-team/react-jsonschema-form#1541]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1.Component where Form exists: 

const widgets = {
  myCustomWidget: Measurements,
}
.....
Html render:
Form  fields={fields}  schema={schema} uiSchema={uiSchema} formData={formData} widgets={widgets}>

2. Custom field Measurements:
constructor(props) {
     this.state = {...props.formData,fetchedData:[]};
}

componentDidMount(){
   #Want to get the values from the formData here
   this.props 
}

#### Expected behavior
FormData fields data to be passed on custom field.

#### Actual behavior
They are not passed.

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by taspapak** [comment]
Hello all, 

I have created a custom field for plotting several data that come from the formData. When the custom field is rendered the props contain a lot of the expected properties (registry, schema, formContext etc.) but I cannot see the data themselves. I want to access the values of two input fields of the form but they are not visible to the custom field.

Any suggestions?

Thanks

**Comment by epicfaace** [comment]
Hey @taspapak , the information you gave is not enough to reproduce the issue and see where the error is. Could you make a jsfiddle (based on https://jsfiddle.net/5wgq2noj/) and send over the link?

**Comment by taspapak** [comment]
Hi @epicfaace, indeed the info was not enough sorry for this. I have simplified my case but still you can see the issue. So, inside the HPOTree class I would like to access the values of the formData e.g the value of the name input [https://jsfiddle.net/vLforjy1/1/].

**Comment by harsimranb** [comment]
@epicfaace Any thoughts on this?  I am trying to access the entire form data inside a custom widget - similar to what @taspapak is doing.

**Comment by harsimranb** [comment]
@epicfaace I gave the code a brief look, I'm thinking about adding `formData` to the [FieldComponent](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/fields/SchemaField.js#L284).  It seems we're already passing formData to [_AnyOfField](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/fields/SchemaField.js#L368) and [_OneOfField](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/fields/SchemaField.js#L386).

If this looks good to you, I can create a PR to take this on.

**Comment by epicfaace** [comment]
I see... thanks for the explanation @taspapak and the bump @harsimranb. One way you could do this now is to add the `formData` as part of the `formContext`. Here's an example:

https://jsfiddle.net/etn6kw72/

Given that we can already do it this way, I don't know if there's a really good reason to give access to formData to custom widgets by default.
Given
