### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by metamn** [rjsf-team/react-jsonschema-form#1543]
Hey everyone,

And congrats for the great work done.

I've started to use the library and it seems to be very confusing. There are plenty of examples but hard to figure out how to do things for your own use case.

For example I want a list of checkboxes which displays text on screen (`Agriculture`) but returns numbers (`?sectors=1,3` instead of `?sectors=agriculture, ...`). For that I'm receiving an intimidating error message: `Error: No widget "checkboxes" for type "number"`

So the question is: Is this library covers all possible use cases? Or there are some kind of limitations?

Are there more thorough examples, forums, etc where we can learn from each other? Without bothering here the contributors.

The next question is regarding the high number of issues: Does this library is used in production?

Thank you very much,
Keep up!

**Comment by epicfaace** [comment]
I don't see the issue with checkboxes and numbers -- see [this playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJsaXN0T2ZTdHJpbmdzIjpbImZvbyIsImJhciJdLCJtdWx0aXBsZUNob2ljZXNMaXN0IjpbMSwyLDMsNF0sImZpeGVkSXRlbXNMaXN0IjpbIlNvbWUgdGV4dCIsdHJ1ZSwxMjNdLCJtaW5JdGVtc0xpc3QiOlt7Im5hbWUiOiJEZWZhdWx0IG5hbWUifSx7Im5hbWUiOiJEZWZhdWx0IG5hbWUifSx7Im5hbWUiOiJEZWZhdWx0IG5hbWUifV0sImRlZmF1bHRzQW5kTWluSXRlbXMiOlsiY2FycCIsInRyb3V0IiwiYnJlYW0iLCJ1bmlkZW50aWZpZWQiLCJ1bmlkZW50aWZpZWQiXSwibmVzdGVkTGlzdCI6W1sibG9yZW0iLCJpcHN1bSJdLFsiZG9sb3IiXV0sInVub3JkZXJhYmxlIjpbIm9uZSIsInR3byJdLCJ1bnJlbW92YWJsZSI6WyJvbmUiLCJ0d28iXSwibm9Ub29sYmFyIjpbIm9uZSIsInR3byJdLCJmaXhlZE5vVG9vbGJhciI6WzQyLHRydWUsImFkZGl0aW9uYWwgaXRlbSBvbmUiLCJhZGRpdGlvbmFsIGl0ZW0gdHdvIl19LCJzY2hlbWEiOnsiZGVmaW5pdGlvbnMiOnsiVGhpbmciOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsibmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6IkRlZmF1bHQgbmFtZSJ9fX19LCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJsaXN0T2ZTdHJpbmdzIjp7InR5cGUiOiJhcnJheSIsInRpdGxlIjoiQSBsaXN0IG9mIHN0cmluZ3MiLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6ImJhemluZ2EifX0sIm11bHRpcGxlQ2hvaWNlc0xpc3QiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJBIG11bHRpcGxlIGNob2ljZXMgbGlzdCIsIml0ZW1zIjp7InR5cGUiOiJudW1iZXIiLCJlbnVtIjpbMSwyLDMsNF19LCJ1bmlxdWVJdGVtcyI6dHJ1ZX0sImZpeGVkSXRlbXNMaXN0Ijp7InR5cGUiOiJhcnJheSIsInRpdGxlIjoiQSBsaXN0IG9mIGZpeGVkIGl0ZW1zIiwiaXRlbXMiOlt7InRpdGxlIjoiQSBzdHJpbmcgdmFsdWUiLCJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6ImxvcmVtIGlwc3VtIn0seyJ0aXRsZSI6ImEgYm9vbGVhbiB2YWx1ZSIsInR5cGUiOiJib29sZWFuIn1dLCJhZGRpdGlvbmFsSXRlbXMiOnsidGl0bGUiOiJBZGRpdGlvbmFsIGl0ZW0iLCJ0eXBlIjoibnVtYmVyIn19LCJtaW5JdGVtc0xpc3QiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJBIGxpc3Qgd2l0aCBhIG1pbmltYWwgbnVtYmVyIG9mIGl0ZW1zIiwibWluSXRlbXMiOjMsIml0ZW1zIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL1RoaW5nIn19LCJkZWZhdWx0c0FuZE1pbkl0ZW1zIjp7InR5cGUiOiJhcnJheSIsInRpdGxlIjoiTGlzdCBhbmQgaXRlbSBsZXZlbCBkZWZhdWx0cyIsIm1pbkl0ZW1zIjo1LCJkZWZhdWx0IjpbImNhcnAiLCJ0cm91dCIsImJyZWFtIl0sIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoidW5pZGVudGlmaWVkIn19LCJuZXN0ZWRMaXN0Ijp7InR5cGUiOiJhcnJheSIsInRpdGxlIjoiTmVzdGVkIGxpc3QiLCJpdGVtcyI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6IklubmVyIGxpc3QiLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6ImxvcmVtIGlwc3VtIn19fSwidW5vcmRlcmFibGUiOnsidGl0bGUiOiJVbm9yZGVyYWJsZSBpdGVtcyIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoibG9yZW0gaXBzdW0ifX0sInVucmVtb3ZhYmxlIjp7InRpdGxlIjoiVW5yZW1vdmFibGUgaXRlbXMiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6ImxvcmVtIGlwc3VtIn19LCJub1Rvb2xiYXIiOnsidGl0bGUiOiJObyBhZGQsIHJlbW92ZSBhbmQgb3JkZXIgYnV0dG9ucyIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoibG9yZW0gaXBzdW0ifX0sImZpeGVkTm9Ub29sYmFyIjp7InRpdGxlIjoiRml4ZWQgYXJyYXkgd2l0aG91dCBidXR0b25zIiwidHlwZSI6ImFycmF5IiwiaXRlbXMiOlt7InRpdGxlIjoiQSBudW1iZXIiLCJ0eXBlIjoibnVtYmVyIiwiZGVmYXVsdCI6NDJ9LHsidGl0bGUiOiJBIGJvb2xlYW4iLCJ0eXBlIjoiYm9vbGVhbiIsImRlZmF1bHQiOmZhbHNlfV0sImFkZGl0aW9uYWxJdGVtcyI6eyJ0aXRsZSI6IkEgc3RyaW5nIiwidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJsb3JlbSBpcHN1bSJ9fX19LCJ1aVNjaGVtYSI6eyJsaXN0T2ZTdHJpbmdzIjp7Iml0ZW1zIjp7InVpOmVtcHR5VmFsdWUiOiIifX0sIm11bHRpcGxlQ2hvaWNlc0xpc3QiOnsidWk6d2lkZ2V0IjoiY2hlY2tib3hlcyJ9LCJmaXhlZEl0ZW1zTGlzdCI6eyJpdGVtcyI6W3sidWk6d2lkZ2V0IjoidGV4dGFyZWEifSx7InVpOndpZGdldCI6InNlbGVjdCJ9XSwiYWRkaXRpb25hbEl0ZW1zIjp7InVpOndpZGdldCI6InVwZG93biJ9fSwidW5vcmRlcmFibGUiOnsidWk6b3B0aW9ucyI6eyJvcmRlcmFibGUiOmZhbHNlfX0sInVucmVtb3ZhYmxlIjp7InVpOm9wdGlvbnMiOnsicmVtb3ZhYmxlIjpmYWxzZX19LCJub1Rvb2xiYXIiOnsidWk6b3B0aW9ucyI6eyJhZGRhYmxlIjpmYWxzZSwib3JkZXJhYmxlIjpmYWxzZSwicmVtb3ZhYmxlIjpmYWxzZX19LCJmaXhlZE5vVG9vbGJhciI6eyJ1aTpvcHRpb25zIjp7ImFkZGFibGUiOmZhbHNlLCJvcmRlcmFibGUiOmZhbHNlLCJyZW1vdmFibGUiOmZhbHNlfX19LCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOnRydWUsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=).

Can you give a sample schema in which this is the case?

**Comment by epicfaace** [comment]
Closing this for now, but let me know if you have any other questions!
