### ISSUE TITLE
Question: Simpler way to add conditional descriptions?

### ISSUE THREAD

**Issue by MatinF** [rjsf-team/react-jsonschema-form#1544]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I need to be able to add a conditional description field after a property (a "warning text"). This text should only be shown if the property takes a specific value. 

The simplest way to achieve this would be by making the `description` field of the property change upon the change of the property value. This works, but I'm currently using the description field as part of a hover text comment, meaning that it is by default "hidden" from view unless the user hovers the field. This makes it less ideal for providing an explicit warning text. The `title` also can't be used because of space restrictions in the layout.

I'm able to achieve what I want by adding a new `null` property `warningtext` that changes description when the `keyFormat` property value changes, see below:

[playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJjb25uZWN0Ijp7InNlcnZlciI6eyJ3YXJuaW5ndGV4dCI6bnVsbCwia2V5Zm9ybWF0IjoxfX19LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiY29ubmVjdCI6eyJ0aXRsZSI6IkNvbm5lY3Rpdml0eSIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InNlcnZlciI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJrZXlmb3JtYXQiOnsidHlwZSI6ImludGVnZXIiLCJhbnlPZiI6W3sidHlwZSI6ImludGVnZXIiLCJ0aXRsZSI6IlBsYWluIiwiZW51bSI6WzBdfSx7InR5cGUiOiJpbnRlZ2VyIiwidGl0bGUiOiJFbmNyeXB0ZWQiLCJlbnVtIjpbMV19XX0sIndhcm5pbmd0ZXh0Ijp7InRpdGxlIjoiICIsInR5cGUiOiJudWxsIn19LCJkZXBlbmRlbmNpZXMiOnsia2V5Zm9ybWF0Ijp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7ImtleWZvcm1hdCI6eyJlbnVtIjpbMF19fX0seyJwcm9wZXJ0aWVzIjp7ImtleWZvcm1hdCI6eyJlbnVtIjpbMV19LCJ3YXJuaW5ndGV4dCI6eyJ0eXBlIjoibnVsbCIsInRpdGxlIjoiVGhpcyBpcyBhIHdhcm5pbmcgdGV4dCJ9fX1dfX19fX19fSwidWlTY2hlbWEiOnt9LCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOnRydWUsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

However, it's a rather clumsy solution if I want to add multiple of these warnings throughout my schema - and I'm a bit concerned with the support for the `null` type field across JSON schema tools. 

Is there a better/cleaner way of achieving the same result? I was thinking that there might be some extra "generic" field like description that could be used. I saw that JSON Schema draft 7 has a new `comment` property, but this does not seem to be usable for this purpose.

**Comment by MatinF** [comment]
Perhaps the ideal way to solve this in our particular case would be to enable the parsing of a `comment` field from the Schema so that it shows up in the browser. But not sure if this is something you think makes sense to do. See the JSON Schema: https://json-schema.org/understanding-json-schema/reference/generic.html

**Comment by epicfaace** [comment]
> This works, but I'm currently using the description field as part of a hover text comment, meaning that it is by default "hidden" from view unless the user hovers the field.

It seems like you're using a custom widget / template in this case to render the `description` field. Might it make sense in this case just to add your own custom JSON Schema key that is used for a conditional description? I guess it's probably not ideal, but not sure what other field from JSON schema we could use for this.

Don't think `comment` is appropriate for this, because [it says in the spec](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-8.3): "The value of this keyword MUST be a string.  Implementations MUST NOT present this string to end users."

**Comment by MatinF** [comment]
You're probably right about comment. I guess for us it's a matter of keeping our Rule Schema relatively tidy - we'd want to avoid adding additional property fields that have the unique purpose of displaying helpful info in the browser. I think we'll go with conditionally changing the description field and then using css `:contains` to modify the text to be more clear when there's a specific tag inside the description (e.g. "NOTE:")
