### ISSUE TITLE
Question - Custom ClassName on field in form

### ISSUE THREAD

**Issue by smuller97** [rjsf-team/react-jsonschema-form#1545]
### Prerequisites
I have read the documentation on the topic, where you add custom ClassName field to form - fields: https://react-jsonschema-form.readthedocs.io/en/latest/form-customization/#custom-css-class-names 

Here is the code where I try to add custom classes to the inputfields: https://repl.it/@smuller97/form-json-schema

### Description
I can't add custom classNames to the react component, even though I followed the documentation by adding a uiSchema

#### Expected behavior

I expected the className to be added to the input-fields in the form when I follow the documentation. 

#### Actual behavior

Nothing happened - There was no className added to the inputfield, so the styling wasn't added. 

### Version

The version used is: 
          "react-jsonschema-form": "^2.0.0-alpha.1",

**Comment by WhileTrueEndWhile** [comment]
Hi,

please try something like this:

```
const uiSchema = {
  agree: {
    classNames: "customClassName"
  },

  date: {
    classNames: "customClassName"
  },

  firstName: {
    classNames: "customClassName"
  },

  lastName: {
    classNames: "customClassName"
  },

  email: {
    classNames: "customClassName"
  }
};
```

For a more general solution it seems to be necessary to create a field template which adds a custom class name for each input:

https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/#field-template

You may want to use the `props.formContext` to configure the global input css class names:

https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/#the-formcontext-object

Good luck and happy coding.

**Comment by smuller97** [comment]
@WhileTrueEndWhile I got it to work. Thank you so much :) Merry Christmas and happy holidays :)
