### ISSUE TITLE
extraErrors prop doesn't get cleaned when reset

### ISSUE THREAD

**Issue by gbgdev** [rjsf-team/react-jsonschema-form#1547]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] I'm providing playground links demonstrating the issue.

### Description
I've tried to use the new `extraErrors` prop (introduced in version 2.0.0-alpha.1) to handle the errors for async back-end validation and found that once the errors are displayed they are never cleaned again (`extraErrors = {}`) unless the live validation feature is enabled.

In order to further understand this issue, I had a look at the library's source code and have an insight into the potential root cause of the problem. My guess is that it happens because the `extraErrors` property is being merged into the errorSchema (https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/Form.js#L75), which in turn is persisted in the state. And this ends up making it impossible to reset the extraErrors, as the merge operation wouldn't override the previous value when inputted with `{}`. 

### Steps to Reproduce

**Through playground**
1. Select the `ErrorSchema` sample on the playground (https://rjsf-team.github.io/react-jsonschema-form/)
2. Disable the "Live validation"
3. Try to clean up the `extraErrors` value in the editor

#### Expected behavior
Error messages should disappear from the form.

#### Actual behavior
Error messages are being kept.

**GIF that shows it works when live validation is enabled**
https://cl.ly/45d10cd07b66/Screen%252520Recording%2525202019-12-16%252520at%25252011.11%252520AM.gif

**GIF that shows the issue when live validation is disabled:**
https://d1sz9tkli0lfjq.cloudfront.net/items/2R2E3l362H2I0p2h2R3S/Screen%20Recording%202019-12-16%20at%2010.59%20AM.gif

In the references above you can see that adding a new error works, but cleaning doesn't.

### Version
2.0.0-alpha.1

Could anyone confirm if it is indeed an issue that the error messages don't disappear when the `extraErrors` is reset to `{}`? Should the live validation feature be a requirement for using this prop?

**Comment by pedramtalebi** [comment]
I have this problem as well.

**Comment by epicfaace** [comment]
@gbgdev You're right. I think the correct behavior is that it should update the error messages when `extraErrors` is changed, even if live validation is turned off.
