### ISSUE TITLE
Question: How to get data path in field template?

### ISSUE THREAD

**Issue by WhileTrueEndWhile** [rjsf-team/react-jsonschema-form#1548]
Hi,

thanks for this great project. The fact that is supports oneOf over objects is a awesome!

I created a custom field template component as described in https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/#field-template

My question is:
Is there a way to access or generate the data path the component is bound to from inside the component? (e.g. `.x.y.z`, like `property` in https://react-jsonschema-form.readthedocs.io/en/latest/validation/#custom-error-messages)

I need this, because when I move array elements the component instance is not bound to the data. The data flows, but the component instances remain stuck. So I need a way to track to which data my component is bound to currently (e.g. for a collapse state).

Best regards :-)

**Comment by epicfaace** [comment]
We don't have that functionality yet. I think the solution I suggested to #652 (exposing `pathSchema`) would work for this, though.

**Comment by WhileTrueEndWhile** [comment]
Thanks a lot. I ended up adding `data` attributes inside of the DOM (using object/array templates) which I read bottom to up to get the data path.
This is sufficient, but ugly. So I appreciate your intent to add this feature.
If somebody has the same problem, please reopen. I can report more details.

**Comment by Minekonst** [comment]
Hi,
I think I have a similar problem (see https://github.com/rjsf-team/react-jsonschema-form/issues/4059).
@WhileTrueEndWhile would you mind sharing some details how you solved the issue, if you still remember?
