### ISSUE TITLE
How to change property fields based on dependency on own pattern?

### ISSUE THREAD

**Issue by MatinF** [rjsf-team/react-jsonschema-form#1550]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I'm looking to change the `description` field of a string property, `endpoint`. The description field should be one thing when the endpoint value  starts with `http://` and another when it starts with `https://`. 

I'm able to change the details of _other property fields_ based on the above - but not the `endpoint` details itself. Am I missing something or is this not possible to achieve?

### Steps to Reproduce
See the following playground example: [Playground Example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJjb25uZWN0Ijp7InRpdGxlIjoiQ29ubmVjdGl2aXR5IiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiczMiOnsidGl0bGUiOiJTMyBTZXJ2ZXIgU2V0dGluZ3MiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJzZXJ2ZXIiOnsidGl0bGUiOiJTZXJ2ZXIiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJlbmRwb2ludCI6eyJ0aXRsZSI6IkVuZHBvaW50IiwiZGVzY3JpcHRpb24iOiJEZWZhdWx0IGRlc2NyaXB0aW9uIiwidHlwZSI6InN0cmluZyIsIm1heExlbmd0aCI6MTI4fX0sImRlcGVuZGVuY2llcyI6eyJlbmRwb2ludCI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJlbmRwb2ludCI6eyJwYXR0ZXJuIjoiXmh0dHBzOi8vW2EtekEtWjAtOV8vXFwuLV0rJCIsImRlc2NyaXB0aW9uIjoiVGVzdCBjYXNlOiBIVFRQUyJ9fX0seyJwcm9wZXJ0aWVzIjp7ImVuZHBvaW50Ijp7InBhdHRlcm4iOiJeaHR0cDovL1thLXpBLVowLTlfL1xcLi1dKyQiLCJkZXNjcmlwdGlvbiI6IlRlc3QgY2FzZTogSFRUUCJ9fX1dfX19fX19fX19LCJ1aVNjaGVtYSI6e30sImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

This has been tested in v2.0.

**Comment by epicfaace** [comment]
It seems like rjsf doesn't support this currently. It would probably make sense for it to have the behavior you described.

However, given that the "dependencies" keyword wasn't ever standardized in JSON Schema anyway, I wouldn't put it at a high priority. Would accept a PR changing the behavior though.
