### ISSUE TITLE
enum id and value options

### ISSUE THREAD

**Issue by sali1982** [rjsf-team/react-jsonschema-form#1552]
I need to have some checkbox or dropdowns that have value and id. When user selects one item in the list, it must also return the id of selected item, not only the value.
I can see we have enums. But enums are only array of string or numbers. How can I send id and expect to receive id on submit?

Also, we want to get dropdown list values from API. I assume it needs to be done separately and gets appended to the enum list.

**Comment by WhileTrueEndWhile** [comment]
https://react-jsonschema-form.readthedocs.io/en/latest/form-customization/#custom-labels-for-enum-fields

**Comment by epicfaace** [comment]
Thanks @WhileTrueEndWhile .

To get dropdown list values from the API, you would have to do an API call and then modify the schema with the appropriate enum values.

**Comment by ymoreiratiti** [comment]
> https://react-jsonschema-form.readthedocs.io/en/latest/form-customization/#custom-labels-for-enum-fields

Updated link

**Comment by mdornseif** [comment]
https://web.archive.org/web/20220624151421/https://react-jsonschema-form.readthedocs.io/en/latest/usage/single/#custom-labels-for-enum-fields


> > https://react-jsonschema-form.readthedocs.io/en/latest/form-customization/#custom-labels-for-enum-fields
> 
> Updated link here: https://react-jsonschema-form.readthedocs.io/en/latest/usage/single/#custom-labels-for-enum-fields

2023 Link here: https://rjsf-team.github.io/react-jsonschema-form/docs/json-schema/single#enumerated-values
