### ISSUE TITLE
Nested anyOf not working as expected

### ISSUE THREAD

**Issue by tdamsma** [rjsf-team/react-jsonschema-form#1554]
Using the playground, the schema below works as expected; 

<details><summary>Working schema</summary>

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "options1": {
            "type": "string",
            "enum": [
                "a",
                "b"
            ]
        },
        "options2": {
            "type": "string",
            "enum": [
                "c",
                "d"
            ]
        }
    },
    "type": "object",
    "properties": {
        "only1": {
            "title": "Only 1",
            "$ref": "#/definitions/options1"
        },
        "only2": {
            "title": "Only 2",
            "$ref": "#/definitions/options2"
        },
        "both": {
            "title": "1 and 2",
            "anyOf": [
                {
                    "$ref": "#/definitions/options1"
                },
                {
                    "$ref": "#/definitions/options2"
                }
            ]
        }
    }
}
```

</details>

![Screenshot 2019-12-20 at 16 03 17](https://user-images.githubusercontent.com/7870803/71263616-84243300-2342-11ea-8672-3f56852ac06b.png)

However for the schema below the last dropdown does not work

<details><summary>Not working schema with anyOf's</summary>

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "options1": {
            "type": "string",
            "anyOf": [
                {
                    "title": "A",
                    "const": "a"
                },
                {
                    "title": "B",
                    "const": "b"
                }
            ]
        },
        "options2": {
            "type": "string",
            "anyOf": [
                {
                    "title": "C",
                    "const": "c"
                },
                {
                    "title": "D",
                    "const": "d"
                }
            ]
        }
    },
    "type": "object",
    "properties": {
        "only1": {
            "title": "Only 1",
            "$ref": "#/definitions/options1"
        },
        "only2": {
            "title": "Only 2",
            "$ref": "#/definitions/options2"
        },
        "both": {
            "title": "1 and 2",
            "anyOf": [
                {
                    "$ref": "#/definitions/options1"
                },
                {
                    "$ref": "#/definitions/options2"
                }
            ]
        }
    }
}
```

</details>

![image](https://user-images.githubusercontent.com/7870803/71263659-9e5e1100-2342-11ea-8984-9e8acfcb01bd.png)

The last dropdown is missing here

**Comment by epicfaace** [comment]
Playground example for [working schema](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJib3RoIjoiYyIsIm9ubHkxIjoiYSIsIm9ubHkyIjoiZCJ9LCJzY2hlbWEiOnsiJHNjaGVtYSI6Imh0dHA6Ly9qc29uLXNjaGVtYS5vcmcvZHJhZnQtMDcvc2NoZW1hIyIsImRlZmluaXRpb25zIjp7Im9wdGlvbnMxIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbImEiLCJiIl19LCJvcHRpb25zMiI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJjIiwiZCJdfX0sInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im9ubHkxIjp7InRpdGxlIjoiT25seSAxIiwiJHJlZiI6IiMvZGVmaW5pdGlvbnMvb3B0aW9uczEifSwib25seTIiOnsidGl0bGUiOiJPbmx5IDIiLCIkcmVmIjoiIy9kZWZpbml0aW9ucy9vcHRpb25zMiJ9LCJib3RoIjp7InRpdGxlIjoiMSBhbmQgMiIsImFueU9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9vcHRpb25zMSJ9LHsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvb3B0aW9uczIifV19fX0sInVpU2NoZW1hIjp7fSwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjp0cnVlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19), [not working schema](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJvbmx5MSI6ImEiLCJvbmx5MiI6ImQifSwic2NoZW1hIjp7IiRzY2hlbWEiOiJodHRwOi8vanNvbi1zY2hlbWEub3JnL2RyYWZ0LTA3L3NjaGVtYSMiLCJkZWZpbml0aW9ucyI6eyJvcHRpb25zMSI6eyJ0eXBlIjoic3RyaW5nIiwiYW55T2YiOlt7InRpdGxlIjoiQSIsImNvbnN0IjoiYSJ9LHsidGl0bGUiOiJCIiwiY29uc3QiOiJiIn1dfSwib3B0aW9uczIiOnsidHlwZSI6InN0cmluZyIsImFueU9mIjpbeyJ0aXRsZSI6IkMiLCJjb25zdCI6ImMifSx7InRpdGxlIjoiRCIsImNvbnN0IjoiZCJ9XX19LCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJvbmx5MSI6eyJ0aXRsZSI6Ik9ubHkgMSIsIiRyZWYiOiIjL2RlZmluaXRpb25zL29wdGlvbnMxIn0sIm9ubHkyIjp7InRpdGxlIjoiT25seSAyIiwiJHJlZiI6IiMvZGVmaW5pdGlvbnMvb3B0aW9uczIifSwiYm90aCI6eyJ0aXRsZSI6IjEgYW5kIDIiLCJhbnlPZiI6W3siJHJlZiI6IiMvZGVmaW5pdGlvbnMvb3B0aW9uczEifSx7IiRyZWYiOiIjL2RlZmluaXRpb25zL29wdGlvbnMyIn1dfX19LCJ1aVNjaGVtYSI6e30sImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

**Comment by Saulzi** [comment]
Did you mean this to be any of, i.e. did you want 1 and 2 to have option a,b,c,d as options without the additional option 1 / option 2 dropdown?

**Comment by epicfaace** [comment]
I think it was meant to be any of with the option 1 / option 2 dropdown.

The only difference that is done from working -> not working is that the schemas with `enum` are switched to using `anyOf`. Both should render the same widget.

**Comment by tdamsma** [comment]
That is indeed exactly what I meant, thanks for clarifying

**Comment by tdamsma** [comment]
The current playground examples are working as expected, so this issue can be closed
