### ISSUE TITLE
Suggestion: Expose `default` prop to all fields and widgets

### ISSUE THREAD

**Issue by delyanr** [rjsf-team/react-jsonschema-form#1555]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

First of all, thanks for the awesome library/package.

I think it would be extremely powerful to expose default values from the schema to all fields and widgets, separate from `formData` (so that they remain unchanged regardless of user input). This would allow cool things, such as indicating changes vs. defaults, adding buttons to reset individual widgets to their defaults, and more.

Given that there already is a `getDefaultFormState` utility function that seems to work without given `formData` (although I haven't spent too much time studying it), would it not be possible to assign the defaults into a Form state variable and pass down?

**Comment by epicfaace** [comment]
That's an interesting idea, though I'm not sure how exactly this would work, given that defaults are not always unchanged regardless of user input. For example, if a default value is present in a value that is only triggered by a dependency, then it does change because of user input.

**Comment by epicfaace** [comment]
Maybe one way to do this would be to get the value returned from `computeDefaults`, then compare it with the existing formData, in order to see which fields have been added as a default.

https://github.com/rjsf-team/react-jsonschema-form/blob/64b89213061f1820c55a42d791446bc80ae8d94b/packages/core/src/utils.js#L156
