### ISSUE TITLE
Potential issue with oneOf/anyOf shared fields not resetting?

### ISSUE THREAD

**Issue by delyanr** [rjsf-team/react-jsonschema-form#1558]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When selecting between oneOf/anyOf options, which share identically named fields, their values do not reset. Therefore if a user wants to have an 'undefined' (empty) default value for a specific field, that is not possible. (Given that jsonschema specs do not allow explicit `undefined` values.)

### Steps to Reproduce

Please find the following [playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJvYmoiOnsib2JqXzEiOiJXZSBhcmUgaW4gb3B0aW9uICMxIn0sImFyciI6W3siYXJyXzEiOiJXZSBhcmUgaW5kZWVkIGluIG9wdGlvbiAjMSIsImFycl8yIjoiQXJlIHdlIHJlYWxseSBpbiBvcHRpb24gIzEgPyEifV19LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsIm9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7Im9iaiI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJvYmpfMSI6eyJ0eXBlIjoic3RyaW5nIn19fSwiYXJyIjp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImFycl8xIjp7InR5cGUiOiJzdHJpbmcifSwiYXJyXzIiOnsidHlwZSI6InN0cmluZyJ9fX19fSwiZGVmYXVsdCI6eyJvYmoiOnsib2JqXzEiOiJXZSBhcmUgaW4gb3B0aW9uICMxIn0sImFyciI6W3siYXJyXzEiOiJXZSBhcmUgaW5kZWVkIGluIG9wdGlvbiAjMSIsImFycl8yIjoiQXJlIHdlIHJlYWxseSBpbiBvcHRpb24gIzEgPyEifV19fSx7InByb3BlcnRpZXMiOnsib2JqIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im9ial8xIjp7InR5cGUiOiJzdHJpbmcifX19LCJhcnIiOnsidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiYXJyXzEiOnsidHlwZSI6InN0cmluZyJ9LCJhcnJfMiI6eyJ0eXBlIjoic3RyaW5nIn19fX19LCJkZWZhdWx0Ijp7Im9iaiI6eyJvYmpfMSI6IldlIGFyZSBpbiBvcHRpb24gIzIifSwiYXJyIjpbeyJhcnJfMSI6IldlIGFyZSBpbmRlZWQgaW4gb3B0aW9uICMyIn1dfX1dfSwidWlTY2hlbWEiOnt9LCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOnRydWUsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=).

1. Select "Option 2" and notice how `arr_2` field does not reset to empty.

#### Expected behavior

Identically named fields between oneOf/anyOf options should reset (if no default is specified).

#### Actual behavior

Identically named fields retain their values between oneOf/anyOf options.

### Version

2.0.0-alpha.1

**Comment by epicfaace** [comment]
@delyanr 
Going off your comment in https://github.com/rjsf-team/react-jsonschema-form/pull/1564#issuecomment-570618262 as well, as I think this issue is the best place to discuss this.

To be clear, would fixing this mean that if you have a schema like this:

```json
{
  "oneOf": [{
    "properties": {"name": {"type": "string"}, "age": {"type": "number"}}
  }, {
    "properties": {"name": {"type": "string"}}
  }]
}
```

And then you selected "option 1" and set "name" to "Ashwin", then switched to "option 2", then the form data should reset to set name to "undefined"? (or the default value in the second option, if specified)

This is probably a big (and breaking) change, but if it makes more sense to do it this way, we should do it.

**Comment by mabhub** [comment]
up

**Comment by heath-freenome** [comment]
Honestly, I don't believe that this is the correct behavior. If you change one-ofs and two have the same value, that value should be kept
