### ISSUE TITLE
Warning: Failed prop type: Invalid prop `value` supplied to `TextWidget`.

### ISSUE THREAD

**Issue by temp3l** [rjsf-team/react-jsonschema-form#1559]
## reproduce:
* try a schema without "properties" keyword in the playground
* and a initial-formData of type object ...

=> make sure the formData is a string to have it fixed

```
Warning: Failed prop type: Invalid prop `value` supplied to `TextWidget`.
    in TextWidget
    in Unknown (created by StringField)
    in StringField (created by SchemaField)
    in div (created by WrapIfAdditional)
    in WrapIfAdditional (created by DefaultTemplate)
    in DefaultTemplate (created by SchemaField)
```

**Comment by tugglecore** [comment]
Hey, I am new to contributing to OSS and I want to be able to solve this issue.

I am having trouble with running this project locally. Here are the steps I have taken thus far:

1.  clone the project.
2.  `npm install` inside the root directory of the project. 
3.  change directory to `packages/core` and ran `npm install` and `npm start` and I received the following output:

`> @rjsf/core@2.0.0-alpha.2 start C:\Users\tuggle.24\Desktop\Research\floss\react-jsonschema-form\packages\core
> concurrently "npm:build:* -- --watch"

[build:es]
[build:es] > @rjsf/core@2.0.0-alpha.2 build:es C:\Users\tuggle.24\Desktop\Research\floss\react-jsonschema-form\packages\core
[build:es] > cross-env NODE_ENV=production BABEL_ENV=es babel --extensions ".js,.jsx,.ts,.tsx" ./src --out-dir ./dist/es "--watch"
[build:es]
[build:cjs]
[build:cjs] > @rjsf/core@2.0.0-alpha.2 build:cjs C:\Users\tuggle.24\Desktop\Research\floss\react-jsonschema-form\packages\core
[build:cjs] > cross-env NODE_ENV=production BABEL_ENV=cjs babel --extensions ".js,.jsx,.ts,.tsx" ./src --out-dir ./dist/cjs "--watch"
[build:cjs]
[build:cjs] Browserslist: caniuse-lite is outdated. Please run next command `npm update`
[build:es] Browserslist: caniuse-lite is outdated. Please run next command `npm update`
[build:es] Successfully compiled 41 files with Babel.
[build:cjs] Successfully compiled 41 files with Babel.
`

4.  I repeated step 3 for `packages/playground` and received the following the error:

`
ERROR in ./src/index.js
Module not found: Error: Can't resolve '@rjsf/material-ui' in 'C:\Users\tuggle.24\Desktop\Research\floss\react-jsonschema-form\packages\playground\src'
 @ ./src/index.js 3:0-54 12:11-19
 @ multi ./src/index
`

What can I do to resolve this issue and began developing locally? 
I tried researching the issue on my own by looking at #1642 #1630 #1639.
Also, I am wondering if my issue has any relationship with #1663

**Comment by epicfaace** [comment]
@tugglecore you should run the following from the root directory:

```
lerna bootstrap
npm start
```

And everything should work.

**Comment by stanlemon** [comment]
@temp3l So is the schema you're trying something like this?

```json
{
  "type": "string"
}
```

**Comment by priyang12** [comment]
hi can i work on this issue if no one is working on this

**Comment by heath-freenome** [comment]
I believe this is working in the 5.x release just fine
