### ISSUE TITLE
First object in oneOf not resolved correctly from updating required property

### ISSUE THREAD

**Issue by RVEIII** [rjsf-team/react-jsonschema-form#1569]
Playground: https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0eXBlIjoiaW50ZWdlciJ9LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsIm9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7InR5cGUiOnsiY29uc3QiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbInR5cGUiXX0seyJwcm9wZXJ0aWVzIjp7InR5cGUiOnsiY29uc3QiOiJib29sZWFuIn19LCJyZXF1aXJlZCI6WyJ0eXBlIl19LHsicHJvcGVydGllcyI6eyJ0eXBlIjp7ImNvbnN0IjoiaW50ZWdlciJ9fSwicmVxdWlyZWQiOlsidHlwZSJdfV19LCJ1aVNjaGVtYSI6e30sImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==

### Description

I have a oneOf that always fails to resolve the default selection when it is the first object in the oneOf.

### Steps to Reproduce

1. Open link shown above
2. In the "Type" field, type "integer" and see that it updates the drop down to show "Option 3"
3. In the "Type" field, type "boolean" and see that it updates the drop down to show "Option 2"
4. In the "Type" field, type "string"
#### Expected behavior
The drop down is updated to show "Option 1" as selected

#### Actual behavior
The drop down is not updated.  It still shows "Option 2" as selected

### Version
2.0.0-alpha.1

**Comment by epicfaace** [comment]
This will probably require some debugging of `getMatchingOption`

https://github.com/rjsf-team/react-jsonschema-form/blob/e673a9097e587f28ffe7d82647ff70ba33908bcb/packages/core/src/utils.js#L1107

**Comment by RVEIII** [comment]
Thanks @epicfaace for the tip.  It led me to find that the issue is actually occurring here: https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/fields/MultiSchemaField.js#L49

We correctly are matching that the first option matches the form data and utils.getMatchingOption returns 0 as expected.  But there is code in MultiSchemaField that only returns the option that was returned from the utils.getMatchingOption if it does not equal 0.  If it does equal 0, it looks in the state to see if there's an existing selection...which in my case there is as the previous state is not cleared out.

Why not return 0?  Perhaps `utils.getMatchingOption` should return -1 or something if it fails to find a match.

**Comment by epicfaace** [comment]
Yeah, it makes sense to make `utils.getMatchingOption` return -1. Thanks for debugging! Do you want to make a PR with that change?

**Comment by rjfredrick** [comment]
@epicfaace do you have a PR for this issue?  I'm a colleague of @RVEIII and we can provide one if necessary!
