### ISSUE TITLE
Show string field as multiple choice without enum

### ISSUE THREAD

**Issue by dafeder** [rjsf-team/react-jsonschema-form#1570]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I am wondering if there is an existing way to do this, or if this might be a good idea: I'm building a form around a schema that I don't own. Some of the fields in this existing schema are defined as open text fields, but I want to restrict the incoming values and present a multiple-choice "select" box. Can I do this entirely in the UI configuration? I realize it's a bit of an anti-pattern to hide validation rules in the UI, but there are benefits to my use-case in not forking the schema itself.

#### Expected behavior

I can define a ui:widget as "select" or "checkboxes" for a simple string fields, and define the available options in the ui configuration.

#### Actual behavior

A field must have `enum` values in the schema itself for a select box to be available as a form widget.

### Version

Whatever the live playground is currently running? (1.8.1?)

**Comment by epicfaace** [comment]
You could define a custom widget that does this, which reads values from `uiSchema["ui:options"]["enum"]` and renders a dropdown. Maybe we could also add it to react-jsonschema-form.

We do support an autocomplete option with the `examples` keyword, if that's useful at all: https://github.com/rjsf-team/react-jsonschema-form/pull/1517
