### ISSUE TITLE
Custom validation messages from schema

### ISSUE THREAD

**Issue by Eux86** [rjsf-team/react-jsonschema-form#1571]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/Eux86/sjgp2hwq/) demonstrating the issue.

### Description

Hi,
I'm struggling to put custom error messages to work. I've seen that rjsf also includes the ajv-errors pluigin, so I'm assuming that the schemas shown here would work: 

https://github.com/epoberezkin/ajv-errors#messages-for-keywords

but how you can see in the [JSFiddle](https://jsfiddle.net/Eux86/sjgp2hwq/), it's not happening. What am I doing wrong?

### Steps to Reproduce

1. Run the JSFiddle
2. Click on Submit button

#### Expected behavior

Custom error messages should be shown

#### Actual behavior

Default error messages are shown

### Version

1.8.1

**Comment by epicfaace** [comment]
You should use `transformErrors` as documented in https://react-jsonschema-form.readthedocs.io/en/latest/validation/#custom-error-messages.

**Comment by epicfaace** [comment]
I don't think we have the `ajv-errors` package. Where did you notice we had it?

**Comment by Eux86** [comment]
A month has past and I've moved forward to another solution. I'm not that fresh on this codebase now and can't remember where I've noticed that the ajv-errors package was added. It clearly might have been a mistake that then stuck into my mind as a fact. 
I'll try to take a look to it again in the next days, time permitting :)

PS: your solution wouldn't be good for my case. I needed error messages to be added to the schema, not to the code.

**Comment by epicfaace** [comment]
Thanks for clarifying -- what exactly do you mean by "error messages to be added to the schema"? Is the idea that the schema itself would mutate after form submission? Even `ajv-errors`, I believe, doesn't mutate the original schema and instead returns a new object.

**Comment by scottseeker** [comment]
Adding to schema is because you're trying to contain everything about the form in your JSON.  So, if I'm adding a required field for instance, I want to be able to add the error message for that specific required field to the schema.
