### ISSUE TITLE
build fails: monaco-editor 

### ISSUE THREAD

**Issue by temp3l** [rjsf-team/react-jsonschema-form#1574]
how to build this project from source ?

All tags & branches fail with monaco problems 

Error: Cannot find module 'monaco-editor/esm/vs/editor/contrib/gotoSymbol/goToCommands'

The other error is:

TypeError: validateOptions is not a function

**Comment by satels** [comment]
?

**Comment by arunim2405** [comment]
Can you please share how did you implement monaco editor as a ui:widget in react JSON schema forms? if that's what you were trying to do

**Comment by epicfaace** [comment]
@arunim2405 -- I don't think this issue is about using the monaco editor as widget, but I have implemented that before. Here's the implementation code, if that helps: https://github.com/Chinmayamission/CFF/blob/master/scripts/src/form/form_widgets/JSONEditorWidget.tsx

**Comment by arunim2405** [comment]
@epicfaace Thanks a lot, that really helps, do you just override a textarea with this component in the forms or do you call this component directly in ui;widget (if you could also link me to a JSON+ui schema that uses this that would be awesome)? Again thanks a lot

**Comment by epicfaace** [comment]
You can do either, or also define a custom widget; here's more info on how to use a widget: https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/
