### ISSUE TITLE
Export typings from @rjsf/core

### ISSUE THREAD

**Issue by chanceaclark** [rjsf-team/react-jsonschema-form#1583]
@epicfaace was wondering if there was plans for a new alpha release soon? Hasn't been one since Nov of last year.

**Comment by epicfaace** [comment]
Will do so soon, thanks for the reminder!

**Comment by chanceaclark** [comment]
@epicfaace I know the library is heading toward the direction of converting to typescript. With that in mind, the recent rename of the NPM module to `@rjsf/core` has caused some conflicts when trying to use this alpha.2 version with the `@types/react-jsonschema-form` typings.

There is a temp "solution", which kinda works, but not for my applicable purpose:
```ts
declare module '@rjsf/core' {
  import Form from 'react-jsonschema-form';

  export * from 'react-jsonschema-form';
  export * from 'react-jsonschema-form/lib/components/fields/SchemaField';
  export * from 'react-jsonschema-form/lib/utils';
  export * from 'react-jsonschema-form/lib/validate';

  export default Form;
}
```
I haven't tested the above fully, but may work for people using the out-of-the-box package.

I have to suggest, moving forward, that the next alpha version should include typings along with the package so that we don't have to rely on the `@types` package. Otherwise we would have to create and maintain another typings packing in the DefinitelyTyped repo, which seems cumbersome.

**Comment by lygstate** [comment]
Hope TypeScript Index of react-jsonschema-form to be merged

**Comment by epicfaace** [comment]
@chanceaclark good point, thanks. We could perhaps keep it in JS for now but just export the typings in the next version.
