### ISSUE TITLE
JSFiddle examples are not working

### ISSUE THREAD

**Issue by jeremypeters** [rjsf-team/react-jsonschema-form#1584]
### Prerequisites

N/A

### Description

The JSFiddle examples listed at https://react-jsonschema-form.readthedocs.io/en/latest/#tips-and-tricks are no longer working

### Steps to Reproduce

Go to https://jsfiddle.net/hdp1kgn6/1/

#### Expected behavior

See an example form

#### Actual behavior

The form is not rendered

**Comment by epicfaace** [comment]
Right -- I think it is pulling the latest version (2.0.0 alpha) from the cdn, but still uses an older version of react. Could you fork the fiddles, update the React version, then make a PR to the docs to fix this?

**Comment by jeremypeters** [comment]
I had a quick look today - they're not using the latest, but hopefully will
have more time tomorrow to see what the issue is.

**Comment by jeremypeters** [comment]
FYI I'm in the process of moving the examples to CodeSandbox - it may take a few more days.

**Comment by jnachtigall** [comment]
@jeremypeters I am currently evaluating rjsf and came along the demos listed at https://react-jsonschema-form.readthedocs.io/en/latest/#tips-and-tricks (multi-step, conditional fields etc are important to us). But all these examples do not work. Is there already something to see at codesandbox?

**Comment by jeremypeters** [comment]
@jnachtigall Unfortunately I've been busy with other things and have only done a couple of the demos in CodeSandbox so far.

**Comment by mchelen-gov** [comment]
maybe related: https://github.com/rjsf-team/react-jsonschema-form/pull/1691

**Comment by epicfaace** [comment]
@mchelen-gov in that PR, I just commented out the jsfiddle examples so we can add working examples when they're fully fixed. I did add codepen examples, though those were just for the inline jsx code in the documentation rather than for the more complex jsfiddle examples that this issue is about.

**Comment by mchelen-gov** [comment]
@epicfaace do you have a list of the old examples that need to be migrated to the new docs?

**Comment by epicfaace** [comment]
@mchelen-gov 

From https://raw.githubusercontent.com/rjsf-team/react-jsonschema-form/master/docs/index.md:

## Useful samples

 - Custom field template: <https://jsfiddle.net/hdp1kgn6/1/>
 - Multi-step wizard: <https://jsfiddle.net/sn4bnw9h/1/>
 - Using classNames with uiSchema: <https://jsfiddle.net/gfwp25we/1/>
 - Conditional fields: <https://jsfiddle.net/69z2wepo/88541/>
 - Advanced conditional fields: <https://jsfiddle.net/cowbellerina/zbfh96b1/>
 - Use radio list for enums: <https://jsfiddle.net/f2y3fq7L/2/>
 - Reading file input data: <https://jsfiddle.net/f9vcb6pL/1/>
 - Custom errors messages with transformErrors: <https://jsfiddle.net/revolunet/5r3swnr4/>
 - 2 columns form with CSS and FieldTemplate: <https://jsfiddle.net/n1k0/bw0ffnz4/1/>
 - Validate and submit form from external control: <https://jsfiddle.net/spacebaboon/g5a1re63/>
 - Custom component for Help text with `ui:help`: <https://codesandbox.io/s/14pqx97xl7/>
 - Collapsing / Showing and Hiding individual fields: <https://codesandbox.io/s/examplereactjsonschemaformcollapsefieldtemplate-t41dn>

**Comment by mchelen-gov** [comment]
Here is a CodePen version of the Multi-step wizard (still using class component): https://codepen.io/mchelen/pen/zYrKvEy
