### ISSUE TITLE
Customizing Option 1, Option 2, etc. Drop-Down Labels Displayed When There Are Multiple Valid Schemas for a Schema Element

### ISSUE THREAD

**Issue by chapmanjw** [rjsf-team/react-jsonschema-form#1586]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When providing a schema element with multiple valid schemas, such as an element that has enumerated values but also accepts freeform strings, the form generator displays a drop-down list with each variation of the element. 

Is there a way to customize the labels used for those drop-downs, instead of "Option 1", "Option 2", etc.?

### Steps to Reproduce

Example Schema:

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "propertyA"
  ],
  "properties": {
    "propertyA": {
      "title": "Property A",
      "required": [
        "value"
      ],
      "properties": {
        "value": {
          "title": "Enum with Freeform",
          "anyOf": [
            {
              "enum": [
                "value1",
                "value2",
                "value3"
              ],
              "enumNames": [
                "Value 1",
                "Value 2",
                "Value 3"
              ],
              "type": "string"
            },
            {
              "type": "string"
            }
          ]
        }
      }
    }
  }
}
```

#### Expected behavior

Ability to customize how the labels are derived.

#### Actual behavior

Displays a control with "Option 1" and "Option 2" that render each variation of the element.

<img width="585" alt="Screen Shot 2020-02-10 at 1 57 08 PM" src="https://user-images.githubusercontent.com/1873608/74189283-56a28a00-4c0d-11ea-9a39-10db89959941.png">

<img width="585" alt="Screen Shot 2020-02-10 at 1 57 17 PM" src="https://user-images.githubusercontent.com/1873608/74189303-5bffd480-4c0d-11ea-84e7-5710f877bf01.png">

### Version

Playground: https://rjsf-team.github.io/react-jsonschema-form/

**Comment by epicfaace** [comment]
Add the `title` attribute to each array item in `anyOf`.

Like this:
```
"anyOf": [
            {
              "title": "first title",
              "enum": [
                "value1",
                "value2",
                "value3"
              ],
              "enumNames": [
                "Value 1",
                "Value 2",
                "Value 3"
              ],
              "type": "string"
            },
```
