### ISSUE TITLE
Update uiSchema in FieldTemplate

### ISSUE THREAD

**Issue by Fronix** [rjsf-team/react-jsonschema-form#1589]
I've been searching around and not found a good answer.
Is there any way to make react-jsonschema-form apply uiSchema changes if it's changed within FieldTemplate render?

**Comment by Fronix** [comment]
Reason I want to do this is we have a huge and very complicated form and having to rerender all fields just to update one kills all performance.
Only workaround I've found is updating the DOM directly to change small things that aren't dependant on the form

**Comment by epicfaace** [comment]
hmm, I don't think that's currently possible. That would be a nice improvement to add though.

**Comment by boborua** [comment]
@Fronix At leat, you can change change the "key" prop as long as "uiSchema" prop changed.
@epicfaace Btw, it's not easy to process linkages between fileds when we are developing custom widgets. Any planning improvement for this part?

**Comment by epicfaace** [comment]
@boborua can you explain more what you mean by "process linkages between fields"?

**Comment by boborua** [comment]
For example, I have a field A with custom widiget that rending a dropdown list, if some specific item is selected for field A, then filed B need to be hidden or be set to the same value...etc,
In this case, we do not have a good "context" to do so.

**Comment by epicfaace** [comment]
Will something like `dependencies` not work for your case?

**Comment by Zachary-zm** [comment]
> dependencies

Sorry, I have the same confused. Dependencies can be set to the same value?

**Comment by epicfaace** [comment]
> Dependencies can be set to the default value?

I believe so, just add a `default` key to the dependencies schema.

**Comment by VakarisZ** [comment]
I also have a custom object template and I would like to dynamically disable some children based on the state of the object template. Is there any progress on modifying the `UISchema` in the template?

**Comment by heath-freenome** [comment]
One solution is to override the `ObjectField` or maybe the `SchemaField` implementation itself to modify the `uiSchema` under the conditions you need. You can simply create a wrapper around the `ObjectField` to adjust the `uiSchema`
