### ISSUE TITLE
oneOf dependencies result in "duplicate" validation errors

### ISSUE THREAD

**Issue by MatinF** [rjsf-team/react-jsonschema-form#1590]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] I'm providing a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJwYXJlbnQiOnsiZW5jcnlwdGlvbiI6eyJlbmFibGVkIjowfX19LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsicGFyZW50Ijp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImVuY3J5cHRpb24iOnsidGl0bGUiOiJFbmNyeXB0aW9uIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZW5hYmxlZCI6eyJ0aXRsZSI6IkVuYWJsZWQiLCJ0eXBlIjoiaW50ZWdlciIsImRlZmF1bHQiOjAsImFueU9mIjpbeyJ0eXBlIjoiaW50ZWdlciIsInRpdGxlIjoiRGlzYWJsZSIsImVudW0iOlswXX0seyJ0eXBlIjoiaW50ZWdlciIsInRpdGxlIjoiRW5hYmxlIiwiZW51bSI6WzFdfV19fSwiZGVwZW5kZW5jaWVzIjp7ImVuYWJsZWQiOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsiZW5hYmxlZCI6eyJlbnVtIjpbMF19fX0seyJwcm9wZXJ0aWVzIjp7ImVuYWJsZWQiOnsiZW51bSI6WzFdfSwia2V5Zm9ybWF0Ijp7InRpdGxlIjoiS2V5IGZvcm1hdCIsImRlc2NyaXB0aW9uIjoiVGhlIGZvcm1hdCBvZiB0aGUgZW5jcnlwdGlvbiBwYXNzd29yZCIsInR5cGUiOiJpbnRlZ2VyIiwiZGVmYXVsdCI6MCwiYW55T2YiOlt7InR5cGUiOiJpbnRlZ2VyIiwidGl0bGUiOiJQbGFpbiIsImVudW0iOlswXX0seyJ0eXBlIjoiaW50ZWdlciIsInRpdGxlIjoiRW5jcnlwdGVkIiwiZW51bSI6WzFdfV19LCJwd2QiOnsidGl0bGUiOiJFbmNyeXB0aW9uIHBhc3N3b3JkIiwidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiIifX0sImRlcGVuZGVuY2llcyI6eyJrZXlmb3JtYXQiOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsia2V5Zm9ybWF0Ijp7ImVudW0iOlswXX0sInB3ZCI6eyJkZXNjcmlwdGlvbiI6IkVuY3J5cHRpb24gcGFzc3dvcmQgaW4gcGxhaW4gZm9ybSAobWluIGxlbmd0aCAyMCkiLCJtaW5MZW5ndGgiOjIwfX19LHsicHJvcGVydGllcyI6eyJrZXlmb3JtYXQiOnsiZW51bSI6WzFdfSwicHdkIjp7ImRlc2NyaXB0aW9uIjoiRW5jcnlwdGlvbiBwYXNzd29yZCBpbiBlbmNyeXB0ZWQgZm9ybSAobWluIGxlbmd0aCA0MCkiLCJtaW5MZW5ndGgiOjQwfX19XX19LCJyZXF1aXJlZCI6WyJrZXlmb3JtYXQiLCJwd2QiXX1dfX19fSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlLCJwYXR0ZXJuUHJvcGVydGllcyI6eyJrZXlmb3JtYXQiOnt9LCJwd2QiOnt9fSwicmVxdWlyZWQiOlsiZW5jcnlwdGlvbiJdfX19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==) demonstrating the issue.

### Description

We have a use case where we wish to restrict the minLength or a password based on whether the password is plain-form of encrypted. To do so we use `oneOf` and dependencies to modify the `pwd` property based on the `keyformat` property.

#### Expected behavior

We would expect that when the `keyformat` is set to `Plain`, the minLength required during validation would be 20. When it is set to `Encrypted`, the validation should check if the minLength is 40. 

#### Actual behavior
The validation "works" in the sense that the validation errors dissapear for the Plain case when the `pwd` is >20 in length and for Encrypted when it is >40 in length. 

However, when selecting Plain, the validation errors will show both validation errors, i.e. the user will be told that the password must be >20 in length **and** >40, which is confusing (and not reflective of what the editor actually checks against in practice)

### Version
Tested in the latest playground.

**Comment by Saulzi** [comment]
doing it this way will mean that you would get the validation error in relation to 40 and 20 chars rather than both because the validation is only being done based on the value you selected

**Comment by MatinF** [comment]
That sounds like a viable solution - I'd be interested in getting that PR added to master in that case

**Comment by MatinF** [comment]
One thought though: Is this something that is supported in general by the JSON Schema concept? We also use other tools for loading our Schema files, so we'd want it to be a syntax that is generally supported ideally.

**Comment by Saulzi** [comment]
this is part of the json schema 7 spec, not all tools support it but I can confirm that it works in tools such as vscode.

please refer to 

https://json-schema.org/understanding-json-schema/reference/conditionals.html
