### ISSUE TITLE
`onChange` sometimes incorrectly fires on component mount

### ISSUE THREAD

**Issue by garrettmaring** [rjsf-team/react-jsonschema-form#1591]
### Description

The `onChange` prop is incorrectly invoked when there is no matching form data for a given field.

### Steps to Reproduce

```js
const schema = {
  title: "Todo",
  type: "object",
  required: ["title"],
  properties: {
    done: { type: "boolean", title: "Done?" }
  }
};

const data = {
  done: true
};

export default function App() {
  return (
    <div className="App">
      {/* ✅ This does not fire an `onChange` event on mount */}
      <Form schema={schema} onChange={console.log} formData={data} />
      {/* 🚫 This fires an `onChange` event on mount */}
      <Form schema={schema} onChange={console.log} />
    </div>
  );
}
```

[CodeSandbox](https://codesandbox.io/s/elastic-babbage-9dudm)

#### Expected behavior

The `onChange` event should only fire when the underlying formData changes.

#### Actual behavior

`onChange` was called unexpectedly when `formData` was omitted.

### Version

1.8.1

**Comment by epicfaace** [comment]
I think this is a duplicate of #1201 (i.e., this only occurs on mount when there is existing form data) -- is that so @garrettmaring ?

**Comment by garrettmaring** [comment]
That looks like it!
