### ISSUE TITLE
1.8.2?

### ISSUE THREAD

**Issue by Zanaku** [rjsf-team/react-jsonschema-form#1592]
Hello!
I was just wondering if a version 1.8.2 is anywhere close? I'm particularly desperate for 'allOf' support which seems to have just missed the cut for 1.8.1.

Apologies if I missed something somewhere with info about release frequency, thank you for the wonderful library!

**Comment by epicfaace** [comment]
New features such as allOf support will only be introduced in v2 -- you can use the alpha version to test it out. See https://github.com/rjsf-team/react-jsonschema-form/issues/1409 for more information.
