### ISSUE TITLE
Errors in `onError` loose all ajv properties when a custom `validator` property is specified.

### ISSUE THREAD

**Issue by RoboPhred** [rjsf-team/react-jsonschema-form#1596]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When a custom validator is passed through the `validate` property, all properties except the `stack` property on onError errors are wiped.

### Steps to Reproduce

See https://codesandbox.io/s/react-example-22s01
Click submit to see proper errors.  Click "Enable custom validation" to add a no-op custom validator, and submit again.  Observe errors now are missing most of their properties.

#### Expected behavior

Existing AJV errors should mantain their properties.  Custom validator errors should at the very least specify the `property` property so consumers of onError know what field is having the error.

#### Actual behavior

All errors, both custom and ajv, only have a `stack` property.

Error with custom validation off:
(all properties specified as expected)
```js
[
  {
    "name": "maxLength",
    "property": ".test",
    "message": "should NOT be longer than 3 characters",
    "params": {
      "limit": 3
    },
    "stack": ".test should NOT be longer than 3 characters",
    "schemaPath": "#/properties/test/maxLength"
  }
]
```

Error with custom validation on:
(No properties aside from `stack` specified for both schema and custom errors)
```js
[
  {
    "stack": "test: should NOT be longer than 3 characters"
  },
  {
    "stack": "test: This is a custom error"
  }
]
```
### Version

1.8.1

### Cause:

The error properties are generated by transformAjvErrors [here](https://github.com/rjsf-team/react-jsonschema-form/blob/ef8b7fce19c5271f75a849fa951ad62595314b00/packages/core/src/validate.js#L212).  If custom validation is off, this is the error object returned [here](https://github.com/rjsf-team/react-jsonschema-form/blob/ef8b7fce19c5271f75a849fa951ad62595314b00/packages/core/src/validate.js#L249).

However, if a custom validator is used, the error list is entirely regenerated by toErrorList [here](https://github.com/rjsf-team/react-jsonschema-form/blob/ef8b7fce19c5271f75a849fa951ad62595314b00/packages/core/src/validate.js#L258).  This function only populates the `stack` property.

### Fix 

~~Fixing this might be difficult if we want to completely regenerate the list to allow the validate handler to delete existing errors.  
However, at the very least we should populate the `property` key in toErrorList so that the consumer knows where the errors occurred.  This would be enough to fix our particular use case.~~

Edit: validate does not receive the existing errors, but a new schema object.  This means the user cannot delete existing errors and we can simply compute the `toErrorList` of the validator errors and concat it.

We can accomplish this by replacing the code [here](https://github.com/rjsf-team/react-jsonschema-form/blob/ef8b7fce19c5271f75a849fa951ad62595314b00/packages/core/src/validate.js#L252)
```
  const errorHandler = customValidate(formData, createErrorHandler(formData));
  const userErrorSchema = unwrapErrorHandler(errorHandler);
  const newErrorSchema = mergeObjects(errorSchema, userErrorSchema, true);
  // XXX: The errors list produced is not fully compliant with the format
  // exposed by the jsonschema lib, which contains full field paths and other
  // properties.
  const newErrors = toErrorList(newErrorSchema);
```

with

```
  const errorHandler = customValidate(formData, createErrorHandler(formData));
  const userErrorSchema = unwrapErrorHandler(errorHandler);
  const newErrorSchema = mergeObjects(errorSchema, userErrorSchema, true);
  // Concat the new errors to the existing error list
  const newErrors = [].concat(errors, toErrorList(userErrorSchema));
```

**Comment by epicfaace** [comment]
Yeah, your analysis / fix seem to be right. Can you make a PR that fixes this?

**Comment by RoboPhred** [comment]
PR: https://github.com/rjsf-team/react-jsonschema-form/pull/1608

**Comment by RoboPhred** [comment]
I rebooted this issue with a MR against 2.x: #2002

**Comment by penx** [comment]
Not stale. Open PR at #2002

**Comment by heath-freenome** [comment]
Fixed in v5 beta via https://github.com/rjsf-team/react-jsonschema-form/pull/3047
