### ISSUE TITLE
[Question] How to determine an `ui:order` for array items?

### ISSUE THREAD

**Issue by tomaszmys** [rjsf-team/react-jsonschema-form#1598]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

As in the title, can't seem to find any information on what's the proper uiSchema syntax for determining the `ui:order` of array elements.
My sincere apologies if that's the part of the common knowledge base, and it's me who failed to browse it properly (but I've tried).

### Steps to Reproduce

1. Add any schema with an array holding items of type: object.
`type: 'object',
title: 'Example root',
properties: {
    exampleList: {
        type: 'array',
        minItems: 1,
        items: {
            type: 'object',
            properties: {
                A: {(...)},
                B: {(...)},
                C: {(...)},
            }
        }
    }
}`
2. Add an uiSchema for the array, with an `ui:order` for array items:
`exampleList: {
    items: {
        'ui:order': [ 'B', 'A', 'C' ]
    }
}`

#### Expected behavior

Items added to the array have their properties rendered in the given order.

#### Actual behavior

A classic `ui:order` error (

> Invalid root object field configuration:uiSchema order list does not contain properties

) gets thrown/rendered on the form.

### Version

I'm currently fetching 1.8.1 version from npm.

**Comment by epicfaace** [comment]
`ui:order` should work -- check [https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6W3t9XSwic2NoZW1hIjp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImEiOnsidHlwZSI6InN0cmluZyJ9LCJiIjp7InR5cGUiOiJzdHJpbmcifX19fSwidWlTY2hlbWEiOnsiaXRlbXMiOnsidWk6b3JkZXIiOlsiYiIsImEiXX19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOnRydWUsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=](this playground link).

Can you send a playground link of what exact schema / uiSchema you are trying to use?

**Comment by tomaszmys** [comment]
Sigh...

Of course, it works. I've found a regression in our form wrapper.
Your example helped immensely, though - starting from the example that worked, I could crawl back to find the exact problem in my case.
