### ISSUE TITLE
Local playground does not hot-reload modified react-jsonschema-form

### ISSUE THREAD

**Issue by Saulzi** [rjsf-team/react-jsonschema-form#1609]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Playground does not contain latest source / is out of date when developing

### Steps to Reproduce

1. Check out react-jsonschema-form
2. run npm install
3. change to packages/playground
4. run npm build:lib
5 change to packages/core
6 run npm start
7 make changes

#### Expected behavior

Changes are picked up and webpack HMR reloads page

#### Actual behavior

Sweet FA

### Version

master - sha: b7ef383

**Comment by Saulzi** [comment]
I have a workaround / fix, on my local machine I have changed package.json in playground to use relative path, running start from this directory works and updates / hot reloads as required.

Perhaps it would be worth removing extra playground and scripts from core package and doing the above in the playground package?

**Comment by Saulzi** [comment]
correction does not hot reload, have to still run build:lib in core,

really the playground etc should be set up with sourcemaps to aid development as yes the tdd script seems to work to some extent it would be nice to actually see what the hell is going on in the browser.

**Comment by epicfaace** [comment]
I believe this has been fixed with the new playground setup.
