### ISSUE TITLE
File Upload Enhancements

### ISSUE THREAD

**Issue by davidrenne** [rjsf-team/react-jsonschema-form#1619]
### Description

I want to implement better file upload handling, currently when testing the playground examples and pushing my json to the server.  When I am editing existing data, it doesnt show up my old files.  So if someone re-uploads something else, the data originally there gets deleted.

Additionally I want to add support to delete files and possibly show a preview thumbnail.

Maybe if someone can point me in the right direction on here, I am sure I can customize something on my own, but I would like to see better support by default and would love to contribute some code.

**Comment by epicfaace** [comment]
Yeah, you would need to change the default FileWidget. You can add that on your own, though it would be great to make the default FileWidget on rjsf be better with the inputs you mentioned.

I worked on another project where we did make a file widget with a preview, using an iframe:

https://github.com/TreeHacks/root/blob/9f21f350416493e1f90fed5102330f4c8f8f1d0c/src/FormPage/FormPage.tsx#L27-L52

**Comment by davidrenne** [comment]
thanks @epicfaace ill look into changing the default FileWidget to handle existing data instead of overwriting if its an array of files.  It might make sense for a single but an array, isnt good.
