### ISSUE TITLE
Is there a way to define a field to populate/validate its input by calling an api

### ISSUE THREAD

**Issue by vinay32724** [rjsf-team/react-jsonschema-form#1621]
i have a requirement where one of the field in my form needs a make an api call to populate data as user is typing. How Can I achieve this ?

**Comment by timkindberg** [comment]
We have a fairly complicated custom SelectWidget in our project. It takes some `ui:options` that look like this (e.g. if you have field called Author and wanted to populate it with all the available authors from an API)(FYI, we use react-select):
```js

      "author": {
        "ui:widget": "select",
        "ui:options": {
          "optionsFromApi": {
            "url": "/api/authors",
            "transform": "$.results.{'value': id, 'label': name}[] ~> $uniqBy('value')"
          }
        }
      },
      "books": {
        "ui:widget": "select",
        "ui:options": {
          "optionsFromApi": {
            "url": "/api/authors?author=${author}",
            "transform": "$.results.{'value': id, 'label': name}[] ~> $uniqBy('value')"
          }
        }
      },
 
```

The `transform` is a [jsonata](https://jsonata.org/) expression that transforms the JSON response into a shape that the select box requires.

Additionally you might notice the token in the books url `${author}` that is replaced live whenever the author value changes.

We might open source at some point, but no plans at the moment. But hopefully that gives you some inspiration?

**Comment by vinay32724** [comment]
Thanks @timkindberg for the explanation. It is really helpful

a) Is there a way to create multi page form ? 
b) Is there a way instead of coding submit action can developer  mention an API call (in json) to be called when user clicks submit button? I’m looking for a zero code framework where multiple teams can bring their forms onto my portal without coding and there by relieving them from release cycles. 
c) It would be great to point me to detailed documentation of usage of each widget.

**Comment by vinay32724** [comment]
@timkindberg 

> Thanks @timkindberg for the explanation. It is really helpful
> 
> a) Is there a way to create multi page form ?
> b) Is there a way instead of coding submit action can developer mention an API call (in json) to be called when user clicks submit button? I’m looking for a zero code framework where multiple teams can bring their forms onto my portal without coding and there by relieving them from release cycles.
> c) It would be great to point me to detailed documentation of usage of each widget.

@timkindberg Could you reply on the above comment. Thanks in Advance

**Comment by timkindberg** [comment]
Sure but it probably won't help too much :)

a) Surely there is, but I don't know how to do it. I imagine it would be a matter of visually showing and hiding portions of the form via a custom ObjectFieldTemplate.

b) You have control of onSubmit, you have JS/JSON at your disposal, you will need to design something custom here I think.

c) Detailed documentation is already [here](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/) or in the source.

**Comment by epicfaace** [comment]
For another project, I made a field that populates dropdown options from making an api call -- the source code is available here: https://github.com/epicfaace/CFF/blob/master/scripts/src/form/form_widgets/AutoPopulateField.tsx

**Comment by GFoley83** [comment]
@timkindberg are you able to share the code for your custom component ? That's exactly what I'm looking for at the moment.

**Comment by timkindberg** [comment]
Unfortunately it's quite coupled to our application of which I can't share. If I get some time perhaps I can try to extract the generic parts.
