### ISSUE TITLE
Selecting large files will crash the browser

### ISSUE THREAD

**Issue by erwinsmit** [rjsf-team/react-jsonschema-form#1624]
### Prerequisites

- [x ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
When you select a file roughly around 100mb the browser freezes for a while and will eventually crash.

This occurs on my Dell XPS i7, 16gb using chrome. So it's not an issue with low-performance laptops. 

### Steps to Reproduce

1. Go to https://rjsf-team.github.io/react-jsonschema-form/
2. Navigate to files
3. Try uploading a pdf around 100mb

#### Actual behavior

![image](https://user-images.githubusercontent.com/5425589/75685731-5725c200-5c9b-11ea-9458-cd728d72a8b6.png)

I tried running the performance profile in chrome, but also that crashes trying to upload a large file... 

Thanks in advance!

**Comment by erwinsmit** [comment]
After waiting a couple of minutes my profiler started working after all.

It looks like the "dataURItoBlob" function is causing this problem:

![image](https://user-images.githubusercontent.com/5425589/75686787-17f87080-5c9d-11ea-9136-a65197fcd2e4.png)

**Comment by erwinsmit** [comment]
I have created a pull request which fixes the issue with a non-breaking change. It would be great if someone could review it? @epicfaace

**Comment by epicfaace** [comment]
What is the maximum file size that can be parsed to base64? Is it fixed at 5mb as you mentioned, or does it depend on the computer's RAM?

**Comment by erwinsmit** [comment]
I don't know about a maximum file size, but I noticed on my laptop there was a very small lag on 5mb but it was still acceptable.

**Comment by epicfaace** [comment]
I'm guessing that other users with different computers may have a different threshold (smaller or larger) than 5 MB, though. I'm not comfortable with adding a default threshold for this reason, though we could make the maximum file size a configurable option in the uiSchema.

**Comment by erwinsmit** [comment]
Yeah, that makes sense. I can add that to my pull request.

**Comment by erwinsmit** [comment]
@epicfaace I have updated the pull request with a configurable option in the UI schema. I've also added an example to the playground.
