### ISSUE TITLE
Build size too high

### ISSUE THREAD

**Issue by dumbape** [rjsf-team/react-jsonschema-form#1625]
### Description

Is there any way to install only the core package and not material-ui. BundlePhobia says the package size is 69kb, which is way greater than react + redux.

**Comment by epicfaace** [comment]
`react-jsonschema-form` (and the v2 versio in `@rjsf/core`) don't have material ui in it -- material ui is part of a separate package. You're probably right that they're large bundles, but it's not thanks to material-ui.

**Comment by dpacmittal** [comment]
There are some of us are using this library without any validation features, only as a way to display the form. It'd be better if ajv was put in as peer dependency and user could pass the ajv import manually in the <Form> component.
