### ISSUE TITLE
Access enum value in schema

### ISSUE THREAD

**Issue by MMrj9** [rjsf-team/react-jsonschema-form#1636]
**Version: 1.8.1**

```
alertLevels: {
        type: "array",
        minItems: 1,
        maxItems: 2,
        hasRemove: true,
        items: {
          type: "object",
          required: ["severity", "upperThreshold", "lowerThreshold"],
          properties: {
            severity: {
              type: "string",
              title: "Alert Severity",
              enum: ["Critical", "Warning"]
            },
            isBulkAssign: {
              type: "boolean",
              title: "Assign Type",
              default: isOneByOne.indexOf(#severity#????) === -1,
              oneOf: [
                {
                  "const": true,
                  "title": "Bulk"
                },
                {
                  "const": false,
                  "title": "One By One"
                }
              ],
            },
            lowerThreshold: {
              type: "number",
              title: "Lower Threshold"
            },
            upperThreshold: {
              type: "number",
              title: "Upper Threshold"
            }
          }
        }
      }
```
Is there any way I can access the enum value of the field "severity" in the default property of "isBulkAssign"?
Thanks

**Comment by Saulzi** [comment]
To me it looks like you are trying to set the default value of isBulkAssign to something depending on the value of severity,

https://github.com/rjsf-team/react-jsonschema-form/pull/1610

**Comment by MMrj9** [comment]
> To me it looks like you are trying to set the default value of isBulkAssign to something depending on the value of severity,
> 
> #1610

exactly. Not yet possible?

**Comment by Saulzi** [comment]
not yet I am afraid, one day soon hopefully once #1610 then maybe,

Is isBulkAssign a constant i.e. readonly value i.e. true if one value and false if the other (do you actually need this extra field here?) 

There are some considerations with the If, Then, Else stuff as thinking about it the default value may not do quite what you need as if the user selects one value in severity or it is the default value and they select a different value the default value for isBulkAssign will of allready been set.
