### ISSUE TITLE
Playground crashes with invalid schema (instead of showing an error)

### ISSUE THREAD

**Issue by hrvojebusic** [rjsf-team/react-jsonschema-form#1637]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Form crashes when provided with a more complex schema that has several levels of nesting.

### Steps to Reproduce

This bug has first been observed during `rjsf` use in development, but can be reproduced in the playground.

1. Got to `rjsf` [playground](https://rjsf-team.github.io/react-jsonschema-form/).
2. Input the following JSON schema snippet:
```
{
  "title": "Demo",
  "type": "object",
  "properties": {
    "firstProperty" : {
      "title": "First title",
      "type": "object",
      "properties": {
        "secondProperty": {
          "title": "Second title",
          "type": "array",
          "items": {
            "type": "object"
            // Add more JSON here.
          }
        }
      }
    }
  }
}
```
3. In a place specified by comment, add the following JSON schema snippet.

```
"properties":  {
	"type":  "string",
	"title":  "Third title"
}
```

#### Expected behavior

Appropriate form should be rendered.

#### Actual behavior

Website crashes due to a bug in the form.

![image](https://user-images.githubusercontent.com/17817728/76067346-1d003d00-5f87-11ea-9d27-57176f2e05ff.png)

### Version

1.7.1

**Comment by mirajp** [comment]
Your schema is invalid. Properties should list out the nested keys' details.
For instance, this is valid:
```
"secondProperty": {
  "title": "Second title",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      // Add more JSON properties here
      "imAPropertyOfEachObjectIn_secondProperty_Array": {
        "title": "Third title",
        "type": "string"
      }
    }
  },
  ...
}
```

**Comment by hrvojebusic** [comment]
Thanks for clarifying 👍

Still, I don't think that this issue should be closed, as online playground does crash for this input, while for other types of invalid input it displays some kind of error.
