### ISSUE TITLE
Is it possible to implement custom array field with multiple values?

### ISSUE THREAD

**Issue by ERRORthenBSOD** [rjsf-team/react-jsonschema-form#1645]
Hello, first of all great thanks for your project. I already been working with rjsf a lot and read the docs from the beginning and to the the end several times and i already broke my brain trying to implement custom array with multiply values.
I want to set my array to be like [material-ui autocomplete Multiple values
](https://codesandbox.io/s/fcogc) [Material Design link](https://material-ui.com/components/autocomplete/#multiple-values) .
i have scheme like: 
```
const JSONSchema = {
  "type": "array",
  "items": {
      "type": "string"
    }
}
```
```
const formData = ["foo"]
```
it is array of strings.
Problem that if i set for example custom widget with material ui autocomplete on items, i can`t create new index value with onChange event because it always rewrites the first index in array when i add new value.

It looks like i should create new item on "target values" when onChange event fires there, and write new value in it immediately but it is impossible. Also i can`t set enum there because my select values are dynamic from api.

My current workaround is that i write in single string all values with space between (like ["foo bar"]) when material-ui autocomplte input onChange event fires and then when i submit my form i split them by space and write all values like `["foo", "bar"]`

Maybe you can give me an advice how i can implement multiply values on same array input without creating new items in GUI?
Thanks in advance

**Comment by videni** [comment]
I also have this trouble.

I use a single string that has values seperated by comma, like `1,2`. it is implemented with material-ui autocomplete component.the problem is when you  do update, the formData we got from server might looks like following. 

```
{
    "formData": {
        "channels": '1,2'
    },
    "schema": {
        "title": "product",
        "type": "object",
        "properties": {
            "channels": {
                "title": "Chanels",
                "type": [
                    "string",
                    "null"
                ]
            }
        }
    },
    "uiSchema": {
        "channels": {
            "ui:widget": "autocomplete",
            "ui:options": {
                "placeholder": "acme.channel.choose_channel",
                "allowClear": true,
                "minimumInputLength": 0,
                "multiple": true,
                "route_parameters": {
                    "_org_id": 2
                },
                "autocomplete_alias": "channels",
                "properties": [
                    "name",
                    "hostname"
                ],
                "route_name": "acme_form_autocomplete_search",
                "component": "autocomplete",
                "option_label": "name",
                "option_value": "id"
            }
        }
    }
}
```
Assume we have following options. how can we show the selected label? 
```
[
    {
        "id": 1,
        "name": "test1"
    },
    {
        "id": 2,
        "name": "test2"
    }
]
```

You may think we can keep them in the schema part. for example, 
```
{
    "title": "product",
    "type": "object",
    "properties": {
        "channels": {
            "title": "Chanels",
            "type": [
                "string",
                "null"
            ],
            "dataSelected": [
                {
                    "id": 1,
                    "name": "test1"
                },
                {
                    "id": 2,
                    "name": "test2"
                }
            ]
        }
    }
}
```
on this occasion it work, but if  the `channels` properties is in `array`, it doesn't work anymore. we can not add  "dataSelected" to `channels` property as above example, because `channels` property only show one time.

```
{
    "title": "block",
    "type": "object",
    "properties": {
        "appliedTo": {
            "type": "array",
            "title": "Applied to",
            "items": {
                "title": "0",
                "type": "object",
                "properties": {
                    "channels": {
                        "type": "string",
                        "title": "Channels",
                        "dataSelected": [
                            "we can't keep options here anymore, because this property only show one time."
                        ]
                    },
                    "price": {
                        "title": "Price",
                        "type": "integer"
                    }
                }
            }
        }
    }
}
```

**Comment by videni** [comment]
The above solution is a very complex, I came up a simple one which allows  us to register a custom view transfomer to a field. the transformation run  before validation , and  the transformed data will be fed to  the validate and the submit method.  you can register  a view transformer like following

```

 const AutocompleteWidget: React.FC<WidgetProps> => (props) {
    const {
        addViewTransformer,
    } = props;

    useEffect(() => {
        addViewTransformer && addViewTransformer((formData: any) => {
         // transform form data  to view data which will be validated and submited.
           return formData;
        });
    });
}

```

check [ my customized repo](https://github.com/videni/react-jsonschema-form.git) for more details.

**Comment by gullitmiranda** [comment]
sorry if I didn't understand your problems, but if I'm not wrong, what you want is:

1. using a dynamic array
	```json
	  const JSONSchema = {
	    "type": "array",
	    "items": {
	        "type": "string"
	      }
	  }
	```
2. sent the API options to the autocomplete
3. enable multiple selection

if yes, see my demo in https://codesandbox.io/s/rjsf-async-multiple-select-c62fi?file=/src/FormSpike.js

**Comment by heath-freenome** [comment]
I believe #2697 will fix this
