### ISSUE TITLE
Seperate concern of form data.

### ISSUE THREAD

**Issue by videni** [rjsf-team/react-jsonschema-form#1651]
### Description

The idea is that form data can be any format, view data is used to validate and submit. the form data  doesn't need to conform schema definitions.  a example like below.
```
{
    "formData": {
        "channels": [
            {
                "name": "test1",
                "id": 1
            }
            {
                "name": "test2",
                "id": 2
            }
        ]
    },
    "schema": {
        "title": "Autocomplete",
        "type": "object",
        "properties": {
            "channels": {
                "type": ["string", "null"],
                "title": "Channels"
            }
        },
    },
    "uiSchema": {
        "channels": {
           "ui:widget": "autocomplete"
        }
    }
}
```
we transform this form data  into view data which will be used to validate and submit.  this way we give a change to widget to register their own view transformer, the reason why let widget do this view transform registration is that only the widget knows how to transform form data to view data.

# Use cases

## Autocomplete
Please look this [issue](https://github.com/rjsf-team/react-jsonschema-form/issues/1645) for more details. 

## Address selector 

Let's say we create a AddressWidget to select address. the data to select is 4 level structure.

country
     state
          city
                area

in this case, we only need to submit the area to server, the view transformer the AddressWidget registered will  do transformation automatically.  to show the full address ,  the underlining form data  of the AddressWidget  got from server looks like below,  the AddressWidget can use this data to build a full  address.
```
[
    {
        "name": "Chinna",
        "id": 100
    },
    {
        "name": "Sichuan",
        "id": 101
    },
    {
        "name": "Chengdu",
        "id": 102
    },
    {
        "name": "Gaoxinqu",
        "id": 103
    }
]
```

we can't add a custom key to schema or uiSchema to keep the full form data, because they only show once, the AddressWidget may be used in a array, check [thins link](https://github.com/rjsf-team/react-jsonschema-form/issues/1645#issuecomment-598633239) if you don't get what  I mean.

# You may have following questions

1. Why I don't do transformation before passing the form data to react-json-schema form component?

the widget need to get the full form data  instead of normalized one, for autocomplete widget, I keep mutliple selected choices seperated by comma, `1,2`, in order to show the selected options, it need the full selected options which include id and name data,   for example.
```
[
            {
                "name": "test1",
                "id": 1
            }
            {
                "name": "test2",
                "id": 2
            }
        ]
```

# What need to change.

1. Tranform form data into view data before validation and submit, and pass the transformed view data to validate and submit method.

2.  Allow widget to register view transfomer.

**Comment by Saulzi** [comment]
I have had success without changing things in rsjf to create 1 a autocomplete driven by dynamic data from websevice (using custom fields / widgets) and to essentially transform data / schema on the fly (custom field using schemafield)

**Comment by Parro** [comment]
I also have a very similar problem, I have an autocomplete dropdown that is populated on typing calling a remote endpoint. If I pass a value in `formData` I don't have the complete information of which value is shown in the dropdown, because the formData is an integer like `123` and the option is in the form of
```
{
  label: 'store name',
  value: 123,
}
```
I manage to found a solution passing the option in the uiSchema, but is very tricky and it gives me a lot of headache to keep the `formData` and the dropdown in sync... @videni I see your implementation of the trasnformData mentions in #1645 and I think is very interesting, it could simplify a lot my code 🙂. Do you have plan to make a PR for the main project?
And do the maintainers (@epicfaace ?) think is a good idea?
