### ISSUE TITLE
oneOf/anyOf does not infer type or respect subschema-level type

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#1654]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Explicitly giving the type in a root-level schema [works fine](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6ImQiLCJzY2hlbWEiOnsidHlwZSI6InN0cmluZyIsIm9uZU9mIjpbeyJ0aXRsZSI6IkMiLCJjb25zdCI6ImMifSx7InRpdGxlIjoiRCIsImNvbnN0IjoiZCJ9XX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjp0cnVlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19).

However, the following do not render anything, though are supposed to still render a dropdown:
- [Not providing](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6ImQiLCJzY2hlbWEiOnsib25lT2YiOlt7InRpdGxlIjoiQyIsImNvbnN0IjoiYyJ9LHsidGl0bGUiOiJEIiwiY29uc3QiOiJkIn1dfSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOnRydWUsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=) the type at all (in which the type should be inferred to be a string)
- [Explicitly providing](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6ImQiLCJzY2hlbWEiOnsib25lT2YiOlt7InRpdGxlIjoiQyIsImNvbnN0IjoiYyIsInR5cGUiOiJzdHJpbmcifSx7InRpdGxlIjoiRCIsImNvbnN0IjoiZCIsInR5cGUiOiJzdHJpbmcifV19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==) the type only in subschemas

### Version

2.0.0-alpha.2

**Comment by Saulzi** [comment]
@epicfaace saw this happening the other day, it looks like there is some code to detect but this is not working, I have a few examples of this on what I am currently working on which also requires #885 / my if then else stuff
