### ISSUE TITLE
Unexpected reset to initial data on re-render

### ISSUE THREAD

**Issue by yassera2** [rjsf-team/react-jsonschema-form#1658]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When re-rendering the Form component, the fields values are reset to it's initial value.

### Steps to Reproduce

https://codesandbox.io/s/rjsf-render-issue-dy10l

#### Expected behavior

The formData should be updated based on changes in the schema or the initial data provided.

#### Actual behavior

The fields are reset after any re-render regardless.

### Version
^2.0.0-alpha.2

**Comment by yassera2** [comment]
Found duplicate issue from 2016

https://github.com/rjsf-team/react-jsonschema-form/issues/391

**Comment by phatNfqAsia** [comment]
@epicfaace is this going to be in progress any soon? I can not see the To do anynmore 😢
