### ISSUE TITLE
Ship untranspiled version of library

### ISSUE THREAD

**Issue by betalb** [rjsf-team/react-jsonschema-form#1659]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Is it possible to ship untranspiled version of code in addition to the current build?
Probably es module version with transpiled code will be also helpful.

There seems to be a common pattern to include untranspiled version of code into package and link it in esnext field of package.json, this will allow us as consumers to decide which level of transpilation to apply because this is not the task of library developer.

### Version

1.8.1

**Comment by epicfaace** [comment]
Does https://github.com/rjsf-team/react-jsonschema-form/pull/1642 fix this? (we haven't released since that PR was merged though)

**Comment by betalb** [comment]
@epicfaace I've quickly looked at the code and it seems that it partially implements what I'm talking about: it created es modules build

But my major request is to ship untranspiled version, without babel runtime, because build still applies this transformation and requires corejs2
