### ISSUE TITLE
@rjsf/material-ui 2.0.0-alpha.2 not published or built properly

### ISSUE THREAD

**Issue by zwjohn** [rjsf-team/react-jsonschema-form#1663]
### Prerequisites

- [ Yes] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ Yes] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ Yes] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

npm install @rjsf/material-ui
 contain no bundle

[Description of the bug or feature]

https://registry.npmjs.org/@rjsf/material-ui/-/material-ui-2.0.0-alpha.2.tgz is empty too

### Steps to Reproduce

npm install @rjsf/material-ui

check node_modules\@rjsf\material-ui folder

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by zwjohn** [comment]
I also would like to point out that, @rjsf/material-ui 2.0.0-alpha.2 is still using react-jsonschema-form instead of @rjsf/core

var reactJsonschemaForm = require('react-jsonschema-form');
var React = _interopDefault(require('react'));
var utils = require('react-jsonschema-form/lib/utils');

**Comment by epicfaace** [comment]
This is fixed by 2.0.0-alpha.4
