### ISSUE TITLE
Make a input field required if two conditions are true

### ISSUE THREAD

**Issue by grgicpetar** [rjsf-team/react-jsonschema-form#1670]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

type: nested

I am trying to make a input field required if two of conditions are true. I am able how to make it work with one condition, but how do I nest them correctly? Ideally it would be OneOf inside of OneOf in Dependencies...

### Steps to Reproduce

I am sharing a playground example I made.
I am aware this is just asking for help, probably not a real issue. But if someone may point me to the right direction it would be helpful.

Ideally the Test Dependency text field should be required if Test Radio equals "Require" and if Test Select equals "select 2".

[Playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0ZXN0UmFkaW8iOiJPcHRpb25hbCIsInRlc3RTZWxlY3QiOiJzZWxlY3QgMSIsIkEiOnsiQSI6Ii0tc2VsZWN0LS0iLCJCIjoiTk9STUFMIn19LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidGVzdFJhZGlvIjp7InRpdGxlIjoiVGVzdCByYWRpbyIsInR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIk9wdGlvbmFsIiwiUmVxdWlyZSJdLCJkZWZhdWx0IjoiSGlkZSJ9LCJ0ZXN0RGVwZW5kZW5jeSI6eyJ0aXRsZSI6IlRlc3QgRGVwZW5kZW5jeSIsInR5cGUiOiJzdHJpbmciLCJtaW5MZW5ndGgiOjEsInBsYWNlaG9sZGVyIjoiVGVzdCBEZXBlbmRlbmN5In0sInRlc3RTZWxlY3QiOnsidGl0bGUiOiJUZXN0IFNlbGVjdCIsInR5cGUiOiJzdHJpbmciLCJlbnVtIjpbInNlbGVjdCAxIiwic2VsZWN0IDIiLCJzZWxlY3QgMyJdLCJkZWZhdWx0Ijoic2VsZWN0IDEifX0sImRlcGVuZGVuY2llcyI6eyJ0ZXN0UmFkaW8iOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsidGVzdFJhZGlvIjp7ImVudW0iOlsiT3B0aW9uYWwiXX19fSx7InByb3BlcnRpZXMiOnsidGVzdFJhZGlvIjp7ImVudW0iOlsiUmVxdWlyZSJdfX0sInJlcXVpcmVkIjpbInRlc3REZXBlbmRlbmN5Il19XX19fSwidWlTY2hlbWEiOnsidGVzdFJhZGlvIjp7InVpOndpZGdldCI6InJhZGlvIn19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOnRydWUsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

#### Expected behavior

Make an input field depend on two conditions.

#### Actual behavior

I am not aware how to implement this functionality.

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by epicfaace** [comment]
[This is probably how you'd do it with JSON Schema](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0ZXN0U2VsZWN0Ijoic2VsZWN0IDIiLCJ0ZXN0UmFkaW8iOiJSZXF1aXJlIn0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0Iiwib25lT2YiOlt7InByb3BlcnRpZXMiOnsidGVzdFJhZGlvIjp7ImVudW0iOlsiT3B0aW9uYWwiXX19fSx7InByb3BlcnRpZXMiOnsidGVzdFJhZGlvIjp7ImVudW0iOlsiUmVxdWlyZSJdfSwidGVzdFNlbGVjdCI6eyJlbnVtIjpbInNlbGVjdCAyIl19fSwicmVxdWlyZWQiOlsidGVzdERlcGVuZGVuY3kiXX1dLCJwcm9wZXJ0aWVzIjp7InRlc3RSYWRpbyI6eyJ0aXRsZSI6IlRlc3QgcmFkaW8iLCJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJPcHRpb25hbCIsIlJlcXVpcmUiXSwiZGVmYXVsdCI6IkhpZGUifSwidGVzdERlcGVuZGVuY3kiOnsidGl0bGUiOiJUZXN0IERlcGVuZGVuY3kiLCJ0eXBlIjoic3RyaW5nIiwibWluTGVuZ3RoIjoxLCJwbGFjZWhvbGRlciI6IlRlc3QgRGVwZW5kZW5jeSJ9LCJ0ZXN0U2VsZWN0Ijp7InRpdGxlIjoiVGVzdCBTZWxlY3QiLCJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJzZWxlY3QgMSIsInNlbGVjdCAyIiwic2VsZWN0IDMiXSwiZGVmYXVsdCI6InNlbGVjdCAxIn19fSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOnRydWUsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=), though evidently our oneOf field doesn't work well for such cases.
