### ISSUE TITLE
UI updated but “FormData” is not updating when using “dependencies” and “oneOf” 

### ISSUE THREAD

**Issue by YanivKimhi** [rjsf-team/react-jsonschema-form#1671]
### Prerequisites

- [v ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [v ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [v ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

With default value:
https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJlbnVtMSI6InYzIiwiZW51bTIiOiJ2MTMifSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImVudW0xIjp7InRpdGxlIjoiRW51bTEiLCJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJ2MSIsInYyIiwidjMiXX0sImVudW0yIjp7InRpdGxlIjoiRW51bTIiLCJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJ2MTEiLCJ2MTIiLCJ2MTMiLCJ2MjEiLCJ2MjIiLCJ2MjMiLCJ2MzEiLCJ2MzIiLCJ2MzMiXX19LCJkZXBlbmRlbmNpZXMiOnsiZW51bTEiOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsiZW51bTEiOnsiZW51bSI6WyJ2MSJdfSwiZW51bTIiOnsiZW51bSI6WyJ2MTEiLCJ2MTIiLCJ2MTMiXSwiZGVmYXVsdCI6InYxMSJ9fX0seyJwcm9wZXJ0aWVzIjp7ImVudW0xIjp7ImVudW0iOlsidjIiXX0sImVudW0yIjp7ImVudW0iOlsidjIxIiwidjIyIiwidjIzIl0sImRlZmF1bHQiOiJ2MjEifX19LHsicHJvcGVydGllcyI6eyJlbnVtMSI6eyJlbnVtIjpbInYzIl19LCJlbnVtMiI6eyJlbnVtIjpbInYzMSIsInYzMiIsInYzMyJdLCJkZWZhdWx0IjoidjMxIn19fV19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOnRydWUsImxpdmVPbWl0Ijp0cnVlfX0=
:
No default value 
https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJlbnVtMSI6InYzIiwiZW51bTIiOiJ2MTMifSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImVudW0xIjp7InRpdGxlIjoiRW51bTEiLCJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJ2MSIsInYyIiwidjMiXX0sImVudW0yIjp7InRpdGxlIjoiRW51bTIiLCJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJ2MTEiLCJ2MTIiLCJ2MTMiLCJ2MjEiLCJ2MjIiLCJ2MjMiLCJ2MzEiLCJ2MzIiLCJ2MzMiXX19LCJkZXBlbmRlbmNpZXMiOnsiZW51bTEiOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsiZW51bTEiOnsiZW51bSI6WyJ2MSJdfSwiZW51bTIiOnsiZW51bSI6WyJ2MTEiLCJ2MTIiLCJ2MTMiXX19fSx7InByb3BlcnRpZXMiOnsiZW51bTEiOnsiZW51bSI6WyJ2MiJdfSwiZW51bTIiOnsiZW51bSI6WyJ2MjEiLCJ2MjIiLCJ2MjMiXX19fSx7InByb3BlcnRpZXMiOnsiZW51bTEiOnsiZW51bSI6WyJ2MyJdfSwiZW51bTIiOnsiZW51bSI6WyJ2MzEiLCJ2MzIiLCJ2MzMiXX19fV19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOnRydWUsImxpdmVPbWl0Ijp0cnVlfX0=

### Description
In the attached examples, when selecting Enum1 value, Enum2 updates in the UI but FormData does not change.

[Description of the bug or feature]
FormData for Enum2 should update when default value exists and cleared when no default value.

### Steps to Reproduce
1. Change Enum1 
2. Check if Enum2 updates in the UI (Yes)
3. Check if Enum2 updates in the FormData (No)

#### Expected behavior
FormData should update and represent data in UI

#### Actual behavior
FormData does not update

### Version
1.8.1

**Comment by nishitkakkad** [comment]
@YanivKimhi - Both examples pretty much sums up the issue but it becomes more complicated to handle when you have different fields for oneOf dependencies unlike shared sample playground.
In such cases, we have leftover json blocks in formData even you have switched already to other enum value.
With Live validation we can see validation messages for allowed oneOf enums but user will have no idea what to do for that. 
Enabling omitExtraData and LiveOmit blocking insertion of containers.
