### ISSUE TITLE
Material UI Range widget does not show the current value

### ISSUE THREAD

**Issue by heath-freenome** [rjsf-team/react-jsonschema-form#1674]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Unlike the Bootstrap version, which shows the current value, the material UI version of the `RangeWidget` does not.

### Steps to Reproduce

1. Go to the [playground](https://rjsf-team.github.io/react-jsonschema-form/) and click on the `Numbers` tab
2. Move the slider and notice the value being displayed below the slider is changed
3. Switch to the material UI view and move the slider and notice there is no value being displayed

#### Expected behavior

I would expect to see the value in the Material UI `RangeWidget`

#### Actual behavior

I don't see the value like I do for the bootstrap version...

NOTE: There is a single prop for the Material UI `Slider` that can be enabled to do this automatically. Setting the `valueLabelDisplay` prop to `on` will show the current value as a tooltip, always as shown [here](https://material-ui.com/components/slider/#label-always-visible).  It should be an extremely simple fix, simply add the prop after this [line](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/material-ui/src/RangeWidget/RangeWidget.tsx#L47).

### Version

Whatever version the playground uses

**Comment by heath-freenome** [comment]
@epicfaace Is this something you can do easily?

**Comment by dekelb** [comment]
Once #1672 is merged this can be resolved

**Comment by stanlemon** [comment]
I'm offering a short term fix in #1822
