### ISSUE TITLE
Material UI View does not respect "ui:title" value

### ISSUE THREAD

**Issue by heath-freenome** [rjsf-team/react-jsonschema-form#1675]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

While the core theme will change the Label of a field to match the `ui:title` in the UISchema, the material UI view does not.

### Steps to Reproduce

1. Go to the [playground](https://rjsf-team.github.io/react-jsonschema-form/) and select the `ErrorSchema` choice
2. Notice the Label for the `Age` field says `Age of person`
3. Switch to the material ui theme
4. Notice the Label for the `Age` field says `Age`

#### Expected behavior

The material UI view picks up the `ui:title` of a field from the UI schema

#### Actual behavior

The material UI view picks up the default title of the field from the schema

### Version

whatever version the playground is running

**Comment by heath-freenome** [comment]
Maybe it's related to this line in [ObjectFieldTemplate](https://github.com/rjsf-team/react-jsonschema-form/blob/f3be67e7fe45c4c6437b72a4866f7073090fc58b/packages/material-ui/src/ObjectFieldTemplate/ObjectFieldTemplate.tsx#L31) not using the `ui:title`?

**Comment by rafde** [comment]
When I ran into this issue, I noticed 
https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/fields/StringField.js#L30
https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/fields/StringField.js#L47
when I traced why the `ui:title` wasn't working.

I ended up making a wrapper component for `StringField`. Here's a winded example

```jsx
import React, { memo, } from 'react';
import Form, { Theme, } from '@rjsf/material-ui';

const {
	fields: muiFields,
} = Theme;

const {
	StringField: MUIStringField,
} = muiFields;

const StringField = memo( function StringFieldComponent( props ) {
	let _props = props;
	const title = props?.uiSchema?.['ui:title'];

	if ( title ) {
		const {
			schema,
		} = props;
		_props = {
			...props,
			schema: {
				...schema,
				title,
			},
		};
	}

	return <MUIStringField {
		..._props
	} />;
} );

const fields = {
	StringField,
};

export default memo( function FormBuilderComponent( props ) {
	return <Form {...{
		fields,
		...props,
	}} />;
} );
```

**Comment by jonathanstanley** [comment]
Some additional notes:

- nested ui:title fails for material-ui, semantic-ui, fluent-ui, and bootstrap-4. 
- antd keeps ui:title correctly, however it does not represent the ui:description correctly

[concise playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6Im9yZyIsIiRzY2hlbWEiOiJodHRwOi8vanNvbi1zY2hlbWEub3JnL2RyYWZ0LTA3L3NjaGVtYSMiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJncm91cCI6eyJ0aXRsZSI6Imdyb3VwIiwidHlwZSI6InN0cmluZyJ9fX0sInVpU2NoZW1hIjp7InVpOnRpdGxlIjoiTXkgT3JnYW5pemF0aW9uIiwidWk6ZGVzY3JpcHRpb24iOiJUaGUgdG9wIGxldmVsIiwiZ3JvdXAiOnsidWk6dGl0bGUiOiJNeSBHcm91cCAqKnRoaXMgdGl0bGUgZG9lc24ndCBzaG93IG9uIG1hdGVyaWFsdWkgdGhlbWUqKiIsInVpOmRlc2NyaXB0aW9uIjoiTXkgZ3JvdXAgZGVzY3JpcHRpb24iLCJ1aTpwbGFjZWhvbGRlciI6ImhlcmUgaXMgYSBwbGFjZWhvbGRlciJ9fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==) ... just toggle between themes.

**Comment by epicfaace** [comment]
Yeah, that's unfortunate. Would definitely be open to merging a fix for this (both for the material-ui theme, or other themes as well).
