### ISSUE TITLE
index.d.ts is not properly included in the v2.0.0-alpha.4

### ISSUE THREAD

**Issue by joeraygme** [rjsf-team/react-jsonschema-form#1682]
### Description

index.d.ts is not properly included in the v2.0.0-alpha.4

copy [index.d.ts](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/index.d.ts) to node_modules/@rjsf/core

### Steps to Reproduce
yarn install @rjsf/core

no index.d.ts in node_modules/@rjsf/core
#### Expected behavior

index.d.ts in node_modules/@rjsf/core

#### Actual behavior

tsx files can't compile

### Version

v2.0.0-alpha.4

**Comment by epicfaace** [comment]
fixed by #1676
