### ISSUE TITLE
The ui:widget hidden does not hide description

### ISSUE THREAD

**Issue by j-zimnowoda** [rjsf-team/react-jsonschema-form#1683]
### Prerequisites
@rjsf/material-ui

### Description

By hiding a field it should hide all field related ui items (e.g.: labels, description etc.)
### Steps to Reproduce
uiSchema
```
{
      myfield: { 'ui:widget': 'hidden' },
}
```
schema
```
{
  "mySchema": {
    "type": "object",
    "properties": {
      "myfield": {
        "type": "string",
        "description": "myfield description"
      }
    }
  }
}
```

#### Expected behavior

Whole `div` element is hidden

```
<div class="MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12" style="margin-bottom: 10px;" hidden>
  <div class="MuiFormControl-root MuiFormControl-fullWidth">
    <input id="root_myfield" value="">
    <span class="MuiTypography-root MuiTypography-caption MuiTypography-colorTextSecondary">myfield description</span>
  </div>
</div>
```
#### Actual behavior

Description is still visible
Only input field is marked as hidden

```
<div class="MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12" style="margin-bottom: 10px;">
  <div class="MuiFormControl-root MuiFormControl-fullWidth">
    <input type="hidden" id="root_myfield" value="">
    <span class="MuiTypography-root MuiTypography-caption MuiTypography-colorTextSecondary">myfield description</span>
  </div>
</div>
```
### Version

    "@rjsf/core": "^2.0.0-alpha.4",
    "@rjsf/material-ui": "^2.0.0-alpha.4",

**Comment by Morriz** [comment]
One ugly workaround that still adds invisible space: `'ui:description': ' '`

**Comment by zhaoyao91** [comment]
![image](https://user-images.githubusercontent.com/3808838/85507981-c7c76480-b625-11ea-977b-b45a070e8e5b.png)
Not only description, but also the grid is left for the hidden widget (which is not expected)

**Comment by boskjoett** [comment]
Any progress or timeline for fixing this bug?
