### ISSUE TITLE
How best to test different themes?

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#1688]
In order to have a stable release and prevent regressions we need to have tests for the new themes that we add to this repository.

However, it doesn't seem that copying all the tests from `packages/core` will be effective or worth the effort, given that those tests test a lot of core functionality (not specific to a theme package), and also the fact that adapting the tests to work with a new theme will require significant changes because the HTML structure will be completely different.

I've been setting up tests to work for material-ui in https://github.com/rjsf-team/react-jsonschema-form/pull/1641. In that PR, I just added some snapshot tests for a list of given schemas. I'm thinking we can add tests that test interactivity such as button presses, etc. at a later time.

Any thoughts on this approach? Would appreciate any feedback / ideas on how to keep all the themes under test coverage.

**Comment by epicfaace** [comment]
@stanlemon since you've worked quite a bit with the material-ui theme -- any thoughts on this issue?

**Comment by stanlemon** [comment]
I'm OK with the snapshot testing, but it's implicitly brittle. I was going to attempt with one of the date tickets to do some more acceptance-style testing in jest. 

Anything with business logic, like #1807 should have coverage. 

I should probably write something to generally cover [`<TextWidget />`](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/material-ui/src/TextWidget/TextWidget.tsx) but I wouldn't expect something over [`<URLWidget />'](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/material-ui/src/URLWidget/URLWidget.tsx).

In the end we probably could come up with a Core set of flows (like in Form.test.tsx) that cover specific UI patterns and then could be reused.

This is more of a stream of conscience right now than a strong opinion. :)

**Comment by epicfaace** [comment]
Yeah, I like the idea of having a base set of acceptance tests that every theme should pass. This way, we can also more easily review themes to make sure they are fully functional.
