### ISSUE TITLE
Additional properties change key cause all title lost

### ISSUE THREAD

**Issue by wenerme** [rjsf-team/react-jsonschema-form#1706]
### Prerequisites

- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

* https://rjsf-team.github.io/react-jsonschema-form/

### Steps to Reproduce

![demo-rjsf](https://user-images.githubusercontent.com/1777211/79579749-92206f80-80fa-11ea-9747-9a5c0f2b1b63.gif)

#### Expected behavior

works

#### Actual behavior

title lost

### Version

latest, test on 2.0.0.alpha.6

**Comment by epicfaace** [comment]
There appears to have been an older version deployed to the playground; I've just deployed the latest version and this no longer seems to be an issue. I've made https://github.com/rjsf-team/react-jsonschema-form/pull/1722 to make sure this doesn't happen again, though.

**Comment by DenBy1726** [comment]
The issue is still there. Please, check playground.

**Comment by epicfaace** [comment]
Sorry, I mistakenly closed this issue. It's the same as #1749 (which has a pending PR to fix it), though.
