### ISSUE TITLE
Module not found: Can't resolve '@rjsf/core' when using simple example from documentation 

### ISSUE THREAD

**Issue by d-malko** [rjsf-team/react-jsonschema-form#1707]
### Description

I saw issue #1685, maybe this issue related.
Trying to run simple example from the documentation, but faceoff the problem with import issue
```
Module not found: Can't resolve '@rjsf/core' in '../src/components/Home'
```

### Steps to Reproduce
run
 `npm install react-jsonschema-form --save`

```
import React from "react";
import Form from "@rjsf/core";

const schema = {
  title: "Todo",
  type: "object",
  required: ["title"],
  properties: {
    title: {type: "string", title: "Title", default: "A new task"},
    done: {type: "boolean", title: "Done?", default: false}
  }
};
const log = (type) => console.log.bind(console, type);
export default function Home() {
  return (
    <div>
      <Form schema={schema}
        onChange={log("changed")}
        onSubmit={log("submitted")}
        onError={log("errors")} />
    </div>
  );
}
```

#### Actual behavior
import issue
```
Module not found: Can't resolve '@rjsf/core' in '/containers/fto/src/components/Home'
```
### Version

"react-jsonschema-form": "^1.8.1"

**Comment by epicfaace** [comment]
Did you do `npm install @rjsf/core`? @rjsf/core is for version 2.x while if you want to use react-jsonschema-form, you'll have to replace @rjsf/core with react-jsonschema-form.

**Comment by d-malko** [comment]
Thank you for your answer! It helped!

**Comment by epicfaace** [comment]
Playground is in this folder: https://github.com/rjsf-team/react-jsonschema-form/tree/master/packages/playground

**Comment by d-malko** [comment]
Thank you a lot! 
Issue resolved.

**Comment by epicfaace** [comment]
No problem. We'll be updating the docs to make things clearer in this PR: #1691

**Comment by uriva** [comment]
fwiw I stumbled across this issue as well.

**Comment by charitygrace** [comment]
You should changed your documentation to use `import Form from "react-jsonschema-form"`
rather than `import Form from "@rjsf/core"` if you direct people to install `npm install react-jsonschema-form`.  See this page: https://react-jsonschema-form.readthedocs.io/en/latest/#usage

![Screen Shot 2020-04-25 at 7 18 04 PM](https://user-images.githubusercontent.com/2454516/80293027-d37fd300-8729-11ea-9e28-38457fcb4375.png)

**Comment by epicfaace** [comment]
Oops, it appears our docs build was broken -- it's been fixed now (https://github.com/rjsf-team/react-jsonschema-form/pull/1729) and the latest docs should be up now.

**Comment by charitygrace** [comment]
Thanks
