### ISSUE TITLE
An extra title is rendered while using anyOf

### ISSUE THREAD

**Issue by j-zimnowoda** [rjsf-team/react-jsonschema-form#1711]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] I'm providing a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJJRCI6eyJmaXJzdE5hbWUiOiJDaHVjayJ9LCJmaXJzdE5hbWUiOiJDaHVjayJ9LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiSUQiOnsiYW55T2YiOlt7InRpdGxlIjoiRmlyc3QgbWV0aG9kIG9mIGlkZW50aWZpY2F0aW9uIiwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRmlyc3QgbmFtZSIsImRlZmF1bHQiOiJDaHVjayJ9LCJsYXN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJMYXN0IG5hbWUifX19LHsidGl0bGUiOiJTZWNvbmQgbWV0aG9kIG9mIGlkZW50aWZpY2F0aW9uIiwicHJvcGVydGllcyI6eyJpZENvZGUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiSUQgY29kZSJ9fX1dfX19LCJ1aVNjaGVtYSI6eyJJRCI6eyJ1aTp3aWRnZXQiOiJyYWRpbyIsInVpOm9wdGlvbnMiOnsiaW5saW5lIjp0cnVlfX19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOnRydWUsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=) demonstrating the issue.

### Description

The `anyOf` attribute allows to select optional schemas.
By default `anyOf` renders as a dropdown that contains schema titles - cool.

Unfortunately this title is repeated below the dropdown element, what is redundant.
### Steps to Reproduce
See shared playground link.

#### Expected behavior
The title is only visible as an option to be selected.
To have an `ui:option` that instructs to not render redundant titles.

#### Actual behavior
From the shared playground link, title "First method of identification" is rendered three times.

### Version

    "react-jsonschema-form": "^1.8.1",

**Comment by sramaswami11** [comment]
@j-zimnowoda , it looks like we are missing an extra piece of "type":"object" for each element of the anyOf array in the JSONschema, I have [shared playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJJRCI6eyJmaXJzdE5hbWUiOiJDaHVjayJ9LCJmaXJzdE5hbWUiOiJDaHVjayJ9LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiSUQiOnsiYW55T2YiOlt7InR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6IkZpcnN0IG1ldGhvZCBvZiBpZGVudGlmaWNhdGlvbiIsInByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkZpcnN0IG5hbWUiLCJkZWZhdWx0IjoiQ2h1Y2sifSwibGFzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiTGFzdCBuYW1lIn19fSx7InR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6IlNlY29uZCBtZXRob2Qgb2YgaWRlbnRpZmljYXRpb24iLCJwcm9wZXJ0aWVzIjp7ImlkQ29kZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJJRCBjb2RlIn19fV19fX0sInVpU2NoZW1hIjp7IklEIjp7InVpOndpZGdldCI6InJhZGlvIiwidWk6b3B0aW9ucyI6eyJpbmxpbmUiOnRydWV9fX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)  here to show that if you added those then the problem goes away. Please check the json schema specs for "anyOf" and if you can confirm that this is a schema error, then close this issue.

**Comment by j-zimnowoda** [comment]
@sramaswami11, thanks for good hint.
Indeed after adding `"type":"object" ` we can get rid of one an additional title.

Is there any way to have a title visible just in radio/dropdown element, so the rendered form below does not contain the title?

Rationale:
Since a user has already chosen a given item from `anyOf`, it is clear that form rendered below is related to that item, so we do not to render the title second time.

**Comment by mr-bjerre** [comment]
Any pointers on how to fix this? I might give it a try

**Comment by mzvast** [comment]
Any way to fix this?

**Comment by aaraney** [comment]
watching @aaraney

**Comment by heath-freenome** [comment]
@mzvast @aaraney @j-zimnowoda In 5.x using the `"ui:options": { label: false }` fixes this issue as can be see in this modified [playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJJRCI6eyJmaXJzdE5hbWUiOiJDaHVjayJ9LCJmaXJzdE5hbWUiOiJDaHVjayJ9LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiSUQiOnsiYW55T2YiOlt7InRpdGxlIjoiRmlyc3QgbWV0aG9kIG9mIGlkZW50aWZpY2F0aW9uIiwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRmlyc3QgbmFtZSIsImRlZmF1bHQiOiJDaHVjayJ9LCJsYXN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJMYXN0IG5hbWUifX19LHsidGl0bGUiOiJTZWNvbmQgbWV0aG9kIG9mIGlkZW50aWZpY2F0aW9uIiwicHJvcGVydGllcyI6eyJpZENvZGUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiSUQgY29kZSJ9fX1dfX19LCJ1aVNjaGVtYSI6eyJJRCI6eyJ1aTp3aWRnZXQiOiJyYWRpbyIsInVpOm9wdGlvbnMiOnsiaW5saW5lIjp0cnVlLCJsYWJlbCI6ZmFsc2V9fX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

**Comment by GlennButera** [comment]
@heath-freenome Would there be any consideration to re-opening this issue?  While I understand that the statement from Apr 9 shows off the "ui:options" feature for removing labels, the label that is removed is the root level label, which is inline with the other properties in an object.  In some cases of "anyOf" with object properties, the label on the input itself may be better served to be removed, as the radio or dropdown already has the label (from the title).

Here is a [playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCIsInRlbGVwaG9uZSI6IjEtODAwLUtJQ0tBU1MifSwic2NoZW1hIjp7IiRpZCI6ImV4YW1wbGUiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJpZCI6eyJhbnlPZiI6W3sidHlwZSI6InN0cmluZyIsInBhdHRlcm4iOiJeWzEtOV1bMC05XSskIiwidGl0bGUiOiJpZCBbc3RyaW5nXSJ9LHsidHlwZSI6Im51bWJlciIsIm1pbmltdW0iOjEsInRpdGxlIjoiaWQgW251bWJlcl0ifV19LCJzdW1tYXJ5Ijp7InR5cGUiOlsic3RyaW5nIiwibnVsbCJdfX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsIm5vSHRtbDVWYWxpZGF0ZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZSwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjoicG9wdWxhdGUifX19) showing off the duplicate label right below the dropdown.  Using a ui schema of  `{ "id": { "ui:options": { "label": false } } }` removes both labels (subschema label and label under dropdown).

**Comment by heath-freenome** [comment]
@GlennButera Ah, interesting use case. Which label are you trying to remove?
