### ISSUE TITLE
Allow duplicate items

### ISSUE THREAD

**Issue by kasinau** [rjsf-team/react-jsonschema-form#1712]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I see that we can add new items in two ways using ArrayFields, either adding a  new item at the bottom of the list, using `onAddClick`, or adding a new item on a specific index, using `onAddIndexClick`. 

These are really nice features, but it adds an empty item, or, pre-populated with the default values set in the schema.

What I need is to be able to duplicate an item, and, I'm curious if maybe there's a `duplicate item` functionality, or, maybe it is possible to add a new item with pre-set values?

Thank you!

**Comment by epicfaace** [comment]
You couldn't do that with `onAddClick`, but you could instead store the form data in the component's state, then use `setState` to change the form data.

**Comment by votar1408** [comment]
@epicfaace Sorry for the extra question, after creating a custom ArrayField component in the props I see formData with my actual data information and empty formContext. How can I update the state for re-render form?
