### ISSUE TITLE
radios and checkboxes use different colors

### ISSUE THREAD

**Issue by Morriz** [rjsf-team/react-jsonschema-form#1717]
I would expect them both to be primary.

Radio: primary
Checkboxes: secondary

Why??????

**Comment by epicfaace** [comment]
They look the same color to me --

![image](https://user-images.githubusercontent.com/1689183/80217118-244dd980-860d-11ea-823f-b82df60c7969.png)


This is likely a browser-dependent behavior that you might be seeing.

**Comment by matthias-ccri** [comment]
I am also seeing checkboxes in color=secondary.

![image](https://user-images.githubusercontent.com/18034092/91489145-53f04500-e87e-11ea-8d25-a6b7bc5b32a8.png)

I don't know why you're seeing them as one color, but the props say one is primary and the other is secondary:
![image](https://user-images.githubusercontent.com/18034092/91489238-7bdfa880-e87e-11ea-8aea-6acdabeebe4a.png)
