### ISSUE TITLE
material-ui Add support for additionalProperties

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#1724]
### Description

We should add support for additionalProperties for the `@rjsf/material-ui` theme.

bootstrap:
![image](https://user-images.githubusercontent.com/1689183/80288540-98b87380-8706-11ea-812d-afbb58eb9042.png)

material-ui:
![image](https://user-images.githubusercontent.com/1689183/80288567-bede1380-8706-11ea-8b9f-71a7fdda8e5f.png)

**Comment by Rayray625** [comment]
Hi @epicfaace ,
Does this enhancement have ETA? I'm currently dealing with this improvement, too.
Thanks.

**Comment by jeffothy** [comment]
@epicfaace I started using rjsf for a project and this issue prevented us from utilizing material-ui, so I thought I'd use it to get my contribution feet wet (#1993).

But it seems I failed to search through open PRs to see that @ValYouW created #1982 review which covers this (for some reason it didn't show in this issue's thread). 
I'm fine with closing this #1993 if #1982 is preferred.

**Comment by ValYouW** [comment]
I'm fine going with #1993 - the more contributors the better...! I'll add my comments there.

**Comment by epicfaace** [comment]
Closed by #1993
