### ISSUE TITLE
Use default material-ui button component for submit

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#1725]
# Description

We should use the default material-ui button component for the default submit button, rather than just rendering a plain button.

bootstrap:

![image](https://user-images.githubusercontent.com/1689183/80288610-f0ef7580-8706-11ea-8610-d077016a3340.png)

material-ui:

![image](https://user-images.githubusercontent.com/1689183/80288600-e03eff80-8706-11ea-862c-3be1a6130255.png)

**Comment by delyanr** [comment]
@epicfaace Why don't we simply create a SubmitWidget which renders the button, and instead of using the button tag in the Form component, we use SubmitWidget?

**Comment by epicfaace** [comment]
Not sure a widget is the right way to go about it, since a widget implies that you can use `ui:widget` to access it.

I think we might actually be able to do this by doing something like this:
`withTheme({ children: () => <button>custom submit button</button> });`

Do you think that might work?

**Comment by delyanr** [comment]
A pure widget will not work, you are right, but then some component that is similar to ErrorList and is passed to the Theme object would. The withTheme can then leverage it and, if no children are present, pass it down to the Form component.

Your suggestion would mean that the user of a theme must always define their submit button, so it doesn't work out-of-the-box, which is slightly counter-intuitive. And also, the playground will need to be rewritten and add buttons for each theme separately.

**Comment by epicfaace** [comment]
> Your suggestion would mean that the user of a theme must always define their submit button, so it doesn't work out-of-the-box,

Sorry, I don't think I was clear with my suggestion. I meant that in the theme object itself (like at https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/material-ui/src/Theme/Theme.ts#L20), we can define a `children` key and put the submit component there (and also pass down the `children` key to the form in the actual implementation of `withTheme`). What do you think?

**Comment by delyanr** [comment]
Ahh, yes, sorry for the misunderstanding. This is pretty much aligned then with what I was thinking as well. It can potentially be called `defaultChildren` to avoid confusion. Makes sense to me.

**Comment by epicfaace** [comment]
@delyanr I actually got submit button customization to work without any changes to `@rjsf/core` -- just pass in `React.createElement([submit button element])` to the `children` prop in `withTheme`. See https://github.com/epicfaace/react-jsonschema-form/commit/d86ee6ca37c45f5e2fdf6323e0f040706bc4479b#diff-db6a7dd8a035ee6212a2521ed0f983b2R23

I think you should be able to use this.

**Comment by stanlemon** [comment]
@epicfaace if you want I can take a stab at this. Your suggestion above looks easy enough to tackle.
