### ISSUE TITLE
material-ui datepickers

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#1726]
### Description

Currently, we only use the native datepicker for the material-ui theme.

![image](https://user-images.githubusercontent.com/1689183/80290145-97d90f00-8711-11ea-94ac-e4affb4bfd35.png)

It would be good to use [the material-ui pickers](https://material-ui.com/components/pickers/#date-time-pickers) if @material-ui/pickers is installed, and if not, fall back to the native datepicker.

**Comment by stanlemon** [comment]
@epicfaace You wanted to wait on this until a major version, correct?

**Comment by jonra1993** [comment]
Hello @stanlemon @epicfaace do you know which is the correct format for using material-ui pickers I always get incorrect format using custom widget. I always get day name not date 
![image](https://user-images.githubusercontent.com/23468720/100126568-1afb4880-2e4c-11eb-8641-f15ed569cac9.png)

**Comment by stanlemon** [comment]
@jonra1993 It should be MM/dd/yyyy
