### ISSUE TITLE
material-ui alternative date widget needs fixing

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#1727]
### Description

Currently, [it looks like this](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJuYXRpdmUiOnt9LCJhbHRlcm5hdGl2ZSI6e319LCJzY2hlbWEiOnsidGl0bGUiOiJEYXRlIGFuZCB0aW1lIHdpZGdldHMiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJuYXRpdmUiOnsidGl0bGUiOiJOYXRpdmUiLCJkZXNjcmlwdGlvbiI6Ik1heSBub3Qgd29yayBvbiBzb21lIGJyb3dzZXJzLCBub3RhYmx5IEZpcmVmb3ggRGVza3RvcCBhbmQgSUUuIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZGF0ZXRpbWUiOnsidHlwZSI6InN0cmluZyIsImZvcm1hdCI6ImRhdGUtdGltZSJ9LCJkYXRlIjp7InR5cGUiOiJzdHJpbmciLCJmb3JtYXQiOiJkYXRlIn19fSwiYWx0ZXJuYXRpdmUiOnsidGl0bGUiOiJBbHRlcm5hdGl2ZSIsImRlc2NyaXB0aW9uIjoiVGhlc2Ugd29yayBvbiBtb3N0IHBsYXRmb3Jtcy4iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJhbHQtZGF0ZXRpbWUiOnsidHlwZSI6InN0cmluZyIsImZvcm1hdCI6ImRhdGUtdGltZSJ9LCJhbHQtZGF0ZSI6eyJ0eXBlIjoic3RyaW5nIiwiZm9ybWF0IjoiZGF0ZSJ9fX19fSwidWlTY2hlbWEiOnsiYWx0ZXJuYXRpdmUiOnsiYWx0LWRhdGV0aW1lIjp7InVpOndpZGdldCI6ImFsdC1kYXRldGltZSIsInVpOm9wdGlvbnMiOnsieWVhcnNSYW5nZSI6WzE5ODAsMjAzMF19fSwiYWx0LWRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGUiLCJ1aTpvcHRpb25zIjp7InllYXJzUmFuZ2UiOlsxOTgwLDIwMzBdfX19fSwidGhlbWUiOiJtYXRlcmlhbC11aSIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==):

![image](https://user-images.githubusercontent.com/1689183/80290160-a8898500-8711-11ea-9e89-cdadb35a8aa5.png)

**Comment by delyanr** [comment]
Looking through the docs, it is not quite clear why we need alternative pickers. Is that to support older browsers? If so, keep in mind that Material UI and Ant Design do not support older browsers than IE11, and their native pickers already work with IE11.

**Comment by doncesarts** [comment]
For me it is not clear why this library even needs to support material-ui , I would argue it is out of the scope of this project. The fact that it provides the capability to use any theme should be enough. Any custom implementation of a theme can be handle in a separate repository/library . 

Reviewing the last issues added to this repository , many of them are related to material-ui, not  all the users of this project are interested on that feature.  From my perspective I think that is more important to address issues/bugs related to the core package, and give the opportunity to others to open / handle / manage their priorities regarding to material-ui theme on their own repository.

**Comment by epicfaace** [comment]
@doncesarts Yes, @rjsf/core is the package with the core functionality -- others can make their own themes in their own repos, but @rjsf/material-ui is an "officially" supported theme. See this for original context for why the decision was made to keep everything in one repository: https://github.com/rjsf-team/react-jsonschema-form/issues/1222#issuecomment-511054781

**Comment by ronny-rentner** [comment]
So what is the plan here? Use the none-native datepicker UI so it also works on Firefox, Safari and Opera?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

https://material-ui.com/components/pickers/
