### ISSUE TITLE
Default values on custom widgets from outside sources

### ISSUE THREAD

**Issue by lmeerwood** [rjsf-team/react-jsonschema-form#1731]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/43xr1fbd/4/)  demonstrating the issue.

### Description

I am trying to set custom components to have default values. However, these default values don't come from the schema, but other external sources. The problem I am having is that if I have a page with multiple custom widgets that set the default value on creation, only the last widget in the form has the default value set. In the example provided I made a simple Date field that defaults to today's value. On submission you can see that only the last date in the form actually has a value.

We did manage to solve this by wrapping the `onChange` call in a useEffect hook and adding a timeout to the `onChange`. This [JSFiddle](https://jsfiddle.net/43xr1fbd/5/) shows how we have it setup, but for some reason I cannot get React.useEffect to work on the JSFiddle setup so the example doesn't actually work...

So my main question is, is this the correct / best available way to set a default value on a custom widget? I know that onChange should really only be called when the value has actually changed, but I couldn't find another function available to the Widget that allowed me to set the value. 

### Steps to Reproduce

1. Create a custom component that calls `onChange` during creation to set a value.
2. Load a form that has multiple custom components that do this.
3. Submit form and see only one preset value come through

#### Expected behavior

All preset values are submitted

#### Actual behavior

Only last preset value is submitted

### Version

1.8.1

**Comment by osphost** [comment]
I'm also facing a similar issue

**Comment by gryevns** [comment]
Another example: https://codesandbox.io/s/eloquent-darkness-1cpq4?file=/src/index.js

`useEffect` called twice (two of the same custom widget) but only the last component value updated.

**Comment by gonzaloaune** [comment]
Were you able to find a workaround for this?

**Comment by lmeerwood** [comment]
@gonzaloaune Unfortunately, I left the company that I was using this library for shortly after creating this ticket. I have not touched it in a long time.

**Comment by ivanlewin** [comment]
@gonzaloaune Hi, I was trying to give 'now' values for my DateWidget by default and I ran into this problem. I *solved it* by using setTimeout; 

On mount, I set a timeout that, after 1 ms, calls `onChange` with the value for the current date. (I am not sure if the cleanup function is necessary since we're talking about 1ms here, but it's my attempt at good practices).


```javascript
    useEffect(() => {
        if (props.value === undefined) {
            const timeoutId = setTimeout(
                () => props.onChange(dayjs().format('YYYY-MM-DD')),
                1
            );
            return () => clearTimeout(timeoutId);
        }
    }, []);
```

(I'm on v2.5.1 so I don't know if this is solved on v3)

**Comment by gonzaloaune** [comment]
Thanks @ivanlewin, I ended up doing something similar but abandoned the use of this library altogether for something that I can have more control of. Thanks for the tip though!

**Comment by jcbrockschmidt** [comment]
> @gonzaloaune Hi, I was trying to give 'now' values for my DateWidget by default and I ran into this problem. I _solved it_ by using setTimeout;
> 
> On mount, I set a timeout that, after 1 ms, calls `onChange` with the value for the current date. (I am not sure if the cleanup function is necessary since we're talking about 1ms here, but it's my attempt at good practices).
> 
> ```js
>     useEffect(() => {
>         if (props.value === undefined) {
>             const timeoutId = setTimeout(
>                 () => props.onChange(dayjs().format('YYYY-MM-DD')),
>                 1
>             );
>             return () => clearTimeout(timeoutId);
>         }
>     }, []);
> ```
> 
> (I'm on v2.5.1 so I don't know if this is solved on v3)


For anyone stumbling across this, I was able to simplify this to something like
```js
    useEffect(() => {
        if (props.value === undefined) {
            return () => props.onChange(dayjs().format('YYYY-MM-DD'));
        }
    }, []);
```

I'm on v4.2.0. The original issue appears to be unsolved still.
