### ISSUE TITLE
UISchema classNames do not work with material-ui theme

### ISSUE THREAD

**Issue by bwbroersma** [rjsf-team/react-jsonschema-form#1738]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

UISchema [`classNames`](https://react-jsonschema-form.readthedocs.io/en/latest/form-customization/#custom-css-class-names) do not seem to work with the `material-ui` theme.

### Steps to Reproduce

See this simple sample:
JSONSchema
```json
{
  "properties": {
    "field": {
      "type": "string"
    }
  }
}
```
UISchema
```json
{
  "classNames": "extraClass"
}
```
See the playgrounds
* [with material-ui theme](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJwcm9wZXJ0aWVzIjp7ImZpZWxkIjp7InR5cGUiOiJzdHJpbmcifX19LCJ1aVNjaGVtYSI6eyJjbGFzc05hbWVzIjoiZXh0cmFDbGFzcyJ9LCJ0aGVtZSI6Im1hdGVyaWFsLXVpIiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjp0cnVlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19)
* [with default theme](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJwcm9wZXJ0aWVzIjp7ImZpZWxkIjp7InR5cGUiOiJzdHJpbmcifX19LCJ1aVNjaGVtYSI6eyJjbGFzc05hbWVzIjoiZXh0cmFDbGFzcyJ9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOnRydWUsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

#### Expected behavior

`extraClass` like in the `default` html output:
```html
<form class="rjsf">
 <div class="form-group field field-undefined  extraClass">
  <fieldset id="root">
   <div class="form-group field field-string">
    <label class="control-label" for="root">
     field
    </label>
    <input class="form-control" id="root" label="field" placeholder="" type="text" value="">
   </div>
  </fieldset>
 </div>
 <div>
  <button type="submit" class="btn btn-info">
   Submit
  </button>
 </div>
</form>
```

#### Actual behavior

No `extraClass` in the `material-ui` html output:
```html
<form class="rjsf">
 <div class="MuiFormControl-root MuiFormControl-fullWidth">
  <div class="MuiGrid-root jss5 MuiGrid-container MuiGrid-spacing-xs-2">
   <div class="MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12" style="margin-bottom: 10px;">
    <div class="MuiFormControl-root MuiFormControl-fullWidth">
     <div class="MuiFormControl-root MuiFormControl-fullWidth">
      <div class="MuiFormControl-root MuiTextField-root">
       <label class="MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated" data-shrink="false" for="root" id="root-label">
        field
       </label>
       <div class="MuiInputBase-root MuiInput-root MuiInput-underline MuiInputBase-formControl MuiInput-formControl">
        <input aria-invalid="false" id="root" name="" type="string" class="MuiInputBase-input MuiInput-input" value="">
       </div>
      </div>
     </div>
    </div>
   </div>
  </div>
 </div>
 <div>
  <button type="submit" class="btn btn-info">
   Submit
  </button>
 </div>
</form>
```

A [simple code search](https://github.com/rjsf-team/react-jsonschema-form/search?q=classnames+path:/packages/material-ui/src/&type=Code) shows no result for `classnames` in the path `/packages/material-ui/src/`.

### Version

The current [github pages version](https://github.com/rjsf-team/react-jsonschema-form/commit/347637b94c12e8c03833747556dfa979abec3083).

**Comment by bwbroersma** [comment]
Related to #1647

**Comment by hiitskiran** [comment]
If providing field level classNames is not yet supported for material UI, is there a work around until support is avaialble?

**Comment by psamerliondata** [comment]
Maybe not a real workaround, but what about a wrapper around the schema with a separate schema set with only the display none fields. and then with submit, submitting the wrapped json?

**Comment by jsduffy** [comment]
Any updates on this?

**Comment by leonoheart** [comment]
I met the same problem when using material ui, and as a workaround, I put className into formContext props and make it out. 

https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/form-props/#formcontext

**Comment by yanhan569046480** [comment]
> I met the same problem when using material ui, and as a workaround, I put className into formContext props and make it out.
> 
> https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/form-props/#formcontext

Hi, can you give us some examples about solving field style problems with formContext?

**Comment by mrpintcom** [comment]
I've been poking around debugging and inside SchemaField.js, there is this section:  
```
// See #439: uiSchema: Don't pass consumed class names to child components
  const field = (
    <FieldComponent
      ...
      uiSchema={{ ...uiSchema, classNames: undefined }}
      ...
    />
  );
```

With that, `classNames` will always be set to undefined when the any of the theme widgets are rendering. I don't know the reason why that was ever added and it seems like an anti-pattern to do it in this manner.


If uiSchema is passed along without modification, then something like this can be done in the themes TextWidget.tsx class:
```
className: uiSchema.classNames ? uiSchema.classNames : "",
```

At that point, the classNames passed into uiSchema would be attached to the element the theme creates - in this case `<TextField>` from material-ui would have the classNames you passed in.

Once you can pass classes in - you can use the normal useStyles/makeStyles paradigm:
```
const useStyles = makeStyles(muiTheme => ({
    halfWidth: {
        width: "50%"
    }
}));

function App() {

    const classes = useStyles();

    const uiSchema = {
        "basics": {
            classNames: "foobar", // a text based className can be passed
            "description": {
                classNames: classes.halfWidth, // or a material ui style can be used like this
                "ui:widget": 'textarea'
            }
        }
    }
```

I'd be willing to make a PR with these changes if I'm understanding everything correctly here.

**Comment by Ugolaf** [comment]
Has anyone investigated or solved the problem?

**Comment by benjaminbours** [comment]
Wow it's crazy such an important problem is still there for that long time! I'm gonna open a PR about it, I mean, it's the basic of such a theme library, to at least support the basic features of the form generator itself.

**Comment by heath-freenome** [comment]
Fixed in 5.x
