### ISSUE TITLE
Error when using specific schema

### ISSUE THREAD

**Issue by FBurner** [rjsf-team/react-jsonschema-form#1739]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
Getting this error if using specific json schema.

[PositionProfile.zip](https://github.com/rjsf-team/react-jsonschema-form/files/4568667/PositionProfile.zip)

Error: Could not find a definition for #/definitions/PostingInstructionType/properties/end/anyOf/1.

### Steps to Reproduce

1. load schema
2. put schema into form

const JobForm = props => {

    return (
        <Form schema={schema}
              onChange={log("changed")}
              onSubmit={log("submitted")}
              onError={log("errors")}
        />
    );
};

#### Expected behavior

Json schema would be parsed and shown as form.

#### Actual behavior

Error: Could not find a definition for #/definitions/PostingInstructionType/properties/end/anyOf/1.
utils.js:562
    findSchemaDefinition utils.js:562
    computeDefaults utils.js:205
    computeDefaults utils.js:231
    reduce self-hosted:303
    computeDefaults utils.js:228
    computeDefaults utils.js:231
    reduce self-hosted:303
    computeDefaults utils.js:228
    getDefaultFormState utils.js:286
    getStateFromProps Form.js:255
    Form Form.js:224
    React 16
    js index.js:47
    Webpack 7

### Version
2.0.0

**Comment by epicfaace** [comment]
It might have to do with the fact that your ref is to an element of an array. Could you make an example on the playground so it's easier to test and isolate the issue?

**Comment by FBurner** [comment]
playground also crashing

Focused root_firstName with value Chuck 2 bundle.js:88:436193
Touched root_firstName with value Chuck bundle.js:88:436104
Error: "Could not find a definition for #/definitions/PostingInstructionType/properties/end/anyOf/1."

**Comment by epicfaace** [comment]
@FBurner can you create and send a shared playground link? You can do so by clicking the "Share" button on the top right.

![image](https://user-images.githubusercontent.com/1689183/80931344-38b97100-8d87-11ea-9561-e852621a001e.png)

**Comment by FBurner** [comment]
I cannot because the playground crashes and turns into an empty page.

But i think we can close this
