### ISSUE TITLE
How to handle error when submitting using external button?

### ISSUE THREAD

**Issue by developersatyajit** [rjsf-team/react-jsonschema-form#1740]
I have a from generated through json schema. The buttons(Save & Cancel) are rendered separately. When saving the form it works perfectly including validation but while cancelling I want to remove the field errors.

**Comment by developersatyajit** [comment]
I am using react formio. Can anybody help me on that?

**Comment by epicfaace** [comment]
@developersatyajit did you mean to create an issue at https://github.com/formio/react-formio? This repository is for another library, react-jsonschema-form.

**Comment by newt10** [comment]
Possibly related to https://github.com/rjsf-team/react-jsonschema-form/issues/2408

**Comment by newt10** [comment]
@epicfaace 👆
