### ISSUE TITLE
Fields lose focus on first entered character

### ISSUE THREAD

**Issue by Fedorov113** [rjsf-team/react-jsonschema-form#1744]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

In playground, in simple example (and all others) when trying to edit field it loses focus after first entered character.

### Steps to Reproduce

1. Open `Simple` example
2. Try to enter something into `Last name`
3. It will lose focus and the focus will be on `First name`

1. Open `Nested` example
2. Try to enter something into `Task list title`
3. It will lose focus

#### Expected behavior

Fields should not lose focus

#### Actual behavior

Fields lose focus
### Version

Current playground. I assume it is `v2.0.0`

**Comment by bwbroersma** [comment]
I just noticed the same thing on `Firefox Nightly 78.0a1 (2020-05-05)`, but not on `Chrome Version 81.0.4044.129 (Official Build) (64-bit)`.

**Comment by bwbroersma** [comment]
The first (Simple) example in the online playground also has an issue on Chrome, the UISchema `"ui:autofocus": true` on `firstName` will set the focus to first name after one keystroke in another field, e.g. last name (also with Live validation disabled).
