### ISSUE TITLE
UISchema ui:placeholder only works for ui:textarea case in material-ui theme

### ISSUE THREAD

**Issue by bwbroersma** [rjsf-team/react-jsonschema-form#1745]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

UISchema [`ui:placeholder`](https://react-jsonschema-form.readthedocs.io/en/latest/form-customization/#placeholders) only works for the `"ui:widget": "ui:textarea"` case in `material-ui` theme.

### Steps to Reproduce

See this simple sample:
JSONSchema
```json
{
  "properties": {
    "field": {
      "type": "string"
    }
  }
}
```
UISchema
```json
{
  "field": {
    "ui:placeholder": "placeholder text"
  }
}
```

There are already two examples in the playground that have `"ui:placeholder"`, namely `Large` and `Nullable`, the last one with `"ui:widget": "ui:textarea"` works for `material-ui`, the Large example with `enum` (Select) does not.

See the playgrounds
* [with material-ui theme](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJwcm9wZXJ0aWVzIjp7ImZpZWxkIjp7InR5cGUiOiJzdHJpbmcifX19LCJ1aVNjaGVtYSI6eyJmaWVsZCI6eyJ1aTpwbGFjZWhvbGRlciI6InBsYWNlaG9sZGVyIHRleHQifX0sInRoZW1lIjoibWF0ZXJpYWwtdWkiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOnRydWUsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)
* [with default theme](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJwcm9wZXJ0aWVzIjp7ImZpZWxkIjp7InR5cGUiOiJzdHJpbmcifX19LCJ1aVNjaGVtYSI6eyJmaWVsZCI6eyJ1aTpwbGFjZWhvbGRlciI6InBsYWNlaG9sZGVyIHRleHQifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

#### Expected behavior

`placeholder="placeholder text"` like in the `default` html output:
```html
<form class="rjsf">
 <div class="form-group field field-undefined">
  <fieldset id="root">
   <div class="form-group field field-string">
    <label class="control-label" for="root">
     field
    </label>
    <input class="form-control" id="root" label="field" placeholder="placeholder text" type="text" value="">
   </div>
  </fieldset>
 </div>
 <div>
  <button type="submit" class="btn btn-info">
   Submit
  </button>
 </div>
</form>
```

#### Actual behavior

No `placeholder="placeholder text"` in the `material-ui` html output:
```html
<form class="rjsf">
 <div class="MuiFormControl-root MuiFormControl-fullWidth">
  <div class="MuiGrid-root jss5 MuiGrid-container MuiGrid-spacing-xs-2">
   <div class="MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12" style="margin-bottom: 10px;">
    <div class="MuiFormControl-root MuiFormControl-fullWidth">
     <div class="MuiFormControl-root MuiFormControl-fullWidth">
      <div class="MuiFormControl-root MuiTextField-root">
       <label class="MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated" data-shrink="false" for="root" id="root-label">
        field
       </label>
       <div class="MuiInputBase-root MuiInput-root MuiInput-underline MuiInputBase-formControl MuiInput-formControl">
        <input aria-invalid="false" id="root" name="" type="string" class="MuiInputBase-input MuiInput-input" value="">
       </div>
      </div>
     </div>
    </div>
   </div>
  </div>
 </div>
 <div>
  <button type="submit" class="btn btn-info">
   Submit
  </button>
 </div>
</form>
```
A [simple code search](https://github.com/rjsf-team/react-jsonschema-form/search?q=placeholder+path:/packages/material-ui/src/&type=Code) shows only one result for `placeholder` in the path `/packages/material-ui/src/` for the `TextareaWidget`. The problem might be not passing the `placeholder` property to the [`@material-ui/core/TextField`](https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/TextField/TextField.js).

Compare the not passing & not working:
https://github.com/rjsf-team/react-jsonschema-form/blob/713844a86d2d3ca084f72547421074df0cd04557/packages/material-ui/src/TextWidget/TextWidget.tsx#L8-L21
To the passing & working:
https://github.com/rjsf-team/react-jsonschema-form/blob/713844a86d2d3ca084f72547421074df0cd04557/packages/material-ui/src/TextareaWidget/TextareaWidget.tsx#L12-L26

### Version

The current [github pages version](https://github.com/rjsf-team/react-jsonschema-form/commit/347637b94c12e8c03833747556dfa979abec3083).

**Comment by bwbroersma** [comment]
Related to #1647

**Comment by stanlemon** [comment]
I believe this has now been addressed with #1789

**Comment by epicfaace** [comment]
@stanlemon any idea why, [in the linked playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJwcm9wZXJ0aWVzIjp7ImZpZWxkIjp7InR5cGUiOiJzdHJpbmcifX19LCJ1aVNjaGVtYSI6eyJmaWVsZCI6eyJ1aTpwbGFjZWhvbGRlciI6InBsYWNlaG9sZGVyIHRleHQifX0sInRoZW1lIjoibWF0ZXJpYWwtdWkiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOnRydWUsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=), it looks like this:

![image](https://user-images.githubusercontent.com/1689183/84096291-92890880-a9cf-11ea-91fb-f2756757c085.png)


and then, when I click, it looks like this?:

![image](https://user-images.githubusercontent.com/1689183/84096305-97e65300-a9cf-11ea-9139-4cdbe5fbb500.png)

**Comment by stanlemon** [comment]
@epicfaace it's because of what Material UI calls the "shrink state", which is when the label (which normally floats over the input) shrinks up to the top. Even with placeholder support, if the shrink state is false (default setting, means it grows/shrinks), when there is no focus on the widget the placeholder is essentially hidden until you bring the input into focus.

It's a weird behavior IMO, but it is the default behavior for Material UI.
