### ISSUE TITLE
Cannot hide title 

### ISSUE THREAD

**Issue by FBurner** [rjsf-team/react-jsonschema-form#1748]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

Title should be nullable. In a complex schema there might be nested values.
But i want to display them without a title / legend yet i seem to have no control over it.

Is there any widget im missing i tried a CustomTitleField yet it has not all required parameters to have control over it in the passed props.

**Comment by epicfaace** [comment]
Did you try `title: ""`?

**Comment by epicfaace** [comment]
You can also do `{"ui:options": {label: false}}` to turn off titles.

**Comment by FBurner** [comment]
Well i started to submit the form and tried 
title: ""

There where some validation errors the sort of items must be an array or something or x must be integer. 

So i postponed the title issue and fixed those validation problems.

Seems the issue where with the invalid structure that didnt result in any error message.

Title: "" now works it seem it.

**Comment by wmgsh** [comment]
Is this possible? I have found a way to hide the widget but not the actual `title`.

**Comment by michal-kurz** [comment]
> {"ui:options": {label: false}}

This unfortunately also hides description, not just title.
