### ISSUE TITLE
Don't return empty divs; return null instead

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#1761]
### Description

Basically, we want to undo the changes in #312 -- we want to return `null` instead of an empty `<div />`. This is because we no longer support such old versions of React.

**Comment by doncesarts** [comment]
I think this was already done by https://github.com/rjsf-team/react-jsonschema-form/commit/b096c999650a732690d34f3cf26d101b33c1a074

**Comment by epicfaace** [comment]
It's still there in some files, see https://github.com/bookmd/react-jsonschema-form/blob/master/src/components/fields/DescriptionField.js

**Comment by epicfaace** [comment]
Sorry, you're right -- I was looking at a different link. Seems to be done, thanks @doncesarts !

**Comment by doncesarts** [comment]
Here the only empty divs that I saw https://github.com/rjsf-team/react-jsonschema-form/pull/1777
The rest are to evaluate something in the unit tests:

Example :
```
          // Empty field template to prove that overides work
          FieldTemplate: () => <div />,
```
