### ISSUE TITLE
Name prop in custom widget for nested properties

### ISSUE THREAD

**Issue by Parro** [rjsf-team/react-jsonschema-form#1763]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

If the schema is an object of fields, in the custom Field component there is a `name` prop (I didn't found it in the doc) that contains the schema property name, while the `id` prop contains 

> The tree of unique ids for every child field

as stated in the docs. 
In the custom Widget component, I found only `id` as a string and no `name` prop, see Codepen https://codepen.io/Parro78/pen/zYvMZVY. `name` is useful because it is the same name used in the formData object. Could we uniform the behavior adding name in both Field and Widget component?

#### Expected behavior

If a field is a child of an object field, `name` is exposed in the props in the Field and Widget components.

#### Actual behavior

If a field is a child of an object field, `name` is present only in Field component and undocumented 

### Version

2.0.1

I made a PR to add the name prop.

**Comment by newt10** [comment]
@Parro can you workaround this by using a custom ObjectField or custom ObjectFieldTemplate?

**Comment by Parro** [comment]
Hi @newt10, I could use a custom `ObjectFieldTemplate` to inject the `name` prop for custom Fields and Widgets, but my PR was intended to correct what I thought was an inconsistency in the documentation (`name` prop already exists in Field but is undocumented). Are there any drawbacks in exposing this prop?
