### ISSUE TITLE
Material UI theme not showing title for date fields

### ISSUE THREAD

**Issue by michalten** [rjsf-team/react-jsonschema-form#1765]
### Prerequisites

- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Titles do not appear for date fields when using the Material UI theme.

### Steps to Reproduce

1. Go to the playground and select the "Simple" schema
2. Add a date field to properties, e.g. "testing": { "type": "string", "format": "date" }
3. Switch to the "material-ui" theme

#### Expected behavior

The title "testing" should appear above the date field.

#### Actual behavior

No title appears above the date field.

### Version

The playground version (but happens to me locally on 2.0.0).

**Comment by stanlemon** [comment]
I think this is resolved with #1789
