### ISSUE TITLE
How to turn off focusable feature for required fields

### ISSUE THREAD

**Issue by hiitskiran** [rjsf-team/react-jsonschema-form#1767]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When we have one or more fields in the form with a list specified in  "required" and if the field is not filled the framework tries to focus the required field which is not field with tool tip "Please fill out this field".  I have a multi level form data capture like in tabbed view so I don't want to stop the user to move on to next step as we already indicate the user on top of the stepper that step is incomplete so indicating the field error inline that it is required is sufficient and we would like to turn off the feature to turn off making the required field focusable, I havent found in documentation how to turn that off, can you please let me  know how to achieve that?

{
  "title": "Custom validation",
  "description": "This form defines custom validation rules checking that the two passwords match.",
  "type": "object",
  "required":["field1"],
  "properties": {
    "field1": {
      "title": "field1",
      "type": "string",
      "minLength": 3
    },
}

**Comment by epicfaace** [comment]
Can you try the `noHtml5Validate ` prop? Related: #1184

**Comment by hiitskiran** [comment]
Yes that fixed the issue, i did try noHtml5Validate=true before but i had other issue which i fixed and removed this to see if this was causing issue, setting it back to true fixed the issue, thanks
