### ISSUE TITLE
Validations showing unnecessary errors when using schema dependencies with oneOf

### ISSUE THREAD

**Issue by hiitskiran** [rjsf-team/react-jsonschema-form#1768]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
I have the schema dependencies like below using oneOf.  When the required field is not filled in it shows 5 error messages instead of one.

[Actual]:
- should be equal to one of the allowed values
- should be equal to one of the allowed values
- is a required property
- is a required property
- should match exactly one schema in oneOf

[Expected]:
- is a required property

{
  "type": "object",
  "properties": {
	"type": {
	  "type": "string",
	  "enum": [
		"A",
		"B"
	  ],
	  "enumNames": [
		"Type A",
		"Type B"
	  ],
	  "readOnly": true,
	  "title": "Choose a Type"
	}
  },
  "dependencies": {
	"type": {
	  "oneOf": [
		{
		  "properties": {
			"type": {
			  "enum": [
				"A"
			  ]
			},
			"details": {
			  "type": "object",
			  "required": ["field1"],
			  "title": "",
			  "properties": {
				"field1": {
				  "type": "string",
				  "title": "Field 1 with label X"
				}
			  }
			}
		  }
		},
		{
		  "properties": {
			"type": {
			  "enum": [
				"B"
			  ]
			},
			"details": {
			  "type": "object",
			  "required": ["field1"],
			  "title": "",
			  "properties": {
				"field1": {
				  "type": "string",
				  "title": "Field 1 with label Y"
				}
			  }
			}
		  }
		}
	  ]
	}
  }
}

**Comment by hiitskiran** [comment]
Here is the live playground link, I have a schema situation with array of objects using conditional fields using oneOf

https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6W3sibW9wRGV0YWlscyI6e30sInR5cGUiOiJYWCJ9XSwic2NoZW1hIjp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InR5cGUiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiWFgiLCJZWSJdLCJlbnVtTmFtZXMiOlsiVHlwZSBBIiwiVHlwZSBCIl0sInRpdGxlIjoiU2VsZWN0IFR5cGUifX0sImRlcGVuZGVuY2llcyI6eyJ0eXBlIjp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7InR5cGUiOnsiZW51bSI6WyJYWCJdfSwibW9wRGV0YWlscyI6eyJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsiZmllbGQxIl0sInRpdGxlIjoiIiwicHJvcGVydGllcyI6eyJmaWVsZDEiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRmllbGQgd2l0aCBsYWJlbCBBIn19fX19LHsicHJvcGVydGllcyI6eyJ0eXBlIjp7ImVudW0iOlsiWVkiXX0sIm1vcERldGFpbHMiOnsidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbImZpZWxkMSJdLCJ0aXRsZSI6IiIsInByb3BlcnRpZXMiOnsiZmllbGQxIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkZpZWxkIHdpdGggbGFiZWwgQiJ9fX19fV19fX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==

**Comment by epicfaace** [comment]
related: #1590

**Comment by hiitskiran** [comment]
Thanks @epicfaace but is there a workaround for my problem?

**Comment by epicfaace** [comment]
Maybe try using `transformErrors`?
