### ISSUE TITLE
Missing files in newest package

### ISSUE THREAD

**Issue by w0nche0l** [rjsf-team/react-jsonschema-form#1771]
### Prerequisites

- [ x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Just downloaded 2.0.1 of @rjsf/core, 
Got this error when trying to add it to my project:

```
[start] ./node_modules/@rjsf/core/dist/es/utils.js
[start] Module not found: Can't resolve './components/fields' in 'C:\Users\wonje\Documents\dennis-games\infinidate\node_modules\@rjsf\core\dist\es'  
```

And if you look, the fields folder is missing in the /dist/es/components folder, even though it is present in the /lib/components folder 
![image](https://user-images.githubusercontent.com/3719829/82743580-3d949380-9d3b-11ea-9f3b-b58af6c4517f.png)

I'm assuming this was just a localized issue to the most recent release?

### Steps to Reproduce

1. Add the package
2. Try to use this package
3. Get error

### Version

2.0.1

**Comment by w0nche0l** [comment]
Yup, just reverted to 2.0.0 and everything worked fine.

**Comment by epicfaace** [comment]
Huh, interesting -- that directory is definitely there in @rjsf/core@2.0.1. Compare https://unpkg.com/@rjsf/core@2.0.1/dist/es/components/fields/index.js and https://unpkg.com/@rjsf/core@2.0.1/dist/es/components/fields/index.js (they're the same). Can you maybe try reinstalling rjsf?

Also, thought I recognized you from CodaLab -- welcome to rjsf 😄
