### ISSUE TITLE
Is there a possible memory leak for the codes below?

### ISSUE THREAD

**Issue by tayay** [rjsf-team/react-jsonschema-form#1772]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

The memory usage (Nodes) seems to continue to grow.
Are there any code issues?
Thanks.

```js
import React, { useState } from "react";
import Form from "@rjsf/core";
import "./styles.css";

const schema = {
  title: "Todo",
  type: "object",
  required: ["title"],
  properties: {
    title: { type: "string", title: "Title" },
  }
};

export default function App() {
  const [open, setOpen] = useState(false);
  const handleClick = () => {
    setOpen(!open);
  };
  const button = <button onClick={handleClick}>toggle</button>;
  const form = open ? <Form schema={schema} /> : null;
  return (
    <div className="App">
      {button}
      {form}
    </div>
  );
}
```

![screenshot](https://user-images.githubusercontent.com/36296084/82828142-62c80400-9eeb-11ea-9fad-5d6b57deac80.png)

### Steps to Reproduce

1. Click the 'toggle' button.
2. Enter any string in the input form.
3. Click the 'toggle' button.
4. Go back to 1 and repeat over and over.

#### Expected behavior

The memory usage (Nodes) does not continue to grow.

#### Actual behavior

The memory usage (Nodes) continues to grow.

### Version

v2.0.1

**Comment by epicfaace** [comment]
Hard to tell if this is due to rjsf or due to other code in your system. Could you try changing this line

`const form = open ? <Form schema={schema} /> : null;`

to this:

`const form = <div style={{display: open ? "block": "none"}}><Form schema={schema} /></div>`

If this code change removes the memory leak, then we know that the problem is due to rjsf.

**Comment by tayay** [comment]
Thank you very much for your advice.
Here is the result of trying with the following code.

```js
import React, { useState } from "react";
import Form from "@rjsf/core";
import "./styles.css";

const schema = {
  title: "Todo",
  type: "object",
  required: ["title"],
  properties: {
    title: { type: "string", title: "Title" }
  }
};

export default function App() {
  const [open, setOpen] = useState(false);
  const handleClick = () => {
    setOpen(!open);
  };
  const button = <button onClick={handleClick}>toggle</button>;
  const form = (
    <div style={{ display: open ? "block" : "none" }}>
      <Form schema={schema} />
    </div>
  );
  return (
    <div className="App">
      {button}
      {form}
    </div>
  );
}
```

![スクリーンショット 2020-06-18 1 26 29](https://user-images.githubusercontent.com/36296084/84923873-c4eae200-b102-11ea-8ff5-ce37084630b1.png)

I'm not sure why Nodes continue to grow, but other objects seem to have removed the memory leak.

**Comment by tayay** [comment]
Isn't the memory leak due to rjsf?

**Comment by epicfaace** [comment]
> I'm not sure why Nodes continue to grow, but other objects seem to have removed the memory leak.

Sorry, does this mean that the memory leak is still happening or not?

**Comment by tayay** [comment]
Thank you for your confirmation.

The `style = {{display: open?" Block ":" none "}}` code has fixed a memory leak of the JS Heap and Listener.
So, I suspect that there is a memory leak of JS Heap and Listener somewhere inside rjsf.

**Comment by ani9450** [comment]
Hey Team, Do we have any workaround for this, as i  am facing the same issue wherein on re-renders i am seeing jump in the memory. 
I have taken two snapshot - 

- snapshot 1 - initial load 
- snapshot 2 - after re-render (component update)

![image](https://github.com/rjsf-team/react-jsonschema-form/assets/55308435/5e68436f-6d35-41a6-be70-1837eb3b1617)

Any suggestions would be highly appreciated !

Thanks
