### ISSUE TITLE
Up-down buttons for anyOf array items not working in Material UI theme

### ISSUE THREAD

**Issue by michalten** [rjsf-team/react-jsonschema-form#1775]
### Prerequisites

- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When using the Material UI theme, the up and down array buttons don't do anything when the items are anyOf objects.

### Steps to Reproduce

1. Go to the playground and select the "Any Of" schema
2. Add items to the array
3. Press the up and down buttons. You'll see that they work as expected
4. Switch to the "material-ui" theme
5. Try using the up and down buttons again

#### Expected behavior

Up and down buttons should move items around.

#### Actual behavior

Up and down buttons do nothing.

### Version

The playground version (but happens to me locally on 2.0.0).

**Comment by stanlemon** [comment]
@michalten can you share your schema? There is a working demo of this in the [playground](https://rjsf-team.github.io/react-jsonschema-form/) that behaves correctly as far as I can tell, so it might be something specific to your schema.

**Comment by michalten** [comment]
@stanlemon I'm using the "Any Of" schema in the playground, without any changes.
Adding a gif to show what I mean
![rjsf_up_down_bug](https://user-images.githubusercontent.com/717615/84260724-cfade180-ab1a-11ea-92a5-0685a0e32a1a.gif)

**Comment by stanlemon** [comment]
Got it, I see it now, thanks @michalten. I’ll try and poke around on this one as I have time this weekend.

**Comment by stanlemon** [comment]
It looks like this issue only occurs when the value field is not filled in.

**Comment by stanlemon** [comment]
This one was tricky and took me awhile, but I think I tracked down the issue and the fix is in #1812
