### ISSUE TITLE
Question: Embedding a 'react jsonschema' form inside another form

### ISSUE THREAD

**Issue by onionhammer** [rjsf-team/react-jsonschema-form#1782]
I've been going over the docs and so far haven't seen an obvious answer here, so I would like to just ask: How do you embed this <Form> into a normal <form> and override simple things like the 'Submit' button?

Obviously you can create a `CustomForm` like in the docs, but the submit button still comes along for the ride.

It would be great to have a way to break down the JSON schema into its component parts rather than having it try to handle **everything**

i.e.

```js
const JsonEditorDemo = () => {
    const schemaForm = useJsonSchema({ schema, formData });

    return <form onSubmit={e => ...schemaForm.data }>
        ... your other custom form fields can go here, or you can use Formik, etc..
        <schemaForm.Editor />
        <button>submit</button>
    </form>
};

```

**Comment by epicfaace** [comment]
You can override the submit button by passing something as a child to the `<Form>` component.

Interesting idea you bring up -- but how do you think it would handle things like validation errors? For example, how would we display validation errors if we had formik embedded within rjsf?

**Comment by onionhammer** [comment]
I tend to use HTML5 validation anyways, even for Formik forms. The way I was thinking of it was more as RJSF inside of Formik, not Formik inside of RJSF.

**Comment by NurdinDev** [comment]
I'm searching for a way to integrate RJSF with my Formik as a nested form, but RJSF uses the Formik submit handler to send values.
In the end, we have a form from Fomaik display some fields from RJSF, Any idea?

@onionhammer did you embedded with Formik?

**Comment by onionhammer** [comment]
@NurdinDev I'm using react-hook-form.

**Comment by rlamorea** [comment]
Trying to do this as well (with Formik).  I think it would be nice to just have the code to validate/retrieve the values out of the form programmatically without doing a `submit`.  Then if my primary form is submitted, I can just programmatically call the JSON form to validate/capture the `formData` and deal with it as I like.

FWIW: I was not able to get programmatic `submit` to work at all (using MUI JSON form and Formik).

**Comment by heath-freenome** [comment]
@rlamorea Programmatic submit was fixed in 5.x. give it a try and let us know

**Comment by nlarusstone** [comment]
For others who get here, you can also use `_internalFormWrapper` and `tagName` to override the outermost component so that you can use everything else within a pre-existing form component.
