### ISSUE TITLE
Custom UI widgets for fields with the OneOf option

### ISSUE THREAD

**Issue by MMrj9** [rjsf-team/react-jsonschema-form#1788]
I'm using react-jsonschema-form v1.8.1.
I didn't find any documentation on how to create UI widgets for fields that have the OneOf Option.
I would like to have my custom dropdown to select the OneOf Option and then a custom DatePicker or a custom Integer field depending on the selected OneOf option.
How can I do this? Thanks

My Schema:
```
  time: {
      $id: "#/definitions/time",
      title: "Time",
      description: "Defines the characteristics of the time",
      oneOf: [
        {
          title: "Datetime",
          type: "string",
          format: "date-time"
        },
        {
          title: "Unix Timestamp",
          type: "integer",
          minimum: 0
        }
      ],
      examples: ["2011-08-12T20:17:46.384Z", 1]
    },
```

**Comment by felippenardi** [comment]
Here it is:
https://github.com/rjsf-team/react-jsonschema-form/blob/53ee91f95df2f5e6b2cbafa7316a0c7dce04ab24/packages/core/test/oneOf_test.js#L128-L156

**Comment by ksbrar** [comment]
bump

**Comment by localhosted** [comment]
I'd also like to know this. I need to apply a widget and ui:order to a property from oneOf

**Comment by duveborg** [comment]
Bump. Still need to find a way to do this

**Comment by nico1996it** [comment]
bump
