### ISSUE TITLE
Focus on first error field while submit (if errors)

### ISSUE THREAD

**Issue by saswat3115** [rjsf-team/react-jsonschema-form#1791]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Focus on the first error field while submit the form (if any errors)

### Steps to Reproduce

1. Submit the form (form should have validations enabled)
2. If any validations failed then error messages are populating besides fields
3. But the focus is still on submit button

#### Expected behavior

The focus should be on first error field.

#### Actual behavior

The focus is still on submit button

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by saswat3115** [comment]
I have the fix. But unable to push the code. access denied.

**Comment by epicfaace** [comment]
@saswat3115 please try making a fork, push to your fork, and then make a PR for this. Thanks!

**Comment by saswat3115** [comment]
Raised PR
