### ISSUE TITLE
Docs site should have a link back to GitHub

### ISSUE THREAD

**Issue by jnachtigall** [rjsf-team/react-jsonschema-form#1799]
It would be great if the docs at https://react-jsonschema-form.readthedocs.io/en/latest/ hat a link back to the GitHub page of the project. As someone using the docs quite heavily I noticed it more than once, that links forth and back are missing.

It imagine a link at the top left or top right header.

**Comment by epicfaace** [comment]
It might be nice to switch the docs site to use the [mkdocs-material](https://squidfunk.github.io/mkdocs-material/getting-started/) theme? This also has a link to the github project show up nicely in the top right corner.

![image](https://user-images.githubusercontent.com/1689183/84662932-7662fb00-aeea-11ea-98bf-af6ee9f732e1.png)
