### ISSUE TITLE
Option missing in @rjsf/material-ui in ui:option

### ISSUE THREAD

**Issue by Mamamouchi** [rjsf-team/react-jsonschema-form#1809]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

In the previous version of the material ui (https://github.com/cybertec-postgresql/rjsf-material-ui) we've got the option addButtonLabel in order to change the title of the button. Unfortunately, this feature disappeared and I would like to know how to change the text of this button ?

Thanks in advance

### Steps to Reproduce

            uiSchema: {
                "ui:options": {
                    "addButtonLabel": "Custom add label"
                }
            },

### Version

2.0.1

**Comment by stanlemon** [comment]
I don't believe this is specific to the Material UI theme. I don't see support for this in code for Bootstrap either.
