### ISSUE TITLE
Ability to set field width when using Material-UI

### ISSUE THREAD

**Issue by Nathan961207** [rjsf-team/react-jsonschema-form#1810]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Ability to override the grid item size when using Material-UI theme so i can display 2 or more fields per row instead of 1.

I have multiple schemas with an unknown amount of fields so it vary from 10 to 30+ fields which is quite bothering to scroll through for an user.

I have read a previous issue https://github.com/rjsf-team/react-jsonschema-form/issues/910#issue-318233190 but it has no solution when using Material-UI.

### Version

"@rjsf/core": "^2.0.1",
"@rjsf/material-ui": "^2.0.1",

**Comment by stanlemon** [comment]
You can do this today by customizing your [`ObjectFieldTemplate`](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/material-ui/src/ObjectFieldTemplate/ObjectFieldTemplate.tsx), which is where the `<Grid />` component from Material UI is used.

**Comment by Spinningbull** [comment]
I have a very similar issue to the OP.  I've been trying to go down the ui:schema approach, but that doesn't seem to be working with MUIForm...  (or more likely, I'm doing it wrong).

I did make a failed attempt at the ObjectFieldTemplate, and couldn't figure out how to get it to set the grid with "MuiGrid-grid-xs-6" - Could someone point at an example with Material-UI?

**Comment by stanlemon** [comment]
Try this (note the second `<Grid />` now has `xs={6}`:

```jsx
import React from 'react';

import Grid from '@material-ui/core/Grid';
import { makeStyles } from '@material-ui/styles';

const useStyles = makeStyles({
  root: {
    marginTop: 10,
  },
});

const ObjectFieldTemplate = ({
  DescriptionField,
  description,
  TitleField,
  title,
  properties,
  required,
  uiSchema,
  idSchema,
}) => {
  const classes = useStyles();

  return (
    <>
      {(uiSchema['ui:title'] || title) && (
        <TitleField
          id={`${idSchema.$id}-title`}
          title={title}
          required={required}
        />
      )}
      {description && (
        <DescriptionField
          id={`${idSchema.$id}-description`}
          description={description}
        />
      )}
      <Grid container={true} spacing={2} className={classes.root}>
        {properties.map((element, index) => (
          <Grid
            item={true}
            xs={6}
            key={index}
            style={{ marginBottom: '10px' }}
          >
            {element.content}
          </Grid>
        ))}
      </Grid>
    </>
  );
};

export default ObjectFieldTemplate;
```

And use it like this:
```jsx
<Form
  schema={schema.schema}
  formData={data}
  onChange={this.onChange}
  onSubmit={this.onSubmit}
  uiSchema={{
    "ui:ObjectFieldTemplate": ObjectFieldTemplate
  }}
/>
```

And it should turn out like this:

<img width="714" alt="Screen Shot 2020-06-19 at 4 02 56 PM" src="https://user-images.githubusercontent.com/86314/85175936-a3930e80-b246-11ea-8fc7-249f1dd70fcb.png">

**Comment by Spinningbull** [comment]
Perfect - that did it!  Thanks.   

Since I have a complex form, I added this for the value of xs...

```
xs={(element.content.props.schema.type === 'object') ? 12: (element.content.props.schema.type === 'boolean') ? 3 : 6}
```

**Comment by Nathan961207** [comment]
It works when you have your fields inside the properties key, my fields are generated from an XML schema and my fields ends up in definitions key.

**Comment by sdwailah** [comment]
> Try this (note the second `<Grid />` now has `xs={6}`:
> 
> ```js
> import React from 'react';
> 
> import Grid from '@material-ui/core/Grid';
> import { makeStyles } from '@material-ui/styles';
> 
> const useStyles = makeStyles({
>   root: {
>     marginTop: 10,
>   },
> });
> 
> const ObjectFieldTemplate = ({
>   DescriptionField,
>   description,
>   TitleField,
>   title,
>   properties,
>   required,
>   uiSchema,
>   idSchema,
> }) => {
>   const classes = useStyles();
> 
>   return (
>     <>
>       {(uiSchema['ui:title'] || title) && (
>         <TitleField
>           id={`${idSchema.$id}-title`}
>           title={title}
>           required={required}
>         />
>       )}
>       {description && (
>         <DescriptionField
>           id={`${idSchema.$id}-description`}
>           description={description}
>         />
>       )}
>       <Grid container={true} spacing={2} className={classes.root}>
>         {properties.map((element, index) => (
>           <Grid
>             item={true}
>             xs={6}
>             key={index}
>             style={{ marginBottom: '10px' }}
>           >
>             {element.content}
>           </Grid>
>         ))}
>       </Grid>
>     </>
>   );
> };
> 
> export default ObjectFieldTemplate;
> ```
> 
> And use it like this:
> 
> ```js
> <Form
>   schema={schema.schema}
>   formData={data}
>   onChange={this.onChange}
>   onSubmit={this.onSubmit}
>   uiSchema={{
>     "ui:ObjectFieldTemplate": ObjectFieldTemplate
>   }}
> />
> ```
> 
> And it should turn out like this:
> 
> <img alt="Screen Shot 2020-06-19 at 4 02 56 PM" width="714" src="https://user-images.githubusercontent.com/86314/85175936-a3930e80-b246-11ea-8fc7-249f1dd70fcb.png">

Thank you very much

**Comment by sdwailah** [comment]
Hello 
I add some improvements so you can add more than 2 columns 

```
import React from 'react';

import Grid from '@material-ui/core/Grid';
import { makeStyles } from '@material-ui/styles';

const useStyles = makeStyles({
  root: {
    marginTop: 10,
  },
});

const ObjectFieldTemplate = ({
  DescriptionField,
  description,
  TitleField,
  title,
  properties,
  required,
  uiSchema,
  idSchema,
  
}) => {
  const classes = useStyles();
  const numberOfColumn = 12 / properties.length;
  return (
    <>
      {(uiSchema['ui:title'] || title) && (
        <TitleField
          id={`${idSchema.$id}-title`}
          title={title}
          required={required}
        />
      )}
      {description && (
        <DescriptionField
          id={`${idSchema.$id}-description`}
          description={description}
        />
      )}
      <Grid container={true} spacing={2} className={classes.root}>
        {properties.map((element, index) => (
          <Grid
            item={true}
            xs={numberOfColumn}
            key={index}
            style={{ marginBottom: '10px' }}
          >
            {element.content}
          </Grid>
        ))}
      </Grid>
    </>
  );
};

export default ObjectFieldTemplate;
```
