### ISSUE TITLE
Modify JSON Validation for Optgroup support

### ISSUE THREAD

**Issue by Enola-guy** [rjsf-team/react-jsonschema-form#1813]
Hello, I've successfully created the widget to support optgroup select (i.e. categories inside a select). I'm now seeking help for the validation. 

In order to generate the categories I give a dict instead of a list to my "enum" field. How can I modify the JSON validation to avoid the error ```.enum should be array```

**Here is the codepen of my implementation:**  
https://codepen.io/enola-guy/pen/ZEQOVEN

If you can explain me the steps missing, I would gladly open a PR in order to make this feature in the main branch :) 

![image](https://user-images.githubusercontent.com/17969523/84604418-425dea80-ae96-11ea-8d58-8cbcd82b03f9.png)

**Comment by epicfaace** [comment]
@Enola-guy thanks for your custom widget! I don't think we can merge this into the main library, though, until we have a JSON Schema-compliant approach (and in JSON Schema, `enum` must be an array, not a dict). Can you think of a JSON-schema-compliant way of using optgroups? For example, this might involve customizing the optgroups in uiSchema using something like this:


```json
{
    "ui:groups": [
         { "title": "Theropods", "items": ["Tyrannosaurus", "Velociraptor"] },
         ...
     ]
}
```

This is just an idea -- let me know if you have any other thoughts / ways of doing this.

**Comment by Enola-guy** [comment]
Thanks for the hint, I'm gonna try this, unfortunately it's not going to be DRY, but that's something. Will update the code today.

**Comment by Enola-guy** [comment]
Hey late update, thank you so much it worked `ui:groups` did the work ! @epicfaace

**Comment by epicfaace** [comment]
Would you be interested in contributing your widget to this library as a PR?

**Comment by Enola-guy** [comment]
I would be very interested !

**Comment by VladislavArkavenko** [comment]
@Enola-guy Can you please share your working code here?

**Comment by nagaozen** [comment]
I made a PR implementing this feature:

![image](https://github.com/user-attachments/assets/156b331f-de99-4dda-ac2f-6ce460f88f0e)

It extends the current SelectWidget to support `optgroups` at `ui:options`. e.g.:

```json
  "selectWidgetOptions3": {
    "ui:options": {
      "optgroups": {
        "lipsum": [
          "foo"
        ],
        "dolorem": [
          "bar"
        ]
      }
    }
  }
```
