### ISSUE TITLE
Can I change the position of the lifting button

### ISSUE THREAD

**Issue by xyy7260** [rjsf-team/react-jsonschema-form#1818]
### Description

Can I change the position of the lifting button

 
#### Expected behavior

I want to put the button on the right on the top

![image](https://user-images.githubusercontent.com/23183393/85006221-6c602700-b18c-11ea-9925-b2982f6d66d1.png)

 

### Version
 "@rjsf/core": "^2.0.2",

**Comment by epicfaace** [comment]
You'd probably need to define your own `ArrayFieldTemplate` to do this.

**Comment by xyy7260** [comment]
@epicfaace  thank you
