### ISSUE TITLE
Contribution Bulma CSS

### ISSUE THREAD

**Issue by mowses** [rjsf-team/react-jsonschema-form#1832]
Hi folks.
I would like to announce my first contribution for the library. Its a theme for Bulma CSS.
Its still in beta, I'm testing it right now. Planning to make a PR soon. It's still missing a SASS for basic theming structure. I'm doing it also.

For those who want to contribute please follow: [https://github.com/mowses/rjsf-bulma-css](https://github.com/mowses/rjsf-bulma-css).
Download, fork, comment.

Thanks.

**Comment by epicfaace** [comment]
Thanks! I think you should just call it @rjsf/bulma instead of @rjsf/bulma-css.

**Comment by enietom** [comment]
Hi @mowses . First of all, awesome job!

I'm running into an issue when I try to integrate your work with the Playground package myself. I guess it's related to the missing SASS configuration you mentioned in your comment.

```Uncaught Error: Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
> @import '../utils.sass'
| @import '~bulma/sass/elements/box.sass'
    at Object.../bulma/node_modules/react-bulma-components/lib/components/box/box.sass (main.js:136706)
    at __webpack_require__ (bootstrap:767)
    at fn (bootstrap:130)
    at Object.../bulma/node_modules/react-bulma-components/lib/components/box/index.js (index.js:10)
    at __webpack_require__ (bootstrap:767)
    at fn (bootstrap:130)
    at Object.../bulma/dist/bulma.cjs.development.js (bulma.cjs.development.js:9)
    at __webpack_require__ (bootstrap:767)
    at fn (bootstrap:130)
    at Object.../bulma/dist/index.js (index.js:7)```

Have you fixed this already? Do you have any tips on how can I address this issue?

**Comment by mowses** [comment]
Hi @enietom 
what command did you run to get this issue? I will try to reproduce in my localhost to try to figure it out.

> Have you fixed this already?

Well, actually I have an app that is consuming the library, in this app I had a similar issue as you mentioned above. Maybe if you follow the steps we can solve it.

Disclaimer: I am not sure if this will help to solve the problem, but we can give a try in the playground. Lets start:

1. add bulma to the dependencies list of your package file. mine is `"bulma": "^0.9.0",` in `package.json`
2. create an `.scss` file somewhere in playground project and add `@import "~react-bulma-components/src/index.sass";` and `@import "~/bulma/bulma.sass";`
3. In the personal project I am using a scss file that handles the minimum structure for the json form. This could be added to the `.scss` file created at step 2: `@import "./JsonEditor.scss";` and in JsonEditor.scss:


```
@charset "utf-8";

.rjsf {

    /**
     * submitting form state
     */
    &.submitting {
        button[type="submit"] {
            @extend .is-loading;
        }
    }

    .card {
        @extend .is-shadowless;

        .card-content {
            padding: 0px;
        }
    }

    /**
     * we hide anything that is outside of the card
     * because some elements were rendered outside of it
     * maybe review where it is rendered in the @rjsf-bulma library
     */
    .field-object {
        & > *:not(.control) {
            display: none;
        }
    }

    /**
     * disabled field template
     */
    .field.disabled {
        @extend .has-text-grey;

        & > .label {
            @extend .has-text-grey;

            &:after {
                @extend .has-text-grey;
            }
        }
    }

    /**
     * main error list and field error list styles
     */
    .error-list-items,
    .error-list-field {
        @extend .is-shadowless, .is-radiusless;
        margin: 0px;
    }

    .error-list-items .notification,
    .error-list-field .notification {
        @extend .is-danger, .is-light, .is-shadowless;
        margin: 0.5em 0em 0.5em 0em ;
        padding: 0.6em;
        list-style: none;
    }

    /**
     * required labels style
     */
    .field-row > .field.required > .label:after {
        content:" *";
        color: $danger;
    }

    /**
     * styles for field rows that contains errors
     */
    .field-row > .field.has-error {
        > .label {
            @extend .has-text-danger;
        }

        > .control > .input,
        > .control > .textarea {
            @extend .is-danger;
        }
    }

    /**
     * there are 2 types of checkboxes, a single checkbox used for the boolean widget
     * and checkboxes for multiple choices
     * also, each checkbox has a label that wraps the element and text
     */
    label.checkbox {
        padding: 5px 20px 5px 5px;

        input {
            margin-right: 0.5em;
        }
    }

    /**
     * for a group of checkboxes
     * block and inline styles
     */
    .checkboxes {
        label.checkbox {
            &.checkbox-block {
                display: table;
            }
            &.checkbox-inline {
                display: inline;
            }
        }
    }

    /**
     * we add a border for each grouped class elements
     * the selector .is-grouped can be changed to another name
     */
    .is-grouped {
        @extend .is-shadowless, .box;
        border: 1px solid $border;
    }

    /**
     * children elements of form, generaly its a submit button
     */
    .submit-button {
        @extend .is-link;
    }
}
```

I think that is it.
The error that gave to you is probably because of stylesheets not found when you tried to build the project.
After you import the bulma css theme it should stop.

**Comment by enietom** [comment]
I was able to fix the build issue by adding `modules: ['node_modules', 'src']` to the `resolve` field in `webpack.config.dev.js` file and also adding `path.join(__dirname, "..", "bulma", "node_modules", "react-bulma-components"),` as a path in the Sass loader rules of the same file.

A fork of the rjsf repo with the Bulma package can be found at https://github.com/enietom/react-jsonschema-form . It still needs some styles fixes (haven't added your `JsonEditor.scss` file yet) and also I noticed fontawesome icons are not being displayed. But at least the playground works.

**Comment by mowses** [comment]
Good job @enietom 
I have fixed the font awesome icons. You can git pull the changes. Also, make sure to add `<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>` to your index.html

also, add the following in the `JsonEditor.scss` inside `.rjsf` block:

```
    /**
     * icon spacing
     */
    .array-item-add.button .icon {
        margin-right: 0em;
    }
```
