### ISSUE TITLE
Can't add description to array with additional items and items defined

### ISSUE THREAD

**Issue by mkkeffeler** [rjsf-team/react-jsonschema-form#1871]
### Prerequisites

- [x ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Heres the schema that is working right now
```
requiredAttributes": {
                "type": "array",
                "title": "LDAP Attributes",
                "examples": [
                    
                        "azjobcode",
                        "cn",
                        "departmentnumber",
                        "givenname",
                        "mail",
                        "passwordexpirationtime",
                        "sn"
                    
                ],
                
                "items": [
                    {
                        "title": "Required UID",
                        "type": "string",
                        "description": "The required attribute that comes with all agent configurations",
                        "default": "uid",
                        "readOnly": true
                    }
                ],
                "additionalItems": {
                    "type": "string",
                    "title": "Choose the attribute you need access to",
                    "description": "list is prepopulated.",
                    "enum": [
                        "cn",
                        "givenname",
                        "mail",
                        "sn"
                    ]
                }
            }
```
when I add "description" right below title (anywhere, but just as an example) fails to render with 

```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ArrayFieldDescription`.
```

### Steps to Reproduce

Add this example to your schema without description to show success case, then add description to show failure
#### Expected behavior

render description

#### Actual behavior

crashes
### Version

    "@rjsf/material-ui": "^2.0.1",

**Comment by mkkeffeler** [comment]
reproduced the same issue after upgrading to 2.1.0 as well, just to confirm this wasn't patched

**Comment by rnagy90** [comment]
Same here. 
It doesn't matter the `additional` is defined or not, neither the shema's depth. It seems like the `ArrayFieldDescriptionProps` props doesn't contain the `DescriptionField` component reference.

You can also reproduce this bug on the playground by adding description to an array type section and change the theme to the material ui
