### ISSUE TITLE
Antd Theme date-time has problems.

### ISSUE THREAD

**Issue by bear-c** [rjsf-team/react-jsonschema-form#1880]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

The antd theme has some minor problems.
When I use the date component. Selecting the value will cause an error. The form crashed directly

### Steps to Reproduce

1. Open the playground. https://rjsf-team.github.io/react-jsonschema-form/
2. select antd theme and  Data & time
3. select a time.

#### Expected behavior

I hope the value like 2020-06-13T04:39:00.000Z

#### Actual behavior

The form crashed directly

### Tips

Antd used the moment.js . So this value is moment object.You need to use it to convert values
![image](https://user-images.githubusercontent.com/38900476/86077415-82d87d80-babe-11ea-9947-4f183e9913ad.png)

**Comment by z5980000** [comment]
face the same issue too, any workaround?

**Comment by CaldeDaniele** [comment]
Same issue here

**Comment by MacroBet** [comment]
Could you please make a version with this fix?
