### ISSUE TITLE
How to use classNames field level

### ISSUE THREAD

**Issue by hiitskiran** [rjsf-team/react-jsonschema-form#1886]
I followed the documentation https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/uiSchema/#classnames to use field styling by setting classNames: "task-title foo-bar" in the uiSchema  the class is not getting applied to the field.  I dont see the class being applied to the field, we are using material UI theme.

**Comment by hiitskiran** [comment]
If providing field level classNames is not yet supported for material UI, is there a work around until support is avaialble?

**Comment by epicfaace** [comment]
You could create custom fields.

**Comment by hiitskiran** [comment]
I was looking at https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/#custom-field-components

Are the custom widgets and fields supported with material-ui Form?

**Comment by epicfaace** [comment]
Yes, they are.

**Comment by hiitskiran** [comment]
Thanks @epicfaace  but for some reason I keep getting the below compile error when I try to create simple custom checkbox field:

TS2322: Type 'typeof CustomCheckbox' is not assignable to type 'Field'.
  Type 'typeof CustomCheckbox' is not assignable to type 'ComponentClass<FieldProps<any>, any>'.
    Type 'CustomCheckbox' is missing the following properties from type 'Component<FieldProps<any>, any, any>': context, setState, forceUpdate, props, and 2 more.

Not sure if there are version restrictions for custom widgets and fields but I am using these versions:

"react-jsonschema-form": "^1.8.1"
 "@rjsf/core": "2.0.0",
  "@rjsf/material-ui": "2.0.0"


Thanks very much for you help!

**Comment by hiitskiran** [comment]
I got the custom field working.. thanks for you help.
