### ISSUE TITLE
Fix broken codepen examples on the documentation

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#1887]
### Description

Some of the new interactive codepen examples on the documentation show up as a blank screen -- likely they are failing due to a minor syntax error. We need to fix all of these.

For example (on https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/):

![image](https://user-images.githubusercontent.com/1689183/86182630-55abbf80-bafe-11ea-9359-5ecdf42cd54f.png)

**Comment by eslachance** [comment]
Considering I get these warnings in console I'm guessing the issue is a bit bigger than this particular code block.
![image](https://user-images.githubusercontent.com/643344/86398880-52d2db00-bc74-11ea-9a83-9d0557df3dc3.png)

**Comment by jrasanen** [comment]
None of the code examples work on the latest Safari or Firefox. CodePen returns a 503 error for them,

<img width="830" alt="" src="https://user-images.githubusercontent.com/13303/154003596-50e5dbb9-3d6d-4b8b-bf22-b9ce207ddc97.png">
