### ISSUE TITLE
row column not in initial formdata has a default but is not being populate

### ISSUE THREAD

**Issue by mrehder** [rjsf-team/react-jsonschema-form#1892]
### Prerequisites

- [x ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Question:
If there is initial formdata supplied and there are "default" statements in the jsonschema, how does the form resolve this?
Does it apply defaults at all?
If so, how does it "merge" the defaults and the initial form data together?
In particular, if there is an array row provided and some of the keys in the items object have "default" JSONSchema statements, will the form fill in the default value if the array row/column is not provided?

It looks like for an initial row, default values are not populated if the key isn't present in the initial row data.

I couldn't find this level of detail in the documentation about support for "default".

### Steps to Reproduce

Supply formdata with a row in an array of objects.
A key (column) in that array object isn't present in this initial data.
The key has a "default" declaration in the jsonschema.
The form appears with the initial data but there is no value populated for the absent column in the row.

#### Expected behavior

Form will merge together the defaults and initial data, with the initial data taking precedence.

#### Actual behavior

The form appears with the initial data but there is no value populated for the absent column in the row.

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by epicfaace** [comment]
@mrehder , See [Handling of schema defaults](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/internals/#handling-of-schema-defaults) for an in-depth discussion on how defaults are currently handled.

**Comment by mrehder** [comment]
thanks for the pointer to that documentation. I also checked this out in the playground and it is clear.

One other question about defaults.
It seems that the form will generate an empty top-level array or object "container" automatically. 
Is there a way to prevent this from happening?
This causes a problem if the object has required items within or an array as minitems - it then fails validation because only a shell was created.

Example in the playground:
"Nested".
Erase all data.
Enter data for key "title".
This is the resulting form data
{
  "tasks": [],
  "title": "hh"
}
Why is an empty "tasks" array created?

"Widgets".
Erase the data for the "boolean" block.
Enter data for the key "X".
This is injected into the form data
      "boolean":{} 
is created - why is this empty object created?

**Comment by epicfaace** [comment]
> It seems that the form will generate an empty top-level array or object "container" automatically.
> Is there a way to prevent this from happening?

I don't think there's a way to stop this from happening, with the current behavior of rjsf.

> This causes a problem if the object has required items within or an array as minitems - it then fails validation because only a shell was created.

Can you explain a bit more about what this issue is? Such as a schema example

**Comment by mrehder** [comment]
specific example to reproduce:

in "Nested", add this to the "tasks" array:
      "minItems": 1,
Then remove the rows of this array.
Validation error reports at least one row is required for "tasks"


in "Widgets", add this to the "boolean" object:
 "required": ["default"],
Then remove the data for "boolean", type something into the form.
"boolean":{} is created
Validation error occurs because "default" is required but missing.

In both cases, the object/array is not required in its parent context but because the form generates their presence, their own internal content constraints now apply. This constraint violation would be very confusing to the user.

**Comment by mrehder** [comment]
Actually I think I'd consider the behavior to be a defect, as it prevents certain JSON Schema constructs from being used.

**Comment by mrehder** [comment]
I revise my comment - I realize that inserting the optional empty container or array is necessary for the form's behavior. This is how such an object appears in the JSON dataset. The alternative is to have a widget of some sort on the form by which the user inserts or removes such an optional object/array.
This does constrain the jsonschema one can use (one can't use optional object/array which has required top-level content since effectively the form makes it non-optional).
