### ISSUE TITLE
Root: Should be object error for programatic form submission

### ISSUE THREAD

**Issue by paintedbicycle** [rjsf-team/react-jsonschema-form#1896]
### Prerequisites

- [x ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

There is a validation error that happens in newer versions of the form (I downgraded to 1.8.1 and it went away). I *believe* it has something to do with submitting the form programatically, as I have 20+ forms that are working and my one programatic form broke.

I'm working on getting a reproduction

### Steps to Reproduce

1. Use ref
2. Submit form

#### Expected behavior

Form submission as normal

#### Actual behavior

- Validation function finds no errors
- Submit function never fires
- Validation error message (Regardless of form schema: `root: Should be object`

### Version

2.2.0

**Comment by paintedbicycle** [comment]
I tracked this down:

Before version 2 or so, it was ok for your `formData` to be an empty string, now it appears, the form will not submit if it is. So, instead of passing an empty string as formData, I now do an extra check and pass it undefined or an empty object

**Comment by aripo99** [comment]
What was the solution to this? I'm seeing the same behavior where I get the `Must be object` error unless the user changes the form directly, even when `form_data` is not empty/undefined. It requires me to change the form directly to send it. `form_data` looks good as an object so not sure why the validator is rejecting it?
