### ISSUE TITLE
Link to semantic-ui-specific documentation in docs

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#1897]
### Description

Part of #1888.

Right now, we have some specific docs for @rjsf/semantic-ui in https://github.com/rjsf-team/react-jsonschema-form/blob/master/docs/themes/semantic-ui/uiSchema.md, but it's not accessible at https://react-jsonschema-form.readthedocs.io/en/latest/. We should link to this page from the table of contents by adding an entry in mkdocs.yml.

**Comment by jacqueswho** [comment]
@epicfaace I have updated the docs. Also fix the docs where links don't exist
