### ISSUE TITLE
Custom widget support for object type 

### ISSUE THREAD

**Issue by SivaGanesh56** [rjsf-team/react-jsonschema-form#1902]
### Prerequisites

- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description
Right now for custom widget type  there is support for basic JSON types like boolean,number,string,integer,array. but for my case i need support for object type also. reason is i am developing a custom widget where formData is an object. Inorder to submit/onChange it should accept object type. 

### Steps to Reproduce

I tired to add object type and maps widgets to it

#### Expected behavior

works as  like other widgets

#### Actual behavior

widget was not showing without an error

**Comment by epicfaace** [comment]
You should use ObjectFieldTemplate for this -- see https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-templates/. Widgets cannot be used for object fields.
