### ISSUE TITLE
[Validation] Email type is not validated correctly

### ISSUE THREAD

**Issue by nhatthanh510** [rjsf-team/react-jsonschema-form#1918]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Field with format = "email" is not validated correctly

I have the jsfiddle link https://jsfiddle.net/thanhbcvt/ea46bk0s/

### Steps to Reproduce

1. Type an invalid email address such as : "test@gmail"
2. Just leave the input or click submit
3. No error happens

#### Expected behavior

Error message related to wrong email format should happen

#### Actual behavior

Nothing happens and form is valid

### Version

1.8.1

**Comment by mdornseif** [comment]
I think there are different Expectations, what should be considered a Valid E-Mail Adress. Generally much more things e.g. spaces) are valid within E-Mail Protocols (SMTP et al.). `test@gmail` is for sure a valid E-Mail adress within the SMTP standard. I know people with E-Mail Adresses directly under TLDs are also valid E-Mail adresses. E.g. `hostmaster@google` [certainly is](https://en.wikipedia.org/wiki/.google).

Web developers are much more interested in the  **deliverability** of E-Mail adresses. Can I send Mail to this Address?This is a very hard problem. You would have to test the host (right) part against DNS. But you can not thest against the DNS view your mailserver would have (often seeing company-internal domains, aliases and special routing) but only the view of the browser where rjsf probably is running. 

Even if you CAN validate the host part it is even harder to validate the local (left) part. Basically you would have to try to deliver an E-Mail there. 

So let's stick with formal validation if an E-Mail adress is valid within SMTP. I thing rjsf is already overly restrictive there.

**Comment by nhatthanh510** [comment]
Thanks for well explanation @mdornseif
