### ISSUE TITLE
additionalProperties can't be added with semantic-ui fluent-ui themes

### ISSUE THREAD

**Issue by ErQrYfkrju** [rjsf-team/react-jsonschema-form#1927]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

additionalProperties can`t be added with semantic-ui fluent-ui and material-ui themes

### Steps to Reproduce

1. Goto https://rjsf-team.github.io/react-jsonschema-form/
2. Select additionalProperties example
3. Select theme material-ui, semantic-ui, fluent-ui

#### Expected behavior

Expected behavior should be as for default and antd themes
![Screen Shot 2020-07-22 at 15 31 12](https://user-images.githubusercontent.com/65288684/88176740-67c9db00-cc30-11ea-82ef-9cdb9ced2b95.png)

#### Actual behavior

Can`t add or remove additioanlProperties for selected object
![Screen Shot 2020-07-22 at 15 31 41](https://user-images.githubusercontent.com/65288684/88176778-7617f700-cc30-11ea-9a6a-1ce2d470db4b.png)

### Version

Latest version from npm

**Comment by bretep** [comment]
Just about to report the same issue, although I found it after upgrading to the latest.

**Comment by ValYouW** [comment]
Encountered into this also just now... any simple workaround?
I made a simple implementation of this feature by overriding `ObjectFieldTemplate` and `FieldTemplate` it seems to work on a very simple scenario, it's on [CodeSandbox](https://codesandbox.io/s/react-jsonschema-form-67qn4) if anyone is interested...

**Comment by ErQrYfkrju** [comment]
any news?

**Comment by ErQrYfkrju** [comment]
@jacqueswho any news on senantic-ui?

**Comment by jacqueswho** [comment]
@ErQrYfkrju at the moment none of the themes support this feature. This is not a simple change and needs to be thought of how to integrate different themes to support this. One linear approach that all themes can use to support this feature

**Comment by ErQrYfkrju** [comment]
Why none? Default, antd and now material-ui supports it.

**Comment by jacqueswho** [comment]
will look into this then. As I have not seen the latest development with other themes

**Comment by ErQrYfkrju** [comment]
@jacqueswho any news?

**Comment by jacqueswho** [comment]
@ErQrYfkrju waiting for this [pull request](https://github.com/rjsf-team/react-jsonschema-form/pull/1972) to be approved. Will then look at implementing this. I have made quite a lot of code changes in this branch. I see I need to alter the Field Template to wrapAdditional

**Comment by jacqueswho** [comment]
@epicfaace There are going to be quite a few issues related to other themes not supporting the default behavior. I think we need to create a contributing guide doc, to assist others in the future. So we should either include utilities in the core and use them, or give some best practice guidance, direction. what do you think? we can create separate tasks for each to document how, and what to use to implement
The following are not quite clear

- Additional Properties

- theme specific props

- Date picker

- hidden fields

- Submit Button

**Comment by ErQrYfkrju** [comment]
@jacqueswho @epicfaace thanks for your work. Looking forward to see this feature implemented.....

**Comment by ErQrYfkrju** [comment]
@epicfaace ping

**Comment by epicfaace** [comment]
> @epicfaace There are going to be quite a few issues related to other themes not supporting the default behavior. I think we need to create a contributing guide doc, to assist others in the future. So we should either include utilities in the core and use them, or give some best practice guidance, direction. what do you think? we can create separate tasks for each to document how, and what to use to implement
> The following are not quite clear
> 
> * Additional Properties
> * theme specific props
> * Date picker
> * hidden fields
> * Submit Button

Yeah, that's a good point and a good idea. A separate "contributing guide" page might be helpful.

**Comment by ErQrYfkrju** [comment]
@epicfaace  @jacqueswho  Happy New Year!
Any news on this issue...?

**Comment by ErQrYfkrju** [comment]
@epicfaace ping

**Comment by jacqueswho** [comment]
> @epicfaace @jacqueswho Happy New Year!
> Any news on this issue...?

Waiting for the pull request to be approved. sorry

**Comment by epicfaace** [comment]
Sorry, I'll take a look soon.

**Comment by abeMedia** [comment]
Same for Bootstrap 4. It doesn't support `additionalProperties`.

**Comment by jmcauhy** [comment]
Hello guys, any updates on the Semantic-ui theme?

**Comment by epicfaace** [comment]
No one's working on it currently, so if you would like to contribute a PR, that would be welcome.

**Comment by ErQrYfkrju** [comment]
> No one's working on it currently, so if you would like to contribute a PR, that would be welcome.

Why no one? @jacqueswho is working on three pull requests [#224](https://github.com/rjsf-team/react-jsonschema-form/pull/2224), [#2225](https://github.com/rjsf-team/react-jsonschema-form/pull/2225), [#2227](https://github.com/rjsf-team/react-jsonschema-form/pull/2227) to be able to close this issue...

**Comment by ErQrYfkrju** [comment]
@epicfaace please review following PR. I know you are very busy, but soon it would be one year anniversary for this issue. Thanks in advance!

**Comment by ErQrYfkrju** [comment]
Hi, once #2224, #2225, #2227 are already merged in could this issue be resolved?

**Comment by ErQrYfkrju** [comment]
@jacqueswho ping

**Comment by jacqueswho** [comment]
@epicfaace ill see if I have time this week

**Comment by ErQrYfkrju** [comment]
@jacqueswho ping

**Comment by ErQrYfkrju** [comment]
@jacqueswho is there any possibility to get this working using custom patch or dirty hacks?

**Comment by jacqueswho** [comment]
@ErQrYfkrju just got back from holiday. Will see if I can look at this next week. I have a branch for this that needs to be completed. Its just needs styling, positioning changes
