### ISSUE TITLE
Make Version with Data fix 

### ISSUE THREAD

**Issue by MacroBet** [rjsf-team/react-jsonschema-form#1936]
I saw you fixed the data issue, could you please version it?

https://github.com/rjsf-team/react-jsonschema-form/pull/1900

**Comment by CaldeDaniele** [comment]
+1

**Comment by epicfaace** [comment]
v2.2.2 has now been released.

By the way, if you depend on react-jsonschema-form and are interested in helping sustain its development, consider either helping out with triaging issues / reviewing PRs (see #1757) or sponsor [developers who are working on it](https://github.com/rjsf-team/react-jsonschema-form/graphs/contributors). Appreciate it!
