### ISSUE TITLE
semantic-ui: Title is absent for string property with enum values

### ISSUE THREAD

**Issue by ErQrYfkrju** [rjsf-team/react-jsonschema-form#1937]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
Title Label is absent for string property with enum values 

### Steps to Reproduce

1. Go to https://rjsf-team.github.io/react-jsonschema-form/
2. Select semantic-ui theme
3. Use following scheme 
{
  "title": "A registration form",
  "description": "A simple form example.",
  "type": "object",
  "required": [
    "gender"    
  ],
  "properties": {
    "gender": {
      "type": "string",
      "title": "Gender",
      "default": "Male",
      "enum":["male","female"]
    }}
}

#### Expected behavior
Title is shown
![Screen Shot 2020-07-22 at 15 21 15](https://user-images.githubusercontent.com/65288684/88175903-2ab11900-cc2f-11ea-81de-7d6307067d2f.png)

#### Actual behavior
Title is not shown
![Screen Shot 2020-07-22 at 15 21 03](https://user-images.githubusercontent.com/65288684/88175861-1ec55700-cc2f-11ea-86a9-b1b56cd51ecd.png)

**Comment by jacqueswho** [comment]
@ErQrYfkrju can this issue be closed? I just tried to reproduce and I think its fixed

**Comment by epicfaace** [comment]
If it's fixed, let's go ahead and close it, @ErQrYfkrju can let us know if it comes up again and reopen in that case.
