### ISSUE TITLE
ArrayField.js throwing error when nextFormData is null

### ISSUE THREAD

**Issue by mowses** [rjsf-team/react-jsonschema-form#1941]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

ArrayField.js is giving error due to a null nextFormData value:

at line ~230 of file: `packages/core/src/components/fields/ArrayField.js`
there this check: `nextFormData.length`. it will give error since `nextFormData` is null

#### Actual behavior

throws error in console and make browser screen white

I fixed the code. please see:
https://github.com/mowses/react-jsonschema-form/blob/master/packages/core/src/components/fields/ArrayField.js
now I would like to use the corrected version in my project or make a PR

**Comment by mowses** [comment]
I see there is an open PR for this at: https://github.com/rjsf-team/react-jsonschema-form/pull/1553

**Comment by richmahn** [comment]
@mowses should this be closed if the PR isn't merged in yet? Now the PR has conflicts.
