### ISSUE TITLE
Updating the UiSchema through form onChange function deletes formData

### ISSUE THREAD

**Issue by grgicpetar** [rjsf-team/react-jsonschema-form#1942]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Updating the UiSchema through form onChange function deletes formData

### Steps to Reproduce

1. Programatically update the field in uiSchema
2. Update uiSchema state variable

```
const onChangeHandler = (props: any) => {
    console.log(props);
    if (props.formData["izradiola"]) {
      props.uiSchema["kontroliraola"]["ui:options"].disabledOption = props.formData["izradiola"];
      setUiFormSchema(props.uiSchema);
    }
  };
```

#### Expected behavior

I expect the uiSchema to be populated with new value from the onChangeHandler method and formData to stay the same. 

#### Actual behavior

The uiSchema is properly updated after the condition is met, but formData object resets after that. All fields become empty.

### Version

@rjsf/core": "^2.2.1

**Comment by 5arg** [comment]
Just a quick remark, the problem I am actually trying to solve is how to access a value from one field in another through custom widget props.

**Comment by RoboPhred** [comment]
Modifying props directly like that is playing with fire.  A core tenant of react is to [not mutate state](https://www.freecodecamp.org/news/handling-state-in-react-four-immutable-approaches-to-consider-d1f5c00249d5/#:~:text=React%20state%20should%20be%20treated,replace%20the%20mutation%20you%20made.).  And the 'props' variable you have is actually the [raw state](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/Form.js#L51) of the form.

If you modify a property, you need to make new references all the way down.  the lodash/fp set function is particularly useful for this.
```
import { set } from "lodash/fp";

var newUiSchema = set(["kontroliraola", "ui:options", "disabledOption"], props.formData["izradiola"], props.uiSchema);
setUiFormSchema(newUiSchema);
```

We also encountered the need to have widgets be aware of the global form data and not their local data.  We pulled it off using [react context objects](https://reactjs.org/docs/context.html) to create a context containing the formData, which can then be called upon in the particular widget that wants to access the value.

Here is an example of using context to expose the form data for all widgets:
https://codesandbox.io/s/react-example-forked-7pmzz?file=/index.js
