### ISSUE TITLE
When using the Semantic UI theme, labels disappear when specifying format or enum

### ISSUE THREAD

**Issue by GeekLad** [rjsf-team/react-jsonschema-form#1946]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When specifying a format, the field labels are not displayed

### Steps to Reproduce

1. ```import Form from "@rjsf/semantic-ui";```
2. Create a JSONSchema that specifies formats (such as email and date)
```
const schema = {
  title: "Label Bug Demo",
  type: "object",
  required: ["name", "originalContractAmount", "applicationDate", "periodTo"],
  properties: {
    email: {
      type: "string",
      title: "Email",
      format: "email"
    },
    birthday: {
      type: "string",
      title: "Birthday",
      format: "date"
    }
  }
};
```
3. Render the form
```
<Form schema={schema} />
```

See https://codesandbox.io/s/react-jsonschema-form-demo-grtcz?file=/src/App.tsx for a live example

#### Expected behavior

Expect to see the form render with labels containing the specified titles.

#### Actual behavior

The fields render without any labels.

![Screen Shot 2020-07-23 at 10 05 06 PM](https://user-images.githubusercontent.com/143769/88354949-a5159200-cd30-11ea-965e-bab0c9e60811.png)

### Version

    "@rjsf/core": "^2.2.1",
    "@rjsf/semantic-ui": "^2.2.1",

**Comment by mvershinin-chwy** [comment]
Same issue

**Comment by GeekLad** [comment]
The label also seems to disappear when using an `enum`.  There may be other conditions that also cause it to disappear.

**Comment by GeekLad** [comment]
I came up with a simple work around with this field template (in TypeScript): 

```typescript
import React from 'react';
import { FieldTemplateProps } from '@rjsf/core';
import { Form } from 'semantic-ui-react';

export const FieldTemplate: React.FC<FieldTemplateProps> = (props: FieldTemplateProps) => {
  // Return with the label, if it's in a situation where it would be missing
  if (
    props.schema.format
    || props.schema.enum
  ) {
    return (
      <Form.Field required={props.required}>
        <label>{props.schema.title}</label>
        {props.children}
      </Form.Field>
    );
  }

  // Return the field as-is in other situations
  return props.children;
};
```

**Comment by epicfaace** [comment]
@jacqueswho do you think you'd be able to take a look at this?

**Comment by jacqueswho** [comment]
> @jacqueswho do you think you'd be able to take a look at this?

Sure. I'll take a look

**Comment by jjarcik** [comment]
still does not work in **v2.5.1**... 😪

**Comment by jacqueswho** [comment]
@jjarcik pull request has not been merged in ? [2225](https://github.com/rjsf-team/react-jsonschema-form/pull/2225)

**Comment by jjarcik** [comment]
> @jjarcik pull request has not been merged in ? [2225](https://github.com/rjsf-team/react-jsonschema-form/pull/2225)

probably not, or the title was not fixed. GeekLad's work around works, but....
