### ISSUE TITLE
Nullable array crash the form

### ISSUE THREAD

**Issue by kikonejacob** [rjsf-team/react-jsonschema-form#1957]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
The following schema crash the app when value=null
```json
{
      
      "type": ["array", "null"]
}
```

![image](https://user-images.githubusercontent.com/3852574/89074605-3f359580-d342-11ea-95d9-29669193400b.png)

[Description of the bug or feature]

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Version
v 2.2.2

**Comment by epicfaace** [comment]
Fixed by https://github.com/rjsf-team/react-jsonschema-form/pull/2154.
