### ISSUE TITLE
Bootstrap 4 theme - add additional properties support

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#1962]
From #1938.

Need additional properties support for this theme.

![image](https://user-images.githubusercontent.com/1689183/88480748-d30ff780-cf25-11ea-9da8-94d9e7f751ac.png)

**Comment by atsetilam** [comment]
Any news on this issue? 😀

**Comment by staboness** [comment]
Bump

**Comment by heath-freenome** [comment]
This appears to have been fixed with #2429
