### ISSUE TITLE
Losing focus when I use a custom fieldTemplate

### ISSUE THREAD

**Issue by roievil** [rjsf-team/react-jsonschema-form#1969]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

[Firstly thank you for this awesome library !

I am trying to use a fieldtemplate to add html markup and change the layout of each field of the form to easily style it, set the length of the slider etc.. When I add my field template to the parameters of the form, and I try to use a slider or any input, I lose the focus almost instantly  (I think this is because the form is re rendered but that the modified form data does not succeed in populating the form). It is a behaviour I am not having without the fieldtemplate. What I am missing in my fieldtemplate?I am using rjsf inside a react redux component this is why I did not provide a JSFiddle sample]

here are extracts of the component : 

```
function CustomFieldTemplate(props: any) {
    const {
      id,
      classNames,
      label,
      help,
      required,
      description,
      errors,
      children,
    } = props;
    return (
      <div className={classNames}>
        <label htmlFor={id}>
          {label}
          {required ? '*' : null}
        </label>
        {description}
        {children}
        {errors}
        {help}
      </div>
    );
  }
```
```
    <Form
        onSubmit={onSubmit}
        schema={schema.dataSchema}
        uiSchema={schema.uiSchema}
        formData={configuration.confData}
        onChange={handleOnChange}
        widgets={widgets}
        FieldTemplate={CustomFieldTemplate}
      >
```

here is are the json schema and ui schema

```
    const dataSchema = {
      title: '',
      type: 'object',
      properties: {
        group1: {
          title: 'group1',
          type: 'object',
          properties: {
            S1: {
              title: 'Height (mm)',
              type: 'number',
              minimum: 100,
              maximum: 1000,
              multipleOf: 10,
            },
            S2: {
              title: 'Position middle 2 diameter',
              type: 'number',
              minimum: 2.5,
              maximum: 3.8,
              multipleOf: 0.1,
            },
            Toggle: {
              type: 'boolean',
            },
          },
        },

        group2: {
          title: 'group2',
          type: 'object',
          required: ['T1'],
          properties: {
            T1: {
              title: 'inputField',
              type: 'string',
              default: 'inputField',
            },
          },
        },
      },
    };

    const uiSchema = {
      group1: {
        classNames: '',
        S1: {
          'ui:widget': 'range',
        },
        S2: {
          'ui:widget': 'range',
        },
         toggle: {
          'ui:widget': 'checkbox',
        },
      },
      group2: {
        classNames: '',
        T1: {
          'ui:emptyValue': '',
        },
      },
    };
```

and I also attached the whole tsx component in a zip file
[DynamicForm.zip](https://github.com/rjsf-team/react-jsonschema-form/files/5023076/DynamicForm.zip)

I am building an dynamic form controlling a 3D object hence the collection of sliders.

Thank you for your help,
Olivier

### Steps to Reproduce

1. [Click and drag the handle of the slider]

#### Expected behavior

[handle slides]

#### Actual behavior

[focus is lost]

### Version

   "@jsonforms/core": "^2.4.0",
    "@jsonforms/react": "^2.3.2",
    "@rjsf/core": "^2.1.0",

**Comment by xyy7260** [comment]
I think it's not the fieldtemplate, but the onchange monitoring change of the form

**Comment by NaccOll** [comment]
I have a same problem. input will lose focus when using custom field template and entering first character

**Comment by NaccOll** [comment]
```js
import React from 'react'
import { Form } from 'antd'
import { withTheme } from '@rjsf/core'
import { Theme as AntDTheme } from '@rjsf/antd'
const JsonForm = withTheme(AntDTheme)
class Test extends React.Component {
  componentDidMount() {
    this.init()
  }

  init = () => {
    new Promise((resolve, reject) => {
      resolve(10)
    }).then((data) => {
      this.setState({ a: data })
    })
  }
  render() {
    return (
      <JsonForm
        className='ant-form ant-form-inline'
        ObjectFieldTemplate={(props) => {
          return (
            <div className='ant-form ant-form-inline'>
              {props.properties.map((element) => element.content)}
            </div>
          )
        }}
        FieldTemplate={(props) => {
          const { label, required, children } = props
          return (
            <Form.Item label={label} required={required}>
              {children}
            </Form.Item>
          )
        }}
        schema={{
          type: 'object',
          properties: {
            firstName: { type: 'string', title: 'First Name' },
            lastName: { type: 'string', title: 'Last Name' }
          }
        }}
      />
    )
  }
}

export default Test
```

**Comment by roievil** [comment]
Hum, I am sorry I cannot help you I did not find what I was doing wrong. I ended up dealing with my problem through CSS.

**Comment by jc-louis** [comment]
You need your `CustomFieldTemplate` to be a `React.PureComponent` to not loose focus

**Comment by heath-freenome** [comment]
@roievil does the solution provided in the previous comment work?
