### ISSUE TITLE
Form does not refresh definition section of schema

### ISSUE THREAD

**Issue by jantomas** [rjsf-team/react-jsonschema-form#1971]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

When want to update data structrure schema, after setState no change takes effect.

### Steps to Reproduce

1. Default schema looks like this
```
{
  "definitions": {
    "CountryCode_Type": {
      "enum": [
        "AF",
        "DE",
        "PL",
        "SK"
      ],
      "enumNames": [
        "AFGHANISTAN",
        "GERMANY",
        "POLAND",
        "SLOVAKIA"
      ]
    }...
}
```
2. Extend enum for CountryCode_Type
3. Call setState
`this.form.setState({schema: structureSchemaNew})`

#### Expected behavior

Form schema is updated according to modifications

#### Actual behavior

Form schema stays in initial state

### Version

@rjsf/core2.2.2

**Comment by epicfaace** [comment]
What is `this.form` equal to? Usually you need to call `React.setState`. Can you send a complete example?

**Comment by jantomas** [comment]
Yes, setState is method of React component, what actually `this.form` is. As we are combine React and JQuery world, to update React component we have to use indirect call. Consider it as equall to `this.setState`

**Comment by epicfaace** [comment]
I can't help much unless you can provide a complete example of your actual code.
