### ISSUE TITLE
Validation function doesn't work

### ISSUE THREAD

**Issue by ywu151** [rjsf-team/react-jsonschema-form#1973]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I use basic function like
import Form from '@rjsf/core';
schema = {
    properties: {
      uuid: {
        minLength: 10,
        required: true,
        type: 'string',
      },
    },
  };
While the validation doesn't work and the submission is always triggered.
Here is a warning during submitting
![Screen Shot 2020-08-05 at 3 45 24 PM](https://user-images.githubusercontent.com/33992458/89471313-af715c00-d732-11ea-9ba9-0e48e3e7bb22.png)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by epicfaace** [comment]
Can you provide a full example of all your code (including using the actual <Form> component)?

**Comment by ywu151** [comment]
Sure.
I use
```
"react": "^16.12.0",
"react-dom": "^16.12.0",
"styletron-react": "^5.2.6",
"bootstrap": "3.4.1",
```

for the code
```
import Form from '@rjsf/core';
import React, {useState} from 'react';
...
const [formData, setFormData] = useState({});
schema = {
    properties: {
      uuid: {
        minLength: 10,
        required: true,
        type: 'string',
      },
    },
  };
...
<div>
    <Helmet>
        <link
          href={assetUrl(
            '../../../node_modules/bootstrap/dist/css/bootstrap.min.css'
          )}
          rel="stylesheet"
        />
      </Helmet>
      <Form
        formData={formData}
        onChange={e => {setFormData(e.formData)}
        schema={schema}
      >
         <button />
      </Form>
</div>
```
Based on the Error information, it raised by `ajv.validate(schema, formData);` in `node_modules/@rjsf/core/lib/validate.js`
I also checked my `ajv` veriosn in `yarn.lock`
```
  ajv@^6.1.0, ajv@^6.10.0, ajv@^6.10.2, ajv@^6.12.0, ajv@^6.5.5, ajv@^6.7.0:
  version "6.12.2"
  resolved "https://unpm.uberinternal.com/ajv/-/ajv-6.12.2.tgz#c629c5eced17baf314437918d2da88c99d5958cd"
  integrity sha1-xinF7O0XuvMUQ3kY0tqIyZ1ZWM0=
  dependencies:
    fast-deep-equal "^3.1.1"
    fast-json-stable-stringify "^2.0.0"
    json-schema-traverse "^0.4.1"
    uri-js "^4.2.2"
```

**Comment by epicfaace** [comment]
I think you have a typo. This line

```
onChange={e => {setFormData(e.formData)}
```

should be

```
onChange={e => setFormData(e.formData)}
```

Additionally, can you try removing the custom submit button and see if it works?

If the issue is still there, please make a custom jsfiddle (https://jsfiddle.net/n1k0/f2y3fq7L/6/) and share it with me.

**Comment by ywu151** [comment]
I fixed this error by adding 
```
csp: {
    overrides: {scriptSrc: ["'unsafe-eval'"]},
},
```
One more question, if I want to use my own submit button to overwrite the default submit button, how should I do? How should I prevent submission if validation failed
