### ISSUE TITLE
Hidden field with Material-ui display large Spacing

### ISSUE THREAD

**Issue by lowent** [rjsf-team/react-jsonschema-form#1974]
### Prerequisites

- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Hidden field with Material-ui theme : field is hidden but a spacing is display between field

### Steps to Reproduce

1. Create 3 fields 
2. Hide the second field  : "mySecondField": { "ui:widget": "hidden"  }
3. Use Material-UI has theme

You can see that on the playground https://rjsf-team.github.io/react-jsonschema-form/
Select "widget" and use Material-ui as theme, see space where the Secret hidden field is.

#### Expected behavior

Field is hide without extra Blank

#### Actual behavior

 Field is hide but it remains large spacing between first and third field , this is ok with other Theme

### Version

1.8.1

**Comment by GraftonJ** [comment]
@lowent Did you find a resolution or workaround for this issue? I'm having the same problem.

**Comment by AScully24** [comment]
For anyone looking for a hacky work around.

In the component loading the form, call this method

```javascript
const handleMaterialFormHiddenFields = () => {
    var inputs = document.getElementsByTagName("input")

    for (var i = 0; i < inputs.length; i++) {
        const input = inputs[i]
        if (input.type.toLowerCase() == "hidden") {
            const grandParent = input.parentElement.parentElement
            grandParent.style.display = "none"
        }
    }
}
```

I don't like doing this at all, but not found another way around it.

I'd recommend having a wrapper around your RJSF form and have this load on every one. Then you can tweak it further for any project specific cases.
