### ISSUE TITLE
@rjsf/bootstrap-4 not published to npm?

### ISSUE THREAD

**Issue by sasikanth513** [rjsf-team/react-jsonschema-form#1980]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

In the master branch `bootstrap-4` theme was mentioned but when I tried install it `@rjsf/bootstrap-4` i'm getting the error

```
⇒  npm install --save @rjsf/bootstrap-4
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@rjsf%2fbootstrap-4 - Not found
npm ERR! 404
npm ERR! 404  '@rjsf/bootstrap-4@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sasikanth/.npm/_logs/2020-08-08T09_47_32_357Z-debug.log
```

I realized this code is merged very recently, If this is not yet released, any tentative date on when is this going to be released?

### Steps to Reproduce

1. Try installing `npm install --save @rjsf/bootstrap-4` in your node.js project

#### Expected behavior

- Package to be installed without any issues

#### Actual behavior

- Package is not found in npm registry

### Version

- (not related to the bug)

**Comment by epicfaace** [comment]
[@rjsf/bootstrap-4](https://www.npmjs.com/package/@rjsf/bootstrap-4) has just been published to npm with version 2.3.0. Thanks for your patience!
