### ISSUE TITLE
Cursor going to end of text input upon text change in between

### ISSUE THREAD

**Issue by s-kris** [rjsf-team/react-jsonschema-form#1983]
### Prerequisites

- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### Description

If you place the cursor in the middle of a text input value and press a key, the value is inserted in the correct position but afterwards the cursor is moved to the end of the field. 

I'm setting `formData` and  `onChange` props

```
 <JSONSchemaForm
            ref={(form) => {
              formInstance = form;
            }}
            disabled={loading}
            schema={jsonSchema}
            showErrorList={false}
            onSubmit={submitForm}
            formData={formData}
            onChange={(e) => {
              setState({ ...state, formData: e.formData });
            }}
          >
```

I have read the issues: https://github.com/rjsf-team/react-jsonschema-form/issues/328 https://github.com/rjsf-team/react-jsonschema-form/issues/851
I see that the issue is closed with the pull https://github.com/rjsf-team/react-jsonschema-form/pull/857
However, I'm still facing this bug. 

### Version
1.8.1

**Comment by epicfaace** [comment]
Can you link to a playground / jsfiddle replication of this issue? I can't see this issue on the latest playground, which uses @rjsf/core v2.

**Comment by s-kris** [comment]
Sorry for the delayed response. 
I'm not able to reproduce this bug outside of my current project. Too bad!

**Comment by s-kris** [comment]
Debugging revealed that react-easy-state was causing the issue.

**Comment by mtleonard120** [comment]
In case anyone else encounters a similar issue I found this was caused for me when my custom field inputs were using the formData passed in props as the source of truth instead of their local state values. The formData passed in props loses cursor position. Hope this helps!
