### ISSUE TITLE
How to return the default form in schemafield

### ISSUE THREAD

**Issue by EasyTuan** [rjsf-team/react-jsonschema-form#1984]
In 1.x, I can use react-jsonschema-form/lib/components/fields/SchemaField directly, but in 2.x,An error was thrown(Cannot read property 'ui:widget' of undefined)

**Comment by epicfaace** [comment]
Can you provide a code sample / jsfiddle example?

**Comment by EasyTuan** [comment]
@epicfaace [](https://codesandbox.io/s/heuristic-meitner-wcqt8?file=/src/App.js)
