### ISSUE TITLE
Material-UI array icons wrap in some cases

### ISSUE THREAD

**Issue by ValYouW** [rjsf-team/react-jsonschema-form#1985]
When rendering the array template (material-ui theme), there are cases when the icons (up/down etc) will wrap to new line.
In the [Example](https://codesandbox.io/s/react-jsonschema-form-array-bug-w94ff) shrink the browser and at some point the icons will wrap.

I have a quick fix idea, in `DefaultArrayItem` when rendering the item `Grid` [here](https://github.com/rjsf-team/react-jsonschema-form/blob/v2.3.0/packages/material-ui/src/ArrayFieldTemplate/ArrayFieldTemplate.tsx#L80) add `style={{overflow: 'auto'}}`, this will prevent the first cell to take the entire space.

(version: 2.3.0)

**Comment by epicfaace** [comment]
That sounds good. Will making this change also align the material ui array behavior to the arrays of other themes (such as Bootstrap)?

**Comment by ValYouW** [comment]
@epicfaace I need to check this... Also need to check mobile, the current toolbar icons are way too big for mobile...

**Comment by ValYouW** [comment]
@epicfaace Updated the [example](https://codesandbox.io/s/react-jsonschema-form-array-bug-w94ff) with 2 optional fixes:
1. Just make sure the buttons will not wrap and make them a bit smaller so it looks better on mobile
1. Like above but also don't render the items inside an "elevated box" which takes extra space - this more resembles the bootstrap-4 theme.

Personally I prefer number 2 but I am not sure whether it is considered as a "breaking change" (I think it does...).

Thoughts?
