### ISSUE TITLE
Localized Label and Accessibility Support and POST/GET HTTP calls for formsubmission 

### ISSUE THREAD

**Issue by rajaveernapu** [rjsf-team/react-jsonschema-form#1986]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the 
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
I need to see if following features can be implemented here 
1- Support for Localized labels and controls 
2- Support for Accessible controls
3- How to invoke http post calls , GET calls for page like a textbox with auto completed fetches from API.
4- Sharing data between forms by using redux store etc 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by epicfaace** [comment]
Localization is not yet supported: https://github.com/rjsf-team/react-jsonschema-form/issues/739
Accessibility is partially supported: https://github.com/rjsf-team/react-jsonschema-form/issues/959

3 and 4 are possible, though beyond the scope of this library -- it's something that you would need to implement yourself, and perhaps if you'd like to contribute an example for the docs, that would be appreciated.

Please make specific issues for each issue you're facing in the future!
