### ISSUE TITLE
Outlined Material-UI TextField

### ISSUE THREAD

**Issue by correaricardo** [rjsf-team/react-jsonschema-form#1987]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

How can I pass props (specifically, the **variant** prop) to the Material-UI TextField?

![image](https://user-images.githubusercontent.com/7898290/89913023-dc04f800-dbb8-11ea-8153-16806e478787.png)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Version

**^2.3.0**

**Comment by correaricardo** [comment]
Well, I have [override](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/) the TextWidget with a custom outlined TextField, I don't know if there's another solution

![image](https://user-images.githubusercontent.com/7898290/89950557-76802e00-dbef-11ea-9ea7-deb53a844b53.png)

**Comment by ValYouW** [comment]
You can simply wrap the Form in a MuiTheme, this is how I do it:

```js
import { MuiThemeProvider, createMuiTheme } from '@material-ui/core/styles';

const muiTheme = createMuiTheme({
    props: {
        MuiTextField: {
            variant: 'outlined'
        }
    }
});

// Then in render
<MuiThemeProvider theme={muiTheme}>
    <Form />
</MuiThemeProvider>
```

**Comment by stanlemon** [comment]
Ideally we need to support passing in this sort of thing via uiSchema, but we don't do that yet today as far as I recall.

**Comment by mberatsanli** [comment]
Solution for MUI (v5)
see: https://mui.com/material-ui/customization/theme-components/#default-props

```js
import {createTheme, ThemeProvider} from "@mui/material";

const theme = createTheme({
    components: {
      MuiTextField: {
        defaultProps: {
          variant: 'standard',
        },
     },
  },
});

<ThemeProvider theme={theme}>
    ...
</ThemeProvider>

```

**Comment by heath-freenome** [comment]
There appears to be an answer for this question. Will close soon

**Comment by kdegaltseva** [comment]
It doen't work with mui 7

**Comment by heath-freenome** [comment]
> It doen't work with mui 7

It's likely that you have to read the upgrade guides to adapt the solution to MUI 7. Otherwise file a bug with them since it is their codebase and has nothing to do with RJSF
