### ISSUE TITLE
ArrayFieldTemplate for children of array

### ISSUE THREAD

**Issue by Gryso** [rjsf-team/react-jsonschema-form#1989]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

Hello guys, thanks for nice work on library. I am seeking for advice.

I have `schema` like this:
```json
{
  "type": "array",
  "items": [
    {
      "type": "array",
      "items": [...]
    },
    {
      "type": "array",
      "items": [...]
    }
  ]
}
```
and I am using arrayFieldTemplate on top level `uiSchema`:
```json
{
  "ui:arrayFieldTemplate": MyArrayFieldTemplate, 
}
```
I want to define another arrayFieldTemplate for all items that are rendered as children of the top level array and maybe even their children. Is there a way how to define custom templates for children of array (also children of top level array) in `uiSchema`?

**Comment by ValYouW** [comment]
Did you try [this](https://react-jsonschema-form.readthedocs.io/en/latest/usage/arrays/#uischema-for-array-items) from the docs?

**Comment by Gryso** [comment]
> Did you try [this](https://react-jsonschema-form.readthedocs.io/en/latest/usage/arrays/#uischema-for-array-items) from the docs?

No i did not. It does solve the problem thanks a lot. I ques, I focused on 'customization' part of docs too much.
