### ISSUE TITLE
Conditionally enabling submit button resets the whole form

### ISSUE THREAD

**Issue by grgicpetar** [rjsf-team/react-jsonschema-form#1997]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
In the form the submit button is disabled by default. Only when all the required fields are filled the submit button becomes enabled. At that point the whole form resets.

I am using @rjsf/antd package, I don't know if it is related.

onChange method:

```
const onChange = (props: any) => {
    let counter = 0;
    props.schema.required.forEach((item: string) => {
      if (!props.formData.hasOwnProperty(item)) {
        counter++;
      }
    });
    console.log(counter);
    if (counter > 0) {
      setDisableSubmit(true);
    } else {
      setDisableSubmit(false);
    }
  };
```

Form:

```
<Form
      className="form-react-schema-json"
      widgets={Widgets}
      onSubmit={handleSubmit}
      onChange={onChange}
      FieldTemplate={FieldTemplate}
      transformErrors={transformErrors}
      showErrorList={false}
    >
      <Button htmlType="submit" type="primary" disabled={disableSubmit}>
        Submit
      </Button>{" "}
      <Popconfirm
        title={t(("quit")}
        okText={t("yes")}
        cancelText={t("no")}
        onConfirm={handleOkQuit}
      >
        <Button>Quit</Button>
      </Popconfirm>
    </Form>
```

### Steps to Reproduce

1. Render form with disabled button. The button is a children element.
2. Conditonally update the state which decides if button is disabled or enabled.
3. Enable the submit button.

#### Expected behavior

The form should have an enabled submit button with all the previous values filled.

#### Actual behavior

The form resets all the fields. The submit button is disabled.

### Version

2.2.1

**Comment by epicfaace** [comment]
Can you link to a jsfiddle example?

Potentially, making the form a controlled component (by passing in the `formData` prop) may fix this.

**Comment by stvhanna** [comment]
@epicfaace Not sure if this issue is related to https://github.com/rjsf-team/react-jsonschema-form/issues/2056

**Comment by phatNfqAsia** [comment]
@stvhanna @grgicpetar 
As @epicfaace instructed doing this fix the problem
```jsx
const [formData, setFormData]  = React.useState({});
...
<Form
 onChange={jsonSchemaChangeEvent => {
   setFormData(jsonSchemaChangeEvent.formData);
})
...
/>
```

**Comment by josephalez** [comment]
> @stvhanna @grgicpetar As @epicfaace instructed doing this fix the problem
> 
> ```js
> const [formData, setFormData]  = React.useState({});
> ...
> <Form
>  onChange={jsonSchemaChangeEvent => {
>    setFormData(jsonSchemaChangeEvent.formData);
> })
> ...
> />
> ```

This causes text/number inputs to lose focus after every keystroke, is there a way to prevent this?

**Comment by heath-freenome** [comment]
Are you passing the formData back into the `Form`?

**Comment by zuritale** [comment]
> Are you passing the formData back into the `Form`?

Hi(this is my new account after josephalez), I don't have access to that project anymore but in my case I was pasing it, the formData, back to the Form, but it kept losing focus after every keystroke, so we migrated to formik
