### ISSUE TITLE
Bootstrap 4 theme not applying UiSchema classNames

### ISSUE THREAD

**Issue by nicmendoza** [rjsf-team/react-jsonschema-form#1998]
### Prerequisites

- [ ✔ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ✔ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ✔ ] I'm providing a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCJ9LCJzY2hlbWEiOnsidGl0bGUiOiJBIHJlZ2lzdHJhdGlvbiBmb3JtIiwiZGVzY3JpcHRpb24iOiJBIHNpbXBsZSBmb3JtIGV4YW1wbGUuIiwidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbImZpcnN0TmFtZSIsImxhc3ROYW1lIl0sInByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkZpcnN0IG5hbWUiLCJkZWZhdWx0IjoiQ2h1Y2sifSwibGFzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiTGFzdCBuYW1lIn0sInRlbGVwaG9uZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJUZWxlcGhvbmUiLCJtaW5MZW5ndGgiOjEwfX19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIiwidWk6YXV0b2NvbXBsZXRlIjoiZmFtaWx5LW5hbWUiLCJjbGFzc05hbWVzIjoiYmctZGFuZ2VyIn0sImxhc3ROYW1lIjp7InVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJnaXZlbi1uYW1lIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sInRoZW1lIjoiYm9vdHN0cmFwLTQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19) demonstrating the issue.

### Steps to Reproduce
1. As an example, add a "classNames" property in the uiSchema to any of the form fields ("firstName" in the playground link) and set it to "bg-danger (FYI I'm currently using col-* classes with the Bootstrap 3 theme and it works as expected in my project)
2. Load the form in a browser

#### Expected behavior

I would expect to see a "danger color" around the input (i.e. red)

#### Actual behavior

No background color. The class is not applied anywhere in the DOM. Here's a screenshot comparing the two versions. BS3 in the middle, BS4 on the right.

<img width="1197" alt="bs3_v_bs4_comparison" src="https://user-images.githubusercontent.com/5489626/90559826-329ba480-e16c-11ea-9a3f-924fc9f7ef78.png">

### Version

Here's what's in my package.json (though my repro steps use the playground)
"@rjsf/bootstrap-4": "^2.3.0",
"@rjsf/core": "^2.3.0",

**Comment by arkzky** [comment]
I would like to add more to the issue, neither of these uiSchema options seems to work as they should:

### They don't do their changes at all
- `ui:title`
- `ui:placeholder`
-  `ui:options`
    - `label: false`
### It doesn't appear as expected
- `ui:description` 
    - Appeas under the input field, just like a `ui:help`

I attach a [playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIn0sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsiZmlyc3ROYW1lIiwibGFzdE5hbWUiXSwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRmlyc3QgbmFtZSIsImRlZmF1bHQiOiJDaHVjayJ9LCJsYXN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJMYXN0IG5hbWUifSwidGVsZXBob25lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlRlbGVwaG9uZSIsIm1pbkxlbmd0aCI6MTB9fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJmYW1pbHktbmFtZSIsImNsYXNzTmFtZXMiOiJiZy1kYW5nZXIifSwibGFzdE5hbWUiOnsidWk6aGVscCI6IkhpbnQ6IFB1dCB5b3VyIGxhc3QgbmFtZSIsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJnaXZlbi1uYW1lIiwidWk6b3B0aW9ucyI6eyJsYWJlbCI6ZmFsc2V9fSwidGVsZXBob25lIjp7InVpOnRpdGxlIjoiTXkgVGVsZXBob25lIiwidWk6ZGVzY3JpcHRpb24iOiJUZWxlcGhvbmUgZGVzY3JpcHRpb24iLCJ1aTpwbGFjZWhvbGRlciI6IlB1dCB5b3VyIHRlbGVwaG9uZSIsInVpOm9wdGlvbnMiOnsiaW5wdXRUeXBlIjoidGVsIn19fSwidGhlbWUiOiJib290c3RyYXAtNCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=) to demonstrate this additional issues

**Comment by psehgal** [comment]
Echoing that adding `classNames` in `uiSchema` is not adding classes to components. Any updates on when this might be added?

**Comment by slopen** [comment]
Would like to add even more here: in bootstrap-4 no classes at all exist there apart from bootstrap styling (`row`, `py-*`, `my-*` etc, obviously going with `!important` directive) + direct style attribute; which is absolutely annoying making this almost impossible for even slight adjustments (comparing to default bootstrap-3).

<img width="513" alt="Screenshot 2021-01-21 at 15 17 20" src="https://user-images.githubusercontent.com/673813/105370789-d990da80-5bfb-11eb-9d77-deb546d493c5.png">


so **WAS** hoping that uiSchema could help here, but not

**Comment by epicfaace** [comment]
If anyone is willing to make a PR to fix this issue, we'd gladly accept it!

**Comment by mrpintcom** [comment]
This issue relates to [issue #1738](https://github.com/rjsf-team/react-jsonschema-form/issues/1738#issuecomment-995943783) and my latest comment may provide insight into what needs to change. With confirmation, I could make the updates.

**Comment by heath-freenome** [comment]
Testing with the [playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIn0sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsiZmlyc3ROYW1lIiwibGFzdE5hbWUiXSwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRmlyc3QgbmFtZSIsImRlZmF1bHQiOiJDaHVjayJ9LCJsYXN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJMYXN0IG5hbWUifSwidGVsZXBob25lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlRlbGVwaG9uZSIsIm1pbkxlbmd0aCI6MTB9fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJmYW1pbHktbmFtZSIsImNsYXNzTmFtZXMiOiJiZy1kYW5nZXIifSwibGFzdE5hbWUiOnsidWk6aGVscCI6IkhpbnQ6IFB1dCB5b3VyIGxhc3QgbmFtZSIsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJnaXZlbi1uYW1lIiwidWk6b3B0aW9ucyI6eyJsYWJlbCI6ZmFsc2V9fSwidGVsZXBob25lIjp7InVpOnRpdGxlIjoiTXkgVGVsZXBob25lIiwidWk6ZGVzY3JpcHRpb24iOiJUZWxlcGhvbmUgZGVzY3JpcHRpb24iLCJ1aTpwbGFjZWhvbGRlciI6IlB1dCB5b3VyIHRlbGVwaG9uZSIsInVpOm9wdGlvbnMiOnsiaW5wdXRUeXBlIjoidGVsIn19fSwidGhlbWUiOiJib290c3RyYXAtNCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=) provided in one of the comments above, this issue seems to be fixed in all themes
