### ISSUE TITLE
Typescript: OnFocus not a property of Form

### ISSUE THREAD

**Issue by cdussud** [rjsf-team/react-jsonschema-form#1999]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

[Description of the bug or feature]

Minor issue with Typescript: the Form object has no property for onFocus (the way it does for onChange and onSubmit). 

The onFocus callback works just fine, but using causes a typescript error that needs to be ignored.

### Steps to Reproduce

1. Create an rjsf Form object in a Typescript file
2. add a callback to onFocus

```
<Form
    onFocus = {() => { console.log('hello')}
/>
```

#### Expected behavior

No typescript error

#### Actual behavior

Typescript compiler issues an error: `Property 'onFocus' does not exist on type 'IntrinsicAttributes & Pick<Pick<FormProps<unknown>....`

### Version

2.3.0

**Comment by epicfaace** [comment]
@cdussud thanks for reporting -- could you update the `index.d.ts` file and send over a PR to fix this?

**Comment by cdussud** [comment]
Actually I got my wires crossed. This works fine on the latest version!! I was loading an older version.
