### ISSUE TITLE
Why array item keys changed if I remove or add a new item to the array?

### ISSUE THREAD

**Issue by Klynger** [rjsf-team/react-jsonschema-form#2001]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Is there a reason to change the key of elements of an array that have no change? This happens every time we add or remove an item from the array ([part of the code that does that in 1.x](https://github.com/rjsf-team/react-jsonschema-form/blob/1.x/src/components/fields/ArrayField.js#L218-L233) // [code in master](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/fields/ArrayField.js#L220-L241))

### Steps to Reproduce

You can just check the code to see that this is happening, or you can implement the `ArrayFieldTemplate` and check that all the keys change every time you add or remove an item.

#### Expected behavior

I don't know exactly if this is intentional or not. This is more like a question and if there is no reason to be this way maybe a suggestion to change.

#### Actual behavior

Keys changing all the time

### Version

I'm using `1.x`, but I saw that the new version has the same behavior

And just a comment, the code from this library is really nice, any time I want to understand how you guys are doing things is really easy to just open the code and read it.

**Comment by epicfaace** [comment]
The last change involving array keys was added in #1335. What you are describing shouldn't be happening; we have a specific test to check for that ("should retain existing row keys/ids when adding new row" -- https://github.com/fsteger/react-jsonschema-form/blob/f5fddc8aff1f800430415e176886db8c48459088/test/ArrayField_test.js#L253).

Could you look into why you are seeing this behavior and if it's really happening? Perhaps can you see if something is wrong with the existing tests that guard against this behavior, and if you can modify it to show that array keys are indeed changing for existing items when adding / removing items?

**Comment by Klynger** [comment]
@epicfaace [here is an example of this happening](https://codesandbox.io/s/heuristic-resonance-towzo), I just copied the component in the tests (`ExposedArrayKeyTemplate`) and put in a codesandbox with a `console.log` with the index and key of the element.

#### How to see it happening

1. Open the console
2. Add one item and see the key it
3. Add the second item and then see the key of the first item again, is different
![image](https://user-images.githubusercontent.com/8517023/90674255-3f350100-e22f-11ea-9c82-b0b908c43ed0.png)

**Comment by Klynger** [comment]
I saw this PR that you put too, and [saw this comment from the guy](https://github.com/rjsf-team/react-jsonschema-form/pull/1335/files#r298815366) that did this code, but I didn't understand exactly why is this way. He said that if you change the list externally (using something else then `onAddClick`), didn't know that this is possible
