### ISSUE TITLE
[bootstrap-4] Widget and FieldTemplate customisation

### ISSUE THREAD

**Issue by stufisher** [rjsf-team/react-jsonschema-form#2007]
### Prerequisites

- [ x ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ x ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ x ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

The boostrap-4 theme widgets now wrap each form control in a Form.Group directly with the label:
https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/bootstrap-4/src/TextWidget/TextWidget.tsx

this makes it pretty difficult to customise the form layout by providing a custom FieldTemplate. The only way to do this is to now copy and paste each widget you need and modify them independently.

Previously you could inject a customised FieldTemplate and thus override the label / field positioning as the label was part of the FieldTemplate and not the specific Widget in question

#### Expected behavior

It would be better for customisation if the label was injected from the FieldTemplate rather than in each widget (as this worked previously)

#### Actual behavior

You have to modify every Widget class rather than the FieldTemplate

### Version

@rjsf/bootstrap-4: ^2.3.0
@rjsf/core: ^2.1.0

**Comment by newt10** [comment]
Addressed by PR #2533
