### ISSUE TITLE
Non-required fields do not pass validation when they are `null` unless their `type` is an array with "null"

### ISSUE THREAD

**Issue by Vestride** [rjsf-team/react-jsonschema-form#2009]
### Prerequisites

- [x] I have read the [documentation](https://reau7ct-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Non-required fields do not pass validation when they are `null` unless their `type` is an array with "null".

[Playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOm51bGwsIm1pZGRsZU5hbWUiOm51bGwsImxhc3ROYW1lIjpudWxsfSwic2NoZW1hIjp7InRpdGxlIjoiTm9uLXJlcXVpcmVkIG51bGwgaXNzdWUiLCJkZXNjcmlwdGlvbiI6Ik5vbi1yZXF1aXJlZCBmaWVsZHMgZG8gbm90IHBhc3MgdmFsaWRhdGlvbiB3aGVuIHRoZXkgYXJlIGBudWxsYCB1bmxlc3MgdGhlaXIgYHR5cGVgIGlzIGFuIGFycmF5IHdpdGggXCJudWxsXCIuIiwidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbImZpcnN0TmFtZSJdLCJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJGaXJzdCBuYW1lIn0sIm1pZGRsZU5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiTWlkZGxlIG5hbWUifSwibGFzdE5hbWUiOnsidHlwZSI6WyJzdHJpbmciLCJudWxsIl0sInRpdGxlIjoiTGFzdCBuYW1lIn19fSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOnRydWUsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

### Steps to Reproduce

Given a schema like this with 3 fields and only one of them is `required`, the second field, `middleName`, does not pass validation. Instead the error **.middleName should be string** is shown.

```json
{
  "type": "object",
  "required": [
    "firstName"
  ],
  "properties": {
    "firstName": {
      "type": "string",
      "title": "First name"
    },
    "middleName": {
      "type": "string",
      "title": "Middle name"
    },
    "lastName": {
      "type": [
        "string",
        "null"
      ],
      "title": "Last name"
    }
  }
}
```

Initial form data

```json
{
  "firstName": null,
  "middleName": null,
  "lastName": null
}
```
#### Expected behavior

Only the `firstName` field should have an error state because it is required. The `middleName` field should not have an error because it is not required. `lastName` should not have an error (and it doesn't).

#### Actual behavior

Both `firstName` and `middleName` have errors. `lastName` does not.

### Version

2.3.0

**Comment by RoboPhred** [comment]
This is a json-schema thing, required requires the presence of a property regardless of its value, and a null value is still considered presence.  If the property exists, and there is json-schema matching it, the matcher will kick in, enforcing the type.

What does the form do if you enter data then clear it out again?  The form should probably detect if we allow null and either set to null, or set to undefined if not.

As for the initial form data, you are passing data that would not validate in a normal json-schema validator.  You can test this with AJV directly: https://runkit.com/embed/pzigycvt20n1

**Comment by Vestride** [comment]
Thanks for the explanation @RoboPhred, I see this is by design now.

**Comment by epicfaace** [comment]
@Vestride if you wanted a nullable type, you could also do:

```
    "middleName": {
      "type": ["string", "null"],
      "title": "Middle name"
    },
```
