### ISSUE TITLE
[Question] support for multi-select widget with external data source and search?

### ISSUE THREAD

**Issue by zopyx** [rjsf-team/react-jsonschema-form#2015]
I am currently checking the options for moving to react-jsonschema-form.
In many cases we have large external vocabularies and external sources that can not be specified as part of a JSON schema.
Is there a way to configure a multi-select widget where the user types in a prefix of a query, the query is send through AJAX to some custom REST endpoint. The REST endpoint will then return the related hits. The widget should then show the options and let the user decide. I could not find any example or pointer in the documentation. ...something like the "chosen" module with a configured external source and multiple options enabled.

**Comment by raratiru** [comment]
Did you find a solution? 

The closest solution I could find is this library: https://github.com/RXNT/react-json-schema-form-extras
