### ISSUE TITLE
Titles in refs are not incorporated when constructing allOf/oneOf/anyOf dropdowns

### ISSUE THREAD

**Issue by erunion** [rjsf-team/react-jsonschema-form#2016]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

If a `title` property is stored within a `$ref` on an `allOf`, `oneOf`, or `anyOf` schema, it is not used when constructing a dropdown select for that schema.

### Steps to Reproduce

You can see this in action here: https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0Iiwib25lT2YiOlt7IiRyZWYiOiIjL2NvbXBvbmVudHMvc2NoZW1hcy9DYXQifSx7InRpdGxlIjoiV29vZiIsIiRyZWYiOiIjL2NvbXBvbmVudHMvc2NoZW1hcy9Eb2cifV0sImNvbXBvbmVudHMiOnsic2NoZW1hcyI6eyJQZXQiOnsidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbInBldF90eXBlIl0sInByb3BlcnRpZXMiOnsicGV0X3R5cGUiOnsidHlwZSI6InN0cmluZyJ9fSwiZGlzY3JpbWluYXRvciI6eyJwcm9wZXJ0eU5hbWUiOiJwZXRfdHlwZSJ9fSwiRG9nIjp7ImFsbE9mIjpbeyIkcmVmIjoiIy9jb21wb25lbnRzL3NjaGVtYXMvUGV0In0seyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJiYXJrIjp7InR5cGUiOiJib29sZWFuIn0sImJyZWVkIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIkRpbmdvIiwiSHVza3kiLCJSZXRyaWV2ZXIiLCJTaGVwaGVyZCJdfX19XX0sIkNhdCI6eyJ0aXRsZSI6Ik1lb3ciLCJ0eXBlIjoib2JqZWN0IiwiYWxsT2YiOlt7IiRyZWYiOiIjL2NvbXBvbmVudHMvc2NoZW1hcy9QZXQifSx7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Imh1bnRzIjp7InR5cGUiOiJib29sZWFuIn0sImFnZSI6eyJ0eXBlIjoiaW50ZWdlciJ9fX1dfX19fSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19

We have a `oneOf` with both entries in the array being loaded via a `$ref`. One of them has a `title` alongside the `$ref` in the array, while the other has a `title` in the `$ref` schema. The one with the title alongside has its title represented in the dropdown, while the other has an option label of "Option 1".

#### Expected behavior

Titles within a `$ref` should be incorporated into the dropdown option labels.

#### Actual behavior

Title is not accessed within the `$ref` when constructing the dropdown.

### Version

Current HEAD

**Comment by mr-bjerre** [comment]
Any pointers on how to fix this?

**Comment by epicfaace** [comment]
I think you have to fix this line of code (https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/fields/MultiSchemaField.js#L135) so that it properly resolves `$ref`'s in the subschema before getting its `title` property.

**Comment by mr-bjerre** [comment]
Ok so I forked the project, cloned it and followed the [instructions](https://react-jsonschema-form.readthedocs.io/en/latest/contributing/) but I get a compile error on playground when running `npm start`. Then I get `Module not found: Error: Can't resolve './material-ui.cjs.development.js' in ...` although the file is actually there. Maybe those errors are related I don't know - I'm kinda a rookie in the webpack field unfortunately.

I'm using node v14.13.0 and npm 6.14.8.

**Comment by epicfaace** [comment]
I think that's a bug with Netlify (i.e. something with mismatches with Node version) -- you can just ignore those jobs.
