### ISSUE TITLE
Errors are not cleared on resubmit, in controlled Form (@rjsf/material-ui)

### ISSUE THREAD

**Issue by arnemahl** [rjsf-team/react-jsonschema-form#2017]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When submitting the form, the previous errors are not cleared, although they are fixed.

This only happen if you use a *controlled* Form (from `@rjsf/material-ui: 2.3.0`). Uncontrolled Form works as expected.

Possible regression, as this has been [reported before](https://github.com/rjsf-team/react-jsonschema-form/issues/930) and since fixed (the linked sandbox in that issue no longer reproduces the problem).

### Steps to Reproduce

1. Open [CodeSandbox demo](https://codesandbox.io/s/bug-in-react-jsonschema-form-6u6xe?file=/src/App.js)
1. Use the controlled form
1. Click submit (Shows error message)
1. Fix error (e.g write Jon)
1. Click submit (Still shows error message)

#### Expected behavior

Displayed error message should go away on submit if there are no errors.

#### Actual behavior

Displayed error message persists.

PS:  `onSubmit` is called and `event.errors` is correctly empty: `[]`.

### Version

2.3.0

@rjsf/core: 2.3.0
@rjsf/material-ui: 2.3.0

**Comment by arnemahl** [comment]
A usable workaround for this problem is to set the prop `liveValidate`. Live validation correctly updates error messages, as opposed to only validating on submit.

(I prefer to enable `liveValidate` once the user has clicked submit, to avoid showing error messages before they have started filling out the form.)

[CodeSandbox demo](https://codesandbox.io/s/workaround-for-bug-in-react-jsonschema-form-forked-uwrt8).

**Comment by e-cooper** [comment]
I've also recently encountered this issue in the @rjsf/core `Form` component. In my case, I'm presenting async server errors with the `extraErrors` prop as described in the docs. However, if there are any schema validation errors (which are then corrected) before the submit button is clicked again and `onSubmit` is handled, those aren't cleared.

**Comment by findumesh** [comment]
This seems to be introduced in 2.0.1. I've reverted back to v 2.0.0 and it started working again. Probable commit for this behavior change would be https://github.com/rjsf-team/react-jsonschema-form/commit/72963385db4753243d134641709b7a47930a4687

**Comment by ofekshalom** [comment]
Hi, I'm using extra errors with the default rjsf Form component.  
When I'm submitting the form I still can see  the last error that occurred in the Form, even though the Form is valid.  
I'm using version 2.4.0 and tried version 3.0.  
Is there a way to fix this issue?
