### ISSUE TITLE
Validation not working after generating the build

### ISSUE THREAD

**Issue by jitdwoodside** [rjsf-team/react-jsonschema-form#2020]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

The validation is working fine in local but after generating production build it is showing error. Here is the error

Error compiling schema, function code: var refVal1 = refVal[1]; var validate = function(data, dataPath, parentData, parentDataProperty, rootData) { 'use strict';  var vErrors = null;  var errors = 0;      if (rootData === undefined) rootData = data;      var errs_1 = errors;    var errs_2 = errors; if ((typeof data !== "number" || (data % 1) || data !== data)) {  var err =  { keyword: 'type' , dataPath: (dataPath || '') + "" , schemaPath: '#/definitions/nonNegativeInteger/type' , params: { type: 'integer' }  , message: 'should be integer'  } ;  if (vErrors === null) vErrors = [err]; else vErrors.push(err); errors++;  }  if ((typeof data === "number")) {    if (  data < 0 || data !== data) {  var err =  { keyword: 'minimum' , dataPath: (dataPath || '') + "" , schemaPath: '#/definitions/nonNegativeInteger/minimum' , params: { comparison: '>=', limit: 0, exclusive: false }  , message: 'should be >= 0' } ;  if (vErrors === null) vErrors = [err]; else vErrors.push(err); errors++;  }   }  var valid2 = errors === errs_2;   var valid1 = errors === errs_1;   validate.errors = vErrors;  return errors === 0;        }; return validate;

### Steps to Reproduce

```
const schema: JSONSchema7 = {
        "type": "object",
        "required": [
            "firstName"
        ],
        "properties": {
            "firstName": {
                "type": "string",
                "title": 'First Name',
                "minLength": 5
            }
        }
};

const uiSchema = {
        "firstName": {
            "ui:options": {
                label: false
            }
        }
 };
const formData = {
        firstName: ""
};
```

#### Expected behavior

The validation should work and show error message

#### Actual behavior

Showing error:-
Error compiling schema, function code: var refVal1 = refVal[1]; var validate = function(data, dataPath, parentData, parentDataProperty, rootData) { 'use strict';  var vErrors = null;  var errors = 0;      if (rootData === undefined) rootData = data;      var errs_1 = errors;    var errs_2 = errors; if ((typeof data !== "number" || (data % 1) || data !== data)) {  var err =  { keyword: 'type' , dataPath: (dataPath || '') + "" , schemaPath: '#/definitions/nonNegativeInteger/type' , params: { type: 'integer' }  , message: 'should be integer'  } ;  if (vErrors === null) vErrors = [err]; else vErrors.push(err); errors++;  }  if ((typeof data === "number")) {    if (  data < 0 || data !== data) {  var err =  { keyword: 'minimum' , dataPath: (dataPath || '') + "" , schemaPath: '#/definitions/nonNegativeInteger/minimum' , params: { comparison: '>=', limit: 0, exclusive: false }  , message: 'should be >= 0' } ;  if (vErrors === null) vErrors = [err]; else vErrors.push(err); errors++;  }   }  var valid2 = errors === errs_2;   var valid1 = errors === errs_1;   validate.errors = vErrors;  return errors === 0;        }; return validate;

### Version

I am using "@rjsf/core": "^2.3.0"

**Comment by epicfaace** [comment]
Does this error only happen with that specific schema? Or with even a simple schema such as `{type: "string"}`?

**Comment by jitdwoodside** [comment]
Yes the issue is also happening for simple schema `{type: "string"}`

**Comment by jitdwoodside** [comment]
FYI i am using typescript to write the code.

**Comment by jitdwoodside** [comment]
Hi There,

Any update on this issue?

**Comment by VivianaG** [comment]
Hi,

I also ran into the same issue. After debugging it, it seems that it relates to this issue: [https://github.com/ajv-validator/ajv/issues/551](url)

**Comment by PremVarma** [comment]
If you are using helmet in react please use version 3.22.0 it internally has helmet-csp which solved this contect Security Policy issue or you can seprately install helmet-csp from npm.

**Comment by BALEHOK** [comment]
@jitdwoodside I understand this is an old post, but have you solved the problem and how? Thanks.

**Comment by jainamshah711** [comment]
@jitdwoodside have you find anything to resolve the above issue?

**Comment by heath-freenome** [comment]
So the fix for this is NOT really in @rjsf per this [comment in AJV](https://github.com/ajv-validator/ajv/issues/406#issuecomment-910623734)

**Comment by nickgros** [comment]
This could be a potential path forward: https://github.com/rjsf-team/react-jsonschema-form/issues/3269
