### ISSUE TITLE
How to check random schema is renderable as a form?

### ISSUE THREAD

**Issue by ppmag** [rjsf-team/react-jsonschema-form#2024]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

Random schema may be valid against draft-07, but how to make sure it is renderable with 'react-jsonschema-form'?
How to validate it externally (outside the 'react-jsonschema-form').?
Unfortunately, I didn't found any local metaschema, which as I expected, should limit draft-07 to some subset, which 'react-jsonschema-form' knows how to represent as web form. 

Also I'm looking for functionality to easily limit whole assortment of Fields/Widgets to some custom subset.  I was expecting to do it with cutting down metaschema I was talking above.

TYA.

**Comment by epicfaace** [comment]
> Unfortunately, I didn't found any local metaschema, which as I expected, should limit draft-07 to some subset, which 'react-jsonschema-form' knows how to represent as web form.

That would be a nice contribution / feature to have!

**Comment by SivaGanesh56** [comment]
@ppmag any breakthrough on this ?
