### ISSUE TITLE
"Module not found" error trying to import bootstrap-4 and fluent-ui themes

### ISSUE THREAD

**Issue by Sammii** [rjsf-team/react-jsonschema-form#2027]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Errors when trying to import Bootstrap 4 or Fluent UI themes.
```
./node_modules/@rjsf/bootstrap-4/dist/bootstrap-4.cjs.development.js
Module not found: Can't resolve 'react-bootstrap/Button' in '/my-app/node_modules/@rjsf/bootstrap-4/dist'
```
```
./node_modules/@rjsf/fluent-ui/dist/fluent-ui.cjs.development.js
Module not found: Can't resolve '@fluentui/react' in '/my-app/node_modules/@rjsf/fluent-ui/dist'
```

### Steps to Reproduce

1. `yarn install @rjsf/core`
2. `yarn install @rjsf/bootstrap-4` and/or `yarn install @rjsf/fluent-ui`
3. Confirmed dependencies are present in `package.json`:
```
"dependencies": {
    "@rjsf/bootstrap-4": "^2.3.0",
    "@rjsf/core": "^2.3.0",
    "@rjsf/fluent-ui": "^2.3.0",
...
}
```
4. Import the theme into my app: `import Form from "@rjsf/fluent-ui";`

### Version

2.3.0

**Comment by Xtremilicious** [comment]
@Sammii Try explicitly installing `react-bootstrap` using `npm install --save react-bootstrap@1.0.1` if you are using the Bootstrap-4 version. These dependencies are peer dependencies, hence need to be installed separately.

**Comment by Sammii** [comment]
Thanks @Xtremilicious , that indeed worked to solve my issue.

It would be great if those instructions were added to the [documentation](https://react-jsonschema-form.readthedocs.io/en/latest/usage/themes/) since it includes installation instructions for themes but there is no mention of the peer dependencies that need to be verified/installed separately. I didn't actually realize that every theme even had its own README.
