### ISSUE TITLE
Using a memoized component as custom widget raise an "Unsupported widget definition"

### ISSUE THREAD

**Issue by lucataglia** [rjsf-team/react-jsonschema-form#2039]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
Using a memoized component (_React.memo(Component)_) as [custom widget](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/) raise the following error:
```
utils.js:210 Uncaught Error: Unsupported widget definition: object
    at getWidget (utils.js:210)
    at getWidget (utils.js:224)
    at BooleanField (BooleanField.js:52)
```
I investigated the source code I saw that into the utils.js file there is an if statement that fails to recognize the memoized component:
```
// utils.js, line 201-203. ReactIs.isMemo(widget) gives false as result
if (typeof widget === "function" || ReactIs.isForwardRef(_react["default"].createElement(widget)) || ReactIs.isMemo(widget)) {
    return mergeOptions(widget);
  }
```
Googling around I found out that into the ReactIs library the behavior of the isMemo method was recently changed: [#PR 17278](https://github.com/facebook/react/pull/17278)

I'm wondering if also the react-jsonschema-form library has to change how it checks that conditions. Removing the React.memo that wrap my component makes the "Unsupported widget definition" error disappear.

In my code I'm trying to use a custom CheckboxWidget.
### Steps to Reproduce

1. Create a memoized component e.g. const MemoizedComponent = React.memo(/* could be also a silly div*/)
2. Use that component as custom widget e.g. { CheckboxWidget: MemoizedComponent }
3. Render the form

#### Expected behavior

A memoized component shouldn't breaks the page

#### Actual behavior

Use e memoized component as custom widget breaks the page

### Version
react: "16.13.1"
react-jsonschema-form: "2.0.0-alpha.1"

**Comment by adam-beck** [comment]
I wasn't able to recreate this in the latest version.

**Comment by adam-beck** [comment]
I also wasn't able to recreate this with the version supplied:

```js
import React from "react";
import Form from "react-jsonschema-form";

import { render } from "react-dom";

const schema = {
  type: "boolean",
  default: true,
};

const uiSchema = {
  "ui:widget": "checkbox",
};

const CustomCheckbox = function(props) {
  return (
    <button
      id="custom"
      className={props.value ? "checked" : "unchecked"}
      onClick={() => props.onChange(!props.value)}>
      {String(props.value)}!
    </button>
  );
};

const Memoed = React.memo(CustomCheckbox);

const widgets = {
  CheckboxWidget: Memoed,
};

render(
  <Form schema={schema} uiSchema={uiSchema} widgets={widgets} />,
  document.getElementById("app")
);
```

**Comment by adam-beck** [comment]
I _am_ getting an error on [codesandbox](https://codesandbox.io/s/wizardly-fire-chqvy?file=/src/index.js:536-542) though.

**Comment by adam-beck** [comment]
Here is a CRA demonstrating the issue with the latest react-jsonschema-form: https://github.com/adam-beck/react-jsonschema-form/tree/investigate-2039-part2

**Comment by lucataglia** [comment]
Is there any news about that bug ?
