### ISSUE TITLE
Is it possible to manually change value of custom (AntD) SelectWidget?

### ISSUE THREAD

**Issue by grgicpetar** [rjsf-team/react-jsonschema-form#2041]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I am trying to change the value of my custom SelectWidget depending on some condition in useEffect() hook. but the app keeps crashing.

### Steps to Reproduce

1. I define the form element in schema
```
"select-field": {
        "title": "Select field",
        "type": "string",
        "enum": ["yes", "no"],
        "enumNames": ["Yes", "no"],
        "optional": false
},
```

and uiSchema

```
"select-field": {
      "ui:widget": "DependingSelectWidget",
      "ui:options": {
        "dependsOn": "input-field"
      }
    },
```

This is the widget (made with Ant Design):

```
const DependingSelectWidget = (props: any) => {

  const { condition } = useDynamicOptions();

  useEffect(() => {
    if (props.options.dependsOn === "input-field" && condition) {
      props.onChange("yes);
    }
  }, [props, condition]);

  return (
    <Select
      onChange={(event) => {
        props.onChange(event);
      }}
      value={props.value}
    >
      {props.options.enumOptions.map((enumItem: any) => {
        return (
          <Option key={enumItem.value} value={enumItem.value}>
            {enumItem.label}
          </Option>
        );
      })}
    </Select>
  );
};
```

But when the condition in useEffect() is actually met, the app crashes. I am not sure if it has to do something with enum values, because for a normal string input widget I was able to do the same without errors.

#### Expected behavior

The value of DependingSelectWidget should change accordingly.

#### Actual behavior

The app crashes.

### Version
 "@rjsf/antd": "^2.2.0",
 "@rjsf/core": "^2.2.1",

**Comment by heath-freenome** [comment]
@grgicpetar First of all, does this still happen in 5.x? Second of all, how is it crashing? If it is inside of your custom widget then we really can't do much for you.
