### ISSUE TITLE
Material-UI theme problem with value 0 (zero) in UpDownWidget

### ISSUE THREAD

**Issue by cstim** [rjsf-team/react-jsonschema-form#2042]
Dear authors, the "initial 0 number" problem was fixed recently in #1795 except that the fix there didn't catch the UpDownWidget. That one still tests for truthy here: https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/material-ui/src/UpDownWidget/UpDownWidget.tsx#L43 and that line needs a similar change into `value={value || (value === 0) ? value : ''}` 
Could you fix that one, too, please? Thanks a lot!

### Steps to Reproduce

[playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJudW1iZXIiOjAsImludGVnZXIiOjAsIm51bWJlckVudW0iOjIsImludGVnZXJSYW5nZSI6NDIsImludGVnZXJSYW5nZVN0ZXBzIjo4MH0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwidGl0bGUiOiJOdW1iZXIgZmllbGRzICYgd2lkZ2V0cyIsInByb3BlcnRpZXMiOnsibnVtYmVyIjp7InRpdGxlIjoiTnVtYmVyIiwidHlwZSI6Im51bWJlciJ9LCJpbnRlZ2VyIjp7InRpdGxlIjoiSW50ZWdlciIsInR5cGUiOiJpbnRlZ2VyIn0sIm51bWJlckVudW0iOnsidHlwZSI6Im51bWJlciIsInRpdGxlIjoiTnVtYmVyIGVudW0iLCJlbnVtIjpbMSwyLDNdfSwibnVtYmVyRW51bVJhZGlvIjp7InR5cGUiOiJudW1iZXIiLCJ0aXRsZSI6Ik51bWJlciBlbnVtIiwiZW51bSI6WzEsMiwzXX0sImludGVnZXJSYW5nZSI6eyJ0aXRsZSI6IkludGVnZXIgcmFuZ2UiLCJ0eXBlIjoiaW50ZWdlciIsIm1pbmltdW0iOjQyLCJtYXhpbXVtIjoxMDB9LCJpbnRlZ2VyUmFuZ2VTdGVwcyI6eyJ0aXRsZSI6IkludGVnZXIgcmFuZ2UgKGJ5IDEwKSIsInR5cGUiOiJpbnRlZ2VyIiwibWluaW11bSI6NTAsIm1heGltdW0iOjEwMCwibXVsdGlwbGVPZiI6MTB9fX0sInVpU2NoZW1hIjp7ImludGVnZXIiOnsidWk6d2lkZ2V0IjoidXBkb3duIn0sIm51bWJlckVudW1SYWRpbyI6eyJ1aTp3aWRnZXQiOiJyYWRpbyIsInVpOm9wdGlvbnMiOnsiaW5saW5lIjp0cnVlfX0sImludGVnZXJSYW5nZSI6eyJ1aTp3aWRnZXQiOiJyYW5nZSJ9LCJpbnRlZ2VyUmFuZ2VTdGVwcyI6eyJ1aTp3aWRnZXQiOiJyYW5nZSJ9fSwidGhlbWUiOiJtYXRlcmlhbC11aSIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)  where the "Number" field correctly has the zero, but the "Integer" field is blank where we would have expected the zero, too.

#### Expected behavior

Both "Number" and "Integer" field should show the value zero `0`

#### Actual behavior

The "Integer" field is blank

### Version

Current playground

**Comment by epicfaace** [comment]
@cstim thanks for reporting -- would you be able to send a patch to fix this?

**Comment by cstim** [comment]
@epicfaace well... the proposed fix consists literally of changing file packages/material-ui/src/UpDownWidget/UpDownWidget.tsx line 43 from 
`value={value ? value : ''}`
into
`value={value || (value === 0) ? value : ''}`
i.e. extending the condition by the extra or-value. What else would you like to receive for such a change? Thanks!

**Comment by epicfaace** [comment]
That's it -- additionally, perhaps a test to ensure this behavior doesn't regress in the future.

**Comment by wegry** [comment]
This is still a problem in the `@rjsf/bootstrap-4@2.4.0` package.
