### ISSUE TITLE
[Bootstrap-4] Warning: React does not recognize the `pId` prop on a DOM element.

### ISSUE THREAD

**Issue by Pavinati** [rjsf-team/react-jsonschema-form#2043]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
Rendering a form that contains array items with the bootstrap 4 theme generates the warning
```
Warning: React does not recognize the `pId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `pid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
the responsible line of code is in the icon library
https://github.com/rjsf-team/react-jsonschema-form/blob/af9842771aa95d280e5927adddc50402ae06681f/packages/bootstrap-4/src/AddButton/AddButton.tsx#L9

### Steps to Reproduce
You can see the wrong attributes in the svg item from the playground
1. open https://rjsf-team.github.io/react-jsonschema-form/
2. select theme "bootstrap-4"
3. select "array"
4. inspect the add button "+" icon and see the pId attribute
There will be no warning in the playground, probably suppressed by build configuration

#### Expected behavior

No warnings thrown

#### Actual behavior

A warning is thrown

### Version

@rjsf/bootstrap-4: 2.3.0

**Comment by Pavinati** [comment]
I was looking in the ui:schema for an option to override the addButton, but couldn't find any

**Comment by Xtremilicious** [comment]
@epicfaace Fixed this problem in #2046 
Kindly have a look :)

**Comment by sanket-work** [comment]
Is this fixed ? I am still facing the same issue. All my packages are updated.
I still see the pId on the icon

**Comment by epicfaace** [comment]
It will be released in the new version, which hasn't come out yet.
