### ISSUE TITLE
When `type` is an array, child id schema is lost

### ISSUE THREAD

**Issue by Vestride** [rjsf-team/react-jsonschema-form#2044]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

[Playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJuYW1lcyI6W119LCJzY2hlbWEiOnsidGl0bGUiOiJQZW9wbGUiLCJ0eXBlIjpbIm9iamVjdCJdLCJwcm9wZXJ0aWVzIjp7Im5hbWVzIjp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmcifX19fSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19). Notice both "People" and "names" have the same `id` attribute in the DOM.

### Description

If a parent schema has `"type": ["object", "null"]`, the `idSchema` passed to the child `<SchemaField>` is an empty object `{}`. Duplicate `id` attributes now exist.

### Steps to Reproduce

Schema:

```json
{
  "title": "People",
  "type": ["object", "null"],
  "properties": {
    "names": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}
```

If `"type"` is changed to `"object"`, the issue does not occur. The issue also happens when the `names` property is an object with a title instead of an array.

#### Expected behavior

The `names` title should not have the same id (`root__title`) as the `People` title.

#### Actual behavior

The `names` title has the same id (`root__title`) as the `People` title.

### Version

2.3.0

---

Changing this line to use `getSchemaType` "fixed" the issue for me locally, but one of the tests fails with that change.

https://github.com/rjsf-team/react-jsonschema-form/blob/af9842771aa95d280e5927adddc50402ae06681f/packages/core/src/utils.js#L1002

**Comment by christoz** [comment]
We have the same issue, thanks for opening this ticket

**Comment by heath-freenome** [comment]
Hmmm, This is still happening in 5.5.0
