### ISSUE TITLE
Inconsistant behaviour in Array field for ui:widget hidden

### ISSUE THREAD

**Issue by mahesh-kedari** [rjsf-team/react-jsonschema-form#2051]
### Prerequisites

- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
I'm trying to hide Array field using ui:widget as hidden. It is working as expected in case of default theme. But not working for Material-ui theme. I know as per the documentation, only basic datatypes are supported for ui:widget = hidden, but if its working for default theme, I think it should work for other themes as well. If not, is there any workaround available to achieve this behaviour?

Reference: [Default Theme ](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ2ZXJzaW9uIjoiMS4wIiwiY29tcGF0aWJsZV9kZXZpY2VfdHlwZSI6ImlDYXN0U2Vuc2UiLCJyZXZpc2lvbiI6MSwicHJvZmlsZV9vYmplY3RzIjp7ImNsb3VkX2NvbmZpZ3VyYXRpb24iOnsiZGF0YV91cGRhdGVfaW50ZXJ2YWxfdGltZV9zZWMiOjM2MDB9fX0sInNjaGVtYSI6eyIkc2NoZW1hIjoiaHR0cDovL2pzb24tc2NoZW1hLm9yZy9kcmFmdC0wNy9zY2hlbWEiLCIkaWQiOiJodHRwOi8vZXhhbXBsZS5jb20vaUNhc3RTZW5zZS1kZXZpY2UtcHJvZmlsZS1zY2hlbWEuanNvbiIsInR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6ImlDYXN0U2Vuc2UgZGV2aWNlIHByb2ZpbGUgc2NoZW1hIiwiZGVzY3JpcHRpb24iOiJEZXNjcmliZXMgcHJvcGVydGllcyBmb3IgdGhlIGlDYXN0U2Vuc2UgZGV2aWNlIHByb2ZpbGUganNvbiIsInJlcXVpcmVkIjpbIm5hbWUiLCJ2ZXJzaW9uIiwiY29tcGF0aWJsZV9kZXZpY2VfdHlwZSIsImRlc2NyaXB0aW9uIiwicHJvZHVjdF9tb2RlbCIsInByb2R1Y3RfbWFrZSIsInByb2R1Y3RfY2F0ZWdvcnkiLCJwcm9maWxlX29iamVjdHMiXSwicHJvcGVydGllcyI6eyJuYW1lIjp7IiRpZCI6IiMvcHJvcGVydGllcy9uYW1lIiwidGl0bGUiOiJQcm9maWxlIE5hbWUiLCJkZXNjcmlwdGlvbiI6IlVuaXF1ZSBuYW1lIGZvciB0aGUgcHJvZmlsZSIsInBhdHRlcm4iOiJeKD8hIClbQS1aYS16MC05IF8sLV17MSw2NH0oPzwhICkkIiwidHlwZSI6InN0cmluZyJ9LCJ2ZXJzaW9uIjp7IiRpZCI6IiMvcHJvcGVydGllcy92ZXJzaW9uIiwidGl0bGUiOiJWZXJzaW9uIiwicGF0dGVybiI6Il5bMC05Ll17Myx9JCIsInJlYWRPbmx5Ijp0cnVlLCJ0eXBlIjoic3RyaW5nIiwiY29uc3QiOiIxLjAiLCJkZWZhdWx0IjoiMS4wIn0sImNvbXBhdGlibGVfZGV2aWNlX3R5cGUiOnsiJGlkIjoiIy9wcm9wZXJ0aWVzL2NvbXBhdGlibGVfZGV2aWNlX3R5cGUiLCJ0aXRsZSI6Ik1vZGVsIiwiY29uc3QiOiJpQ2FzdFNlbnNlIiwidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJpQ2FzdFNlbnNlIiwicmVhZE9ubHkiOnRydWV9LCJyZXZpc2lvbiI6eyIkaWQiOiIjL3Byb3BlcnRpZXMvcmV2aXNpb24iLCJ0aXRsZSI6IlJldmlzaW9uIiwicmVhZE9ubHkiOnRydWUsInR5cGUiOiJpbnRlZ2VyIiwiZGVmYXVsdCI6MX0sImRlc2NyaXB0aW9uIjp7IiRpZCI6IiMvcHJvcGVydGllcy9kZXNjcmlwdGlvbiIsInRpdGxlIjoiUHJvZmlsZSBEZXNjcmlwdGlvbiIsInBhdHRlcm4iOiJeKD8hIClbQS1aYS16MC05IF8sLV17MSw2NH0oPzwhICkkIiwidHlwZSI6InN0cmluZyJ9LCJwcm9kdWN0X2NhdGVnb3J5Ijp7IiRpZCI6IiMvcHJvcGVydGllcy9wcm9kdWN0X2NhdGVnb3J5IiwidGl0bGUiOiJQcm9kdWN0IENhdGVnb3J5IiwicGF0dGVybiI6Il4oPyEgKVtBLVphLXowLTkgXywtXXsxLDY0fSg/PCEgKSQiLCJ0eXBlIjoic3RyaW5nIn0sInByb2R1Y3RfbW9kZWwiOnsiJGlkIjoiIy9wcm9wZXJ0aWVzL3Byb2R1Y3RfbW9kZWwiLCJ0aXRsZSI6IlByb2R1Y3QgTW9kZWwiLCJwYXR0ZXJuIjoiXig/ISApW0EtWmEtejAtOSBfLC1dezEsNjR9KD88ISApJCIsInR5cGUiOiJzdHJpbmcifSwicHJvZHVjdF9tYWtlIjp7IiRpZCI6IiMvcHJvcGVydGllcy9wcm9kdWN0X21ha2UiLCJ0aXRsZSI6IlByb2R1Y3QgTWFrZSIsInBhdHRlcm4iOiJeKD8hIClbQS1aYS16MC05IF8sLV17MSw2NH0oPzwhICkkIiwidHlwZSI6InN0cmluZyJ9LCJwcm9kdWN0X2FkZGl0aW9uYWxfaW5mbyI6eyIkaWQiOiIjL3Byb3BlcnRpZXMvcHJvZHVjdF9hZGRpdGlvbmFsX2luZm8iLCJ0aXRsZSI6IlByb2R1Y3QgQWRkaXRpb25hbCBpbmZvIiwicGF0dGVybiI6Il4kfF4oPyEgKVtBLVphLXowLTkgXywtXXsxLDY0fSg/PCEgKSQiLCJ0eXBlIjoic3RyaW5nIn0sInByb2ZpbGVfb2JqZWN0cyI6eyIkaWQiOiIjL3Byb3BlcnRpZXMvcHJvZmlsZV9vYmplY3RzIiwidGl0bGUiOiIiLCJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsic2Vuc29yX2NvbmZpZ3VyYXRpb24iLCJjbG91ZF9jb25maWd1cmF0aW9uIl0sInByb3BlcnRpZXMiOnsic2Vuc29yX2NvbmZpZ3VyYXRpb24iOnsidGl0bGUiOiIiLCIkaWQiOiIjL3Byb3BlcnRpZXMvcHJvZmlsZV9vYmplY3RzL3Byb3BlcnRpZXMvc2Vuc29yX2NvbmZpZ3VyYXRpb24iLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyIkaWQiOiIjL3Byb3BlcnRpZXMvcHJvZmlsZV9vYmplY3RzL3Byb3BlcnRpZXMvc2Vuc29yX2NvbmZpZ3VyYXRpb24vaXRlbXMiLCJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsicG9ydCIsImNvbmZpZyJdLCJwcm9wZXJ0aWVzIjp7InBvcnQiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiU05TX0FDQ0VMRVJPTUVURVIiLCJTTlNfTUlDUk9QSE9ORSIsIlNOU19BTkFMT0dfSU5QVVQiLCJTTlNfVEVNUF9TVVJGQUNFIiwiU05TX0hVTUlESVRZIiwiU05TX1RFTVBfRU5WIiwiU05TX0JBUk9NRVRFUiIsIlNOU19DU1EiLCJTTlNfUlNSUCIsIlNOU19TSU5SIiwiU05TX1JTUlEiLCJTTlNfQkFORCIsIlNOU19TSU1fU0xPVCIsIlNOU19QT1NUX1JFUV9ET05FIiwiU05TX1BPU1RfUkVRX1NVQ0MiLCJTTlNfUFdSX1NVUFBMWSJdfSwiY29uZmlnIjp7InR5cGUiOiJvYmplY3QiLCJyZXF1aXJlZCI6WyJzZW5zb3JfdHlwZSIsImNvbW1vbl9wcm9wZXJ0aWVzIiwiZGF0YXBvaW50cyIsIm1vZHVsZV9tZXRhIl0sInByb3BlcnRpZXMiOnsic2Vuc29yX3R5cGUiOnsidGl0bGUiOiJTZW5zb3IgVHlwZSIsInR5cGUiOiJzdHJpbmciLCJlbnVtIjpbInNuc19hY2NlbGVyb21ldGVyIiwic25zX21pY3JvcGhvbmUiLCJzbnNfYW5hbG9nX2lucHV0Iiwic25zX3RlbXBlcmF0dXJlIiwic25zX2h1bWlkaXR5Iiwic25zX3ByZXNzdXJlIiwic25zX2NzcSIsInNuc19yc3JwIiwic25zX3NpbnIiLCJzbnNfcnNycSIsInNuc19iYW5kIiwic25zX3NpbV9zbG90Iiwic25zX3Bvc3RfcmVxX2RvbmUiLCJzbnNfcG9zdF9yZXFfc3VjYyIsInNuc19iYXR0ZXJ5Il0sImRlZmF1bHQiOiJzbnNfYWNjZWxlcm9tZXRlciJ9fX19fX0sImNsb3VkX2NvbmZpZ3VyYXRpb24iOnsidGl0bGUiOiJDbG91ZCBDb25maWd1cmF0aW9uIiwiJGlkIjoiIy9wcm9wZXJ0aWVzL3Byb2ZpbGVfb2JqZWN0cy9wcm9wZXJ0aWVzL2Nsb3VkX2NvbmZpZ3VyYXRpb24iLCJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsiZGF0YV91cGRhdGVfaW50ZXJ2YWxfdGltZV9zZWMiLCJzdGFydF90aW1lIl0sInByb3BlcnRpZXMiOnsiZGF0YV91cGRhdGVfaW50ZXJ2YWxfdGltZV9zZWMiOnsidGl0bGUiOiJEYXRhIHVwZGF0ZSBpbnRlcnZhbCAoc2VjKSIsIiRpZCI6IiMvcHJvcGVydGllcy9wcm9maWxlX29iamVjdHMvcHJvcGVydGllcy9jbG91ZF9jb25maWd1cmF0aW9uL3Byb3BlcnRpZXMvZGF0YV91cGRhdGVfaW50ZXJ2YWxfdGltZV9zZWMiLCJ0eXBlIjoiaW50ZWdlciIsImRlZmF1bHQiOjM2MDAsIm1pbmltdW0iOjAsIm1heGltdW0iOjg2NDAwfSwic3RhcnRfdGltZSI6eyJ0aXRsZSI6IlN0YXJ0IFRpbWUiLCJkZXNjcmlwdGlvbiI6IkZvcm1hdCBoaDptbSBBTS9QTSIsIiRpZCI6IiMvcHJvcGVydGllcy9wcm9maWxlX29iamVjdHMvcHJvcGVydGllcy9jbG91ZF9jb25maWd1cmF0aW9uL3Byb3BlcnRpZXMvc3RhcnRfdGltZSIsInR5cGUiOiJzdHJpbmcifX0sImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjpmYWxzZX19LCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2V9fSwicG9ydF92YWxpZGF0b3IiOnRydWUsImRhdGFwb2ludF9uYW1lX3ZhbGlkYXRvciI6dHJ1ZSwic2Vuc29yX2NvbmZpZ192YWxpZGF0b3IiOnRydWUsImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjpmYWxzZX0sInVpU2NoZW1hIjp7InByb2ZpbGVfb2JqZWN0cyI6eyJ1aTp3aWRnZXQiOiJoaWRkZW4ifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

**Comment by ri0ter** [comment]
The [docs](https://react-jsonschema-form.readthedocs.io/en/latest/usage/widgets/#hidden-widgets) are saying that hidden widgets are not supported for arrays.
But you could do it by overriding ArrayFieldTemplate in uiSchema, for eg. like that:
```
const uiSchema = {
    someArrayField: { 'ui:ArrayFieldTemplate': () => null },
}
```

**Comment by Kaldolol** [comment]
@ri0ter Thank you very much for this tip, it's exactly what I wanted to hide array fields !
