### ISSUE TITLE
Json Basic form cant edit form displayed in read only mode

### ISSUE THREAD

**Issue by Selvi-winvest** [rjsf-team/react-jsonschema-form#2053]
Hi All,
Am new to react started with react-app..
installed npm install react-json-form-schema --save

Code:
import Form from "react-jsonschema-form";
const schema = {type: "string"};
const uiSchema = {
  "ui:options": {
    label: false
  }
};
<Form schema={schema} uiSchema={uiSchema}/>

Form is displaying with Readonly format.. Cant edit or enter.
Can anyone please help me what am missing...

**Comment by Selvi-winvest** [comment]
Errors in console 
Form.js:21 Uncaught TypeError: Cannot read property 'Component' of undefined
    at Module.<anonymous> (Form.js:21)
    at t (bootstrap:19)
    at bootstrap:83
    at react-jsonschema-form.js:1
    at universalModuleDefinition:9
    at universalModuleDefinition:1

**Comment by adam-beck** [comment]
Seems to be working here: https://codepen.io/adam-beck/pen/WNwLrPR

Need more context to your specific problem.
