### ISSUE TITLE
BUG: Material-ui - field type `data-url`

### ISSUE THREAD

**Issue by hoetmaaiers** [rjsf-team/react-jsonschema-form#2054]
### Prerequisites

- [x ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I am using the material-ui theme, which I love to have available.
When defining a data-url field in Material-ui all form values are reset when selecting a file. This a bug I am afraid.

### Version

├─ @rjsf/core@2.3.0
└─ @rjsf/material-ui@2.3.0

**Comment by adam-beck** [comment]
Would you provide a playground link? You checked the box but didn't provide one :)

**Comment by hoetmaaiers** [comment]
I managed to solve this one..
