### ISSUE TITLE
Disabling Form Clears Its Data

### ISSUE THREAD

**Issue by stvhanna** [rjsf-team/react-jsonschema-form#2056]
### Prerequisites
- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
Disabling the form on submit, clears the form data.

### Steps to Reproduce
https://codesandbox.io/s/solitary-meadow-dbvpn?file=/src/App.js
1. Type text into the input box
2. Hit the submit button
3. The typed text in the input is gone

![Screen Shot 2020-09-17 at 10 52 23 PM](https://user-images.githubusercontent.com/507482/93550002-84387a00-f938-11ea-9d0e-c9bb57aa3d8c.png)
![Screen Shot 2020-09-17 at 10 52 34 PM](https://user-images.githubusercontent.com/507482/93550012-88fd2e00-f938-11ea-9620-08e44760a8ba.png)

#### Expected behavior
Form data should not be cleared when the form is disabled.

#### Actual behavior
The form data is cleared when the form is disabled.

### Version
2.4.0

**Comment by stvhanna** [comment]
@epicfaace @agustin107 any ideas what's going on here? Any help would be greatly appreciated!

**Comment by ronny-rentner** [comment]
@stvhanna After you submit, because you change a state variable, you rerender the form and you have not saved the formData, so the form gets rendered with the initial data you provide.
