### ISSUE TITLE
Material-UI TextWidget does not respect the inputType in uiSchema

### ISSUE THREAD

**Issue by heath-freenome** [rjsf-team/react-jsonschema-form#2057]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Using the [stock playground](https://rjsf-team.github.io/react-jsonschema-form/), you can see that for the default theme, the telephone input is of `type="tel"`. Here's the excerpt from the generated html:
```
<div class="form-group field field-string">
  <label class="control-label" for="root_telephone">Telephone</label>
  <input class="form-control" id="root_telephone" label="Telephone" placeholder="" type="tel" value="">
</div>
```

When you switch to the material-ui theme, that type is lost. Here's the excerpt from the generated html:
```
<div class="MuiInputBase-root MuiInput-root MuiInput-underline MuiInputBase-formControl MuiInput-formControl">
  <input aria-invalid="false" id="root_telephone" placeholder="" type="string" class="MuiInputBase-input MuiInput-input" value="">
</div>
```

### Steps to Reproduce

1. Go to the [stock playground](https://rjsf-team.github.io/react-jsonschema-form/)
2. View the source for the `Telephone` input and see the `type="tel"` on it
3. Switch the theme to `material-ui`
4. View the source for the `Telephone` input and DO NOT see the `type="tel"` on it.

#### Expected behavior

The `material-ui` `TextWidget` will respect the `inputType` specified in the `uiSchema` just like the default theme

#### Actual behavior

The `material-ui` `TextWidget` ignores the `inputType`

### Version
    "@rjsf/core": "^2.4.0",
    "@rjsf/material-ui": "^2.4.0",

**Comment by heath-freenome** [comment]
Actually, only the default theme and the `antd` theme respect the `inputType`

**Comment by mdornseif** [comment]
Did https://github.com/rjsf-team/react-jsonschema-form/pull/2215 fix that?

**Comment by heath-freenome** [comment]
No... That fix does not respect `inputType` on the UI:schema. You can tell by simply using the stock playground per my steps above.

**Comment by Jisay** [comment]
Same with bootstrap4 theme

**Comment by heath-freenome** [comment]
Fixed in v5 beta
