### ISSUE TITLE
[bootstrap-4] withTheme additional customization

### ISSUE THREAD

**Issue by Pavinati** [rjsf-team/react-jsonschema-form#2058]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

The documentation describes the use of `withTheme` for the customization of the default theme.
Is there any plan to have something similar for bootstrap-4 too?
Say for example i want to use BS4 as default theme, but i want to change the standard `<input>` that comes with it.
Ideally i could use

```
import { withTheme } from '@rjsf/bootstrap-4';

MyForm = withTheme({ /* my customization object */ });
```

**Comment by jacqueswho** [comment]
There is a bootstrap-4 theme.

**Comment by Pavinati** [comment]
i was already using the bootstrap 4 theme, but it is missing features and I need some extra customization, that's why we I wanted to customize the already existing bootstrap 4 implementation
see https://github.com/rjsf-team/react-jsonschema-form/issues/1962 https://github.com/rjsf-team/react-jsonschema-form/issues/1963

**Comment by heath-freenome** [comment]
Fixed in the v5 beta, see the [5.x migration guide](https://react-jsonschema-form.readthedocs.io/en/latest/5.x%20upgrade%20guide/)
