### ISSUE TITLE
Set default as current date in Date Field

### ISSUE THREAD

**Issue by Selvi-winvest** [rjsf-team/react-jsonschema-form#2063]
Hi,

How to set the default value as current date  in date field..

This is not working
date: { type: 'string', format: "date", default: new Date() title: " Date"}

**Comment by ronny-rentner** [comment]
Use new Date().toString() to make it work

**Comment by Selvi-winvest** [comment]
date: { type: 'string', format: "date", default: Date().toString(), title: "Date",},

Its not working...

**Comment by ronny-rentner** [comment]
new Date().toString()

not just Date().toString()

**Comment by Selvi-winvest** [comment]
Yes , i did but now working

**Comment by adam-beck** [comment]
You'll need to put it into the format `YYYY-MM-DD` which is what that control understands. 

For example: `new Date().toISOString().slice(0,10)`

Here is a codepen: https://codepen.io/adam-beck/pen/bGpOEpG?editors=1111

**Comment by Selvi-winvest** [comment]
Thank you... it works

**Comment by simmo15** [comment]
I AM FACING THE SAME ISSUE BUT STILL NOT ABLE TO SOLVE IT BY USING THE ABOVE WAY
