### ISSUE TITLE
Is there a way to set TitleField inside the ui schema or per field?

### ISSUE THREAD

**Issue by eugenefedoto** [rjsf-team/react-jsonschema-form#2064]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I want to be able to set the layout of the title for each field separately, instead of the current global way that uses the TitleField prop to affect all fields. I'm relying on json files, so setting by FieldTemplate in the ui schema isn't possible (sidenote: there doesn't seem to be a prop for ui field templates like the widgets props).  Does something like this exist?

**Comment by ronny-rentner** [comment]
I'm not sure if i understand correctly what you're trying to do but to have a custom title field for each title, you need to override https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/fields/ObjectField.js and/or https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/fields/ArrayField.js and add logic to do this.
