### ISSUE TITLE
Dynamic Dropdowns when using an array

### ISSUE THREAD

**Issue by upheads** [rjsf-team/react-jsonschema-form#2066]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Another conditional dropdown question.  This time, I have an array of objects.  These objects have two dropdowns and I want one to depend on the other.  I have tried to get this to work using 1) react-jsonschema-form-conditional and 2) a CustomFieldTemplate.  For both options the problems seem to roughly be the same: changing the dropdown values means changing the value in the schema, but since all objects/fields share the same schema, all objects will be affected, e.g. if I choose US for the first dropdown of the first array element, it will change to use US states for the second dropdown of all the other array elements.

I also looked at [this issue](https://github.com/rjsf-team/react-jsonschema-form/issues/1472) asking a similar question, but the sample does not use an array in the schema and I think it would have the same problem in this scenario.

### Steps to Reproduce

Example schema:

```
{
  "schema": {
    "definitions": {
      "foo": {
        "type": "object",
        "properties": {
          "country": {
            "type": "string",
            "enum": [
              "US",
              "CA",
            ]
          },
          "stateProvince": {
            "type": "string",
            "enum": [
            ]
          },
        }
      }
    },
    "title": "Example",
    "type": "object",
    "properties": {
      "payload": {
        "type": "array",
        "items": { "$ref": "#/definitions/foo" }
      }
    }
  },
  "uiSchema": {
    "payload": {
      "ui:options": {
        "addable": true,
        "orderable": false,
        "removable": true
      }
    }
  }
}

```

#### Expected behavior

Ideally, the user can add multiple `foos`.  For each `foo`, they can select either `US` or `CA` as the `country` and this should populate the second dropdown with either a list of states or provinces as required.  Choosing `US` for the first `foo` shouldn't affect the states/provinces list for the other `foos`.

#### Actual behavior

Using react-jsonschema-form-conditional, I set `schema.definitions.foo.stateProvince.enum` based on `country`, but this changes the values for all elements of the array.  I also tried creating [an ObjectFieldTemplate](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-templates/#objectfieldtemplate) and modifying `props.schema.properties.stateProvince.enum`, but 1) the form does not update when `props` is modified in the OFT and 2) I think there will still be the problem of shared schema, because when I add a new element, then the new element has the values is `stateProvince` I would've expected from the previous element.

### Version

2.0.0-alpha.1

**Comment by nickgros** [comment]
This behavior should be possible in RJSF v5 since conditional (if/then/else) support was added in v4.
