### ISSUE TITLE
Can use Material UI's TextareaAutosize?

### ISSUE THREAD

**Issue by stvhanna** [rjsf-team/react-jsonschema-form#2068]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
Is is possible to use Material UI's `TextareaAutosize` with `react-jsonschema-form`? If so how would this be done using `ui:widget`?

I tried the follow but that did not work:
```
import { TextareaAutosize } from '@material-ui/core';
...
autoGrowingTextarea: {
    "ui:widget": "TextareaAutosize"
}
```

### Version
2.4.0

**Comment by adam-beck** [comment]
Yes you can

https://codesandbox.io/s/optimistic-ptolemy-9iqy1?file=/src/App.js

**Comment by stvhanna** [comment]
@adam-beck Thanks for the reply, your codesandbox isn't loading.

**Comment by adam-beck** [comment]
Sorry. Try this: https://codesandbox.io/s/modest-frog-qmibb?file=/src/App.js

I must've deleted the other one.

**Comment by adam-beck** [comment]
And for some reason I'm getting "Too much recursion" errors now.
