### ISSUE TITLE
oneOf not selecting correct option for objects with the same property keys but different default, read-only values

### ISSUE THREAD

**Issue by zmagauina-fn** [rjsf-team/react-jsonschema-form#2069]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

A oneOf schema with two objects with the same property but different read-only, default values won't correctly select the option with the matching value for the key when passed a formData, and instead will match the first option with the correct property keys (both the property keys are the same).

### Steps to Reproduce

In this [playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJsb3JlbSI6ImZpcnN0In0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0Iiwib25lT2YiOlt7InByb3BlcnRpZXMiOnsibG9yZW0iOnsidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJmaXJzdCIsInJlYWRPbmx5Ijp0cnVlfX0sInJlcXVpcmVkIjpbImxvcmVtIl19LHsicHJvcGVydGllcyI6eyJsb3JlbSI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6InNlY29uZCIsInJlYWRPbmx5Ijp0cnVlfX0sInJlcXVpcmVkIjpbImxvcmVtIl19XX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==), you can see that the two oneOf options both have the same properties (one "lorem" key), with different read-only, default values.
2. If you select the second option, it will update formData to `{ "lorem": "second" }`. If you select the first option, formData becomes `{ "lorem": "first" }`. This is the expected behavior.
3. If you now change formData to `{ "lorem": "second" }`, it will keep the selector on the first option, but change the name to "second".

#### Expected behavior

Per the example above, I'm trying to initialize the selector on the second option using the formData value. 

I have data objects with the same keys but different default, read-only values that represent different options. I want to be able to initialize the selector at the correct option based on the formData passed in.

#### Actual behavior

The `isValid` check inside the `getMatchingOption` method in `utils` will return true when comparing the following schema:
```
{
    "properties": {
        "lorem": {
            "type": "string",
            "default": "first",
            "readOnly": true
        }
    },
    "required": [
        "lorem"
    ]
}
```
and formData:
```
{
  "lorem": "second"
}
```
Even though the it's a default, read-only value and the values don't match.

### Version
```
"@rjsf/core": "^2.4.0"
```

**Comment by yair-dana** [comment]
I had the same problem.
after I used 'const' instead 'readonly' it works

`const: 'second'`
