### ISSUE TITLE
[Help] Show form fields inline instead of vertically stacked

### ISSUE THREAD

**Issue by ashvin777** [rjsf-team/react-jsonschema-form#2070]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Currently, all the form fields are shown on top of each other. I couldn't find any configuration to change it to support inline field.
![image](https://user-images.githubusercontent.com/8143154/94109920-5b941100-fe5f-11ea-8f45-546396075bf0.png)

#### Expected behavior
![image](https://user-images.githubusercontent.com/8143154/94110090-af065f00-fe5f-11ea-9721-ca2d6e7e33dd.png)

#### Actual behavior
No way to inline couple fields.

### Version
Latest (https://rjsf-team.github.io/react-jsonschema-form/)

**Comment by bdaenen** [comment]
You can achieve this by overwriting the `ObjectFieldTemplate` and creating a new ui prop `ui:grid`.
Using bootstrap 4 as an example, your ui prop could look something like

```
"ui:grid": [
    {
        "firstName": 4,
        "lastName": 8
    },
    {
        "companyName": 12
    }
],
```

Where each object indicates a row, and every key in the object maps to the name of the field. To make it responsive you could even use objects with the bootstrap xs/sm/md/lg/xl keys instead of numbers, to determine the size per breakpoint.

In the `ObjectFieldTemplate` you would then check for this prop on the uiSchema, and if it is present loop over the entries and render the rows and cols with the correct props for that size.

You can access the original content through `this.props.properties[i].content`, which also has a `.name` which you can use to map it to the `ui:grid` and get the correct width.

We have a working implementation of this, but the code is closed-source and not owned by me, so unfortunately I cannot share it any shape or form.

**Comment by jonra1993** [comment]
Hello @ashvin777 I was able to do it using materil ui ObjectFieldTemplate here you can find code:

`  const schema = {
    type: "object",
    properties: {
      firstName: {
        type: "string"
      },
      lastName: {
        type: "string"
      },
      id: {
        type: "number"
      },
      email: {
        type: "string"
      },
      phone: {
        type: "number"
      },
      businessLine: {
        type: "string"
      },
      role: {
        type: "string"
      },
      state: {
        type: "string"
      },
      office: {
        type: "string"
      },
    }
  };
  function ObjectFieldTemplate(props) {
    return (
      <Grid container spacing={3}>
        {props.properties.map(element =>
          <Grid item md={6} xs={12}>{element.content}</Grid>
        )}
      </Grid>
    );
  }

 <Form schema={schema} ObjectFieldTemplate={ObjectFieldTemplate} />
`

![image](https://user-images.githubusercontent.com/23468720/95811338-ae335100-0cd8-11eb-8b81-69e09a1f41af.png)

**Comment by rohith94** [comment]
Is there a way to mix-match the input layout ..?

> Few fields as vertical and few as horizontal in one form .?l

**Comment by sparmboy** [comment]
Building on the answers above, here's a way for doing this using Material UI grids (in Typescript):

Define a UI schema such as this (where each entry in the array is a row, and the numbers against the field are the column lengths out of 12):

```
const uiSchema: UiSchema = {
    "ui:grid": [
      {
        "name": 6,
        "age": 6
      },
      {
        "address": 4,
        "favouriteWayToDie": 8
      }
    ],
  };
```

and a react component to execute this grid layout:

```
const MuiGridLayoutTemplate = (props: ObjectFieldTemplateProps) => {
  return <Grid
    container
    direction="column"
    justify="space-between"
    alignItems="center"
  >
    {props.uiSchema['ui:grid'].map(row =>
      <Grid
        item
        container
        direction="row"
        justify="space-between"
        alignItems="center"
        spacing={4}
      >
        {Object.keys(row).map(fieldName =>
        <Grid item xs={row[fieldName]}>
          {props.properties.find(p=>p.name===fieldName).content}
        </Grid>)}
      </Grid>)}
  </Grid>
}
```

and then your form:

```
<Form
    uiSchema={uiSchema}
    ObjectFieldTemplate={MuiGridLayoutTemplate}
.
.
.
/>
```

**Comment by rohith94** [comment]
> Hello @ashvin777 I was able to do it using material ui ObjectFieldTemplate here you can find code:
> 
> ![image](https://user-images.githubusercontent.com/23468720/95811338-ae335100-0cd8-11eb-8b81-69e09a1f41af.png)
> 
> ` const schema = {
> type: "object",
> properties: {
> firstName: {
> type: "string"
> },
> lastName: {
> type: "string"
> }
> }
> };
> 
> `
> function ObjectFieldTemplate(props) {
> return (
> 
> {props.properties.map(element =>
> {element.content}
> )}
> 
> );
> }
> 
> ```
>     <Form schema={schema} ObjectFieldTemplate={ObjectFieldTemplate} />
> ```
> 
> `

can u pass the working code in any sandbox online .?

**Comment by newt10** [comment]
This can be achieved using the custom templates for fields, array and objects. Given that there is a workaround, I am labeling this as a discussion rather than an issue. @ashvin777 Please close this issue once you have been able to get the desired help.
