### ISSUE TITLE
Combination of `anyOf`/`allOf` does not retain the correct option defaults

### ISSUE THREAD

**Issue by linas-vii** [rjsf-team/react-jsonschema-form#2071]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When having a combination of `anyOf`/`allOf`, the generated default option for `anyOf` is not retained correctly from the form data.

See this [link](https://codesandbox.io/s/rjsf-ref-bug-1v2pi?file=/src/index.js  ) in CodeSandbox for an example.

[Playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6IkZvbyIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImJhciI6eyJ0aXRsZSI6IkJhciIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJvYmplY3QiLCJhbnlPZiI6W3sidGl0bGUiOiJCYXoiLCJ0eXBlIjoib2JqZWN0IiwiYWxsT2YiOlt7IiRyZWYiOiIjL2RlZmluaXRpb25zL2Zvb3JlZiJ9XSwicHJvcGVydGllcyI6eyJ2YXJpYWJsZU5hbWUiOnsiY29uc3QiOiJiYXoiLCJkZWZhdWx0IjoiYmF6In19fSx7InRpdGxlIjoiQmF4IiwidHlwZSI6Im9iamVjdCIsImFsbE9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9mb29yZWYifV0sInByb3BlcnRpZXMiOnsidmFyaWFibGVOYW1lIjp7ImNvbnN0IjoiYmF4IiwiZGVmYXVsdCI6ImJheCJ9fX1dfX19LCJkZWZpbml0aW9ucyI6eyJiYXJyZWYiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZGF0YSI6eyJ0aXRsZSI6IkRhdGEiLCJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsibmFtZSJdLCJwcm9wZXJ0aWVzIjp7Im5hbWUiOnsidGl0bGUiOiJOYW1lIiwidHlwZSI6InN0cmluZyJ9fX19fSwiZm9vcmVmIjp7ImFsbE9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9iYXJyZWYifV19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

### Steps to Reproduce

1. Open the example.
2. Choose a variable and change it from `Baz` to `Bax`.
3. Change tabs from `Form` to `JSON`, and back again from `JSON` to `Form`.

#### Expected behavior

The option for a variable selected is retained between the tab changes.

#### Actual behavior

The option for a variable selected is always changed to the first option (in this case `Baz`).

### Version

2.4.0

### Additional details:

I tried to debug this issue, and there are certain points which might be the cause, but please correct me if I have misunderstood something here:
- In `core/src/util.js:224`, `getMatchingOption` is being passed `formData` as `undefined`, shouldn’t it just pass the `formData` as it is?
- In `core/src/util.js:1179`, shouldn’t the `option` be resolved first with `resolveSchema(option, schema, formData)` in order to have all `$ref`'s resolved before performing validation at `core/src/util.js:1222` and `core/src/util.js:1225`? 

#### PRs:
https://github.com/rjsf-team/react-jsonschema-form/pull/1564

**Comment by marian2js** [comment]
I reproduced this issue using only `allOf` (without combining it with anyOf): [Playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJkZWZpbml0aW9ucyI6eyJhZGRyZXNzIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InN0cmVldF9hZGRyZXNzIjp7InR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoiRGVmYXVsdCBzdHJlZXQifSwiY2l0eSI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6IkRlZmF1bHQgY2l0eSJ9LCJzdGF0ZSI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6IkRlZmF1bHQgc3RhdGUifX0sInJlcXVpcmVkIjpbInN0cmVldF9hZGRyZXNzIiwiY2l0eSIsInN0YXRlIl19fSwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiYmlsbGluZ19hZGRyZXNzIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL2FkZHJlc3MifSwic2hpcHBpbmdfYWRkcmVzcyI6eyJhbGxPZiI6W3siJHJlZiI6IiMvZGVmaW5pdGlvbnMvYWRkcmVzcyJ9LHsicHJvcGVydGllcyI6eyJ0eXBlIjp7ImVudW0iOlsicmVzaWRlbnRpYWwiLCJidXNpbmVzcyJdfX0sInJlcXVpcmVkIjpbInR5cGUiXX1dfX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=).

I copied the example from the official [Json Schema documentation](https://json-schema.org/understanding-json-schema/structuring.html) but added defaults.

**Expected**: Form should show defaults for both addresses.
**Actual**: Form only shows defaults for the address not using allOf.
