### ISSUE TITLE
Children's key of array is null 

### ISSUE THREAD

**Issue by MatSemCVMaker** [rjsf-team/react-jsonschema-form#2077]
I'm trying to use a custom ArrayFieldTemplate, just to set my own add button, but rendering the children results in key null and react warning, what am i missing?

### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/degsunw8/) demonstrating the issue.

### Description

Children of array as key null

### Steps to Reproduce

Trying to set a custom template for array field

#### Expected behavior

children key should be unique for react list

#### Actual behavior

element children is null

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by heath-freenome** [comment]
@MatSemCVMaker Can you provide a codesandbox.io for this? Otherwise we really can't help you.
