### ISSUE TITLE
Losing onChange when using a custom array template

### ISSUE THREAD

**Issue by CYLSI** [rjsf-team/react-jsonschema-form#2085]
### Prerequisites

- [☑️] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [☑️] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Firstly thank you for this awesome library !

I am trying to use a custom array template which can render my custom widget. Just like render multiple select. But there's no onChange event passed by props which means I can't pass it to my custom widget.

       <Form
          key={key}
          ref={formRef}
          ArrayFieldTemplate={ArrayFieldTemplate}
          widgets={Widgets}
          formData={formdata}
          uiSchema={uiSchema}
          schema={schema}
        >
        </Form>

    const ArrayFieldTemplate: React.FC<ArrayFieldTemplateProps> = ({ schema, items, uiSchema, ...props }) => {

      const { fields, rootSchema, widgets } = registry;

      const { isFixedItems, optionsList, retrieveSchema, isMultiSelect, getWidget, getUiOptions } = utils;

       if (isMultiSelect(schema, rootSchema)) {

        return renderMultiSelect();

      }

      const renderMultiSelect = () => {

        const itemsSchema = retrieveSchema(schema.items, rootSchema, formData);

        const enumOptions = optionsList(itemsSchema);

        const { widget = 'select', ...options } = {
          ...getUiOptions(uiSchema),
          enumOptions,
        };

        const Widget = getWidget(schema, widget, widgets);

        return (
          <Widget
            autofocus={autofocus}
            disabled={disabled}
            formContext={formContext}
            id={idSchema && idSchema.$id}
            label={label}
            multiple
            onBlur={onBlur}
            onChange={onChange}
            onFocus={onFocus}
            options={options}
            placeholder={placeholder}
            rawErrors={rawErrors}
            readonly={readonly}
            registry={registry}
            required={required}
            schema={schema}
            value={formData}
          />
    };

    return null;
  };

### Version

"@rjsf/core": "^2.4.0",

**Comment by AlexMachin1997** [comment]
Yeah I've just discovered this, it's rather annoying. 

Look's like for now I'll have to assign the component to each schema field which need's it grrr.

**Comment by dekelb** [comment]
Closed with #2243

**Comment by angcivics** [comment]
can I know how is this issue solve in the end? I also need onChange for ArrayFieldTemplate

**Comment by corbinschwartz** [comment]
Please reopen this, ArrayFieldTemplate doesn't receive onChange as a prop.
