### ISSUE TITLE
State corruption of selectedOption in MultiSchemaField when editing data within an oneOf

### ISSUE THREAD

**Issue by erunion** [rjsf-team/react-jsonschema-form#2086]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

On a `oneOf` schema that contains a handful of objects that might slightly differ, the `selectedOption` state is immediately corrupted and the selected option changes once editing data within the form.

Debugging, the problem is the [`componentDidUpdate` React event handler on the `MultiSchemaField` component](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/fields/MultiSchemaField.js#L25-L43). This event is invoked anytime `formData` is changed within the multi schema, and is changing the `selectedOption` without the users permission, resulting in an incredibly degraded experience on these types of schemas. Check out this [playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJyZWdpc3RyYXRpb24iOnt9LCJleGVtcHRpb24iOnt9fSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJvbmVPZiI6W3sidGl0bGUiOiJBbmRhbHVjaWEiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJsaXN0aW5nX2lkIjp7InR5cGUiOiJpbnRlZ2VyIn0sInJlZ3VsYXRvcnlfYm9keSI6eyJ0eXBlIjoic3RyaW5nIn0sInJlZ2lzdHJhdGlvbiI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJwZXJtaXRfbnVtYmVyIjp7InR5cGUiOiJzdHJpbmcifSwicmVnaXN0cmF0aW9uX293bmVyc2hpcCI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJPV05FUiIsIlBST1BFUlRZX01BTkFHRVIiXX0sImVtYWlsIjp7InR5cGUiOiJzdHJpbmcifSwiZnVsbF9uYW1lIjp7InR5cGUiOiJzdHJpbmcifSwiaWRlbnRpZmljYXRpb25fbnVtYmVyIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbInBlcm1pdF9udW1iZXIiLCJyZWdpc3RyYXRpb25fb3duZXJzaGlwIiwiZW1haWwiLCJmdWxsX25hbWUiLCJpZGVudGlmaWNhdGlvbl9udW1iZXIiXX0sImV4ZW1wdGlvbiI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJyZWFzb24iOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiTElTVElOR19UWVBFX05PVF9JTkNMVURFRCIsIkxJU1RJTkdfTk9UX1RPVVJJU1RfQUNDT01NT0RBVElPTiJdfSwicmVnaXN0cmF0aW9uX293bmVyc2hpcCI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJPV05FUiIsIlBST1BFUlRZX01BTkFHRVIiXX0sImVtYWlsIjp7InR5cGUiOiJzdHJpbmcifSwiZnVsbF9uYW1lIjp7InR5cGUiOiJzdHJpbmcifSwiaWRlbnRpZmljYXRpb25fbnVtYmVyIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbInJlYXNvbiIsInJlZ2lzdHJhdGlvbl9vd25lcnNoaXAiLCJlbWFpbCIsImZ1bGxfbmFtZSIsImlkZW50aWZpY2F0aW9uX251bWJlciJdfX0sInJlcXVpcmVkIjpbImxpc3RpbmdfaWQiLCJyZWd1bGF0b3J5X2JvZHkiXX0seyJ0aXRsZSI6IkJhbHRpbW9yZSIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Imxpc3RpbmdfaWQiOnsidHlwZSI6ImludGVnZXIifSwicmVndWxhdG9yeV9ib2R5Ijp7InR5cGUiOiJzdHJpbmcifSwicmVnaXN0cmF0aW9uIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InBlcm1pdF9udW1iZXIiOnsidHlwZSI6InN0cmluZyJ9LCJleHBpcmF0aW9uX2RhdGUiOnsidHlwZSI6InN0cmluZyJ9LCJmdWxsX25hbWUiOnsidHlwZSI6InN0cmluZyJ9LCJlbWFpbCI6eyJ0eXBlIjoic3RyaW5nIn0sImxpc3RpbmdfYWRkcmVzcyI6eyJ0eXBlIjoic3RyaW5nIn0sImF0dGVzdGF0aW9uX2V4aXN0aW5nX3JlZ2lzdHJhdGlvbiI6eyJ0eXBlIjoiYm9vbGVhbiJ9fSwicmVxdWlyZWQiOlsicGVybWl0X251bWJlciIsImV4cGlyYXRpb25fZGF0ZSIsImZ1bGxfbmFtZSIsImVtYWlsIiwibGlzdGluZ19hZGRyZXNzIiwiYXR0ZXN0YXRpb25fZXhpc3RpbmdfcmVnaXN0cmF0aW9uIl19LCJleGVtcHRpb24iOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZXhlbXB0aW9uX3JlYXNvbiI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJob3RlbF9tb3RlbCJdfSwiZnVsbF9uYW1lIjp7InR5cGUiOiJzdHJpbmcifSwiZW1haWwiOnsidHlwZSI6InN0cmluZyJ9LCJhdHRlc3RhdGlvbl9leGVtcHRpb25fY2xhaW0iOnsidHlwZSI6ImJvb2xlYW4ifX0sInJlcXVpcmVkIjpbImV4ZW1wdGlvbl9yZWFzb24iLCJmdWxsX25hbWUiLCJlbWFpbCIsImF0dGVzdGF0aW9uX2V4ZW1wdGlvbl9jbGFpbSJdfX0sInJlcXVpcmVkIjpbImxpc3RpbmdfaWQiLCJyZWd1bGF0b3J5X2JvZHkiXX0seyJ0aXRsZSI6IkJvc3RvbiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Imxpc3RpbmdfaWQiOnsidHlwZSI6ImludGVnZXIifSwicmVndWxhdG9yeV9ib2R5Ijp7InR5cGUiOiJzdHJpbmcifSwicmVnaXN0cmF0aW9uIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InBlcm1pdF9udW1iZXIiOnsidHlwZSI6InN0cmluZyJ9LCJlbWFpbCI6eyJ0eXBlIjoic3RyaW5nIn0sImZ1bGxfbmFtZSI6eyJ0eXBlIjoic3RyaW5nIn0sImxpc3RpbmdfYWRkcmVzcyI6eyJ0eXBlIjoic3RyaW5nIn0sImF0dGVzdGF0aW9uIjp7InR5cGUiOiJib29sZWFuIn19LCJyZXF1aXJlZCI6WyJwZXJtaXRfbnVtYmVyIiwiZW1haWwiLCJmdWxsX25hbWUiLCJsaXN0aW5nX2FkZHJlc3MiLCJhdHRlc3RhdGlvbiJdfSwiZXhlbXB0aW9uIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImV4ZW1wdGlvbl9yZWFzb24iOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiaG90ZWxfbW90ZWwiLCJiZWRfYnJlYWtmYXN0X2xvZGdpbmciLCJpbnN0aXR1dGlvbmFsX2J1c2luZXNzIiwiaG9zcGl0YWxzIl19LCJsaXN0aW5nX2FkZHJlc3MiOnsidHlwZSI6InN0cmluZyJ9LCJhdHRlc3RhdGlvbiI6eyJ0eXBlIjoiYm9vbGVhbiJ9fSwicmVxdWlyZWQiOlsiZXhlbXB0aW9uX3JlYXNvbiIsImxpc3RpbmdfYWRkcmVzcyIsImF0dGVzdGF0aW9uIl19fSwicmVxdWlyZWQiOlsibGlzdGluZ19pZCIsInJlZ3VsYXRvcnlfYm9keSJdfSx7InRpdGxlIjoiQ2F0YWxvbmlhIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsibGlzdGluZ19pZCI6eyJ0eXBlIjoiaW50ZWdlciJ9LCJyZWd1bGF0b3J5X2JvZHkiOnsidHlwZSI6InN0cmluZyJ9LCJyZWdpc3RyYXRpb24iOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsicGVybWl0X251bWJlciI6eyJ0eXBlIjoic3RyaW5nIn0sInJlZ2lzdHJhdGlvbl9vd25lcnNoaXAiOnsidHlwZSI6InN0cmluZyJ9LCJlbWFpbCI6eyJ0eXBlIjoic3RyaW5nIn0sImZ1bGxfbmFtZSI6eyJ0eXBlIjoic3RyaW5nIn0sImlkZW50aWZpY2F0aW9uX251bWJlciI6eyJ0eXBlIjoic3RyaW5nIn19LCJyZXF1aXJlZCI6WyJwZXJtaXRfbnVtYmVyIiwicmVnaXN0cmF0aW9uX293bmVyc2hpcCIsImVtYWlsIiwiZnVsbF9uYW1lIiwiaWRlbnRpZmljYXRpb25fbnVtYmVyIl19LCJleGVtcHRpb24iOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsicmVhc29uIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbImxpc3Rpbmdfbm90X2Z1bGxfYnVpbGRpbmciLCJsaXN0aW5nX2lzX3NoYXJlZF9yb29tIiwib3RoZXJfZXhlbXB0aW9uX3JlYXNvbiJdfSwicmVnaXN0cmF0aW9uX293bmVyc2hpcCI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJPV05FUiIsIlBST1BFUlRZX01BTkFHRVIiXX0sImVtYWlsIjp7InR5cGUiOiJzdHJpbmcifSwiZnVsbF9uYW1lIjp7InR5cGUiOiJzdHJpbmcifSwiaWRlbnRpZmljYXRpb25fbnVtYmVyIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbInJlYXNvbiIsInJlZ2lzdHJhdGlvbl9vd25lcnNoaXAiLCJlbWFpbCIsImZ1bGxfbmFtZSIsImlkZW50aWZpY2F0aW9uX251bWJlciJdfX0sInJlcXVpcmVkIjpbImxpc3RpbmdfaWQiLCJyZWd1bGF0b3J5X2JvZHkiXX0seyJ0aXRsZSI6IkNoaWNhZ28iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJsaXN0aW5nX2lkIjp7InR5cGUiOiJpbnRlZ2VyIn0sInJlZ3VsYXRvcnlfYm9keSI6eyJ0eXBlIjoic3RyaW5nIn0sInJlZ2lzdHJhdGlvbiI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJwZXJtaXRfbnVtYmVyIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbInBlcm1pdF9udW1iZXIiXX19LCJyZXF1aXJlZCI6WyJsaXN0aW5nX2lkIiwicmVndWxhdG9yeV9ib2R5IiwicmVnaXN0cmF0aW9uIl19LHsidGl0bGUiOiJDdWJhIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsibGlzdGluZ19pZCI6eyJ0eXBlIjoiaW50ZWdlciJ9LCJyZWd1bGF0b3J5X2JvZHkiOnsidHlwZSI6InN0cmluZyJ9LCJhZmZpbGlhdGlvbiI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJhdHRlc3RhdGlvbl9lbnRyZXByZW5ldXIiOnsidHlwZSI6ImJvb2xlYW4ifSwibGlzdGluZ19hZGRyZXNzIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbImF0dGVzdGF0aW9uX2VudHJlcHJlbmV1ciIsImxpc3RpbmdfYWRkcmVzcyJdfX0sInJlcXVpcmVkIjpbImxpc3RpbmdfaWQiLCJyZWd1bGF0b3J5X2JvZHkiLCJhZmZpbGlhdGlvbiJdfSx7InRpdGxlIjoiRGVubWFyayIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Imxpc3RpbmdfaWQiOnsidHlwZSI6ImludGVnZXIifSwicmVndWxhdG9yeV9ib2R5Ijp7InR5cGUiOiJzdHJpbmcifSwiY2F0ZWdvcml6YXRpb24iOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsibGlzdGluZ190eXBlIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbInByaW1hcnlfcmVzaWRlbmNlIiwiaG91c2Vib2F0IiwidGVudCIsInRyZWVfaG91c2UiLCJob3RlbF9vcl9ob3N0ZWwiLCJzZXJ2aWNlZF9hcGFydG1lbnQiLCJ0cmFpbGVyIiwibW9iaWxlX2hvbWUiLCJzdW1tZXJfaG91c2UiXX0sImRhdGFfcmVwb3J0aW5nX3N0YXR1cyI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJwcml2YXRlX2FjdGl2aXR5IiwiYnVzaW5lc3NfYWN0aXZpdHkiXX0sImRhdGFfcmVwb3J0aW5nX2JiciI6eyJ0eXBlIjoic3RyaW5nIn0sImF0dGVzdGF0aW9uIjp7InR5cGUiOiJib29sZWFuIn0sImF0dGVzdGF0aW9uX2NvbmRpdGlvbmFsIjp7InR5cGUiOiJib29sZWFuIn19LCJyZXF1aXJlZCI6WyJsaXN0aW5nX3R5cGUiXX19LCJyZXF1aXJlZCI6WyJsaXN0aW5nX2lkIiwicmVndWxhdG9yeV9ib2R5IiwiY2F0ZWdvcml6YXRpb24iXX1dfSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19) for an example of it in action.

Completely eliminating the `componentDidUpdate` event from this component resolves the issue, but I'm having a hard time understanding why this component has a `componentDidUpdate` at all to reset the `selectedOption` when `formData` changes. `selectedOption` should only change with the `onOptionChange` event handler, no?

### Steps to Reproduce

1. Load the [playground example.](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJyZWdpc3RyYXRpb24iOnt9LCJleGVtcHRpb24iOnt9fSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJvbmVPZiI6W3sidGl0bGUiOiJBbmRhbHVjaWEiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJsaXN0aW5nX2lkIjp7InR5cGUiOiJpbnRlZ2VyIn0sInJlZ3VsYXRvcnlfYm9keSI6eyJ0eXBlIjoic3RyaW5nIn0sInJlZ2lzdHJhdGlvbiI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJwZXJtaXRfbnVtYmVyIjp7InR5cGUiOiJzdHJpbmcifSwicmVnaXN0cmF0aW9uX293bmVyc2hpcCI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJPV05FUiIsIlBST1BFUlRZX01BTkFHRVIiXX0sImVtYWlsIjp7InR5cGUiOiJzdHJpbmcifSwiZnVsbF9uYW1lIjp7InR5cGUiOiJzdHJpbmcifSwiaWRlbnRpZmljYXRpb25fbnVtYmVyIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbInBlcm1pdF9udW1iZXIiLCJyZWdpc3RyYXRpb25fb3duZXJzaGlwIiwiZW1haWwiLCJmdWxsX25hbWUiLCJpZGVudGlmaWNhdGlvbl9udW1iZXIiXX0sImV4ZW1wdGlvbiI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJyZWFzb24iOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiTElTVElOR19UWVBFX05PVF9JTkNMVURFRCIsIkxJU1RJTkdfTk9UX1RPVVJJU1RfQUNDT01NT0RBVElPTiJdfSwicmVnaXN0cmF0aW9uX293bmVyc2hpcCI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJPV05FUiIsIlBST1BFUlRZX01BTkFHRVIiXX0sImVtYWlsIjp7InR5cGUiOiJzdHJpbmcifSwiZnVsbF9uYW1lIjp7InR5cGUiOiJzdHJpbmcifSwiaWRlbnRpZmljYXRpb25fbnVtYmVyIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbInJlYXNvbiIsInJlZ2lzdHJhdGlvbl9vd25lcnNoaXAiLCJlbWFpbCIsImZ1bGxfbmFtZSIsImlkZW50aWZpY2F0aW9uX251bWJlciJdfX0sInJlcXVpcmVkIjpbImxpc3RpbmdfaWQiLCJyZWd1bGF0b3J5X2JvZHkiXX0seyJ0aXRsZSI6IkJhbHRpbW9yZSIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Imxpc3RpbmdfaWQiOnsidHlwZSI6ImludGVnZXIifSwicmVndWxhdG9yeV9ib2R5Ijp7InR5cGUiOiJzdHJpbmcifSwicmVnaXN0cmF0aW9uIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InBlcm1pdF9udW1iZXIiOnsidHlwZSI6InN0cmluZyJ9LCJleHBpcmF0aW9uX2RhdGUiOnsidHlwZSI6InN0cmluZyJ9LCJmdWxsX25hbWUiOnsidHlwZSI6InN0cmluZyJ9LCJlbWFpbCI6eyJ0eXBlIjoic3RyaW5nIn0sImxpc3RpbmdfYWRkcmVzcyI6eyJ0eXBlIjoic3RyaW5nIn0sImF0dGVzdGF0aW9uX2V4aXN0aW5nX3JlZ2lzdHJhdGlvbiI6eyJ0eXBlIjoiYm9vbGVhbiJ9fSwicmVxdWlyZWQiOlsicGVybWl0X251bWJlciIsImV4cGlyYXRpb25fZGF0ZSIsImZ1bGxfbmFtZSIsImVtYWlsIiwibGlzdGluZ19hZGRyZXNzIiwiYXR0ZXN0YXRpb25fZXhpc3RpbmdfcmVnaXN0cmF0aW9uIl19LCJleGVtcHRpb24iOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZXhlbXB0aW9uX3JlYXNvbiI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJob3RlbF9tb3RlbCJdfSwiZnVsbF9uYW1lIjp7InR5cGUiOiJzdHJpbmcifSwiZW1haWwiOnsidHlwZSI6InN0cmluZyJ9LCJhdHRlc3RhdGlvbl9leGVtcHRpb25fY2xhaW0iOnsidHlwZSI6ImJvb2xlYW4ifX0sInJlcXVpcmVkIjpbImV4ZW1wdGlvbl9yZWFzb24iLCJmdWxsX25hbWUiLCJlbWFpbCIsImF0dGVzdGF0aW9uX2V4ZW1wdGlvbl9jbGFpbSJdfX0sInJlcXVpcmVkIjpbImxpc3RpbmdfaWQiLCJyZWd1bGF0b3J5X2JvZHkiXX0seyJ0aXRsZSI6IkJvc3RvbiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Imxpc3RpbmdfaWQiOnsidHlwZSI6ImludGVnZXIifSwicmVndWxhdG9yeV9ib2R5Ijp7InR5cGUiOiJzdHJpbmcifSwicmVnaXN0cmF0aW9uIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InBlcm1pdF9udW1iZXIiOnsidHlwZSI6InN0cmluZyJ9LCJlbWFpbCI6eyJ0eXBlIjoic3RyaW5nIn0sImZ1bGxfbmFtZSI6eyJ0eXBlIjoic3RyaW5nIn0sImxpc3RpbmdfYWRkcmVzcyI6eyJ0eXBlIjoic3RyaW5nIn0sImF0dGVzdGF0aW9uIjp7InR5cGUiOiJib29sZWFuIn19LCJyZXF1aXJlZCI6WyJwZXJtaXRfbnVtYmVyIiwiZW1haWwiLCJmdWxsX25hbWUiLCJsaXN0aW5nX2FkZHJlc3MiLCJhdHRlc3RhdGlvbiJdfSwiZXhlbXB0aW9uIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImV4ZW1wdGlvbl9yZWFzb24iOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiaG90ZWxfbW90ZWwiLCJiZWRfYnJlYWtmYXN0X2xvZGdpbmciLCJpbnN0aXR1dGlvbmFsX2J1c2luZXNzIiwiaG9zcGl0YWxzIl19LCJsaXN0aW5nX2FkZHJlc3MiOnsidHlwZSI6InN0cmluZyJ9LCJhdHRlc3RhdGlvbiI6eyJ0eXBlIjoiYm9vbGVhbiJ9fSwicmVxdWlyZWQiOlsiZXhlbXB0aW9uX3JlYXNvbiIsImxpc3RpbmdfYWRkcmVzcyIsImF0dGVzdGF0aW9uIl19fSwicmVxdWlyZWQiOlsibGlzdGluZ19pZCIsInJlZ3VsYXRvcnlfYm9keSJdfSx7InRpdGxlIjoiQ2F0YWxvbmlhIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsibGlzdGluZ19pZCI6eyJ0eXBlIjoiaW50ZWdlciJ9LCJyZWd1bGF0b3J5X2JvZHkiOnsidHlwZSI6InN0cmluZyJ9LCJyZWdpc3RyYXRpb24iOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsicGVybWl0X251bWJlciI6eyJ0eXBlIjoic3RyaW5nIn0sInJlZ2lzdHJhdGlvbl9vd25lcnNoaXAiOnsidHlwZSI6InN0cmluZyJ9LCJlbWFpbCI6eyJ0eXBlIjoic3RyaW5nIn0sImZ1bGxfbmFtZSI6eyJ0eXBlIjoic3RyaW5nIn0sImlkZW50aWZpY2F0aW9uX251bWJlciI6eyJ0eXBlIjoic3RyaW5nIn19LCJyZXF1aXJlZCI6WyJwZXJtaXRfbnVtYmVyIiwicmVnaXN0cmF0aW9uX293bmVyc2hpcCIsImVtYWlsIiwiZnVsbF9uYW1lIiwiaWRlbnRpZmljYXRpb25fbnVtYmVyIl19LCJleGVtcHRpb24iOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsicmVhc29uIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbImxpc3Rpbmdfbm90X2Z1bGxfYnVpbGRpbmciLCJsaXN0aW5nX2lzX3NoYXJlZF9yb29tIiwib3RoZXJfZXhlbXB0aW9uX3JlYXNvbiJdfSwicmVnaXN0cmF0aW9uX293bmVyc2hpcCI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJPV05FUiIsIlBST1BFUlRZX01BTkFHRVIiXX0sImVtYWlsIjp7InR5cGUiOiJzdHJpbmcifSwiZnVsbF9uYW1lIjp7InR5cGUiOiJzdHJpbmcifSwiaWRlbnRpZmljYXRpb25fbnVtYmVyIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbInJlYXNvbiIsInJlZ2lzdHJhdGlvbl9vd25lcnNoaXAiLCJlbWFpbCIsImZ1bGxfbmFtZSIsImlkZW50aWZpY2F0aW9uX251bWJlciJdfX0sInJlcXVpcmVkIjpbImxpc3RpbmdfaWQiLCJyZWd1bGF0b3J5X2JvZHkiXX0seyJ0aXRsZSI6IkNoaWNhZ28iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJsaXN0aW5nX2lkIjp7InR5cGUiOiJpbnRlZ2VyIn0sInJlZ3VsYXRvcnlfYm9keSI6eyJ0eXBlIjoic3RyaW5nIn0sInJlZ2lzdHJhdGlvbiI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJwZXJtaXRfbnVtYmVyIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbInBlcm1pdF9udW1iZXIiXX19LCJyZXF1aXJlZCI6WyJsaXN0aW5nX2lkIiwicmVndWxhdG9yeV9ib2R5IiwicmVnaXN0cmF0aW9uIl19LHsidGl0bGUiOiJDdWJhIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsibGlzdGluZ19pZCI6eyJ0eXBlIjoiaW50ZWdlciJ9LCJyZWd1bGF0b3J5X2JvZHkiOnsidHlwZSI6InN0cmluZyJ9LCJhZmZpbGlhdGlvbiI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJhdHRlc3RhdGlvbl9lbnRyZXByZW5ldXIiOnsidHlwZSI6ImJvb2xlYW4ifSwibGlzdGluZ19hZGRyZXNzIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbImF0dGVzdGF0aW9uX2VudHJlcHJlbmV1ciIsImxpc3RpbmdfYWRkcmVzcyJdfX0sInJlcXVpcmVkIjpbImxpc3RpbmdfaWQiLCJyZWd1bGF0b3J5X2JvZHkiLCJhZmZpbGlhdGlvbiJdfSx7InRpdGxlIjoiRGVubWFyayIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Imxpc3RpbmdfaWQiOnsidHlwZSI6ImludGVnZXIifSwicmVndWxhdG9yeV9ib2R5Ijp7InR5cGUiOiJzdHJpbmcifSwiY2F0ZWdvcml6YXRpb24iOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsibGlzdGluZ190eXBlIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbInByaW1hcnlfcmVzaWRlbmNlIiwiaG91c2Vib2F0IiwidGVudCIsInRyZWVfaG91c2UiLCJob3RlbF9vcl9ob3N0ZWwiLCJzZXJ2aWNlZF9hcGFydG1lbnQiLCJ0cmFpbGVyIiwibW9iaWxlX2hvbWUiLCJzdW1tZXJfaG91c2UiXX0sImRhdGFfcmVwb3J0aW5nX3N0YXR1cyI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJwcml2YXRlX2FjdGl2aXR5IiwiYnVzaW5lc3NfYWN0aXZpdHkiXX0sImRhdGFfcmVwb3J0aW5nX2JiciI6eyJ0eXBlIjoic3RyaW5nIn0sImF0dGVzdGF0aW9uIjp7InR5cGUiOiJib29sZWFuIn0sImF0dGVzdGF0aW9uX2NvbmRpdGlvbmFsIjp7InR5cGUiOiJib29sZWFuIn19LCJyZXF1aXJlZCI6WyJsaXN0aW5nX3R5cGUiXX19LCJyZXF1aXJlZCI6WyJsaXN0aW5nX2lkIiwicmVndWxhdG9yeV9ib2R5IiwiY2F0ZWdvcml6YXRpb24iXX1dfSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19)
2. Type `1` into the `listing_id` input.

#### Expected behavior

The selected `MultiSchemaField` should not change unless the user invokes a change to the dropdown. 

#### Actual behavior

`MultiSchemaField` `selectedOption` state is changed when `formData` is updated.

### Version

This is happening on the latest master.

**Comment by skyboyer** [comment]
to emphasize: it happens only if there may be multiple types that may match current data

why it can re-calculate type after formData has changed? Since `formData` is coming from outside, it's technically possible new data does not match shape of previously selected "oneOf". Maybe a desired result would be not picking first matching type but checking, if data still fits type currently selected. And then picking first matching only if data shape does not satisfy type currently selected.

**Comment by skyboyer** [comment]
By now, in general case, I see 2 different approaches with their own pitfalls:

1. to convert flat list of "oneOf" into a tree of nested "oneOf" where at each level there would have be unique set of fields. Easier to say than to do, sure.
2. to materialize type with introducing extra field with "enum" of only one possible value(`"enum": ["Cuba"]`), enforce that value with `"default": ["Cuba"]` and hide it with `"ui:widget": "hidden"` in UI schema([example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0eXBlIjoiVVNBIiwicmVnaXN0cmF0aW9uIjp7fSwiZXhlbXB0aW9uIjp7fX0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0Iiwib25lT2YiOlt7InRpdGxlIjoiVVNBIiwicHJvcGVydGllcyI6eyJ0eXBlIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIlVTQSJdLCJkZWZhdWx0IjoiVVNBIn0sIm5hbWUiOnsidHlwZSI6InN0cmluZyJ9LCJ6aXAiOnsidHlwZSI6InN0cmluZyJ9fX0seyJ0aXRsZSI6Im5vbi1VU0EiLCJwcm9wZXJ0aWVzIjp7InR5cGUiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsibm9uLVVTQSJdLCJkZWZhdWx0Ijoibm9uLVVTQSJ9LCJuYW1lIjp7InR5cGUiOiJzdHJpbmcifX19XX0sInVpU2NoZW1hIjp7InR5cGUiOnsidWk6d2lkZ2V0IjoiaGlkZGVuIn19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19)). Unfortunately, in this case we need also trim that extra field before sending to server.
