### ISSUE TITLE
[bootstrap-4] File uploads result in error ".file should match format "data-url""

### ISSUE THREAD

**Issue by dstaley** [rjsf-team/react-jsonschema-form#2095]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Using the `bootstrap-4` theme, submitting a file triggers an error:

```
.file should match format "data-url"
```

### Steps to Reproduce

1. [Playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaWxlIjoiQzpcXGZha2VwYXRoXFxXZWJTdG9ybS0yMDIwLjIuMy5leGUifSwic2NoZW1hIjp7InRpdGxlIjoiRmlsZXMiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaWxlIjp7InR5cGUiOiJzdHJpbmciLCJmb3JtYXQiOiJkYXRhLXVybCIsInRpdGxlIjoiU2luZ2xlIGZpbGUifSwiZmlsZXMiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJNdWx0aXBsZSBmaWxlcyIsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJmb3JtYXQiOiJkYXRhLXVybCJ9fSwiZmlsZXNBY2NlcHQiOnsidHlwZSI6InN0cmluZyIsImZvcm1hdCI6ImRhdGEtdXJsIiwidGl0bGUiOiJTaW5nbGUgRmlsZSB3aXRoIEFjY2VwdCBhdHRyaWJ1dGUifX19LCJ1aVNjaGVtYSI6eyJmaWxlc0FjY2VwdCI6eyJ1aTpvcHRpb25zIjp7ImFjY2VwdCI6Ii5wZGYifX19LCJ0aGVtZSI6ImJvb3RzdHJhcC00IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)
2. Click "Choose file" for the first file upload
3. Select any file from your computer
4. Click "Submit"

#### Expected behavior

No errors are displayed.

#### Actual behavior

The following error is displayed:

```
.file should match format "data-url"
```

### Version

`master`

**Comment by NeonMando158** [comment]
Is this issue due to Bootstrap or Something to do with the react-jsonschema wrapper ?

**Comment by epicfaace** [comment]
Yeah, this appears to be a problem with the bootstrap-4 theme. Seems like the form value is incorrectly being set to the file path, instead of the data url representation of the file:

![image](https://user-images.githubusercontent.com/1689183/101181978-864ad480-361b-11eb-93c3-d554d0931afe.png)

@anikethsaha @Xtremilicious is this something you might be able to look into?

**Comment by Hasenn** [comment]
Are there any workarounds?

**Comment by tjuravich** [comment]
@Hasenn  I worked around it using this:

I first created a widget in my repo called BootstrapFileWidget and reference the FileWidget from core:

```
import React from "react";
import FileWidget from "@rjsf/core/dist/cjs/components/widgets/FileWidget";

const BootstrapFileWidget = (props: any) => {
  return (
    <>
      <FileWidget {...props} type="file" />
    </>
  );
};

export default BootstrapFileWidget;
```

Then i popped that into the widgets

```
const widgets = {
  file: BootstrapFileWidget,
};
```

Then, made sure my file was using that widget:
```
const uiSchema = { file: { "ui:widget": "file" } }
```

Not the cleanest workaround, but it got me up in running in a few minutes

**Comment by NeonMando158** [comment]
@tjuravich Nice solution but what happens when you need more than two or three file upload fields ? 
File Widget will only accommodate 1.

**Comment by tjuravich** [comment]
Still not the most elegant, but something like this:

`const uiSchema = { fileFieldOne: { "ui:widget": "file" }, fileFieldTwo: { "ui:widget": "file" }}
`

**Comment by CKGrafico** [comment]
Super small update to @tjuravich great solution :)

```
 <>
      <Form.Label className={props.rawErrors?.length > 0 ? 'text-danger' : ''}>
        {props.label || props.schema.title}
        {(props.label || props.schema.title) && props.required ? '*' : null}
      </Form.Label>
      <div className="form-control-file">
        <FileWidget {...props} type="file" />
      </div>
    </>
```

To have label like in bootstrap theme

**Comment by CKGrafico** [comment]
Let'ts wait to the original author @tjuravich if not, ping me.

**Comment by peterkelly** [comment]
Here's another workaround which monkey-patches the library, without requiring you to do anything special in `uiSchema`:

```
import { withTheme, utils } from "@rjsf/core";
import { Theme } from "@rjsf/bootstrap-4";

const registry = utils.getDefaultRegistry();
const defaultFileWidget = registry.widgets["FileWidget"];
(Theme as any).widgets["FileWidget"] = defaultFileWidget;
const Form = withTheme(Theme);
```

The root cause of the bug is an incomplete implementation of FileWidget in the theme, which simply wraps around the text input. It doesn't work because obtaining data urls for the uploaded files requires some extra javascript functions, which are present in the core FileWidget.

**Comment by epicfaace** [comment]
I think an easier way to do this would be just to override FileWidget in https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/#customizing-the-default-fields-and-widgets?

**Comment by boskjoett** [comment]
This bug is almost 1 year old and still not fixed - why?

**Comment by epicfaace** [comment]
lol bugs don't fix themselves, someone has to fix it

**Comment by boskjoett** [comment]
This thread has identified the root cause (thanks peterkelly), so I was hoping some of the maintainers would fix it. I am unfortunately not a React expert.

**Comment by epicfaace** [comment]
Also see https://github.com/rjsf-team/react-jsonschema-form/issues/2418 for more context

**Comment by alekseisozonovorionic** [comment]
```
import { getDefaultRegistry } from '@rjsf/core';

const FileWidget = (props: any) => {
	const registry = getDefaultRegistry();
	const DefaultFileWidget = registry.widgets['FileWidget'];

	return <DefaultFileWidget {...props} type="file" />;
};

export default FileWidget;
```

```
const widgets = {
  file: BootstrapFileWidget,
};
```

```
const uiSchema = { file: { "ui:widget": "file" } }
```
