### ISSUE TITLE
Why not write a VUE version

### ISSUE THREAD

**Issue by Luckymatian** [rjsf-team/react-jsonschema-form#2097]
Why not write a VUE version？
We're all looking forward to it.

**Comment by laszlocph** [comment]
Just go ahead! ;) Porting is probably much easier than coming up with this lib in the first place

**Comment by epicfaace** [comment]
Looks like there are already a few libraries (such as https://github.com/jarvelov/vue-form-json-schema) that do this.

I think vue is probably beyond the scope of this library for now, though.
