### ISSUE TITLE
Quote  @rjsf/antd error！！！

### ISSUE THREAD

**Issue by Deja-vuuu** [rjsf-team/react-jsonschema-form#2100]
import Form from '@rjsf/antd'; 
Error '@rjsf/antd' does not contain a default export (imported as 'Form').

**Comment by Deja-vuuu** [comment]
![image](https://user-images.githubusercontent.com/27748682/96209640-adcddb00-0fa2-11eb-9ff2-c2ca7e6f3ab4.png)

**Comment by Deja-vuuu** [comment]
![image](https://user-images.githubusercontent.com/27748682/96209668-bb836080-0fa2-11eb-8c0e-117d1ca847a3.png)

**Comment by epicfaace** [comment]
Does `import * as Form` work instead?

**Comment by hackerbyday** [comment]
__Prerequisites__
```
antd >= 4.0.0
@ant-design/icons >= 4.0.0
dayjs >= 1.8.0
@rjsf/core >= 2.0.0
```

```bash
npm install antd @ant-design/icons dayjs @rjsf/core
```

__Installation__
```bash
npm install @rjsf/antd
```

**Comment by hackerbyday** [comment]
Also do
```js
import { withTheme } from '@rjsf/core';
import { Theme as AntDTheme } from '@rjsf/antd';
import 'antd/dist/antd.css';

const Form = withTheme(AntDTheme);
```

**Comment by secreter** [comment]
me too,it`s a bug

**Comment by antonijoDod** [comment]
Same

**Comment by mistory** [comment]
same

**Comment by btoro** [comment]
Same

**Comment by aria-grande** [comment]
same issue

**Comment by KilFront** [comment]
same

**Comment by epicfaace** [comment]
Does someone want to contribute a PR to fix it? 😉

**Comment by laplacehey** [comment]
same

**Comment by dannyozh** [comment]
followed ghost's instructions and still facing the issue of "Could not find a declaration file for module '@rjsf/antd'." Can someone advise?

**Comment by jonborchardt** [comment]
@dannyozh - this is how to add a declaration file

This displays antd form, however it still does not look correct... any advise anyone?

/src/@types/@rjsf/antd.d.ts:
```
declare module '@rjsf/antd' {
    const Theme: any;
    export {Theme};
}
```

myform.tsx:
```
import React from 'react';
import { withTheme } from '@rjsf/core';
import { Theme as AntDTheme } from '@rjsf/antd';
import 'antd/dist/antd.css';

const Form = withTheme(AntDTheme);

export const Crud = () => {
    return <Form schema={blablabla as JSONSchema7} />;
};
```

![image](https://user-images.githubusercontent.com/8194065/125842020-0f612da7-7fa5-4abf-b013-435a89ee30b8.png)

**Comment by chenzitw** [comment]
> @dannyozh - this is how to add a declaration file
> 
> This displays antd themed form
> 
> /src/@types/@rjsf/antd.d.ts:
> 
> ```
> declare module '@rjsf/antd' {
>     const Theme: any;
>     export {Theme};
> }
> ```
> 

Appreciate the guidance, it works!

For type-safe, I think we could declare it as a `ThemeProps` from `@rjsf/core`.

```typescript
declare module '@rjsf/antd' {
  import type { ThemeProps } from '@rjsf/core';

  const Theme: ThemeProps;
  export { Theme };
}
```

**Comment by yanglei177** [comment]
> > @dannyozh - this is how to add a declaration file
> > This displays antd themed form
> > /src/@types/@rjsf/antd.d.ts:
> > ```
> > declare module '@rjsf/antd' {
> >     const Theme: any;
> >     export {Theme};
> > }
> > ```
> 
> Appreciate the guidance, it works!
> 
> For type-safe, I think we could declare it as a `ThemeProps` from `@rjsf/core`.
> 
> ```ts
> declare module '@rjsf/antd' {
>   import type { ThemeProps } from '@rjsf/core';
> 
>   const Theme: ThemeProps;
>   export { Theme };
> }
> ```

It is the same problem

```
Attempted import error: '@rjsf/antd' does not contain a default export (imported as 'Form').
```

**Comment by yanglei177** [comment]
Good, ths

**Comment by epicfaace** [comment]
Can you make a new issue about this? If you know the solution, can you make a PR for it?

**Comment by hansiemithun** [comment]
@yanglei177  - whats the resolution on the last observed issue? @epicfaace  - may i know ticket number which is addressed?
