### ISSUE TITLE
Bug: validation errors stay on screen onSubmit even after fixing the errors.

### ISSUE THREAD

**Issue by saimanoharnethi** [rjsf-team/react-jsonschema-form#2102]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.
Will try to create a jsfiddle in a bit.

### Description

Right now I am facing an issue where my validation errors stay on the screen after onSubmit despite fixing the validation issue. I was able to trace it down to one change - https://github.com/rjsf-team/react-jsonschema-form/pull/1528 in the file - packages/core/src/components/Form.js and line no 74.

I was able to fix it by adding - 

schemaValidationErrors: [],
schemaValidationErrorSchema: [],

to the setState on line 373 of the same file in the PR.

The problem is if you are not using liveValidation and you have some validation errors on submit and for some reason submitting triggers a re-render of the form, the UNSAFE_componentWillReceiveProps is called before the render function, it sets the state with the errors you had from before.

### Steps to Reproduce

1. This happens when liveValidation is turned off
2. Submit your form with validation errors.
3. fix the errors and resubmit.
4. You should see that the errors still display on the screen.

#### Expected behavior

After fixing the error and resubmitting, the validation errors on screen go away.

#### Actual behavior

After fixing the error and resubmitting, the validation errors are still displayed.

### Version

2.0.1 and above.

**Comment by anveshpuli12** [comment]
I'm also facing the same issue , I have used the custom error message to show the errors and when selecting the field or value the error message is still visible. I want to remove my error at on change event can you help me with it @saimanoharnethi

**Comment by saimanoharnethi** [comment]
@anveshpuli12 - It needs a change to the jsonschem-form library, see the description to see what I think could be the fix.

**Comment by rnagy90** [comment]
Same here.
It would be nice if they include that fix in the next release, because currently you can only use it with the `liveValidate` flag or with a full remount, but that's not too resource friendly :/

**Comment by DanielElport** [comment]
Same issue here. would be nice if the errors disappeared on submit
