### ISSUE TITLE
[antd] Losing focus on first entered character when I use a custom FieldTemplate or ObjectFieldTemplate

### ISSUE THREAD

**Issue by NaccOll** [rjsf-team/react-jsonschema-form#2106]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I am trying to use a fieldtemplate to change the layout of each field of the form. When I add my field template to the parameters of the form and use setState in componentDidMount , and I try to use any input, I lose the focus almost instantly. It is a behaviour I am not having without the fieldtemplate or objectFieldTemplate.

### Steps to Reproduce

1. [enter a character]

#### Expected behavior

I can enter any character.

#### Actual behavior

focus is lost

### Demo

https://github.com/NaccOll/rjsf-custom-fieldtemplate

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.
```json
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@ant-design/icons": "^4.2.2",
    "@rjsf/antd": "^2.4.0",
    "@rjsf/core": "^2.4.0",
    "@testing-library/jest-dom": "^5.11.5",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "antd": "^4.7.3",
    "dayjs": "^1.9.4",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.0",
    "web-vitals": "^0.2.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

**Comment by yuvalshi0** [comment]
Hi @NaccOll ,
I also ran into this problem,
Please read this question:
https://stackoverflow.com/questions/56064571/react-text-input-loses-focus-when-i-type-a-letter

**Comment by NaccOll** [comment]
@yuvalshi0 Thank You

**Comment by jaramillo-carlos** [comment]
> @yuvalshi0 Thank You

¿how you fix this?

**Comment by yuvalshi0** [comment]
> > @yuvalshi0 Thank You
> 
> ¿how you fix this?  im having problems related with loss the focus when i use ObjectFieldTemplate :(

@jaramillo-carlos don't define your components (or templates) inside your render function

**Comment by jaramillo-carlos** [comment]
> > > @yuvalshi0 Thank You
> > 
> > 
> > ¿how you fix this?  im having problems related with loss the focus when i use ObjectFieldTemplate :(
> 
> @jaramillo-carlos don't define your components (or templates) inside your render function

I'm trying to use Form, sharing the currentData in formData, and when i apply Object field, start losing focus at each change. :(
`
  const ObjectFieldTemplate = (props: ObjectFieldTemplateProps) => {
    return (
      <>
        {props.title}
        {props.description}
        <Grid container={true} style={{ flexGrow: 1 }}>
          {props.properties.map((element, index) => {
            return (
              <Grid
                item={true}
                key={index}
                xs={element.content?.props?.uiSchema?.['ui:columns'] || 12}>
                  <div style={{ width: '100%', overflow: 'auto' }}>
                    {element.content}
                  </div>
              </Grid>
            )
          })}
        </Grid>
      </>
    );
  };
`

`      <Form
        uiSchema={UIHelpers}
        schema={Schema}
        widgets={widgets}
        fields={fields}
        formData={formData}
        formContext={formData}
        onChange={(d) => setFormData(d.formData)}
        onSubmit={log('submitted')}
        onError={log('errors')}
        ObjectFieldTemplate={ObjectFieldTemplate}
        >

      </Form>`

**Comment by jaramillo-carlos** [comment]
![image](https://user-images.githubusercontent.com/19381328/98255768-c69b3200-1f4b-11eb-9383-cd84a0bcb5db.png)

![image](https://user-images.githubusercontent.com/19381328/98255842-dca8f280-1f4b-11eb-89ee-77fd67e8421b.png)

**Comment by yuvalshi0** [comment]
@jaramillo-carlos 
Seems fine here,
Try adding the element key when you are mapping the elements:
`props.properties.map(element => <foo key={element.content.key} />`

**Comment by jaramillo-carlos** [comment]
> @jaramillo-carlos
> Seems fine here,
> Try adding the element key when you are mapping the elements:
> `props.properties.map(element => <foo key={element.content.key} />`

not works :(

**Comment by yuvalshi0** [comment]
@jaramillo-carlos 
I tested your `ObjectFieldTemplate` and it seems to be working, something else might be affecting your form

**Comment by jaramillo-carlos** [comment]
> @jaramillo-carlos
> I tested your `ObjectFieldTemplate` and it seems to be working, something else might be affecting your form

You test having state inside a useState? im having problems with i use both, onChange with state, and my ObjectFieldTemplate :(

**Comment by yuvalshi0** [comment]
@jaramillo-carlos I use redux.. so It's kinda irrelevant

**Comment by jaramillo-carlos** [comment]
> > @jaramillo-carlos
> > I tested your `ObjectFieldTemplate` and it seems to be working, something else might be affecting your form
> 
> You test having state inside a useState? im having problems with i use both, onChange with state, and my ObjectFieldTemplate :(

Was fixed, extracting the function ObjectFieldTemplate out of the component.

**Comment by JaosnHsieh** [comment]
>  second this! it works.

before

```jsx
const MyForm = ()=> <Form ObjectFieldTemplate={()=>{ return <div>something</div> }} ..... />
```

after 


```jsx
const MyObjectFieldTemplate = ()=><div>something</div> ;
const MyForm = ()=> <Form ObjectFieldTemplate={MyObjectFieldTemplate} ..... />
```

**Comment by minaairsupport** [comment]
I have the same issue and the reason is `ObjectFieldTemplate` was rendered each change happens

**Comment by xyy7260** [comment]
@minaairsupport  how do you fix this?

**Comment by Deep-z21** [comment]
What If I want to pass Custom Props to ObjectField Template, how will I pass if they are declared above the main Page component ?
