### ISSUE TITLE
[bootstrap-4] No UMD dist for bootstrap-4 theme

### ISSUE THREAD

**Issue by stringfellow** [rjsf-team/react-jsonschema-form#2110]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue: https://jsfiddle.net/v7ka24od/1/

### Description

Bootstrap4 theme doesn't allow UMD/AMD use, while core does. As far as I understand, this makes the dist versions built with `npm run build` impossible to use via RequireJS (bootstrap-4.cjs.production.min.js, bootstrap-4.esm.js).

### Steps to Reproduce

1. run `npm install`, `npm run build` as per docs
2. Include dist files into project
3. use `requirejs.config` to include rjsf/rjsf-bs4
4. see e.g. `'exports' is undefined`

#### Expected behavior

1. run `npm install`, `npm run build`
2. find `umd` dist in bootstrap-4 module

#### Actual behavior

There are no `umd` files in bootstrap-4 dist -- see https://jsfiddle.net/v7ka24od/1/

### Version

v2.4.0

**Comment by stringfellow** [comment]
Updated to add JSFiddle demonstrating the problem: https://jsfiddle.net/v7ka24od/1/

**Comment by killua-eu** [comment]
Would someone look into this please?

**Comment by epicfaace** [comment]
We would need to modify the `tsdx build` command to instead also build a `umd` version: see https://github.com/formium/tsdx#tsdx-build. I'd be happy to review a PR that adds this in for bootstrap-4 and the other packages that have similar issues (material-ui, fluent-ui).

**Comment by stringfellow** [comment]
Thanks for the hint @epicfaace - I'm afraid I'm so far removed from typescript/webpack/etc workflows and working environment that this is almost a new technology to me right now (versus using r.js and AMD) - is it an onerous task or a simple config change? (i.e. is it something that someone who knows how that workflow works, could do with small effort; or is it a more fundamental change to the way this library is built?) 

I wish I were more up to date with this and could help fix it :(

**Comment by EricLanduyt** [comment]
would indeed be nice to have this, as I suppose it would also allow using all the themes from CDN, which seems impossible so far. :(

**Comment by stringfellow** [comment]
In the playground (and presumably the default build) the default theme is still bootstrap3; if providing a UMD version of the BS4 & other themes is hard to do, could there be an easier way to make a build out of the core package with a theme that is not bootstrap3 as the default?

I've been trying to understand what it is that causes a build out of the core as UMD, but leaves the other packages as only CJS and ES; unfortunately my knowledge of modern JS builds is not good. @epicfaace mentioned `tsdx` above - is that still relevant in the latest version? What would it take to cause a build out of the UMD module in the `dist` directory so that it is available on CDNs, for example, is it as simple as some change to e.g. https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/webpack.config.dist.js ?

**Comment by epicfaace** [comment]
> @epicfaace mentioned `tsdx` above - is that still relevant in the latest version? What would it take to cause a build out of the UMD module in the `dist` directory so that it is available on CDNs

Yes. I think it would require some effort to see how to emit a UMD build. Part of the time required to do this is scoping it out (seeing whether it's possible using tsdx, or we have to switch to webpack, etc.). Currently, the core theme uses webpack but other themes such as bootstrap-4 use tsdx.

**Comment by stringfellow** [comment]
@epicfaace From the documentation, I believe this will solve it but as per comment above, I cannot test unfortunately :( https://github.com/rjsf-team/react-jsonschema-form/pull/2810

**Comment by nickgros** [comment]
I believe this was added in v4.2.1. @stringfellow can you confirm? Thanks!

**Comment by stringfellow** [comment]
@nickgros ahh well we now seem to have the opposite problem, there is no UMD module for `core`: https://unpkg.com/browse/@rjsf/core@4.2.1/dist/ 😭

**Comment by nickgros** [comment]
@stringfellow We released 4.2.2 to fix the missing UMD bundle. Can you see if that works for you? Greatly appreciate your patience!
