### ISSUE TITLE
asynctypeahead URL param depends on value from another select box

### ISSUE THREAD

**Issue by Iain-Cleland** [rjsf-team/react-jsonschema-form#2112]
I have a requirement where we have a react-jsonschema-form-extras asyncTypeahead as shown in my uischema at the end of this message. What I need is that when the user starts typing in the asyncTypeahead field is that it can get the value of the selected select box (called 'Type' in my schema below) value and use it in the URL in the asyncTypeahead i.e. replacing my hardcoded '367' in the URL "url": URL_EXTERNAL_GET_FILTERED_DICTIONARY+ 5 + "/" + 367,

Can anyone tell me how I can do this (sorry if I have post under the wrong place)? Thanks.

export const uischemaJsonForms = {
"COMPOUND": {
    "Comments": {
        "ui:widget": "textarea",
        "rows": 5
    },
    "BATCH": {
        "SAMPLE": {
            "Container": {
                "ui:field": "asyncTypeahead",
                "asyncTypeahead": {
                    "url": URL_EXTERNAL_GET_FILTERED_DICTIONARY+ 5 + "/" + 367,
                    "labelKey": RESERVED_FIELD_DICT_VALUE,
                    "mapping": RESERVED_FIELD_ID,
                }}
            }
        }
    }

And my schema is:

export const schemaJsonForms = {
"type": "object",
"properties": {
    "COMPOUND" : {
        "type": "object",
        "properties": {
            "Comments": {
                "messages": false,
                "type": "string",
                "minLength": 0,
                "maxLength":200
            },
            "BATCH" : {
                "type": "object",
                "properties": {
                    "Purity": {
                        "type": "number"
                    },
                    "Barcode": {
                        "type": "string",
                        "minLength": 0,
                        "maxLength":200
                    },
                    "SAMPLE" : {
                        "type": "object",
                        "properties": {
                            "Amount": {
                                "type": "number"
                            },
                            "Type": {
                                "type": "number",
                                "anyOf": [
                                    {
                                        "type": "number",
                                        "title": "Default",
                                        "enum": [
                                            367
                                        ]
                                    },
                                    {
                                        "type": "number",
                                        "title": "Eppendorf",
                                        "enum": [
                                            1929
                                        ]
                                    },
                                    {
                                        "type": "number",
                                        "title": "Plate",
                                        "enum": [
                                            1931
                                        ]
                                    },
                                    {
                                        "type": "number",
                                        "title": "Bottle",
                                        "enum": [
                                            366
                                        ]
                                    }
                                ],
                                "default": "Default"
                            },
                            "Container": {
                                "type": "string",
                            }
                        }
                    }
                },
                "required": ["Type", "Container"]
            }
        }
    }
}

**Comment by acushlakoncept** [comment]
I am looking forward to implementing something similar. A field dependent on a URL params, example `http:localhost:3000/sample-form?country=US`

```json
"definitions": {
    "country": {
      "type": "string",
       "title": "Country Main"
    },
    "countryUS": {
      "type": "string",
       "title": "Country US"
    }
  },

[...],

 "country": { "$ref": "#/definitions/country{{param: country}}" },
```

**Comment by acushlakoncept** [comment]
> I am looking forward to implementing something similar. A field dependent on a URL params, example `http:localhost:3000/sample-form?country=US`
> 
> ```json
> "definitions": {
>     "country": {
>       "type": "string",
>        "title": "Country Main"
>     },
>     "countryUS": {
>       "type": "string",
>        "title": "Country US"
>     }
>   },
> 
> [...],
> 
>  "country": { "$ref": "#/definitions/country{{param: country}}" },
> ```

This worked for me!

**Comment by nickgros** [comment]
Closing because it looks like @acushlakoncept provided one possible solution. Thanks!
