### ISSUE TITLE
[bootstrap-4] Autocomplete should be passed through to the Text widget in the same way it is in the default theme.

### ISSUE THREAD

**Issue by wegry** [rjsf-team/react-jsonschema-form#2113]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

[A shared playground](
https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJlbWFpbCI6IkNodWNrIiwibGFzdE5hbWUiOiJOb3JyaXMiLCJhZ2UiOjc1LCJiaW8iOiJSb3VuZGhvdXNlIGtpY2tpbmcgYXNzZXMgc2luY2UgMTk0MCIsInBhc3N3b3JkIjoibm9uZWVkIn0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJlbWFpbCI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJFbWFpbCJ9LCJwYXNzd29yZCI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJQYXNzd29yZCJ9fSwicmVxdWlyZWQiOlsiZW1haWwiLCJwYXNzd29yZCJdfSwidWlTY2hlbWEiOnsiZW1haWwiOnsidWk6YXV0b2NvbXBsZXRlIjoidXNlcm5hbWUifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQifX0sInRoZW1lIjoiYm9vdHN0cmFwLTQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19)

### Steps to Reproduce

1. Looking at the playground, the email field has autocomplete set on it with the default Boostrap 3 theme.
2. Switch to the Bootstrap 4 theme and it is missing. 

#### Expected behavior

It looks like adding `autocomplete` (or maybe `autoComplete`) to https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/bootstrap-4/src/TextWidget/TextWidget.tsx#L11 would patch this.

#### Actual behavior

`autocomplete` doesn't make it onto the rendered `<input>`.

### Version

@rjsf/core@4.4.0
@rjsf/bootstrap-4@2.4.0

**Comment by seanspeaks** [comment]
Huh I think this is also why placeholder isn't making it as well... #2091 Specifically
