### ISSUE TITLE
Validation for max/min date

### ISSUE THREAD

**Issue by Wmarie** [rjsf-team/react-jsonschema-form#2118]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
For date form fields, I am using a regex pattern to validate that dates are of a specific format, such as the following:
```
"field":{
    "title":"Date",
    "type":"string",
    "pattern":"^(([0][1-9]|[1-2][0-9]|[3][0-1])\.([0][1-9]|[1][0-2])\.((1[8,9][0-9][0-9])|(20[0-9][0-9])))$",
    "validationMessage":"Date has to follow the format dd.mm.yyyy"
}
```

Some of my date fields should not accept a date that is either before or after a specific date. So I would like to also validate that the date is BeforeOrEqual or EqualOrAfter a specified date. In my use case, the date is always "today".

I have managed to pass a min or max date option to a custom dateWidget, which greys out the unwanted dates (see screenshot), however the actual form field only validates using the pattern, which means that if a date is manually entered it only valides using the regex and not a min/max date.

Is it possible to supply a minimum or maximum date in any way using the form schema but not a pattern?  

Screenshot attached.
![image](https://user-images.githubusercontent.com/32560503/98240960-85fee100-1f6a-11eb-9e8b-05eef312c4a2.png)

### Version
1.8.1

**Comment by laboratorioAI** [comment]
Hello @Wmarie, I have the same problem. I need to disable the past dates from today. Do you have something for fixing?

**Comment by jonra1993** [comment]
This took a lot of my time. Maybe this can help others I created my custom DateTime widget. 

```
import React from 'react'
import moment from 'moment';
import { TextField } from '@material-ui/core';
import { utils } from "@rjsf/core";
const { localToUTC, utcToLocal } = utils;

const CustomDatetimeWidget = props => {
    const value = utcToLocal(props.value);
    //const onChange = (value) => {
    //  props.onChange(localToUTC(value));
    //};
     const onChange = (event) => {
       props.onChange(localToUTC(event.target.value));
     };
  
    return (
      <TextField
        id="inspection_dates"
        //label="Fecha de inspección"
        required={true}
        type="datetime-local"
        disabled={props.disabled || props.readonly}
        value={value || value === 0 ? value : ""}
        onChange={onChange}
        //inputProps={{ min: `${moment().format('YYYY-MM-DD')}T08:00` }}
        //inputProps={{ min: '2020-12-08T08:00' }}
        InputLabelProps={{
          shrink: true,
        }}
        //{...props}

      />
    )
}


export default CustomDatetimeWidget
```


import in your code

```
import CustomDatetimeWidget from 'src/components/CustomDatetimeWidget';

const customWidgets = { DateTimeWidget: CustomDatetimeWidget };

<Form widgets={customWidgets}  schema={schema}  onSubmit={changeData} >
```

**Comment by iwan-uschka** [comment]
We ended up with the following solution:
- use regular schema definition for date fields (`type: "string", format: "date"`) but set `minimum` and `maximum` as timestamp in schema (if you use date strings for `minimum` or `maximum` the whole validation will stop working)
- create custom date widget
  - convert timestamp values of `minimum` and `maximum` taken from schema into date strings like `2022-03-31`
  - validate `value` manually inside the widget (strings can be compared, `2022-03-31` is bigger than `2022-02-24` so we can compare `value` against `minimum` and `maximum`)
  - we even check `inputRef.current?.validity?.badInput` and create a custom error if necessary
  - store errors into formContext (https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/form-props/#formcontext), we're using a data structure like `formContext.fieldById[<ID>].customError`, formContext can be accessed from every widget
- customize the validate (https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/form-props/#validate) function to check for custom errors in the formContext (including localization and variable substitution to show what `minimum` and `maximum` is actually)

Be careful with the timezones here if you have server side validation next to client side validation :)

**Comment by iwan-uschka** [comment]
@jacqueswho This ticket has been closed. Can you tell more about the solution here? Wasn't able to find anything suitable in the commit log. Thx!

**Comment by jacqueswho** [comment]
@iwan-uschka there was no response, assumed the custom widget mentioned above solved the problem. will re open

**Comment by nickgros** [comment]
You could possibly customize the [ajvFormatOptions](https://rjsf-team.github.io/react-jsonschema-form/docs/usage/validation/#ajvformatoptions) with the `@rjsf/validator-ajv8` validator. See `ajv-formats` docs as well: https://ajv.js.org/packages/ajv-formats.html
