### ISSUE TITLE
 npm run  build:dist  report errors

### ISSUE THREAD

**Issue by guangzhou** [rjsf-team/react-jsonschema-form#2121]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

[Description of the bug or feature]
in the dir  react-jsonschema-form-master/packages/playground

run cmd 
 npm run  build:dist

report errors
  

ROR in ./node_modules/@rjsf/bootstrap-4/dist/bootstrap-4.esm.js
Module not found: Error: Can't resolve 'react-bootstrap/Button' in '/Users/andy/npm/react-jsonschema-form-master/packages/playground/node_modules/@rjsf/bootstrap-4/dist'
 @ ./node_modules/@rjsf/bootstrap-4/dist/bootstrap-4.esm.js 3:0-44 50:29-35 78:29-35 996:62-68
 @ ./src/index.js
 @ multi ./src/index

 

#### Expected behavior

[What you expected to happen]

 can build success

[What actually happened]

**Comment by epicfaace** [comment]
For what purpose were you running `npm run build:dist` in the playground directory?

If you run `npm run build` in the root directory, do you get the same error?
