### ISSUE TITLE
Dependencies between objects

### ISSUE THREAD

**Issue by yuvalshi0** [rjsf-team/react-jsonschema-form#2122]
Hi everyone,
I would like this ask if its possible to make a field depended on a field from another object.
For example: 
https://jsfiddle.net/fs7o1vcw/1/ 

I want "note" field be presented only if "showNotes" is marked under "notes" section.
I haven't managed to find any example covering this case.

**Comment by kaldebert** [comment]
Maybe the "Property dependencies" section on https://rjsf-team.github.io/react-jsonschema-form/ could help.

**Comment by yuvalshi0** [comment]
Closing because I can't remember 😅
