### ISSUE TITLE
Update root FormData Object on Array Add Item Click

### ISSUE THREAD

**Issue by talhahsn** [rjsf-team/react-jsonschema-form#2124]
### Prerequisites

- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

I've a scenario where I want to update the formData Object on adding new item into the array, I tried using arrayFieldTemplate and providing my own template for array but I'm only getting the formData of the array items and by updating it root formData Object is not getting updated. Is there any other way to do so! @epicfaace  can you please help, Thanks

**Comment by heath-freenome** [comment]
@talhahsn Can you provide more details about what this object is doing and where it is supposed to be added and why? If the object isn't defined in the JSON Schema I'm pretty sure we can't handle it.
