### ISSUE TITLE
Using validateFormData on Node results in "Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by timothyallan** [rjsf-team/react-jsonschema-form#2131]
### Prerequisites

- [x ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

[Description of the bug or feature]

Hey all, I'm upgrading from react-jsonschema-form v1.8.1 to @rjsf/core 2.4.0. On Node 12 or 14 (probably more), v2.4 results in a compilation error of::

````
@rjsf/core/lib/validate.js:1
import _toConsumableArray from "@babel/runtime-corejs2/helpers/esm/toConsumableArray";
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)
````

While using my usual import line here that works flawlessly in 1.8.1 and previous versions:

`import * as validateFormData from '@rjsf/core/lib/validate';`

also tried 

`import validateFormData from '@rjsf/core/lib/validate';` 

### Steps to Reproduce

1. [First Step]
`import validateFormData from '@rjsf/core/lib/validate';`

in Node 14.15 or prior

#### Expected behavior

Should be able to use validateFormData as I did in v1.8.1 

#### Actual behavior

Node won't run at all because of the above error.

**Comment by timothyallan** [comment]
Ooookay. I found there's a cjs included, so I can get it to function like this
````
// @ts-ignore
import validateFormData from '@rjsf/core/dist/cjs/validate'; 
````
The `@ts-ignore` is because it reports `Could not find a declaration file for module '@rjsf/core/dist/cjs/validate'.`

Is this the 'proper' way to import now?

**Comment by romkadj** [comment]
> ### Prerequisites
> * [x ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
> 
> ### Description
> [Description of the bug or feature]
> 
> Hey all, I'm upgrading from react-jsonschema-form v1.8.1 to @rjsf/core 2.4.0. On Node 12 or 14 (probably more), v2.4 results in a compilation error of::
> 
> ```
> @rjsf/core/lib/validate.js:1
> import _toConsumableArray from "@babel/runtime-corejs2/helpers/esm/toConsumableArray";
> ^^^^^^
> SyntaxError: Cannot use import statement outside a module
>     at compileFunction (<anonymous>)
> ```
> 
> While using my usual import line here that works flawlessly in 1.8.1 and previous versions:
> 
> `import * as validateFormData from '@rjsf/core/lib/validate';`
> 
> also tried
> 
> `import validateFormData from '@rjsf/core/lib/validate';`
> 
> ### Steps to Reproduce
> 1. [First Step]
>    `import validateFormData from '@rjsf/core/lib/validate';`
> 
> in Node 14.15 or prior
> 
> #### Expected behavior
> Should be able to use validateFormData as I did in v1.8.1
> 
> #### Actual behavior
> Node won't run at all because of the above error.

Had same issue running tests with jest, but in frontend it was working fine without errors.
build configuration could be usefull to solve your issue. 

added
```   
"jest": {
...
 "moduleNameMapper": {
      "@rjsf/core/lib/validate": "@rjsf/core/dist/cjs/validate",
    }
...
}

**Comment by heath-freenome** [comment]
Did you solve your problem?
