### ISSUE TITLE
ui:enumDisabled with antd

### ISSUE THREAD

**Issue by aburtsev** [rjsf-team/react-jsonschema-form#2132]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Using ui:enumDisable with antd theme leads to unexpected results. Items listed in the enumDisable are not shown as disabled, but if you select one of the listed items, then all items became disable.

### Steps to Reproduce
[link to the bug demo](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6Im9uZSIsInNjaGVtYSI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJvbmUiLCJ0d28iLCJ0aHJlZSJdfSwidWlTY2hlbWEiOnsidWk6ZW51bURpc2FibGVkIjpbInR3byJdfSwidGhlbWUiOiJhbnRkIiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjp0cnVlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19)

1. Open the select box and choose "two" (it mentioned in UISchema as enumDisabled)

#### Expected behavior

- When you open the select box "two" should be shown as disabled (as in other themes)
- You should not be able to choose the disabled option

#### Actual behavior

all options became disabled

### Version

"@rjsf/antd": "^2.4.0"
"@rjsf/core": "^2.4.0"

**Comment by aburtsev** [comment]
Will be fixed with PR #2111

**Comment by epicfaace** [comment]
Thanks for #2111! Closing this issue as that PR is now merged.
