### ISSUE TITLE
Enum titles do not appear with antd

### ISSUE THREAD

**Issue by GabrielBellard** [rjsf-team/react-jsonschema-form#2134]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

The **title** of an **enum** does not appear with antd.

### Steps to Reproduce

1. Make a enum
2. Add a title to this enum

[material-ui working example ](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6Im9uZSIsInNjaGVtYSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJJIEFNIEEgVElUTEUiLCJlbnVtIjpbIm9uZSIsInR3byIsInRocmVlIl19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoibWF0ZXJpYWwtdWkiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOnRydWUsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

[antd bug example ](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6Im9uZSIsInNjaGVtYSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJJIEFNIEEgVElUTEUiLCJlbnVtIjpbIm9uZSIsInR3byIsInRocmVlIl19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiYW50ZCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

#### Expected behavior

The enum title should appear.

#### Actual behavior

The enum title does not appear.

#### Version
"@rjsf/antd": "^2.4.0"
"@rjsf/core": "^2.4.0"

**Comment by GGSheridan** [comment]
Should this issue be labeled as Good First Issue?

We are doing research about how to help newcomers onboarding in an open source project and how to accelerate the issue resolving process.
We have developed a tool to automatically label the Good First Issue (GFI), i.e., the issue which is good for newcomers. 
We first extract 72 features from different dimensions of issue reports, such as readability, semantic meaning, associated code snippets, etc, and experimentally investigate to what extent these features correlate with GFI. Results turn out that a large portion of these features do have a medium to large correlation with GFI. 
We then build a machine learning model based on these features to predict GFI. The experiments on a dataset of 12k issues from Github show that 0.90 AUC can be achieved. 

Our tool shows that this issue has a very large possibility to be a GFI. 
Could you please tell us whether it should be labeled as a GFI?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by heath-freenome** [comment]
Also, fails for checkbox version too[ playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCIsInRlbGVwaG9uZSI6IjEtODAwLUtJQ0tBU1MifSwic2NoZW1hIjp7InR5cGUiOiJhcnJheSIsInRpdGxlIjoibXkgdGl0bGUiLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJteSBpdGVtIHRpdGxlIiwiZW51bSI6WyJhIiwiYiIsImMiXX0sInVuaXF1ZUl0ZW1zIjp0cnVlfSwidWlTY2hlbWEiOnsidWk6d2lkZ2V0IjoiY2hlY2tib3hlcyJ9LCJ0aGVtZSI6ImFudGQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsInZhbGlkYXRlIjp0cnVlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19)
