### ISSUE TITLE
AjvError type definition is missing fields defined for actual AJV ErrorObject

### ISSUE THREAD

**Issue by rogervera** [rjsf-team/react-jsonschema-form#2140]
You have to do workarounds when wanting to define a function for the `transformErrors` prop on `<Form/>` that accesses `schemaPath` on an error. 

This is despite the fact that `{ dataPath, keyword, message, params, schemaPath }` are deconstructed for the error object in `transformErrors` (see below)

**Issue**: The type definition for AjvError is missing `schemaPath`, as well as other missing fields compared to the ErrorObject in `ajv`.
**Expected**: `errors.schemaPath`
**Actual**: `Property 'schemaPath' does not exist on type 'AjvError'.ts(2339)`

### `/packages/core/index.d.ts`
https://github.com/rjsf-team/react-jsonschema-form/blob/bf6c99862afe9b381c9be4027ad97adbeabc1bd5/packages/core/index.d.ts#L227-L233
### `/packages/core/src/validate.js `
https://github.com/rjsf-team/react-jsonschema-form/blob/bf6c99862afe9b381c9be4027ad97adbeabc1bd5/packages/core/src/validate.js#L137-L147

### ajv-validator `ajv/lib/types/index.ts`
```ts
export interface ErrorObject<K = string, P = Record<string, any>> {
  keyword: K
  dataPath: string
  schemaPath: string
  params: P
  // Added to validation errors of "propertyNames" keyword schema
  propertyName?: string
  // Excluded if option `messages` set to false.
  message?: string
  // These are added with the `verbose` option.
  schema?: unknown
  parentSchema?: AnySchemaObject
  data?: unknown
}
```
https://github.com/ajv-validator/ajv/blob/3bf88ee217702dd1dcd6bf7bedbcd905d0acdd1e/lib/types/index.ts#L76-L89

**Comment by heath-freenome** [comment]
Hopefully this will be fixed in rjsf v5... take a look at the `rjsf-v5` branch for a sneak peak

**Comment by heath-freenome** [comment]
I believe this has been fixed in the v5 beta, see the  [5.x migration guide](https://react-jsonschema-form.readthedocs.io/en/latest/5.x%20upgrade%20guide/)
