### ISSUE TITLE
Add classNames to all the string fields of the form

### ISSUE THREAD

**Issue by aureliendebord** [rjsf-team/react-jsonschema-form#2143]
### Prerequisites

I have read the documentation on how to customize a widget: https://react-jsonschema-form.readthedocs.io/en/v1.8.1/advanced-customization/#custom-widget-components

Here is the kind of uiSchema I am try to use to get all my inputs the same style:

```
const uiSchema = {
      "ui:widget": (props) => {
        return (
          <input
            type="text"
            className="custom"
            value={props.value}
            required={props.required}
            onChange={(event) => props.onChange(event.target.value)}
          />
        );
      },
    };
```

### Description

I am looking for a simple way to add classNames to all String fields (input field) of my Form, to give them the same look.

#### Expected behavior

I expect the classes to be added to all inputs.

#### Actual behavior

Using a `uischema` the classes does not apply

### Version

"@rjsf/core": "^2.4.0"

**Comment by heath-freenome** [comment]
You could create a custom StringField to do what you want. Or, using the 5.0.0 release, create a wrapper around the `BaseInputTemplate` to pass pull the original template from `getDefaultTemplates()` and then pass `className="custom"` as follows:

```
import { WidgetProps } from '@rjsf/utils';
import { getDefaultRegistry } from '@rjsf/core';
import validator from '@rjsf/validator-ajv8';

const { templates: { BaseInputTemplate } } = getDefaultRegistry();

function MyBaseInputTemplate(props: WidgetProps) {
  return <BaseInputTemplate {...props} className="custom" } />
}

<Form schema={/* your schema */} validator={validator} templates={{ BaseInputTemplate: MyBaseInputTemplate }} />
```
