### ISSUE TITLE
@rjsf/core v2.4.0 Form does not re-render when formData changes.

### ISSUE THREAD

**Issue by braayim** [rjsf-team/react-jsonschema-form#2146]
### Prerequisites

- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/braayim/npxv5bg6/137/) which works well with jsfiddle but does not work in my app

### Description
I have tested [this code](https://jsfiddle.net/braayim/npxv5bg6/137/) in jsfiddle and it works well though with the same code (component) in my app, Form can not re-render when `formData` is updated.

Below is the version of `@rjsf/core` and it's dependencies currently installed in my app. Used `yarn add @rjsf/core` to install
and  then `import Form from '@rjsf/core';`

```
├─ @rjsf/core@2.4.0
│  ├─ @babel/runtime-corejs2@^7.8.7
│  ├─ @types/json-schema@^7.0.4
│  ├─ ajv@^6.7.0
│  ├─ ajv@6.12.6
│  │  ├─ fast-deep-equal@^3.1.1
│  │  ├─ fast-json-stable-stringify@^2.0.0
│  │  ├─ json-schema-traverse@^0.4.1
│  │  └─ uri-js@^4.2.2
│  ├─ core-js@^2.5.7
│  ├─ core-js@2.6.11
│  ├─ fast-deep-equal@3.1.1
│  ├─ js-tokens@4.0.0
│  ├─ json-schema-merge-allof@^0.6.0
│  ├─ json-schema-traverse@0.4.1
│  ├─ jsonpointer@^4.0.1
│  ├─ lodash@^4.17.15
│  ├─ lodash@4.17.15
│  ├─ loose-envify@1.4.0
│  │  └─ js-tokens@^3.0.0 || ^4.0.0
│  ├─ prop-types@^15.7.2
│  ├─ prop-types@15.7.2
│  │  ├─ loose-envify@^1.4.0
│  │  ├─ object-assign@^4.1.1
│  │  ├─ react-is@^16.8.1
│  │  └─ react-is@16.11.0
│  ├─ react-app-polyfill@^1.0.4
│  ├─ react-is@^16.9.0
│  └─ shortid@^2.2.14

```
I can't tell which version of `react-jsonschema-form` am using in the jsfiddle

**Comment by braayim** [comment]
Hi team. Any update on this

**Comment by braayim** [comment]
Never mind. I have been able to fix the issue by upgrading `react` and `react-dom` to `16.7.0` from `16.2.0`

**Comment by epicfaace** [comment]
Okay, great! Are you good to close this issue then?
