### ISSUE TITLE
Non-required object field can't be left empty if at least one its property is required.

### ISSUE THREAD

**Issue by OleksiL** [rjsf-team/react-jsonschema-form#2150]
### Prerequisites

- [x ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

[playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOltdLCJwcm9wZXJ0aWVzIjp7ImQwNDM0YWFjLTg1ZTYtNGVmYy05N2M3LTY0NmFiZTlhYWZhYyI6eyJ0aXRsZSI6InBlcnNvbiBmaWVsZCIsInR5cGUiOiJvYmplY3QiLCJkZXNjcmlwdGlvbiI6InNvbWUgdGV4dCIsInJlcXVpcmVkIjpbImIzZGUyNjdiLTUwNzMtNGM1MC1hYWE2LTAwY2RiMTM4OTgxZCJdLCJwcm9wZXJ0aWVzIjp7ImIzZGUyNjdiLTUwNzMtNGM1MC1hYWE2LTAwY2RiMTM4OTgxZCI6eyJ0aXRsZSI6IkVNQUlMIiwidHlwZSI6InN0cmluZyJ9LCI4ZDVhMmYzNy01NTAyLTRjZGEtOTVhOS04M2JjODYwMjg3NWIiOnsidGl0bGUiOiJGSVJTVF9OQU1FIiwidHlwZSI6InN0cmluZyJ9LCI0YTVmYjUwOC0xMGRhLTQ4ODgtOGY5Mi0zMjE3MGE5MzliZjkiOnsidGl0bGUiOiJMQVNUX05BTUUiLCJ0eXBlIjoic3RyaW5nIn19fX19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIiwidWk6YXV0b2NvbXBsZXRlIjoiZmFtaWx5LW5hbWUifSwibGFzdE5hbWUiOnsidWk6ZW1wdHlWYWx1ZSI6IiIsInVpOmF1dG9jb21wbGV0ZSI6ImdpdmVuLW5hbWUifSwiYWdlIjp7InVpOndpZGdldCI6InVwZG93biIsInVpOnRpdGxlIjoiQWdlIG9mIHBlcnNvbiIsInVpOmRlc2NyaXB0aW9uIjoiKGVhcnRoaWFuIHllYXIpIn0sImJpbyI6eyJ1aTp3aWRnZXQiOiJ0ZXh0YXJlYSJ9LCJwYXNzd29yZCI6eyJ1aTp3aWRnZXQiOiJwYXNzd29yZCIsInVpOmhlbHAiOiJIaW50OiBNYWtlIGl0IHN0cm9uZyEifSwiZGF0ZSI6eyJ1aTp3aWRnZXQiOiJhbHQtZGF0ZXRpbWUifSwidGVsZXBob25lIjp7InVpOm9wdGlvbnMiOnsiaW5wdXRUeXBlIjoidGVsIn19fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjp0cnVlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19)

I would expect that if object field is not required and left empty then form can be submitted without error. If at least one property of such field is provided then the rest should be validated for requireness. 

### Steps to Reproduce

Create non-required object field with some required properties.

#### Expected behavior

If non-required object field doesn't have any properties entered (is empty) then it is possible to submit the form - property is not marked as required

#### Actual behavior

If at least one property of the non-required object field is required on its own, then validation shows error.

**Comment by gaitat** [comment]
Any updates on this one?

**Comment by OleksiL** [comment]
I use `transformErrors={this.suppressEmptyOptionalObjectError}` property to suppress this error:

```
  suppressEmptyOptionalObjectError = (errors: IReactJsonSchemaError[]) => {
    function shouldSuppressError(formData, error: IReactJsonSchemaError): boolean {
      if (error.name === 'required') {
        const parentFieldId = error.property
          .replace(`['${error.params.missingProperty}']`, '')
          .replace("['", '')
          .replace("']", '');
        const parentFieldValue = formData[parentFieldId];
        return parentFieldId && JSON.stringify(parentFieldValue) === '{}';
      }
      return false;
    }

    return errors.filter(error => !shouldSuppressError(this.state.formData, error));
  };
```

**Comment by ranihorev** [comment]
The issue is due to [this call](https://github.com/rjsf-team/react-jsonschema-form/blob/57f00cb522c698a2a201c7204d78dfc6323ac6f6/packages/core/src/utils.js#L240). It sets the default value to be an empty object which later on causing the validation to fail
