### ISSUE TITLE
Bug: Array Field Template - items key prop changes after new element is added to the array

### ISSUE THREAD

**Issue by OleksiL** [rjsf-team/react-jsonschema-form#2158]
### Prerequisites

- [x ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description
I noticed that item key prop changes each time when new element is being added - this causes unnecessary re-rendering and losing selected value by widget.

This is my custom array field template, but I think it has nothing to do with it because problem is with the props passed to it:
`import React from 'react';
import { Button, Grid, IconButton, Typography, Divider } from '@material-ui/core';
import { Add, Clear } from '@material-ui/icons';
import HelperText from 'app/modules/spaces/forms/form-renderer/fields/shared/helper-text';

const arrayTemplate = props => {
  const isRemovable = (element): boolean => element.hasRemove && (element.index !== 0 || !props.required);
  const isArrayEmpty = (): boolean => props.items.length === 0;
  const getText = ({ required, schema: { description } }): string => {
    if (required) return description;
    else if (description) return 'Optional. ' + description;
    else return 'Optional';
  };
  return (
    <div className="form-renderer-array">
      {props.items.map(element => {
          console.log('%c props', 'background: orange; color: black;', props);
          return (

          <Grid key={element.key} container className="form-renderer-array-element">
            <Grid item className="form-renderer-array-element-item">
              {element.children}
            </Grid>
            {/* py-1 is the same vertical compensation class as in text field */}
            <Grid item className="form-renderer-array-element-button py-1">
              {isRemovable(element) && (
                <IconButton size="small" onClick={element.onDropIndexClick(element.index)}>
                  <Clear fontSize="inherit" />
                </IconButton>
              )}
            </Grid>
          </Grid>)
        }
        )}
      {!isArrayEmpty() && <HelperText text={getText(props)} isError={false} />}
      {props.canAdd && (
        // my-1 is the same vertical compensation class as in text field
        <>
          <Button
            size="large"
            onClick={props.onAddClick}
            fullWidth
            className={`my-1 form-renderer-array-add-button form-renderer-array-add-button--${isArrayEmpty() ? 'empty' : 'not-empty'}`}
          >
            <Add color="action" className="mr-2" />
            <Typography color="textSecondary">{props.items.length === 0 ? props.title : 'Add'}</Typography>
          </Button>
          <Divider />
        </>
      )}
      {isArrayEmpty() && <HelperText text={getText(props)} isError={false} />}
    </div>
  );
};

export default arrayTemplate;
`

### Steps to Reproduce

Add new element to array and check key prop for array items - they changed.

#### Expected behavior

I expect that key prop for existing elements remain the same

#### Actual behavior

Key prop for array items changes.

### Version

1.8.1

**Comment by heath-freenome** [comment]
I believe this is fixed in 5.x
