### ISSUE TITLE
Number slider is broken for the number. 

### ISSUE THREAD

**Issue by ievgennaida** [rjsf-team/react-jsonschema-form#2161]
### Prerequisites

1. Open numbers example in chrome. 
2. Select material UI style.
3. Selected Number Range:

https://rjsf-team.github.io/react-jsonschema-form/

4. See that drag not working with the material UI. 

#### Expected behavior

drag for the range slider should work.

**Comment by ps1x** [comment]
As a temporary fix one could use something like this:
```
function CustomRangeFix(props) {
  const { value, onChange } = props
  return (
    <Slider
      aria-label="Volume"
      value={value}
      valueLabelDisplay="auto"
      onChange={(e, b) => onChange(b)}
    />
  )
}

const widgets = {
  range: CustomRangeFix,
}
```
Then use react component with widgets props:
```
<Form widgets={widgets} .... />
```

**Comment by JonCatmull** [comment]
I have added a PR to fix this: https://github.com/rjsf-team/react-jsonschema-form/pull/3297
