### ISSUE TITLE
Question: I would like to show confirmation when item is about to be removed from the array.

### ISSUE THREAD

**Issue by ievgennaida** [rjsf-team/react-jsonschema-form#2162]
Question: I would like to show confirmation when the item is about to be removed from the array.
Is it possible to intersect item removal?

**Comment by aploshay** [comment]
:+1: to this question/request

**Comment by epicfaace** [comment]
You could, but you may have to create your own ArrayFieldTemplate -- check the docs for that.

**Comment by mzvast** [comment]
if you use antd theme like me, you can copy the template  `ArrayFieldTemplate`
<img width="271" alt="image" src="https://user-images.githubusercontent.com/8097465/159879127-89463565-8a26-4e66-89aa-181c5751c8a6.png">

and just change  [this line](https://github.com/rjsf-team/react-jsonschema-form/blob/6063bce42fc3faec5710a67d2671aa5123239feb/packages/antd/src/templates/ArrayFieldTemplate/ArrayFieldTemplateItem.js#L61), use popconfirm or something similar.
