### ISSUE TITLE
Playground website crash!

### ISSUE THREAD

**Issue by ievgennaida** [rjsf-team/react-jsonschema-form#2163]
### Prerequisites

1. Open website in chrome:
https://rjsf-team.github.io/react-jsonschema-form/

2. Go to schema dependencies. 

3. Try to change schema definition name = crash.

ex: 

  "$ref": "#/definitions/person"

type something for a person

#### Expected behavior

Website should work

**Comment by shawn888** [comment]
the same probleme with him

**Comment by connorjclark** [comment]
Starting typing `"$ref": "",` into the initial example schema text input, and it will crash.

Copy pasting a schema with a valid $ref value works OK though.
