### ISSUE TITLE
Sneaky CommonJS require without interop causes runtime error in Rollup

### ISSUE THREAD

**Issue by volkanunsal** [rjsf-team/react-jsonschema-form#2178]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

The `react-jsonschema-form` causes a runtime error because utils.js file contains a CommonJS `require`, statement, which should be wrapped with `_interopRequireDefault` like all the other requires to make it work as part of a library without a runtime. Due to this statement, I cannot run my library, which is compiled by Rollup, and doesn't come with a runtime, like Webpack projects do.

Enclosing a screenshot of the problematic code:

<img width="550" alt="Screen Shot 2020-12-22 at 4 47 56 PM" src="https://user-images.githubusercontent.com/151600/102936331-fbb90080-4475-11eb-8dc8-ad93cf64ee7e.png">

### Steps to Reproduce

1. Use [this rollup config to](https://gist.githubusercontent.com/volkanunsal/384bd724f0e5d11bf0c47e4b89e2679f/raw/6f474064c1bcb004ef1b6b7b1fbdca2cf9f8e4ab/rollup.config.js) compile a React file that renders a few fields.
2. Use `import Form from '@rjsf/core';` to import the core library. Note that this import will use the `lib` folder, rather than the dist folder. If we use the dist folder with `import Form from 'react-jsonschema-form';`, this seems to work.
3. Notice the error in the console.

<img width="483" alt="Screen Shot 2020-12-22 at 4 54 00 PM" src="https://user-images.githubusercontent.com/151600/102936526-518da880-4476-11eb-9f83-557de35a2a41.png">

#### Expected behavior

The code should not contain `require`s.

#### Actual behavior

It does.

### Version

2.4.0

**Comment by volkanunsal** [comment]
Quick update. I compiled this locally in my machine and found that the `require` is generated correctly. So this must have been a bug in an earlier version of `babel` compiler. All you need to do is to recompile the core library and publish a bugfix release.

**Comment by epicfaace** [comment]
I think https://github.com/rjsf-team/react-jsonschema-form/pull/2028 would fix this, so the next version of rjsf shouldn't have this problem regardless?
