### ISSUE TITLE
Represent dynamic key in the json schema form

### ISSUE THREAD

**Issue by arunkumar413** [rjsf-team/react-jsonschema-form#2184]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Represent dynamic key in the json schema form. 

I'm trying to build an open API specification generator using the react-jsonschema-form. However I ran to into issues trying to implement the path obect (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#paths-object). Most of the entities in Open API are fixed and static. However the path object keys such as `/pet ` are dynamic (i.e they should be taken from string type field value)  . Any idea on how to represent these keys in react-jsonschema-form?

Here is what I was able to achieve so far.

https://codesandbox.io/s/164zn?file=/src/App.js

[Description of the bug or feature]

### Steps to Reproduce

1. Refer to this json https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#paths-object-example In this the  ` "/pets" ` is the key which should depend on the value entered by the user in another text field

#### Expected behavior

Represent dynamic keys. A value entered for a field should become the key for another field

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by epicfaace** [comment]
Have you tried using the `additionalProperties` keyword?
