### ISSUE TITLE
How can I add a Clear button?

### ISSUE THREAD

**Issue by levyitay** [rjsf-team/react-jsonschema-form#2185]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

How can I add Clear Button? 
I know I can create a Widget that will return it, but how do I make this widget be placed in the Form's UI? 
Is there a way to add it to the `uiSchema` in some sort of way?

**Comment by epicfaace** [comment]
Related to #1321.

Once you create a widget, you can use `ui:widget` to reference it. See the docs: https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/#custom-component-registration

**Comment by levyitay** [comment]
So this is what I have: 
```
const widgets = {
    'code-text-input': CodeWidget,
    'clear-button-widget': ClearButtonWidget
}
const uiSchema = {
    'clear-button':{
        'ui:widget':'clear-button-widget'
    },
    'ui:order': [ '*', 'clear-button']
}

const fields = {
    'code-text-input': CodeWidget
}

const schema = {
    type: "object",
    properties: {
   "myTitle":{ type:"string" }
}
}
```

And the HTML: 
```
  <Form schema={schema} widgets={widgets} fields={fields} uiSchema={uiSchema} formData={formData} >
            <div>
                <Button color="primary" variant="contained" type="submit">Submit</Button>

            </div>
        </Form>
        ```

**Comment by heath-freenome** [comment]
Why not just add the clear button as another child of the form?

**Comment by levyitay** [comment]
Lol that is what I ended up doing 2 years ago

**Comment by heath-freenome** [comment]
Sounds like you have your solution, closing
