### ISSUE TITLE
Radio button labels interfere with one another on Bootstrap 4 edition

### ISSUE THREAD

**Issue by JonSilver** [rjsf-team/react-jsonschema-form#2191]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Boolean radio button labels, when clicked on, operate unrelated, earlier radio button controls

### Steps to Reproduce

1. Visit [the playground sample](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCIsImFyZSI6dHJ1ZSwiaXMiOmZhbHNlLCJPbmUiOnRydWV9LCJzY2hlbWEiOnsidGl0bGUiOiJCYWQgcmFkaW8gYnV0dG9uIGxhYmVscyIsImRlc2NyaXB0aW9uIjoiQSBmb3JtIHRoYXQgZGVtb25zdHJhdGVzIHRoZSBCb290c3RyYXA0IHJhZGlvIGJ1dHRvbiBsYWJlbHMgYnVnLiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Ik9uZSI6eyJ0eXBlIjoiYm9vbGVhbiIsInRpdGxlIjoiT25lIn0sIlR3byI6eyJ0eXBlIjoiYm9vbGVhbiIsInRpdGxlIjoiVHdvIn0sIlRocmVlIjp7InR5cGUiOiJib29sZWFuIiwidGl0bGUiOiJUaHJlZSJ9fX0sInVpU2NoZW1hIjp7Ik9uZSI6eyJ1aTp3aWRnZXQiOiJyYWRpbyJ9LCJUd28iOnsidWk6d2lkZ2V0IjoicmFkaW8ifSwiVGhyZWUiOnsidWk6d2lkZ2V0IjoicmFkaW8ifX0sInRoZW1lIjoiYm9vdHN0cmFwLTQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19)
2. Click on Yes/No labels for field _Three_
3. Observe the value of _One_ changing

#### Expected behavior

Labels should be rendered to be specific to the value they're labelling

#### Actual behavior

All radio buttons for booleans are rendered with the same `id` attributes: _Yes_ and _No_. So clicking on a label operates the first set of boolean radio buttons rendered instead of the set of radio buttons for the label.

This also occurs if you create enum-based string fields with the same enum value selection, operated by radio buttons, [illustrated by this sample](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJPbmUiLCJsYXN0TmFtZSI6IkZvdXIiLCJhZ2UiOjc1LCJiaW8iOiJSb3VuZGhvdXNlIGtpY2tpbmcgYXNzZXMgc2luY2UgMTk0MCIsInBhc3N3b3JkIjoibm9uZWVkIn0sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRmlyc3QgbmFtZSIsImVudW0iOlsiT25lIiwiVHdvIiwiVGhyZWUiXX0sImxhc3ROYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6Ikxhc3QgbmFtZSIsImVudW0iOlsiT25lIiwiVHdvIiwiVGhyZWUiXX0sInRlbGVwaG9uZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJUZWxlcGhvbmUiLCJtaW5MZW5ndGgiOjEwfX19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6d2lkZ2V0IjoicmFkaW8iLCJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJmYW1pbHktbmFtZSJ9LCJsYXN0TmFtZSI6eyJ1aTp3aWRnZXQiOiJyYWRpbyIsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJnaXZlbi1uYW1lIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sInRoZW1lIjoiYm9vdHN0cmFwLTQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19)

### Version

2.4.1

**Comment by JonSilver** [comment]
I've worked around this bug by importing the RadioWidget from core and using that as a custom widget, then fixing up visuals with some minor CSS rules.

**Comment by laitanop** [comment]
I had  the same issue with radio buttons, I fixed it by adding in CSS file

  label {
    pointer-events:none;
}

it works for me!

**Comment by nickgros** [comment]
This appears to be fixed in RJSF v5
