### ISSUE TITLE
MultiSchemaField getting incorrect id when inside array

### ISSUE THREAD

**Issue by QingqiShi** [rjsf-team/react-jsonschema-form#2197]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When MultiSchemaField is part of an array the idSchema is incorrectly generated. This can cause duplicated ids.

### Steps to Reproduce

1. Check `packages/core/test/anyOf_test.js`
2. Find the test `should correctly render form inputs for anyOf inside array items`
3. Currently we're expecting `input#root_foo` to exist, but that's not the right id

#### Expected behavior

The idSchema ids should maintain the full id even if they're inside arrays.

For example, given a schema 

```js
const schema = {
  type: "object",
  properties: {
    items: {
      type: "array",
      items: {
        type: "object",
        anyOf: [
          {
            properties: {
              foo: {
                type: "string",
              },
            },
          },
          {
            properties: {
              bar: {
                type: "string",
              },
            },
          },
        ],
      },
    },
  },
};
```

The id for the `foo` field within each array item should be `root_items_0_foo`, `root_items_1_foo` etc.

#### Actual behavior

For the example above, the generated id is `root_foo` for all array items.

### Version

2.4.1

**Comment by QingqiShi** [comment]
Fix by https://github.com/rjsf-team/react-jsonschema-form/pull/2127

**Comment by heath-freenome** [comment]
Fixed in v5 beta via https://github.com/rjsf-team/react-jsonschema-form/pull/3039
