### ISSUE TITLE
Checkbox doesn't support descriptions for material-ui / bootstrap-4

### ISSUE THREAD

**Issue by gaitat** [rjsf-team/react-jsonschema-form#2203]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

The description of the the boolean field widget is missing when the theme is material-ui and bootstrap-4

### Steps to Reproduce

1. Go to the playground https://rjsf-team.github.io/react-jsonschema-form/
2. Select the `Widgets` from the top row and observe the boolean field on the right when the default theme is selected. The top widget (checkbox) has a visible description of `This is the checkbox-description`. 
3. If you select the `material-ui` or `bootstrap-4` theme the description disappears for the checkbox widget. The description is still there for the radio widget and the select widget.
4. Is there a way to bring it back?

#### Expected behavior

I expect to see (somewhere) the description of the boolean field widget

#### Actual behavior

The description disappears for the checkbox widget

### Version

These are the packages that I have installed:
    "@rjsf/core": "2.4.1",
    "react": "16.14.0",
    "react-icons": "4.1.0",
    "react-dom": "16.14.0",
    "react-bootstrap": "1.4.3",
    "@rjsf/bootstrap-4": "2.4.1",
    "@material-ui/core": "4.11.2",
    "@material-ui/icons": "4.11.2",
    "@rjsf/material-ui": "2.4.1",

**Comment by nurikk** [comment]
Same issue, I've created example with issue
https://codesandbox.io/s/custom-fields-example-forked-2c09r

**Comment by zehawki** [comment]
I can confirm this issue as well. I see in the playground, as well as in my own experimentation. Occurring only for single checkbox.

![image](https://user-images.githubusercontent.com/8095144/112961693-3b714180-9163-11eb-8fdd-cf613738c370.png)

**Comment by arunim2405** [comment]
Was the fix for this released for material-ui? If yes, which version?
