### ISSUE TITLE
Once description is added to array, console errors are generated

### ISSUE THREAD

**Issue by gaitat** [rjsf-team/react-jsonschema-form#2204]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Once a description is added to an array console errors are generated

### Steps to Reproduce

1. Visit the working page https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJkZWZhdWx0c0FuZE1pbkl0ZW1zIjpbLTEsMCwxXX0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJkZWZhdWx0c0FuZE1pbkl0ZW1zIjp7InR5cGUiOiJhcnJheSIsIm1pbkl0ZW1zIjozLCJtYXhJdGVtcyI6MywiaXRlbXMiOlt7InR5cGUiOiJudW1iZXIifSx7InR5cGUiOiJudW1iZXIifSx7InR5cGUiOiJudW1iZXIifV19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJtYXRlcmlhbC11aSIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==
2. Under the `"type": "array"` add `"description": "abc",`
3. The page will hang giving several errors in the console

#### Expected behavior

I expect the page not to hang

#### Actual behavior

The page hanged

### Version

These are my installed versions:
    "@rjsf/core": "2.4.1",
    "react": "16.14.0",
    "react-icons": "4.1.0",
    "react-dom": "16.14.0",
    "react-bootstrap": "1.4.3",
    "@rjsf/bootstrap-4": "2.4.1",
    "@material-ui/core": "4.11.2",
    "@material-ui/icons": "4.11.2",
    "@rjsf/material-ui": "2.4.1",
    "showdown": "1.9.1"

**Comment by nickgros** [comment]
Fixed in RJSF v5.11.0 (or likely much earlier)
