### ISSUE TITLE
Webpack build

### ISSUE THREAD

**Issue by FBurner** [rjsf-team/react-jsonschema-form#2207]
### Prerequisites

- [X ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

[Description of the bug or feature]

Hi i tried to build an application with webpack

and this is happening

```
ERROR in ./node_modules/@rjsf/core/node_modules/ajv/lib/refs/json-schema-draft-07.json 2:13
Module parse failed: Unexpected token (2:13)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| {
>     "$schema": "http://json-schema.org/draft-07/schema#",
|     "$id": "http://json-schema.org/draft-07/schema#",
|     "title": "Core schema meta-schema",
 @ ./node_modules/@rjsf/core/node_modules/ajv/lib/ajv.js 448:19-62
 @ ./node_modules/@rjsf/core/dist/es/validate.js 8:0-22 16:16-19
 @ ./node_modules/@rjsf/core/dist/es/utils.js 26:0-55 814:30-46 1196:10-17 1199:15-22
 @ ./node_modules/@rjsf/core/dist/es/index.js 3:0-33 4:0-28
 @ ./node_modules/@rjsf/material-ui/dist/material-ui.esm.js 1:0-46 100:20-39 101:25-49 310:31-61 421:16-31 477:30-59 610:22-43 679:17-33 680:17-33 809:16-31 858:15-29 859:16-31 1081:27-51 1117:0-9
```

i tried many loader but nothing seem to have helped.

 ```
rules: [
        {
          test: /\.m?js/,
          type: "javascript/auto",
          resolve: {
            fullySpecified: false,
          },
        },
        {
          test: /\.css$/i,
          use: ["style-loader", "css-loader"],
        },
        {
          test: /\.(ts|tsx|js|jsx)$/,
          exclude: /node_modules/,
          use: {
            loader: "babel-loader",
          },
        },
      ],
```

### Version
   "@rjsf/core": "^2.4.1",
    "@rjsf/material-ui": "^2.4.1",

**Comment by epicfaace** [comment]
Maybe try adding `exclude: /node_modules/` to each of the entries in `rules`? I wonder if you're accidentally transpiling the rjsf module.

**Comment by knilink** [comment]
My guess is 
```       
{
  test: /\.m?js/,
  type: "javascript/auto",
  resolve: {
    fullySpecified: false,
  },
}
```
overrided the default rules so webpack didn't know how to process `json` files.
So you may need to explicitly add json rules.
```
{
  test: /\.json/,
  type: "json",
},
```

tested with `webpack@5.19.0`

**Comment by heath-freenome** [comment]
@FBurner Did the above solution solve your issue? We will close this soon unless you say otherwise.
