### ISSUE TITLE
How to group React json schema nested objects

### ISSUE THREAD

**Issue by NeslihanKolukisa** [rjsf-team/react-jsonschema-form#2221]
Let me explain my scenario;I have a schema like that { "type": "object", "properties": { "a": { "type": "object", "title": "title1", "properties": { "a1": "a1", "a2": "a2" } }, "b": { "type": "object", "title": "title2", "properties": { "b1": "b1", "b2": "b2" } } } } and I can seperate that schema into two groups as "a" and "b" in tabs . But i want to make other group only including a1 and b1 but not adding to schema. and display them in my added tab. How can i do it ?

**Comment by ri0ter** [comment]
Hmm maybe you could try creating a custom widget which would implement all the different views/tabs you want to have.

You could also try creating different forms with custom widgets for each tab. It's similar to the first option but it could be easier to implement. Also here you would need to implement something to sync all the different forms (if they share the same data).

**Comment by NeslihanKolukisa** [comment]
I tried making a custom theme app that would apply all the different tabs I wanted to have. But in json shema, I could not access the content (React element) of the object in the object. Do you have a chance to give an example on this subject?

**Comment by NeslihanKolukisa** [comment]
`const doGrouping = ({
  properties, groups, formContext, schema,
}):any => {
  const mapped = groups.map((g) => {
    if (typeof g === 'string') {
      const found = properties.filter((p) => p.name === g);
      if (found.length === 1) {
        const el = found[0];
        return el.content;
      }
      return EXTRANEOUS;
    } else if (typeof g === 'object') {
      const { templates } = formContext;
      const GroupComponent = templates.tabsComponent;
      // @ts-ignore
      const tempProperties = Object.keys(g).reduce((acc, key) => {
        const field = g[key];
        if (key.startsWith('ui:')) return acc;
        if (!Array.isArray(field)) return acc;
        return [
          ...acc,
          {
            name: key,
            children: doGrouping({
              properties,
              formContext,
              groups: field,
              schema,
            }),
          },
        ];
      }, []);
      return <GroupComponent properties={tempProperties} />;
    }
    throw new Error(`Invalid object type: ${typeof g} ${g}`);
  });
  const remainder = mapped.filter((m) => m === REST);
  if (remainder.length > 0) {
    throw new Error('Remainder fields not supported');
  }
  return mapped;
};
`
