### ISSUE TITLE
Too much recursion when when inputting lots of decimals in a number field

### ISSUE THREAD

**Issue by arime** [rjsf-team/react-jsonschema-form#2233]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When entering a number with lots of decimals in a number field, something starts recursing a lot and the browser gets stuck. It gets worse when there is small decimals. For example 1.000000000000001 is still fine, but if you start adding more zeros in between, keeping 1 as the last digit, this happens.

The issue can be reproduced in the playground, here's a link:

https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCIsIm51bWJlciI6MS4wMDAwMDAwMDAwMDAwMDF9LCJzY2hlbWEiOnsidGl0bGUiOiJSZXByb2R1Y2luZyB0b28gbXVjaCByZWN1cnNpb24iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJudW1iZXIiOnsidHlwZSI6Im51bWJlciJ9fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJmYW1pbHktbmFtZSJ9LCJsYXN0TmFtZSI6eyJ1aTplbXB0eVZhbHVlIjoiIiwidWk6YXV0b2NvbXBsZXRlIjoiZ2l2ZW4tbmFtZSJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoidXBkb3duIiwidWk6dGl0bGUiOiJBZ2Ugb2YgcGVyc29uIiwidWk6ZGVzY3JpcHRpb24iOiIoZWFydGhpYW4geWVhcikifSwiYmlvIjp7InVpOndpZGdldCI6InRleHRhcmVhIn0sInBhc3N3b3JkIjp7InVpOndpZGdldCI6InBhc3N3b3JkIiwidWk6aGVscCI6IkhpbnQ6IE1ha2UgaXQgc3Ryb25nISJ9LCJkYXRlIjp7InVpOndpZGdldCI6ImFsdC1kYXRldGltZSJ9LCJ0ZWxlcGhvbmUiOnsidWk6b3B0aW9ucyI6eyJpbnB1dFR5cGUiOiJ0ZWwifX19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19

### Steps to Reproduce

1. Define a JSON schema with a number-type field
2. Generate form out of the schema and enter 1.000000000000001 in the number field
3. Start adding more zeros in between, while keeping 1 as the last digit

#### Expected behavior

The app stays responsive and there are no errors.

#### Actual behavior

The app becomes unresponsive and after some time an "Uncaught InternalError: too much recursion" happens.

![Screenshot 2021-02-11 at 13 08 25](https://user-images.githubusercontent.com/2574772/107630186-de313780-6c6b-11eb-9f8b-ef2e261629f0.png)

### Version

2.4.1

**Comment by arime** [comment]
![Screenshot 2021-02-11 at 12 44 48](https://user-images.githubusercontent.com/2574772/107630466-3d8f4780-6c6c-11eb-9e21-2c7e11ded685.png)

**Comment by NishantChorge7** [comment]
Issue is still there
