### ISSUE TITLE
"export 'Icon' was not found in 'antd'

### ISSUE THREAD

**Issue by hansiemithun** [rjsf-team/react-jsonschema-form#2237]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

[export Icon not found and types declaration for rjsf-antd is not found in typescript]
Trying to implement the react-jsonschema-form with antd theme having typescript. 

**Getting errors as below:**

    WARNING in ./node_modules/rjsf-antd/es/AddButton/AddButton.js 5:24-28
    "export 'Icon' was not found in 'antd'

    WARNING in ./node_modules/rjsf-antd/es/IconButton/IconButton.js 8:38-42
    "export 'Icon' was not found in 'antd'

Also it states that there is no types declaration for @rjsf/antd. Can someone please assist this at the earliest

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior

[Should apply the antd theme without any error]

#### Actual behavior

[Error in the layout without grid css applied and wierd warnings]

### Version

**Dev dependencies installed: **
    "@rjsf/antd": "2.4.2",
    "@rjsf/core": "2.4.2",
     "@types/react-jsonschema-form": "1.7.4",
     "webpack": "4.44.2",
     "webpack-cli": "3.3.11"

**Dependencies installed: **
     "rjsf-antd": "0.1.5-alpha.17",
     "react-jsonschema-form": "1.8.1",

**Comment by epicfaace** [comment]
I think you have too old versions of rjsf and rjsf-antd installed. Try `npm uninstall rjsf-antd && npm uninstall @types/react-jsonschema-form && npm uninstall react-jsonschema-form && npm i @rjsf/antd && npm i @rjsf/core`
