### ISSUE TITLE
Provide onChange to FieldTemplate

### ISSUE THREAD

**Issue by TimothyBJacobs** [rjsf-team/react-jsonschema-form#2238]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

I'd like to be able to apply a "Reset" button to any arbitrary field in a form. Because it could be applied to any field type, I think it'd make sense to do this as part of the `FieldTemplate` level instead of as a part of each field or widget type.

This would be possible if the `onChange` function was passed to the `FieldTemplate`. Would that be an acceptable change? If so, I'm happy to work on a PR.

**Comment by epicfaace** [comment]
Yes, that would be a great change. Feel free to make a PR!

**Comment by TimothyBJacobs** [comment]
Awesome, thanks @epicfaace! PR in #2243.
