### ISSUE TITLE
Playground crashes when single sample's input is empty

### ISSUE THREAD

**Issue by pedrowindisch** [rjsf-team/react-jsonschema-form#2254]
### Prerequisites

- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I was testing some samples on the playground and I found out that if you clear the Single sample's input, the app crashes.

### Steps to Reproduce

1. Open the [playground](https://rjsf-team.github.io/react-jsonschema-form/) and select the Single sample
2. Remove all content from the sample's input.

![demo](https://user-images.githubusercontent.com/30203228/109392256-edfe7c00-78f9-11eb-974e-3622271f1958.gif)

**Comment by pedrowindisch** [comment]
So it looks like when I clear the input, the onFormDataChange handler receives `undefined` as its parameter value. The form data editor throws an error when it tries to parse `undefined` to JSON.  I've managed to fix this issue by adding a default value to the handler parameter as below.

![image](https://user-images.githubusercontent.com/30203228/109394473-f1980000-7905-11eb-9dfb-060722eca365.png)

![demo](https://user-images.githubusercontent.com/30203228/109394845-e80f9780-7907-11eb-8787-6b1a17f8ca38.gif)

@epicfaace can I create a PR with the fix?

**Comment by heath-freenome** [comment]
This has been fixed by #2257
