### ISSUE TITLE
Unable to input formData for oneOf while omitExtraData and liveOmit is set to true

### ISSUE THREAD

**Issue by maksymt1** [rjsf-team/react-jsonschema-form#2262]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Unable to input formData for oneOf while omitExtraData and liveOmit is set to true
ex: https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0Iiwib25lT2YiOlt7InByb3BlcnRpZXMiOnsibG9yZW0iOnsidHlwZSI6InN0cmluZyJ9fSwicmVxdWlyZWQiOlsibG9yZW0iXX0seyJwcm9wZXJ0aWVzIjp7Imlwc3VtIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbImlwc3VtIl19XX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOnRydWUsImxpdmVPbWl0Ijp0cnVlfX0=

### Steps to Reproduce

1. Select oneOf schema example
2. Select omitExtraData and liveOmit
3. Attempt to input data

#### Expected behavior

Data is inputted 

#### Actual behavior

Nothing happens

### Version

2.4.2

**Comment by mr-bjerre** [comment]
Same here... Which is a problem since shared fields are not resetting with anyOf/oneOf without this option. See #1819

**Comment by maksymt1** [comment]
The problem seems to be coming from here:
`const fieldNames = this.getFieldNames(pathSchema, formData);`
or
`newFormData = this.getUsedFormData(formData, fieldNames);`

fieldNames is `[]` and `let data = _pick(formData, fields);` in `getUsedFormData` returns `[]`

It looks like changing 
`    if (fields.length === 0 && typeof formData !== "object") {
      return formData;
    }`
    to
`if (fields.length === 0) {
  return formData;
}`
in getUsedFormData works but i haven't been able to test this out properly as I'm not sure about the functionality of the code/original purpose and unfortunately i haven't had the time to dig in more.

**Comment by maksymt1** [comment]
Looking into it more it looks like the 

-toPathSchema ignores the properties contained in oneOf
	-because of this fieldNames doesn’t load the names in oneOf 
		-and getUsedFormData filters out the required fields

**Comment by xyy7260** [comment]
@maksymt1  hi， Do you use omitextradata and liveomit to delete extra form data values that are not in the form fields?

**Comment by knjoeyn** [comment]
Hi @xyy7260 we are hitting this issue as well and yes, we are using omitextradata and liveomit to delete extra form data values that are not in the form fields.
