### ISSUE TITLE
"description" of a property won't show when using theme antd

### ISSUE THREAD

**Issue by Littly** [rjsf-team/react-jsonschema-form#2273]
### Description

[Example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCJ9LCJzY2hlbWEiOnsidGl0bGUiOiJBIHJlZ2lzdHJhdGlvbiBmb3JtIiwiZGVzY3JpcHRpb24iOiJUaGlzIGlzIHRoZSBzYW1lIGFzIHRoZSBzaW1wbGUgZm9ybSwgYnV0IGl0IGlzIHJlbmRlcmVkIGFzIGEgYm9vdHN0cmFwIGdyaWQuIFRyeSBzaHJpbmtpbmcgdGhlIGJyb3dzZXIgd2luZG93IHRvIHNlZSBpdCBpbiBhY3Rpb24uIiwidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbImZpcnN0TmFtZSIsImxhc3ROYW1lIl0sInByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkZpcnN0IG5hbWUiLCJkZXNjcmlwdGlvbiI6IlRoaXMgaXMgdGhlIHNhbWUgYXMgdGhlIHNpbXBsZSBmb3JtLCBidXQgaXQgaXMgcmVuZGVyZWQgYXMgYSBib290c3RyYXAgZ3JpZC4gVHJ5IHNocmlua2luZyB0aGUgYnJvd3NlciB3aW5kb3cgdG8gc2VlIGl0IGluIGFjdGlvbi4ifSwibGFzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiTGFzdCBuYW1lIn0sImFnZSI6eyJ0eXBlIjoiaW50ZWdlciIsInRpdGxlIjoiQWdlIn0sImJpbyI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJCaW8ifSwicGFzc3dvcmQiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiUGFzc3dvcmQiLCJtaW5MZW5ndGgiOjN9LCJ0ZWxlcGhvbmUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiVGVsZXBob25lIiwibWluTGVuZ3RoIjoxMH19fSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImFudGQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19)
When using theme `@rjsf/antd`, `description` of a property won't show.

The problem will be resolved if I uncomment [this line](https://github.com/rjsf-team/react-jsonschema-form/blob/dafd55a01891634a62cf3b2ab9f1cf6a9a1ff26d/packages/antd/src/templates/FieldTemplate/index.js#L67). Is that commented out for some other reason?

### Steps to Reproduce

1. Add `description` for any property at [rjsf-jsonschema-form playground](https://rjsf-team.github.io/react-jsonschema-form/), like:
```diff
 "properties": {
    "firstName": {
      "type": "string",
      "title": "First name",
 +++     "description": "This is the same as the simple form, but it is rendered as a bootstrap grid. Try shrinking the browser window to see it in action."
    },
```
2. Switch the theme, and see the result.

> default
![image](https://user-images.githubusercontent.com/5780093/111114938-ecda7980-859e-11eb-8560-63e7aef2bb44.png)

> antd
![image](https://user-images.githubusercontent.com/5780093/111114965-f663e180-859e-11eb-8eea-bd2c3a199ff1.png)

#### Expected behavior

`description` should be shown as what default theme did.

**Comment by momesana** [comment]
@Littly, We are facing the same issue and it would be nice if the antd-theme supported it by default but there is a simple workaround. Looking at the code you will notice that the `extra` prop (which is how antd would normally display a description pertaining to the input field in question) is listed as a prop in `FieldTemplate.js` accounted for but commented out for some reason: https://github.com/rjsf-team/react-jsonschema-form/blob/7c0d6c2785f170444d806847328b3d060085bb5a/packages/antd/src/templates/FieldTemplate/index.js#L67.

Morover @rjsf allows you to override the template by providing it as a property to the Form component. Therefore you can easily clone the existing file (don't forget to include the MIT license since this constitutes a derived work), enable the extra field by removing the comments and pass the resulting custom FieldTemplate component to your Form like this:
```js
import FieldTemplate from './FieldTemplate';

...
<Form FieldTemplate={FieldTemplate} {...yourOtherProps}>
</Form>
```

**Comment by soarding** [comment]
> @Littly, We are facing the same issue and it would be nice if the @rjsf antd theme supported it out of the box but there is still a simple workaround. Looking at the code you will notice that the `extra` prop (which is how antd would normally display a description pertaining to the input field in question) is listed as a prop in `FieldTemplate.js` but commented out for some reason:
> 
> https://github.com/rjsf-team/react-jsonschema-form/blob/7c0d6c2785f170444d806847328b3d060085bb5a/packages/antd/src/templates/FieldTemplate/index.js#L67
> 
> .
> Morover @rjsf allows you to override the template by providing it as a property to the Form component. Therefore you can easily
> 
> 1. clone the mentioned file (don't forget to include the Apache2 license since this constitutes a derivative work),
> 2. enable the extra field by removing the comments
> 3. and pass the resulting custom FieldTemplate component to your Form like this:
> 
> ```js
> import FieldTemplate from './FieldTemplate';
> 
> ...
> <Form FieldTemplate={FieldTemplate} {...yourOtherProps}>
>    ...
> </Form>
> ```

it can solve this problem,but i don't know why @rjsf remark the know

**Comment by epicfaace** [comment]
@delyanr do you remember why the "extra" line was commented out? Should we add it back?

**Comment by Ezhvsalate** [comment]
@epicfaace it would be great if this line will be uncommented. Currently it looks weird to clone the whole file to enable this small piece of functionality.

**Comment by epicfaace** [comment]
Yeah, feel free to make a PR that does that
