### ISSUE TITLE
All schema data lost in case of error

### ISSUE THREAD

**Issue by genvarek** [rjsf-team/react-jsonschema-form#2277]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

In case of some errors the playground turns into a blank page. It looks like that: 
![Screenshot from 2021-03-16 19-21-34](https://user-images.githubusercontent.com/38023948/111316208-41f4b900-868d-11eb-8ef9-de764550a5b1.png)

If I click on "go back" in Chrome or reload the page, I return to the default example and my own json schema is lost. 

### Steps to Reproduce

1. Go to the shared playground [https://bit.ly/38Ns83L](url)
2. Try to type in the UI schema inside "case2" this: "ui:widget": "radio"
3. The form is lost!

#### Expected behavior

Errors are underlined with red curved lines like typos. Or anything else, but I don't want my data to be erased!

#### Actual behavior

Data is lost.

### Version

Current playground

**Comment by ngquoctrong** [comment]
I have the same issue here when users edit UI Schema, and they type word by word and issue happened

**Comment by nickgros** [comment]
This will be fixed in the playground in #3164. To fix this in your own application, I recommend using an error boundary and/or not committing an invalid UI schema to the Form component.
