### ISSUE TITLE
How to pass component props value for Antd components.

### ISSUE THREAD

**Issue by kunalshewale** [rjsf-team/react-jsonschema-form#2281]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

It's not a bug, I want to understand how customisation works for supported widget props.

I am using `Antd` with `RJSF`, I am facing an issue with the `Select` component. In the case of multi-select, `Antd` hides the drop-down arrow icon. I want to show that arrow as per requirement.

In `Antd` the drop-down arrow display can be controlled through a prop; `showArrow`. I am looking for an option to update this `Select` component props.

Please guide me on this.

### Steps to Reproduce

NA

#### Expected behaviour

NA
#### Actual behavior

NA

### Version

```
"@rjsf/antd": "^2.2.2",
"@rjsf/core": "^2.2.2",
```

**Comment by jacqueswho** [comment]
looking at the code base antd theme does not support antd theme props like some of the other themes do. Log a issue for the antd theme to support antd widget props
