### ISSUE TITLE
Default Enum Values in OneOf Definitions do not appear in form data submissions

### ISSUE THREAD

**Issue by AScully24** [rjsf-team/react-jsonschema-form#2296]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x]  Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When submitting an enum value from a field contained in a oneOf definition, the default value is not included in the formData property after submission.

[JS Fiddle Example](https://jsfiddle.net/FartyFace/jt9f6dbw/)

[Playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJOYW1lIjoiaGkifSwic2NoZW1hIjp7InRpdGxlIjoiT25lT2YgRW51bSBCdWciLCJ0eXBlIjoib2JqZWN0IiwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7Ik5hbWUiOnsidHlwZSI6InN0cmluZyJ9LCJvbmUtb2YtZXhhbXBsZS1maWVsZCI6eyJvbmVPZiI6W3siJHJlZiI6IiMvZGVmaW5pdGlvbnMvTXlEZWZpbml0aW9uIiwidGl0bGUiOiJNeSBDaG9pY2UifV19fSwicmVxdWlyZWQiOlsiTmFtZSJdLCJkZWZpbml0aW9ucyI6eyJNeURlZmluaXRpb24iOnsidHlwZSI6Im9iamVjdCIsImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjpmYWxzZSwicHJvcGVydGllcyI6eyJ0aGlzIGRlZmF1bHQgZW51bSB3aWxsIG5vdCBiZSBpbiB0aGUgc3VibWl0dGVkIGZvcm0gZGF0YSI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJmb28tYmFyIl0sImRlZmF1bHQiOiJmb28tYmFyIn0sIkhlYWRlciBLZXkiOnsidHlwZSI6InN0cmluZyJ9LCJIZWFkZXIgVmFsdWUiOnsidHlwZSI6InN0cmluZyJ9fSwicmVxdWlyZWQiOltdfX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

### Steps to Reproduce

1. Use the following schema in the Playground / JS Fiddle:
```json
{
  "title": "OneOf Enum Bug",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "Name": {
      "type": "string"
    },
    "one-of-example-field": {
      "oneOf": [
        {
          "$ref": "#/definitions/MyDefinition",
          "title": "My Choice"
        }
      ]
    }
  },
  "required": [
    "Name"
  ],
  "definitions": {
    "MyDefinition": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "this default enum will not be in the submitted form data": {
          "type": "string",
          "enum": [
            "foo-bar"
          ],
          "default": "foo-bar"
        },
        "Header Key": {
          "type": "string"
        },
        "Header Value": {
          "type": "string"
        }
      },
      "required": []
    }
  }
}
```
2. Fill in any fields
3. Submit the form

#### Expected behavior
Form data should contain all fields, including the default enum value described in MyDefinition

#### Actual behavior
The default value is not present

### Version
2.5.1

**Comment by rohansaw** [comment]
I also encountered the issue as described above - in addition, the default value of "oneOf" fileds are not rendered in the form. Is there any fix planned for this, since this issue has been open for more than 2 years?
