### ISSUE TITLE
rawErrors seem to not be properly cleared on a successful validation (after a failed validation).

### ISSUE THREAD

**Issue by bmmpt** [rjsf-team/react-jsonschema-form#2309]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I'm using an app store, powered by React's Context API, were I persist the form errors. Then, I use an Alert (reactstrap) to display the number of errors on the form, by accessing the length of the errors array in the store.
I submit my form without a title and an error is displayed on my Alert. Then I enter a title and submit. The form will validate and the title field will re-render (when debugging, BaseInput props.rawErrors is undefined). Then the form submit callback runs, which I use to clear the store errors (because submit succeeded). Updating the store will cause another re-render of the form and the BaseInput. At this point, BaseInput props.rawErrors gets the previous error back as the image below shows:
![image](https://user-images.githubusercontent.com/14299284/112702401-b7b90b80-8e69-11eb-9e72-baa8da783f12.png)

After running past the break point, the Alert no longer shows, because there are effectively no errors on the form, but the Title field still displays the error.
![image](https://user-images.githubusercontent.com/14299284/112702438-da4b2480-8e69-11eb-9efa-32242b393f90.png)

If you comment onSubmit={onSubmit} on <Form ...> the issue won't occur.

Something seems to be wrong with rawErrors. It seems to not be properly cleared on a successful validation (after a failed validation).

### Steps to Reproduce

1. Load https://codesandbox.io/s/react-json-schema-form-and-context-api-fmz0g
2. Click submit (Title will display the required field error)
3. Enter a title and click submit (Title **still** displays the required field error)

#### Expected behavior

No errors should be displayed under Title

#### Actual behavior

Title **still** displays the required field error

### Version

2.5.1

**Comment by bmmpt** [comment]
Maybe I'm drawing a blank here... but it seems to me that this is a considerable issue. Context Api is getting more popular everyday. I would expect more people to run into this issue...

**Comment by bmmpt** [comment]
@epicfaace can I get a comment on this one? 🥱

**Comment by LevBuchel** [comment]
@bmmpt I had the same issue, a working workaround can be found here:
https://github.com/rjsf-team/react-jsonschema-form/issues/486#issuecomment-282431387

**Comment by kfcaio** [comment]
> @bmmpt I had the same issue, a working workaround can be found here: [#486 (comment)](https://github.com/rjsf-team/react-jsonschema-form/issues/486#issuecomment-282431387)

This seems to be a workaround for the whole form clearing. What if I want to clear each field a time after validation?
