### ISSUE TITLE
Feature Request MUI Validation

### ISSUE THREAD

**Issue by daniel-pfaeffli** [rjsf-team/react-jsonschema-form#2313]
### Description
Hi all

I had recently a customer with the requirement for german validation messages.
A came accross the [ajv-i18n](https://ajv.js.org/packages/ajv-i18n.html) extension.

My solution was pretty quick & dirty because the customer only needs german validation messages.
I've updated validation.js

- Import ajv-i18n
- After[ line 50](https://github.com/rjsf-team/react-jsonschema-form/blob/3ae111c3de72645bd7051a64fd39c675dd42a22c/packages/core/src/validate.js#L50) 
`//Added localization
  _localize.de(errors);`

I think it would be a big plus if a mui validation is possible in react-jsonshema-form. 
I see multiple maturity steps for validation integration

- Static definition of validation language in form defintion
- Dynamic definition of validation language based on browser language

what do you think about this?

thx in advance

**Comment by heath-freenome** [comment]
Using the new `@rjsf/validator-ajv8` in the new v5 beta you can do this pretty easily now. See https://react-jsonschema-form.readthedocs.io/en/latest/usage/validation/#localization-l12n-support
