### ISSUE TITLE
Question about the ObjectFieldTemplate

### ISSUE THREAD

**Issue by AlexMachin1997** [rjsf-team/react-jsonschema-form#2314]
Hi everyone,

Is there a way to get either the errorSchema or rawErrors inside of the ObjectFieldTemplate ?

Basically in my project at work we have Accordions within the ObjectFieldTemplate, we want to add an error state to the Accordion but we need access to the error state, but from what I can see that's not possible.

Is there a way around this limitation ?

**Comment by epicfaace** [comment]
@AlexMachin1997 were you able to find a solution to this? Looking at the docs (https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-templates/#objectfieldtemplate), it seems that ObjectFieldTemplate doesn't currently have these properties, but FieldTemplate does. A possible enhancement to this library would be to add these properties to ObjectFieldTemplate as well.

**Comment by devgeeks** [comment]
I know this is closed, but I'd also like to find a workaround for this.

**Comment by sudo-NithishKarthik** [comment]
I had a similar use case as well. I created a CustomObjectField component that works the same way as the default one, but it will pass the `rawErrors` into the TemplateProps.
