### ISSUE TITLE
Dependency warning

### ISSUE THREAD

**Issue by zehawki** [rjsf-team/react-jsonschema-form#2317]
warning @rjsf/core > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning @rjsf/core > @babel/runtime-corejs2 > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

**Comment by epicfaace** [comment]
This will be fixed by https://github.com/rjsf-team/react-jsonschema-form/pull/2211.
