### ISSUE TITLE
Boolean Select from Material UI theme can never be set to Yes/true

### ISSUE THREAD

**Issue by davidnyman-caci** [rjsf-team/react-jsonschema-form#2326]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When using the Material UI theme, the select drop down will always display a value of "No", all change events show the formData has a value of `false` for the field, regardless of what was selected.  This appears to be an issue with the @rjsf/material-ui library, the provided example works as expected when using the default theme.

This seems to be caused by https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/material-ui/src/SelectWidget/SelectWidget.tsx#L25 where it fails a strict equality check of the value; the function is given a boolean `true` or `false`, which is never equal to `"true"`.  It appears the same problem was encountered by https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/semantic-ui/src/SelectWidget/SelectWidget.js#L44

### Steps to Reproduce

1. Go to the playground https://rjsf-team.github.io/react-jsonschema-form/
2. Change the theme from `default` to `material-ui`
3. Paste the following text into the JSONSchema field
```
{
  "type": "object",
  "properties": {
    "myStuckBoolean": {
      "type": "boolean",
      "title": "myStuckBoolean"
    }
  }
}
```
4. Paste the following text into the UISchema field
```
{
  "myStuckBoolean": {
    "ui:widget": "select"
  }
}
```
5. Paste the following text into the formData field
```
{
  "myStuckBoolean": true
}
```
6. Select "Yes" on the generated form

#### Expected behavior

Selecting `Yes` causes it to be selected/reselected

#### Actual behavior

`No` is always selected/reselected regardless of choice

### Version
"@rjsf/core@2.4.2",
"@rjsf/material-ui@2.4.2",

**Comment by heath-freenome** [comment]
This was fixed in the v5 beta
