### ISSUE TITLE
Can't access schemaUI of dependency property

### ISSUE THREAD

**Issue by roman-hrybinchuk** [rjsf-team/react-jsonschema-form#2331]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
Can't access widgets of dependency property

### Steps to Reproduce
https://jsfiddle.net/ve5npdsu/

#### Expected behaviour
Be able to put on the conditional field 
ui:help or ui:widget and etc

[What you expected to happen]

#### Actual behaviour

[What actually happened]
Does not work to access by key inside the UISchema
### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by adyyoung** [comment]
This seemed to work for me? What did you try?

```diff
const uiSchema = {
 
  "field": {
    "field-child": {
      "ui:widget": "radio",
      "ui:options": {
        "inline": true
      }
    },
+    "filed_to_have_widget_on": {
+     "ui:widget": "textarea"
+  }
  }
};
```
