### ISSUE TITLE
Overwriting TextWidget is causing `RangeError: Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by taylorpreston** [rjsf-team/react-jsonschema-form#2334]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Trying to override the default `TextWiget`. I followed the docs and am using Next.js. 

### Steps to Reproduce

```
import React from "react"
import Form from "@rjsf/core"

const schema = {
  title: "A registration form",
  description: "A simple form example.",
  type: "object",
  required: ["firstName", "lastName"],
  properties: {
    firstName: {
      type: "string",
      title: "First name",
      default: "Chuck",
    },  
    lastName: {
      type: "string",
      title: "Last name",
    },
    telephone: {
      type: "string",
      title: "Telephone",
      minLength: 10,
    },
  },
}

const TextWidget = function (props) {
  const { label, onChange, onBlur, onFocus, value } = props
  return (
    <div>
      <label className="block text-sm font-medium text-gray-700">{label}</label>
      <div className="mt-1">
        <input
          onChange={onChange}
          onBlur={onBlur}
          onFocus={onFocus}
          value={value}
          type="text"
          className="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md"
        />
      </div>
    </div>
  )
}

const Widgets = {
  TextWidget,
}

const MyForm = () => {
  const handleSubmit = () => { }
  return (
    <div>
      <Form schema={schema} onSubmit={handleSubmit} widgets={Widgets} />
    </div>
  )
}

export default MyForm
```

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by Yitzchak-SB** [comment]
I'm experiencing the same issue.

**Comment by noe-lc** [comment]
Hi @taylorpreston and @Yitzchak-SB. You've probably fixed this by now, but I'll post how I fixed this problem here anyway in case someone else bumps into it:

It all boils down to the fact that the `Form` component's `onChange` prop does not pass the whole event object, it only passes the value, so for it to work correctly one has to strip the value off the event with another callback, like so:

```
const PhoneInputJSF = (props) => {
  const handleChange = (e) => {
    props.onChange(e.target.value) // this is the Form's onChange prop
  }

  return <PhoneInput onChange={handleChange} value={props.value} />
}
```

I am using the component in the schema like this:
```
const uiSchema: UiSchema = {
  clientId: {
    'ui:widget': PhoneInput,
  },
}
```

This solved my problem. Curious to know how you fixed it.

**Comment by heath-freenome** [comment]
This appears to be user error and not a bug in the library.
