### ISSUE TITLE
Kitchen sink examples with lots of errors

### ISSUE THREAD

**Issue by nikolaidk** [rjsf-team/react-jsonschema-form#2340]
### Prerequisites

- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I have tested this project extensively for the last couple of days, and was quite exited. Now I'am wondering why so many of the examples in the kitchensick only works as expected for the default and Boostrap theme. Forexample the yellow text fields in the Widget and in the Examples examples the browser option only shows for bootstrap?  Iam know a solution might not be around the corner. Is the project drifting apart or is there a roadmap?

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by epicfaace** [comment]
Hi @nikolaidk , I don't see any of the errors you're talking about. Can you please give a shared playground link that describes the issue? Additionally, you should include which browser you're using and screenshots of the specific issues. Thanks.
