### ISSUE TITLE
Externally determining if form has errors

### ISSUE THREAD

**Issue by ronnyek** [rjsf-team/react-jsonschema-form#2343]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

Honestly this is just  quick question that I didn't find in searching first.  Being that I'm not using submit button because of displaying a form in a dialog and wanting to use submit button of my modals, I'm curious what the best way to determine whether the form was in a "good" state... rather that validation is passing.

I know I can provide a `onChange` callback, and get at `e.errors`. Would the best way of providing the state to my modals button be to set a state variable `isValid` to `e.errors.length> 0` and then use that as whether my button is enabled/disabled?

Is there a better way to get at that more directly? Appreciate any feedback.

**Comment by jacqueswho** [comment]
should an easy change, if you want to make a PR, to include this functionality, please do. Possibly another callback called isValid could be added that we can called to check state of the form. regarding the submit button, I have a [PR](https://github.com/rjsf-team/react-jsonschema-form/pull/2640) that will give more flexibility to hide the button. Read only forms will then be a possibility and change the text

**Comment by kfcaio** [comment]
Are you able to get something like `e.errors` using React v17? I'm only getting `undefined` 👍🏾 

```
onChange={
            (formData, e) => {
              console.log("Event:", e)
            }
          }
```

`e` is undefined

**Comment by heath-freenome** [comment]
Fixed in the v5 beta.9

**Comment by Ricerob** [comment]
Dropping new link: https://rjsf-team.github.io/react-jsonschema-form/docs/usage/validation/#validate-form-programmatically
