### ISSUE TITLE
submitting the form programmatically // native form submit

### ISSUE THREAD

**Issue by devo-wm** [rjsf-team/react-jsonschema-form#2344]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Are there any best practices/good strategies for autosaving a form?

I thought I'd use the instructions on submitting the form programmatically - however the onSubmit passed to <Form /> never fires as demonstrated here: 

https://codesandbox.io/s/awesome-grothendieck-jfvnl?file=/src/App.js

It looks like the (lowercase) `<form />`'s native submit is firing causing a page refresh.

...I'm probably doing something wrong.

**Comment by epicfaace** [comment]
I think this is a duplicate of https://github.com/rjsf-team/react-jsonschema-form/issues/500, which has some more discussion on what you may want.

**Comment by devo-wm** [comment]
I was able to iterate on the useRef button click strategy described [here](https://github.com/rjsf-team/react-jsonschema-form/issues/500#issuecomment-743116788)
