### ISSUE TITLE
Styles not working correctly 

### ISSUE THREAD

**Issue by Aditi-1400** [rjsf-team/react-jsonschema-form#2345]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I've been trying to use react-jsonschema-form and am unable to get the right styles for the array add and delete buttons, the styles look something like:
![Screenshot from 2021-04-24 13-38-41](https://user-images.githubusercontent.com/62544124/115952409-508f8500-a503-11eb-97b6-d904191ec8dd.png)

#### Expected behavior

The expected styles are:

![Screenshot from 2021-04-24 13-46-14](https://user-images.githubusercontent.com/62544124/115952429-787ee880-a503-11eb-9369-f6bf04d64d12.png)

### Version
 "@rjsf/core": "^2.5.1",
  "react": "^17.0.2"

### My code
Javascript:
https://github.com/Aditi-1400/rjsf-test/blob/main/src/index.js

HTML:
https://github.com/Aditi-1400/rjsf-test/blob/main/public/index.html

Repository:
https://github.com/Aditi-1400/rjsf-test

**Comment by epicfaace** [comment]
I think your repo is using Bootstrap 5. The default theme only works with Bootstrap 3; please try changing your stylesheet to use that instead.

**Comment by Aditi-1400** [comment]
Oh, That Worked!! Thank you so much!! :)

**Comment by epicfaace** [comment]
No problem!
