### ISSUE TITLE
Provide form and field meta data like pristine or dirty, touched

### ISSUE THREAD

**Issue by elissaioskon** [rjsf-team/react-jsonschema-form#2346]
### Description

1) **A Form needs to know when it is dirty for the following reasons**
    i) In order to enable/disable submit button on edit. If form is dirty submit should be enabled otherwise disabled
    ii) When user is editing a form and clicks somewhere outside the form (so there are unsaved changes) a prompt should be 
         displayed in order to save the changes

2) **A form needs to know when a field is touched in order to be able to display an error after the users blurs on a field and not only when they click the submit button**

Documentation does not provide any guideline about how we could make these two and they are fundamentals in order to create a form correctly. 

Because the library is popular, has anyone manage to handle these issues? 

Also similar issue has been mentioned on #504 but since it was created before 4 years i create this one.

Thank you for your time !

**Comment by cerpins** [comment]
I have handled the issue by importing `utils` from `@rjsf/core`, then using `getDefaultFormState()` to generate all form defaults - the resulting object can be compared to whatever `formData` comes out of `onChange` callback

**Comment by ferretwithaberet** [comment]
> I have handled the issue by importing `utils` from `@rjsf/core`, then using `getDefaultFormState()` to generate all form defaults - the resulting object can be compared to whatever `formData` comes out of `onChange` callback
> 
> edit: I was also not able to find this in documentation, maybe it is, maybe it is not, but I came across the solution by digging the code

I made my own proxy component for `<Form />`, which overrides the `onChange` prop to also call a `onDirtyChange` callback.

For referrence, it looks something like this:
```ts
import React, { useRef } from "react";
import { Form } from "@rjsf/antd";
import { FormProps } from "@rjsf/core";
import validator from "@rjsf/validator-ajv8";
import { getDefaultFormState, deepEquals } from "@rjsf/utils";

const normalizeObject = (obj: Record<string, unknown>) => {
  return Object.fromEntries(
    Object.entries(obj).filter(([, value]) => value != null)
  );
};

export type MyFormProps = FormProps & {
  onDirtyChange?: (
    ...args: [
      isDirty: boolean,
      ...Parameters<NonNullable<FormProps["onChange"]>>,
    ]
  ) => void;
};

const MyForm = (props: MyFormProps) => {
  const { schema, formData } = props;
  const { onChange, onDirtyChange, ...restProps } = props;

  const lastDirtyRef = useRef(false);

  const handleChange: FormProps["onChange"] = (data, id) => {
    onChange?.(data, id);

    const { formData: newFormData } = data;

    const normalizedDefaultFormData = normalizeObject(
      getDefaultFormState(validator, schema, formData)
    );
    const normalizedNewFormData = normalizeObject(newFormData);

    const isDirty = !deepEquals(
      normalizedDefaultFormData,
      normalizedNewFormData
    );
    if (lastDirtyRef.current !== isDirty) {
      lastDirtyRef.current = isDirty;
      onDirtyChange?.(isDirty, data, id);
    }
  };

  return <Form {...restProps} onChange={handleChange} />;
};

export default MyForm;
```

**Comment by caillou** [comment]
I took @ferretwithaberet answer and changed the `normalizeObject` to the following definitions. This hopefully handles nested objects as well:

```ts
const normalize = (data: unknown): unknown => {
  switch (typeof data) {
    case 'boolean':
      return data ? 'true' : undefined;
    case 'string':
      return data ? data : undefined;
    case 'function':
    case 'bigint':
    case 'symbol':
    case 'number':
    case 'undefined':
      return data;
    case 'object':
      if (Array.isArray(data)) {
        return data.map(x => normalize(x));
      }

      if (data === null || Object.keys(data).length === 0) {
        return undefined;
      }

      return Object.fromEntries(
        Object.entries(data)
          .map(([key, value]) => [key, normalize(value)])
          .filter(([, value]) => value !== undefined)
      );
  }
};
```
