### ISSUE TITLE
The FieldValidation type doesn't support objects in schemas 

### ISSUE THREAD

**Issue by Steffan-Ennis** [rjsf-team/react-jsonschema-form#2347]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

In index.d.ts the FieldValidation type does not support the schemas that have properties of type: 'object' with there 
own properties keys
### Steps to Reproduce

For the following schema

```
import * as RJSF from '@rjsf/core'

const mySchema = {
  'type': 'object',
  'properties': {
    'anotherObject': {
      'type': 'object',
      'properties': {
        'someField': {'type':'string'}
      }
    }
  }
}

function customValidate(formData:any, errors:RJSF.FormValidation):RJSF.FormValidation {
  if(!formData.anotherObject.someField){
    errors.anotherObject.someField.addError('This field has special validation rules')
  }

  return errors
}
```

#### Expected behaviour

Typescript should compile

#### Actual behaviour

There are typescript compilation errors

### Version

Latest

**Comment by heath-freenome** [comment]
Fixed in the v5 beta, see the [5.x migration guide](https://react-jsonschema-form.readthedocs.io/en/latest/5.x%20upgrade%20guide/)
