### ISSUE TITLE
Widget number and integer field documentation error

### ISSUE THREAD

**Issue by ovdgInitworks** [rjsf-team/react-jsonschema-form#2358]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

[Description of the bug or feature]

In the documentation about Widgets ([here](https://react-jsonschema-form.readthedocs.io/en/latest/usage/widgets/#for-number-and-integer-fields)), it says that 'By default, a regular input[type=text] element is used' for number and integer fields. Shouldn't this be 'By default, a regular input[type=number] element is used'?

[What you expected to happen]

Widget docs about integer and number fields should say 'By default, a regular input[type=number] element is used'

[What actually happened]

Widgets docs about integer and number fields says 'By default, a regular input[type=text] element is used'

**Comment by heath-freenome** [comment]
This has been fixed in the v5 beta
