### ISSUE TITLE
Form ref question

### ISSUE THREAD

**Issue by AlexMachin1997** [rjsf-team/react-jsonschema-form#2361]
Hi,

I'm using this library at work and I've come to a piece of functionality to disable the enter button for submitting the form.

I want to use refs so I can attach a custom event to the Form element, however, I can't see a way to attach a ref to the component. Is there a undocumented prop which allows you to access the Form component via a ref ?

If I can't it's not a big deal I can probably do the event via a className, but it would be better with ref's 😄

**Comment by devo-wm** [comment]
Not 100% sure but perhaps this may be of use to you? Docs: [Submit form programmatically](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/internals/#submit-form-programmatically)

**Comment by AlexMachin1997** [comment]
@devo-wm I'm sure I've tried that before and it didn't work.

Honestly that example is pretty bad, if it's a react library it should be using useRef or the class equivalent or something. 

I can see the form uses a ref internally, but I can't see a ref prop to access the form.

**Comment by AlexMachin1997** [comment]
I got around it with a vanilla javascript solution

```
 // Adds an event listener to the Form element, it prevents the enter key from being used you have to click submit.
    useEffect(() => {
        // Get the element by id, this is
        const element = document.getElementById(FORM_ID);

        const event = e => {
            // When the Enter key is used stop the form from submitting
            if (e.code === 'Enter') {
                e.preventDefault();
            }
        };

        // When the form has loaded and the DOM element exists ie not null add the event listener
        if (isPageLoading === false && element !== null) {
            element.addEventListener('keypress', e => event(e));
        }

        // Cleanup function, run's when this Resource page is destroyed, it's good practice to cleanup any unnecessary event listeners to prevent any resource/memory leaks
        return () => {
            if (isPageLoading === false && element !== null) {
                return element.removeEventListener('keypress', event);
            }
            return {};
        };
    }, [isPageLoading]);
```

**Comment by AlexMachin1997** [comment]
> > @devo-wm I'm sure I've tried that before and it didn't work.
> > Honestly that example is pretty bad, if it's a react library it should be using useRef or the class equivalent or something.
> > I can see the form uses a ref internally, but I can't see a ref prop to access the form.
> 
> Yeah, I ended up using a ref on my project as well.

I didn't use a ref. I had to find the element by Id and manually add an event listener.

Its super annoying it doesn't have a ref attached to the form which devs can use. It's used internally, but it's not exposed via a prop.

I wanted to attach a ref via useRef the form should then be exposed but that's not possible.
