### ISSUE TITLE
readOnly field is not stripped onSubmit

### ISSUE THREAD

**Issue by Morriz** [rjsf-team/react-jsonschema-form#2362]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Hi, when rendering a schema which has a `readOnly` prop in version `2.5.1`, this prop is not rendered, which is great. But `onSubmit` this value does not get stripped from the payload, which it should imo. Maybe this is by design but I see it as a bug. Feel free to reclassify.

It would be awesome if this could be made configurable, as a lot of people would otherwise have to create custom logic to do this, while it could be centralized in rjsf forms.

**Comment by MrX8503** [comment]
[HTML attribute: readonly](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly)

It's by design.

**Comment by Morriz** [comment]
I am talking about jsonschema generated api that does not expect those props. As such this can be seen as a design flaw...
