### ISSUE TITLE
Label undefined for Multiselect ArrayField

### ISSUE THREAD

**Issue by Parnswir** [rjsf-team/react-jsonschema-form#2378]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

JSFiddle: https://jsfiddle.net/f7xjq935/

### Description

While implementing a highly customized rjsf in my current project, I use the `label` prop within the custom widgets to do some i18n / metadata lookup to render the widgets correctly (In essence, all forms are user-generated and the translated labels are provided by a third party). This works surprisingly fine.

However, with an array field with unique items (aka Multiselect), the `label` prop of the custom widget is `undefined` and no other prop can be used as a fallback (as far as I can see) to determine the name of the property in the schema.

I have looked into the code and noticed, that in https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/fields/ArrayField.js#L542, `label` is in fact undefined (it's not part of the ArrayField props). However, there's the `name` prop, which is not being used (and contains exactly what I need).

Is this a bug or expected behavior? Would it be appropriate to set `label = this.props.name`?

JSFiddle: https://jsfiddle.net/f7xjq935/

### Steps to Reproduce

1. Override `SelectWidget` with a custom component that renders the `label` prop
2. Render a form with an enum field (successfully renders the label) and an array field (label = undefined)
3. Be confused

### Version

2.5.1

**Comment by Parnswir** [comment]
Bump. If someone with knowledge of the internals could comment on my question, I would attempt to create a PR for this.

**Comment by epicfaace** [comment]
What are `label` and `name` usually equal to for normal (non-multiselect)
array fields?

--
Ashwin Ramaswami

**Comment by Parnswir** [comment]
My [updated jsFiddle](https://jsfiddle.net/rx6m8atn/) suggests `label` is the key of the schema property. Other array variants use the [`name` prop](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/fields/ArrayField.js#L463), while the multi select does not mention `name` and instead [destructures the undefined `label` attribute](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/fields/ArrayField.js?rgh-link-date=2021-05-12T07%3A56%3A20Z#L542).

To me it looks like an internal confusion of attributes at some point I cannot see right now, but to be honest, I'm not quite sure what exactly the `label` should be when we also have `title` for, well, the title of a field and `name` for the field's name in the schema.

**Comment by epicfaace** [comment]
It looks like @fsteger added that line (label={label}) in
https://github.com/rjsf-team/react-jsonschema-form/pull/1301. I did note at
that time that "label" wasn't used at all. I'm guessing the way to fix this
is that "title" should actually be passed into the "label" prop. Does that
seem right to you?

--
Ashwin Ramaswami

**Comment by Parnswir** [comment]
I've created a PR that solves the problem for me. I don't know if this has any practical implications for anyother use case though. All tests pass.
