### ISSUE TITLE
Not able to apply uiSchema customizations or custom widgets to properties in additionalProperties of an object.

### ISSUE THREAD

**Issue by vinitasher** [rjsf-team/react-jsonschema-form#2380]
### Prerequisites

- [ x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Custom widgets are not rendered in additional properties of an object.

### Steps to Reproduce

JSFiddle: https://jsfiddle.net/vinitasher/4u6yxhj9/1/

#### Expected behavior

Expect to be able to use custom widgets and other customizations using UI-Schema in properties rendered by additionalProperties of an object.

#### Actual behavior

It always only renders 2 input fields without providing any way to customize this.

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by AndrewWUw** [comment]
Try define uiSchema like this:

```
const uiSchema = {
  description: {
    "ui:widget": "textarea"
  },
  tags: {
    additionalProperties: {
      "ui:title": "New Key", //does not work
      "ui:widget": "CheckboxWidget" //cannot use widgets for properties in additional properties
    }
  }
};
```

**Comment by vinitasher** [comment]
Thanks @AndrewWUw that works!
