### ISSUE TITLE
Programatically triggering validation does not render error state of the fields

### ISSUE THREAD

**Issue by litzebauer** [rjsf-team/react-jsonschema-form#2381]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When I called `Form#validate` I get back the errors but the fields themselves are not showing the error messages. Is that the expected behavior? If so, how can I programmatically trigger validation that will have the form fields show the error state?

**Comment by heath-freenome** [comment]
Fixed in the v5 beta.9
