### ISSUE TITLE
Create custom fields with info option

### ISSUE THREAD

**Issue by Aditi-1400** [rjsf-team/react-jsonschema-form#2389]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Hey, I have used rjsf for a project I am working on, so I was wondering if there was a way to add info button in form fields, something of the form: 
![image](https://user-images.githubusercontent.com/62544124/119129626-cc261880-ba54-11eb-96c3-3bb7af997724.png)

**Comment by j-zimnowoda** [comment]
I am also interested in this feature. Could you recommend us the best approach for that issue?

**Comment by epicfaace** [comment]
Yeah, I think you'd have to create a custom widget for this instead. You can see this for an example: http://docs.chinmayamission.com/cff/uischema/widgets/infoboxRadioWidget/ and https://github.com/Chinmayamission/CFF/blob/master/scripts/src/form/form_widgets/InfoboxRadioWidget.tsx#L34-L40
