### ISSUE TITLE
Array Field Template not rendering correctly in 2.5.1

### ISSUE THREAD

**Issue by shafeequa** [rjsf-team/react-jsonschema-form#2391]
### Prerequisites

- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Not able to input values .
Same as issue  #1572 .

#### Expected behavior
Want the array fields to  allow the user to type in the dynamically created condition text box.
 
#### Actual behavior

The array fields do not allow the user to type in the dynamically created condition text box. It only takes in the first character entered and then is lost.

### Version

2.5.1

**Comment by jacqueswho** [comment]
fixed in later version

**Comment by shafeequa** [comment]
Thanks @jacqueswho
