### ISSUE TITLE
Add deprecate warning for react-jsonschema-form npmjs

### ISSUE THREAD

**Issue by phatNfqAsia** [rjsf-team/react-jsonschema-form#2392]
### Prerequisites

- [✅] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

From npmjs: https://www.npmjs.com/package/react-jsonschema-form. The version is **1.8.1**
And there is no deprecation warning to say about the moving to https://www.npmjs.com/package/@rjsf/core

I only know about the new package name when I check the releases in the github repo. So to avoid these incidents, please add the **deprecation warning** to the old npmjs site as this instruction: https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions

**Comment by heath-freenome** [comment]
@epicfaace Do you have the ability to make this change?

**Comment by heath-freenome** [comment]
@epicfaace Can you please do this ASAP?! I'd hate for people to not realize they are using terribly ancient code

**Comment by nickgros** [comment]
This is done.
