### ISSUE TITLE
formContext is undefined when using a custom schemaField

### ISSUE THREAD

**Issue by snowbambo** [rjsf-team/react-jsonschema-form#2394]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

First of all sorry if this is not the correct way of posting, I am not used to that so please tell me if I do anything wrong.

So I'm trying to use a custom SchemaField and according to the documentation I'm supposed to be able to use the same props as the one in a custom field. But while I am able to retrieve the formContext property on all of my custom code (custom widget and custom object field template), it is always undefined when I try to use it in the custom SchemaField.

### Steps to Reproduce

1. create a custom SchemaField
2. create a formContext with some property 
3. provide the custom schemaField and the formContext to the form

#### Expected behavior

formContext should not be undefined in the custom schemaField

#### Actual behavior

formContext is undefined

### Version

rjsf/core: 2.4.1

```javascript
const CustomSchemaField = (props: any) => {

	const { onChange, name, formContext } = props;

	//here the formContext is undefined
	console.log(formContext)

	return (
		<SchemaField {...props} />
	)
}
```

**Comment by heath-freenome** [comment]
Fixed in v5 beta via https://github.com/rjsf-team/react-jsonschema-form/pull/3040
