### ISSUE TITLE
onSubmit prop misbehaving (Resets formData and validation error messages are set even though it's a valid payload).

### ISSUE THREAD

**Issue by AlexMachin1997** [rjsf-team/react-jsonschema-form#2395]
Hi everyone,

**Issue:**

When the formData is set inside of the onSubmit it clears the formData.

When the formData is set it re-runs the validation, and even though the formData is valid it shows invalid messages.

**Notes:**

I'm not sure why this is happening, it seems bizzare though It might be something specifc to my project. After all the schema is enormous.

I have a sick feeling it might be to do with the Form.js UNSAFE_componentWillReceiveProps() though I can't say 100% as there is so much going on with this library it's difficult to pin point where it's going wrong for me.

Any guidance would be greatly appreciated

**Comment by ecojuntak** [comment]
Hi @AlexMachin1997,
I also face this issue and I found work around solution for this issue. Can you share your code here so I can understand your use case?

**Comment by AlexMachin1997** [comment]
Hi @ecojuntak 

Sadly I can't share any code as it's on my work laptop.

How did you get around the issue ? Did you use the useRef hook

**Comment by ecojuntak** [comment]
The point that I want to achieve here is to keep the form data state for every time it changed.

```ts
import {useState} from "react";
import {withTheme} from '@rjsf/core';
import {Theme as AntDTheme} from '@rjsf/antd';

const JSForm = withTheme(AntDTheme);

const YourComponent = ({}) => {

    const [formData, setFormData] = useState<object>()

    const onFormDataChanged = (formState) => {
        setFormData(formState.formData)
    }

    const onFormDataSubmit = () => {
        console.log(formData)
    }

    return (
        <>
            <JSForm schema={schema}
                    formData={formData}
                    onSubmit={onFormDataSubmit} 
                    onChange={onFormDataChanged}
                    liveValidate/>
        </>
    )
}

export default YourComponent
```

**Comment by ljwagerfield** [comment]
Great tip on using `liveValidate={true}` to workaround this issue, @ecojuntak!

Whilst I don't want live validation on by default, I've found that if I set it to `true` only after the first failed submission, I get quite a nice behaviour that is consistent with the other forms in my app -- i.e. validation only becomes "live" after the form has been submitted with errors:

```typescript
import {useState} from "react";
import {withTheme} from '@rjsf/core';
import {Theme as AntDTheme} from '@rjsf/antd';

const JSForm = withTheme(AntDTheme);

const YourComponent = ({}) => {

    const [formData, setFormData] = useState<object>()
    const [invalidFormDataAttempted, setInvalidFormDataAttempted] = useState(false);

    const onFormDataChanged = (formState) => {
        setFormData(formState.formData)
    }

    const onFormDataSubmit = () => {
        console.log(formData)
    }

    return (
        <>
            <JSForm schema={schema}
                    formData={formData}
                    onSubmit={onFormDataSubmit} 
                    onChange={onFormDataChanged}
                    onError={_ => setInvalidFormDataAttempted(true)}
                    liveValidate={invalidFormDataAttempted}/>
        </>
    )
}

export default YourComponent
```

**Comment by ecojuntak** [comment]
Hi @ljwagerfield, your example is really great. I agree this is a better behavior since you activate the live validate once you submit it.

But the main workaround for this issue is when you store the `formData` to state, not the `liveValidate={true}`.

**Comment by ljwagerfield** [comment]
@ecojuntak on `3.0.0` (at least for me) simply making the `Form` a controlled component (by providing both `formData` and `onChange`, and storing the state yourself) did not fix the issue: the form's error list would disappear (once the user corrected the values), but the errors beneath each field would remain.

Enabling `liveValidate` was the only thing that ensured the errors under the fields get cleared too, but obviously has the unwanted side effect of also making the form live-validate.

Hence why my solution only enables live-validate when it's really needed: after the errors are first displayed -- thus giving the user a nicer experience on the happy path.
