### ISSUE TITLE
default theme: ui:title renders 3 times in different locations

### ISSUE THREAD

**Issue by Morriz** [rjsf-team/react-jsonschema-form#2401]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] I'm providing a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJzb3BzIjp7ImFQcm9wIjp7fX0sImZpcnN0TmFtZSI6IkNodWNrIiwibGFzdE5hbWUiOiJOb3JyaXMiLCJhZ2UiOjc1LCJiaW8iOiJSb3VuZGhvdXNlIGtpY2tpbmcgYXNzZXMgc2luY2UgMTk0MCIsInBhc3N3b3JkIjoibm9uZWVkIn0sInNjaGVtYSI6eyJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2UsInByb3BlcnRpZXMiOnsic29wcyI6eyJ0aXRsZSI6IlRFU1QgVGlUTEUiLCJkZXNjcmlwdGlvbiI6IlRFU1QgREVTQ3JJUFRJT04iLCJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJhUHJvcCI6eyJwcm9wZXJ0aWVzIjp7Im5lc3RlZFByb3AiOnsidHlwZSI6InN0cmluZyJ9fSwicmVxdWlyZWQiOlsibmVzdGVkUHJvcCJdfX19LHsicHJvcGVydGllcyI6eyJiUHJvcCI6eyJwcm9wZXJ0aWVzIjp7ImFub3RoZXJOZXN0ZWRQcm9wIjp7InR5cGUiOiJzdHJpbmcifX19fX1dfX19LCJ1aVNjaGVtYSI6eyJzb3BzIjp7InVpOnRpdGxlIjoiVEVTVCBUaVRMRSJ9fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==) demonstrating the issue.

**Comment by heath-freenome** [comment]
@Morriz Is this still an issue? I only see it rendering twice. Maybe it should only be once?
