### ISSUE TITLE
NOTICE: How you (or your company) can support rjsf's development

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#2418]
Update May 2022 -- We now have an open collective! Consider supporting us here: https://opencollective.com/react-jsonschema-form

---

For additional context on rjsf's history, I began maintaining this library in 2019. Before that, it was created and owned by Mozilla, but it had really fallen into disuse -- no one was really merging PRs and releases were rarely happening. I just contacted the maintainers and offered to help out. Eventually, we moved it over to the rjsf-team organization, as the rjsf maintainers at Mozilla were just happy to have someone else (me) maintain the project (see #1440).

Over time, rjsf has just become one of a dozen other projects I'm working on, and it's unpaid, so I really only have limited bandwidth to work on this project (regularly merging some PRs, keeping releases going, etc.). There are two solutions to this:

- Get more maintainers, i.e., people who can review PRs and provide good feedback to ensure the code base has good code. See #1757. A couple people have signed up to help (and have been great and super helpful!) but no one other than me has yet had the time to consistently review the PRs that keep coming in to the project (understandably -- it's a lot of free work). If you're interested in helping, let me know!
- Make it easier for me to work on your issue by sponsoring me! Obviously, I'm still maintaining this library for free and will likely get to major bug fixes / issues eventually, but if you / your company would like me to put in more effort than just what I can manage in my free time, the most sustainable way would be to sponsor me: https://github.com/sponsors/epicfaace/

**Comment by dwjohnston** [comment]
@epicfaace  If you open an Open Collective account for the project - I'll put in $5/month

**Comment by dwjohnston** [comment]
Hey consider opening an account at Open Collective. I'm sponsoring you here regardless - but Open Collective is my usual go to.

**Comment by epicfaace** [comment]
That's a really good point! Will look into doing that.

**Comment by epicfaace** [comment]
We have an open collective now! https://opencollective.com/react-jsonschema-form
