### ISSUE TITLE
How to implement Country -> State-> City Dropdown list?

### ISSUE THREAD

**Issue by xiaoronglv** [rjsf-team/react-jsonschema-form#2419]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I would like to implement a Dropdown list for the employee to fill out the country, state, and city. It seems the only way to implement it is `dependency`, which will generate a very complicated JSON.

![image](https://user-images.githubusercontent.com/1224077/120757344-073f4600-c543-11eb-934d-94dfb156df3d.png)

Here is the demo code.

https://codesandbox.io/s/fervent-cherry-lokjk?file=/src/App.js

**Is there a cleaner way to implement it?**

## Reference

1. a similar question: https://github.com/rjsf-team/react-jsonschema-form/issues/1047
2. https://stackoverflow.com/questions/65597922/how-to-create-a-typical-country-province-or-state-dependency-dropdowns-with-re

**Comment by xiaoronglv** [comment]
Here is the demo code.

https://codesandbox.io/s/fervent-cherry-lokjk?file=/src/App.js

**Comment by saadq** [comment]
The way we're handling this on my team is by using a dynamic schema. Meaning we don't keep all the countries/states as hardcoded dropdown values but we have an API that returns these values. When the user changes the country, we fetch the new countries states and then dynamically update the `enum` for the states with the API response.

**Comment by xiaoronglv** [comment]
> The way we're handling this on my team is by using a dynamic schema. Meaning we don't keep all the countries/states as hardcoded dropdown values but we have an API that returns these values. When the user changes the country, we fetch the new countries states and then dynamically update the `enum` for the states with the API response.

Hi @saadq 

Thanks for your insights.

We used to consider this approach, but didn't find any hooks or standard interface provided by react-jason-schema to do it.

have you implement it though hacking this library?

Could you please provide some pseudo code or explain more details?

**Comment by Maikel-Nait** [comment]
You can achieve it by using [rjsf-conditionals](https://github.com/ivarprudnikov/rjsf-conditionals) package.
This package allows you to add some additional JSON rules to trigger javascript events when some form component changes.
You can use a customized javascript function to fetch new enum values and replace the options of a select box dynamically.
I've done it in my current project and it works.  Just FYI

**Comment by tejaswiMinnu** [comment]
Maikel-Nait
can you share the code or example for customized javascript function to fetch new enum values and replace the options of a select box dynamically.

**Comment by Maikel-Nait** [comment]
Will try to drop an example on codesandbox in the following days (currently on vacation)

**Comment by jcalfee** [comment]
Updating a datalist in the browser seems problematic > https://stackoverflow.com/q/26610752

**Comment by Maikel-Nait** [comment]
> I went through and tried out **rjsf-conditionals** but found out they are in maintenance mode and don't support async: [ivarprudnikov/rjsf-conditionals#342 (comment)](https://github.com/ivarprudnikov/rjsf-conditionals/issues/342#issuecomment-1030827469). I would love to hear about it. The more options the better. My test confirms that comment, my returned Promise was ignored.
> 
> Async dropdowns are pretty common, there must be an example somewhere and maybe we can include that in the docs..

You are right. Async does not work.  I actually perform some pre-loading of all the data needed for all the dropdown options into an object (kind of hashmap), and then replace the enum data with the correct values taken from my object, based on the selected dropdown value.  It works perfectly, as long as you are not using dropdowns with thousands of values to preload.  I tried to upload a sample to codesandbox, but I'm getting issues having a simple demo to work (I can't use my real code for security reasons). Hoperfully sooner or later I will have it working

**Comment by bansi112** [comment]
import React, { useState } from 'react';

const stateCityMap = {
  usa: {
    california: ["Los Angeles", "San Francisco"],
    texas: ["Houston", "Austin"],
  },
  canada: {
    ontario: ["Toronto", "Ottawa"],
    quebec: ["Montreal", "Quebec City"],
  },
};

function Menu() {
  const [selectedCountry, setSelectedCountry] = useState('');
  const [selectedState, setSelectedState] = useState('');

  const countries = Object.keys(stateCityMap);
  const states = selectedCountry ? Object.keys(stateCityMap[selectedCountry]) : [];
  const cities = selectedState ? stateCityMap[selectedCountry][selectedState] : [];

  const handleCountryChange = (event) => {
    setSelectedCountry(event.target.value);
    setSelectedState('');
  };

  const handleStateChange = (event) => {
    setSelectedState(event.target.value);
  };

  return (
    <div>
      <label htmlFor="country">Select Country:</label>
      <select id="country" onChange={handleCountryChange} value={selectedCountry}>
        <option value="">Select a country</option>
        {countries.map(country => (
          <option key={country} value={country}>{country}</option>
        ))}
      </select>

      {selectedCountry && (
        <div>
          <label htmlFor="state">Select State:</label>
          <select id="state" onChange={handleStateChange} value={selectedState}>
            <option value="">Select a state</option>
            {states.map(state => (
              <option key={state} value={state}>{state}</option>
            ))}
          </select>

          {selectedState && (
            <div>
              <label htmlFor="city">Select City:</label>
              <select id="city">
                <option value="">Select a city</option>
                {cities.map(city => (
                  <option key={city} value={city}>{city}</option>
                ))}
              </select>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default Menu;
