### ISSUE TITLE
Stuck while working with Custom Widgets and Fields

### ISSUE THREAD

**Issue by Aditi-1400** [rjsf-team/react-jsonschema-form#2421]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Hey everyone, I've been working with RJSF and I wish to use custom widgets and fields for my form. 
Ideally I wish to have an onChange functionality for each field, so I can fetch field values as soon as it is changed using event.target.value. Passing the onChange prop to entire form doesn't provide this functionality, so I wish to use custom fields for that.
The problem I am encountering is that I am unable to get the desired data in the custom field.
For example:
```
const CustomSelect = function(props){
    return(
      <select id="input"
      value={props.value}
      schema={props.schema}
      onChange={(e) => console.log(e.target.value)}
      >
      </select>
    )
  }
  const widgets = {
    SelectWidget: CustomSelect
  }
```
That's my custom select widget which I am passing to the form as:
```
<Form schema={schema} 
      widgets={widgets}  
      onSubmit={onSubmit} 
      formData={formData} />
```
And my schema looks like:
```
"vendor": {
  "title": "XYZ",
  "name":"XYZ",
  "description": "description",
  "type": "string",
  "enum": [
      "A",
      "B",
      "C",
      "D",
      "E",
      "F",
      "G",
      "H"
       ....
```
The output I am receiving after this is a simple dropdown without any data. 
![Screenshot from 2021-06-06 15-43-05](https://user-images.githubusercontent.com/62544124/120920757-0a226e00-c6de-11eb-8131-644951b8a042.png)

Can someone tell me what am I doing wrong, or if there's a better way of providing the desired functionality.

Thank you :))

**Comment by epicfaace** [comment]
I think this is because you are using a plain HTML <select> tag, which
doesn't support just setting the value / using onChange as what you created
yourself. You'd have to instead add <option> tags for each possible option
(see https://reactjs.org/docs/forms.html#the-select-tag).

I'd recommend instead of a HTML <select> tag, using a library like
react-select (https://react-select.com/home) -- this does support value /
onChange as what you're using and should just be a drop-in replacement with
what you're already using.

--
Ashwin Ramaswami

**Comment by Aditi-1400** [comment]
Oh that worked, thank you so much! :))

**Comment by Aditi-1400** [comment]
Hey, this worked, but I need some additional functionality, I need to modify the formData, depending upon the value from dropdown, i.e, if I select the value of one field, I would like to autofill another field depending upon that value, is that possible?

**Comment by epicfaace** [comment]
Closing this as we are talking about this on Discord.
