### ISSUE TITLE
Add 2.x migration guide to the docs

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#2423]
We have a 1.x -> 2.x migration guide here (https://github.com/rjsf-team/react-jsonschema-form/releases/tag/v2.0.0), but we should add it to the docs so that it's easier to find.

**Comment by wegry** [comment]
Would this be the same as what I did for the 2 -> 3 migration doc?

**Comment by epicfaace** [comment]
Yes, exactly!

--
Ashwin Ramaswami
