### ISSUE TITLE
[Material-UI] [Date field] Change the date format from 'mm-dd-yyyy' to 'dd-mm-yyyy'

### ISSUE THREAD

**Issue by mimiski** [rjsf-team/react-jsonschema-form#2425]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I'd like to change the date format from 'mm-dd-yyyy' to 'dd-mm-yyyy'. How to do that?

### Steps to Reproduce

1. Create a date field ({type: "string', format: "date"}).
2. The field's format is 'mm-dd-yyyy'. How to change it to 'dd-mm-yyyy'?

A minimal example: https://jsfiddle.net/fLzewap2/9/

Best regards,
Kuba

**Comment by epicfaace** [comment]
For the bootstrap theme, we just use a plain HTML5 input. This displays the date format based on the user's locale (so it can be dd-mm-yyyy for some locales, but mm-dd-yyyy for others). See https://stackoverflow.com/questions/7372038/is-there-any-way-to-change-input-type-date-format

If you want to force it to say "dd-mm-yyyy", your best bet is to create a custom widget that does this. There might also be other options in other themes that allow you to change the format, but I'm not sure exactly about if they exist.

**Comment by mimiski** [comment]
@epicfaace Thanks for the quick response.
According to https://stackoverflow.com/questions/46543391/change-formatdate-in-datepicker-of-material-ui, in plain Material-UI you should use
```
<Field
      name="dateFrom"
      component={DatePicker}
      [...]
      formatDate={(date) => moment(date).format('DD-MM-YYYY')}
/>
```
Is there a way to pass on the `formatDate={(date) => moment(date).format('DD-MM-YYYY')}`  argument in RJSF schema/UI schema without implementing a separate widget?

**Comment by epicfaace** [comment]
That's not possible at the moment, though it will be possible after https://github.com/rjsf-team/react-jsonschema-form/issues/1647 / https://github.com/rjsf-team/react-jsonschema-form/pull/1672 are resolved / merged.

**Comment by mimiski** [comment]
I see, thanks.
