### ISSUE TITLE
Add Bootstrap 5 theme

### ISSUE THREAD

**Issue by wegry** [rjsf-team/react-jsonschema-form#2428]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

`react-bootstrap` is in an early beta to support `bootstrap@5`. Copying the existing bootstrap 4 package seems like it would be a good way to start the move over. CSS classes are probably the biggest hurdle.

**Comment by epicfaace** [comment]
That's true -- though do you know how drastic the changes are? If it's only
a couple of class changes, would it be possible to maybe have a more
efficient way of creating themes rather than having to copy a theme
codebase for each new version of Bootstrap?

--
Ashwin Ramaswami

**Comment by wegry** [comment]
I was thinking we'd need react-bootstrap@2 and to change class names around bootstrap 5. This codebase already has a different bootstrap 3 / 4 theme (@rjsf/core and @rjsf/bootstrap-4, respectively).

Bootstrap itself changes -> https://getbootstrap.com/docs/5.0/migration/.
React-bootstrap changes -> https://github.com/react-bootstrap/react-bootstrap/blob/master/CHANGELOG.md

**Comment by nurikk** [comment]
bootstrap 4 and 5 are quite backward compatible, I have project with bootsrap5 and rjsf, everything works fine

**Comment by camsjams** [comment]
Yes for the most part bootstrap is fine on 4/5
