### ISSUE TITLE
Problem with custom field state and formData not agreeing / being in sync

### ISSUE THREAD

**Issue by Realtimeknowledge** [rjsf-team/react-jsonschema-form#2432]
### Prerequisites

**Yes**, I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers - **Not sure this is a bug**

I'm providing a pen to show the problem:  **https://codepen.io/Feezercat/pen/eYvaZKz**

### Description

I have created a custom field component to act as a numeric counter. The schema can provide multiple items to count and each item will render a numeric counter with an input field.  These are accompanied by a plus and minus buttons which will increment the counter in defined units. The incremental units are set using a shared set of units buttons. Sight of the pen provided will clearly explain the counters function.

Initially I thought that the component was completed and all was OK, but on further testing I find that there is a problem.

I am new to react and rjsf so it's most likely me. but I thought I'd got it right and on first test I thought I had nailed this.

### Steps to Reproduce

1.  Go to the pen example at: **https://codepen.io/Feezercat/pen/eYvaZKz**
2.  Pick 1s, 10s or 100s increments and have fun counting chickens or other animals. Importantly remember the value of the last item you increment or decrement.
3. Click the Submit button. The formData will be shown above the form.
4. As an example if I count chickens up to 40 and then ferrets up to 30, with the last click being to increment ferrets from 20 to 30 then the formData will only show the data/state value from the previous click of the button. So the field may say 30 but the data still shows 20.    

#### Expected behavior

In the increment and decrement functions I set the state of the component and would expect the formData to remain in sync with the state. 

#### Actual behavior

The component state reflects the same state as the UI, but the last value stored in the formData remains the previous value. Which will result in their always being at least one data item in my counter being invalid when submitted to the db.

### Version

**PEN Versions**
The pen is using a cdn so I would assume it is the latest: https://unpkg.com/@rjsf/core/dist/react-jsonschema-form.js 

The pens React versions are:
https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.13.1/umd/react-dom.production.min.js
https://cdnjs.cloudflare.com/ajax/libs/react/16.13.1/umd/react.production.min.js

**Project Versions**
My project and package.json, which behaves the same as the pen is using:

        "@rjsf/core": "^2.5.1",
        "@rjsf/material-ui": "^2.5.1",
        "react": "^17.0.2",
        "react-dom": "^17.0.2"

**Comment by Realtimeknowledge** [comment]
Can anyone please help with this?

**Comment by epicfaace** [comment]
I'm not quite sure, but maybe it has to do with the fact that you're mutating state? Can you try removing that and ensure state is never mutated, and see if the issue still persists?

![image](https://user-images.githubusercontent.com/1689183/124136350-b55ee280-da52-11eb-85f8-9279c166330e.png)


Also, because of #2447, you have to change it to import https://unpkg.com/@rjsf/core@2.5.1/dist/react-jsonschema-form.js to make the codepen work again (otherwise, it's blank since v3 was released).

**Comment by Realtimeknowledge** [comment]
@epicfaace Thanks very much for the reply and taking time to look into the pen. 

I have updated the pen as you suggest so that it now works and uses 2.5.1.

Sorry I'm new to RJSF and React itself. If I remove the lines you suggest then the counter won't count up/increment any longer. How would you approach incrementing the value, which is the goal of the counter and at the same time not mutate the state? 

Counting animals may seem a bizarre example. The reality is this is intended for counting parts in a manufacturing context.

Any help gratefully accepted.

**Comment by epicfaace** [comment]
I just took a further look at this and I think I found the issue! It seems like the problem isn't actually about mutating state. It's that `setState` is asynchronous. This means that `this.state` will not be immediately updated after you call `this.setState`. Instead, you have to call `onChange` in a callback function passed as the second argument to `this.setState`:

![image](https://user-images.githubusercontent.com/1689183/124293889-1ce56280-db25-11eb-9e24-3be3172b6f6f.png)

Here's a working codepen that updates both instances of this issue, in both the `increment` and `decrement` functions:

https://codepen.io/epicfaace/pen/WNjvBrb

Here's a website that explains better about this issue and how to fix it: https://sentry.io/answers/forget-set-state-is-async/

Hope this helps!

**Comment by epicfaace** [comment]
If you really wanted to not mutate the state, you could do something like this, which uses the spread operator:

![image](https://user-images.githubusercontent.com/1689183/124294224-7057b080-db25-11eb-805a-b535661a5790.png)

This is probably best practice, but it doesn't seem to be causing this particular issue -- so if you just add the callback function I mentioned in my previous comment, you should be all good!

**Comment by Realtimeknowledge** [comment]
@epicfaace 

Thank you very much indeed, this is a big help. It was a niggling problem that was driving me mad! I have implemented it in the project and the bug is fixed now : ) 

I have sponsorship you via GitHub, I hope others do too, you're doing a great job maintaining this project.

Many thanks
