### ISSUE TITLE
How to import css styling to forms created with @rjsf/fluent-ui package within a VS Code extension?

### ISSUE THREAD

**Issue by chelsiemb** [rjsf-team/react-jsonschema-form#2434]
### Prerequisites

- [Yes] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I am currently working to create a VS Code extension that reads in JSON schemas and renders forms created with @rjsf/fluent-ui package. Currently, my forms are rendering in the Extension Development Host of VS Code but without the css styling of fluent-ui. This problem only occurs within my VS Code extension and not in regular React applications that render to the browser. I am following all the steps outlined in the "Getting Started" section of the @rjsf/fluent-ui documentation. Could my use of ReactDOMServer.renderToString() in converting my Form component into HTML string be messing with the class names and other tags and therefore not allow for the css styling?

### Version

I have the latest versions of all required packages.

**Comment by epicfaace** [comment]
What was your solution?

**Comment by chelsiemb** [comment]
I began using the office-ui-fabric-js library instead to style my Form component because rendering the Form in the browser and inspecting its elements revealed that it was using classes from the office-ui-fabric-js library such as ms-Button and ms-CheckBox. I'm not too sure why that would be the case since my Form component is from @rjsf/fluent-ui.
