### ISSUE TITLE
alt-date select boxes do not change value

### ISSUE THREAD

**Issue by paintedbicycle** [rjsf-team/react-jsonschema-form#2440]
What I believe to be an issue with the v3 of rjsf, alt-date module select box values cannot be changed.

You can see it in the playground [here](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJuYXRpdmUiOnt9LCJhbHRlcm5hdGl2ZSI6e319LCJzY2hlbWEiOnsidGl0bGUiOiJEYXRlIGFuZCB0aW1lIHdpZGdldHMiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJuYXRpdmUiOnsidGl0bGUiOiJOYXRpdmUiLCJkZXNjcmlwdGlvbiI6Ik1heSBub3Qgd29yayBvbiBzb21lIGJyb3dzZXJzLCBub3RhYmx5IEZpcmVmb3ggRGVza3RvcCBhbmQgSUUuIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZGF0ZXRpbWUiOnsidHlwZSI6InN0cmluZyIsImZvcm1hdCI6ImRhdGUtdGltZSJ9LCJkYXRlIjp7InR5cGUiOiJzdHJpbmciLCJmb3JtYXQiOiJkYXRlIn19fSwiYWx0ZXJuYXRpdmUiOnsidGl0bGUiOiJBbHRlcm5hdGl2ZSIsImRlc2NyaXB0aW9uIjoiVGhlc2Ugd29yayBvbiBtb3N0IHBsYXRmb3Jtcy4iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJhbHQtZGF0ZXRpbWUiOnsidHlwZSI6InN0cmluZyIsImZvcm1hdCI6ImRhdGUtdGltZSJ9LCJhbHQtZGF0ZSI6eyJ0eXBlIjoic3RyaW5nIiwiZm9ybWF0IjoiZGF0ZSJ9fX19fSwidWlTY2hlbWEiOnsiYWx0ZXJuYXRpdmUiOnsiYWx0LWRhdGV0aW1lIjp7InVpOndpZGdldCI6ImFsdC1kYXRldGltZSIsInVpOm9wdGlvbnMiOnsieWVhcnNSYW5nZSI6WzE5ODAsMjAzMF19fSwiYWx0LWRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGUiLCJ1aTpvcHRpb25zIjp7InllYXJzUmFuZ2UiOlsxOTgwLDIwMzBdfX19fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

(Try to change the select boxes for the date in the alt-date widget)

**Comment by epicfaace** [comment]
This is probably a regression from https://github.com/rjsf-team/react-jsonschema-form/pull/2339 (cc @jimmycallin )

**Comment by jimmycallin** [comment]
Sounds like my fault, I'll take a look at it!
