### ISSUE TITLE
Could please give me idea about patternProperties schema?

### ISSUE THREAD

**Issue by woodyu995** [rjsf-team/react-jsonschema-form#2444]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
Hello,
I want use patternProperties of json Schema. But this schema is not support.
So in order to solve this problem, I use Custom Fileds.
My idea is below.
Generate Custom Field compoent. It is generate form using &lt;Form>. 
In time passed patternProperties schema from main. 
And using this component at uiSchema of main component .
But this idea have problem. It is pop warning" &lt;form> connot appear as a descendant of &lt;form>". 
I think this problem's caouse is that patternProperties form nested with main form.
So html is below.

&lt;html>
&nbsp;&nbsp;&nbsp;&nbsp; &lt;head>
&nbsp;&nbsp;&nbsp;&nbsp; &lt;/head>
&nbsp;&nbsp;&nbsp;&nbsp; &lt;body>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;form......>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;....
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;form...>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/form>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/form>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/body>
&lt;/html>

Could please give me idea to solve this problem?
thanks.

### Version
@rjsf/core : ^2.5.1
@react: ^17.0.2
You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by epicfaace** [comment]
You can use `tagName` to create a non-<form> element, so that you don't
have <form> elements nested in other <form> elements.
https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/form-props/#tagname

--
Ashwin Ramaswami

**Comment by woodyu995** [comment]
> You can use `tagName` to create a non-<form> element, so that you don't have <form> elements nested in other <form> elements. https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/form-props/#tagname
> […](#)

Thanks
