### ISSUE TITLE
Bug that causes VS Code extension to fail due to deprecated variable in library.

### ISSUE THREAD

**Issue by chelsiemb** [rjsf-team/react-jsonschema-form#2446]
### Prerequisites

- [Yes] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

This is a bug. I am currently working to create a VS Code extension that renders forms created with the @rjsf/fluent-ui package. In my extension, I read in JSON schemas that define Site Builder module definitions and render them to an HTML string using the ReactDOMServer.renderToString() method. Then I concatenate them to the HTML string that gets rendered by my extension. When I run my extension, it fails with a reference error stating that "name is not defined". This variable is deprecated and can be found in @rjsf\fluent-ui\dist\fluent-ui.cjs.development.js on line 348. Removing this line allows my extension to run. Currently, I have deleted this line so that I can be unblocked and continue working on my intern project but I am interested to know if anything can be done about this bug.

### Steps to Reproduce

1. Create a VS Code extension.
2. Add a JSON schema + UI schema that are used to define a Site Builder module definition to the project and read them in.
3. Create a @rjsf/fluent-ui Form where the JSON schema + UI schema fill in the schema and uiSchema fields of the Form respectively.
3. Convert the Form into an HTML string using the ReactDOMServer.renderToString() method and concatenate to the HTML string that will be rendered by the extension.
4. Set a breakpoint at the line where the ReactDOMServer.renderToString() method is called and use the debugger to locate the error message.

#### Expected behavior

I expect the extension to render the form using the styling of the fluent-ui library.

#### Actual behavior

My extension fails with a reference error that states "name is not defined" as described above.

### Version

I have the latest version of all required packages.

**Comment by epicfaace** [comment]
Which version are you using of @rjsf/fluent-ui? Are you sure it's version 3? We had a problem like this earlier but it was fixed.

If so, can you send in the couple of lines around line 348 (and including line 348) so we can see which part of the source code is causing this issue?

**Comment by chelsiemb** [comment]
I am using version 2.5.1 of @rjsf/fluent-ui. How can I update my version?

This is the chunk of code: 
  var inputType = schema.type === 'string' ? 'text' : "" + schema.type;
  return React.createElement(react.TextField, Object.assign({
    id: id,
    placeholder: placeholder,
    label: label || schema.title,
    autoFocus: autofocus,
    required: required,
    disabled: disabled,
    readOnly: readonly,
    name: name,
    type: inputType,
    value: value ? value : "",
    onChange: _onChange,
    onBlur: _onBlur,
    onFocus: _onFocus,
    errorMessage: (rawErrors || []).join("\n")
  }, uiProps));
};

**Comment by chelsiemb** [comment]
Disregard above, I just updated to the latest version (3.0.0) and all works fine!
