### ISSUE TITLE
ui:emptyValue does not work when initial data has an empty string

### ISSUE THREAD

**Issue by ssbyoung** [rjsf-team/react-jsonschema-form#2449]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

The method of providing a default value, putting a `ui:emptyValue` in the uiSchema does not fill out a default value.

SSCCE 
[rjsf-empty-value-issue.zip](https://github.com/rjsf-team/react-jsonschema-form/files/6735809/rjsf-empty-value-issue.zip)

![empty value does not work](https://user-images.githubusercontent.com/23528141/123854103-dead3080-d8e3-11eb-86c4-46fcfe953a51.PNG)

### Steps to Reproduce

1. Use ui:emptyValue

#### Expected behavior

The form should have the value of ui:emptyValue if the property is falsey.

#### Actual behavior

Form is still empty

### Version

3.0.0

**Comment by ssbyoung** [comment]
@epicfaace I'm not seeing emptyValue work in the default theme either.

**Comment by ssbyoung** [comment]
Based on the code it looks like the empty value is only filled when the user manually clears the input. However it does not handle the case when the initial data has an empty string.

**Comment by ssbyoung** [comment]
I've fixed this for all themes in https://github.com/rjsf-team/react-jsonschema-form/pull/2457

**Comment by epicfaace** [comment]
@ssbyoung so this is no longer an issue for you? Shall we close it then?
