### ISSUE TITLE
Can I add a custom `type`?

### ISSUE THREAD

**Issue by shreyamalviya** [rjsf-team/react-jsonschema-form#2464]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/).

### Description

Is it possible for me to add a custom `type`? From the documentation, I gather that it is possible for me to add a custom widget and override an already existing one, but I don't want to override. I'm wondering if there is a (hacky) way for me to create a new type and map it to a custom widget?

Alternatively, it would be nice to be able to provide a custom widget for the `null` type, or have some way for me to exclude the `title` field when I'm overriding one of `string`, `number`, `integer`, or `boolean`.

**Comment by epicfaace** [comment]
You can't do that, unless you fork the library. This library is meant to only be used with JSON Schemas according to the JSON Schema specification, which I believe doesn't support custom types.

You definitely could override some widgets, and I think you might be able to override TitleField, if that helps.
