### ISSUE TITLE
Does rjsf support using function component to custom widget?

### ISSUE THREAD

**Issue by MagicBoBo** [rjsf-team/react-jsonschema-form#2468]
### Prerequisites

- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

#### Description
I read the typescript definition of Widget, which is ` React.StatelessComponent<WidgetProps> | React.ComponentClass<WidgetProps>;`

I want to custom the ui of the form, but the ui library of my company is implemented by function component.

so does rjsf support function component?

**Comment by MagicBoBo** [comment]
I really want to use rjsf, because it supports the standard json schema well.

**Comment by epicfaace** [comment]
Yes, rjsf does support function components. Did you solve your issue?

**Comment by MagicBoBo** [comment]
yes, i solve my issue, sorry, i didn't read the document carefully
