### ISSUE TITLE
Only include MonacoWebpackPlugin in docs / playground build

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#2474]
https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/webpack.config.dist.js#L18

> I don't think this plugin is usable within a library. I'm almost certain that we're just incurring a build time cost with no usable change in output.
> 
> It makes sense for it to be available within the playground and docs though.

_Originally posted by @wegry in https://github.com/rjsf-team/react-jsonschema-form/pull/2470#discussion_r671875214_

**Comment by epicfaace** [comment]
@wegry how do you think this could be accomplished? I see that `playground/webpack.config.dist.js` already has `MonacoWebpackPlugin`, so I'm not sure how we could go about removing it from the `@rjsf/core` build https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/playground/webpack.config.dist.js#L20

**Comment by wegry** [comment]
@epicfaace unless the docs need their own copy of the plugin in a build, it looks like it can just be dropped from the packages/core/webpack.config.dist.js.

We use the monaco-webpack plugin at work and it adds a decent amount to the output of our project. But in core's case, it might not do anything.

Having it in core might just be an artifact of copying webpack.configs between packages.

**Comment by epicfaace** [comment]
Yeah, you could be right -- I initially thought it broke the build because the PR was failing (see https://github.com/rjsf-team/react-jsonschema-form/runs/3097423112), but maybe that was due to another issue. Do you want to try making a PR that removes it to see if the build passes?

**Comment by wegry** [comment]
I can't see build output for that Node 12 build like @epicfaace.

**Comment by epicfaace** [comment]
Yeah, I can't see build output for it either. Maybe a transient issue with GHA?

**Comment by epicfaace** [comment]
Fixed by #2476
