### ISSUE TITLE
Custom DescriptionField not working, Unable to render Icons with Description in Form

### ISSUE THREAD

**Issue by chelsiemb** [rjsf-team/react-jsonschema-form#2481]
### Prerequisites

- [Yes] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I am currently using the @rjsf/fluent-ui library to render Forms in the browser as part of an intern project. I created a custom DescriptionField to render Info icons with descriptions in my form but they do not seem to be working unless the property in question is of type: object. I am able to render icons with description if I simply render <DescriptionField description="foo" /> but not when I am trying to pass the DescriptionField into a Form using its fields prop. I've seen a couple other issues raised that are similar, and was wondering if there is a solution?

#### Expected behavior

<img width="285" alt="Screenshot (36)" src="https://user-images.githubusercontent.com/47193781/126426811-cdc4a18b-6f9c-490e-828a-ae95dbd5a73f.png">

#### Actual behavior

<img width="202" alt="Screenshot (37)" src="https://user-images.githubusercontent.com/47193781/126426768-b9a41297-7efb-4788-b297-f298cad854c3.png">

### Version

@rjsf/fluent-ui - ^2.5.1

**Comment by newt10** [comment]
@chelsiemb can you provide some example code to showcase how you are setting up the description field

**Comment by heath-freenome** [comment]
Fixed in the v5 beta, see the [5.x migration guide](https://react-jsonschema-form.readthedocs.io/en/latest/5.x%20upgrade%20guide/)
