### ISSUE TITLE
How do I position form elements side by side

### ISSUE THREAD

**Issue by alfonsoar** [rjsf-team/react-jsonschema-form#2482]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

How do I go about positioning the form elements side by side? Let's say I have something like [this](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaWVsZDEiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRmllbGQgMSJ9LCJkcm9wZG93bjEiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRHJvcGRvd24gMSIsImVudW0iOlsib3B0aW9uMSIsIm9wdGlvbjIiXX0sImRyb3Bkb3duMiI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJEcm9wZG93biAyIiwiZW51bSI6WyJvcHRpb24xIiwib3B0aW9uMiIsIm9wdGlvbjMiLCJvcHRpb240Iiwib3B0aW9uNSJdfSwiZHJvcGRvd24zIjp7InRpdGxlIjoiRHJvcGRvd24gMyIsInR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIm9wdGlvbjEiLCJvcHRpb24yIiwib3B0aW9uMyIsIm9wdGlvbjQiXX0sImZpZWxkMiI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJGaWVsZCAyIn19fSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19) 

If I wanted to position Dropdown 1 next to Dropdown 2 (so they are side by side) how do It?

**Comment by ademgashi** [comment]
+1

**Comment by c0ncentus** [comment]
```css
.container .MuiGrid-container.MuiGrid-root {
  display: grid;
  grid-template-columns: auto auto auto auto;
}
```

maybe should consider 
```css
display:flex
flew-wrap:wrap
```

**Comment by alfonsoar** [comment]
https://github.com/rjsf-team/react-jsonschema-form/issues/2070
