### ISSUE TITLE
[Antd] [FieldTemplate] The form item displayed error style, but has been validated correct by ajv.js on submit.

### ISSUE THREAD

**Issue by zzwfe** [rjsf-team/react-jsonschema-form#2483]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
I used the **antd**'s theme of the **react-jsonschema-form**. when i validated part of my form and submit, the form item's error tips was not showed, but the style was still here.

### Steps to Reproduce
1. I have created a [minimal project](https://codesandbox.io/s/twilight-leaf-m7yf8?file=/src/App.js) in codesanbox. 
2. Click the **Submit** button at first, and then the errors tips show with the error style. It's expected.
![image](https://user-images.githubusercontent.com/20536345/126865995-d9e41ca4-e203-4df6-a84b-f0452b9b5dbc.png)
3. Select the **name** form item, for example, i chose a **one** as my answer. in rapid sequence, click the **Submit** again, the error tips of the **name** form item is disappeared, but the error style  is still here. 
![image](https://user-images.githubusercontent.com/20536345/126866015-6c134ad0-6771-4681-a413-628891be7ded.png)

#### Expected behavior
1. I think we should make a change for [the code](https://github.com/industrialdev/react-jsonschema-form/blob/master/packages/antd/src/templates/FieldTemplate/index.js#L75)
**origin code**
```
...
validateStatus={rawErrors ? 'error' : undefined}
...
```
**coming code**
```
...
validateStatus={rawErrors?.length ? 'error' : undefined}
...
```
2.pleace do the 1st step, and then, the the form item of the **name** is validated successfully, the error style is not show here together with the error tips again. just like that:
![image](https://user-images.githubusercontent.com/20536345/126866485-efee7be7-d0da-4908-b95b-46a3eca39ccd.png)

#### Actual behavior
the error style of the **name** is still show here.

### Version
@rjsf/antd@3.0.0

**Comment by newt10** [comment]
@zzwfe can you submit a PR with a change, along with tests to ensure that we can fix this bug?

**Comment by heath-freenome** [comment]
Fixed by https://github.com/rjsf-team/react-jsonschema-form/pull/2576
