### ISSUE TITLE
Material UI TextWidget does not set the `step` attribute on the input element.

### ISSUE THREAD

**Issue by atrakh** [rjsf-team/react-jsonschema-form#2488]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

The Material UI theme's `TextWidget` does not set the `step` attribute on the input element. This causes a bug in safari where floats are not valid inputs.

### Steps to Reproduce

1. [Visit this playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJudW1iZXIiOjMuMTR9LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInRpdGxlIjoiTnVtYmVyIGZpZWxkcyAmIHdpZGdldHMiLCJwcm9wZXJ0aWVzIjp7Im51bWJlciI6eyJ0aXRsZSI6Ik51bWJlciIsInR5cGUiOiJudW1iZXIifX19LCJ1aVNjaGVtYSI6eyJpbnRlZ2VyIjp7InVpOndpZGdldCI6InVwZG93biJ9fSwidGhlbWUiOiJtYXRlcmlhbC11aSIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)
2. Inspect the `Number` input element

#### Expected behavior

I would expect this behavior to be consistent with the unthemed `TextField` element, setting `step="any"`

#### Actual behavior

The step attribute is not set.

### Version

2.5.1

**Comment by heath-freenome** [comment]
Fixed in v5 beta
