### ISSUE TITLE
Multi dependence dynamic form

### ISSUE THREAD

**Issue by MagicBoBo** [rjsf-team/react-jsonschema-form#2493]
### Prerequisites

- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] I have read the dynamic part and i see that rjsf use dependence and one of to create a dynamic form, but the dependence is only one key

### Description

Can i use rfjs to create a Multi dependence dynamic form ? It means a dynamic form depended on at least two keys.

**Comment by Juansasa** [comment]
Have you looked into If, then, else ? 
When combine with anyOf, allOf and oneOf this shouldn't be a problem.
My PR #2506 have an example of this. Take a look if this is what you mean

**Comment by epicfaace** [comment]
Yeah, that PR could do it, or you could also do this with oneOf / anyOf / allOf. See https://json-schema.org/understanding-json-schema/reference/combining.html for a reference of the latter.
