### ISSUE TITLE
Unable to create jsfiddle examples with version 2.1 or higher

### ISSUE THREAD

**Issue by gustavshf** [rjsf-team/react-jsonschema-form#2498]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Examples like this ( https://jsfiddle.net/n1k0/wqjzvsvh ) with version 1.8.1, for example, work just fine. But when I try to create an example with version 2.1 or higher ( https://jsfiddle.net/8cw2Lo47/1/ ), it doesn't work.

### Steps to Reproduce

1. Try creating an example on jsfiddle.com with rjsf version 2.1 or higher
2. See the console output in jsfiddle.com

Here is the example I tried to create:
https://jsfiddle.net/8cw2Lo47/1/

It doesn't work and shows an error in the console.

#### Expected behavior

No errors, able to create the example

#### Actual behavior

Getting error: "Uncaught ReferenceError: JSONSchemaForm is not defined"

### Version

3.0

**Comment by epicfaace** [comment]
This should be fixed with 3.0.2 now! 🎉
