### ISSUE TITLE
oneOf and anyOf fields forget the readonly state from parent schemas

### ISSUE THREAD

**Issue by rtkedean** [rjsf-team/react-jsonschema-form#2499]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When using anyOf, or oneOf schemas, the readOnly property is not being passed into the <_AnyOfField or <_OneOfField in the core SchemaField implementation.  See: https://github.com/rjsf-team/react-jsonschema-form/blob/0a37d7133a7623f40ffeca5c0cd1f490b4c46aae/packages/core/src/components/fields/SchemaField.js#L384

If the root schema has readOnly true, normally this is inherited by all child properties, thus setting readOnly to true on the root schema "should" make the entire form readonly.  This does not occur for fields inside a oneOf or anyOf as the inheritance is "forgotten"

### Steps to Reproduce

1. Create a JSON schema with nested anyOf or oneOf properties
2. On the root schema set readOnly to true

Examples

OneOf
```
{
  "type": "object",
  "readOnly" : true,
  "oneOf": [
    {
      "properties": {
        "lorem": {
          "type": "string"
        }
      },
      "required": [
        "lorem"
      ]
    },
    {
      "properties": {
        "ipsum": {
          "type": "string"
        }
      },
      "required": [
        "ipsum"
      ]
    }
  ]
}
```

AnyOf
```
{
  "type": "object",
  "readOnly" : true,
  "properties": {
    "age": {
      "type": "integer",
      "title": "Age"
    },
    "items": {
      "type": "array",
      "items": {
        "type": "object",
        "anyOf": [
          {
            "properties": {
              "foo": {
                "type": "string"
              }
            }
          },
          {
            "properties": {
              "bar": {
                "type": "string"
              }
            }
          }
        ]
      }
    }
  },
  "anyOf": [
    {
      "title": "First method of identification",
      "properties": {
        "firstName": {
          "type": "string",
          "title": "First name",
          "default": "Chuck"
        },
        "lastName": {
          "type": "string",
          "title": "Last name"
        }
      }
    },
    {
      "title": "Second method of identification",
      "properties": {
        "idCode": {
          "type": "string",
          "title": "ID code"
        }
      }
    }
  ]
}
```
#### Expected behavior

- All nested properties of the form should be read only. 

#### Actual behavior

- Any properties nested inside an anyOf or oneOf schema are NOT read-only.

### Version

2.5.1

**Comment by heath-freenome** [comment]
This seems to be fixed in version 4.x
