### ISSUE TITLE
FluentUI Theme does not work with latest version

### ISSUE THREAD

**Issue by pksorensen** [rjsf-team/react-jsonschema-form#2511]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

FluentUI Theme does not work with the latest version due to the restriction of peer dependencies that does not allow @fluentui/react > 8.0 to be used.  Using 2.5 RJSF does not have this restriction.

```

  "peerDependencies": {
    "@fluentui/react": "^7.114.2",
    "@rjsf/core": "^3.0.0",
    "react": ">=16"
  },

```

### Steps to Reproduce

update example to use ` "@fluentui/react": "8.27.1"` and npm install and try to npm install.

 

#### Expected behavior

`@rjsf/fluent-ui` is installed and can be used `import Form from "@rjsf/fluent-ui";`

#### Actual behavior

`@rjsf/fluent-ui` is not installed 

### Version

```
 "@rjsf/core": "3.0.1",
 "@rjsf/fluent-ui": "3.0.1",
```

**Comment by epicfaace** [comment]
Do you have any idea why this works using v2 of rjsf? The peer dependency for that version for @fluentui/react should be the same.

**Comment by pksorensen** [comment]
Hi again, sorry for the delay.  I think its related with changes to how npm resolves peerdependencies in latest versions of npm.

I am working around it by npm install --force, but this is not optimal and would be nice if someone have time / knowledge of helping figuring out what the proper solution is here.

**Comment by rajeshpatil74** [comment]
Any update on same ? without using --force ...
