### ISSUE TITLE
Controlled form not working as expected with controlled widget input

### ISSUE THREAD

**Issue by zaid-makani** [rjsf-team/react-jsonschema-form#2513]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/zmakani/zchyjf6t/4/) 

### Description
I am creating a basic react form using react-jsonschema-form
I am replacing the text field with a custom widget of material-ui text field.

I need the form to be controlled form since I want to perform actions of fields depending upon the state of a particular field.
In this example if I change the value of my 1st dropdown the value of 2nd dropdown will automatically change.

Note: This works as expected however, the custom input field has some issues. It keeps losing focus on every key stroke.
the change handler of the text field is calling props.onchange(e.target.value) and the form also has an onChange (this is needed to ensure that I can make use of sideeffect /useEffect when value of 1st dropdown changes.)

### Steps to Reproduce

1) Try typing something in 'Title' text field

#### Expected behavior

I should be able to easily type and remove data. Also data of the field should be available in formData

#### Actual behavior
The title field keeps losing focus on every keystroke

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by n-sviridenko** [comment]
Having the same problem. Any updates on this?

**Comment by zaid-makani** [comment]
Yes I resolved this issue. Its actually a weird one with material-ui text field.
When we render TextField,

`<TextField value={props.value || ''} onChange={handleChange} label={props.label} />`

Make sure the value props does not have undefined during any phase. Inorder to fix this instead of just passing props.value is passed 'props.value || '' '

This ensures that at least blank value gets passed initially. Note: instead of props the value could also come from state.

Adding this workaround fixed the issue for me.

**Comment by n-sviridenko** [comment]
@zaid-makani on which level you overridden the text field? Did you fork the library or did it from the outside?

Mine was uglier:

```ts
function getFieldKey(fieldId: string): string {
  // https://github.com/rjsf-team/react-jsonschema-form/blob/8335ad1966c7e249225d9dce50766750785d8e77/docs/api-reference/form-props.md#idprefix
  const idPrefix = 'root';
  const fieldKey = fieldId.substr(idPrefix.length + 1);
  return fieldKey;
}

// ...

  const isTextField = useCallback(
    (fieldKey: string) => {
      return (
        schema?.properties[fieldKey]?.type === 'string' &&
        !(uiSchema[fieldKey] && uiSchema[fieldKey]['ui:widget'])
      );
    },
    [schema, uiSchema],
  );

  // https://github.com/rjsf-team/react-jsonschema-form/issues/2513
  const onFormChangeHandler = (obj: IChangeEvent<Record<string, unknown>>) => {
    const changedTextFieldKey = Object.keys(obj.formData).find((key) => {
      return (
        isTextField(key) &&
        !!formValues &&
        obj.formData[key] !== formValues[key]
      );
    });
    // skip all input fields
    if (changedTextFieldKey) {
      return;
    }
    setFormValues((prev) => {
      return { ...prev, ...obj.formData };
    });
  };

  // https://github.com/rjsf-team/react-jsonschema-form/issues/2513
  const handleInputFields = (fieldId: string, v: string) => {
    const fieldKey = getFieldKey(fieldId);
    if (!isTextField(fieldKey)) {
      return;
    }
    setFormValues((prev) => {
      return { ...prev, [fieldKey]: v };
    });
  };

  return (
    <Container component="main" maxWidth="lg">
      <div className={classes.paper}>
        <Grid container>
          <Grid item md={6} xs={12}>
            <Form
              schema={schema}
              uiSchema={uiSchema}
              onBlur={handleInputFields}
              formData={formValues}
              onChange={onFormChangeHandler}
            />
          </Grid>
```

**Comment by n-sviridenko** [comment]
Because from what I see here your solution is already a part of the library: https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/material-ui/src/TextWidget/TextWidget.tsx#L60

But suddenly it doesn't help

**Comment by zaid-makani** [comment]
I created a custom widget component that simply renders TextField corresponding to the uischema.
The react-jsonschema-form allows you to plugin in custom widgets for ui components.

something like this,
`<Form schema={schema} uiSchema={uiSchema} widgets={widgets} />`

Now widgets would be,

`const widgets = {TextWidget: CustomTextField}`

Note: We are overriding the 'TextWidget' of react-jsonschema-form // you can see that in official docs as well
//you can also override SelectWidget for dropdowns

The 'CustomTextField' would simply return material-ui TextField

**Comment by zaid-makani** [comment]
> Because from what I see here your solution is already a part of the library: https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/material-ui/src/TextWidget/TextWidget.tsx#L60
> 
> But suddenly it doesn't help

Yes it is. This works for all other textfield. However, my issue was specifically with material-ui TextField. As I mentioned in my latest comment, I was substituting the default react-jsonschema-form TextWidget with Material ui text field.
So this issue was not with library, rather, with material ui.

Note: I am using the widgets prop of the Form
