### ISSUE TITLE
Deprecation notice on material-ui Grid usage.

### ISSUE THREAD

**Issue by duskybox** [rjsf-team/react-jsonschema-form#2517]
### Prerequisites

- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

```
console.error
  Warning: Failed prop type: The prop `justify` of `ForwardRef(Grid)` is deprecated. Use `justifyContent` instead, the prop was renamed.
          at Grid (~/node_modules/@material-ui/core/Grid/Grid.js:243:35)
 ```
 
 This is an issue for applications using newer versions of material ui.

I had an attempt at fixing this, but the fix requires updating Material UI from version `4.5.2`, which in turn caused a number of other Typescript/dependency errors.

The code in question can be seen here: https://github.com/rjsf-team/react-jsonschema-form/pull/2516/files

### Steps to Reproduce

1. Have an application running on a current version of Material UI (e.g. ^4.11.3) will cause the above error.

### Version

"@rjsf/core@^3.1.0":
  version "3.1.0"

"@rjsf/material-ui@^3.1.0":
  version "3.1.0"

**Comment by Morriz** [comment]
bump
