### ISSUE TITLE
Pattern Validation does not work with oneOf in a subschema

### ISSUE THREAD

**Issue by dwwarren** [rjsf-team/react-jsonschema-form#2520]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Pattern validation is not working when using validation when using oneOf in a subschema.

https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJBcnJheU9mVmFsdWVzIjpbeyJvYmplY3QiOnsidHlwZSI6InBlckIiLCJzdWJzY3JpcHRpb25JZCI6ImRkZCJ9fV0sImFyZVlvdU1hcnJpZWQiOiJZZXMiLCJmYW1pbHlEZXRhaWxzIjp7ImRvWW91SGF2ZUNoaWxkcmVuIjoiWWVzIiwibnVtYmVyT2ZDaGlsZHJlbiI6M30sInN0cmluZ1RvTWF0Y2giOiJkZGQifSwic2NoZW1hIjp7IiRzY2hlbWEiOiJodHRwczovL2pzb24tc2NoZW1hLm9yZy9kcmFmdC8yMDIwLTEyL3NjaGVtYSMiLCIkaWQiOiJodHRwczovL2pzb24tc2NoZW1hLm9yZy9kcmFmdC8yMDIwLTEyL3NjaGVtYSMiLCJ0aXRsZSI6IlNhbXBsZVNjaGVtYSIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InN0cmluZ1RvTWF0Y2giOnsiZGVzY3JpcHRpb24iOiJTdHJpbmcgd2l0aCBwYXR0ZXJuIiwidHlwZSI6InN0cmluZyIsInBhdHRlcm4iOiJeW3tdP1swLTlhLWZBLUZdezh9LShbMC05YS1mQS1GXXs0fS0pezN9WzAtOWEtZkEtRl17MTJ9W31dPyQifSwiQXJyYXlPZlZhbHVlcyI6eyJkZXNjcmlwdGlvbiI6IkFycmF5IG9mIHN1YnNjaGVtYSIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7IiRyZWYiOiIjLyRkZWZzL3N1YnNjaGVtYSJ9LCJtaW5JdGVtcyI6MX19LCJyZXF1aXJlZCI6WyJzdHJpbmdUb01hdGNoIl0sIiRkZWZzIjp7InN1YnNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJvYmplY3QiOnsidHlwZSI6Im9iamVjdCIsIm9uZU9mIjpbeyIkcmVmIjoiIy8kZGVmcy9vYmplY3RBIn0seyIkcmVmIjoiIy8kZGVmcy9vYmplY3RCIn1dfX19LCJvYmplY3RBIjp7InByb3BlcnRpZXMiOnsidHlwZSI6eyJlbnVtIjpbInBlckEiXX0sInN1YnNjcmlwdGlvbklkIjp7ImRlc2NyaXB0aW9uIjoiU2FtcGxlIERlc2NyaXB0aW9uIEEiLCJ0eXBlIjoic3RyaW5nIiwicGF0dGVybiI6Il5be10/WzAtOWEtZkEtRl17OH0tKFswLTlhLWZBLUZdezR9LSl7M31bMC05YS1mQS1GXXsxMn1bfV0/JCJ9fX0sIm9iamVjdEIiOnsicHJvcGVydGllcyI6eyJ0eXBlIjp7ImVudW0iOlsicGVyQiJdfSwic3Vic2NyaXB0aW9uSWQiOnsiZGVzY3JpcHRpb24iOiJTYW1wbGUgRGVzY3JpcHRpb24gQiIsInR5cGUiOiJzdHJpbmciLCJwYXR0ZXJuIjoiXlt7XT9bMC05YS1mQS1GXXs4fS0oWzAtOWEtZkEtRl17NH0tKXszfVswLTlhLWZBLUZdezEyfVt9XT8kIn19fX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==

### Steps to Reproduce

1. Navigate to the shared playground in the description
2. Enter a value in the StringToMatch field

#### Expected behavior

Validation should indicate that the entered string does not match the pattern

#### Actual behavior

Validation does not occur
### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.
3.1.0

**Comment by newt10** [comment]
This is an interesting bug, I was able to make it work by removing the $id field and $schema field.
This can be a workaround for now. You can add a PR with tests to fix this when you get  a chance.

![Screen Shot 2021-09-06 at 11 16 08 AM](https://user-images.githubusercontent.com/42853152/132251944-db7dd169-e049-4ef9-ab51-96dfa86e0d6c.png)

**Comment by newt10** [comment]
Also check this out '$schema': 'http://json-schema.org/draft-07/schema#',

**Comment by newt10** [comment]
@epicfaace do you know if the library supports metaschema newer than draft-07?

**Comment by epicfaace** [comment]
This library usually needs to implement new features in json schema on a case-by-case basis, so it's possible that some features newer than draft-07 might be supported, but probably there are features that aren't.

**Comment by heath-freenome** [comment]
This appears to be fixed in the 5.x release using AJV8
