### ISSUE TITLE
Retain field repeater 

### ISSUE THREAD

**Issue by rash09** [rjsf-team/react-jsonschema-form#2521]
### Prerequisites

- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

The application has a multi step form for which a we are using nested json structure, we have come across a scenario where in Step1 there is an email field and has a repeater button, on click on '**Add email'** button the user can add N number of email fields.Once the user fills the Step1 form and click on '**Continue**' the Step1 json is saved in Redux store along with the user filled data. 

### JSON data
 "name": {
            "title": "Email",
            "type": "string",
            "schemaname": "name",
            "datatype": "string",
            "tootltip": "text",
            "helpText": "Help text"
          },
          arrayOfConditionals: {
            "title": "",
            "className": "papers",
            "type": "array",
            "items": {
              "$ref": "#/repeaterschema"
            }
          },
        },
        "repeaterschema": {
          // "title": "Add nationality",
          "logicalname": "contact",
          "type": "object",
          "classNames": "repeate",
          "required": ["email"],
          "properties": {
            "email": {
              "title": "Email",
              "type": "string",
              "schemaname": "name",
              "datatype": "string",
              "tootltip": "text",
              "helpText": "Help text"
            },
          }
        },

#### Expected behavior

The additional Email fields added using "Add Email" button should be retained when the user navigates back to the Step1

#### Actual behavior

The additional email fields are disappeared along with the data 

### Version

"@rjsf/core": "^2.5.1",
    "@rjsf/material-ui": "^2.5.1"

**Comment by newt10** [comment]
@rash09 , if you manage the state and provide the correct form data, you should be able to accomplish this, I am not sure where you are loosing the data

When the back button is pressed, you need to ensure that you are passing the updated schema  and formData (persisted from previous submission) to the page/component you are rendering.

Let me know if this make sense.

**Comment by rash09** [comment]
handling formData resolved the issue
