### ISSUE TITLE
Required one of Fields

### ISSUE THREAD

**Issue by phungne** [rjsf-team/react-jsonschema-form#2525]
### Prerequisites

Can we config like that?

`{
  "properties": {
    "A": {},
    "B": {}
  },
  "anyOf": [{
    "required" : ["A"]
  }, {
    "required" : ["B"]
  }]
}`

### Description

- I wanna required both fields A and B if user not input both
- And if user input field A or input field B=> validate success

**Comment by newt10** [comment]
Feel free to post this on the rjsf discord server #2417 . I am closing this as not an issue. Please let us know if you still need help here.
