### ISSUE TITLE
ui:options not behaving as expected from the documentation

### ISSUE THREAD

**Issue by bejito** [rjsf-team/react-jsonschema-form#2535]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Hello ! I'm sorry if I missed something, but in the [documentation](https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/uiSchema/) it seems to state that `{"ui:options": {[property]: [value]}}` and `{"ui:[property]": value}` are equivalent. When I try this locally or on your playground though, I'm having a different behaviour where the `ui:options` does not seem to be read.

### Steps to Reproduce

https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJuYW1lIjp7InR5cGUiOiJzdHJpbmcifX19LCJ1aVNjaGVtYSI6eyJ1aTpvcHRpb25zIjp7InRpdGxlIjoiVGl0bGUiLCJkZXNjcmlwdGlvbiI6IkRlc2NyaXB0aW9uIn0sIm5hbWUiOnsidWk6b3B0aW9ucyI6eyJ0aXRsZSI6IkN1c3RvbSB0aXRsZSIsImRlc2NyaXB0aW9uIjoiY3VzdG9tIGRlc2MifX19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19

#### Expected behavior

`uiSchema["ui:options].title` and  `uiSchema["ui:options].description` should be taken into account and override the field title that is in the json schema

#### Actual behavior

`uiSchema["ui:options"]` seem to be ignored for these ui options.

### Version

3.1.0

**Comment by epicfaace** [comment]
This might be a bug? Perhaps if "ui:title" / "ui:description" are
hard-coded in some of the theme code

--
Ashwin Ramaswami

**Comment by epicfaace** [comment]
Yes, that seems like the right solution. Would you be willing to make a PR that fixes this issue wherever it's found in the codebase?

**Comment by bejito** [comment]
I don't have enough knowledge of the codebase and bandwidth right now to do this unfortunately. Especially since it is easy to work around this issue by directly using `uiSchema["ui:{prop}"]` for now. If no one touches this in a while, I'll try to find some time

**Comment by newt10** [comment]
I have created a fix for this waiting in PR , @bejito it would be great if you could check it out as well.
