### ISSUE TITLE
"oneOf" set of objects in "additionalProperties"

### ISSUE THREAD

**Issue by RAM92** [rjsf-team/react-jsonschema-form#2538]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

It is not possible to specify "additionalProperties" where the property key(s) is customizable and the value is "oneOf" a set of given object structures.

### Steps to Reproduce

https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0ZXN0UHJvcGVydHkiOnt9fSwic2NoZW1hIjp7IiRzY2hlbWEiOiJodHRwOi8vanNvbi1zY2hlbWEub3JnL3NjaGVtYSMiLCJpZCI6Imh0dHA6Ly9ibGFoLmNvbS9zY2hlbWFzL2JsYWguanNvbiIsInRpdGxlIjoiVGVzdCBzY2hlbWEgdGl0bGUiLCJkZXNjcmlwdGlvbiI6IlRlc3Qgc2NoZW1hIGRlc2NyaXB0aW9uIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidGVzdFByb3BlcnR5Ijp7ImRlc2NyaXB0aW9uIjoiQW55IGtleSBuYW1lLCBmaXhlZCBzZXQgb2YgcG9zc2libGUgdmFsdWVzIiwidHlwZSI6Im9iamVjdCIsIm1pblByb3BlcnRpZXMiOjEsImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjp7Im9uZU9mIjpbeyJ0aXRsZSI6Im15IGNob2ljZSAxIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsicHJvcDEiOnsiZGVzY3JpcHRpb24iOiJwcm9wMSBkZXNjcmlwdGlvbiIsInR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbInByb3AxIl0sImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjpmYWxzZX0seyJ0aXRsZSI6Im15IGNob2ljZSAyIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsicHJvcDIiOnsiZGVzY3JpcHRpb24iOiJwcm9wMiBkZXNjcmlwdGlvbiIsInR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbInByb3AyIl0sImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjpmYWxzZX1dfX19LCJyZXF1aXJlZCI6WyJ0ZXN0UHJvcGVydHkiXSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlfSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19

#### Expected behavior

UI Should show a dropdown with ability to add properties of type "my choice 1" or "my choice 2", and the ability to change the key. Also "prop1" _or_ "prop2" should be visible.

**Comment by newt10** [comment]
Marking this as a bug as object schemas seem to work with additionalProperties and based on that this schema should have generated a dropdown widget to select between the different object schemas.

![Screen Shot 2021-09-06 at 9 59 45 AM](https://user-images.githubusercontent.com/42853152/132249386-020ae164-c0e5-4bb4-83d9-297126fa62de.png)

@RAM92 feel free to create a PR once you are able to fix this.

**Comment by RAM92** [comment]
I can confirm that this issue still occurs when using basic types in the "oneOff" clause.

[playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmb28iOnsiYmFyIjoiYmFyIHZhbHVlIiwiYmF6IjoiYmF6IHZhbHVlIn19LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZm9vIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImJhciI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6ImJhciB2YWx1ZSJ9LCJiYXoiOnsidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJiYXogdmFsdWUifX0sImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjp7Im9uZU9mIjpbeyJ0aXRsZSI6ImFkZGl0aW9uYWwgcHJvcGVydHkgMSIsInR5cGUiOiJzdHJpbmcifSx7InRpdGxlIjoiYWRkaXRpb25hbCBwcm9wZXJ0eSAyIiwidHlwZSI6ImJvb2xlYW4ifV19fX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

**Comment by RAM92** [comment]
Here is an example of a "oneOf" clause not working when loading data. There should be one of each type described, but RJSF treats them both as the first item in the oneOf clause - in this case, a string.
If you change the order, it will render as if they were both booleans.

https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6WyJoZWxsbyB3b3JsZCIsdHJ1ZV0sInNjaGVtYSI6eyIkc2NoZW1hIjoiaHR0cDovL2pzb24tc2NoZW1hLm9yZy9zY2hlbWEjIiwiaWQiOiJodHRwOi8vYmxhaC5jb20vc2NoZW1hcy9ibGFoLmpzb24iLCJ0aXRsZSI6IlRlc3Qgc2NoZW1hIHRpdGxlIiwiZGVzY3JpcHRpb24iOiJUZXN0IHNjaGVtYSBkZXNjcmlwdGlvbiIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7Im9uZU9mIjpbeyJ0aXRsZSI6Im15IHN0cmluZyIsInR5cGUiOiJzdHJpbmcifSx7InRpdGxlIjoibXkgYm9vbGVhbiIsInR5cGUiOiJib29sZWFuIn1dfX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJmYW1pbHktbmFtZSJ9LCJsYXN0TmFtZSI6eyJ1aTplbXB0eVZhbHVlIjoiIiwidWk6YXV0b2NvbXBsZXRlIjoiZ2l2ZW4tbmFtZSJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoidXBkb3duIiwidWk6dGl0bGUiOiJBZ2Ugb2YgcGVyc29uIiwidWk6ZGVzY3JpcHRpb24iOiIoZWFydGhpYW4geWVhcikifSwiYmlvIjp7InVpOndpZGdldCI6InRleHRhcmVhIn0sInBhc3N3b3JkIjp7InVpOndpZGdldCI6InBhc3N3b3JkIiwidWk6aGVscCI6IkhpbnQ6IE1ha2UgaXQgc3Ryb25nISJ9LCJkYXRlIjp7InVpOndpZGdldCI6ImFsdC1kYXRldGltZSJ9LCJ0ZWxlcGhvbmUiOnsidWk6b3B0aW9ucyI6eyJpbnB1dFR5cGUiOiJ0ZWwifX19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19
