### ISSUE TITLE
Ajv6 is past EOL, upgrade AJV

### ISSUE THREAD

**Issue by newt10** [rjsf-team/react-jsonschema-form#2541]
## [AJV@6 was EOL on 30 June 2021](https://ajv.js.org/guide/schema-language.html#draft-04). We should start looking at upgrading AJV since it is an essential piece that makes this library work.

Ajv is already one of the most performant json schema validators so I am proposing that we continue using AJV and take a step by step approach to upgrading.
1. Upgrade to latest version of AJV@7
2. Start a beta branch where more folks from community can try, test and provide feedback.
3. Create a new version with breaking changes

### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

**Comment by newt10** [comment]
@epicfaace what do you think about this? I have a PR where I have been able to integrate ajv@7 into the library in the linked PR.

Let me know if we can include this in 4.x

**Comment by heath-freenome** [comment]
RJSF v5 Beta has decoupled AJV from the `core` implementation and provides both an AJV6 and AJV8 implementation... Closing
