### ISSUE TITLE
Boolean type is not working with semantic-ui

### ISSUE THREAD

**Issue by dvoptv** [rjsf-team/react-jsonschema-form#2546]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

A JSONSchema with boolean type is not working with semantic-ui. On your playground side the error also comes.
Error: 
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Qr (main.js:1)
    at Xr (main.js:1)
    at fl (main.js:1)
    at Di (vendors~main.js:114)
    at ks (vendors~main.js:114)
    at Cs (vendors~main.js:114)
    at _s (vendors~main.js:114)
    at ps (vendors~main.js:114)
    at vendors~main.js:114
```

### Steps to Reproduce

1. Go to "https://rjsf-team.github.io/react-jsonschema-form/"
2. Choose "Nested" there is a boolean type
3. Choose "semantic-ui" as theme

#### Expected behavior

Boolean type should work with semantic-ui like with all other themes

#### Actual behavior

Your playground side crashes.

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.
"@rjsf/core": "^3.1.0",
"@rjsf/semantic-ui": "^3.1.0",

**Comment by solt9029** [comment]
🤔 I could not reproduce this error on https://rjsf-team.github.io/react-jsonschema-form/

**Comment by dvoptv** [comment]
Yeah its working with 3.2.0 now.
