### ISSUE TITLE
BooleanField does not propagate uiSchema prop, causing CheckboxWidget to crash

### ISSUE THREAD

**Issue by henriksvensson** [rjsf-team/react-jsonschema-form#2549]
### Description

When using a boolean field, the form generation using Semantic UI crashes with the following error message:

```
Uncaught TypeError: can't convert undefined to object
    getUiOptions utils.js:354
    getDisplayLabel utils.js:374
    CheckboxWidget CheckboxWidget.js:29
    React 12
    unstable_runWithPriority scheduler.development.js:468
    React 2
    workLoop scheduler.development.js:417
    flushWork scheduler.development.js:390
    performWorkUntilDeadline scheduler.development.js:157
    js scheduler.development.js:180
    js scheduler.development.js:645
    Webpack 20
utils.js:354
```

The BooleanField component that renders the CheckboxWidget does not set the uiSchema prop. My suggestion is that it is added similarly to other fields, such as StringField. That would fix this issue as well as add support for UI schema in the CheckboxWidget.  

### Version
```
"@rjsf/core": "^3.1.0"
"@rjsf/semantic-ui": "^3.1.0"
```

**Comment by jacqueswho** [comment]
@henriksvensson can this issue be closed?

**Comment by epicfaace** [comment]
Yeah, looks like https://github.com/rjsf-team/react-jsonschema-form/pull/2587 fixed it.
