### ISSUE TITLE
Add Mui in addition to material-ui (material ui 5)

### ISSUE THREAD

**Issue by JeremyRubin** [rjsf-team/react-jsonschema-form#2555]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Material-UI just shipped V5 (rebranded mui) so it may make sense to add a separate package for mui v5 support. This did not seem to be already in progress (afaict).

I'd be happy to push an initial port of it (it doesn't seem too tough to do) if there's agreement to support it.

**Comment by MateuszWkDev** [comment]
I am also interested as I have open source project which relies on material-ui V5 beta and would like to migrate to full version

**Comment by joshhoegen** [comment]
I would be highly interested as our team was an early adopter of mui5.

**Comment by chunyenHuang** [comment]
I would like to help. Please start the branch/project thanks

**Comment by JeremyRubin** [comment]
seems like there's decent interest, i'll take a pass at it.

**Comment by heath-freenome** [comment]
+1 I can also help if need be

**Comment by heath-freenome** [comment]
@JeremyRubin @timfee Any progress on this?

**Comment by JeremyRubin** [comment]
I'm good with whatever; not actively focused on this. As long as @timfee apache licenses the changes it should be fine for you to base on that?

**Comment by heath-freenome** [comment]
@epicfaace @JeremyRubin @timfee I have begun working on this new theme... I hope to have a PR up by early next week.

**Comment by heath-freenome** [comment]
> @epicfaace @JeremyRubin @timfee I have begun working on this new theme... I hope to have a PR up by early next week.

And the first problem I encounter is that `antd` does not support `react@17` but `material-ui` v5 has it as a peer dependency :(

**Comment by heath-freenome** [comment]
> I'm good with whatever; not actively focused on this. As long as @timfee apache licenses the changes it should be fine for you to base on that?

I didn't bother with using those changes as I wanted the experience of doing a material-ui V4 to V5 upgrade myself since I'll be doing it for my own code next.

**Comment by heath-freenome** [comment]
@epicfaace How crazy does it sound to create a react-17 version of the playground as a separate application?

**Comment by timfee** [comment]
hey sorry for the delay here... submitted at PR: https://github.com/rjsf-team/react-jsonschema-form/pull/2601 -- and not sure how to best make sure everything's on the up and up RE: apache, so please let me know if you need anything else!

**Comment by epicfaace** [comment]
> @epicfaace How crazy does it sound to create a react-17 version of the playground as a separate application?

I think that's possible! I'd note that the form previews on the playground are actually rendered in a separate iframe, so I could imagine an implementation that seamlessly switches from react 16 to react 17 for the material-ui v5 theme.

**Comment by heath-freenome** [comment]
> > @epicfaace How crazy does it sound to create a react-17 version of the playground as a separate application?
> 
> I think that's possible! I'd note that the form previews on the playground are actually rendered in a separate iframe, so I could imagine an implementation that seamlessly switches from react 16 to react 17 for the material-ui v5 theme.

I'm not sure I have the time to figure this out at the moment. It would still require two running instances of webpack I believe... Probably want to overhaul the playground structure to support something like this perhaps
