### ISSUE TITLE
Examples not shown as suggestions in material-ui, antd, semantic-ui and fluent-ui

### ISSUE THREAD

**Issue by palle-k** [rjsf-team/react-jsonschema-form#2557]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

Fully reproducible example: [Playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCJ9LCJzY2hlbWEiOnsidGl0bGUiOiJFeGFtcGxlcyIsImRlc2NyaXB0aW9uIjoiQSB0ZXh0IGZpZWxkIHdpdGggZXhhbXBsZSB2YWx1ZXMuIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiYnJvd3NlciI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJCcm93c2VyIiwiZXhhbXBsZXMiOlsiRmlyZWZveCIsIkNocm9tZSIsIk9wZXJhIiwiVml2YWxkaSIsIlNhZmFyaSJdfX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoibWF0ZXJpYWwtdWkiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19)

### Description

When selecting a theme other than default or bootstrap-4, field examples are not shown as suggestions.

### Steps to Reproduce

1. Create a JSON schema with examples for a field.
2. Create a form (e.g. with @rjsf/antd) using the schema.
3. Select the text field corresponding to the field with examples

#### Expected behavior

Examples should be shown like in the default theme or bootstrap-4

#### Actual behavior

Besides the default theme and bootstrap-4, no theme shows examples as suggestions.

### Version

@rjsf/antd: 3.1.0
@rjsf/core: 3.1.0
antd: 4.16.13

**Comment by dwjohnston** [comment]
Encountering this too. 

Note also that the example in the default theme doesn't display properly (displays as [object Set] 

Do the maintainers have an opinion about how examples should be displayed? (ie. in a popover, below the form element, etc). I'd be willing to possible submit a PR to add example functionality to default and mui widgets. (I think the helperText seems the appropriate place for examples). 

Or is this something that really, we should just implement our own widgets to handle?

**Comment by epicfaace** [comment]
@palle-k the playground link no longer seems to be working...

> Do the maintainers have an opinion about how examples should be displayed?

Perhaps similar to how it looks like in the default theme and bootstrap-4?

**Comment by heath-freenome** [comment]
Fixed in v5 beta
