### ISSUE TITLE
Dependencies based on boolean is not working as expected

### ISSUE THREAD

**Issue by benjaminbours** [rjsf-team/react-jsonschema-form#2564]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

[Description of the bug or feature]

Property dependencies when using a checkbox / boolean is not working as expected. When it has never been checked, the behavior is ok, but when you uncheck it, the field is still required.

Related to #795 

### Steps to Reproduce
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/8804297/134766598-14879251-b267-4743-869d-4d6421cbee21.gif)

#### Expected behavior

 I expect the field not to be required anymore when I uncheck the checkox.

#### Actual behavior

The field is still required after I unchecked the checkbox.

### Version

Last version. Or the current online demo version.

**Comment by samuelneff** [comment]
Can't help exactly, but I have been working on this exact same issue for the last 5 hours trying several different workarounds. The one that came closest is dynamically updating the `schema` and changing the `required` array when the checkbox is checked or un-checked. Unfortunately, updating the schema resets the entire `formData`, so all data is lost.

Still looking for a fix for this or better would be actual fix within jsonschema-form. Great project!

**Comment by robsweet** [comment]
Schema dependencies seem to be broken the same way.

**Comment by gogulnathv** [comment]
I was able to resolve with oneOf in dependencies

**Comment by siddharth159** [comment]
> I was able to resolve with oneOf in dependencies

@gogulnathv Could you please let me know how I can use oneOf for checkboxes.

**Comment by mi6o** [comment]
@siddharth159 , it is a bit late but this could be helpful.

I suppose, this solves the case: [Link to shared example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJlbWFpbCI6eyJ0eXBlIjoib2JqZWN0IiwidGl0bGUiOiJlbWFpbCBvcHRpb25zIiwicHJvcGVydGllcyI6eyJlbmFibGVkIjp7InR5cGUiOiJib29sZWFuIiwidGl0bGUiOiJlbmFibGUgZW1haWwgbm90aWZpY2F0aW9ucyJ9fSwiZGVwZW5kZW5jaWVzIjp7ImVuYWJsZWQiOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsiZW5hYmxlZCI6eyJjb25zdCI6dHJ1ZX0sInN1YmplY3QiOnsidHlwZSI6InN0cmluZyJ9LCJyZWNpcGllbnRzIjp7InR5cGUiOiJhcnJheSIsInRpdGxlIjoiZW1haWwgcmVjaXBpZW50cyIsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmcifSwidW5pcXVlSXRlbXMiOnRydWV9fX0seyJwcm9wZXJ0aWVzIjp7ImVuYWJsZWQiOnsiY29uc3QiOmZhbHNlfX19XX19fX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIn19)
