### ISSUE TITLE
Expose the AJV instance used for validation as a Prop

### ISSUE THREAD

**Issue by Steffan-Ennis** [rjsf-team/react-jsonschema-form#2566]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

This is a general question and a forum to open discussion. Is there any desire to expose the AJV instance used for validation as  a prop?

### Use Case
I have a set of business rules/requirements that ask for fields to be validated in a specific way in accordance to those rules. At the moment we do this server side in an express application and return the errorSchema and errors to the client. 

To achieve this we've had to instantiate our own instance of AJV and expose that with webpack aliases. That solution isn't really scalable and poses a problem when this project moves.

**Comment by heath-freenome** [comment]
@Steffan-Ennis the v5 beta refactored the validation code into its own `@rjsf/validator-ajv6` package, making it a required prop to the `Form` (see [5.x upgrade guide](https://react-jsonschema-form.readthedocs.io/en/latest/5.x%20upgrade%20guide/)). In that package we exposed ways to configure the base `ajv` instance. In addition, we will soon be providing an implementation of the validator built on ajv8 (i.e. `@rjsf/validator-ajv8`). More-over with this decoupling of validation from the `Form` it is possible for you to build your own implementation, as long as you support the new `ValidatorType` interface.  Does this help?
