### ISSUE TITLE
Question: How to integrate custom fields/widgets into existing schema?

### ISSUE THREAD

**Issue by irakli-g** [rjsf-team/react-jsonschema-form#2567]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
Hi, we are sending a prebuilt react json schema object from backend to frontend and use rjsf material ui library.
This is how the form looks like:
<img width="939" alt="Screenshot 2021-09-27 at 15 20 30" src="https://user-images.githubusercontent.com/70649220/134898795-450aff28-02e3-4b71-8e35-a8d2f6c744b8.png">

Everything works fine but as you can see there is an extra component "Google Map" which contains address autocomplete field, and a map please don't pay attention to schemaData.

Google map generates coordinates and address and as you can see when user submits the form I am adding this address manually on top of formData.

Could you please let me know if it's possible to integrate Google Map and  address autocomplete field component into the schema directly. I've read docs about custom widgets and custom fields but I could not figure out how this actually works. 

Please not that I receive already defined schema and uischema from the backend, I just want to add on top of that schema google map and address autocomplete.

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Version
        "@rjsf/core": "^3.1.0",
        "@rjsf/material-ui": "^3.1.0",

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by epicfaace** [comment]
Yes, it's possible. I actually made a similar widget before: see https://github.com/Chinmayamission/CFF/blob/f26e1a37a9d9688e26e8a2c1cc7e698ae6b4d9eb/scripts/src/form/form_widgets/AddressAutocompleteField.tsx.

You can pass in a custom field through the `fields` prop in the Form component -- check the documentation to see examples.
