### ISSUE TITLE
Inconsistent behavior for ui:widget hidden in different themes

### ISSUE THREAD

**Issue by 01jaraujo** [rjsf-team/react-jsonschema-form#2571]
### Prerequisites
- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I'm trying to hide an Object property and understand this feature is not supported per the [docs](https://react-jsonschema-form.readthedocs.io/en/latest/usage/widgets/#hidden-widgets):
`Hiding widgets is only supported for boolean, string, number and integer schema types `

But in the live playground I'm able to successfully hide the Object property which is what I need, this is feature intended? If not, I think it should be offered to easily hide data types other than `boolean, string, number and integer schema types`. Here's a link to the [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJwcm9wMSI6e30sInByb3AyIjp7fX0sInNjaGVtYSI6eyJ0aXRsZSI6IlRlc3QgRm9ybSIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InByb3AxIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL1Rlc3RGb3JtUHJvcDEifSwicHJvcDIiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvVGVzdEZvcm1Qcm9wMiJ9fSwicmVxdWlyZWQiOlsicHJvcDEiLCJwcm9wMiJdLCJkZWZpbml0aW9ucyI6eyJUZXN0Rm9ybVByb3AxIjp7InRpdGxlIjoiUHJvcCAxIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZmllbGQxIjp7InRpdGxlIjoiRmllbGQxIiwidHlwZSI6ImludGVnZXIifSwiZmllbGQyIjp7InRpdGxlIjoiRmllbGQyIiwidHlwZSI6ImludGVnZXIifX0sInJlcXVpcmVkIjpbImZpZWxkMSIsImZpZWxkMiJdfSwiVGVzdEZvcm1Qcm9wMiI6eyJ0aXRsZSI6IlByb3AgMiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImZpZWxkMyI6eyJ0aXRsZSI6IkZpZWxkMyIsInR5cGUiOiJpbnRlZ2VyIn0sImZpZWxkNCI6eyJ0aXRsZSI6IkZpZWxkNCIsInR5cGUiOiJpbnRlZ2VyIn19LCJyZXF1aXJlZCI6WyJmaWVsZDMiLCJmaWVsZDQiXX19fSwidWlTY2hlbWEiOnsicHJvcDIiOnsidWk6d2lkZ2V0IjoiaGlkZGVuIn19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=).

The object property is hidden with the default theme:
![image](https://user-images.githubusercontent.com/80909176/135318314-ad057a53-ccd3-4415-a39d-d6e2dce1a6e2.png)

The issue I'm running into is moving to material-ui as the theme does not hide the Object property. I think not only should we be able to hide Object properties but that it should be consistent across all themes. Currently the default theme, antd, fluent-ui and bootstrap-4 support hiding the Object property but not with material-ui or sematic-ui.

The object property is not hidden:
<img width="1678" alt="Screen Shot 2021-09-29 at 12 04 23 PM" src="https://user-images.githubusercontent.com/80909176/135317945-a0f5876f-d08c-4b5a-b8d2-ea0fc29a2971.png">

Is there any workaround available to achieve this behaviour?

#### Expected behavior

I expected to not be able to hide the Object property but does work but only in certain themes.

#### Actual behavior

The Object property is hidden in the live playground:

Here's the JSONSchema and UISchema I used in the playground:

- JSONSchema
`{
    "title": "Test Form",
    "type": "object",
    "properties": {
      "prop1": {
        "$ref": "#/definitions/TestFormProp1"
      },
      "prop2": {
        "$ref": "#/definitions/TestFormProp2"
      }
    },
    "required": [
      "prop1",
      "prop2"
    ],
    "definitions": {
      "TestFormProp1": {
        "title": "Prop 1",
        "type": "object",
        "properties": {
          "field1": {
            "title": "Field1",
            "type": "integer"
          },
          "field2": {
            "title": "Field2",
            "type": "integer"
          }
        },
        "required": [
          "field1",
          "field2"
        ]
      },
      "TestFormProp2": {
        "title": "Prop 2",
        "type": "object",
        "properties": {
          "field3": {
            "title": "Field3",
            "type": "integer"
          },
          "field4": {
            "title": "Field4",
            "type": "integer"
          }
        },
        "required": [
          "field3",
          "field4"
        ]
      }
    }
  }`
- UISchema
`{
  "prop2": {
    "ui:widget": "hidden"
  }
}`

**Comment by heath-freenome** [comment]
Fixed in v5 beta via https://github.com/rjsf-team/react-jsonschema-form/pull/3036
