### ISSUE TITLE
Upgrade to Material UI v5

### ISSUE THREAD

**Issue by speakyourcode** [rjsf-team/react-jsonschema-form#2578]
### Description

Material UI has released v5. Any plans to upgrade the package `@rjsf/material-ui`?

**Comment by camsjams** [comment]
Looks like this is primarily tracked here: https://github.com/rjsf-team/react-jsonschema-form/issues/2555

**Comment by epicfaace** [comment]
closing as duplicate of https://github.com/rjsf-team/react-jsonschema-form/issues/2555
