### ISSUE TITLE
TextWidget and TextareaWidget break validation

### ISSUE THREAD

**Issue by iwan-uschka** [rjsf-team/react-jsonschema-form#2580]
### Description

Using a custom TextWidget and TextareaWidget break the validation for required fields.

### Steps to Reproduce

1. https://codesandbox.io/s/ancient-sun-qy8dm
2. Click on submit => errors appear (required fields)
3. put in some values into both fields
4. Click on submit => errors disappear
5. remove values from both fields
6. Click on submit => no errors appear

#### Expected behavior

Errors should appear.

#### Actual behavior

Errors do not appear.

### Version

`3.1.0`

**Comment by tonny008** [comment]
remove   ` widgets={widgets}` works, it's not a rjsf bug.
you provide your custom implementation
you should fix the bug if it's a bug in your implementation

**Comment by iwan-uschka** [comment]
Thanks. I gather from your answer that an empty string won't be handled like an invalid value for a required input field in RJSF. So my fix can be seen as a valid fix for my use case, not as an inspiration for a fix in RJSF.

Ticket can be closed.

**Comment by epicfaace** [comment]
> I gather from your answer that an empty string won't be handled like an invalid value for a required input field in RJSF.

That's correct. There's an easy way to change this behavior, though -- for each field, set `"ui:emptyValue": null,` in the uiSchema.
