### ISSUE TITLE
Nested object's additionalProperties default values not used

### ISSUE THREAD

**Issue by jfblain** [rjsf-team/react-jsonschema-form#2593]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

If an object within the "global" form object contains `additionalProperties` with defaults on some of their fields, they won't be used or showed in the form. Bellow is an example of such a schema in which the defaults that do not appear are mentioned (`x2-additionalProperties` and `x5`).

```
{
  "title": "Missing default showcase",
  "type": "object",
  "properties": {
    "x1": {
      "type": "string",
      "default": "x1 default"
    },
    "x2": {
      "type":"object",
      "properties": {
        "x3": {
          "type": "string",
          "default": "x3 default"
        }
      },
      "additionalProperties": {
        "type": "string",
        "default": "x2-additional default (not showing)"
      }
    }
  },
  "additionalProperties": {
    "type": "object",
    "properties": {
      "x4": {
        "type": "string",
        "default": "x4 default"
      }
    },
    "additionalProperties": {
      "type": "object",
      "properties": {
        "x5": {
          "type": "string",
          "default": "x5 default (not showing)"
        },
        "x6": {
          "type": "array",
          "items": {
            "type": "string",
            "default": "x6 default"
          }
        }
      }
    }
  }
}
```

Also included in this example schema is that arrays within those "problematic" objects will still use the default values as expected.

#### Expected behavior

Defaults should always be used as mentioned in the first paragraph of [this part](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/internals/#handling-of-schema-defaults) of the documentation.

#### Actual behavior

Defaults are not always present in nested objects' `additionalProperties`.

### Version

`3.2.0`

**Comment by kovayur** [comment]
Hi,

Looks like we're also affected by the same issue.

**Comment by kovayur** [comment]
Hi,

Looks like we are also affected by the same issue. Here's the schema example:
```
{
  "type": "object",
  "default": {
    "resources": {
      "limits": {
        "cpu": "500m",
        "memory": "1Gi"
      },
      "requests": {
        "cpu": "100m",
        "memory": "256Mi"
      }
    }
  },
  "properties": {
    "resources": {
      "type": "object",
      "properties": {
        "limits": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "requests": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

Expected: Limits and requests are filled with defaults;
Actual: Limits and requests are empty.

Playground [link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJyZXNvdXJjZXMiOnsibGltaXRzIjp7fSwicmVxdWVzdHMiOnt9fX0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwiZGVmYXVsdCI6eyJyZXNvdXJjZXMiOnsibGltaXRzIjp7ImNwdSI6IjUwMG0iLCJtZW1vcnkiOiIxR2kifSwicmVxdWVzdHMiOnsiY3B1IjoiMTAwbSIsIm1lbW9yeSI6IjI1Nk1pIn19fSwicHJvcGVydGllcyI6eyJyZXNvdXJjZXMiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsibGltaXRzIjp7InR5cGUiOiJvYmplY3QiLCJhZGRpdGlvbmFsUHJvcGVydGllcyI6eyJ0eXBlIjoic3RyaW5nIn19LCJyZXF1ZXN0cyI6eyJ0eXBlIjoib2JqZWN0IiwiYWRkaXRpb25hbFByb3BlcnRpZXMiOnsidHlwZSI6InN0cmluZyJ9fX19fX0sInVpU2NoZW1hIjp7InJlc291cmNlcyI6eyJ1aTpvcmRlciI6WyJsaW1pdHMiLCJyZXF1ZXN0cyJdfX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==).

**Comment by ezzadeen** [comment]
I still see this problem in the Playground:

`{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "test": {
      "title": "Test",
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "name": {
            "title": "Name",
            "type": "string",
            "default": "test"
          },
          "host": {
            "title": "Host",
            "type": "string",
            "default": "localhost"
          },
          "port": {
            "title": "Port",
            "type": "integer",
            "default": 389
          }
        }
      }
    }
  }
}`

If you move the properties out of the additionalProperties, I see the defaults used:

`{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "test": {
      "title": "Test",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "type": "string",
          "default": "test"
        },
        "host": {
          "title": "Host",
          "type": "string",
          "default": "localhost"
        },
        "port": {
          "title": "Port",
          "type": "integer",
          "default": 389
        }
      }
    }
  }
}`

**Comment by ezzadeen** [comment]
I still see this problem. Using the Playground:

`{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "test": {
      "title": "Test",
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "host": {
            "title": "Host",
            "type": "string",
            "default": "localhost"
          },
          "port": {
            "title": "Port",
            "type": "integer",
            "default": 389
          }
        }
      }
    }
  }
}`

**Comment by heath-freenome** [comment]
[Playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0ZXN0Ijp7Im5ld0tleSI6e319fSwic2NoZW1hIjp7IiRzY2hlbWEiOiJodHRwOi8vanNvbi1zY2hlbWEub3JnL2RyYWZ0LTA3L3NjaGVtYSMiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0ZXN0Ijp7InRpdGxlIjoiVGVzdCIsInR5cGUiOiJvYmplY3QiLCJhZGRpdGlvbmFsUHJvcGVydGllcyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJob3N0Ijp7InRpdGxlIjoiSG9zdCIsInR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoibG9jYWxob3N0In0sInBvcnQiOnsidGl0bGUiOiJQb3J0IiwidHlwZSI6ImludGVnZXIiLCJkZWZhdWx0IjozODl9fX19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJtYXRlcmlhbC11aS01IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==) for the above schema example
