### ISSUE TITLE
Replacing schema properties with JSX / ReactNodes breaks form

### ISSUE THREAD

**Issue by jorisw** [rjsf-team/react-jsonschema-form#2594]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

We're trying to decorate/enrich our forms by pre-processing template tags like `{{user:firstName}}` and injecting looked up API values, into RJSF property values like that of `.title` and `.description` on a field.

This works, until our output includes ReactNodes, in other words some kind of JSX. When we do this, we get an error along the lines of:

`schema.properties['your-name'].title should be a string`

This is quite understandable from a RJSF standpoint.

My only question is if it would be possible at all for RJSF to also validate `ReactNode[]` as a title or description. This would stop the form from invalidating with above error when we inject JSX into the title or description.

### Steps to Reproduce

1. Make a static schema
2. Write a function that takes .titles and .descriptions and adds some JSX to them, making them ReactNode arrays instead of strings
3. Try to submit the form. You'll get above errors in the console

#### Expected behavior

For RJSF to render the ReactNodes without complaining

#### Actual behavior

See above error

### Version

`@rjsf/core@3.2.0`

**Comment by epicfaace** [comment]
Not sure if that's possible, because we pass our schemas to ajv, which
actually does the validation. An alternative would be to use the uischema's
ui:title and ui:description attributes for this, instead, which should be
able to accept React components.

--
Ashwin Ramaswami

**Comment by jorisw** [comment]
Same for `enumNames` then, I suppose?

Can I use something in `ui:options` to override `enumNames`?

**Comment by epicfaace** [comment]
No, there isn't something supported in uiSchema analogous to `enumNames` currently.
