### ISSUE TITLE
Passing custom props with cloneElement from custom ObjectFieldTemplate

### ISSUE THREAD

**Issue by MrDelik** [rjsf-team/react-jsonschema-form#2596]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When using a custom ObjectFieldTemplate, I want to clone the properties to pass custom props to the chidlren.
The problem is that the SchemaField do not pass added props to the children.

### Steps to Reproduce

1. Creating a custom ObjectFieldTemplate
2. Cloning each properties content with custom props
3. Rendering cloned properties

#### Expected behavior

Having the custom properties in the clones

#### Actual behavior

The custom properties are passed to the SchemaField, but not to SchemaFIeld children

### Version

3.2.0

**Comment by heath-freenome** [comment]
@MrDelik what about modifying your custom `ObjectFieldTemplate` to insert these custom props into the `uiSchema` object that IS guaranteed to be passed down to the widgets?
