### ISSUE TITLE
Consider using a babel plugin to remove proptypes for production build

### ISSUE THREAD

**Issue by MoOx** [rjsf-team/react-jsonschema-form#260]
Instead of using `if (process.env.NODE_ENV !== "production") {`  you can use stuff like https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types.

Pros: simpler code, no process env check

Cons: Can't be handled by you, you must tell people to handle this by themselves (because you must leave them for development, and you don't handle production optimization).
This can be considered as a good argument since using this plugin will optimize **all** react components you use, not just `react-jsonschema-form`. But this will need some docs :)

**Comment by tiemevanveen** [comment]
> Can't be handled by you, you must tell people to handle this by themselves 

So that doubles the amount of installation steps needed by end users right? Is that really worth it?

**Comment by oliviertassinari** [comment]
This plugin now supports a *wrap mode* for libraries author, basically, it's reproducing the same `if (process.env.NODE_ENV !== "production") {` pattern we can see at the build time.

**Comment by epicfaace** [comment]
@MoOx if you are still interested in implementing this, feel free to send a PR.
