### ISSUE TITLE
Prefilled, readonly text field for `const` string types

### ISSUE THREAD

**Issue by mmkal** [rjsf-team/react-jsonschema-form#2600]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- ~[ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.~
- [x] I'm providing a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsidXNlclR5cGUiLCJmaXJzdE5hbWUiXSwicHJvcGVydGllcyI6eyJ1c2VyVHlwZSI6eyJ0eXBlIjoic3RyaW5nIiwiY29uc3QiOiJlbXBsb3llZSJ9LCJmaXJzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRmlyc3QgbmFtZSJ9fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJmYW1pbHktbmFtZSJ9LCJsYXN0TmFtZSI6eyJ1aTplbXB0eVZhbHVlIjoiIiwidWk6YXV0b2NvbXBsZXRlIjoiZ2l2ZW4tbmFtZSJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoidXBkb3duIiwidWk6dGl0bGUiOiJBZ2Ugb2YgcGVyc29uIiwidWk6ZGVzY3JpcHRpb24iOiIoZWFydGhpYW4geWVhcikifSwiYmlvIjp7InVpOndpZGdldCI6InRleHRhcmVhIn0sInBhc3N3b3JkIjp7InVpOndpZGdldCI6InBhc3N3b3JkIiwidWk6aGVscCI6IkhpbnQ6IE1ha2UgaXQgc3Ryb25nISJ9LCJkYXRlIjp7InVpOndpZGdldCI6ImFsdC1kYXRldGltZSJ9LCJ0ZWxlcGhvbmUiOnsidWk6b3B0aW9ucyI6eyJpbnB1dFR5cGUiOiJ0ZWwifX19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=) demonstrating the issue.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. Have a schema using `{ "type": "string", "const": "something" }`

#### Expected behavior

The `input` should have the `const` value already filled in, and have `readonly=true`

#### Actual behavior

The `input` is just a regular textbox, and the user has to type the exact value of `const` manually (without even a hint of what the value should be)

### Version

3.2.0

I'd be happy to open a PR to improve this if someone could point me in roughly the right direction.

**Comment by ranihorev** [comment]
Same issue, I wonder if we can create a custom widget for it

**Comment by heath-freenome** [comment]
@mmkal Are you still willing to fix this? Some refactoring that was done in version 5 should make fixing this fairly simple

**Comment by mmkal** [comment]
@heath-freenome sorry I missed this message. I'm not using rjsf at the moment any more, so probably won't do this any time soon.
