### ISSUE TITLE
How to hide the submit button in the form component?

### ISSUE THREAD

**Issue by dajun1230** [rjsf-team/react-jsonschema-form#2615]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
How to hide the submit button in the form component?
[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by dajun1230** [comment]
How to hide the submit button in the form component?

**Comment by epicfaace** [comment]
See https://github.com/rjsf-team/react-jsonschema-form/issues/1602
