### ISSUE TITLE
[Theme][Bootstrap4] Readonly attribute is not valid on select element

### ISSUE THREAD

**Issue by Lausselloic** [rjsf-team/react-jsonschema-form#2616]
Hello,

Looks like there's a mistake on bootstrap4 select Widget that have been fixed in core. Readonly attribute have no effect on select element. So maybe like in core https://github.com/rjsf-team/react-jsonschema-form/blob/79a61ff70c25f84ec3e989899ac7f92d1dd3e443/packages/core/src/components/widgets/SelectWidget.js#L74 use disabled on select element if readonly or disabled value is set to true?

https://github.com/rjsf-team/react-jsonschema-form/blob/79a61ff70c25f84ec3e989899ac7f92d1dd3e443/packages/bootstrap-4/src/SelectWidget/SelectWidget.tsx#L91

**Comment by Lausselloic** [comment]
Issue also present on 
semanticUI : https://github.com/rjsf-team/react-jsonschema-form/blob/79a61ff70c25f84ec3e989899ac7f92d1dd3e443/packages/semantic-ui/src/SelectWidget/SelectWidget.js#L113

**Comment by epicfaace** [comment]
Interesting, can you make a PR to fix it?

--
Ashwin Ramaswami

**Comment by heath-freenome** [comment]
Fixed in v5 beta via https://github.com/rjsf-team/react-jsonschema-form/pull/3036
