### ISSUE TITLE
When overriding StringField the base label is shown together with mine.

### ISSUE THREAD

**Issue by stsiushkevich** [rjsf-team/react-jsonschema-form#2621]
### Prerequisites

- [ +] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

I'm overriding a base StringField component by my custom using instructions. But the base label doesn't appear.

```javascript
const fields = {
    StringField: TextField
}

export default function DynaForm(
    {
        className,
        ...props
    }
) {
    return (
        <Form
            {...props}
            fields={fields}
            className={cn('DynaForm', className)}
        />
    )
}
```

![image](https://user-images.githubusercontent.com/12151060/144046668-c2d936bd-845c-44b6-bc56-1629f274d28e.png)

Documentation says: "A field usually wraps one or more widgets and most often handles internal field state; think of a field as a form row, including the labels." So how can I override StringField properly, to avoid extra label?

**Comment by RaphaelSve** [comment]
Hello ! 

I'm digging up the topic but I have the same question. 🤨

**Comment by cdomigan** [comment]
It looks like the label is defined inside the default [FieldTemplate](https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/material-ui/src/FieldTemplate/FieldTemplate.tsx), whereas the docs state that it's the Field that should handle the labels... confusing!
