### ISSUE TITLE
Nested "allOf" does not resolve $ref

### ISSUE THREAD

**Issue by jdkultur** [rjsf-team/react-jsonschema-form#2622]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
When using multiple levels of "allOf" in combination with $ref, the target reference is not resolved.

Consider the following schema
https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJteUltYWdlTWFwIjp7Im1hcmtlcnMiOlt7fV19fSwic2NoZW1hIjp7ImRlZmluaXRpb25zIjp7IkltYWdlTWFya2VyIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImNvb3JkaW5hdGVzIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7IngiOnsidHlwZSI6ImludGVnZXIifSwieSI6eyJ0eXBlIjoiaW50ZWdlciJ9fX19fSwiSW1hZ2VNYXAiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiaW1hZ2UiOnsidHlwZSI6InN0cmluZyJ9LCJtYXJrZXJzIjp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL0ltYWdlTWFya2VyIn19fX19LCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJteUltYWdlTWFwIjp7ImFsbE9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9JbWFnZU1hcCJ9LHsicHJvcGVydGllcyI6eyJtYXJrZXJzIjp7Iml0ZW1zIjp7ImFsbE9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9JbWFnZU1hcmtlciJ9LHsicHJvcGVydGllcyI6eyJuYW1lIjp7InR5cGUiOiJzdHJpbmcifX19XX19fX1dfX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==

My goal is to "extend" the objects inside the items (myImageMap/properties/markers/items), allowing to input a string "name" in addition to "coordinates".

If I replace the first $ref with the complete definition of ImageMarker, it works as expected.
https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJteUltYWdlTWFwIjp7Im1hcmtlcnMiOlt7ImNvb3JkaW5hdGVzIjp7IngiOjEsInkiOjJ9LCJuYW1lIjoiYSJ9XX19LCJzY2hlbWEiOnsiZGVmaW5pdGlvbnMiOnsiSW1hZ2VNYXJrZXIiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiY29vcmRpbmF0ZXMiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsieCI6eyJ0eXBlIjoiaW50ZWdlciJ9LCJ5Ijp7InR5cGUiOiJpbnRlZ2VyIn19fX19LCJJbWFnZU1hcCI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJpbWFnZSI6eyJ0eXBlIjoic3RyaW5nIn0sIm1hcmtlcnMiOnsidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvSW1hZ2VNYXJrZXIifX19fX0sInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im15SW1hZ2VNYXAiOnsiYWxsT2YiOlt7IiRyZWYiOiIjL2RlZmluaXRpb25zL0ltYWdlTWFwIn0seyJwcm9wZXJ0aWVzIjp7Im1hcmtlcnMiOnsiaXRlbXMiOnsiYWxsT2YiOlt7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImNvb3JkaW5hdGVzIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7IngiOnsidHlwZSI6ImludGVnZXIifSwieSI6eyJ0eXBlIjoiaW50ZWdlciJ9fX19fSx7InByb3BlcnRpZXMiOnsibmFtZSI6eyJ0eXBlIjoic3RyaW5nIn19fV19fX19XX19fSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=

### Steps to Reproduce

See first playground-link ^

#### Expected behavior

The form inputs for "markers" contain both coordinates (x, y) AND name.

#### Actual behavior

inputs for coordinates are missing, only "name" is present.

### Version

3.2.1 (I guess, on the playground website)

**Comment by heath-freenome** [comment]
@jdkultur It appears that this issue is fixed in the 5.x release. I tried the first playground link in your issue and it seems to work fine now.
