### ISSUE TITLE
Show conditional field when checked boxes includes some options?

### ISSUE THREAD

**Issue by gentcys** [rjsf-team/react-jsonschema-form#2625]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOlsiQSJdLCJsYXN0TmFtZSI6Ik5vcnJpcyIsImFnZSI6NzUsImJpbyI6IlJvdW5kaG91c2Uga2lja2luZyBhc3NlcyBzaW5jZSAxOTQwIiwicGFzc3dvcmQiOiJub25lZWQifSwic2NoZW1hIjp7InRpdGxlIjoiQSByZWdpc3RyYXRpb24gZm9ybSIsImRlc2NyaXB0aW9uIjoiQSBzaW1wbGUgZm9ybSBleGFtcGxlLiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6IkZpcnN0IG5hbWUiLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJBIiwiQiIsIkMiLCJEIl19fX0sImRlcGVuZGVuY2llcyI6eyJmaXJzdE5hbWUiOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7ImVudW0iOltbIkEiLCJCIl1dfSwiZGVzY3JpcHRpb24iOnsidHlwZSI6InN0cmluZyJ9fX1dfX19LCJ1aVNjaGVtYSI6eyJmaXJ0TmFtZSI6eyJ1aTp3aWRnZXQiOiJjaGVja2JveGVzIn19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=) demonstrating the issue.

### Description

Suppose we defined a field of checkboxes with 4 options(A, B, C, D) and another field will show dependent on its checked options included A option.
e.g. we checked (A, B)/(A, C)/(A, B, C)/(A, B, C, D) the other field should be shown in all these cases
**And no matter the order we checked these options, like for (A, B), we can checked B then A or checked A then B**

### Version

1.8.1

**Comment by epicfaace** [comment]
You can probably do this with a combination of `contains` and `oneOf` --
see
https://json-schema.org/understanding-json-schema/reference/array.html#contains
for more details on contains.

--
Ashwin Ramaswami

**Comment by gentcys** [comment]
@epicfaace Thanks for you reply.

Did you mean
```
{
  "title": "A registration form",
  "description": "A simple form example.",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "array",
      "title": "First name",
      "items": {
        "type": "string",
        "enum": [
          "A",
          "B",
          "C",
          "D"
        ]
      }
    }
  },
  "dependencies": {
    "firstName": {
      "oneOf": [
        {
          "properties": {
            "firstName": {
              "contains": "A"
            },
            "description": {
              "type": "string"
            }
          }
        }
      ]
    }
  }
}
```

**Comment by epicfaace** [comment]
Perhaps, did that work?

--
Ashwin Ramaswami

**Comment by dylanfprice** [comment]
Similar use case--it worked for me. Just one small adjustment since `contains` is supposed to be a schema:
```
"contains": {
  "const": "A"
}
```
[Playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOlsiQSJdfSwic2NoZW1hIjp7InRpdGxlIjoiQSByZWdpc3RyYXRpb24gZm9ybSIsImRlc2NyaXB0aW9uIjoiQSBzaW1wbGUgZm9ybSBleGFtcGxlLiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6IkZpcnN0IG5hbWUiLCJ1bmlxdWVJdGVtcyI6dHJ1ZSwiaXRlbXMiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiQSIsIkIiLCJDIiwiRCJdfX19LCJkZXBlbmRlbmNpZXMiOnsiZmlyc3ROYW1lIjp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJjb250YWlucyI6eyJjb25zdCI6IkEifX0sImRlc2NyaXB0aW9uIjp7InR5cGUiOiJzdHJpbmcifX19XX19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOndpZGdldCI6ImNoZWNrYm94ZXMifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==) - if A is checked (along with any others), description field shows.

**Comment by Zhenglish** [comment]
Hum, the 'contains' in the oneOf stops working when I try to controls individually. In my example, I have 2 checkboxes, and each controls a text field. They work by themselves, but stop working when both selected. 

Any suggestions? 

[playground line](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOlsiQiJdfSwic2NoZW1hIjp7InRpdGxlIjoiQSByZWdpc3RyYXRpb24gZm9ybSIsImRlc2NyaXB0aW9uIjoiQSBzaW1wbGUgZm9ybSBleGFtcGxlLiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6IkZpcnN0IG5hbWUiLCJ1bmlxdWVJdGVtcyI6dHJ1ZSwiaXRlbXMiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiQSIsIkIiLCJDIiwiRCJdfX19LCJkZXBlbmRlbmNpZXMiOnsiZmlyc3ROYW1lIjp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJjb250YWlucyI6eyJjb25zdCI6IkEifX0sImEtZGVzYyI6eyJ0eXBlIjoic3RyaW5nIn19fSx7InByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7ImNvbnRhaW5zIjp7ImNvbnN0IjoiQiJ9fSwiYi1kZXNjIjp7InR5cGUiOiJzdHJpbmcifX19XX19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOndpZGdldCI6ImNoZWNrYm94ZXMifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

**Comment by dylanfprice** [comment]
Yeah I just encountered that one too. You have to enumerate the cases which is a bit unsavory but it works. [Playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOlsiQSIsIkIiXX0sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJGaXJzdCBuYW1lIiwidW5pcXVlSXRlbXMiOnRydWUsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIkEiLCJCIiwiQyIsIkQiXX19fSwiZGVwZW5kZW5jaWVzIjp7ImZpcnN0TmFtZSI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsiY29udGFpbnMiOnsiY29uc3QiOiJBIn0sIm5vdCI6eyJjb250YWlucyI6eyJjb25zdCI6IkIifX19LCJhLWRlc2MiOnsidHlwZSI6InN0cmluZyJ9fX0seyJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJjb250YWlucyI6eyJjb25zdCI6IkIifSwibm90Ijp7ImNvbnRhaW5zIjp7ImNvbnN0IjoiQSJ9fX0sImItZGVzYyI6eyJ0eXBlIjoic3RyaW5nIn19fSx7InByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7ImFsbE9mIjpbeyJjb250YWlucyI6eyJjb25zdCI6IkEifX0seyJjb250YWlucyI6eyJjb25zdCI6IkIifX1dfSwiYS1kZXNjIjp7InR5cGUiOiJzdHJpbmcifSwiYi1kZXNjIjp7InR5cGUiOiJzdHJpbmcifX19XX19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOndpZGdldCI6ImNoZWNrYm94ZXMifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==).

Beyond about 3 controls it becomes a good interview question to generate all the cases :smile: 

You'll want to follow https://github.com/rjsf-team/react-jsonschema-form/pull/2506 which should make it a lot easier.

**Comment by Zhenglish** [comment]
There is a warning message in console "react_devtools_backend.js:4045 ignoring oneOf in dependencies because there isn't exactly one subschema that is valid".  This occurs when no item is select, so I added a subschema for that scenario. However, I couldn't make it right. Can you please look at my [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOltdfSwic2NoZW1hIjp7InRpdGxlIjoiQSByZWdpc3RyYXRpb24gZm9ybSIsImRlc2NyaXB0aW9uIjoiQSBzaW1wbGUgZm9ybSBleGFtcGxlLiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6IkZpcnN0IG5hbWUiLCJ1bmlxdWVJdGVtcyI6dHJ1ZSwiaXRlbXMiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiQSIsIkIiXX19fSwiZGVwZW5kZW5jaWVzIjp7ImZpcnN0TmFtZSI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsiY29udGFpbnMiOnsiY29uc3QiOltdfX19fSx7InByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7ImNvbnRhaW5zIjp7ImNvbnN0IjoiQSJ9LCJub3QiOnsiY29udGFpbnMiOnsiY29uc3QiOiJCIn19fSwiYS1kZXNjIjp7InR5cGUiOiJzdHJpbmcifX19LHsicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsiY29udGFpbnMiOnsiY29uc3QiOiJCIn0sIm5vdCI6eyJjb250YWlucyI6eyJjb25zdCI6IkEifX19LCJiLWRlc2MiOnsidHlwZSI6InN0cmluZyJ9fX0seyJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJhbGxPZiI6W3siY29udGFpbnMiOnsiY29uc3QiOiJBIn19LHsiY29udGFpbnMiOnsiY29uc3QiOiJCIn19XX0sImEtZGVzYyI6eyJ0eXBlIjoic3RyaW5nIn0sImItZGVzYyI6eyJ0eXBlIjoic3RyaW5nIn19fV19fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTp3aWRnZXQiOiJjaGVja2JveGVzIn19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)?

**Comment by dylanfprice** [comment]
`contains` matches items within an array so `contains: {const: []}` doesn't do what you want. You need something that will match an empty array, `maxItems: 0` works. [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOltdfSwic2NoZW1hIjp7InRpdGxlIjoiQSByZWdpc3RyYXRpb24gZm9ybSIsImRlc2NyaXB0aW9uIjoiQSBzaW1wbGUgZm9ybSBleGFtcGxlLiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6IkZpcnN0IG5hbWUiLCJ1bmlxdWVJdGVtcyI6dHJ1ZSwiaXRlbXMiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiQSIsIkIiXX19fSwiZGVwZW5kZW5jaWVzIjp7ImZpcnN0TmFtZSI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsibWF4SXRlbXMiOjB9fX0seyJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJjb250YWlucyI6eyJjb25zdCI6IkEifSwibm90Ijp7ImNvbnRhaW5zIjp7ImNvbnN0IjoiQiJ9fX0sImEtZGVzYyI6eyJ0eXBlIjoic3RyaW5nIn19fSx7InByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7ImNvbnRhaW5zIjp7ImNvbnN0IjoiQiJ9LCJub3QiOnsiY29udGFpbnMiOnsiY29uc3QiOiJBIn19fSwiYi1kZXNjIjp7InR5cGUiOiJzdHJpbmcifX19LHsicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsiYWxsT2YiOlt7ImNvbnRhaW5zIjp7ImNvbnN0IjoiQSJ9fSx7ImNvbnRhaW5zIjp7ImNvbnN0IjoiQiJ9fV19LCJhLWRlc2MiOnsidHlwZSI6InN0cmluZyJ9LCJiLWRlc2MiOnsidHlwZSI6InN0cmluZyJ9fX1dfX19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6d2lkZ2V0IjoiY2hlY2tib3hlcyJ9fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19)

**Comment by dylanfprice** [comment]
@epicfaace I think you can close this

**Comment by epicfaace** [comment]
thanks!

**Comment by jorisw** [comment]
```
const Form = JSONSchemaForm.default;
const schema = {
  "title": "Title",
  "type": "object",
  "properties": {
    "intent_goal": {
      "title": "What is your goal?",
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "advise_me",
          "continuous_credit",
          "other"
        ],
        "enumNames": [
          "Advise me",
          "I want to start a company",
          "Other goal..."
        ]
      },
      "minItems": 1,
      "uniqueItems": true
    }
  },
  "required": [
  ],
  "dependencies": {
    "intent_goal": {
      "oneOf": [
        {
          "properties": {
            "intent_goal": {
              "items":{
                "enum": [null]
              }
            }
          }
        },{
          "properties": {
            "intent_goal": {
              "contains": { enum :  ["other"] }  
            },
            "foo": {
              "type": "string"
            }
          }
        }
      ]
    }
  }
};

const uiSchema = {
  "intent_goal": {
    "ui:widget": "checkboxes"
  },
  "foo": {
    "ui:widget": "textarea"
  }
}

ReactDOM.render((
  <Form schema={schema} uiSchema={uiSchema} />
), document.getElementById("app"));
```

**Comment by xyy7260** [comment]
> 是的，我也刚遇到那个。你必须举一些命令人反对但有有效的例子。[游乐场链接](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOlsiQSIsIkIiXX0sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJGaXJzdCBuYW1lIiwidW5pcXVlSXRlbXMiOnRydWUsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIkEiLCJCIiwiQyIsIkQiXX19fSwiZGVwZW5kZW5jaWVzIjp7ImZpcnN0TmFtZSI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsiY29udGFpbnMiOnsiY29uc3QiOiJBIn0sIm5vdCI6eyJjb250YWlucyI6eyJjb25zdCI6IkIifX19LCJhLWRlc2MiOnsidHlwZSI6InN0cmluZyJ9fX0seyJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJjb250YWlucyI6eyJjb25zdCI6IkIifSwibm90Ijp7ImNvbnRhaW5zIjp7ImNvbnN0IjoiQSJ9fX0sImItZGVzYyI6eyJ0eXBlIjoic3RyaW5nIn19fSx7InByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7ImFsbE9mIjpbeyJjb250YWlucyI6eyJjb25zdCI6IkEifX0seyJjb250YWlucyI6eyJjb25zdCI6IkIifX1dfSwiYS1kZXNjIjp7InR5cGUiOiJzdHJpbmcifSwiYi1kZXNjIjp7InR5cGUiOiJzdHJpbmcifX19XX19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOndpZGdldCI6ImNoZWNrYm94ZXMifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)。
> 
> 除了大约3个控制之外，它成为生成所有案例的一个很好的面试题😄
> 
> 你会想要跟随#2506这应该会让它更容易。

Too many options and so much logic，


> 是的，我也刚遇到那个。您必须列举一些令人讨厌但有效的案例。[游乐场链接](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOlsiQSIsIkIiXX0sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJGaXJzdCBuYW1lIiwidW5pcXVlSXRlbXMiOnRydWUsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIkEiLCJCIiwiQyIsIkQiXX19fSwiZGVwZW5kZW5jaWVzIjp7ImZpcnN0TmFtZSI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsiY29udGFpbnMiOnsiY29uc3QiOiJBIn0sIm5vdCI6eyJjb250YWlucyI6eyJjb25zdCI6IkIifX19LCJhLWRlc2MiOnsidHlwZSI6InN0cmluZyJ9fX0seyJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJjb250YWlucyI6eyJjb25zdCI6IkIifSwibm90Ijp7ImNvbnRhaW5zIjp7ImNvbnN0IjoiQSJ9fX0sImItZGVzYyI6eyJ0eXBlIjoic3RyaW5nIn19fSx7InByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7ImFsbE9mIjpbeyJjb250YWlucyI6eyJjb25zdCI6IkEifX0seyJjb250YWlucyI6eyJjb25zdCI6IkIifX1dfSwiYS1kZXNjIjp7InR5cGUiOiJzdHJpbmcifSwiYi1kZXNjIjp7InR5cGUiOiJzdHJpbmcifX19XX19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOndpZGdldCI6ImNoZWNrYm94ZXMifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)。
> 
> 除了大约 3 个控件之外，它成为生成所有案例的一个很好的面试问题😄
> 
> 你会想要遵循#2506这应该会让它更容易。
If you have a lot of choices and you have to write a lot of judgments in oneOf, what else can you do?

**Comment by xyy7260** [comment]
> 是的，我也刚遇到那个。你必须举一些命令人反对但有有效的例子。[游乐场链接](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOlsiQSIsIkIiXX0sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJGaXJzdCBuYW1lIiwidW5pcXVlSXRlbXMiOnRydWUsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIkEiLCJCIiwiQyIsIkQiXX19fSwiZGVwZW5kZW5jaWVzIjp7ImZpcnN0TmFtZSI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsiY29udGFpbnMiOnsiY29uc3QiOiJBIn0sIm5vdCI6eyJjb250YWlucyI6eyJjb25zdCI6IkIifX19LCJhLWRlc2MiOnsidHlwZSI6InN0cmluZyJ9fX0seyJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJjb250YWlucyI6eyJjb25zdCI6IkIifSwibm90Ijp7ImNvbnRhaW5zIjp7ImNvbnN0IjoiQSJ9fX0sImItZGVzYyI6eyJ0eXBlIjoic3RyaW5nIn19fSx7InByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7ImFsbE9mIjpbeyJjb250YWlucyI6eyJjb25zdCI6IkEifX0seyJjb250YWlucyI6eyJjb25zdCI6IkIifX1dfSwiYS1kZXNjIjp7InR5cGUiOiJzdHJpbmcifSwiYi1kZXNjIjp7InR5cGUiOiJzdHJpbmcifX19XX19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOndpZGdldCI6ImNoZWNrYm94ZXMifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)。
> 
> 除了大约3个控制之外，它成为生成所有案例的一个很好的面试题😄
> 
> 你会想要跟随#2506这应该会让它更容易。

The more options you have, the more code you write. Is there a better way to do this?
