### ISSUE TITLE
fluent-ui theme does not respect array configuration options

### ISSUE THREAD

**Issue by mmiller42** [rjsf-team/react-jsonschema-form#2632]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

The examples from the playground do not appear to render correctly when you choose the fluent-ui theme. Specifically, options for controlling whether items can be sorted or deleted from an array appear to be ignored.

![image](https://user-images.githubusercontent.com/11927375/145623714-66d0c156-8af9-41c2-b741-2e147694c308.png)

### Steps to Reproduce

1. Check out the ["Arrays" example playground using fluent-ui theme](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJsaXN0T2ZTdHJpbmdzIjpbImZvbyIsImJhciJdLCJtdWx0aXBsZUNob2ljZXNMaXN0IjpbImZvbyIsImJhciJdLCJmaXhlZEl0ZW1zTGlzdCI6WyJTb21lIHRleHQiLHRydWUsMTIzXSwibWluSXRlbXNMaXN0IjpbeyJuYW1lIjoiRGVmYXVsdCBuYW1lIn0seyJuYW1lIjoiRGVmYXVsdCBuYW1lIn0seyJuYW1lIjoiRGVmYXVsdCBuYW1lIn1dLCJkZWZhdWx0c0FuZE1pbkl0ZW1zIjpbImNhcnAiLCJ0cm91dCIsImJyZWFtIiwidW5pZGVudGlmaWVkIiwidW5pZGVudGlmaWVkIl0sIm5lc3RlZExpc3QiOltbImxvcmVtIiwiaXBzdW0iXSxbImRvbG9yIl1dLCJ1bm9yZGVyYWJsZSI6WyJvbmUiLCJ0d28iXSwidW5yZW1vdmFibGUiOlsib25lIiwidHdvIl0sIm5vVG9vbGJhciI6WyJvbmUiLCJ0d28iXSwiZml4ZWROb1Rvb2xiYXIiOls0Mix0cnVlLCJhZGRpdGlvbmFsIGl0ZW0gb25lIiwiYWRkaXRpb25hbCBpdGVtIHR3byJdfSwic2NoZW1hIjp7ImRlZmluaXRpb25zIjp7IlRoaW5nIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im5hbWUiOnsidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJEZWZhdWx0IG5hbWUifX19fSwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsibGlzdE9mU3RyaW5ncyI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6IkEgbGlzdCBvZiBzdHJpbmdzIiwiaXRlbXMiOnsidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJiYXppbmdhIn19LCJtdWx0aXBsZUNob2ljZXNMaXN0Ijp7InR5cGUiOiJhcnJheSIsInRpdGxlIjoiQSBtdWx0aXBsZSBjaG9pY2VzIGxpc3QiLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJmb28iLCJiYXIiLCJmdXp6IiwicXV4Il19LCJ1bmlxdWVJdGVtcyI6dHJ1ZX0sImZpeGVkSXRlbXNMaXN0Ijp7InR5cGUiOiJhcnJheSIsInRpdGxlIjoiQSBsaXN0IG9mIGZpeGVkIGl0ZW1zIiwiaXRlbXMiOlt7InRpdGxlIjoiQSBzdHJpbmcgdmFsdWUiLCJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6ImxvcmVtIGlwc3VtIn0seyJ0aXRsZSI6ImEgYm9vbGVhbiB2YWx1ZSIsInR5cGUiOiJib29sZWFuIn1dLCJhZGRpdGlvbmFsSXRlbXMiOnsidGl0bGUiOiJBZGRpdGlvbmFsIGl0ZW0iLCJ0eXBlIjoibnVtYmVyIn19LCJtaW5JdGVtc0xpc3QiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJBIGxpc3Qgd2l0aCBhIG1pbmltYWwgbnVtYmVyIG9mIGl0ZW1zIiwibWluSXRlbXMiOjMsIml0ZW1zIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL1RoaW5nIn19LCJkZWZhdWx0c0FuZE1pbkl0ZW1zIjp7InR5cGUiOiJhcnJheSIsInRpdGxlIjoiTGlzdCBhbmQgaXRlbSBsZXZlbCBkZWZhdWx0cyIsIm1pbkl0ZW1zIjo1LCJkZWZhdWx0IjpbImNhcnAiLCJ0cm91dCIsImJyZWFtIl0sIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoidW5pZGVudGlmaWVkIn19LCJuZXN0ZWRMaXN0Ijp7InR5cGUiOiJhcnJheSIsInRpdGxlIjoiTmVzdGVkIGxpc3QiLCJpdGVtcyI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6IklubmVyIGxpc3QiLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6ImxvcmVtIGlwc3VtIn19fSwidW5vcmRlcmFibGUiOnsidGl0bGUiOiJVbm9yZGVyYWJsZSBpdGVtcyIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoibG9yZW0gaXBzdW0ifX0sInVucmVtb3ZhYmxlIjp7InRpdGxlIjoiVW5yZW1vdmFibGUgaXRlbXMiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6ImxvcmVtIGlwc3VtIn19LCJub1Rvb2xiYXIiOnsidGl0bGUiOiJObyBhZGQsIHJlbW92ZSBhbmQgb3JkZXIgYnV0dG9ucyIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoibG9yZW0gaXBzdW0ifX0sImZpeGVkTm9Ub29sYmFyIjp7InRpdGxlIjoiRml4ZWQgYXJyYXkgd2l0aG91dCBidXR0b25zIiwidHlwZSI6ImFycmF5IiwiaXRlbXMiOlt7InRpdGxlIjoiQSBudW1iZXIiLCJ0eXBlIjoibnVtYmVyIiwiZGVmYXVsdCI6NDJ9LHsidGl0bGUiOiJBIGJvb2xlYW4iLCJ0eXBlIjoiYm9vbGVhbiIsImRlZmF1bHQiOmZhbHNlfV0sImFkZGl0aW9uYWxJdGVtcyI6eyJ0aXRsZSI6IkEgc3RyaW5nIiwidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJsb3JlbSBpcHN1bSJ9fX19LCJ1aVNjaGVtYSI6eyJsaXN0T2ZTdHJpbmdzIjp7Iml0ZW1zIjp7InVpOmVtcHR5VmFsdWUiOiIifX0sIm11bHRpcGxlQ2hvaWNlc0xpc3QiOnsidWk6d2lkZ2V0IjoiY2hlY2tib3hlcyJ9LCJmaXhlZEl0ZW1zTGlzdCI6eyJpdGVtcyI6W3sidWk6d2lkZ2V0IjoidGV4dGFyZWEifSx7InVpOndpZGdldCI6InNlbGVjdCJ9XSwiYWRkaXRpb25hbEl0ZW1zIjp7InVpOndpZGdldCI6InVwZG93biJ9fSwidW5vcmRlcmFibGUiOnsidWk6b3B0aW9ucyI6eyJvcmRlcmFibGUiOmZhbHNlfX0sInVucmVtb3ZhYmxlIjp7InVpOm9wdGlvbnMiOnsicmVtb3ZhYmxlIjpmYWxzZX19LCJub1Rvb2xiYXIiOnsidWk6b3B0aW9ucyI6eyJhZGRhYmxlIjpmYWxzZSwib3JkZXJhYmxlIjpmYWxzZSwicmVtb3ZhYmxlIjpmYWxzZX19LCJmaXhlZE5vVG9vbGJhciI6eyJ1aTpvcHRpb25zIjp7ImFkZGFibGUiOmZhbHNlLCJvcmRlcmFibGUiOmZhbHNlLCJyZW1vdmFibGUiOmZhbHNlfX19LCJ0aGVtZSI6ImZsdWVudC11aSIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

#### Expected behavior

react-jsonschema-form behaves the same for fluent-ui components as for other supported UI component libraries.

#### Actual behavior

1. The list items under "A list of fixed items" are sortable
2. The list items under "Unremovable items" are removable
3. The list items under "No add, remove and order buttons" are removable and display move up/down controls
4. The list items under "Fixed array without buttons" are removable and display move up/down controls

### Version

v3.2.1

**Comment by heath-freenome** [comment]
I just tried this locally with the v5 beta and the buttons seems to be working now
