### ISSUE TITLE
Reading json schema and ui schema from json file?

### ISSUE THREAD

**Issue by MichaelMallett** [rjsf-team/react-jsonschema-form#2638]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Maybe I'm being a bit thick here, but the playground generates schemas, and UI schemas and allows you to update those and see changes to your form...however it's not mentioned anywhere in the docs how to actually use json files to generate the form? It seems it all has to be defined in JS? This seems a little confusing to me when presented with the output and interaction of the playground

**Comment by epicfaace** [comment]
I think that depends on how you set up your React application. How is your setup?

**Comment by MichaelMallett** [comment]
I'm just trying to use the examples in the docs, so an absolutely basic example for now, but all examples use a schema object, rather than pull it in from json?

This codepen that I found is doing what I want, but I cannot figure out how (I'm not a JS developer, so I was looking for something that let me build the form with only basic react, and a json schema)

https://codesandbox.io/s/l988k9x8n9?file=/public/index.html

**Comment by epicfaace** [comment]
I think your question is a general react question of "How do I load a JSON file in a React app?" rather than specific to react-jsonschema-form. You can look at these links, which might help: https://stackoverflow.com/questions/31758081/loading-json-data-from-local-file-into-react-js and https://www.pluralsight.com/guides/fetch-data-from-a-json-file-in-a-react-app. Hope that helps!

**Comment by MichaelMallett** [comment]
Thanks, I had wondered if it was just loading json regularly, or if it was doing some magic in the background like json-forms does.
