### ISSUE TITLE
omitExtraData drops value of field whose identifier contains a dot ".

### ISSUE THREAD

**Issue by jakob-ed** [rjsf-team/react-jsonschema-form#2642]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

[See playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJuZXN0ZWRfcHJvcGVydGllcyI6eyJsZXZlbC4yLnByb3BlcnR5IjoiYXNkZiJ9LCJsZXZlbC4xLnByb3BlcnR5IjoiYXNkZiJ9LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbImxldmVsLjEucHJvcGVydHkiXSwicHJvcGVydGllcyI6eyJsZXZlbC4xLnByb3BlcnR5Ijp7InR5cGUiOiJzdHJpbmcifSwibmVzdGVkX3Byb3BlcnRpZXMiOnsidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbImxldmVsLjIucHJvcGVydHkiXSwicHJvcGVydGllcyI6eyJsZXZlbC4yLnByb3BlcnR5Ijp7InR5cGUiOiJzdHJpbmcifX19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6dHJ1ZSwibGl2ZU9taXQiOmZhbHNlfX0=)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by epicfaace** [comment]
Is this issue fixed?

**Comment by jakob-ed** [comment]
This is an incomplete duplicate issue I created by accident and therefore closed right away again. The bug still exists and is documented in #2643.

**Comment by epicfaace** [comment]
Thanks

Ashwin Ramaswami
