### ISSUE TITLE
How to use rjsf-antd theme for react-json-schema with antd 3 version?

### ISSUE THREAD

**Issue by hansiemithun** [rjsf-team/react-jsonschema-form#2659]
Stackoverflow reference: https://stackoverflow.com/questions/70732801/how-to-use-rjsf-antd-theme-for-react-json-schema-with-antd-3-version

**Comment by epicfaace** [comment]
Unfortunately, the theme at the moment only supports antd 4+. You might be able to fork it, but I'm not sure how much work it would take to backport it to antd 3. Sorry!
