### ISSUE TITLE
Include enumNames in the typescript declaration files

### ISSUE THREAD

**Issue by Steffan-Ennis** [rjsf-team/react-jsonschema-form#2663]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

The property enumNames is supported by @rjsf.core but it is no longer in any JSONSchema proposal and thus is missing from the json-schema declaration files.

see https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/index.d.ts#L45 

#### Expected behaviour

When building typescript applications and relying on the type declared file index.d.ts. All supported field properties should be declared

#### Actual behaviour

enumNames is missing 

### Version
Current

**Comment by epicfaace** [comment]
Hmm, enumNames isn't part of the JSON Schema spec, though, but I'd be willing to accept a PR that adds this into the type files.

**Comment by Steffan-Ennis** [comment]
When I have some time, I'll be happy to do so

**Comment by wight554** [comment]
You can use module augmentation when using schema type
```
import { JSONSchema7 } from 'json-schema';

declare module 'json-schema' {
  export interface JSONSchema7 {
    enumNames?: Array<string>;
  }
}
```
you can feed this type to rjsf without error

**Comment by iwan-uschka** [comment]
Use

```TypeScript
import 'json-schema';

declare module 'json-schema' {
  export interface JSONSchema7 {
    enumNames?: Array<string>;
  }
}
```

to avoid TypeScript complaining about an unused variable. See https://github.com/typescript-eslint/typescript-eslint/issues/2577#issuecomment-694974608.
