### ISSUE TITLE
Semantic UI is missing `error` class on `Form.Group` when field is invalid

### ISSUE THREAD

**Issue by coreyjv** [rjsf-team/react-jsonschema-form#2666]
### Description

When using `@rjsf/semantic-ui` fields that are in an error state don't render with the proper class attached to the `Form.Group` component as defined [here](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/semantic-ui/src/FieldTemplate/FieldTemplate.js#L25).

### Steps to Reproduce

1. Open [Code Sandbox](https://codesandbox.io/s/rjsf-semantic-ui-errors-eyweb?file=/src/App.js)
2. Enter values in field and press submit

#### Expected behavior

Expect the `error` class to be applied to the field so it renders properly

#### Actual behavior

The `error` class is not attached and therefore the input looks like it is not in an error state 

### Version

```
    "@rjsf/core": "3.2.1",
    "@rjsf/semantic-ui": "3.2.1",
    "semantic-ui-css": "2.4.1",
    "semantic-ui-react": "2.0.4"
```

**Comment by heath-freenome** [comment]
Fixed in v5 beta
