### ISSUE TITLE
Passing additionalProperties does not work with omitExtraData

### ISSUE THREAD

**Issue by sempostma** [rjsf-team/react-jsonschema-form#2667]
https://github.com/rjsf-team/react-jsonschema-form/blob/63636b7af2189bc151dfaa261318f167d6bb36e6/packages/core/src/utils.js#L1041

Passing additionalProperties = false does not work because in the line above. It should check if it is true instead of checking the precence:

http://json-schema.org/understanding-json-schema/reference/object.html#additional-properties

**Comment by lpillonel** [comment]
Probably the same regarding additionalProperties, liveOmit & omitExtraData : 
data are not removed when part of an additionalProperties "object".

Please check "liveOmit" and "OmitExtraData" in the [following example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJlbnRyaWVzIjp7Im5ld0tleSI6eyJ0eXBlIjoic3RyaW5nIiwiZm9ybWF0IjoiZGF0ZSIsIm1pbkxlbmd0aCI6NSwibWF4TGVuZ3RoIjoxMH19fSwic2NoZW1hIjp7IiRzY2hlbWEiOiJodHRwOi8vanNvbi1zY2hlbWEub3JnL2RyYWZ0LTA3L3NjaGVtYSMiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJlbnRyaWVzIjp7InR5cGUiOiJvYmplY3QiLCJhZGRpdGlvbmFsUHJvcGVydGllcyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0aXRsZSI6eyJ0eXBlIjoic3RyaW5nIn0sInR5cGUiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsic3RyaW5nIiwibnVtYmVyIl19fSwiYWxsT2YiOlt7ImlmIjp7InJlcXVpcmVkIjpbInR5cGUiXSwicHJvcGVydGllcyI6eyJ0eXBlIjp7ImNvbnN0Ijoic3RyaW5nIn19fSwidGhlbiI6eyJwcm9wZXJ0aWVzIjp7ImZvcm1hdCI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJkYXRlIiwiZW1haWwiXX0sIm1pbkxlbmd0aCI6eyJ0aXRsZSI6Im1pbmltdW0gbGVuZ3RoIiwidHlwZSI6ImludGVnZXIifSwibWF4TGVuZ3RoIjp7InRpdGxlIjoibWF4aW11bSBsZW5ndGgiLCJ0eXBlIjoiaW50ZWdlciJ9fX19XX19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19), and switch the type from string to date in the form. Extra data are not removed.

**Comment by heath-freenome** [comment]
fixed in v5 beta via https://github.com/rjsf-team/react-jsonschema-form/pull/2940
