### ISSUE TITLE
Is there any library known for BUILD json schema templates?

### ISSUE THREAD

**Issue by ThomazAquino** [rjsf-team/react-jsonschema-form#2668]
Hi,
Is there a tool that provides an UI where the user can visually build a form with pre defined fiels and afterwards it generates an json schema?

More info:
I want provide a tool for the user define how the form should looks like. Something where the user can choose the field name, the field type, the position in the form, if is required or not, etc. And in the end generate a json schema to be used.

Do you guys know if there is an open source platform who provide such feature? Or do I need to go custom on this?

**Comment by epicfaace** [comment]
See https://github.com/rjsf-team/react-jsonschema-form/issues/588 for some discussion on this!
