### ISSUE TITLE
refactor validation

### ISSUE THREAD

**Issue by Morriz** [rjsf-team/react-jsonschema-form#2669]
The form validation routine is not working correctly with nested schemas and should be refactored. How about traversing the data tree and keep a valid flag per leaf. Imo leafs should be pruned first when it is either an empty object or array, or undefined.

The form should only be invalid when any of its direct decendants are invalid.

**Comment by heath-freenome** [comment]
Hopefully this will be fixed as part of #2693

**Comment by heath-freenome** [comment]
This should be fixed in the v5 beta, see the [5.x migration guide](https://react-jsonschema-form.readthedocs.io/en/latest/5.x%20upgrade%20guide/)
