### ISSUE TITLE
Invalid values when adding property with multiple possible value types (e.g. nullable ["object", "null"])

### ISSUE THREAD

**Issue by cosborne83** [rjsf-team/react-jsonschema-form#2672]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Invalid form data when adding additionalProperties where the values are of multiple possible types (e.g. `["object", "null"]`)

### Steps to Reproduce

1. Open this [playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjpbIm9iamVjdCIsIm51bGwiXSwicHJvcGVydGllcyI6eyJEaWN0UHJvcCI6eyJ0eXBlIjpbIm9iamVjdCIsIm51bGwiXSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOnsidHlwZSI6WyJvYmplY3QiLCJudWxsIl0sInByb3BlcnRpZXMiOnsiVmFsdWUiOnsidHlwZSI6WyJzdHJpbmciLCJudWxsIl19fX19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19).
2. Click the "+" button to add a new property to "DictProp"
3. Set the `Value` property of the newly added value on the form.

#### Expected behavior

At step 2 above, either the new value in the formData should be one of the valid types (object/null).
At step 3 above, the properties of newKey should not contain the characters of "New Value" expanded out into properties on the object.

#### Actual behavior

At step 2 above, the formData now includes an invalid property: `"newKey": "New Value"` that does not match the schema (the values for additional properties must be `object` or `null`, but the value added is a `string`:
```json
{
  "DictProp": {
    "newKey": "New Value"
  }
}
```

At step 3 above, the formData now includes the string "New Value" expanded out character-by-character as numbered properties of the object:
```json
{
  "DictProp": {
    "newKey": {
      "0": "N",
      "1": "e",
      "2": "w",
      "3": " ",
      "4": "V",
      "5": "a",
      "6": "l",
      "7": "u",
      "8": "e",
      "Value": "X"
    }
  }
}
```

### Version

3.2.1

**Comment by Sachin-chaurasiya** [comment]
Hello @jacqueswho , Would like to know the update on this issue.
Thanks.

**Comment by jacqueswho** [comment]
@Sachin-chaurasiya I will bring it up in the next meeting

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya I will bring it up in the next meeting

That would be great, thanks @jacqueswho

**Comment by Sachin-chaurasiya** [comment]
Hello @jacqueswho , Hope you are doing well, 
Is there any update on this issue?

**Comment by jacqueswho** [comment]
> Hello @jacqueswho , Hope you are doing well, Is there any update on this issue?

@Sachin-chaurasiya apologies, but work has been quite busy, not been in the last 2 meetings, also there was a public holiday. Will check on what was discussed

**Comment by Sachin-chaurasiya** [comment]
> > Hello @jacqueswho , Hope you are doing well, Is there any update on this issue?
> 
> @Sachin-chaurasiya apologies, but work has been quite busy, not been in the last 2 meetings, also there was a public holiday. Will check on what was discussed

Thanks, @jacqueswho, It would be great if you provide me with some work around for this.

**Comment by jacqueswho** [comment]
@Sachin-chaurasiya Sorry it took so long. I have investigated this, had a look at the code, according to the
[docs](https://react-jsonschema-form.readthedocs.io/en/latest/usage/single/), you cant specify object as a type for this. So if you look at this [playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJEaWN0UHJvcCI6eyJuZXdLZXkiOiJOZXcgVmFsdWUifSwiZmlyc3ROYW1lIjoiZmRmZGZmIn0sInNjaGVtYSI6eyJ0eXBlIjpbIm9iamVjdCIsIm51bGwiXSwicHJvcGVydGllcyI6eyJEaWN0UHJvcCI6eyJ0eXBlIjpbIm9iamVjdCIsIm51bGwiXSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOnsidHlwZSI6WyJzdHJpbmciLCJudWxsIl0sInByb3BlcnRpZXMiOnsiVmFsdWUiOnsidHlwZSI6WyJzdHJpbmciLCJudWxsIl19fX19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19) . It works as expected, not sure what you were expecting

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya Sorry it took so long. I have investigated this, had a look at the code, according to the
> [docs](https://react-jsonschema-form.readthedocs.io/en/latest/usage/single/), you cant specify object as a type for this. So if you look at this [playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJEaWN0UHJvcCI6eyJuZXdLZXkiOiJOZXcgVmFsdWUifSwiZmlyc3ROYW1lIjoiZmRmZGZmIn0sInNjaGVtYSI6eyJ0eXBlIjpbIm9iamVjdCIsIm51bGwiXSwicHJvcGVydGllcyI6eyJEaWN0UHJvcCI6eyJ0eXBlIjpbIm9iamVjdCIsIm51bGwiXSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOnsidHlwZSI6WyJzdHJpbmciLCJudWxsIl0sInByb3BlcnRpZXMiOnsiVmFsdWUiOnsidHlwZSI6WyJzdHJpbmciLCJudWxsIl19fX19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19) . It works as expected, not sure what you were expecting

Thanks @jacqueswho , I will have a look.

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya Sorry it took so long. I have investigated this, had a look at the code, according to the [docs](https://react-jsonschema-form.readthedocs.io/en/latest/usage/single/), you cant specify object as a type for this. So if you look at this [playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJEaWN0UHJvcCI6eyJuZXdLZXkiOiJOZXcgVmFsdWUifSwiZmlyc3ROYW1lIjoiZmRmZGZmIn0sInNjaGVtYSI6eyJ0eXBlIjpbIm9iamVjdCIsIm51bGwiXSwicHJvcGVydGllcyI6eyJEaWN0UHJvcCI6eyJ0eXBlIjpbIm9iamVjdCIsIm51bGwiXSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOnsidHlwZSI6WyJzdHJpbmciLCJudWxsIl0sInByb3BlcnRpZXMiOnsiVmFsdWUiOnsidHlwZSI6WyJzdHJpbmciLCJudWxsIl19fX19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19) . It works as expected, not sure what you were expecting

Hello @jacqueswho , How can we get rid of this default values in additional properties?
![image](https://user-images.githubusercontent.com/59080942/206831107-ba371c13-8968-4701-bd0a-e08db54309c8.png)

**Comment by chirag-madlani** [comment]
> > @Sachin-chaurasiya Sorry it took so long. I have investigated this, had a look at the code, according to the [docs](https://react-jsonschema-form.readthedocs.io/en/latest/usage/single/), you cant specify object as a type for this. So if you look at this [playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJEaWN0UHJvcCI6eyJuZXdLZXkiOiJOZXcgVmFsdWUifSwiZmlyc3ROYW1lIjoiZmRmZGZmIn0sInNjaGVtYSI6eyJ0eXBlIjpbIm9iamVjdCIsIm51bGwiXSwicHJvcGVydGllcyI6eyJEaWN0UHJvcCI6eyJ0eXBlIjpbIm9iamVjdCIsIm51bGwiXSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOnsidHlwZSI6WyJzdHJpbmciLCJudWxsIl0sInByb3BlcnRpZXMiOnsiVmFsdWUiOnsidHlwZSI6WyJzdHJpbmciLCJudWxsIl19fX19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19) . It works as expected, not sure what you were expecting
> 
> Hello @jacqueswho , How can we get rid of this default values in additional properties? ![image](https://user-images.githubusercontent.com/59080942/206831107-ba371c13-8968-4701-bd0a-e08db54309c8.png)

Hi @jacqueswho Is there a way of hack that will allow us to remove this values to be populated?

**Comment by chirag-madlani** [comment]
Hi @jacqueswho 

I have investigated this and figured out that we have Hardcoded "newKey" [here](https://github.com/rjsf-team/react-jsonschema-form/blob/86d1993269aa9e4a7c0d476b87f97cb312c6bab2/packages/core/src/components/fields/ObjectField.tsx#L216)

Can we provide an option to override it? 

The same goes for value too, look [here](https://github.com/rjsf-team/react-jsonschema-form/blob/86d1993269aa9e4a7c0d476b87f97cb312c6bab2/packages/core/src/components/fields/ObjectField.tsx#L174)

We need some way to override these values as adding a new field renders these hardcoded strings.


Any help or hack is appriciated
