### ISSUE TITLE
Bug: FieldTemplateProps.fields is incorrectly typed

### ISSUE THREAD

**Issue by sophstad** [rjsf-team/react-jsonschema-form#2673]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

The [docs](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-templates/#fieldtemplate) and [package exports](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/index.d.ts#L170) indicate that `fields` within `FieldTemplateProps` is an array of Fields. However, a form with a custom FieldTemplate indicates that `fields` is an object.

### Steps to Reproduce

JSFiddle: https://jsfiddle.net/5v1wsru9/

#### Expected behavior

`FieldTemplateProps.fields` is an array

#### Actual behavior

`FieldTemplateProps.fields` is an object (this makes more sense, but the documentation and typing appear to be incorrect)

### Version

v3.2.1

**Comment by epicfaace** [comment]
Thanks for reporting. Do you mind making a PR to update this?

**Comment by epicfaace** [comment]
to update the documentation and typing

**Comment by sophstad** [comment]
Happy to do so! Thanks @epicfaace

**Comment by heath-freenome** [comment]
Fixed in the v5 beta, see the [5.x migration guide](https://react-jsonschema-form.readthedocs.io/en/latest/5.x%20upgrade%20guide/)
