### ISSUE TITLE
Checkboxes with 'other' text field

### ISSUE THREAD

**Issue by WpSlt** [rjsf-team/react-jsonschema-form#2675]
### Prerequisites
- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
### Description

Is There a way to create a checkboxes group with 'other' text field?
(something like big G form checkboxes)

Thx!

**Comment by jorisw** [comment]
```js

```
const Form = JSONSchemaForm.default;
const schema = {
  "title": "Title",
  "type": "object",
  "properties": {
    "intent_goal": {
      "title": "What is your goal?",
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "advise_me",
          "continuous_credit",
          "other"
        ],
        "enumNames": [
          "Advise me",
          "I want to start a company",
          "Other goal..."
        ]
      },
      "minItems": 1,
      "uniqueItems": true
    }
  },
  "required": [
  ],
  "dependencies": {
    "intent_goal": {
      "oneOf": [
        {
          "properties": {
            "intent_goal": {
              "items":{
                "enum": [null]
              }
            }
          }
        },{
          "properties": {
            "intent_goal": {
              "contains": { enum :  ["other"] }  
            },
            "foo": {
              "type": "string"
            }
          }
        }
      ]
    }
  }
};

const uiSchema = {
  "intent_goal": {
    "ui:widget": "checkboxes"
  },
  "foo": {
    "ui:widget": "textarea"
  }
}

ReactDOM.render((
  <Form schema={schema} uiSchema={uiSchema} />
), document.getElementById("app"));
```
