### ISSUE TITLE
rjsf meeting time (11 AM ET on Fridays)

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#2677]
We have a weekly call where we can talk about PRs, issues, releases, etc. -- see https://docs.google.com/document/d/12PjTvv21k6LIky6bNQVnsplMLLnmEuypTLQF8a-8Wss/edit?usp=sharing for more information.

Original message

> @heath-freenome I'm also thinking we should set up a weekly time / "rjsf work session" where people join a call and can talk about PRs, issues, releases, etc. -- might make it easier to set a cadence for rjsf work and make progress on PRs such as this. wdyt?
> 
> _Originally posted by @epicfaace in https://github.com/rjsf-team/react-jsonschema-form/issues/2605#issuecomment-1023651384_

**Comment by heath-freenome** [comment]
@epicfaace That seems like a good idea... it would be nice to clear up some of the backlog of PRs and issues as well. Are you thinking of doing it on discord, or maybe zoom?

**Comment by epicfaace** [comment]
I think discord might be nice!

**Comment by epicfaace** [comment]
Backlog of PRs that we could review / talk through together during a work session:
- https://github.com/rjsf-team/react-jsonschema-form/pull/2605
- https://github.com/rjsf-team/react-jsonschema-form/pull/2674
- https://github.com/rjsf-team/react-jsonschema-form/pull/2676

**Comment by epicfaace** [comment]
Set up a bare-bones doc with the first meeting time and agenda: https://docs.google.com/document/d/12PjTvv21k6LIky6bNQVnsplMLLnmEuypTLQF8a-8Wss/edit?usp=sharing

**Comment by heath-freenome** [comment]
11am ET = 8am PT... I'll try to be there

**Comment by heath-freenome** [comment]
@epicfaace the discord link disappeared from the document?!

**Comment by heath-freenome** [comment]
> Set up a bare-bones doc with the first meeting time and agenda: https://docs.google.com/document/d/12PjTvv21k6LIky6bNQVnsplMLLnmEuypTLQF8a-8Wss/edit?usp=sharing

@epicfaace May I suggest updating the details of this issue and adding the above document so that others can find and join?

**Comment by epicfaace** [comment]
Done

**Comment by heath-freenome** [comment]
Merged with discord server, closing this
