### ISSUE TITLE
Question: How to notify form on error state in Custom Field?

### ISSUE THREAD

**Issue by levyitay** [rjsf-team/react-jsonschema-form#2683]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

I'm using my own custom field: 
```js
 <Space direction="vertical" align="start">
      <InputNumber
          controls={false} value={numberVal} onChange={onChange} disabled={props.readonly} />
      {(!isErrorState) ? <></> :
          <Typography.Text type="danger">{props.schema.errorText}</Typography.Text>
      }
  </Space>
```
And trying to figure out how to either add error to the error list or notify form one of the fields has an error

**Comment by levyitay** [comment]
Update:
I used schema to try and validate a number which can be useful in many cases but the validator supports only schema validations for Strings and not numbers :(

**Comment by epicfaace** [comment]
See here for some info on the types of validation supported for numbers --
https://json-schema.org/understanding-json-schema/reference/numeric.html

--
Ashwin Ramaswami
