### ISSUE TITLE
react-jsonschema-form 1.8.2 request: Replace use of deprecated shortid dependency with nanoid

### ISSUE THREAD

**Issue by jlczuk** [rjsf-team/react-jsonschema-form#2684]
The shortid package is deprecated and uses a version of nanoid that now has 1 moderate vulnerability.  I am requesting version 1.8.2 be release with the update to use nanoid directly, thus eliminating any exposure to the downlevel nanoid vulneratbility.

I forked the repo and tried to make the updates myself, but for some reason, following the instructions to do the `npm run build` fails and I cannot figure out why.

The necessary changes:
- [ ] Change ArrayField.js to import nanoid from nanoid
- [ ] Change the generateRowId() function in ArrayField.js to call nanoid()
- [ ] Replace the shortid dependency in package.json to nanoid ^3.2.0
- [ ] Rebuild package_lock.json

```                       === npm audit security report ===

┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Exposure of Sensitive Information to an Unauthorized Actor   │
│               │ in nanoid                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ nanoid                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.1.31                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ react-jsonschema-form                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ react-jsonschema-form > shortid > nanoid                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-qrpm-p2h7-hrv2            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 1 moderate severity vulnerability in 440 scanned packages
  1 vulnerability requires manual review. See the full report for details.
```

**Comment by epicfaace** [comment]
Tracking this for next weekly meeting
https://docs.google.com/document/d/12PjTvv21k6LIky6bNQVnsplMLLnmEuypTLQF8a-8Wss/edit#

--
Ashwin Ramaswami

**Comment by alfonsoar** [comment]
@jlczuk Have you considered (does your project allow) upgrading to the latest version of rjsf? It was patch in the latest version by: 

https://github.com/rjsf-team/react-jsonschema-form/pull/2670

**Comment by jlczuk** [comment]
@alfonsoar Yes, I have actually tried it.  The upgrade is apparently a breaking change and we cannot contain revising our code base in the near term.

**Comment by heath-freenome** [comment]
@jlczuk My best suggestion for you is to fork that old, unsupported repo and add it yourself until you are ready to consume the newest version of @rjsf
