### ISSUE TITLE
oneOf validations don't work when $id is set

### ISSUE THREAD

**Issue by debevoise** [rjsf-team/react-jsonschema-form#2685]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

[Here's the playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyIkaWQiOiJodHRwczovL3Jqc2YtdGVhbS5naXRodWIuaW8vaWQuanNvbiIsInR5cGUiOiJvYmplY3QiLCJvbmVPZiI6W3sicmVxdWlyZWQiOlsiZm9vIl0sInByb3BlcnRpZXMiOnsiZm9vIjp7InR5cGUiOiJzdHJpbmcifX19LHsicmVxdWlyZWQiOlsiYmFyIl0sInByb3BlcnRpZXMiOnsiYmFyIjp7InR5cGUiOiJzdHJpbmcifX19XX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19).

#### Observed behavior:

When I press submit on a schema that uses `oneOf` and has `$id` set, it will only validate data on the initial submit, and will allow submission of invalid form data afterwards. 

However, the schema form behaves as expected when I remove the `$id` field. 

### Steps to Reproduce

1. Define a schema that defines required properties in `oneOf` and has an `$id`
2. Don't enter any data and click submit, it should validate the empty fields and display errors
3. Click submit again... the errors will disappear and the onSubmit handler will be called

#### Expected behavior

Form should validate fields, display errors and prevent submission

### Version

3.2.1

**Comment by ranihorev** [comment]
I noticed the same behavior with `ifThenElse`. I had to remove the `$schema` and `$id` fields to fix it, not sure why though

**Comment by ranihorev** [comment]
This issue might be related to #2471
