### ISSUE TITLE
Unclear how to set up a working test environment: requestAnimationFrame error

### ISSUE THREAD

**Issue by debevoise** [rjsf-team/react-jsonschema-form#2686]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I really want to contribute to this! Last time I tried I couldn't get tests to run. @epicfaace recommended using Node 14, but that isn't feasible as Node 15 or below isnt supported on Apple silicon. 

Going through the process of:
```
npm install
npm run build
npm test
```

I get what appears to be a polyfill error in node running tests:
```
@rjsf/core:   1) anyOf
@rjsf/core:        should assign a default value and set defaults on option change:
@rjsf/core:      TypeError: requestAnimationFrame is not a function
@rjsf/core:       at requestHostCallback (node_modules/scheduler/cjs/scheduler.development.js:331:9)
@rjsf/core:       at unstable_scheduleCallback (node_modules/scheduler/cjs/scheduler.development.js:754:7)
@rjsf/core:       at scheduleSyncCallback (node_modules/react-dom/cjs/react-dom.development.js:11319:34)
@rjsf/core:       at scheduleCallbackForRoot (node_modules/react-dom/cjs/react-dom.development.js:21528:27)
@rjsf/core:       at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21424:7)
@rjsf/core:       at Object.enqueueSetState (node_modules/react-dom/cjs/react-dom.development.js:13100:5)
@rjsf/core:       at Form.Component.setState (node_modules/react/cjs/react.development.js:325:16)
...etc...
```

I tried running tests using node versions 16 and 17. 

### Steps to Reproduce
On a mac, using node:
1. npm install
2. npm build
3. npm test

#### Expected behavior

tests should run

#### Actual behavior

tests run up to a point, but an exception occurs and the test suite hangs. have to ctrl+c to stop. 

### Version

3.2.1

**Comment by epicfaace** [comment]
Yeah, currently it only works with node 14, we should fix it so it works with node 15 / 16. See https://github.com/rjsf-team/react-jsonschema-form/issues/2687

**Comment by dieseldjango** [comment]
I ran into this too. Until node 15+ support is added you could put a .nvmrc file in your repo so people using nvm get the right node version.

**Comment by epicfaace** [comment]
> I ran into this too. Until node 15+ support is added you could put a .nvmrc file in your repo so people using nvm get the right node version.

That would be helpful, would you mind making a PR to do so?
