### ISSUE TITLE
has no exported member named 'Theme5'

### ISSUE THREAD

**Issue by linonetwo** [rjsf-team/react-jsonschema-form#2690]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Regarding latest readme, there should be a `Theme5`?

### Steps to Reproduce

Same as readme using mui5

#### Expected behavior

Export mui5 theme

#### Actual behavior

Not exported using latest version.

### Version

    "@emotion/react": "^11.7.1",
    "@emotion/styled": "^11.6.0",
    "@mui/icons-material": "^5.3.1",
    "@mui/material": "^5.4.0",
    "@rjsf/core": "^3.2.1",
    "@rjsf/material-ui": "^3.2.1"

**Comment by linonetwo** [comment]
Can there be a beta release so we can have a try and finding potential bugs?

**Comment by epicfaace** [comment]
This will work in the next release. There's currently no plans for a beta release but the next release will be discussed at the next meeting: https://docs.google.com/document/d/12PjTvv21k6LIky6bNQVnsplMLLnmEuypTLQF8a-8Wss/edit
