### ISSUE TITLE
@rjsf/chakra-ui theme not published on npm

### ISSUE THREAD

**Issue by etaheri** [rjsf-team/react-jsonschema-form#2699]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
`@rjsf/chakra-ui` package is not published on NPM. Documentation indicates that it is published. [Doc](https://github.com/rjsf-team/react-jsonschema-form/blob/master/docs/usage/themes.md#supported-themes)

### Steps to Reproduce

1. Attempt to add `@rjsf/chakra-ui` dependency

#### Expected behavior
`@rjsf/chakra-ui` is available on NPM.

#### Actual behavior
`error An unexpected error occurred: "https://registry.yarnpkg.com/@rjsf%2fchakra-ui: Not found".`

Also not listed here: [NPM registry](https://www.npmjs.com/search?q=%40rjsf)

### Version
`3.2.1`

**Comment by epicfaace** [comment]
Will be published with v4 -- see https://github.com/rjsf-team/react-jsonschema-form/issues/2677 for updates
