### ISSUE TITLE
Incorrect validation of required child properties of optional properties?

### ISSUE THREAD

**Issue by dieseldjango** [rjsf-team/react-jsonschema-form#2708]
### Prerequisites

- [x ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Form validation fails if a required child property of an optional object property is missing.

### Steps to Reproduce

Add the following property schema to the "Simple" example in the playground:

```
    "address": {
      "type": "object",
      "properties": {
        "street": {
          "type": "string"
        },
        "zip": {
          "type": "string"
        }
      },
      "required": ["zip"]
    }
```

Submit the form without entering any address data

#### Expected behavior

Because address is optional and I did not enter any address, validation should succeed and the produced form should have no address property.

#### Actual behavior

Validation fails because the required zip property is missing.

### Version

3.2.1

**Comment by dieseldjango** [comment]
I think this is related to #2669, which mentions pruning empty leaf objects before validation.

**Comment by devinsm** [comment]
Hi there! I would love to contribute a fix if no one has started working on this yet. I have forked the repo and gotten the playground running locally. This is my first time contributing to this repo, so any pointers are welcome.

**Comment by dieseldjango** [comment]
Hi @devinsm I'm new to this repo too, so I can't provide any guidance. I can't use the package as-is without fixing this and need to deliver an alpha of my app very soon. Have you looked into the fix at all? Otherwise, I may poke around and see what I can figure out.

**Comment by dieseldjango** [comment]
I think one problem in dealing with this will be to determine when an object really is empty and can be pruned. There is bound to be ambiguity, such as differentiating between an empty string and an undefined one, a false boolean vs. undefined, an empty array vs. undefined, etc. Also, with enum properties it will be necessary to provide an empty, '--' option so the value can be unset. (That really should be supported in general for any optional enum as well.)

I'm thinking to prune recursively starting at leaf objects. If the object is optional and all of its properties are empty or false then delete it.

**Comment by dieseldjango** [comment]
It also looks like the whole way 'required' is handled needs reworking. The isRequired() method in ObjectField simply looks at the required property on the schema. The problem is that a 'required' property on an optional nested schema is not necessarily required. It would be better to simply rely on ajv validation so this code isn't basically repeating validation logic that's correctly implemented in ajv.

**Comment by epicfaace** [comment]
Would be open to accepting a PR that changes this behavior to be consistent
with that of ajv!

Ashwin Ramaswami

**Comment by pkcpkc** [comment]
The "required" attribute is misinterpreted, when an NOT required element contains required element itself.

Checking out this example:
An object with "name" (obligatory) and "link" (mandatory); the editor does NOT accept leaving "link" empty,  because its inner fields are obligatory.

`{
  "title": "My Test",
  "description": "My description",
  "type": "object",
  "properties": {
    "name": {
      "description": "The name of the menu item",
      "type": "string"
    },
    "link": {
      "$ref": "#/definitions/link"
    }
  },
  "additionalProperties": false,
  "required": [
    "name"
  ],
  "definitions": {
    "target": {
      "enum": [
        "article",
        "push",
        "link",
        "dataprivacy",
        "licenses",
        "stage"
      ]
    },
    "link": {
      "type": "object",
      "properties": {
        "url": {
          "type": "string"
        },
        "target": {
          "$ref": "#/definitions/target"
        }
      },
      "required": [
        "url",
        "target"
      ]
    }
  }
}`
