### ISSUE TITLE
Title in additionalProperties replaces real value

### ISSUE THREAD

**Issue by v1ack** [rjsf-team/react-jsonschema-form#2709]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

![Screenshot_20220215_152934](https://user-images.githubusercontent.com/11501957/154063205-908df371-94c5-47a1-9cf3-e490a73a325c.png)

If additional properties have title it will replace real key

### Steps to Reproduce

[Reprodusing link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJpbmNpZGVudHMiOnsiQW5JbXBvcnRhbnRNZXNzYWdlIjoia2VrIiwiQW5JbXBvcnRhbnRNZXNzYWdlMiI6ImtlazIifX0sInNjaGVtYSI6eyJ0aXRsZSI6IkNvbmZpZyIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImluY2lkZW50cyI6eyJ0aXRsZSI6IkEgbW9kZWwiLCJ0eXBlIjoib2JqZWN0IiwiYWRkaXRpb25hbFByb3BlcnRpZXMiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvQW5vdGhlck1vZGVsIn19fSwiZGVmaW5pdGlvbnMiOnsiQW5vdGhlck1vZGVsIjp7InRpdGxlIjoiQW5vdGhlck1vZGVsIiwidHlwZSI6InN0cmluZyJ9fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

1. Set up scheme with title in additional properties
2. Set formdata with any key

#### Expected behavior

I expected to see real key in input

#### Actual behavior

I see title of model instead of value

After deleting title it looks good

![Screenshot_20220215_154058](https://user-images.githubusercontent.com/11501957/154064350-fcc803fc-703a-4c0c-b05f-8dd3e86e0a4a.png)

### Version

3.2.1

**Comment by gturmel** [comment]
@v1ack I don't think that this is a bug, I think this is working as intended. [Definitions](https://react-jsonschema-form.readthedocs.io/en/latest/usage/definitions/) are intended to create a small, repeatable schema that can be referenced, without having to copy/paste the same piece of JSON over and over again. As the definition is supposed to be broad and generic, explicitly including a title lets us know that this title should be included for every place the definition is referenced.

**Comment by v1ack** [comment]
@gturmel I agree about title, but rewriting the real value can't be intended

**Comment by gturmel** [comment]
@v1ack Can you elaborate more about what you mean by `rewriting the real value`? From my understanding of RJSF, `formData` is _generated_, rather than used as a source of truth. The title set in definitions would _be_ the real value.

**Comment by v1ack** [comment]
fixed in #2878
