### ISSUE TITLE
releases don't exist: v3.3.0, v4.0.0

### ISSUE THREAD

**Issue by Morriz** [rjsf-team/react-jsonschema-form#2712]
Hi, we have begun extensive migration work on our large codebase, having read about `v3.3.0` supporting mui v5 (next to v4). The docs did not mention `v4.0.0`, but that tag also exists in the CHANGELOG (as does `v3.3.0`).

Based on the published information, I was under the impression that mui v5 was already supported. But I can't find any release that hits the mark. 

Now, may I ask if it exists, or when we can expect this? I believe I saw rjsf `v4` mentioned in june 2021 already, so we hope it will be any day now ;)

**Comment by epicfaace** [comment]
We won't support mui v5 in v3.3.0. The next version will be v4 and released on Friday. https://docs.google.com/document/d/12PjTvv21k6LIky6bNQVnsplMLLnmEuypTLQF8a-8Wss/edit

**Comment by Morriz** [comment]
FridaY? Yay! Tnx
