### ISSUE TITLE
omitExtraData/liveOmit doesn't work with dynamic/conditional schemas

### ISSUE THREAD

**Issue by nickgros** [rjsf-team/react-jsonschema-form#2720]
By adding support for conditional logic in schemas (#2700), schemas can now be dynamic. Because of this, it's possible for a user to enter data in a field, and afterwards conditional logic in the form can cause the field to no longer exist, or cause the data to no longer be shown in the form due to a type incompatibility. I would expect `omitExtraData` and `liveOmit` to handle this, but that doesn't seem to be the case.

In cases where the field no longer exists, the data will appear under additionalProperties if permitted by the schema. This is desirable under my use case, where I do not want to lose user data, so I'd like to preserve this behavior when `omitExtraData` and `liveOmit` are false.

**Comment by ksbrar** [comment]
bump

**Comment by dxdc** [comment]
bump

**Comment by nickgros** [comment]
Closing in favor of #4109 since that one has a playground example
