### ISSUE TITLE
No resolver found for key if (or then or else) in allOf subschema

### ISSUE THREAD

**Issue by Lay3r8** [rjsf-team/react-jsonschema-form#2726]
Hello,

I'm trying to reproduce the example called "If Then Else" available via that playground link https://rjsf-team.github.io/react-jsonschema-form. 

You can find an example of the (very simple) code I'm using on this JS Fiddle: https://jsfiddle.net/s03Lvuw9

The problem that I'm encountering is that these conditions (if, then and else) doesn't work (eg. I can't conditionally render any other field based on the value of the dropdown). I may be mistaken but after an extensive search it doesn't seem that there is any documentation about this either. To be more precise, "allOf" is documented but "If Then Else" isn't.

I also noticed that using those keywords produces the following warnings in the browser's console:
`
could not merge subschemas in allOf:
Error: No resolver found for key if. You can provide a resolver for this keyword in the options, or provide a default resolver.
`

Is there an example somewhere of a resolver I can find to fix this issue? I tried searching in the source code of the playground here https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/playground/src/app.js but I didn't find anything called 'resolver'.

**Comment by Spide** [comment]
I have the same issue with both 3.2.1 and latest version.

**Comment by bunge12** [comment]
I'm using the playground and my schema with `allOf` is also not working :/

**Comment by wasinsandiego** [comment]
Have any solutions or clues surfaced for anyone? Is the subschema they mention in reference to additional schemas that must be given the form component to handle things like conditional?

**Comment by shanthisagar-dhanya-kumar-db** [comment]
We are also facing the same issue. 
utils.js:713 
        
       could not merge subschemas in allOf:
Error: No resolver found for key if. You can provide a resolver for this keyword in the options, or provide a default resolver.

Has the If-then-else been removed from allOf schema?

**Comment by AlimovSV** [comment]
Check https://github.com/rjsf-team/react-jsonschema-form/issues/2752 - these issues looks very similar.
