### ISSUE TITLE
enumNames typing not supported

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#2761]
We support enumNames, but if we pass in enumNames in a schema prop to `<Form>`, we get this error:

![image](https://user-images.githubusercontent.com/1689183/158037429-d8b197d4-0ca0-4e7f-beb6-444a70a8886c.png)

**Comment by dwjohnston** [comment]
@epicfaace 

Just FYI pasting screenshots of errors mean that they aren't searchable. Luckily `enumNames` was searchable and I found this issue. 

The error message is: 

```
Object literal may only specify known properties, and 'enumNames' does not exist in type 'JSONSchema7'.`
```

**Comment by RowinVA** [comment]
See [comment #2663 ](https://github.com/rjsf-team/react-jsonschema-form/issues/2663#issuecomment-1106698186) for temporary fix.
