### ISSUE TITLE
MaterialUIContextProps and Mui5ContextProps not exported

### ISSUE THREAD

**Issue by szubster** [rjsf-team/react-jsonschema-form#2763]
I am working on upgrading rjsf for backstage: [PR](https://github.com/backstage/backstage/pull/9852)
After fix https://github.com/rjsf-team/react-jsonschema-form/pull/2732 I thought that v 4.1.0 will pass tsc and webpack, but it still fails on two missing export:

```
node_modules/@rjsf/material-ui/dist/MuiComponentContext/MuiComponentContext.d.ts:2:36 - error TS2307: Cannot find module '../Theme/MaterialUIContextProps' or its corresponding type declarations.

2 import MaterialUIContextProps from '../Theme/MaterialUIContextProps';
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@rjsf/material-ui/dist/MuiComponentContext/MuiComponentContext.d.ts:3:30 - error TS2307: Cannot find module '../Theme5/Mui5ContextProps' or its corresponding type declarations.

3 import Mui5ContextProps from '../Theme5/Mui5ContextProps';
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors.
```

**Comment by szubster** [comment]
Original issue https://github.com/rjsf-team/react-jsonschema-form/issues/2724 mentions those two exports as missing.

**Comment by benjdlambert** [comment]
Just done some digging into this. It looks like `'../Theme/MaterialUIContextProps'` and `'../Theme5/Mui5ContextProps'` are missing from the published package entirely. However if I run `build` on `master` these files are produced, so maybe a bad deploy?

If I copy these files into my local `node_modules` I get past this error, but then get greeted with some issues about `@mui/material` not being installed, but maybe we could add that as a `devDependency` or something so as not to interfere with our install of `@material-ui` that we're currently using.

What does the compatibility look like? Is there any documentation around any of this that I can read? Can we run `@rjsf/material-ui@v3.x` with `@rjsf/core@v4.x`? Or is it assumed that you need to be on `mui5` when using `@rjsf/core@v4.x`?

Thanks for the awesome library!

**Comment by heath-freenome** [comment]
> Just done some digging into this. It looks like `'../Theme/MaterialUIContextProps'` and `'../Theme5/Mui5ContextProps'` are missing from the published package entirely. However if I run `build` on `master` these files are produced, so maybe a bad deploy?
> 
> If I copy these files into my local `node_modules` I get past this error, but then get greeted with some issues about `@mui/material` not being installed, but maybe we could add that as a `devDependency` or something so as not to interfere with our install of `@material-ui` that we're currently using.
> 
> What does the compatibility look like? Is there any documentation around any of this that I can read? Can we run `@rjsf/material-ui@v3.x` with `@rjsf/core@v4.x`? Or is it assumed that you need to be on `mui5` when using `@rjsf/core@v4.x`?
> 
> Thanks for the awesome library!

As of `v4.1.0` the context is now publish. And we added a hook in `v4.1.1`. The `@mui/material` issue is known and reported in #2762 . You need to run `v.4` core with `v.4` material-ui...
