### ISSUE TITLE
Sorting and searching enumNames

### ISSUE THREAD

**Issue by Fohlen** [rjsf-team/react-jsonschema-form#2765]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Hi, currently it's possible to specify `enumNames` for `enum` type selections. This will render a `dropdown` menu, which is correct. However, for larger amounts of items (think e.g countries), the default sorting is annoying. The dropdown is sorted and rendered in-order with the `enum`. However, this does not really reflect the reality of a lot of use-cases.

### Steps to Reproduce

See the following Fiddle: 
https://jsfiddle.net/g03x2ejb/

#### Expected behavior

I would want to be able to display enum dropdowns, and would like to be able to search using `enumNames` instead of the `enum` values.

#### What actually happened

It's sorted in the default order as defined in the schema.

### Version

I'm only embedding react-jsonschema-form via Retool, so cannot guarantee the version is accurate, but according to their documentation it's the latest react-jsonschema-form release.

**Comment by PurnenduMIshra129th** [comment]
Hello Sir ,I want to solve this Issue. Please Assign this I can Solve this.

**Comment by andresespinosapc** [comment]
Can you elaborate on why you won't fix this? I think it's a huge problem and by default the search and sort should be by enumNames when provided.
