### ISSUE TITLE
Array nested inside of if/then/else not rendering if formData is empty?

### ISSUE THREAD

**Issue by ksbrar** [rjsf-team/react-jsonschema-form#2772]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

[Playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJzZWN0aW9uIjp7InNlbGVjdCI6Im5vcm1hbF9lbnVtIn19LCJzY2hlbWEiOnsidGl0bGUiOiJUZXN0IGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsiZmlyc3ROYW1lIiwibGFzdE5hbWUiXSwicHJvcGVydGllcyI6eyJzZWN0aW9uIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InNlbGVjdCI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJub3JtYWxfZW51bSIsImFycmF5X2VudW0iXSwiZGVmYXVsdCI6InR3byJ9fSwiYWxsT2YiOlt7ImlmIjp7InByb3BlcnRpZXMiOnsic2VsZWN0Ijp7ImNvbnN0Ijoibm9ybWFsX2VudW0ifX19LCJ0aGVuIjp7InByb3BlcnRpZXMiOnsic2luZ3VsYXIiOnsidHlwZSI6Im51bWJlciIsImZvcm1hdCI6ImZsb2F0IiwiZGVmYXVsdCI6MC4wMDEsIm1pbmltdW0iOjAsIm1heGltdW0iOjEsImRlc2NyaXB0aW9uIjoic2ltcGxlIGRlc2MuIn19fX0seyJpZiI6eyJwcm9wZXJ0aWVzIjp7InNlbGVjdCI6eyJjb25zdCI6ImFycmF5X2VudW0ifX19LCJ0aGVuIjp7InByb3BlcnRpZXMiOnsiZml4ZWRfYXJyYXkiOnsidHlwZSI6ImFycmF5IiwiaXRlbXMiOlt7InR5cGUiOiJudW1iZXIiLCJtaW5pbXVtIjowLCJtYXhpbXVtIjoxfSx7InR5cGUiOiJudW1iZXIiLCJtaW5pbXVtIjowLCJtYXhpbXVtIjoxfV0sImRlc2NyaXB0aW9uIjoiYXJyYXkgZGVzYy4ifX19fV0sInJlcXVpcmVkIjpbInNlbGVjdCJdfX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

I'm trying to build a schema that follows the current if/then/else example. Basically, we have a selection dropdown that changes the rest of the form - in the case of one selection, part of the form is specified by an array with two items.

If I add some `formData` values then this section will render. But on (default/empty) initial pageload, nothing renders.

### Steps to Reproduce

1. Open playground link
2. Pick second option in dropdown.

#### Expected behavior

Array part of the form should render with two empty fields.

#### Actual behavior

Array section does not render.

### Version

Latest

**Comment by wight554** [comment]
Can confirm, is there an alternative for using if then else?
My playground link: [https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJzZWN0aW9uIjp7ImJvb2xlYW5GaWVsZCI6dHJ1ZSwiYm9vbGVhbkZpZWwiOiJ0d28iLCJib29sZWFuRmllIjoidHdvIiwiYm9vbGVhbkZpIjoidHdvIiwiYm9vbGVhbkYiOiJ0d28iLCJib29sZWFuIjoidHdvIiwiYm9vbGVhIjoidHdvIiwiYm9vbGUiOiJ0d28iLCJib29sIjoidHdvIiwiYm9vIjoidHdvIiwiYm8iOiJ0d28iLCJiIjoidHdvIiwic2VsZWN0IjoiYXJyYXlfZW51bSJ9LCJib29sZWFuRmllbGQiOnsic2VsZWN0IjoidHdvIn0sImJvb2xlYW5GaWVsIjp7InNlbGVjdCI6InR3byJ9LCJib29sZWFuRmllIjp7InNlbGVjdCI6InR3byJ9LCJib29sZWFuRmkiOnsic2VsZWN0IjoidHdvIn0sImJvb2xlYW5GIjp7InNlbGVjdCI6InR3byJ9LCJib29sZWFuIjp7InNlbGVjdCI6InR3byJ9LCJib29sZWEiOnsic2VsZWN0IjoidHdvIn0sImJvb2xlIjp7InNlbGVjdCI6InR3byJ9LCJib29sIjp7InNlbGVjdCI6InR3byJ9LCJib28iOnsic2VsZWN0IjoidHdvIn0sImJvIjp7InNlbGVjdCI6InR3byJ9LCJiIjp7InNlbGVjdCI6InR3byJ9fSwic2NoZW1hIjp7InRpdGxlIjoiVGVzdCBmb3JtIiwiZGVzY3JpcHRpb24iOiJBIHNpbXBsZSBmb3JtIGV4YW1wbGUuIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsic2VjdGlvbiI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJib29sZWFuRmllbGQiOnsidHlwZSI6ImJvb2xlYW4iLCJkZWZhdWx0IjpmYWxzZX19LCJpZiI6eyJwcm9wZXJ0aWVzIjp7ImJvb2xlYW5GaWVsZCI6eyJjb25zdCI6dHJ1ZX19fSwidGhlbiI6eyJwcm9wZXJ0aWVzIjp7ImZpeGVkX2FycmF5Ijp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjpbeyJ0eXBlIjoibnVtYmVyIiwibWluaW11bSI6MCwibWF4aW11bSI6MX0seyJ0eXBlIjoibnVtYmVyIiwibWluaW11bSI6MCwibWF4aW11bSI6MX1dLCJkZXNjcmlwdGlvbiI6ImFycmF5IGRlc2MuIn19fX19fSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=](here)

**Comment by ksbrar** [comment]
@wight554 Haven't found an alternative myself, also fyi your link is broken

**Comment by wight554** [comment]
> @wight554 Haven't found an alternative myself, also fyi your link is broken

link seem to work, anyway managed to workaround this issue by using another example from docs
by using dependencies + oneOf: [link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJzZWN0aW9uIjp7ImJvb2xlYW5GaWVsZCI6ZmFsc2UsImZpeGVkX2FycmF5IjpbbnVsbCxudWxsXSwiYm9vbGVhbkZpZWwiOiJ0d28iLCJib29sZWFuRmllIjoidHdvIiwiYm9vbGVhbkZpIjoidHdvIiwiYm9vbGVhbkYiOiJ0d28iLCJib29sZWFuIjoidHdvIiwiYm9vbGVhIjoidHdvIiwiYm9vbGUiOiJ0d28iLCJib29sIjoidHdvIiwiYm9vIjoidHdvIiwiYm8iOiJ0d28iLCJiIjoidHdvIiwic2VsZWN0IjoiYXJyYXlfZW51bSJ9LCJib29sZWFuRmllbGQiOnsic2VsZWN0IjoidHdvIn0sImJvb2xlYW5GaWVsIjp7InNlbGVjdCI6InR3byJ9LCJib29sZWFuRmllIjp7InNlbGVjdCI6InR3byJ9LCJib29sZWFuRmkiOnsic2VsZWN0IjoidHdvIn0sImJvb2xlYW5GIjp7InNlbGVjdCI6InR3byJ9LCJib29sZWFuIjp7InNlbGVjdCI6InR3byJ9LCJib29sZWEiOnsic2VsZWN0IjoidHdvIn0sImJvb2xlIjp7InNlbGVjdCI6InR3byJ9LCJib29sIjp7InNlbGVjdCI6InR3byJ9LCJib28iOnsic2VsZWN0IjoidHdvIn0sImJvIjp7InNlbGVjdCI6InR3byJ9LCJiIjp7InNlbGVjdCI6InR3byJ9fSwic2NoZW1hIjp7InRpdGxlIjoiVGVzdCBmb3JtIiwiZGVzY3JpcHRpb24iOiJBIHNpbXBsZSBmb3JtIGV4YW1wbGUuIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsic2VjdGlvbiI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJib29sZWFuRmllbGQiOnsidHlwZSI6ImJvb2xlYW4iLCJkZWZhdWx0IjpmYWxzZX19LCJkZXBlbmRlbmNpZXMiOnsiYm9vbGVhbkZpZWxkIjp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7ImJvb2xlYW5GaWVsZCI6eyJjb25zdCI6ZmFsc2V9fX0seyJwcm9wZXJ0aWVzIjp7ImJvb2xlYW5GaWVsZCI6eyJjb25zdCI6dHJ1ZX0sImZpeGVkX2FycmF5Ijp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjpbeyJ0eXBlIjoibnVtYmVyIiwibWluaW11bSI6MCwibWF4aW11bSI6MX0seyJ0eXBlIjoibnVtYmVyIiwibWluaW11bSI6MCwibWF4aW11bSI6MX1dLCJkZXNjcmlwdGlvbiI6ImFycmF5IGRlc2MuIn19fV19fX19fSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

**Comment by ksbrar** [comment]
@wight554 huh, wasn't working for me earlier but it is now. sorry for the unnecessary ping. but thanks for the workaround! Doesn't quite work for my use case, but should help others.

**Comment by ksbrar** [comment]
It appears this has been fixed in one of the recent releases. Thanks!
