### ISSUE TITLE
MUIv5 Failing Example 

### ISSUE THREAD

**Issue by JeremyRubin** [rjsf-team/react-jsonschema-form#2774]
This example fails because of the CPFP Config field under RSJF Playground (and deployed). Changing the CPFP Config type to just string passes. It passes under other themes.

https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCIsImFyZ3VtZW50cyI6eyJwZCI6bnVsbH19LCJzY2hlbWEiOnsiJHNjaGVtYSI6Imh0dHA6Ly9qc29uLXNjaGVtYS5vcmcvZHJhZnQtMDcvc2NoZW1hIyIsImRlZmluaXRpb25zIjp7IkFkZHJlc3MiOnsicGF0dGVybiI6Il4oKFsxM118W21uXSlbYS1rbS16QS1ISi1OUC1aMS05XXsyNSwzNH18KGJjfHRifGJjcnQpMVthYy1oai1ucC16QUMtSEotTlAtWjAyLTldezExLDcxfSkkIiwidHlwZSI6InN0cmluZyJ9LCJBbnlSZWxUaW1lTG9jayI6eyJkZXNjcmlwdGlvbiI6IlJlcHJlc2VudHMgYSB0eXBlIHdoaWNoIGNhbiBiZSBlaXRoZXIgdHlwZSBvZiByZWxhdGl2ZSBsb2NrIiwib25lT2YiOlt7ImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjpmYWxzZSwiZGVzY3JpcHRpb24iOiJpbiBudW1iZXIgb2YgYmxvY2tzIiwicHJvcGVydGllcyI6eyJSSCI6eyJmb3JtYXQiOiJ1aW50MzIiLCJtaW5pbXVtIjowLCJ0eXBlIjoiaW50ZWdlciJ9fSwicmVxdWlyZWQiOlsiUkgiXSwidGl0bGUiOiJSZWxhdGl2ZSBIZWlnaHQiLCJ0eXBlIjoib2JqZWN0In0seyJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2UsImRlc2NyaXB0aW9uIjoiaW4gY2h1bmtzIG9mIDUxMiBzZWNvbmRzIiwicHJvcGVydGllcyI6eyJSVCI6eyJmb3JtYXQiOiJ1aW50MzIiLCJtaW5pbXVtIjowLCJ0eXBlIjoiaW50ZWdlciJ9fSwicmVxdWlyZWQiOlsiUlQiXSwidGl0bGUiOiJSZWxhdGl2ZSBUaW1lIiwidHlwZSI6Im9iamVjdCJ9XSwidGl0bGUiOiJBbnkgUmVsYXRpdmUgVGltZSBMb2NrIn0sIkNvbnRleHR1YWxBcmd1bWVudHMiOnsicHJvcGVydGllcyI6eyJhbW91bnQiOnsiZm9ybWF0IjoiZG91YmxlIiwidGl0bGUiOiJUaGUgQW1vdW50IG9mIEZ1bmRzIEF2YWlsYWJsZSB0byB0aGUgQ29udHJhY3QgYXMgQml0Y29pbi4iLCJ0eXBlIjoibnVtYmVyIn0sImVmZmVjdHMiOnsiYWxsT2YiOlt7IiRyZWYiOiIjL2RlZmluaXRpb25zL01hcEVmZmVjdERCIn1dLCJ0aXRsZSI6IkVmZmVjdHMgdG8gYXVnbWVudCBjb21waWxhdGlvbnMgd2l0aCJ9LCJuZXR3b3JrIjp7ImFsbE9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9OZXR3b3JrIn1dLCJ0aXRsZSI6IlRoZSBOZXR3b3JrIHRoZSBjb250cmFjdCBzaG91bGQgYmUgY3JlYXRlZCBmb3IuIn19LCJyZXF1aXJlZCI6WyJhbW91bnQiLCJuZXR3b3JrIl0sInRpdGxlIjoiQ29udGV4dHVhbCBBcmd1bWVudHMgRm9yIENyZWF0aW5nIHRoaXMgQ29udHJhY3QiLCJ0eXBlIjoib2JqZWN0In0sIkhhc2giOnsiZGVzY3JpcHRpb24iOiJPdXRwdXQgb2YgdGhlIFNIQTI1NiBoYXNoIGZ1bmN0aW9uIiwibWF4TGVuZ3RoIjo2NCwibWluTGVuZ3RoIjo2NCwicGF0dGVybiI6IlswLTlhLWZBLUZdKyIsInR5cGUiOiJzdHJpbmcifSwiTWFwRWZmZWN0REIiOnsiZGVzY3JpcHRpb24iOiJNYXAgb2YgYWxsIGVmZmVjdHMgdG8gcHJvY2VzcyBkdXJpbmcgY29tcGlsYXRpb24uICBFYWNoIEtleSByZXByZXNlbnRzIGEgcGF0aCwgZWFjaCBzdWIta2V5IHJlcHJlc2VudHMgdGhlIHN1Yi1wYXRoIG5hbWUgYW5kIHZhbHVlLiIsInByb3BlcnRpZXMiOnsiZWZmZWN0cyI6eyJhZGRpdGlvbmFsUHJvcGVydGllcyI6eyJhZGRpdGlvbmFsUHJvcGVydGllcyI6dHJ1ZSwidHlwZSI6Im9iamVjdCJ9LCJkZXNjcmlwdGlvbiI6Ikxpc3Qgb2YgZWZmZWN0cyB0byBpbmNsdWRlIHdoaWxlIGNvbXBpbGluZy4iLCJ0aXRsZSI6IlRoZSBzZXQgb2YgYWxsIGVmZmVjdHMiLCJ0eXBlIjoib2JqZWN0In19LCJ0aXRsZSI6IkVmZmVjdHMiLCJ0eXBlIjoib2JqZWN0In0sIk5ldHdvcmsiOnsiZW51bSI6WyJCaXRjb2luIiwiVGVzdG5ldCIsIlNpZ25ldCIsIlJlZ3Rlc3QiXSwidHlwZSI6InN0cmluZyJ9LCJWYXVsdF9mb3JfU2VjdXJlIjp7InByb3BlcnRpZXMiOnsiYmFja3VwIjp7ImFueU9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9IYXNoIn0seyJ0eXBlIjoibnVsbCJ9XSwiZGVzY3JpcHRpb24iOiJJZiBhdmFpbGFibGUsIHRoaXMga2V5IGNhbiBiZSB1c2VkIGltbWVkaWF0ZWx5IGFzIGEgc2luZ2xlIHNpZyBjb2xkIG11bHRpc2lnIG9wdGlvbi4gdXNhYmxlIHdpdGggYSBtdXNpZyBrZXkuIiwidGl0bGUiOiJCYWNrdXAgRGlyZWN0In0sImJhY2t1cF9hZGRyIjp7ImFsbE9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9BZGRyZXNzIn1dLCJkZXNjcmlwdGlvbiI6IldoZXJlIGZ1bmRzIHNob3VsZCBsYW5kIGlmIHRoZXkgYXJlIGJhY2tlZCB1cCIsInRpdGxlIjoiQmFja3VwIEFkZHJlc3MifSwiY3BmcCI6eyJkZXNjcmlwdGlvbiI6IklmIGEgQ1BGUCBhbmNob3IgaXMgdG8gYmUgYWRkZWQsIGhvdyBtdWNoIGZ1bmRzIHRvIGluY2x1ZGUgaW4gaXQiLCJpdGVtcyI6W3siJHJlZiI6IiMvZGVmaW5pdGlvbnMvQWRkcmVzcyJ9LHsiZm9ybWF0IjoidWludDY0IiwibWluaW11bSI6MCwidHlwZSI6ImludGVnZXIifV0sIm1heEl0ZW1zIjoyLCJtaW5JdGVtcyI6MiwidGl0bGUiOiJDUEZQIENvbmZpZyIsInR5cGUiOlsiYXJyYXkiLCJudWxsIl19LCJkZWZhdWx0X2ZlZSI6eyJmb3JtYXQiOiJ1aW50NjQiLCJtaW5pbXVtIjowLCJ0eXBlIjoiaW50ZWdlciJ9LCJob3Rfa2V5Ijp7ImFsbE9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9IYXNoIn1dLCJ0aXRsZSI6IkhvdCBLZXkifSwicGQiOnsidHlwZSI6Im51bGwiLCJ3cml0ZU9ubHkiOnRydWV9LCJ0aW1lb3V0Ijp7ImFsbE9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9BbnlSZWxUaW1lTG9jayJ9XSwiZGVzY3JpcHRpb24iOiJIb3cgTXVjaCBUaW1lIHRvIHdhaXQgYmVmb3JlIHJlZGVlbWFibGUiLCJ0aXRsZSI6IlRpbWVvdXQifX0sInJlcXVpcmVkIjpbImJhY2t1cF9hZGRyIiwiZGVmYXVsdF9mZWUiLCJob3Rfa2V5IiwicGQiLCJ0aW1lb3V0Il0sInR5cGUiOiJvYmplY3QifX0sImRlc2NyaXB0aW9uIjoiUHJvdmlkZSB0aGlzIGluZm9ybWF0aW9uIHRvIGNyZWF0ZSBhbiBpbnN0YW5jZSBvZiBhIGNvbnRyYWN0IiwicHJvcGVydGllcyI6eyJhcmd1bWVudHMiOnsiYWxsT2YiOlt7IiRyZWYiOiIjL2RlZmluaXRpb25zL1ZhdWx0X2Zvcl9TZWN1cmUifV0sInRpdGxlIjoiVGhlIE1haW4gQ29udHJhY3QgQXJndW1lbnRzIn0sImNvbnRleHQiOnsiYWxsT2YiOlt7IiRyZWYiOiIjL2RlZmluaXRpb25zL0NvbnRleHR1YWxBcmd1bWVudHMifV0sImRlc2NyaXB0aW9uIjoiT3RoZXJzIGFyZ3VtZW50cyBzZXQgYnkgZ2VuZXJhbCBzeXN0ZW0gc2V0dGluZ3MiLCJ0aXRsZSI6IkNvbnRleHR1YWwgQXJndW1lbnRzIn19LCJyZXF1aXJlZCI6WyJhcmd1bWVudHMiLCJjb250ZXh0Il0sInRpdGxlIjoiQXJndW1lbnRzIEZvciBDcmVhdGluZyB0aGlzIENvbnRyYWN0IiwidHlwZSI6Im9iamVjdCJ9LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIiwidWk6YXV0b2NvbXBsZXRlIjoiZmFtaWx5LW5hbWUifSwibGFzdE5hbWUiOnsidWk6ZW1wdHlWYWx1ZSI6IiIsInVpOmF1dG9jb21wbGV0ZSI6ImdpdmVuLW5hbWUifSwiYWdlIjp7InVpOndpZGdldCI6InVwZG93biIsInVpOnRpdGxlIjoiQWdlIG9mIHBlcnNvbiIsInVpOmRlc2NyaXB0aW9uIjoiKGVhcnRoaWFuIHllYXIpIn0sImJpbyI6eyJ1aTp3aWRnZXQiOiJ0ZXh0YXJlYSJ9LCJwYXNzd29yZCI6eyJ1aTp3aWRnZXQiOiJwYXNzd29yZCIsInVpOmhlbHAiOiJIaW50OiBNYWtlIGl0IHN0cm9uZyEifSwiZGF0ZSI6eyJ1aTp3aWRnZXQiOiJhbHQtZGF0ZXRpbWUifSwidGVsZXBob25lIjp7InVpOm9wdGlvbnMiOnsiaW5wdXRUeXBlIjoidGVsIn19fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19

**Comment by heath-freenome** [comment]
Fixed in v5 beta
