### ISSUE TITLE
Bootstrap-4 theme does not render array with different item types

### ISSUE THREAD

**Issue by rkeulemans** [rjsf-team/react-jsonschema-form#2775]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue. [Codesandbox Here](https://codesandbox.io/s/rjsf-does-not-render-when-using-bootstrap-4-theme-and-complex-schema-gqnzxp?file=/src/Test.tsx)

### Description

The `bootstrap-4` theme does not render when using this schema, while the `core` does this perfectly fine (see Codesandbox)
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Name Registration Form",
  "type": "object",
  "required": [
      "full_name"
  ],
  "properties": {
      "full_name": {
          "title": "Full Name",
          "description": "Please provide your full name",
          "type": "array",
          "items": [
              {
                  "type": "string"
              },
              {
                  "type": "string"
              }
          ],
          "maxItems": 2,
          "minItems": 2
      }
  }
}
```

### Steps to Reproduce

Run Codesandbox.

#### Expected behavior

Renders the schema in the UI.

#### Actual behavior

Does not render schema and presents an error:

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ArrayFieldDescription`.
```

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one:

```json
  "dependencies": {
    "@rjsf/core": "4.1.0",
    "@rjsf/bootstrap-4": "4.1.0",
    "react-bootstrap": "1.6.4",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-scripts": "4.0.3"
  },
```

**Comment by heath-freenome** [comment]
Fixed in the v5 beta, see the [5.x migration guide](https://react-jsonschema-form.readthedocs.io/en/latest/5.x%20upgrade%20guide/)
