### ISSUE TITLE
Boolean labels not showing up in Semantic UI

### ISSUE THREAD

**Issue by ben-z** [rjsf-team/react-jsonschema-form#2791]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Boolean labels don't show up for Semantic UI:

![image](https://user-images.githubusercontent.com/5977478/161325859-711355a2-bf06-4c8f-b112-12a7e00d6361.png)

And it does show up for all other themes. For example Material UI 5:

![image](https://user-images.githubusercontent.com/5977478/161325872-a4a2fc59-fd17-4e87-88c1-338e83e85a87.png)

No errors in the javascript console either.

### Steps to Reproduce

1. Go to https://rjsf-team.github.io/react-jsonschema-form/
2. Click on "All Of" (or any other examples with a boolean field

#### Expected behavior

The boolean field should have a label.

#### Actual behavior

The boolean field does not have a label.

### Version

v4.1.1

**Comment by ErQrYfkrju** [comment]
Hello, any news on this issue.
Just tried 5.0.0-beta.14 and this issue is stil present there.
