### ISSUE TITLE
If/then/else not working if schema contains an id or $id attribute

### ISSUE THREAD

**Issue by bgrossiord** [rjsf-team/react-jsonschema-form#2821]
Prerequisites
 Link to the playground demonstrating the issue: [Playgroung Link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaWVsZC0xIjp7fX0sInNjaGVtYSI6eyIkaWQiOiJtb2lyaGdvYWllcmdvaWpnOTg0OGY1NHFkZjU0ZWFyZyIsInRpdGxlIjoidGVzdCBkYXRlIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZmllbGQtMSI6eyJ0aXRsZSI6IkNvbnRyYWN0IFR5cGUgYW5kIERhdGVzIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZHVyYXRpb25UeXBlIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIkNESSIsIkNERCJdLCJtYXhMZW5ndGgiOjMwfSwiYmVnaW4iOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiYmVnaW4iLCJmb3JtYXQiOiJkYXRlIiwiZGVzY3JpcHRpb24iOiJGb3JtYXQgREQvTU0vWVlZWSIsIm1heExlbmd0aCI6MTB9fSwiaWYiOnsicHJvcGVydGllcyI6eyJkdXJhdGlvblR5cGUiOnsiZW51bSI6WyJDREQiXX19fSwidGhlbiI6eyJwcm9wZXJ0aWVzIjp7ImVuZCI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJlbmQiLCJmb3JtYXQiOiJkYXRlIiwiZGVzY3JpcHRpb24iOiJGb3JtYXQgREQvTU0vWVlZWSIsIm1heExlbmd0aCI6MTAsImFmdGVyIjoiYmVnaW4ifSwiZHVyYXRpb25ZWVlZIjp7InR5cGUiOiJpbnRlZ2VyIiwidGl0bGUiOiJEdXJhdGlvbllZWVkiLCJtaW5pbXVtIjowLCJlbmREYXRlRnJvbUR1cmF0aW9uIjpbImJlZ2luIiwiZW5kIiwiZHVyYXRpb25ZWVlZIiwiZHVyYXRpb25NTSIsImR1cmF0aW9uREQiXX0sImR1cmF0aW9uTU0iOnsidHlwZSI6ImludGVnZXIiLCJ0aXRsZSI6IkR1cmF0aW9uTU0iLCJtYXhpbXVtIjoxMSwibWluaW11bSI6MCwiZW5kRGF0ZUZyb21EdXJhdGlvbiI6WyJiZWdpbiIsImVuZCIsImR1cmF0aW9uWVlZWSIsImR1cmF0aW9uTU0iLCJkdXJhdGlvbkREIl19LCJkdXJhdGlvbkREIjp7InR5cGUiOiJpbnRlZ2VyIiwidGl0bGUiOiJEdXJhdGlvbkREIiwibWF4aW11bSI6MzAsIm1pbmltdW0iOjAsImVuZERhdGVGcm9tRHVyYXRpb24iOlsiYmVnaW4iLCJlbmQiLCJkdXJhdGlvbllZWVkiLCJkdXJhdGlvbk1NIiwiZHVyYXRpb25ERCJdfX19LCJ2ZXJzaW9uIjoxLCJmaWVsZElkIjoibHNfY29udHJhY3RfdHlwZV9kYXRlcyJ9LCJmaWVsZDIiOnsidHlwZSI6InN0cmluZyJ9fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJmYW1pbHktbmFtZSJ9LCJsYXN0TmFtZSI6eyJ1aTplbXB0eVZhbHVlIjoiIiwidWk6YXV0b2NvbXBsZXRlIjoiZ2l2ZW4tbmFtZSJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoidXBkb3duIiwidWk6dGl0bGUiOiJBZ2Ugb2YgcGVyc29uIiwidWk6ZGVzY3JpcHRpb24iOiIoZWFydGhpYW4geWVhcikifSwiYmlvIjp7InVpOndpZGdldCI6InRleHRhcmVhIn0sInBhc3N3b3JkIjp7InVpOndpZGdldCI6InBhc3N3b3JkIiwidWk6aGVscCI6IkhpbnQ6IE1ha2UgaXQgc3Ryb25nISJ9LCJkYXRlIjp7InVpOndpZGdldCI6ImFsdC1kYXRldGltZSJ9LCJ0ZWxlcGhvbmUiOnsidWk6b3B0aW9ucyI6eyJpbnB1dFR5cGUiOiJ0ZWwifX19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

Description
When using if then else in a schema that is containing a $id or id attribute, the if the else is not working as expected

Steps to Reproduce
Follow link to playground
Change the duration type field to CDD 

Expected behavior
The fields end and durationYYYY durationMM DurationDD should be present

Actual behavior
The fields end and durationYYYY durationMM DurationDD are not displayed

Versions
4.1.0 & 4.1.1

**Comment by PiotrPaprockiSportradar** [comment]
It doesn't work for all top attributes with `$` prefix, so `$id`, `$schema`, etc. Didn't check for nested schemas etc.

**Comment by xpositivityx** [comment]
I am more than happy to give fixing this a shot. This has become a pretty big issue for me. I have some failing tests, but I have no clue where to even start looking for the root cause. Any suggestions?

**Comment by SjoerdManger** [comment]
> I am more than happy to give fixing this a shot. This has become a pretty big issue for me. I have some failing tests, but I have no clue where to even start looking for the root cause. Any suggestions?

It's a big issue for me as well. Any updates on your end? I'd like to help wherever possible.

**Comment by nickgros** [comment]
This should be fixed in 5.0.0-beta.13 (when it is released). This will only be fixed with @rjsf/validator-ajv8. Please re-open if any issues persist.
