### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by dthulin** [rjsf-team/react-jsonschema-form#2826]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.
(But it's the documentation, so I'm not...)

### Description

https://react-jsonschema-form.readthedocs.io/en/docs/usage/oneof/ has an error in the documentation.
`A schema with oneOf is valid if exactly one of the subschemas is valid.
A schema with allOf is valid if at least one of the subschemas is valid.
A schema with allOf is valid if all of the subschemas are valid.`
should read...
`A schema with oneOf is valid if exactly one of the subschemas is valid.
A schema with anyOf is valid if at least one of the subschemas is valid.
A schema with allOf is valid if all of the subschemas are valid.`
notice change one middle line

### Steps to Reproduce

1. Go to link: https://react-jsonschema-form.readthedocs.io/en/docs/usage/oneof/
2. Search for `A schema with allOf is valid if at least one of the subschemas is valid.` and notice it is wrong.

#### Expected behavior

The line above should read `A schema with anyOf is valid if at least one of the subschemas is valid.`

#### Actual behavior

The line above reads `A schema with allOf is valid if at least one of the subschemas is valid.`

### Version

Current live documentation.

**Comment by epicfaace** [comment]
Thanks, can you make a PR?

--
Ashwin Ramaswami

**Comment by dthulin** [comment]
Here's the code: [docs/usage/oneof.md](https://github.com/rjsf-team/react-jsonschema-form/blob/master/docs/usage/oneof.md) on line 6 it looks correct to me.
I have no way to reproduce locally. It looks like it could be a configuration issue. The first of the following links is the problem one, the second works as expected:
https://react-jsonschema-form.readthedocs.io/en/docs/usage/oneof/
https://react-jsonschema-form.readthedocs.io/en/latest/usage/oneof/

**Comment by epicfaace** [comment]
Oh, https://react-jsonschema-form.readthedocs.io/en/docs/usage/oneof/ is the wrong link. That's deployed from a different branch, I think. Not sure where you got it from?
