### ISSUE TITLE
ui:submitButtonOptions don't work. 

### ISSUE THREAD

**Issue by dwjohnston** [rjsf-team/react-jsonschema-form#2831]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue. (**Code Repo**) 

### Description

None of the ui:submitButtonOptions work on @rjsf/material-ui@4.1.1 or @rjsf/core@4.1.1

### Steps to Reproduce

1. Check out this codebase https://github.com/dwjohnston/rjsf-bug
2. `yarn && yarn start`
3. Note that the submit button is not customised. 

Code for quick reference: 

```jsx

function App() {
  return (
    <div className="App">

      <Form
        uiSchema={{
          "ui:submitButtonOptions": {
            "submitText": "Confirm Details",
            "norender": false,
            "props": {
              "disabled": false,
              "className": "btn btn-info"
            }
          },
          "firstName": {
            "ui:autofocus": true,
            "ui:emptyValue": "",
            "ui:autocomplete": "family-name"
          },
          "lastName": {
            "ui:title": "Surname",
            "ui:emptyValue": "",
            "ui:autocomplete": "given-name"
          },
          "age": {
            "ui:widget": "updown",
            "ui:title": "Age of person",
            "ui:description": "(earthian year)"
          },
          "bio": {
            "ui:widget": "textarea"
          },
          "password": {
            "ui:widget": "password",
            "ui:help": "Hint: Make it strong!"
          },
          "date": {
            "ui:widget": "alt-datetime"
          },
          "telephone": {
            "ui:options": {
              "inputType": "tel"
            }
          }
        }}
        schema={{
          "title": "A registration form",
          "description": "A simple form example. Demonstrating ui options",
          "type": "object",
          "required": [
            "firstName",
            "lastName"
          ],
          "properties": {
            "firstName": {
              "type": "string",
              "title": "First name",
              "default": "Chuck"
            },
            "lastName": {
              "type": "string",
              "title": "Last name"
            },
            "telephone": {
              "type": "string",
              "title": "Telephone",
              "minLength": 10
            }
          }
        }}
      />


    </div>
  );
}
```

#### Expected behavior

The submit button should be customised as [per the documentation](https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/uiSchema/#submitbuttonoptions) and [sandbox example](https://rjsf-team.github.io/react-jsonschema-form/). 

Curiously enough, this issue is not present on the sandboxes. 

#### Actual behavior

None of the submitButtonOptions appear to work. 

### Version

4.1.1

**Comment by dwjohnston** [comment]
I'm wondering if the package simply hasn't been published since this feature was added. #2640 was merged 13 days ago, but npm says last publish was a month ago.

**Comment by jacqueswho** [comment]
> I'm wondering if the package simply hasn't been published since this feature was added. #2640 was merged 13 days ago, but npm says last publish was a month ago.

@dwjohnston Hi, material-ui still needs this feature. I have implemented on most of the other themes. If you test the playground you should see which ones have this feature. Because of the complexity of the theme, I decided to leave the contributor to implement this feature. @heath-freenome just letting you know

**Comment by heath-freenome** [comment]
@jacqueswho I'm pretty sure that you could easily add the `SubmitButton` feature into `@material-ui` yourself since the pattern you've establish is straight-forward. I'd be glad to do the review for you. I'm currently working on a few other higher-priority (for me) RJSF issues so it would take me at least another month to get to it, plus you understand the feature better than I.

**Comment by heath-freenome** [comment]
> I'm wondering if the package simply hasn't been published since this feature was added. #2640 was merged 13 days ago, but npm says last publish was a month ago.

That is the case, yes

**Comment by jacqueswho** [comment]
@heath-freenome the button code is merged in. But I think your default children will override this functionality. I did not want to change or remove yours because of the warnings needed for not having packages installed

**Comment by heath-freenome** [comment]
@jacqueswho I am not sure what you mean by `default children` will override this functionality? Maybe you can show me at the friday meeting?

**Comment by jacqueswho** [comment]
Please be aware material UI does not support yet submit button options. We are aware of this issue.

**Comment by jacqueswho** [comment]
> @jacqueswho you mean in the playground, right? I believe it could work outside of it

I don't think so because the default children will take over.

**Comment by heath-freenome** [comment]
> Please be aware material UI does not support yet submit button options. We are aware of this issue.

Fix is incoming

**Comment by jacqueswho** [comment]
Please latest version 4.2.0
