### ISSUE TITLE
Docs should not contain features that are not yet in the NPM package

### ISSUE THREAD

**Issue by ferretwithaberet** [rjsf-team/react-jsonschema-form#2847]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### Is your feature request related to a problem? Please describe.

Docs contains information on features that cannot be used through the NPM package yet. It took me 2 days to realize that [submit button options](https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/uiSchema/#submitbuttonoptions) are not yet in the published version and that's why they do not work.

### Describe the solution you'd like

Docs should only contain information that is confirmed to work in the version published on NPM.

**Comment by epicfaace** [comment]
Maybe we can only publish docs on a new release? Want to make a PR that
modifies github actions to do so?

--
Ashwin Ramaswami
