### ISSUE TITLE
Why are defaults merged with formData object properties when those properties are already set?

### ISSUE THREAD

**Issue by mattpardee** [rjsf-team/react-jsonschema-form#2848]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### What is your question?

We have a schema with definitions that get pre-populated into `formData` on first load - which is great! But if I start with my own edited `formData`, any missing properties from `defaults` are merged into formData on load. For example if this is the formData:

```json
{
  "a": { "foo": "Our edited value" }
}
```

and the defaults are:

```json
{
  "a": { "foo": "", "wee": {} }
}
```

...then on load it turns our edited `formData` into:

```json
{
  "a": { "foo": "Our edited value", "wee": {} }
}
```
 
This is less desirable for our implementation because we need formData to be set to exactly what we've edited it to (the ultimate issue is the data being propagated on contains empty parameters inside `formData` which the remote server rejects with an error and our request is unsuccessful).

We've considered recursively removing empty values in our object properties as a final step before persisting/processing the data, but that has proven to carry its own problems outside of this specific case. However, we can't find issue with the idea of not merging defaults with overwritten/edited properties values, and we're wondering what side effects lurk if the new default behavior was "Don't merge defaults with formData[key] if this formData[key] object property is already set". Any help elucidating this is appreciated, thank you!

**Comment by epicfaace** [comment]
This doc page describes how defaults are merged currently... https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/internals/#handling-of-schema-defaults Does that help? I don't think we can change the default behavior, but we could consider a code change that makes it easier to handle your case.

**Comment by mattpardee** [comment]
Yes read through those and they were very helpful. I agree, changing the default behavior would be problematic. I was curious if those more familiar could foresee any unintended knock-on effects from changing that behavior in principle, but I can investigate options for providing an alternative behavior path and see what comes of that. Thank you!
