### ISSUE TITLE
Nested oneOf json schema works, but rjsf throws error

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [rjsf-team/react-jsonschema-form#2862]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

4.1.1

### Current Behavior

[Playground Link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6IkFzc2V0IFR5cGUiLCJwcm9wZXJ0aWVzIjp7InR5cGUiOnsib25lT2YiOlt7InR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6IkNvbXBvbmVudCIsInByb3BlcnRpZXMiOnsiY29tcG9uZW50U3ViVHlwZSI6eyJvbmVPZiI6W3sidHlwZSI6Im9iamVjdCIsInRpdGxlIjoid2Vic2l0ZSIsInByb3BlcnRpZXMiOnsid2Vic2l0ZSI6eyJ0eXBlIjoic3RyaW5nIiwiZGVzY3JpcHRpb24iOiJXZWJzaXRlIiwicmVhZE9ubHkiOnRydWUsImRlZmF1bHQiOiJ3ZWJzaXRlIn19fSx7InR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6InNlcnZpY2UiLCJwcm9wZXJ0aWVzIjp7IndlYnNpdGUiOnsidHlwZSI6InN0cmluZyIsImRlc2NyaXB0aW9uIjoiV2Vic2l0ZSIsInJlYWRPbmx5Ijp0cnVlLCJkZWZhdWx0Ijoid2Vic2l0ZSJ9fX1dfX19LHsidHlwZSI6Im9iamVjdCIsInRpdGxlIjoiQVBJIiwicmVxdWlyZWQiOlsidHlwZSIsImFwaURlZmluaXRpb24iXSwicHJvcGVydGllcyI6eyJ0eXBlIjp7InRpdGxlIjoiQVBJIFR5cGUiLCJ0eXBlIjoic3RyaW5nIiwiZGVzY3JpcHRpb24iOiJPcGVuQVBJIC8gQXN5bmNBUEkvIEdyYXBoUUwgLyBnUlBDIiwiZW51bSI6WyJvcGVuYXBpIiwiYXN5bmNhcGkiLCJncmFwaHFsIiwiZ3JwYyJdfSwiYXBpRGVmaW5pdGlvbiI6eyJ0aXRsZSI6IkFQSSBEZWZpbml0aW9uIiwidHlwZSI6InN0cmluZyIsImRlc2NyaXB0aW9uIjoiUHJvdmlkZSBsaW5rIHRvIHRoZSBkZWZpbml0aW9uIG9mIHRoZSBBUEkgU3BlY2lmaWNhdGlvbi4iLCJmb3JtYXQiOiJ1cmkiLCJwYXR0ZXJuIjoiaHR0cHM/Oi8vIiwiZGVmYXVsdCI6Imh0dHBzOi8vIiwidWk6ZmllbGQiOiJVUkxWYWx1ZVBpY2tlciIsInVpOmF1dG9mb2N1cyI6dHJ1ZX19fV19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

The json schem is valid

**Comment by nickgros** [comment]
@shanthisagar-dhanya-kumar-db We cannot reproduce this in 5.0.0-beta.13. Please re-open or open a new issue with more details if you're still experiencing this issue.
