### ISSUE TITLE
html input maxlength minlength attributes

### ISSUE THREAD

**Issue by sanjeev16011994** [rjsf-team/react-jsonschema-form#2864]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### Describe the solution you'd like

i would like to have maxlength attribute to input type text to allow only certain values. like if max length is set to 10 . the input field will not take more than ten characters

**Comment by heath-freenome** [comment]
If you do something like the following it should work.

```tsx
schema = {
  type: "string"
}

uiSchema = {
  "ui:options": {
    maxLength: 10
  }
}

<Form schema={schema} uiSchema={uiSchema} />

```

**Comment by nickgros** [comment]
@sanjeev16011994 please open a new issue if the provided solution does not work. Thanks!
