### ISSUE TITLE
Cannot Submit Form // @rjsf/antd

### ISSUE THREAD

**Issue by sarpere** [rjsf-team/react-jsonschema-form#2867]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

antd

### Version

4.2.0

### Current Behavior

When I click submit button,I cannot reach with any response. 
I used default example page

[Example page](https://rjsf-team.github.io/react-jsonschema-form/)
![Screen Shot 2022-05-23 at 12 27 00](https://user-images.githubusercontent.com/29937197/169788645-70db4e75-1385-4901-8170-79bd89345172.png)
 

### Expected Behavior

When I click submit button, Form need to be triggered. 

### Steps To Reproduce

1. Set selected theme to antd
2. click submit 
3. Check  logs on console. (nothing appear)

**Comment by sarpere** [comment]
I have created PR for the issue.

**Comment by andres314** [comment]
Is this fixed? I trying it in a local project with"@rjsf/antd": "^4.2.0" and "@rjsf/core": "^4.2.0" the submit is not working, if use the <Form /> from core the submit works properly.

**Comment by sarpere** [comment]
Hi @andres314,
You need to upgrade your package to 4.2.1 or higher. It fixed on version 4.2.1.
