### ISSUE TITLE
Submit button ignores custom CSS classes passed via ui:submitButtonOptions

### ISSUE THREAD

**Issue by ewaldbenes** [rjsf-team/react-jsonschema-form#2868]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

4.2.0

### Current Behavior

I want to customize the appearance of the submit button via passing custom CSS classes. I took the example from the [docs](https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/uiSchema/#submitbuttonoptions) to accomplish that.

```
"ui:submitButtonOptions": {
   "props": {
      "disabled": false,
      "className": "my-custom-class",
   },
    "norender": false,
    "submitText": "Submit"
  }
}
```

`my-custom-class` is never injected into the DOM.

I figured out that this line of code in file `packages/core/src/components/widgets/SubmitButton.js`

```
...
<button type="submit" {...submitButtonProps} className="btn btn-info">
...
```
causes the `className` property content always to be overwritten with `btn btn-info` which renders this property useless.

Am I right with my conclusion? If yes, should I provide a PR or how should we proceed on this?

### Expected Behavior

Custom provided CSS classes should override all default or existing classes.

### Steps To Reproduce

Happens always if schema contains customization for the submit button as described above.

### Environment

```markdown
- OS: Ubuntu 20.04
- Node: v16.15.0
- npm: 8.5.5
```

**Comment by heath-freenome** [comment]
@ewaldbenes You are correct in your assessment. I encourage you to create a PR against the upcoming v5 release (in the `rjsf-v5` branch). Ping me on the [discord server]( https://discord.gg/fdZm2JZJrX) if you need help

**Comment by heath-freenome** [comment]
This has been fixed in the v5 beta, see the [5.x migration guide](https://react-jsonschema-form.readthedocs.io/en/latest/5.x%20upgrade%20guide/)
