### ISSUE TITLE
Default values for array type:

### ISSUE THREAD

**Issue by adneforslund** [rjsf-team/react-jsonschema-form#2870]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

material-ui

### What is your question?

Hello, Im wondering if it is possible to initialize an array as something *not* null or undefined, but rather have formData start out as an empty array? 

What I imagined would work: 
```
const Schema = {
     tags: {
      title: "Tags",
      type: "array",
      items: {
        type: "string",
      },
     } 
    };
    
    
    const UiSchema = { 
    tags: {
    "ui:field": "SomeField",
    "ui:emptyValue": []
    
        },
    }:
```

**Comment by heath-freenome** [comment]
So it looks like you have discovered that the `ui:emptyValue` does not work for an array type as indicated by this [example playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0YWdzIjp7InRpdGxlIjoiVGFncyIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmcifX19fSwidWlTY2hlbWEiOnsidGFncyI6eyJ1aTplbXB0eVZhbHVlIjpbXX19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsInZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19). And neither does setting an [empty default](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0YWdzIjp7InRpdGxlIjoiVGFncyIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmcifSwiZGVmYXVsdCI6W119fX0sInVpU2NoZW1hIjp7InRhZ3MiOnt9fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==).
