### ISSUE TITLE
ErrorSchema is a none deterministic type thus can't be used to accurately type Field components 

### ISSUE THREAD

**Issue by Steffan-Ennis** [rjsf-team/react-jsonschema-form#2871]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

4.1.1

### Current Behavior

The type ErrorSchema is non deterministic

```
import { ErrorSchema } from '@rjsf/core'

const errorSchema: ErrorSchema = {
  __errors: [
    'This field is required'
  ]
}
```

raises the following compile error
`Type 'string' is not assignable to type 'ErrorSchema' `

### Expected Behavior

The ErrorSchema type should be deterministic so it's usable when typing field components and testing those types

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by heath-freenome** [comment]
Fixed in the v5 beta, see the [5.x migration guide](https://react-jsonschema-form.readthedocs.io/en/latest/5.x%20upgrade%20guide/)
