### ISSUE TITLE
Use RJSF to create maps?

### ISSUE THREAD

**Issue by JohnRosner** [rjsf-team/react-jsonschema-form#2883]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### What is your question?

Hello, 

I have a use case where I need to create a form for a user where the JSON includes a map from a string to an object.
Here is my schema as I have it right now: 

```
{
  "$schema": "http://json-schema.org/draft/2020-12/schema",
  "$defs": {
    "data": {
      "properties": {
        "prop1": {
          "type": "integer",
          "description": "The first property"
        },
        "prop2": {
          "type": "string",
          "description": "A second property"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "prop1"
      ]
    }
  },
  "patternProperties": {
    ".*": {
      "$ref": "#/$defs/data"
    }
  },
  "type": "object"
}
```

An example of the JSON data I need back from the user:

```
{
  "user_modifiable_name": {
    "prop1": 3,
    "prop2": "example"
  },
  "another_modifiable_name": {
    "prop1": 5,
    "prop2": "example2"
  }
}
```

When I give the schema as is to the library or in the playground, it doesn't render anything. Does RJSF support this type of JSON pattern and if so how might I accomplish it?

**Comment by nickgros** [comment]
@JohnRosner I think you just need to add the following to your schema:

```json
  "additionalProperties": {
     "$ref": "#/$defs/data"
  }
```

[See this playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJuZXdLZXkiOnt9fSwic2NoZW1hIjp7IiRzY2hlbWEiOiJodHRwOi8vanNvbi1zY2hlbWEub3JnL2RyYWZ0LzIwMjAtMTIvc2NoZW1hIiwiJGRlZnMiOnsiZGF0YSI6eyJwcm9wZXJ0aWVzIjp7InByb3AxIjp7InR5cGUiOiJpbnRlZ2VyIiwiZGVzY3JpcHRpb24iOiJUaGUgZmlyc3QgcHJvcGVydHkifSwicHJvcDIiOnsidHlwZSI6InN0cmluZyIsImRlc2NyaXB0aW9uIjoiQSBzZWNvbmQgcHJvcGVydHkifX0sImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjpmYWxzZSwidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbInByb3AxIl19fSwicGF0dGVyblByb3BlcnRpZXMiOnsiKiI6eyIkcmVmIjoiIy8kZGVmcy9kYXRhIn19LCJ0eXBlIjoib2JqZWN0IiwiYWRkaXRpb25hbFByb3BlcnRpZXMiOnsiJHJlZiI6IiMvJGRlZnMvZGF0YSJ9fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiIsInVpOmF1dG9jb21wbGV0ZSI6ImZhbWlseS1uYW1lIn0sImxhc3ROYW1lIjp7InVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJnaXZlbi1uYW1lIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=). Please re-open or create a new ticket if this doesn't solve your issue.
