### ISSUE TITLE
Styling does not work.

### ISSUE THREAD

**Issue by Anushka-shukla** [rjsf-team/react-jsonschema-form#2888]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

bootstrap-4, material-ui

### What is your question?

With Bootstrap4 I get below error. I have installed the library and imported the same as given in the doc. Even added CDN URL in "public/index.html".
![Screenshot (44)](https://user-images.githubusercontent.com/47845585/174790466-e1ef9102-1c3d-4a73-aebe-9d8ea34adfbe.png)

I tried MUI as well. But nothing worked.
https://github.com/rjsf-team/react-jsonschema-form/discussions/2881#discussion-4142483

**Comment by heath-freenome** [comment]
Can you provide an example how you are using the `Form`? Do you have a codesandbox.io for the example to look at?
