### ISSUE TITLE
Date & DateTime widgets do not respect falsy/null/non-date `ui:emptyValue`

### ISSUE THREAD

**Issue by thgreasi** [rjsf-team/react-jsonschema-form#2889]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

4.1.1

### Current Behavior

For Date & DateTime fields of type `"type": ["string", "null"]`, that do have `"ui:emptyValue": null` configured, clearing the input results the property to be completely removed from the result object.

### Expected Behavior

For Date & DateTime fields of type `"type": ["string", "null"]`, configured with `"ui:emptyValue": null` in their UISchema, should set a `null` value in the result object, consistently with how string & number fields behave.

### Steps To Reproduce

1. go to to [this shared playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0ZXh0IjpudWxsLCJudW1iZXIiOm51bGx9LCJzY2hlbWEiOnsidGl0bGUiOiJEYXRlIGFuZCB0aW1lIHdpZGdldHMgd2l0aCBudWxsIHVpOmVtcHR5VmFsdWUiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0ZXh0Ijp7InRpdGxlIjoiTnVsbGFibGUgdGV4dCBwcm9wZXJ0eSB1c2VzIHRoZSBudWxsIHByb3ZpZGVkIGVtcHR5VmFsdWUiLCJ0eXBlIjpbInN0cmluZyIsIm51bGwiXX0sIm51bWJlciI6eyJ0aXRsZSI6Ik51bGxhYmxlIG51bWVyaWMgcHJvcGVydHkgdXNlcyB0aGUgbnVsbCBwcm92aWRlZCBlbXB0eVZhbHVlIiwidHlwZSI6WyJudW1iZXIiLCJudWxsIl19LCJkYXRldGltZSI6eyJ0aXRsZSI6Ik51bGxhYmxlIGRhdGV0LXRpbWUgaW5wdXQgZG9lcyBub3QgdXNlIHRoZSBudWxsIHByb3ZpZGVkIGVtcHR5VmFsdWUgJiByZW1vdmVzIHRoZSBwcm9wZXJ0eSBvbiBjbGVhciBpbnN0ZWFkICE/IT8iLCJ0eXBlIjpbInN0cmluZyIsIm51bGwiXSwiZm9ybWF0IjoiZGF0ZS10aW1lIn0sImRhdGUiOnsidGl0bGUiOiJOdWxsYWJsZSBkYXRldCBpbnB1dCBkb2VzIG5vdCB1c2UgdGhlIG51bGwgcHJvdmlkZWQgZW1wdHlWYWx1ZSAmIHJlbW92ZXMgdGhlIHByb3BlcnR5IG9uIGNsZWFyIGluc3RlYWQgIT8hPyIsInR5cGUiOlsic3RyaW5nIiwibnVsbCJdLCJmb3JtYXQiOiJkYXRlIn19fSwidWlTY2hlbWEiOnsidGV4dCI6eyJ1aTplbXB0eVZhbHVlIjpudWxsfSwibnVtYmVyIjp7InVpOmVtcHR5VmFsdWUiOm51bGx9LCJkYXRldGltZSI6eyJ1aTplbXB0eVZhbHVlIjpudWxsfSwiZGF0ZSI6eyJ1aTplbXB0eVZhbHVlIjpudWxsfX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==).
2. set a value to the text, number, date & datetime fields and clear them afterwards.
3. while for the  text & numeric fields the result object will have a property with `null` as a value, the form will not include at all properties for the date & datetime fields.

### Environment

```markdown
- OS: Ubuntu 20.04
- Node: 16.15.1
- npm: 8.12.2
```

**Comment by heath-freenome** [comment]
Fixed in the v5 beta, see the [5.x migration guide](https://react-jsonschema-form.readthedocs.io/en/latest/5.x%20upgrade%20guide/)
