### ISSUE TITLE
RJSF‘s own schema

### ISSUE THREAD

**Issue by chris-schra** [rjsf-team/react-jsonschema-form#2896]
### Discussed in https://github.com/rjsf-team/react-jsonschema-form/discussions/2894
<sup>Originally posted by **chris-schra** June 24, 2022</sup>
This might be a stupid question but googling „react-json-schema-form json schema“ will obviously return a lot of results 😃

I‘m looking for rjsf‘s own JSON schema (the one including „ui:widget“ property definition, for example) to be able to extend it (eg adding „data:index“) and validate it

help is really appreciated and in case it doesn‘t exist yet, I could add it. Maybe it makes sense to even include it in the repo so UIs can download it</div>

Update:
Converting it to an issue because it's really something I either have missed or that should be discussed. 
Another example: is there a registry for "scoped" props like "ui:widget"? Because I think it would make sense to add "ui:labels" to define which props should be used to generate a label for items (consumer-side, eg if you want to group an array of objects and want to show a "group name"). I understand this might not be specifically related to RJSF but rather to JSON Schema, but maybe someone could advise?

**Comment by heath-freenome** [comment]
There are decent typescript definitions in the `@rjsf/core/index.d.ts` file. NOTE: In the upcoming v5 version (see `rjsf-v5` branch), the types have all been moved to the new `@rjsf/utils` directory and improved significantly
