### ISSUE TITLE
useMuiComponent from example fails

### ISSUE THREAD

**Issue by joseika** [rjsf-team/react-jsonschema-form#2905]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

material-ui

### Version

4.2.0

### Current Behavior

I implemented a custom field based on the documentation example: https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/material-ui/customizing-material-ui/#example-of-a-custom-field-for-rjsfmaterial-ui

Error:
export 'useMuiComponent' (imported as 'useMuiComponent') was not found in '@rjsf/material-ui/v4' (possible exports: ArrayFieldTemplate, FieldTemplate, Fields, MuiComponentContext, MuiForm, ObjectFieldTemplate, Theme, Widgets, default)

Is the export missing, or is the documentation outdated?

### Expected Behavior

Examples in documentation should work.

### Steps To Reproduce

1. Set up a Create React App project
2. Install  @rjsf/core@4.2.0, rjsf/material-ui@4.2.0
3. Add code from example
4. Build fails

### Environment

```markdown
- OS: Ubuntu 20.04
- Node: 16.14.0
- npm: 8.3.1
```

**Comment by heath-freenome** [comment]
Whoops, the export is missing. You can also do `React.useContext(MuiComponentContext)` as a work around

**Comment by heath-freenome** [comment]
Fixed in v5 beta by removing the whole hooks implementation: https://react-jsonschema-form.readthedocs.io/en/latest/5.x%20upgrade%20guide/
