### ISSUE TITLE
getWidget throws "Unsupported widget definition: undefined" when widget param is a string

### ISSUE THREAD

**Issue by skysantoroa** [rjsf-team/react-jsonschema-form#2907]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

4.1.1

### Current Behavior

Create a custom widget like

```
DateWidget: (props: WidgetProps) => {
    const { value, label, onChange, required, readonly, disabled, options, schema } =
      props
    const widget = utils.getWidget(schema, 'date')
    return (
      <>{widget}</>
    )
  },
```

Even though the `widget` parameter passed to the `getWidget` function is a string, it will fail throwing "Unsupported widget definition: undefined".

### Expected Behavior

Getting the proper Widget given the schema and its key

### Steps To Reproduce

Read current behaviour

### Environment

```markdown
- OS: Ubuntu 22
- Node: 16
- npm: 8
```

**Comment by heath-freenome** [comment]
Have you added the new widget to the `widgets` prop of the `Form`?

**Comment by skysantoroa** [comment]
There is no new widget, I'm just trying to get the default DateWidget here

**Comment by heath-freenome** [comment]
Which theme?

**Comment by skysantoroa** [comment]
`Bootstrap 3 (default)`

**Comment by heath-freenome** [comment]
using    `const widget = utils.getWidget(schema, 'date')` will cause this problem if the `utils.getSchemaType(schema)` returns something other than string
