### ISSUE TITLE
Empty object next to a checkbox is still inserted

### ISSUE THREAD

**Issue by GiladFeder** [rjsf-team/react-jsonschema-form#2921]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

4.1.1

### Current Behavior

when simply checking the checkbox, it adds a the sibling's empty object as well

formData:

```
{
  "a": {
    "b": true,
    "c": {}
  }
}

```

### Expected Behavior

formData:

formData:

```
{
  "a": {
    "b": true
  }
}

```

### Steps To Reproduce

Would've loved to include a codepen but I see them as all broken at the moment, so you can paste this jsonschema in the [playground](https://rjsf-team.github.io/react-jsonschema-form/) :

JSONSCHEMA: 

```
{
        "type": "object",
        "properties": {
            "a": {
                "type": "object",
                "properties": {
                    "b": {
                        "type": "boolean"
                    },
                    "c": {
                        "type": "object",
                        "properties": {
                            "d": {
                              "type": "string"
                            }
                        }
                    }
                }
            }
        }
    }

```

**Comment by heath-freenome** [comment]
As you can see in the latest [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhIjp7ImIiOmZhbHNlfX0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJhIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImIiOnsidHlwZSI6ImJvb2xlYW4ifSwiYyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJkIjp7InR5cGUiOiJzdHJpbmcifX19fX19fSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsInZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19) built with 5.0.0.beta.14 this now appears to be fixed
