### ISSUE TITLE
number/integer upDown widget not working properly

### ISSUE THREAD

**Issue by ElfeBc** [rjsf-team/react-jsonschema-form#2926]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

material-ui

### Version

4.2.0

### Current Behavior

I've faced this in my code, but in the playground I saw that exist the same issue. When type is number or integer and instead of a number it contains a string, the value is removed from formData and when clicks on save there is no error.

### Expected Behavior

If number/integer type field contains  something that is not a number/integer, an error should be shown and data should not be removed.

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by ElfeBc** [comment]
I've continued investigating and for example in playground, if I remove from the ui schema to use the widget upDown for an integer it is velidated correctly, so seems that the issue comes from the upDown widget, not only for material ui, for all the the themes. Other thing is why it is needed to specify  the updown widget for integer instead of having it by default like for numbers?

**Comment by heath-freenome** [comment]
Fixed in the v5 beta, see the [5.x migration guide](https://react-jsonschema-form.readthedocs.io/en/latest/5.x%20upgrade%20guide/)
