### ISSUE TITLE
NEW: RJSF version 5 beta released

### ISSUE THREAD

**Issue by heath-freenome** [rjsf-team/react-jsonschema-form#2956]
Here is the [5.x migration guide](https://react-jsonschema-form.readthedocs.io/en/latest/5.x%20upgrade%20guide/)

Any and all feedback/issues are appreciated

**Comment by AntonPuko** [comment]
Hi, is there any time estimation when the new major will be released at least with alpha flag? Thnx!

**Comment by heath-freenome** [comment]
No promises, but best guess is alpha in early August

**Comment by benjdlambert** [comment]
@heath-freenome sounds great, is mid-august still a reasonable possibility for v5?

**Comment by heath-freenome** [comment]
> @heath-freenome sounds great, is mid-august still a reasonable possibility for v5?

I'm shooting for releasing `5.0.0-beta.1` before the end of the month.

**Comment by benjdlambert** [comment]
@heath-freenome awesome - sounds great! Thanks!

**Comment by kikonejacob** [comment]
congratulation on the release.
I'm getting the following error when installing 5.0.0-beta.2: 
 Module not found: Can't resolve '@rjsf/core/dist/components/fields/ArrayField'
 Apparently, the typescript types are generated but no js files
 
<img width="283" alt="image" src="https://user-images.githubusercontent.com/3852574/187320187-f0e8da66-7c60-4fe4-887a-ad9d3a7e5e26.png">

**Comment by heath-freenome** [comment]
Can you give me an expanded context on where you are seeing this error? All of the source code was rolled up into the base directory... The `*.d.ts` files weren't rolled up, but I'm leaning towards doing that as well in the beta.3 release

<img width="233" alt="Screen Shot 2022-08-29 at 10 26 33 PM" src="https://user-images.githubusercontent.com/51679588/187356568-f6792a1b-3a4f-4dec-aa22-e9129227c563.png">

**Comment by heath-freenome** [comment]
What are you hoping to do by importing `ArrayField`? Are you trying to override it or something?

**Comment by kikonejacob** [comment]
> What are you hoping to do by importing `ArrayField`? Are you trying to override it or something?

Yes. I have a use case where I override ArrayField when needed and just mount ArrayField when not needed. 
I think the component folder needs to be exposed. 
UISchema is great but there are use cases where we may need more control.

**Comment by heath-freenome** [comment]
> Yes. I have a use case where I override ArrayField when needed and just mount ArrayField when not needed. I think the component folder needs to be exposed. UISchema is great but there are use cases where we may need more control.

Can you explain your use case? Several more components of `ArrayField` were exposed in the v5 beta as templates. Maybe your use case has been simplified by those changes?

**Comment by kikonejacob** [comment]
> > Yes. I have a use case where I override ArrayField when needed and just mount ArrayField when not needed. I think the component folder needs to be exposed. UISchema is great but there are use cases where we may need more control.
> 
> Can you explain your use case? Several more components of `ArrayField` were exposed in the v5 beta as templates. Maybe your use case has been simplified by those changes?

So I have some properties that are of type array but I want to render/edit them in a text editor (monaco-editor) component.  This requires giving full control of the array editing to the component that renders the Monaco editor.
It seems to me that the ArrayField has some abstractions that are not needed in this case and can create problems.  The array field assumes that each item will be rendered in a list but in this case, the text editor will just handle it differently.
The only thing that the editor needs pass the get an array, and pass the array back.
For this use case, I have to override ArrayField when the array property requires a text editor and use ArrayField with it is needed.

Is there a way to override ArrayField and still be able to access the original ArrayField without an `import`?
Same question for templates?

**Comment by heath-freenome** [comment]
You could try calling `getDefaultRegistry()` and access `fields.ArrayField`

**Comment by heath-freenome** [comment]
@kikonejacob In 5.0.0-beta.7 we added a new field called `ArraySchemaField` (defaulting to `SchemaField`) which lets you override the way an array item `children` is rendered. This is the `children` prop passed to the `ArrayFieldItemTemplate`. Now in your specific use case you can override just that `ArraySchemaField` to modify the name before passing it down to the `SchemaField` in a manner similar to how you would have accessed the `ArrayField` itself. Hopefully that simplifies your use case alot

**Comment by kikonejacob** [comment]
> @kikonejacob In 5.0.0-beta.7 we added a new field called `ArraySchemaField` (defaulting to `SchemaField`) which lets you override the way an array item `children` is rendered. This is the `children` prop passed to the `ArrayFieldItemTemplate`. Now in your specific use case you can override just that `ArraySchemaField` to modify the name before passing it down to the `SchemaField` in a manner similar to how you would have accessed the `ArrayField` itself. Hopefully that simplifies your use case alot

Thanks. I. will try it out
