### ISSUE TITLE
Production Builds with Vite and AntD theme not running correctly

### ISSUE THREAD

**Issue by karl-d** [rjsf-team/react-jsonschema-form#2962]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

antd

### Version

4.2.2

### Current Behavior

We are upgrading a project from Webpack to Vite. Currently in development this all works and loads correctly but we have encountered an error with the production build. 

After building a production bundle using Vite & AntD theme, there is a console error `Uncaught TypeError: generatePickerExports is not a function.`

<img width="457" alt="image" src="https://user-images.githubusercontent.com/11346844/181173947-76a2c3eb-9b96-42a6-a431-f1a70753d6e2.png">

<img width="868" alt="image" src="https://user-images.githubusercontent.com/11346844/181173919-1705c766-3bfc-4d32-b631-86d4a1b9394c.png">

### Expected Behavior

Expect the page to load correctly after a production build

### Steps To Reproduce

1. Use a base Vite project `npm create vite@latest . --template react-ts`
2. `npm install @rjsf/core@^4.2.2 @rjsf/antd@^4.2.2 `
3. Create base page with form
4. Run `npm run dev` and page loads fine
5. Run `npm build`, which runs successfully
6. Load browser and see error in the console

### Environment

```markdown
- OS: MacOS 12.3
- Node: v16.16.0
- npm: 8.14.0
- vite: 3.0.0
- typescript: 4.6.4
- react: 18.2.0
- antd: 4.22.1
```

### Anything else?

This looks like it may be cause in the import to override moment.js with day.js in this file
https://github.com/rjsf-team/react-jsonschema-form/blob/4049011ea59737232a86c193d96131ce61be85fa/packages/antd/src/components/DatePicker/index.js

**Comment by heath-freenome** [comment]
@karl-d what version of antd do you have installed?

**Comment by karl-d** [comment]
@heath-freenome v4.22.1

**Comment by heath-freenome** [comment]
Hmmm, the tests for the theme are using a much earlier version. I'll see whether things work with that version locally

**Comment by heath-freenome** [comment]
So, things work for me with the latest, but we use webpack, not Vite. I wonder if Vite is preventing the import that drills directly into the `antd/lib/date-picker/generatePicker` and `rc-picker/lib/generate/dayjs` from actually working. Is there a configuration property for Vite that might allow this?

**Comment by wangxinyu666666** [comment]
I have the same problem. Do you solve it?

**Comment by karl-d** [comment]
@heath-freenome I have not been able to find any configuration that helps resolve the issue.
I have created a base repo here that I am able to replicate the issue.
https://github.com/karl-d/react-json-schema-antd-vite/tree/main

**Comment by heath-freenome** [comment]
@ezze Are you willing to make a PR against the `rjsf-v5` branch with the changes you recommend to `DatePicker`?

**Comment by ezze** [comment]
Thanks for response. At the moment, we're using `rjsf-v4` so that's where we want to see these changes first.

**Comment by heath-freenome** [comment]
There currently isn't a plan to update v4 anymore as v5 beta is going to take over the master branch this weekend.

**Comment by ezze** [comment]
Not good news for us. Probably, we will live with patched v4 for a while. Not sure how many breaking changes will be introduced in v5 and whether they affect us seriously.
Anyway, I am pretty sure that v5 must be ESM compatible to fix the issue.

**Comment by aprilis** [comment]
For me it worked to add this alias to `vite.config.js`:
```
resolve: {
    alias: [
      {
        find: "antd/lib",
        replacement: "antd/es",
      }
    ],
  },
```

**Comment by heath-freenome** [comment]
Since there is a vite config work-around, is it ok to close this issue? I just tried making the suggested change in the v5 beta and jest fails badly while trying to run tests and I do not have the bandwidth to figure it out:
```
 Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/heath/dev/react-jsonschema-form/packages/antd/node_modules/rc-picker/es/generate/dayjs.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import dayjs from 'dayjs';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import dayjsGenerateConfig from "rc-picker/es/generate/dayjs";
        | ^
      2 | import generatePicker from "antd/es/date-picker/generatePicker";
      3 |
      4 | const DatePicker = generatePicker(dayjsGenerateConfig);

      at Runtime.createScriptFromCode (node_modules/dts-cli/node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/components/DatePicker/index.js:1:1)
```

**Comment by heath-freenome** [comment]
Fixed in v5 beta via https://github.com/rjsf-team/react-jsonschema-form/pull/3044
