### ISSUE TITLE
"anyOf" with "dependencies" breaks with a "Unsupported field schema for field {fieldname}: Unknown field type undefined"

### ISSUE THREAD

**Issue by joncarlson** [rjsf-team/react-jsonschema-form#2964]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

4.1.1

### Current Behavior

Can't use anyOf along with dependencies. For the playground example (my actual use case is much more complex):

* On page load, the section of the form using anyOf + dependencies fails to load and shows the Unsupported field schema for field error.
* Removing the "dependencies" section makes the form render correctly.

Here's the simple schema for reproduction of the issue:

```
{
  "title": "anyof with dependencies issue",
  "type": "object",
  "properties": {
    "Contact": {
      "type": "object",
      "properties": {
        "FullName": {
          "type": "string"
        },
        "FirstName": {
          "type": "string"
        },
        "LastName": {
          "type": "string"
        },
        "CreditCard": {
          "type": "number"
        },
        "BillingAddress": {
          "type": "string"
        }
      },
      "anyOf": [
        {
          "required": [
            "FullName"
          ]
        },
        {
          "required": [
            "FirstName",
            "LastName"
          ]
        }
      ],
      "dependencies": {
        "CreditCard": [
          "BillingAddress"
        ]
      }
    }
  }
}
```

### Expected Behavior

Form correctly renders and validates the following:

* User has to enter the name, this can be a full name AND/OR a first name + last Name.
* If user enters a credit card number, they have to enter a billing address.

### Steps To Reproduce

1. See the playground example link, no steps are needed to reproduce, it fails to render the form immediately.

### Environment

```markdown
- N/A, using the playground
```

### Anything else?

https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCJ9LCJzY2hlbWEiOnsidGl0bGUiOiJQcm9wZXJ0eSBkZXBlbmRlbmNpZXMiLCJkZXNjcmlwdGlvbiI6IlRoZXNlIHNhbXBsZXMgYXJlIGJlc3Qgdmlld2VkIHdpdGhvdXQgbGl2ZSB2YWxpZGF0aW9uLiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InVuaWRpcmVjdGlvbmFsIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7IkZ1bGxOYW1lIjp7InR5cGUiOiJzdHJpbmcifSwiRmlyc3ROYW1lIjp7InR5cGUiOiJzdHJpbmcifSwiTGFzdE5hbWUiOnsidHlwZSI6InN0cmluZyJ9LCJDcmVkaXRDYXJkIjp7InR5cGUiOiJudW1iZXIifSwiQmlsbGluZ0FkZHJlc3MiOnsidHlwZSI6InN0cmluZyJ9fSwiYW55T2YiOlt7InJlcXVpcmVkIjpbIkZ1bGxOYW1lIl19LHsicmVxdWlyZWQiOlsiRmlyc3ROYW1lIiwiTGFzdE5hbWUiXX1dLCJkZXBlbmRlbmNpZXMiOnsiQ3JlZGl0Q2FyZCI6WyJCaWxsaW5nQWRkcmVzcyJdfX19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiIsInVpOmF1dG9jb21wbGV0ZSI6ImZhbWlseS1uYW1lIn0sImxhc3ROYW1lIjp7InVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJnaXZlbi1uYW1lIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==

**Comment by heath-freenome** [comment]
Yikes, this is a nasty bug. Not sure how to fix it at the moment. You are welcome to take a stab at updating the way we deal with dependencies and any-of. Sorry this is causing you an issue
