### ISSUE TITLE
Add react 18 to peer dependencies

### ISSUE THREAD

**Issue by ahkhanjani** [rjsf-team/react-jsonschema-form#2976]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

material-ui

### Is your feature request related to a problem? Please describe.

.
└─┬ @rjsf/material-ui
  ├── ✕ unmet peer @types/react@"^16.8.6 || ^17.0.0": found 18.0.15
  ├── ✕ unmet peer react@"^16.8.0 || ^17.0.0": found 18.2.0
  └── ✕ unmet peer react-dom@"^16.8.0 || ^17.0.0": found 18.2.0

can get annoying

**Comment by heath-freenome** [comment]
The upcoming v5 beta will be extending the Peer dependencies. NOTE, that RJSF is still using deprecated features of React 17 and may not work properly with React 18.

**Comment by ahkhanjani** [comment]
What is preventing us from fully committing to react 18?

**Comment by heath-freenome** [comment]
Pretty much developer time to do the work necessary, including all the overhead of doing a beta. Right now, I'm actively working on other breaking fixes, but I do not have the bandwidth to also tackle React 18... At least until the fall/winter of 2022

**Comment by ahkhanjani** [comment]
I see. I do not know rjsf's contribution policies but I'm willing to help with react 18 migration if possible.

**Comment by heath-freenome** [comment]
@ahkhanjani Any assistance is welcome. You can find our contribution policies [here](https://react-jsonschema-form.readthedocs.io/en/latest/contributing/)
