### ISSUE TITLE
Default value of field dependent on drop down not being updated

### ISSUE THREAD

**Issue by IanTurtle** [rjsf-team/react-jsonschema-form#2978]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

Playground

### Current Behavior

In a form with two fields, where one is a dropdown of different options and a second is dependent on the other. The second field changes values depending on the option second. If you then select a different option from the dropdown menu, the value of the second field does not change to the different value.

### Expected Behavior

In a form with two fields, where one is a dropdown of different options and a second is dependent on the other. The second field changes values depending on the option second. If you then select a different option from the dropdown menu, the value of the second field would change to the different value.

### Steps To Reproduce

In the React JSON Schema playground, create a form using the following payload
```
{
    "title": "Optional Components",
    "required": [
      "component"
    ],
    "properties": {
      "component": {
        "title": "Component",
        "type": "object",
        "properties": {
          "component": {
            "title": "Component",
            "type": "string",
            "enum": [
              "value1",
              "value2"
            ]
          }
        },
        "required": [
          "component"
        ],
        "dependencies": {
          "component": {
            "oneOf": [
              {
                "properties": {
                  "component": {
                    "enum": [
                      "value1"
                    ]
                  },
                  "template": {
                    "type": "string",
                    "default": "abc"
                  }
                }
              },
              {
                "properties": {
                  "component": {
                    "enum": [
                      "value2"
                    ]
                  },
                  "template": {
                    "type": "string",
                    "default": "def"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
  ```
Select value1 from the Component menu and notice the value of the template field is abc
![image](https://user-images.githubusercontent.com/13857557/182144335-80a7f609-8672-4069-8919-67f4267886b4.png)

Then select value2 from the Component menu and notice the value of the template field is abc (and not the expected def)
![image](https://user-images.githubusercontent.com/13857557/182144593-68014c13-1df5-4984-87e9-1bb91012f730.png)

### Environment

```markdown
Playground
```

### Anything else?

[Playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJjb21wb25lbnQiOnsidGVtcGxhdGUiOiJhYmMiLCJjb21wb25lbnQiOiJ2YWx1ZTEifSwiZmlyc3ROYW1lIjoiQ2h1Y2siLCJsYXN0TmFtZSI6Ik5vcnJpcyIsImFnZSI6NzUsImJpbyI6IlJvdW5kaG91c2Uga2lja2luZyBhc3NlcyBzaW5jZSAxOTQwIiwicGFzc3dvcmQiOiJub25lZWQifSwic2NoZW1hIjp7InRpdGxlIjoiT3B0aW9uYWwgQ29tcG9uZW50cyIsInJlcXVpcmVkIjpbImNvbXBvbmVudCJdLCJwcm9wZXJ0aWVzIjp7ImNvbXBvbmVudCI6eyJ0aXRsZSI6IkNvbXBvbmVudCIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImNvbXBvbmVudCI6eyJ0aXRsZSI6IkNvbXBvbmVudCIsInR5cGUiOiJzdHJpbmciLCJlbnVtIjpbInZhbHVlMSIsInZhbHVlMiJdfX0sInJlcXVpcmVkIjpbImNvbXBvbmVudCJdLCJkZXBlbmRlbmNpZXMiOnsiY29tcG9uZW50Ijp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7ImNvbXBvbmVudCI6eyJlbnVtIjpbInZhbHVlMSJdfSwidGVtcGxhdGUiOnsidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJhYmMifX19LHsicHJvcGVydGllcyI6eyJjb21wb25lbnQiOnsiZW51bSI6WyJ2YWx1ZTIiXX0sInRlbXBsYXRlIjp7InR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoiZGVmIn19fV19fX19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiIsInVpOmF1dG9jb21wbGV0ZSI6ImZhbWlseS1uYW1lIn0sImxhc3ROYW1lIjp7InVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJnaXZlbi1uYW1lIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==) link here

**Comment by lucaswiman** [comment]
I'm running into similar issues. I _think_ the cause is here: https://github.com/rjsf-team/react-jsonschema-form/blob/b63ec99ad1cd2eb3f9ed98f44e5221163b563fc4/packages/utils/src/schema/getDefaultFormState.ts#L106-L141

When computing the defaults, once one set of defaults is determined, it only recurses down to non-dependent properties.

**Comment by lucaswiman** [comment]
Looking into this a bit more, it's less clear to me that this is a bug. FormData would need to record the source of every field (set from a default or entered data). Slightly altering the example playground with `"enum": ["abc"]` or `"const": "abc"` yields the desired behavior (see [playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJjb21wb25lbnQiOnsidGVtcGxhdGUiOiJhYmMiLCJjb21wb25lbnQiOiJ2YWx1ZTIifSwiZmlyc3ROYW1lIjoiQ2h1Y2siLCJsYXN0TmFtZSI6Ik5vcnJpcyIsImFnZSI6NzUsImJpbyI6IlJvdW5kaG91c2Uga2lja2luZyBhc3NlcyBzaW5jZSAxOTQwIiwicGFzc3dvcmQiOiJub25lZWQifSwic2NoZW1hIjp7InRpdGxlIjoiT3B0aW9uYWwgQ29tcG9uZW50cyIsInJlcXVpcmVkIjpbImNvbXBvbmVudCJdLCJwcm9wZXJ0aWVzIjp7ImNvbXBvbmVudCI6eyJ0aXRsZSI6IkNvbXBvbmVudCIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImNvbXBvbmVudCI6eyJ0aXRsZSI6IkNvbXBvbmVudCIsInR5cGUiOiJzdHJpbmciLCJlbnVtIjpbInZhbHVlMSIsInZhbHVlMiJdfX0sInJlcXVpcmVkIjpbImNvbXBvbmVudCJdLCJkZXBlbmRlbmNpZXMiOnsiY29tcG9uZW50Ijp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7ImNvbXBvbmVudCI6eyJlbnVtIjpbInZhbHVlMSJdfSwidGVtcGxhdGUiOnsidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJhYmMiLCJlbnVtIjpbImFiYyJdfX19LHsicHJvcGVydGllcyI6eyJjb21wb25lbnQiOnsiZW51bSI6WyJ2YWx1ZTIiXX0sInRlbXBsYXRlIjp7InR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoiZGVmIiwiZW51bSI6WyJkZWYiXX19fV19fX19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiIsInVpOmF1dG9jb21wbGV0ZSI6ImZhbWlseS1uYW1lIn0sImxhc3ROYW1lIjp7InVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJnaXZlbi1uYW1lIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)).

**Comment by lucaswiman** [comment]
The example I've been looking at is [here](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJub2RlX3R5cGUiOiJBdHRyaWJ1dGVOb2RlIn0sInNjaGVtYSI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9yb290IiwiZGVmaW5pdGlvbnMiOnsiU3RyaW5nUHJlZGljYXRlIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InBhdHRlcm4iOnsidHlwZSI6InN0cmluZyJ9LCJub2RlX3R5cGUiOnsiZGVmYXVsdCI6IlN0cmluZ1ByZWRpY2F0ZSIsImVudW0iOlsiU3RyaW5nUHJlZGljYXRlIl0sInR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbInBhdHRlcm4iLCJub2RlX3R5cGUiXX0sIkF0dHJpYnV0ZU5vZGUiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiYXR0ciI6eyJlbnVtIjpbImZvbyJdLCJ0eXBlIjoic3RyaW5nIn0sIm5vZGVfdHlwZSI6eyJkZWZhdWx0IjoiQXR0cmlidXRlTm9kZSIsImVudW0iOlsiQXR0cmlidXRlTm9kZSJdLCJ0eXBlIjoic3RyaW5nIn19LCJkZXBlbmRlbmNpZXMiOnsiYXR0ciI6eyJwcm9wZXJ0aWVzIjp7ImF0dHIiOnsiY29uc3QiOiJmb28ifSwiY2hpbGQiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvYXR0cl9mb28ifX19fX0sInJvb3QiOnsidHlwZSI6Im9iamVjdCIsImRlZmF1bHQiOnsibm9kZV90eXBlIjoiQXR0cmlidXRlTm9kZSJ9LCJwcm9wZXJ0aWVzIjp7Im5vZGVfdHlwZSI6eyJlbnVtIjpbIkF0dHJpYnV0ZU5vZGUiLCJOb3QiXX19LCJkZXBlbmRlbmNpZXMiOnsibm9kZV90eXBlIjp7Im9uZU9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9BdHRyaWJ1dGVOb2RlIn0seyJwcm9wZXJ0aWVzIjp7Im5vZGVfdHlwZSI6eyJjb25zdCI6Ik5vdCJ9LCJjaGlsZCI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9yb290In19LCJyZXF1aXJlZCI6WyJjaGlsZCIsIm5vZGVfdHlwZSJdfV19fX0sImF0dHJfZm9vIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im5vZGVfdHlwZSI6eyJlbnVtIjpbIlN0cmluZ1ByZWRpY2F0ZSIsIk5vdCJdLCJkZWZhdWx0IjoiU3RyaW5nUHJlZGljYXRlIn19LCJkZXBlbmRlbmNpZXMiOnsibm9kZV90eXBlIjp7Im9uZU9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9TdHJpbmdQcmVkaWNhdGUifSx7InByb3BlcnRpZXMiOnsibm9kZV90eXBlIjp7ImNvbnN0IjoiTm90In0sImNoaWxkIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL2F0dHJfZm9vIn19LCJyZXF1aXJlZCI6WyJjaGlsZCIsIm5vZGVfdHlwZSJdfV19fX19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiIsInVpOmF1dG9jb21wbGV0ZSI6ImZhbWlseS1uYW1lIn0sImxhc3ROYW1lIjp7InVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJnaXZlbi1uYW1lIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=), with a recursive definition with dependencies.

To reproduce on that playground:
* Select attr -> foo
* Then update node_type -> Not
* Child node_type does not default to "AtttributeNode"

A related schema (which should be semantically equivalent) puts the default on the `node_type` property ([link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJub2RlX3R5cGUiOiJBdHRyaWJ1dGVOb2RlIn0sInNjaGVtYSI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9yb290IiwiZGVmaW5pdGlvbnMiOnsiU3RyaW5nUHJlZGljYXRlIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InBhdHRlcm4iOnsidHlwZSI6InN0cmluZyJ9LCJub2RlX3R5cGUiOnsiZGVmYXVsdCI6IlN0cmluZ1ByZWRpY2F0ZSIsImVudW0iOlsiU3RyaW5nUHJlZGljYXRlIl0sInR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbInBhdHRlcm4iLCJub2RlX3R5cGUiXX0sIkF0dHJpYnV0ZU5vZGUiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiYXR0ciI6eyJlbnVtIjpbImZvbyJdLCJ0eXBlIjoic3RyaW5nIn0sIm5vZGVfdHlwZSI6eyJkZWZhdWx0IjoiQXR0cmlidXRlTm9kZSIsImVudW0iOlsiQXR0cmlidXRlTm9kZSJdLCJ0eXBlIjoic3RyaW5nIn19LCJkZXBlbmRlbmNpZXMiOnsiYXR0ciI6eyJwcm9wZXJ0aWVzIjp7ImF0dHIiOnsiY29uc3QiOiJmb28ifSwiY2hpbGQiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvYXR0cl9mb28ifX19fX0sInJvb3QiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsibm9kZV90eXBlIjp7ImVudW0iOlsiQXR0cmlidXRlTm9kZSIsIk5vdCJdLCJkZWZhdWx0IjoiQXR0cmlidXRlTm9kZSJ9fSwiZGVwZW5kZW5jaWVzIjp7Im5vZGVfdHlwZSI6eyJvbmVPZiI6W3siJHJlZiI6IiMvZGVmaW5pdGlvbnMvQXR0cmlidXRlTm9kZSJ9LHsicHJvcGVydGllcyI6eyJub2RlX3R5cGUiOnsiY29uc3QiOiJOb3QifSwiY2hpbGQiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvcm9vdCJ9fSwicmVxdWlyZWQiOlsiY2hpbGQiLCJub2RlX3R5cGUiXX1dfX19LCJhdHRyX2ZvbyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJub2RlX3R5cGUiOnsiZW51bSI6WyJTdHJpbmdQcmVkaWNhdGUiLCJOb3QiXSwiZGVmYXVsdCI6IlN0cmluZ1ByZWRpY2F0ZSJ9fSwiZGVwZW5kZW5jaWVzIjp7Im5vZGVfdHlwZSI6eyJvbmVPZiI6W3siJHJlZiI6IiMvZGVmaW5pdGlvbnMvU3RyaW5nUHJlZGljYXRlIn0seyJwcm9wZXJ0aWVzIjp7Im5vZGVfdHlwZSI6eyJjb25zdCI6Ik5vdCJ9LCJjaGlsZCI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9hdHRyX2ZvbyJ9fSwicmVxdWlyZWQiOlsiY2hpbGQiLCJub2RlX3R5cGUiXX1dfX19fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJmYW1pbHktbmFtZSJ9LCJsYXN0TmFtZSI6eyJ1aTplbXB0eVZhbHVlIjoiIiwidWk6YXV0b2NvbXBsZXRlIjoiZ2l2ZW4tbmFtZSJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoidXBkb3duIiwidWk6dGl0bGUiOiJBZ2Ugb2YgcGVyc29uIiwidWk6ZGVzY3JpcHRpb24iOiIoZWFydGhpYW4geWVhcikifSwiYmlvIjp7InVpOndpZGdldCI6InRleHRhcmVhIn0sInBhc3N3b3JkIjp7InVpOndpZGdldCI6InBhc3N3b3JkIiwidWk6aGVscCI6IkhpbnQ6IE1ha2UgaXQgc3Ryb25nISJ9LCJkYXRlIjp7InVpOndpZGdldCI6ImFsdC1kYXRldGltZSJ9LCJ0ZWxlcGhvbmUiOnsidWk6b3B0aW9ucyI6eyJpbnB1dFR5cGUiOiJ0ZWwifX19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsInZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19)). Here following the same procedure refuses to update the invalid `child.node_type` value in formData (even though the default is displayed in the UI element), and doesn't display the `attr` element.

**Comment by heath-freenome** [comment]
I'm wondering if this is a very complicated example of #2944 in that our oneOf code isn't properly selecting the correct one-of

**Comment by Codeigniter-form-helper** [comment]
https://emery-struts27.github.io/zENuMf2Ic8FDYjk0Un4YwAk/

**Comment by heath-freenome** [comment]
@Codeigniter-form-helper Since this issue is closed as fixed several years ago, Can you open a new issue and clearly state the issue that your link is highlighting?
