### ISSUE TITLE
How to override submit button's class of the generated form?

### ISSUE THREAD

**Issue by HHOSSAIN** [rjsf-team/react-jsonschema-form#2979]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

material-ui

### What is your question?

I am trying to modify the <style> element in the header where data-mata="MuiButtonBase". I know for the attributes of the form, we can make styling changes like "padding" using ObjectFieldTemplate but what about the "submit" button? Can we make  padding changes to it? If so, what should I use?

**Comment by heath-freenome** [comment]
@HHOSSAIN See [this section](https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/uiSchema/#submitbuttonoptions) of the uiSchema documentation

**Comment by HHOSSAIN** [comment]
But as stated here as well https://github.com/rjsf-team/react-jsonschema-form/issues/2868 , the "Submit" button ignores the css classnames that I add here under "ui:submitButtonOptions". So, this is not letting me change the padding from 0 to 2 of <style> element of the header in data-mata="MuiButtonBase" . Is there currently a way to completely remove the default button of the form and add a custom button of my own from mui?

**Comment by heath-freenome** [comment]
You can wrap your custom button with the `Form` and it will replace the submit button with that content. I.e.
```
<Form schema={schema}>
  <button type="submit" classname="your classname">Submit</button>
</Form>
```

**Comment by heath-freenome** [comment]
Also, in the upcoming rjsf v5 beta, the way the classes are added to `SubmitButton` will be fixed to support your use case.

**Comment by heath-freenome** [comment]
Fixed in the v5 beta, see the [5.x migration guide](https://react-jsonschema-form.readthedocs.io/en/latest/5.x%20upgrade%20guide/)
