### ISSUE TITLE
Delete some old branches on this repo?

### ISSUE THREAD

**Issue by ahkhanjani** [rjsf-team/react-jsonschema-form#3012]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### Is your feature request related to a problem? Please describe.

There are some branches from 2 or 3 years ago and a lot of unmerged dependabot branches. They make the repo heavier and harder to navigate in. If they're not necessary the would you delete them for a cleaner dev experience?

**Comment by heath-freenome** [comment]
@ahkhanjani I'm trying to deal with getting the old PRs either refactored for v5 or closed after some time with no response
