### ISSUE TITLE
Investigate removing enumNames in v5 beta

### ISSUE THREAD

**Issue by nickgros** [rjsf-team/react-jsonschema-form#3016]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### Describe the solution you'd like

See #532 -- there are workarounds in draft-05, draft-06

Should write tests to verify that draft-05 and draft-06 solutions have the same effect as the existing enumNames behavior.

**Comment by heath-freenome** [comment]
@jimmycallin Are you willing to write tests (or verify that they already exist) to ensure that the work-arounds mentioned above are working in the beta already? And if so, removing the enumNames support?

**Comment by nickgros** [comment]
We elected to revert this change and will just deprecate for now.
