### ISSUE TITLE
submit form programmatically

### ISSUE THREAD

**Issue by galr52** [rjsf-team/react-jsonschema-form#3023]
Hey,

 I am trying to submit a form programmatically.
i have read the docs:
https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/internals/#submit-form-programmatically

but my form wont submitting:

https://stackblitz.com/edit/react-ygpqie?file=src/App.js

any idea what am i doing wrong?

@rjsf/core: 4.2.3
react: 18.2.0

thanks in advance,

**Comment by MaximeCrp** [comment]
I'm facing the same issue

```jsx
let form: JSONSchemaForm<Record<string, unknown>> | null = null;

return (
    <>
        <Button onClick={() => { form?.submit();}}>Submit</Button>
        <JSONSchemaForm
            formData={evaluationQuery.data.response}
            schema={formDefinition.jsonSchema}
            uiSchema={formDefinition.uiSchema}
            ref={(newForm) => {
                form = newForm;
            }}
            onSubmit={(event) => console.log(event.formData)}
        />
    </>
)
```

**Comment by heath-freenome** [comment]
Can you try the v5 beta and see if it works now? There was an issue that hopefully was fixed

**Comment by galr52** [comment]
> Can you try the v5 beta and see if it works now? There was an issue that hopefully was fixed

yes, it is working on v5 beta

also as @WillowP suggested, a fix for v4 can be done by make the button a submit button and just set the form attribute.

```
const ExampleB = () => {
  const onSubmit = ({ formData }) => {
    console.log('Data submitted: ', formData)
  };
  const schema = {
    type: 'string',
  };

  return (
    <div style={{ border: '1px solid black', padding: '4px' }}>
      <h3>Example B</h3>
      <Form
        id="my-form"
        schema={schema}
        onSubmit={onSubmit}
      >
        <></>
      </Form>
      <button type="submit" form="my-form">Submit</button>
    </div>
  );
};
```
https://stackblitz.com/edit/react-1yurkc?file=src%2FApp.js

**Comment by heath-freenome** [comment]
Closing as this works in the v5 beta

**Comment by MaximeCrp** [comment]
Do you know if this is going to be released in a patch for v4?
