### ISSUE TITLE
form validation fails on type 'array' and empty 'items.enum'

### ISSUE THREAD

**Issue by Mattervispa** [rjsf-team/react-jsonschema-form#3029]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

4.2.3

### Current Behavior

on submit: form validation fails with error mesages:

properties['multipleChoicesList'].items.enum should NOT have fewer than 1 items
.properties['multipleChoicesList'].items should be array
.properties['multipleChoicesList'].items should match some schema in anyOf

### Expected Behavior

form validation should pass

### Steps To Reproduce

steps to reproduce:

goto playground:arrays:multipleChoicesList

delete options in items.enum

enter submit button

### Environment

```markdown
playground

    "multipleChoicesList": {
      "type": "array",
      "title": "A multiple choices list",
      "items": {
        "type": "string",
        "enum": []
      },
      "minItems": 0,
      "uniqueItems": true
    },
```

### Anything else?

even minItems=0 does not help

**Comment by Mattervispa** [comment]
Background info:

options are editable by user in a second context. Hence an empty list is a valid usecase here.

jsonschema.org says:

> [6.1.2. ](http://json-schema.org/draft/2020-12/json-schema-validation.html#section-6.1.2)[enum](http://json-schema.org/draft/2020-12/json-schema-validation.html#name-enum)

> The value of this keyword MUST be an array. This array SHOULD have at least one element. Elements in the array SHOULD be unique.

SHOULD. But not MUST.

So IMHO form validation MUST not throw an error

**workaround**:

in case of an empty list (items.enum = [])

set items.enum to ["-"]

declare this mock option as disabled

"ui:enumDisabled": ["-"]

and/or 

disable field

works for me and form submit is no longer blocked

**Comment by heath-freenome** [comment]
@Mattervispa Using the latest [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJsaXN0T2ZTdHJpbmdzIjpbImZvbyIsImJhciJdLCJtdWx0aXBsZUNob2ljZXNMaXN0IjpbImZvbyJdLCJmaXhlZEl0ZW1zTGlzdCI6WyJTb21lIHRleHQiLHRydWUsMTIzXSwibWluSXRlbXNMaXN0IjpbeyJuYW1lIjoiRGVmYXVsdCBuYW1lIn0seyJuYW1lIjoiRGVmYXVsdCBuYW1lIn0seyJuYW1lIjoiRGVmYXVsdCBuYW1lIn1dLCJkZWZhdWx0c0FuZE1pbkl0ZW1zIjpbImNhcnAiLCJ0cm91dCIsImJyZWFtIiwidW5pZGVudGlmaWVkIiwidW5pZGVudGlmaWVkIl0sIm5lc3RlZExpc3QiOltbImxvcmVtIiwiaXBzdW0iXSxbImRvbG9yIl1dLCJ1bm9yZGVyYWJsZSI6WyJvbmUiLCJ0d28iXSwidW5yZW1vdmFibGUiOlsib25lIiwidHdvIl0sIm5vVG9vbGJhciI6WyJvbmUiLCJ0d28iXSwiZml4ZWROb1Rvb2xiYXIiOls0Mix0cnVlLCJhZGRpdGlvbmFsIGl0ZW0gb25lIiwiYWRkaXRpb25hbCBpdGVtIHR3byJdfSwic2NoZW1hIjp7ImRlZmluaXRpb25zIjp7IlRoaW5nIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im5hbWUiOnsidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJEZWZhdWx0IG5hbWUifX19fSwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsibGlzdE9mU3RyaW5ncyI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6IkEgbGlzdCBvZiBzdHJpbmdzIiwiaXRlbXMiOnsidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJiYXppbmdhIn19LCJtdWx0aXBsZUNob2ljZXNMaXN0Ijp7InR5cGUiOiJhcnJheSIsInRpdGxlIjoiQSBtdWx0aXBsZSBjaG9pY2VzIGxpc3QiLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6W119LCJtaW5JdGVtcyI6MCwidW5pcXVlSXRlbXMiOnRydWV9LCJmaXhlZEl0ZW1zTGlzdCI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6IkEgbGlzdCBvZiBmaXhlZCBpdGVtcyIsIml0ZW1zIjpbeyJ0aXRsZSI6IkEgc3RyaW5nIHZhbHVlIiwidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJsb3JlbSBpcHN1bSJ9LHsidGl0bGUiOiJhIGJvb2xlYW4gdmFsdWUiLCJ0eXBlIjoiYm9vbGVhbiJ9XSwiYWRkaXRpb25hbEl0ZW1zIjp7InRpdGxlIjoiQWRkaXRpb25hbCBpdGVtIiwidHlwZSI6Im51bWJlciJ9fSwibWluSXRlbXNMaXN0Ijp7InR5cGUiOiJhcnJheSIsInRpdGxlIjoiQSBsaXN0IHdpdGggYSBtaW5pbWFsIG51bWJlciBvZiBpdGVtcyIsIm1pbkl0ZW1zIjozLCJpdGVtcyI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9UaGluZyJ9fSwiZGVmYXVsdHNBbmRNaW5JdGVtcyI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6Ikxpc3QgYW5kIGl0ZW0gbGV2ZWwgZGVmYXVsdHMiLCJtaW5JdGVtcyI6NSwiZGVmYXVsdCI6WyJjYXJwIiwidHJvdXQiLCJicmVhbSJdLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6InVuaWRlbnRpZmllZCJ9fSwibmVzdGVkTGlzdCI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6Ik5lc3RlZCBsaXN0IiwiaXRlbXMiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJJbm5lciBsaXN0IiwiaXRlbXMiOnsidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJsb3JlbSBpcHN1bSJ9fX0sInVub3JkZXJhYmxlIjp7InRpdGxlIjoiVW5vcmRlcmFibGUgaXRlbXMiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6ImxvcmVtIGlwc3VtIn19LCJ1bnJlbW92YWJsZSI6eyJ0aXRsZSI6IlVucmVtb3ZhYmxlIGl0ZW1zIiwidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJsb3JlbSBpcHN1bSJ9fSwibm9Ub29sYmFyIjp7InRpdGxlIjoiTm8gYWRkLCByZW1vdmUgYW5kIG9yZGVyIGJ1dHRvbnMiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6ImxvcmVtIGlwc3VtIn19LCJmaXhlZE5vVG9vbGJhciI6eyJ0aXRsZSI6IkZpeGVkIGFycmF5IHdpdGhvdXQgYnV0dG9ucyIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjpbeyJ0aXRsZSI6IkEgbnVtYmVyIiwidHlwZSI6Im51bWJlciIsImRlZmF1bHQiOjQyfSx7InRpdGxlIjoiQSBib29sZWFuIiwidHlwZSI6ImJvb2xlYW4iLCJkZWZhdWx0IjpmYWxzZX1dLCJhZGRpdGlvbmFsSXRlbXMiOnsidGl0bGUiOiJBIHN0cmluZyIsInR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoibG9yZW0gaXBzdW0ifX19fSwidWlTY2hlbWEiOnsibGlzdE9mU3RyaW5ncyI6eyJpdGVtcyI6eyJ1aTplbXB0eVZhbHVlIjoiIn19LCJtdWx0aXBsZUNob2ljZXNMaXN0Ijp7InVpOndpZGdldCI6ImNoZWNrYm94ZXMifSwiZml4ZWRJdGVtc0xpc3QiOnsiaXRlbXMiOlt7InVpOndpZGdldCI6InRleHRhcmVhIn0seyJ1aTp3aWRnZXQiOiJzZWxlY3QifV0sImFkZGl0aW9uYWxJdGVtcyI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24ifX0sInVub3JkZXJhYmxlIjp7InVpOm9wdGlvbnMiOnsib3JkZXJhYmxlIjpmYWxzZX19LCJ1bnJlbW92YWJsZSI6eyJ1aTpvcHRpb25zIjp7InJlbW92YWJsZSI6ZmFsc2V9fSwibm9Ub29sYmFyIjp7InVpOm9wdGlvbnMiOnsiYWRkYWJsZSI6ZmFsc2UsIm9yZGVyYWJsZSI6ZmFsc2UsInJlbW92YWJsZSI6ZmFsc2V9fSwiZml4ZWROb1Rvb2xiYXIiOnsidWk6b3B0aW9ucyI6eyJhZGRhYmxlIjpmYWxzZSwib3JkZXJhYmxlIjpmYWxzZSwicmVtb3ZhYmxlIjpmYWxzZX19fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==) and the `5.0.0-beta.15` using the newer `ajv8` validator we are seeing a more useful error, indicating that an `enum must have non-empty array`. Your work-around it actually the solution to your problem. Good job finding it.
