### ISSUE TITLE
Ordering of form property in schema without a root element

### ISSUE THREAD

**Issue by joyerean** [rjsf-team/react-jsonschema-form#3043]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### What is your question?

My schema looks like below

```
{
	"attribute1": {
		"title": "Attribute 1",
		"type": "object",
		"properties": {
			"sub1": {
				"title": "Sub 1",
				"type": "object",
				"properties": {
				....
				}
			},
			"sub2": {
				"title": "Sub 2",
				"type": "object",
				"properties": {
				....
				}
			}
		}
	},
	"attribute2": {
		"title": "Attribute 2",
		"type": "object",
		"properties": {
		....
		}
	},
	"attribute3": {
		"title": "Attribute 3",
		"type": "object",
		"properties": {
		....
		}
	}
}
```

My ui schema looks like below

```
{
	"ui:order": [
		"attribute3",
		"attribute1",
		"attribute2"
	],
	"attribute1": {
		"ui:order": [
			"sub2",
			"sub1"
		]
	}	
}
```

While sub1 and sub2 are coming in the mentioned order, I couldn't get the outer elements in the same way. This schema does not have a root element. Is there any way get the outer properties displayed in the mentioned order?

Thanks in advance

**Comment by heath-freenome** [comment]
Does it work for you to make the outer element an `object` type and the `attribute1`, `attribute2` and `attribute3` properties?

**Comment by joyerean** [comment]
@heath-freenome Yes. If there is a root element of `object` type, ordering is fine

**Comment by heath-freenome** [comment]
Is that an acceptable solution?

**Comment by joyerean** [comment]
My use case has multiple root elements and can not be enclosed under a single element. I just wanted to check whether there is a solution that I didn't know of before. If it doesn't exist, it would be great to have ordering support for multiple root elements.
