### ISSUE TITLE
Form data persist removed/hidden properties data while using dependencies

### ISSUE THREAD

**Issue by shubham-malpani** [rjsf-team/react-jsonschema-form#3078]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

material-ui

### Version

4.1.1

### Current Behavior

Let's consider below Schema where dependencies with one added.
If **isMandatory** field is checked then should show **billing_address** otherwise hidden

steps
1. checked isMandatory & fill out **billing_address** field
2. you will billing_address in form-data
3. simply unchecked **isMandatory** & see form data

**billing_address** field is still there in formdata

```
JSON Schema

{
  "title": "Property dependencies",
  "description": "These samples are best viewed without live validation.",
  "type": "object",
  "properties": {
    "title": "Unidirectional",
    "name": {
      "type": "string"
    },
    "isMandatory": {
      "type": "boolean",
      "enum": [
        true,
        false
      ]
    }
  },
  "required": [
    "name"
  ],
  "dependencies": {
    "isMandatory": {
      "oneOf": [
        {
          "properties": {
            "isMandatory": {
              "enum": [
                true
              ]
            },
            "billing_address": {
              "type": [
                "string",
                "null"
              ]
            }
          }
        },
        {
          "properties": {
            "isMandatory": {
              "enum": [
                false,
                null
              ]
            }
          }
        }
      ]
    }
  }
}
```

### Expected Behavior

In above case if I unchecked **isMandatory** then it should reset values of dependent fields (nullify).

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Anything else?

We are using this library in our company project & we are going with some custom solution with onchange event which is quite expensive operation now & also depends on  [this issue](https://github.com/rjsf-team/react-jsonschema-form/issues/651).

**Comment by heath-freenome** [comment]
@shubham-malpani  It looks like you found an issue where the combination of `live omit` and `omit extra data` doesn't work with dependencies. Thanks! Here is a [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJpc01hbmRhdG9yeSI6ZmFsc2UsImJpbGxpbmdfYWRkcmVzcyI6ImZvbyJ9LCJzY2hlbWEiOnsidGl0bGUiOiJQcm9wZXJ0eSBkZXBlbmRlbmNpZXMiLCJkZXNjcmlwdGlvbiI6IlRoZXNlIHNhbXBsZXMgYXJlIGJlc3Qgdmlld2VkIHdpdGhvdXQgbGl2ZSB2YWxpZGF0aW9uLiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InRpdGxlIjoiVW5pZGlyZWN0aW9uYWwiLCJuYW1lIjp7InR5cGUiOiJzdHJpbmcifSwiaXNNYW5kYXRvcnkiOnsidHlwZSI6ImJvb2xlYW4iLCJlbnVtIjpbdHJ1ZSxmYWxzZV19fSwicmVxdWlyZWQiOlsibmFtZSJdLCJkZXBlbmRlbmNpZXMiOnsiaXNNYW5kYXRvcnkiOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsiaXNNYW5kYXRvcnkiOnsiZW51bSI6W3RydWVdfSwiYmlsbGluZ19hZGRyZXNzIjp7InR5cGUiOlsic3RyaW5nIiwibnVsbCJdfX19LHsicHJvcGVydGllcyI6eyJpc01hbmRhdG9yeSI6eyJlbnVtIjpbZmFsc2UsbnVsbF19fX1dfX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjp0cnVlLCJsaXZlT21pdCI6dHJ1ZX19) to help reproduce it.

**Comment by shubham-malpani** [comment]
@heath-freenome  Got it. Thanks for the update.

**Comment by shubham-malpani** [comment]
@heath-freenome any plans to fix this?

**Comment by heath-freenome** [comment]
@shubham-malpani We have no immediate plans to fix this since dependencies are a tricky thing to fully support as it turns out. If you feel up to it, I encourage you to provide a fix since it is definitely impacting you.

**Comment by shubham-malpani** [comment]
Well, I see this got fixed.
