### ISSUE TITLE
How to put description under the input field.

### ISSUE THREAD

**Issue by amin-arabi** [rjsf-team/react-jsonschema-form#3079]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### What is your question?

How can I put the decription **under** the field?

Adding description, it always appears _above_ the field, however I need to show it _under_ the field.
What I get:
![Screenshot 2022-09-02 at 11-44-33 Document](https://user-images.githubusercontent.com/94345665/188112873-811343c5-b6c6-45af-9f66-c18b0da0325f.png)

What I want:
![Screenshot 2022-09-02 at 11-43-58 Document](https://user-images.githubusercontent.com/94345665/188112798-96df7f84-ec78-4879-b55d-be73a1803995.png)
What I

've tried:

- Put the description inside the custom widget.
  problems:
  1. The description appears both above and under.
  2. The added description needs styling, cause it doens't take it automatically, as the normal description does.

**Comment by heath-freenome** [comment]
You can provide a custom field template (see these [instructions](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-templates/#fieldtemplate)) to move the location of the description... It would look something like:

```tsx
import React from "react";
import {
  FieldTemplateProps,
  FormContextType,
  RJSFSchema,
  StrictRJSFSchema,
  getTemplate,
  getUiOptions,
} from "@rjsf/utils";

import Label from "./Label";

/** The `FieldTemplate` component is the template used by `SchemaField` to render any field. It renders the field
 * content, (label, description, children, errors and help) inside of a `WrapIfAdditional` component.
 *
 * @param props - The `FieldTemplateProps` for this component
 */
export default function FieldTemplate<
  T = any,
  S extends StrictRJSFSchema = RJSFSchema,
  F extends FormContextType = any
>(props: FieldTemplateProps<T, S, F>) {
  const {
    id,
    label,
    children,
    errors,
    help,
    description,
    hidden,
    required,
    displayLabel,
    registry,
    uiSchema,
  } = props;
  const uiOptions = getUiOptions(uiSchema);
  const WrapIfAdditionalTemplate = getTemplate<
    "WrapIfAdditionalTemplate",
    T,
    S,
    F
  >("WrapIfAdditionalTemplate", registry, uiOptions);
  if (hidden) {
    return <div className="hidden">{children}</div>;
  }
  return (
    <WrapIfAdditionalTemplate {...props}>
      {displayLabel && <Label label={label} required={required} id={id} />}
      {children}
      {displayLabel && description ? description : null}
      {errors}
      {help}
    </WrapIfAdditionalTemplate>
  );
}
```
