### ISSUE TITLE
Customize the title of ArrayFieldItemTemplate

### ISSUE THREAD

**Issue by Jisay** [rjsf-team/react-jsonschema-form#3090]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

chakra-ui

### What is your question?

I would like to customize the title of an array item of object. For example with the playground (https://t.ly/22xp). I would like to have an other title than `listOfStrings-0`, `listOfStrings-1` etc... In my case, I disable to add an item, to reorder them and delete them and I know the number of items in my array. Those items have their own name and I would like to display those names instead of the default title. 
Is there an easy way of doing it? I have tried to create a custom `ArrayFieldItemTemplate` and `ArrayFieldTemplate` but can't succeed in display what I want.
Thanks in advance for your help!

**Comment by heath-freenome** [comment]
@Jisay Unfortunately, right now there is no simple way of doing what you need right now. You might be able to update the `ArrayFieldItemTemplate` and use the `React.cloneElement()` function on the `children` props to change the `name` prop passed to the `SchemaField` to be what you need, or update the `uiSchema` prop to programmatically insert a `ui:title` into.

```
...
  const onArrowDownClick = useMemo(
    () => onReorderClick(index, index + 1),
    [index, onReorderClick]
  );
let arrayTitle;
switch(index) {
  case 0:
    arrayTitle = "First element title";
    break;
  case 1:
    arrayTitle = "Second element title";
    break;
}
const newChildren = React.cloneElement(children, { uiSchema: { "ui:title": arrayTitle } });

  return (
    <HStack alignItems={"flex-end"} py={1}>
      <Box w="100%">{newChildren}</Box>
...
```

**Comment by Jisay** [comment]
Thanks for your answer @heath-freenome!
Your solution is working, I have changed the `ArrayFieldTemplate` with a "add-on" in the uiSchema. It looks like something like this:
```
...
function ArrayFieldTemplate(props) {
    return (
      <div>
        {props.items.map((element, index) => (
          <React.Fragment key={element.key}>
            {React.cloneElement(element.children, {
              name: props.uiSchema['ui:titles'][index],
            })}
          </React.Fragment>
        ))}
      </div>
    );
  }

const uiSchema = {
    arrayField: {
      'ui:options': {
        addable: false,
        removable: false,
        orderable: false,
      },
      'ui:titles': [
        'First element title',
        'Second element title',
        'Third element title',
      ],
    },
  };
...
```
