### ISSUE TITLE
Custom widget support for object type fields

### ISSUE THREAD

**Issue by jamiehales** [rjsf-team/react-jsonschema-form#3097]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

material-ui

### Is your feature request related to a problem? Please describe.

We have a large number of custom widgets in our schema for providing better interaction experiences with users, but have not currently found a way of binding the widgets to objects. The documentation states that it's only valid for string/number/integer/boolean/array field types. Is there any plans for adding object as one of the supported types here?

### Describe the solution you'd like

The ability to bind to object fields for custom widgets.

### Describe alternatives you've considered

We have a workaround where we transform the object into a single item array at load, and transform it back on submission but this seems sub-optimal. The widgets we're trying to do need to operate on the whole object, not the individual fields.

**Comment by Nibiri** [comment]
In my case, I used ObjectFieldTemplate
 https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-templates/#objectfieldtemplate
 I had a field with an address like an object

**Comment by heath-freenome** [comment]
@jamiehales an object is a collection of field items and a widget is only mappable to field items. You can definitely override the `ObjectFieldTemplate` to do custom things if you need to. Using the `ui:ObjectFieldTemplate` keyword in the uiSchema on a per field basis, you can even allocate different templates to different fields.  You can also implement a custom field that you apply to an object (via the `ui:field` keyword in the uiSchema). There is no plan to support mapping an object to a widget, nor do I image we ever really plan to support that.

**Comment by Bonfims** [comment]
I was trying to build a widget that was an editor, we put json text, check if it is valid and make the value of a field an object resulting from what is written in the custom widget editor, as if I were using the textarea editor to type a json string and with a JSON.parse to translate the text into an object that will be assigned to the widget field.

Example: 

```
schema: {
   "type": "object",
   "properties": {
         "label": {
                "type": "string"
          }
         "schemas": {
                "type": "object",
                "additionalProperties": true
         }
    }
}
```

```
uiSchema: {
   "schemas": { "ui:widget": "jsonEditor" }
}
```

```
formData: {
     "label": "Hello World"
     "schemas": {
           // whole object generated by text in jsonEditor widget
      }
}
```

Makes any sense?
