### ISSUE TITLE
Trouble with i18n on 5.0.0-beta.5

### ISSUE THREAD

**Issue by aurelmegn** [rjsf-team/react-jsonschema-form#3101]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.0.0-beta.5

### Current Behavior

 The released version of `customizeValidator` doesn't take an additional localizer argument. It results in the i18n not working

### Expected Behavior

The error translation should be done

### Steps To Reproduce

I attached a code sandbox https://codesandbox.io/s/wizardly-david-4m3wj4

**Comment by heath-freenome** [comment]
@aurelmegn Try it with beta.6 please as it actually has that code. We have a known issue where the documentation for the latest code in the master (before a release) is shown to users. Sorry about that.
