### ISSUE TITLE
Last release beta.7 is not available as npm package

### ISSUE THREAD

**Issue by v1ack** [rjsf-team/react-jsonschema-form#3117]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.0.0-beta.7

### Current Behavior

<img width="472" alt="Снимок экрана 2022-09-16 в 16 33 42" src="https://user-images.githubusercontent.com/11501957/190651132-e8447d1c-752b-4106-8afb-e8230065fdbb.png">

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by heath-freenome** [comment]
@v1ack Whoops, yes there was an issue building that release. We are releasing 5.0.0-beta.8 momentarily so it should be available very soon.
