### ISSUE TITLE
Programmatic submit does not work properly in Firefox

### ISSUE THREAD

**Issue by nickgros** [rjsf-team/react-jsonschema-form#3121]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.0.0-beta6

### Current Behavior

When using Firefox programmatic submit ends up embedding a copy of the entire page into the rendered form

<img width="1529" alt="image" src="https://user-images.githubusercontent.com/17580037/190682346-589f0338-7846-4bff-a985-f16a397321f4.png">

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by heath-freenome** [comment]
@jacqueswho Do you have time to take a look at this?

**Comment by jacqueswho** [comment]
ill take a look

**Comment by saswat3115** [comment]
I also faced same issue. Want programmatically submit as we ll as validating forms also

**Comment by emielvanseveren** [comment]
> Workaround: it seems instead of calling `ref.current.submit()` as in the [docs](https://rjsf-team.github.io/react-jsonschema-form/docs/advanced-customization/internals/#submit-form-programmatically), you can do `ref.current.formElement.current.requestSubmit()`

Can confirm, this works. Might want to add this to the docs (temporarily). 

I looked a bit further into this. And I think (not tested) it has something to do with the dispatched event not being the same event as the actual formSubmitEvent. So when adding e.g. `e.preventDefault()` in the onSubmitHandler it is trying to stop the formSubmit event and not the custom dispatched event. 

I don't have the time to test this, but one could try to add e.preventDefault close to the dispatchedEvent and see if it still occurs.

**Comment by snlamm** [comment]
> I looked a bit further into this. And I think (not tested) it has something to do with the dispatched event not being the same event as the actual formSubmitEvent. So when adding e.g. e.preventDefault() in the onSubmitHandler it is trying to stop the formSubmit event and not the custom dispatched event.

Also ran into this issue - though in Chrome - where it was causing the onSubmit function to be called twice.
Fortunately, the `ref.current.formElement.current.requestSubmit()` workaround worked 👍 .

**Comment by hirenr** [comment]
I can confirm this does not work on Safari. I can see the issue in the playground also. 

It seems 
```
requestSubmit
```
is not supported in Safari at all. So the above workaround also is not working!

**Comment by jeremy-marcus** [comment]
With the merge of #4150, is this issue now closed?

**Comment by heath-freenome** [comment]
@jeremy-marcus It most likely is. @nickgros would you be willing to confirm this and close it?

**Comment by yelsayed** [comment]
The latest version (v5.19.4) works on firefox
