### ISSUE TITLE
Wrong import in rjsf/antd

### ISSUE THREAD

**Issue by v1ack** [rjsf-team/react-jsonschema-form#3123]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

antd

### Version

5.0.0-beta.8

### Current Behavior

Wrong react import in generated file
node_modules/@rjsf/antd/dist/index.d.ts:35
```typescript
export const Form: import("@rjsf/core/node_modules/@types/react").ForwardRefExoticComponent<import("@rjsf/core").FormProps<any, {}> & import("@rjsf/core/node_modules/@types/react").RefAttributes<import("@rjsf/core").default<any, {}>>>;
```

### Expected Behavior

Must be `import("@types/react")`

### Environment

```markdown
- OS: macOS 12.5
- Node: v18.7.0
- npm: 8.15.0
```

**Comment by heath-freenome** [comment]
Since `antd` isn't written in typescript the compiler is automatically generating things like this. What kind of problems is it causing?

**Comment by v1ack** [comment]
This import can't be found, so unable to compile typescript.
As a workaround I use direct import from antd.esm
