### ISSUE TITLE
ArraySchemaField should default to the SchemaField from the registry

### ISSUE THREAD

**Issue by olzraiti** [rjsf-team/react-jsonschema-form#3131]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### Is your feature request related to a problem? Please describe.

For backward compatibility's sake the new `ArraySchemaField` should default to the `SchemaField` from the registry instead of `rjsf`'s implementation of the `SchemaField` component. Even if backward compatibility wasn't taken into account, in most use cases people probably want to use a single `SchemaField` implementation regardless of whether it's inside an array or not, so not having to define both of them separately would be easier.

**Comment by heath-freenome** [comment]
Are you suggesting that we do not define `ArraySchemaField` in the fields list, but instead look for it and if it does not exist, take the `SchemaField` instead?

**Comment by olzraiti** [comment]
Yes, that way backward compatibility would remain :)
