### ISSUE TITLE
5.0.0 Released on 1/30/2023!

### ISSUE THREAD

**Issue by heath-freenome** [rjsf-team/react-jsonschema-form#3144]
We are SOOOO close to wrapping up the v5 beta. Please download and test the beta and let us know if we've broken anything that we did NOT document.

Initial hope is to have the 5.0.0 release ready by 10/31/22

**Comment by heath-freenome** [comment]
Ok, given we are still making small incremental, but significant changes, we are pushing the 5.0.0 release out. Hopefully 11/15/2022

**Comment by epicfaace** [comment]
I'd also like to take a pass of the 5.x upgrade guide to make sure the upgrade is as painless as possible! I will do soon and make a PR. Thanks for all your work on this!!!

**Comment by heath-freenome** [comment]
Well, we still aren't quite ready... moving out two more weeks

**Comment by heath-freenome** [comment]
Having some issues getting key fixes completed. Moving to 12/25... Hopefully we'll have a holiday present for you all.

**Comment by heath-freenome** [comment]
Wow, we have one more issue left to deal with... pushing out a few more weeks

**Comment by fregante** [comment]
Are there any known issues in v5? Why is it being posticipated?

**Comment by heath-freenome** [comment]
> Are there any known issues in v5? Why is it being postponed?

We are trying to complete the last bit of Typescript conversion #3072 and then hopefully we can release

**Comment by benjdlambert** [comment]
@heath-freenome do you have a revised timeline on when you expect to ship v5 stable?

**Comment by heath-freenome** [comment]
@benjdlambert sorry for the delay, we are fixing two small issues that have potentially small breaking changes to 5.0.0 if they were made after the beta. We will release 5.0.0 within a week, hopefully

**Comment by benjdlambert** [comment]
Congratz @heath-freenome @epicfaace + all. Nice work! :pray:
