### ISSUE TITLE
Custom number format widget

### ISSUE THREAD

**Issue by michal-laskowski** [rjsf-team/react-jsonschema-form#3151]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### What is your question?

How can I add widget for custom format for number fields, like in "widgetMap"?

**Comment by heath-freenome** [comment]
You can either override the `NumberField` in the `fields` prop as described in this [documentation](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/#customizing-the-default-fields-and-widgets) or you can create a custom widget component and use the `uiSchema` to have that field rendered with it as described in this [documentation](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/#custom-component-registration)

**Comment by michal-laskowski** [comment]
yes, these are some of the solutions, but.
1. I don't want to define a widget for every field in the model (in UI schema)
2. in the case of the field, I would have to handle the fallback logic, in case it was not about my format for the numeric field.

The logic of getWidget works so that when a format is given for a field, it tries to find a widget named by format:
registeredWidgets.hasOwnProperty(widget)
where 'widget' will be format.

If it does not find it, it looks up widgetMap[type] and then by format.

If I could define your own widgets in the same way as in widgetMap, adding a format would be much easier, and fallback for default handling would remain the internal logic of your component

**Comment by heath-freenome** [comment]
Using the `getDefaultRegistry()` function in core you could write your `NumberField` as follows:
``` tsx
import { FieldProps } from "@rjsf/utils";
import { getDefaultRegistry } from "@rjsf/core";

const { NumberField: DefaultNumberField } = getDefaultRegistry().fields;

export default function MyNumberField(props: FieldProps) {
  const isMine = ...;  // Your special detection logic
  if (isMine) {
    const { Widget } = getWidget('mywidget');
    const myProps = {...}; // setup your props
    return (
      <Widget {...myProps} />
    );
   return <NumberField {...props} />;
  }
}
```

**Comment by michal-laskowski** [comment]
This is a good solution, I am worried about the amount of code I would have to manage.

At the moment I decided to use a different solution.
I define properties as
```
"createdOn": {
   "type": "number",
   "format": "number: date-time"
}
```

And added widget:
```
const widgets = {
   "number: date-time": NumberDateTimeWidget
}
```

But it would be nice if you moved your widget search logic to the Form component and add the ability to define/extend a widget map on Form

**Comment by heath-freenome** [comment]
Honestly, your solution is rather more elegant, albeit needing to add the custom format into the schema. That may required you to add a [custom format ](https://react-jsonschema-form.readthedocs.io/en/latest/usage/validation/#customformats)to the validator though. Not sure
