### ISSUE TITLE
Add support for chakra-react-select v4 

### ISSUE THREAD

**Issue by ldorofeeva** [rjsf-team/react-jsonschema-form#3152]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

chakra-ui

### Version

5.0.0-beta.9

### Current Behavior

`@rjsf/chakra-ui` has a dependency `"chakra-react-select": "^3.3.8"`

A combination of `@chakra-ui/react@^2.0.0` and `react@^18.0.0` with `chakra-react-select` v3 has a known issue with styles - `Select` element is not displayed correctly in the Dark mode (see this [issue](https://github.com/csandman/chakra-react-select/issues/134) in `chakra-react-select` repo)

![image](https://user-images.githubusercontent.com/15027333/192631382-34311ed4-49c2-4de5-9b54-a8df86edf3bc.png)

Please add support for `chakra-react-select` v4.

### Expected Behavior

Correct styles in dark mode, such as in native Select component of  `chakra-react-select` v4:

![image](https://user-images.githubusercontent.com/15027333/192631602-69096615-4523-4ce6-8cfd-1297f8c5672b.png)

### Steps To Reproduce

Link to the sandbox:
https://codesandbox.io/s/react-18-chakra-2-crs-4-vs-rjsf-chakra-ui-5-example-lj04hz

Switch to dark mode to see the difference

### Environment

```markdown
- OS: CentOS 7
- Node: 16.15.0
- npm: 8.13.1

- @chakra-ui/react@2.2.1
- react@18.2.0
```

**Comment by heath-freenome** [comment]
@ldorofeeva is this something you'd be interested in providing a fix for?
