### ISSUE TITLE
Custom field onchange not working with oneOf

### ISSUE THREAD

**Issue by rkxhs02** [rjsf-team/react-jsonschema-form#3158]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

4.1.1

### Current Behavior

OnChange is used in the custom field, but the formdata does not change.

If you remove oneOf and add items to property, it works correctly.

In the "react-jsonschema-form" package, oneOf works correctly.

```javascript
import React, { useEffect, useState } from "react";
import Form from "@rjsf/core";
// import Form from "react-jsonschema-form"

const schema = {
  type: "object",
  properties: {
    // items: {
    //   type: "array"
    // },
    itemType: {
      type: "string",
      enum: ["A", "B"],
      default: "A"
    }
  },
  dependencies: {
    itemType: {
      oneOf: [
        {
          properties: {
            itemType: {
              enum: ["A"]
            }
          }
        },
        {
          properties: {
            itemType: {
              enum: ["B"]
            },
            items: {
              type: "array"
            }
          }
        }
      ]
    }
  }
};
const uiSchema = {
  items: {
    "ui:field": "CustomField"
  }
};

const defaultFormData = {
  itemType: "B",
  items: ["1", "2"]
};

const CustomField = (props) => {
  const { formData = [], onChange } = props;
  const [options, setOptions] = useState([]);

  useEffect(() => {
    setOptions(formData);
  }, []);

  useEffect(() => {
    console.log(options);
    onChange(options);
  }, [options]);

  return <div>{JSON.stringify(formData)}</div>;
};

const fields = {
  CustomField
};

export default function App() {
  const [formData, setFormData] = useState({});

  useEffect(() => {
    setFormData(defaultFormData);
  }, []);

  const handleOnChange = (e) => {
    setFormData(e.formData);
  };

  return (
    <Form
      onChange={handleOnChange.bind(this)}
      formData={formData}
      schema={schema}
      fields={fields}
      uiSchema={uiSchema}
    />
  );
}

```

[https://codesandbox.io/s/suspicious-tree-3trwfx?file=/src/App.js](https://codesandbox.io/s/suspicious-tree-3trwfx?file=/src/App.js)

### Expected Behavior

The form data must be output ["1", "2"].

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by heath-freenome** [comment]
@rkxhs02 Can you test this with the v5 beta?

**Comment by rkxhs02** [comment]
@heath-freenome It seems to work well with v5 beta.

[https://codesandbox.io/s/angry-bell-fjhj9c?file=/src/App.js](https://codesandbox.io/s/angry-bell-fjhj9c?file=/src/App.js)

**Comment by heath-freenome** [comment]
So we can close this issue now?

**Comment by rkxhs02** [comment]
Yes I will close the issue.
