### ISSUE TITLE
json schema form dependencies coming at the end

### ISSUE THREAD

**Issue by chetnaluthra** [rjsf-team/react-jsonschema-form#3163]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

material-ui

### What is your question?

I tired adding another field after "Do you have any pets?". In case of yes, One, the next question "How old is your pet?*" comes after my new field.
The dependent field comes at the end of the form and not after the dependency.
Tired ui:order too. Didn't work for me.

**Comment by chetnaluthra** [comment]
Any updates? @epicfaace

**Comment by heath-freenome** [comment]
@chetnaluthra If you can provide a playground link to a reproducible use case we can try to understand the issue. Then maybe it can be fixed.
