### ISSUE TITLE
ExtraErrors are merged into errorSchema again and again

### ISSUE THREAD

**Issue by krebbl** [rjsf-team/react-jsonschema-form#3169]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x Beta.10

### Current Behavior

The passed extraErrors are rendered multiple times when typing into an input field.

### Expected Behavior

The `extraErrors` should only be displayed once.

### Steps To Reproduce

See example: https://codesandbox.io/s/vigilant-violet-8txkdr

Given the following Form config:

```jsx
import validator from "@rjsf/validator-ajv6";
import Form from "@rjsf/core";

const schema = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "email": {
            "type": "string",
            "format": "email"
        },
        "password": {
            "type": "string"
        },
        "passwordConfirmation": {
            "type": "string"
        }
    },
    "required": [
        "email",
        "password",
        "passwordConfirmation"
    ],
    "additionalProperties": false
}
...
<Form
   validator={validator}
   extraErrors={{email: {__errors: ["test"]}}}
   schema={schema}
   onSubmit={handleSubmit}
>
```

When typing something into the password field, the extra errors are appended in the UI again and again.

<img width="459" alt="image" src="https://user-images.githubusercontent.com/951433/193607443-5dd17beb-ce1a-431d-b126-bc44e6074ce5.png">

### Environment

```markdown
- OS: MaxOS
- Node: 16.7
- npm: 8.15
```

**Comment by krebbl** [comment]
The issue seems to be caused by this line https://github.com/rjsf-team/react-jsonschema-form/blob/33896dc2d196775a3fde63099efdfbdf11514393/packages/core/src/components/Form.tsx#L565
Here the `newErrorSchema` is merged with the `extraErrors` but instead of replacing the field errors the `extraErrors.email.__errors` are appended everytime it runs.

**Comment by krebbl** [comment]
I'm not able to reproduce this issue on the main branch, so it seems to be fixed there. Waiting for the next beta release now.

**Comment by heath-freenome** [comment]
@krebbl Beta 11 has been out for a few days... give it a try

**Comment by krebbl** [comment]
@heath-freenome Thanks for letting me! I just tried it in the linked code sandbox and the issue unfortunately still exists.

https://codesandbox.io/s/vigilant-violet-8txkdr?file=/package.json

**Comment by dagda1** [comment]
I am hitting this also in beta.13
