### ISSUE TITLE
Wrong doc link on Github

### ISSUE THREAD

**Issue by zehawki** [rjsf-team/react-jsonschema-form#3190]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

other

### Version

NA

### Current Behavior

The main "Explore the docs »" link on readme.md may point to https://react-jsonschema-form.readthedocs.io/en/latest/ rather than https://react-jsonschema-form.readthedocs.io/en/stable/, which is a 404. I'm always tripped by this.

Lower down on the page it links to the former.

```
Documentation
Read our [documentation](https://react-jsonschema-form.readthedocs.io/en/latest/) on Read the Docs.
```

![image](https://user-images.githubusercontent.com/8095144/194701251-01b7d0e5-5f8a-4adf-b074-8fd358b8ba65.png)

**Comment by sohanvichare7** [comment]
Hello @zehawki  , May I Solve this issue stating Wrong Document Link???

**Comment by heath-freenome** [comment]
We are aware of this issue and hope it will resolve once we release 5.0.0
