### ISSUE TITLE
Hiding object fields within array

### ISSUE THREAD

**Issue by sbmsr** [rjsf-team/react-jsonschema-form#3197]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

chakra-ui

### What is your question?

Hi all. I've got an array of objects. I'd like to hide some of the object fields if possible. Can't figure it out. Some things i've tried:

- hide the entire array: this hides the entire array, where as i am trying to hide object fields within the array
- use a custom ArrayFieldTemplate:  i see the uiSchema of each object is {}. I'd like to change this, but uiSchema is readonly.

Any ideas on how I could hide object fields within an array?

**Comment by heath-freenome** [comment]
I guess that depends on how you identify objects to hide. Is something in the data or schema that triggers identifies what to hide? If you just have a list of field names, you could provide an `ArraySchemaField` that pulls the `SchemaField` from the `registry.fields` and returns null for those fields. Something like:

```tsx
import { 

function ArraySchemaField(props: FieldProps) {
  const { registry, idSchema } = props;
  const { SchemaField } = registry.fields;
  const fieldId = idSchema[ID_KEY];
  if (listOfFields.contains(fieldId)) {
   return null;
  }
  return <SchemaField {...props} />
}
```
