### ISSUE TITLE
AJV8 additionalProperties validation broken in playground

### ISSUE THREAD

**Issue by rap1ds** [rjsf-team/react-jsonschema-form#3213]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

 In the playground, with the AJV8 validator, form data with additional keys that don't match the schema are valid and the form is submitted.

Playground: https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYXNzS2lja0NvdW50IjoxMjN9LCJzY2hlbWEiOnsidGl0bGUiOiJBIGN1c3RvbWl6YWJsZSByZWdpc3RyYXRpb24gZm9ybSIsImRlc2NyaXB0aW9uIjoiQSBzaW1wbGUgZm9ybSB3aXRoIGFkZGl0aW9uYWwgcHJvcGVydGllcyBleGFtcGxlLiIsInR5cGUiOiJvYmplY3QiLCJyZXF1aXJlZCI6WyJmaXJzdE5hbWUiLCJsYXN0TmFtZSJdLCJhZGRpdGlvbmFsUHJvcGVydGllcyI6eyJ0eXBlIjoic3RyaW5nIn0sInByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkZpcnN0IG5hbWUifSwibGFzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiTGFzdCBuYW1lIn19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiJ9fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==

Please note that I tried this _only_ on playground since locally I'm still using old AJV6 on my project.

### Expected Behavior

additionalProperties is set to type "string", thus, number value such as 123 should fail to validate.

AJV6 (deprecated) validator behaves as expected and gives validation error "assKickCount should be string"

### Steps To Reproduce

1. Go to Playground
2. Pick the "Additional Properties" example
3. Select AJV8_xx validator
4. Change formData value of assKickCount to any number, e.g. 123.
5. Click Submit

### Environment

```markdown
- Playground
```

**Comment by nickgros** [comment]
Fixed in #3229, will be in 5.0.0-beta.13
