### ISSUE TITLE
codepen examples in docs broken

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#3215]
See https://react-jsonschema-form.readthedocs.io/en/latest/usage/single/

Do you know what might have happened @heath-freenome @nickgros ?

**Comment by heath-freenome** [comment]
@epicfaace Can you be more specific about how they are broken? It's pretty clear we forgot to import the `Form` from `@rjsf/core` but the old links didn't either.

**Comment by epicfaace** [comment]
Running into this issue (https://github.com/skypackjs/skypack-cdn/issues/337) now.

**Comment by epicfaace** [comment]
> @epicfaace Can you be more specific about how they are broken? It's pretty clear we forgot to import the `Form` from `@rjsf/core` but the old links didn't either.

By the way @heath-freenome , the reason they're broken now is that previously, we just used the UMD version and didn't need the import statements, as JSONSchemaForm was a global variable available. Now the code examples all use imports from different packages so we'll have to switch from using UMD to configuring codepen to also support js `import` statements.
