### ISSUE TITLE
Add a support for ```label``` for array items 

### ISSUE THREAD

**Issue by harkiratsm** [rjsf-team/react-jsonschema-form#3231]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### What is your question?

Does rjsf support ```label```  for array items ?

From a conversation with @heath-freenome, I guess rjsf does not support it.

**Comment by heath-freenome** [comment]
@harkiratsm In this [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJsaXN0T2ZTdHJpbmdzIjpbImZvbyIsImJhciJdfSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Imxpc3RPZlN0cmluZ3MiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJBIGxpc3Qgb2Ygc3RyaW5ncyIsIml0ZW1zIjp7InRpdGxlIjoiIiwidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJiYXppbmdhIn19fX0sInVpU2NoZW1hIjp7Imxpc3RPZlN0cmluZ3MiOnsiaXRlbXMiOnsidWk6ZW1wdHlWYWx1ZSI6IiIsInVpOmxhYmVsIjpmYWxzZX19fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOnRydWUsImxpdmVPbWl0Ijp0cnVlfX0=) I just tried adding the `"ui:label": false` and it worked. Does doing something similar in your situation also work?

**Comment by harkiratsm** [comment]
Thank @heath-freenome

**Comment by harkiratsm** [comment]
As the issue hasn't been fixed lately, thank you for reopening it.

**Comment by heath-freenome** [comment]
Confirmed that the use case in this [playground link](https://discord.com/channels/@me/1018563369210482719/1080791477476671590) is not working
