### ISSUE TITLE
Playground: Any Of with Custom Field example and UI schema doesn't seem to work as it should

### ISSUE THREAD

**Issue by rap1ds** [rjsf-team/react-jsonschema-form#3235]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

other

### Version

5.x

### Current Behavior

In Playground, when you pick Any Of with Custom Field example, you see:

* Empty object in UISchema
* The rendered output in certain conditions is dropdown with options and in certain conditions custom component with city + lat/lng side by side

See screenshot

### Expected Behavior

* UISchema with custom field
* Rendered output is always a custom field with city and lat/lng side by side

### Steps To Reproduce

1. Go to Playground (https://rjsf-team.github.io/react-jsonschema-form/)
2. Pick Any Of with Custom Field example

Expected: UISchema with custom field, rendered output is the custom field, not dropdown with two options

Actual: UISchema is empty, rendered output is dropdown with two options

If I pick another example, I can see the custom field correctly rendered, but UI Schema is still empty. Steps:

1. Go to Playground (https://rjsf-team.github.io/react-jsonschema-form/)
2. Pick Any Of with Custom Field example
3. Now pick One of example
4. And then again pick Any Of with Custom Field example

Expected: UISchema with custom field, rendered output is the custom field, not dropdown of two options

Actual: UISchema is empty, rendered output is the custom field, not dropdown of two options

### Environment

```markdown
Playground with Google Chrome
```

### Anything else?

<img width="1362" alt="Screen Shot 2022-11-09 at 9 43 57" src="https://user-images.githubusercontent.com/429876/200770131-0aab9236-f0dd-4e3e-bf66-7d4734a1e037.png">

**Comment by heath-freenome** [comment]
@rap1ds WOW! That is a really interesting issue. It turns out that the `Any Of with Custom Field` example has a react component embedded in the `uiSchema` but the editor code doesn't know how to deal with it, therefore showing an empty `uiSchema`, which is saved into state. When you switch back the component is lost. We'll have to figure out how to fix it, eventually. Thanks!

**Comment by Nezteb** [comment]
I've also noticed that the "Any Of with Custom Field" example is weirdly broken:
<img width="1780" alt="CleanShot 2023-08-07 at 22 42 56@2x" src="https://github.com/rjsf-team/react-jsonschema-form/assets/3588798/1e13f846-dd11-4e23-a147-b37cd8161784">

The display on the right is incorrect. If you copy the schema, click on the "Simple" example, and paste the JSON, it will work properly:
<img width="1776" alt="CleanShot 2023-08-07 at 22 50 49@2x" src="https://github.com/rjsf-team/react-jsonschema-form/assets/3588798/76bd7481-e0ba-4e39-a14d-27687564048a">

**Comment by heath-freenome** [comment]
@Nezteb thanks for pointing that out! The custom field is what renders the latitude and longitude.
