### ISSUE TITLE
Second and further objects in anyOf get properties from the first object

### ISSUE THREAD

**Issue by kentlarsson** [rjsf-team/react-jsonschema-form#3236]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.0.0-beta.12

### Current Behavior

Keys in **anyOf**s first item seem to be added to any other item of an array.

### Expected Behavior

That each object in the anyOf only has their own properties.

### Steps To Reproduce

1. Go to my [Playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJjcmFmdFR5cGVzIjpbXX0sInNjaGVtYSI6eyJ0aXRsZSI6IlVGTyBTaWdodGluZ3MiLCJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsiY3JhZnRUeXBlcyJdLCJwcm9wZXJ0aWVzIjp7ImNyYWZ0VHlwZXMiOnsidHlwZSI6ImFycmF5IiwibWluSXRlbXMiOjEsInVuaXF1ZUl0ZW1zIjp0cnVlLCJ0aXRsZSI6IlR5cGUgb2YgVUZPIiwiaXRlbXMiOnsib25lT2YiOlt7InRpdGxlIjoiQ2lnYXIgU2hhcGVkIiwidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbImRheXNPZlllYXIiXSwicHJvcGVydGllcyI6eyJuYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IldoYXQgZG8geW91IGNhbGwgaXQ/In0sImRheXNPZlllYXIiOnsidHlwZSI6ImFycmF5IiwibWluSXRlbXMiOjEsInVuaXF1ZUl0ZW1zIjp0cnVlLCJ0aXRsZSI6IldoYXQgZGF5cyBvZiB0aGUgeWVhciBkaWQgeW91IHNlZSBpdD8iLCJpdGVtcyI6eyJ0eXBlIjoibnVtYmVyIiwidGl0bGUiOiJEYXkifX19fSx7InRpdGxlIjoiUm91bmQiLCJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsia2V5d29yZHMiXSwicHJvcGVydGllcyI6eyJ0aXRsZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJXaGF0IHNob3VsZCB3ZSBjYWxsIGl0PyJ9LCJrZXl3b3JkcyI6eyJ0eXBlIjoiYXJyYXkiLCJtaW5JdGVtcyI6MSwidW5pcXVlSXRlbXMiOnRydWUsInRpdGxlIjoiTGlzdCBvZiBrZXl3b3JkcyByZWxhdGVkIHRvIHRoZSBzaWdodGluZyIsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IktleXdvcmQifX19fV19fX19LCJ1aVNjaGVtYSI6eyJsaXN0T2ZTdHJpbmdzIjp7Iml0ZW1zIjp7InVpOmVtcHR5VmFsdWUiOiIifX0sIm11bHRpcGxlQ2hvaWNlc0xpc3QiOnsidWk6d2lkZ2V0IjoiY2hlY2tib3hlcyJ9LCJmaXhlZEl0ZW1zTGlzdCI6eyJpdGVtcyI6W3sidWk6d2lkZ2V0IjoidGV4dGFyZWEifSx7InVpOndpZGdldCI6InNlbGVjdCJ9XSwiYWRkaXRpb25hbEl0ZW1zIjp7InVpOndpZGdldCI6InVwZG93biJ9fSwidW5vcmRlcmFibGUiOnsidWk6b3B0aW9ucyI6eyJvcmRlcmFibGUiOmZhbHNlfX0sInVucmVtb3ZhYmxlIjp7InVpOm9wdGlvbnMiOnsicmVtb3ZhYmxlIjpmYWxzZX19LCJub1Rvb2xiYXIiOnsidWk6b3B0aW9ucyI6eyJhZGRhYmxlIjpmYWxzZSwib3JkZXJhYmxlIjpmYWxzZSwicmVtb3ZhYmxlIjpmYWxzZX19LCJmaXhlZE5vVG9vbGJhciI6eyJ1aTpvcHRpb25zIjp7ImFkZGFibGUiOmZhbHNlLCJvcmRlcmFibGUiOmZhbHNlLCJyZW1vdmFibGUiOmZhbHNlfX19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsInZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19)
2. Add a Cigar Shaped (the first item in the anyOf in the schema) UFO with a name (ex. oval) and a day (ex 1)
3. Add a Round UFO (the second item in the anyOf in the schema) UFO
4. Observe that `"daysOfYear": [ null ]` exists in the second craftTypes item of the formData. It should not as it's not part of that object.

### Environment

```markdown
- OS: Arch Linux
- Node: 16
- npm: 8
```

**Comment by heath-freenome** [comment]
@kentlarsson Ah, yeah, our oneOf logic doesn't seem to clear unnecessary fields. This seems similar to #2944 and it is likely that the fix I'm planning to do in the new year may also fix this

**Comment by kentlarsson** [comment]
Yes definitely looks like something that might be squashed in one go.
