### ISSUE TITLE
Is it possible to display field titles in validation error messages instead of real field names?

### ISSUE THREAD

**Issue by shijistar** [rjsf-team/react-jsonschema-form#3246]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### What is your question?

Is it possible to display field titles in validation error messages instead of real property names? Field titles may be clearer to users.
If I have to replace the property name in `transformErrors`, then how to get the field title from the validation error object?

<img width="837" alt="image" src="https://user-images.githubusercontent.com/3147149/201810199-13a75d01-4bb8-47df-b76a-7de13cd87863.png">

**Comment by ademgashi** [comment]
+1

**Comment by cdolek** [comment]
+1

**Comment by dagda1** [comment]
This would be excellent, displaying the field name or using `transformErrors` means a lot of extra coding on every form to get decent error messages.  Using the title would definitely solve this

**Comment by heath-freenome** [comment]
@dagda1 @shijistar @ademgashi There is an OLD PR (#2634) that would fix this, but it is built on top of the earlier 4.x release. The code itself needs to be refactored on top of all the changes made in 5.x. If someone were to redo the code in the PR we'd be willing to merge it

**Comment by dagda1** [comment]
@heath-freenome I am having a look at this now. 

What do you think would be the best approach in the `validator-ajv8` package?

The errors coming back from `rawValidation`  look like this:

```ts
[
   {
      instancePath: '',
      schemaPath: '#/required',
      keyword: 'required',
      params: { missingProperty: 'lastName' },
       message: "must have required property 'lastName'"
    }
]
```
We would somehow need to change the `message` in `transformRJSFValidationErrors` where we would need access to the schema.

It looks like constructing the `message` can only be done after the ajv validation, and all I can think of is doing a string replace with the title (if it exists in the schema).

I've had a really rough hack and would something like this work for `transformRJSFValidationErrors`:

```ts
private transformRJSFValidationErrors(
  schema: S,
  errors: ErrorObject[] = []
): RJSFValidationError[] {
  return errors.map((e: ErrorObject) => {
    const { instancePath, keyword, params, schemaPath, ...rest } = e;
    let { message } = rest;

    
    let property = instancePath.replace(/\//g, ".");
    
    let stack = `${property} ${message}`.trim();
    if ("missingProperty" in params) {
      property = property
      ? `${property}.${params.missingProperty}`
      : params.missingProperty;
      
      const properties = schema?.properties?.[property] as RJSFSchema | undefined;
      
      if (message && properties?.title) {
        message = message.replace(property, properties.title);

      }
      stack = message!;
    }

    // put data in expected format
    return {
      name: keyword,
      property,
      message,
      params, // specific to ajv
      stack,
      schemaPath,
    };
  });
}
```

I'm not over the moon about a string replace, is there a better way?

**Comment by dagda1** [comment]
> @dagda1 @shijistar @ademgashi There is an OLD PR (#2634) that would fix this, but it is built on top of the earlier 4.x release. The code itself needs to be refactored on top of all the changes made in 5.x. If someone were to redo the code in the PR we'd be willing to merge it

@heath-freenome I am having a look at this now. 

What do you think would be the best approach in the `validator-ajv8` package?

The errors coming back from `rawValidation`  look like this:

```ts
[
   {
      instancePath: '',
      schemaPath: '#/required',
      keyword: 'required',
      params: { missingProperty: 'lastName' },
       message: "must have required property 'lastName'"
    }
]
```
We would somehow need to change the `message` in `transformRJSFValidationErrors` where we would need access to the schema.

I have had a rough hack as a means of getting some feedback.  I'm not familiar with the codebase but would something like this work?  I'm really not liking the string replace on the message, but I do not know a better way:

```ts
  private transformRJSFValidationErrors(
    schema: S,
    errors: ErrorObject[] = []
  ): RJSFValidationError[] {
    return errors.map((e: ErrorObject) => {
      const { instancePath, keyword, params, schemaPath, ...rest } = e;
      let { message } = rest;
      
      let property = instancePath.replace(/^\//g, "").replace(/\//g, ".");
      let stack = `${property} ${message}`.trim();


      if ("missingProperty" in params) { 
        property = property
          ? `${property}.${params.missingProperty}`
          : params.missingProperty;

        const paths = property.split('.');
        const titlePath= paths.map((p, i) => i !== paths.length - 1 ? `${p}.${PROPERTIES_KEY}.` : `${p}.title`).join('');
        
        const title = get(schema, `${PROPERTIES_KEY}.${titlePath}`);
        
        if (title) {
          message = message?.replace(property.split('.').slice(-1)[0], title);
        }

        stack = message!;
      }

      // put data in expected format
      return {
        name: keyword,
        property,
        message,
        params, // specific to ajv
        stack,
        schemaPath,
      };
    });
  }
```

Any feedback at all appreciated.
