### ISSUE TITLE
ajv8 does not properly show errors inline under certain circumstances when ajv6 does

### ISSUE THREAD

**Issue by cdolek** [rjsf-team/react-jsonschema-form#3260]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### What is your question?

With `ajv6` the form errors (e.g. required properties) were displayed right under the form elements, which is very helpful especially when you use live validation. 

While `ajv8` validation marks form elements as invalid, error messages show up below the whole form. The longer the form, the higher chance of error messages being displayed outside users' view === bad user experience. 

I would like the error messages to be shown right below the form elements. Is there a way to achieve this?

What I noticed is that `rawErrors` is not being passed to the individual form element using v8.

Help appreciated.

**Comment by cdolek** [comment]
@heath-freenome any insights on this? Thank you

**Comment by heath-freenome** [comment]
Hmmm, this may be a bug related to subtle differences between ajv6 and ajv8. Do you have a reproducible test case?

**Comment by cdolek** [comment]
@heath-freenome check this out: https://codesandbox.io/s/nifty-breeze-rtd9vs?file=/src/App.tsx

**Comment by heath-freenome** [comment]
Here it is inside of the [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6ImFqdjYiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0ZXh0RmllbGQiOnsidGl0bGUiOiJUZXh0IGZpZWxkIiwidHlwZSI6InN0cmluZyJ9LCJhcnJheU9mU3RyaW5ncyI6eyJ0aXRsZSI6IkFycmF5IG9mIHN0cmluZ3MiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIn19LCJhcnJheU9mQXJyYXlPZlN0cmluZ3MiOnsidGl0bGUiOiJBcnJheSBvZiBhcnJheSBvZiBzdHJpbmdzIiwidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidHlwZSI6InN0cmluZyJ9fX19LCJyZXF1aXJlZCI6WyJ0ZXh0RmllbGQiLCJhcnJheU9mU3RyaW5ncyIsImFycmF5T2ZBcnJheU9mU3RyaW5ncyJdfSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiIsInVpOmF1dG9jb21wbGV0ZSI6ImZhbWlseS1uYW1lIn0sImxhc3ROYW1lIjp7InVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJnaXZlbi1uYW1lIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

**Comment by nickgros** [comment]
It looks like the Ajv raw errors for missing required properties doesn't point to the property, but to the object containing the `required` property in the schema. We may have to manually create the path in an error transform.

**Comment by heath-freenome** [comment]
> It looks like the Ajv raw errors for missing required properties doesn't point to the property, but to the object containing the `required` property in the schema. We may have to manually create the path in an error transform.

Hopefully this is a fix in `transformRJSFValidationErrors()` in validator-ajv8 `validator.ts`

**Comment by dagda1** [comment]
@heath-freenome  Thank you for the reply, will that fix include the specific error in this issue, i.e. if I pass the initial form state with `undefined`, values, e.g.

```json
{name: undefined, description: undefined, owner: undefined}
```

I don't get validation errors but if they have values, I get the validation messages, e.g.

```json
{name:'', description: '', owner: ''}
```
