### ISSUE TITLE
How do I adjust the layout of specific form fields using Custom Templates within uiSchema?

### ISSUE THREAD

**Issue by matburnham** [rjsf-team/react-jsonschema-form#3261]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

mui

### What is your question?

I'm having a bit of trouble understanding how to adjust the layout of form items, specifically inlining of fields. Quite a few issues here relate:
* #1344 
* #1551
* #2070
* #2108

Most solutions point to using ObjectFieldTemplate, etc. but I'm struggling to get this to work in conjunction with uiSchema. Once I'd found it, the documentation for [uiSchema](https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/uiSchema/) is good, but doesn't seem to cover this scenario. I've tried to implement it in this [JSFiddle](https://jsfiddle.net/eyLtwzud/) through guesswork.

Specifically:

```js
const uiSchema = {
  // I can override globally within the uiSchema:
  // "ui:ObjectFieldTemplate" : ObjectFieldTemplate,
  // (it will only act on simple as the others are arrays not objects)

  // But attempting to do the same to a specific object doesn't work
  simple: {
    "ui:ObjectFieldTemplate" : ObjectFieldTemplate,
  },

  // It feels like that should work, as one can successfully hide a similar field
  hidden: {
    "ui:widget": "hidden"
  },
};
```

I continue in the [JSFiddle](https://jsfiddle.net/eyLtwzud/) to try and do it with the array field, but once I can override a simple object field, it may become clearer.

StackOverflow [Multi column support for react-jsonschema-form](https://stackoverflow.com/questions/64529750/multi-column-support-for-react-jsonschema-form) also describes some ways of doing this, but globally not via uiSchema.

Am I missing something obvious? Is there a better way to achieve what I'm trying to do? (Inlining MUI theme fields in the first instance, but greater customisation of formatting in due course.)

**Comment by nickgros** [comment]
@matburnham 
In your JSFiddle, the `simple` property is a string, not an object, so overriding `ObjectFieldTemplate` won't do anything. I'm not understanding exactly what you want to do with your array field, but you probably want to override the `ui:ArrayFieldTemplate` with an ArrayFieldTemplate override.

**Comment by heath-freenome** [comment]
There is a PR #2597 that should get you closer.

**Comment by matburnham** [comment]
> the `simple` property is a string, not an object, so overriding `ObjectFieldTemplate` won't do anything.

Ah, you had me for a second saying `simple` wasn't an object. I was thinking of course it's a JS object what are you on about. Pointer in the right direction - many thanks!

```js
const schema = {
  ...
  properties: {
    simple: { type: "string", title: "Simple"},
  ...
```
But yes, replacing it with now has the effect I expected. (New [JSFiddle](https://jsfiddle.net/dgvhmw07/))

```js
const schema = {
  ...
  properties: {
    simple: { type: "object", properties: 
      { "id": { type: "string", title: "Simple" } }
  ...
```

ArrayFieldTemplate hint has also put me on the right track. Now succesfully overriding in another [JSFiddle](https://jsfiddle.net/dgvhmw07/2/).

```js
const uiSchema = {
  ...
  array: {
    'ui:ArrayFieldTemplate': ArrayFieldTemplate,
  ...
```

**Comment by heath-freenome** [comment]
So, is there anything else or can we close this issue?

**Comment by matburnham** [comment]
I was going to summarise the final resolution to my original issue - inlining form fields - in case it's useful to others. But it turns out it boils down to overriding `ObjectFieldTemplate` in the uiSchema rather than ArrayFieldTemplate or ArrayFieldItemTemplate:

```js
export const uiSchema = {
  array: {
    "ui:ObjectFieldTemplate" : ObjectFieldTemplate,
  ...
```
I took [ObjectFieldTemplate.tsx](https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/mui/src/ObjectFieldTemplate/ObjectFieldTemplate.tsx) and changed the `xs={12}` entry to `xs={3}` to allow space for four entries:

```diff
            <Grid
              item={true}
-              xs={12}
+              xs={3}
              key={index}
              style={{ marginBottom: "10px" }}
            >
              {element.content}
            </Grid>
```

You could probably do it on an individual item basis (so long as you don't come a cropper of the 'not and object' object as above) but I didn't get that far.
