### ISSUE TITLE
Documentation for unpkg is incorrect

### ISSUE THREAD

**Issue by hughjdavey** [rjsf-team/react-jsonschema-form#3262]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

mui

### Version

^4.1.1 locally but latest on the JSFiddle - https://jsfiddle.net/mdeazLy3/1/

### Current Behavior

Error stacks are being truncated if a custom validation function is used, even if the function doesn't modify the `errors` object

### Expected Behavior

Error stacks should stay the same

### Steps To Reproduce

See this JSFiddle - https://jsfiddle.net/mdeazLy3/1/

- Create a form with a schema
- Look at the error list
- Add a custom validate function
- Look at the error list again and see the stacks are truncated

### Environment

```markdown
- OS: Windows 10
- Node: 16.x.x
- npm: 8.x.x
```

### Anything else?

Form on the right has a custom validate function that does nothing (just returns `errors` as per [the docs](https://react-jsonschema-form.readthedocs.io/en/docs/usage/validation/#custom-validation-rules)). The forms share a schema. To see the schema and the forms please see the JSFiddle here - https://jsfiddle.net/mdeazLy3/1/

![image](https://user-images.githubusercontent.com/9026053/204519055-e9b86c39-ab18-405b-820e-3ed8a730ebbf.png)

**Comment by heath-freenome** [comment]
Can you update your fiddle to use the latest `@rjsf/core` package instead of the ancient (and no longer supported) `react-jsonschema-form` and let me know if this is still a problem?

**Comment by hughjdavey** [comment]
@heath-freenome Can you point me to the URL I need? I tried to use the one from [the docs](https://react-jsonschema-form.readthedocs.io/en/latest/#as-a-script-served-from-a-cdn) - https://unpkg.com/@rjsf/core/dist/react-jsonschema-form.js -but it doesn't seem to exist

![image](https://user-images.githubusercontent.com/9026053/205915845-ab8db52e-1edb-4be5-8fc1-3fca660458be.png)

**Comment by heath-freenome** [comment]
Can you try using `npm install @rjsf/core@5.0.0-beta.13`? I am not sure we push to unpkg.com anymore

**Comment by hughjdavey** [comment]
Well it looks like the file `react-jsonschema-form.js` is no longer in your packages. [unpkg.com](https://unpkg.com/) allows you to access a fille from npm with the syntax `unpkg.com/:package@:version/:file` and, for example, https://unpkg.com/@rjsf/core@5.0.0-beta.13/dist/core.cjs.production.min.js works. Just the https://unpkg.com/@rjsf/core/dist/react-jsonschema-form.js mentioned in [the docs](https://react-jsonschema-form.readthedocs.io/en/latest/#as-a-script-served-from-a-cdn) doesn't. I looked into the `@rjsf/core@5.0.0-beta.13` using [runpkg](https://www.runpkg.com) and indeed the file is no longer there:

![image](https://user-images.githubusercontent.com/9026053/206234448-80f06ec3-f334-4fb6-8e82-314b433ea780.png)

So should I just use `core.cjs.production.min.js` instead?

**Comment by heath-freenome** [comment]
So we have a doc issue to fix... and yes use that one instead

**Comment by hughjdavey** [comment]
Just tried to reproduce in CodePen and you're right it doesn't happen in `5.0.0-beta.13`. But yeh you're right about the doc issue - the CDM instructions don't work anymore. I managed to get it working with [Skypack](https://www.skypack.dev) in my CodePen - you can do

`import Form from "https://cdn.skypack.dev/@rjsf/core@5.0.0-beta.13";`

which works well. [Here is the CodePen](https://codepen.io/hughjdavey/pen/BaVEope) if you are interested,. Thanks for your time with this.

**Comment by heath-freenome** [comment]
Fixed the doc issue with #3288
