### ISSUE TITLE
<title> Would it be possible to incorperate a wysiwyg field option? </title>

### ISSUE THREAD

**Issue by shammyb** [rjsf-team/react-jsonschema-form#3286]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### Describe the solution you'd like

"format": "HTML",
                "options": {
                  "wysiwyg": true
                }
This should enable users to insert html into a field like wysiwyg does

**Comment by heath-freenome** [comment]
@shammyb what do you mean like `wysiwyg` does? Can you please add more context?

**Comment by shammyb** [comment]
so wysiwyg lets you create bold , underlined text and a few other features, for example if i wanted something like this to be on a json 'text text <b>bold text</b> text'  it would make it intuitive to the user with a bar of options at the top similar to the screenshot attached to customise their own text and push it to the created json.
<img width="854" alt="Screenshot 2022-12-08 at 10 53 24" src="https://user-images.githubusercontent.com/73183234/206428819-1d82cb69-9ae8-4a3c-8e30-bb27dee0c548.png">

**Comment by heath-freenome** [comment]
@shammyb I see. There are no plans to incorporate this directly into the product. You are can create a (set of) [custom widget(s)](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/) and or [template(s)](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-templates/) to do this yourself.
