### ISSUE TITLE
Build fails on Vercel

### ISSUE THREAD

**Issue by toledoroy** [rjsf-team/react-jsonschema-form#3289]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

material-ui

### Version

5.0.0-beta.13

### Current Behavior

Hi
Trying to deploy my app on Vercel and the build is failing, even with the --force. 
Updated to V5 beta, but still having the same issues as some parts of MUI 4 are still loading even though I'm using MUI 5.
Any ideas how can I resolve this?

> 19:11:08.384 | npm ERR! ERESOLVE could not resolve
> 19:11:08.385 | npm ERR!
> 19:11:08.385 | npm ERR! While resolving: @material-ui/core@4.12.4
> 19:11:08.385 | npm ERR! Found: @types/react@18.0.15
> 19:11:08.385 | npm ERR! node_modules/@types/react
> 19:11:08.386 | npm ERR!   dev @types/react@"18.0.15" from the root project
> 19:11:08.386 | npm ERR!   peerOptional @types/react@"*" from @material-ui/types@5.1.0
> 19:11:08.386 | npm ERR!   node_modules/@material-ui/types
> 19:11:08.386 | npm ERR!     @material-ui/types@"5.1.0" from @material-ui/core@4.12.4
> 19:11:08.386 | npm ERR!     node_modules/@material-ui/core
> 19:11:08.386 | npm ERR!       peer @material-ui/core@"^4.0.0" from @material-ui/icons@4.11.3
> 19:11:08.387 | npm ERR!       node_modules/@material-ui/icons
> 19:11:08.387 | npm ERR!         peer @material-ui/icons@"^4.11.2" from @rjsf/material-ui@5.0.0-beta.13
> 19:11:08.387 | npm ERR!         node_modules/@rjsf/material-ui
> 19:11:08.387 | npm ERR!       1 more (@rjsf/material-ui)
> 19:11:08.387 | npm ERR!     @material-ui/types@"5.1.0" from @material-ui/styles@4.11.5
> 19:11:08.388 | npm ERR!     node_modules/@material-ui/core/node_modules/@material-ui/styles
> 19:11:08.388 | npm ERR!       @material-ui/styles@"^4.11.5" from @material-ui/core@4.12.4
> 19:11:08.388 | npm ERR!       node_modules/@material-ui/core
> 19:11:08.388 | npm ERR!         peer @material-ui/core@"^4.0.0" from @material-ui/icons@4.11.3
> 19:11:08.388 | npm ERR!         node_modules/@material-ui/icons
> 19:11:08.388 | npm ERR!         1 more (@rjsf/material-ui)
> 19:11:08.389 | npm ERR!   10 more (@mui/base, @mui/icons-material, @mui/lab, @mui/material, ...)
> 19:11:08.389 | npm ERR!
> 19:11:08.389 | npm ERR! Could not resolve dependency:
> 19:11:08.389 | npm ERR! peerOptional @types/react@"^16.8.6 \|\| ^17.0.0" from @material-ui/core@4.12.4
> 19:11:08.390 | npm ERR! node_modules/@material-ui/core
> 19:11:08.391 | npm ERR!   peer @material-ui/core@"^4.0.0" from @material-ui/icons@4.11.3
> 19:11:08.391 | npm ERR!   node_modules/@material-ui/icons
> 19:11:08.391 | npm ERR!     peer @material-ui/icons@"^4.11.2" from @rjsf/material-ui@5.0.0-beta.13
> 19:11:08.391 | npm ERR!     node_modules/@rjsf/material-ui
> 19:11:08.392 | npm ERR!       @rjsf/material-ui@"^5.0.0-beta.13" from the root project
> 19:11:08.392 | npm ERR!   peer @material-ui/core@"^4.12.3" from @rjsf/material-ui@5.0.0-beta.13
> 19:11:08.392 | npm ERR!   node_modules/@rjsf/material-ui
> 19:11:08.392 | npm ERR!     @rjsf/material-ui@"^5.0.0-beta.13" from the root project
> 19:11:08.392 | npm ERR!
> 19:11:08.392 | npm ERR! Conflicting peer dependency: @types/react@17.0.52
> 19:11:08.392 | npm ERR! node_modules/@types/react
> 19:11:08.393 | npm ERR!   peerOptional @types/react@"^16.8.6 \|\| ^17.0.0" from @material-ui/core@4.12.4
> 19:11:08.393 | npm ERR!   node_modules/@material-ui/core
> 19:11:08.393 | npm ERR!     peer @material-ui/core@"^4.0.0" from @material-ui/icons@4.11.3
> 19:11:08.393 | npm ERR!     node_modules/@material-ui/icons
> 19:11:08.393 | npm ERR!       peer @material-ui/icons@"^4.11.2" from @rjsf/material-ui@5.0.0-beta.13
> 19:11:08.393 | npm ERR!       node_modules/@rjsf/material-ui
> 19:11:08.394 | npm ERR!         @rjsf/material-ui@"^5.0.0-beta.13" from the root project
> 19:11:08.394 | npm ERR!     peer @material-ui/core@"^4.12.3" from @rjsf/material-ui@5.0.0-beta.13
> 19:11:08.394 | npm ERR!     node_modules/@rjsf/material-ui
> 19:11:08.394 | npm ERR!       @rjsf/material-ui@"^5.0.0-beta.13" from the root project
> 19:11:08.394 | npm ERR!
> 19:11:08.394 | npm ERR! Fix the upstream dependency conflict, or retry
> 19:11:08.394 | npm ERR! this command with --force, or --legacy-peer-deps
> 19:11:08.395 | npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> 19:11:08.395 | npm ERR!

Here's the package.json

> 
> "dependencies": {
>     "@apollo/client": "^3.7.1",
>     "@emotion/react": "^11.10.5",
>     "@emotion/styled": "^11.10.5",
>     "@mui/icons-material": "^5.10.16",
>     "@mui/lab": "^5.0.0-alpha.91",
>     "@mui/material": "^5.10.16",
>     "@mui/x-data-grid": "^5.17.14",
>     "@rjsf/core": "^4.2.3",
>     "@rjsf/material-ui": "^5.0.0-beta.13",
>     "@walletconnect/web3-provider": "^1.8.0",
>     "axios": "^0.27.2",
>     "ethers": "^5.7.2",
>     "graphql": "^16.6.0",
>     "ipfs-http-client": "^57.0.3",
>     "lodash": "^4.17.21",
>     "next": "12.2.2",
>     "nextjs-progressbar": "^0.0.14",
>     "notistack": "^2.0.8",
>     "react": "18.2.0",
>     "react-dom": "18.2.0",
>     "styled-components": "^5.3.6",
>     "validate.io-number": "^1.0.3",
>     "web3modal": "^1.9.10"
>   },
> 

### Expected Behavior

Using only MUI 5

### Environment

```markdown
Using Next.js
```

**Comment by heath-freenome** [comment]
You need to use ALL of the v5 beta, not just some of it, so update your `package.json` to look like:
```
"dependencies": {
"@apollo/client": "^3.7.1",
"@emotion/react": "^11.10.5",
"@emotion/styled": "^11.10.5",
"@mui/icons-material": "^5.10.16",
"@mui/lab": "^5.0.0-alpha.91",
"@mui/material": "^5.10.16",
"@mui/x-data-grid": "^5.17.14",
"@rjsf/core": "^5.0.0-beta.13",
"@rjsf/material-ui": "^5.0.0-beta.13",
"@rjsf/utils": "^5.0.0-beta.13",
"@rjsf/validator-ajv6": "^5.0.0-beta.13",
"@walletconnect/web3-provider": "^1.8.0",
"axios": "^0.27.2",
"ethers": "^5.7.2",
"graphql": "^16.6.0",
"ipfs-http-client": "^57.0.3",
"lodash": "^4.17.21",
"next": "12.2.2",
"nextjs-progressbar": "^0.0.14",
"notistack": "^2.0.8",
"react": "18.2.0",
"react-dom": "18.2.0",
"styled-components": "^5.3.6",
"validate.io-number": "^1.0.3",
"web3modal": "^1.9.10"
},
```

Follow the [migration guide](https://react-jsonschema-form.readthedocs.io/en/latest/5.x%20upgrade%20guide/) to update your app to use v5

**Comment by toledoroy** [comment]
I see.
Thanks!
