### ISSUE TITLE
Form not rendering when allOf and dependencies fields used in schema

### ISSUE THREAD

**Issue by cwendtxealth** [rjsf-team/react-jsonschema-form#3291]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

4.2.3

### Current Behavior

When loading a form with a schema using allOf property and dependencies, the window freezes and console errors with "could not merge subschemas in allOf: RangeError: Maximum call stack size exceeded"

Simple Schema:
```json
{
  "type": "object",
  "title": "Test allof dependencies bug",
  "properties": {
      "Field One": {
          "title": "Field One",
          "type": "string",
          "enum": [
              "Option 1",
              "Option 2"
          ]
      },
      "Field Two": {
          "title": "Field 2",
          "type": "string",
          "enum": [
              "Option 3",
              "Option 4"
          ]
      }
  },
  "allOf": [
      {
          "if": {
              "properties": {
                  "Field One": {
                      "const": "Option 1"
                  }
              }
          },
          "then": {
              "properties": {
                  "Field Two": {
                      "type": "string",
                      "enum": [
                          "Option 4"
                      ]
                  }
              },
              "required": [
                  "Field Two"
              ]
          }
      }
  ],
  "dependencies": {
      "Field Two": {
          "oneOf": [
              {
                  "properties": {
                      "Field Two": {
                          "enum": [
                              "Option 3"
                          ]
                      },
                      "New Field": {
                          "title": "New Field",
                          "type": "string"
                      }
                  },
                  "required": [
                      "New Field"
                  ]
              },
              {
                  "properties": {
                      "Field Two": {
                          "enum": [
                              "Option 4"
                          ]
                      }
                  }
              }
          ]
      }
  },
  "required": [
      "Field One",
      "Field Two"
  ]
}
```
Sample [JS Fiddle](https://jsfiddle.net/7dzbp8ty/) using v4.2.3

### Expected Behavior

The form to load with schema, this schema currently works with 5.x version.

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by heath-freenome** [comment]
@cwendtxealth You wrote: "this schema currently works with 5.x version." so the latest software should solve your problem. Since the fix for the issue in 5.x is not easily back-ported due to the large number of changes in the relevant code, upgrading to 5.x will solve your problem.

**Comment by cwendtxealth** [comment]
> @cwendtxealth You wrote: "this schema currently works with 5.x version." so the latest software should solve your problem. Since the fix for the issue in 5.x is not easily back-ported due to the large number of changes in the relevant code, upgrading to 5.x will solve your problem.

Since the latest 5.x has not been officially released and still in beta, I just wanted to make sure the bug was documented. Looking forward to the release of v5.0.0!
