### ISSUE TITLE
Boolean/Checkbox missing Title in Semantic-ui

### ISSUE THREAD

**Issue by mmcgurn** [rjsf-team/react-jsonschema-form#3302]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

semantic-ui

### Version

5.0.0-beta.14

### Current Behavior

When using Semantic-ui and the default checkbox for boolean there is not title with the checkbox.  
<img width="761" alt="image" src="https://user-images.githubusercontent.com/75279702/208322098-1f70c5b1-36ea-4e39-8531-e8db330c85b4.png">

### Expected Behavior

I would expect there to be a title like the other themes (shown in example is default theme).
<img width="761" alt="image" src="https://user-images.githubusercontent.com/75279702/208322133-bb0a4830-ee27-47da-8098-4b5f0ad0138d.png">

### Steps To Reproduce

It can be reproduced in the playground,
https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6ZmFsc2UsInNjaGVtYSI6eyJ0aXRsZSI6IkEgc2luZ2xlLWZpZWxkIGZvcm0iLCJkZXNjaXB0aW9uIjoiQSBzaW5nbGUtZmllbGQgZm9ybSIsInR5cGUiOiJib29sZWFuIn0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJzZW1hbnRpYy11aSIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=

**Comment by heath-freenome** [comment]
@jacqueswho This looks like a quick fix. The use of the `getDisplayLabel()` code is wrong here since it returns false for boolean fields and this wants a label. Can you fix?
