### ISSUE TITLE
formData definition in types should support undefined as a valid value

### ISSUE THREAD

**Issue by dagda1** [rjsf-team/react-jsonschema-form#3305]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

In versions before `5.0.0-beta.*`, if the`<Form />` was given a schema like this:

```ts
{
  properties: {
    repository: {
      type: "object"
    }
  }
}
```

The form component would call `getStateFromProps` which would, in turn, call `computeDefaults` and return:

```ts
{
  repository: {}
}
```

This would allow `getDefaultFormState` to initialise the form correctly.

The code in `computeDefaults` in `v5.0.0-beta.*` has an `isEmpty` check, meaning non-empty objects will not get initialised correctly, and `formData` will be `{}`.

The knock-on effect of that is that this code in `ObjectField` will return undefined for the formData:

```ts
        return {
          content: (
            <SchemaField
              formData={get(formData, name)}  // undefined
```

Any `ui:field` will receive `undefined` for the initial `formData`

### Expected Behavior

`formData` should at least initialise to an empty object.

### Steps To Reproduce

I created a failing test [here](https://github.com/dagda1/react-jsonschema-form/commit/bfa034f7e4514c9413bdb6b675db44c64e3829ba).

### Environment

```markdown
- OS:osx
- Node:16
- npm:8
```

**Comment by heath-freenome** [comment]
@dagda1 Were you depending on that behavior? Many people had been complaining that this behavior was, in fact, a bug and so it was fixed in #3287. If we provided an `opt-in` flag that would let you choose to initialize top-level objects as an empty object would that help?

Also, there is also a big issue (#2980) that indicates our automatically saving defaulting values in the formData is an actual bug itself, and that we should not do so ever.

**Comment by dagda1** [comment]
@heath-freenome  apologies, I totally missed this reply. 

The codebase we are using is still on `3.2.0`, so an opt-in flag would be great to do the initial version bump.

**Comment by benjdlambert** [comment]
@heath-freenome me and @dagda1 discussed this a little bit, and we're happy that the behaviour is fine. However we noticed that the types for `FieldProps` could maybe do with updating? Just wanted to bring this to your attention before you cut a v5 release as I think it would be a breaking change. Seen as it now uses `get` and doesn't default, should `formData` this be optional?

```ts
interface FieldProps<T = any, S extends StrictRJSFSchema = RJSFSchema, F extends FormContextType = any> extends GenericObjectType, Pick<React.HTMLAttributes<HTMLElement>, Exclude<keyof React.HTMLAttributes<HTMLElement>, "onBlur" | "onFocus" | "onChange">> {
    /** The data for this field */
    formData: T;
```

**Comment by heath-freenome** [comment]
Thoughts @nickgros @epicfaace ?

**Comment by heath-freenome** [comment]
> @heath-freenome me and @dagda1 discussed this a little bit, and we're happy that the behaviour is fine. However we noticed that the types for `FieldProps` could maybe do with updating? Just wanted to bring this to your attention before you cut a v5 release as I think it would be a breaking change. Seen as it now uses `get` and doesn't default, should `formData` this be optional?
> 
> ```ts
> interface FieldProps<T = any, S extends StrictRJSFSchema = RJSFSchema, F extends FormContextType = any> extends GenericObjectType, Pick<React.HTMLAttributes<HTMLElement>, Exclude<keyof React.HTMLAttributes<HTMLElement>, "onBlur" | "onFocus" | "onChange">> {
>     /** The data for this field */
>     formData: T;
> ```

Good catch. I will be pushing a PR against this issue to fix `formData` to support `undefined` everywhere

**Comment by dagda1** [comment]
> Good catch. I will be pushing a PR against this issue to fix `formData` to support `undefined` everywhere

Great!  Thank you
