### ISSUE TITLE
persian datepicker

### ISSUE THREAD

**Issue by slhasadi** [rjsf-team/react-jsonschema-form#3308]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### What is your question?

hey guys i want to use persian datepicker(jalali) insted of georgian can anyone help me?

**Comment by heath-freenome** [comment]
You are welcome to write a custom version of the date picker widget for yourself.  Follow the [instructions](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/#adding-your-own-custom-widgets) for building custom widgets.

**Comment by slhasadi** [comment]
i use a datepicker(jalali) but i have error when i submit form `must be string`

**Comment by slhasadi** [comment]
> You are welcome to write a custom version of the date picker widget for yourself. Follow the [instructions](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/#adding-your-own-custom-widgets) for building custom widgets. Out of the box we are just using the date picker that comes with the browser. Have you tried switching your browser locale to `IR`?

no i just use the presian datepicker
i use a datepicker(jalali) but i have error when i submit the form must be string

**Comment by heath-freenome** [comment]
It seems like that date picker may be returning a Date object rather than converting it to a UTC string
