### ISSUE TITLE
<title>Size of input box

### ISSUE THREAD

**Issue by guilherme-funchal** [rjsf-team/react-jsonschema-form#3312]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

material-ui

### What is your question?

Hello, How can I set size to small in "TextField" widgets ?

Im trying to use size="small" but it doesn't working.

**Comment by heath-freenome** [comment]
@guilherme-funchal if you were to override the `BaseInputTemplate` in your code to wrap the material-ui `BaseInputTemplate` implementation, then you would be able to solve this issue. Something like (note you may have to make changes until this works as this is closer to pseudo-code than working code):

```
import { Templates } from '@rjsf/material-ui';

const { BaseInputTemplate } = Templates;

const MyBaseInputTemplate = (props: WidgetProps) => {
  return (
    <BaseInputTemplate
      {...props}
      size="small"
    />
  );
};
```

And then in your form override the `BaseInputTemplate` to use yours, something like:

```
<Form schema={schema} validator={validator} templates={{ BaseInputTemplate: MyBaseInputTemplate }} />
```

**Comment by desuraghu13** [comment]
Above solution is not working. Any idea how to change the input size to small without overriding the BaseInputTemplate ?
