### ISSUE TITLE
Chakra-ui package has missing dependencies

### ISSUE THREAD

**Issue by alexkreidler** [rjsf-team/react-jsonschema-form#3313]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

chakra-ui

### Version

5.x

### Current Behavior

When I install `@rjsf/chakra-ui` using PNPM, I get the following error:

```
✘ [ERROR] Could not resolve "@rjsf/utils"

    node_modules/.pnpm/@rjsf+chakra-ui@5.0.0-beta.15_ihuu76oscbxovuat5af2uqbf4u/node_modules/@rjsf/chakra-ui/dist/chakra-ui.esm.js:6:185:
      6 │ ...RTY_FLAG, parseDateString, toDateString, pad, rangeSpec, processSelectValue } from '@rjsf/utils';
        ╵                                                                                       ~~~~~~~~~~~~~

  You can mark the path "@rjsf/utils" as external to exclude it from the bundle, which will remove
  this error.

✘ [ERROR] Could not resolve "chakra-react-select"

    node_modules/.pnpm/@rjsf+chakra-ui@5.0.0-beta.15_ihuu76oscbxovuat5af2uqbf4u/node_modules/@rjsf/chakra-ui/dist/chakra-ui.esm.js:7:23:
      7 │ import { Select } from 'chakra-react-select';
        ╵                        ~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "chakra-react-select" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "@rjsf/utils"

    node_modules/.pnpm/@rjsf+core@5.0.0-beta.15_react@18.2.0/node_modules/@rjsf/core/dist/core.esm.js:2:547:
      2 │ ...uldRender, isObject as isObject$1, RJSF_ADDITONAL_PROPERTIES_FLAG, NAME_KEY } from '@rjsf/utils';
        ╵                                                                                       ~~~~~~~~~~~~~

  You can mark the path "@rjsf/utils" as external to exclude it from the bundle, which will remove
  this error.
```

### Expected Behavior

`@rjsf/utils` and `chakra-react-select` are properly declared as dependencies or peerDependencies of the `@rjsf/chakra-ui` package, so PNPM installs them, makes them available to the needed code, and my bundler doesn't complain.

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by heath-freenome** [comment]
@alexkreidler If you look at the [peer dependencies](https://github.com/rjsf-team/react-jsonschema-form/blob/ff034df8f6b7080bf76b7f25e0b1f400fbc818e5/packages/chakra-ui/package.json#L32) for `chakra-ui` you'll see that the two packages you've mentioned in your issue, are in fact there. I'm not sure if `PNPM` automatically installs peer dependencies, but I do know that `NPM` does not. Can't you just install them yourself?

```
  "peerDependencies": {
    "@chakra-ui/icons": ">=1.1.1",
    "@chakra-ui/react": ">=1.7.3",
    "@rjsf/core": "^5.0.0-beta.1",
    "@rjsf/utils": "^5.0.0-beta.1",
    "chakra-react-select": ">=3.3.8",
    "framer-motion": ">=5.6.0",
    "react": "^16.14.0 || >=17"
  },
```
