### ISSUE TITLE
Pass index, canAdd, length of array to ArrayFieldItemTemplate

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#3315]

**Comment by heath-freenome** [comment]
@epicfaace we are already passing `index` to the `ArrayFieldTemplateItemType`. `canAdd` is actually being passed as a prop, but was missing in the type (will add it). I can also see a use for adding `totalItems` to that as well

**Comment by epicfaace** [comment]
> Are you imagining a use where each item might, instead have an add button?

Yep that's actually my use case! I need the add and remove buttons on the same row -- currently doing it via a hacky solution but these props will make it much easier.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/1689183/209870933-8a7e78c9-d73f-4702-aa6d-ad5ac81d20fa.png">
