### ISSUE TITLE
Custom Templates documentation wrong for 5.x

### ISSUE THREAD

**Issue by matburnham** [rjsf-team/react-jsonschema-form#3321]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

mui

### Version

5.x

### Current Behavior

Having just spent a good while trying to understand why my custom templates weren't being acted upon, it looks like the documentation for Custom Templates does not appear to have been updated to correctly reflect the 5.x changes.

For example, for **ObjectFieldTemplate** the [documentation](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-templates/#ObjectFieldTemplate)* suggests:
```js
render((
  <Form schema={schema} validator={validator} templates={{ ObjectFieldTemplate }} />
), document.getElementById("app"));
```

Overriding in this way does not work.

### Expected Behavior

The reality seems to be that ```templates={{ ObjectFieldTemplate: ObjectFieldTemplate }}``` is required.

Documentation for other templates like **FieldTemplate** seem to be correct:
```js
render((
  <Form schema={schema} validator={validator} templates={{ FieldTemplate: CustomFieldTemplate }} />
), document.getElementById("app"));
```

\* I also note that deep linking on https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-templates/#ObjectFieldTemplate doesn't seem to work, but that's a minor inconvenience.

**Comment by heath-freenome** [comment]
@matburnham I'm curious whether you are not using a more modern browser? The `{ ObjectFieldTemplate }` is [shorthand syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer) for `{ ObjectFieldTemplate: ObjectFieldTemplate }` and is usually handled automatically by transpilers like babel or works straight-up in esm

**Comment by matburnham** [comment]
I'd found this behaviour on Chrome 108.0.5359.125, so not an old browser. However, testing again now I cannot reproduce the problem and it works fine. That suggests it was a side effect of some other issue I was having, or I'd misunderstood something along the way.
