### ISSUE TITLE
How to monitor changes in other field data?

### ISSUE THREAD

**Issue by mazhe-nerd** [rjsf-team/react-jsonschema-form#3330]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### What is your question?

I have customized a widget, how can i get the value of other fields in the form in this widget.

**Comment by heath-freenome** [comment]
There isn't really a built-in way to access all of the formData from within a single widget. If you wanted, you could implement an `onChange` handler for your `Form` and store the `formData` into the `formContext` which is available from the `registry` that IS passed to all widgets.

**Comment by mazhe-nerd** [comment]
thank you very much

**Comment by noynek** [comment]
Yea, thank you. I'm building components that need this functionality. For example, I've got a component that summarizes other fields.
