### ISSUE TITLE
Render only required fields

### ISSUE THREAD

**Issue by marcosgrzecatiny** [rjsf-team/react-jsonschema-form#3333]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### What is your question?

Is there an option to only render required fields described on a JSON Schema?

We received a external json schema with several attributes, but some one are important.

**Comment by heath-freenome** [comment]
Out of the box we don't support that, but I imagine you could override the `ObjectFieldTemplate` to only render required fields, something like (note you may have to make changes until this works as this is closer to pseudo-code than working code):

```
import { getDefaultTemplates } from '@rjsf/core';

const { ObjectFieldTemplate } = getDefaultTemplates();

const MyObjectFieldTemplate = (props: ObjectFieldTemplateProps) => {
  const { required } = props;
  if (!required) {
    return null;
  }
  return (
    <ObjectFieldTemplate
      {...props}
    />
  );
};
```

And then in your form override the `ObjectFieldTemplate` to use yours, something like:

```
<Form schema={schema} validator={validator} templates={{ ObjectFieldTemplate: MyObjectFieldTemplate }} />
```

**Comment by heath-freenome** [comment]
Or maybe it's the `SchemaField` that needs overriding in this manner?
