### ISSUE TITLE
Custom label for fields

### ISSUE THREAD

**Issue by unzsnu** [rjsf-team/react-jsonschema-form#3334]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

semantic-ui

### What is your question?

**version 5.0.0-beta.15**
I've implemented a custom template for fields using `FieldTemplate`.
It works, but i can't intercept the label amongs the children prop ... so i got it twice.
I tried using TitleFieldTemplate, but it refers to root ids `<h5>`.
I'd like to modify the `<label for>` ... previously i could do it, with this new version, i'm a bit confused.
Any advice?

**Comment by heath-freenome** [comment]
Could you provide a JSFiddle or Codesandbox.io with a simplified use-case so that we can understand how to help you better?

**Comment by unzsnu** [comment]
hi [heath-freenome](https://github.com/heath-freenome), i got problems with semantic-ui, with core implementation is working as expected
