### ISSUE TITLE
How to add a hidden 'comment' field to the formData?

### ISSUE THREAD

**Issue by MatinF** [rjsf-team/react-jsonschema-form#3366]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### What is your question?

We have a use case as follows:

1) We have different product variants that use different JSON Rule Schema files to generate their Configuration Files (formData)

2) When a user loads a Configuration File in our editor from device type A, the editor should automatically load Rule Schema A

In order to achieve the above, we are currently looking for certain fields in the loaded formData - but that is not very scalable or robust. Instead, we'd prefer to add a 'variant identification field' in the formData/Schema. This field should not be displayed in the front-end (regardless of UIschema) and is purely for internal purposes - like a comment field.

Is this possible to achieve in rjsf?

**Comment by adjenks** [comment]
Yeah I wanted to stuff a form version number in mine. I guess I'll just have to add it when saving, and remove it when loading.

**Comment by adjenks** [comment]
I figured it out.

```js
const schema1_0: RJSFSchema = {
  title: 'Test form',
  type: 'object',
  properties: {
    version: {
	  title: ' ',
      type: 'string',
	  default: "1.0"
    },
  },
}

const uiSchema: UiSchema = {
	"version": {
		"ui:inputType": 'hidden'
	}
}
```

**Comment by adjenks** [comment]
"ui:widget": "hidden" works much better, it doesn't leave an empty box.

See: https://github.com/rjsf-team/react-jsonschema-form/pull/111
