### ISSUE TITLE
Nested arrays do not work properly

### ISSUE THREAD

**Issue by JPeer264** [rjsf-team/react-jsonschema-form#3383]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5..0.0-beta.16

### Current Behavior

Following schema is used in the playground:
[Playground Link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6IlJvb3QiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJwYWdlcyI6eyJ0aXRsZSI6IlBhZ2VzIiwidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvUGFnZSJ9fX0sInJlcXVpcmVkIjpbInBhZ2VzIl0sImRlZmluaXRpb25zIjp7IkZpcnN0R3JvdXAiOnsidGl0bGUiOiJGaXJzdEdyb3VwIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidGl0bGUiOnsidGl0bGUiOiJUaXRsZSIsIm1pbkxlbmd0aCI6NSwibWF4TGVuZ3RoIjoyMDAsInR5cGUiOiJzdHJpbmcifSwiZGVzY3JpcHRpb24iOnsidGl0bGUiOiJEZXNjcmlwdGlvbiIsImRlZmF1bHQiOiIiLCJ0eXBlIjoic3RyaW5nIn0sInR5cGUiOnsidGl0bGUiOiJUeXBlIiwiZGVmYXVsdCI6InNvbWVfdHlwZSIsImVudW0iOlsic29tZV90eXBlIl0sInR5cGUiOiJzdHJpbmcifSwic29tZWZpZWxkIjp7InRpdGxlIjoiU29tZSBmaWVsZCIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJtaW5MZW5ndGgiOjIsIm1heExlbmd0aCI6NTAsInBhdHRlcm4iOiJbYS16QS1aMC05LV0rIn19fSwicmVxdWlyZWQiOlsidGl0bGUiLCJzb21lZmllbGQiXX0sIlNlY29uZEdyb3VwIjp7InRpdGxlIjoiU2Vjb25kR3JvdXAiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0aXRsZSI6eyJ0aXRsZSI6IlRpdGxlIiwibWluTGVuZ3RoIjo1LCJtYXhMZW5ndGgiOjIwMCwidHlwZSI6InN0cmluZyJ9LCJkZXNjcmlwdGlvbiI6eyJ0aXRsZSI6IkRlc2NyaXB0aW9uIiwiZGVmYXVsdCI6IiIsInR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbInRpdGxlIl19LCJQYWdlIjp7InRpdGxlIjoiUGFnZSIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InRpdGxlIjp7InRpdGxlIjoiVGl0bGUiLCJtaW5MZW5ndGgiOjUsIm1heExlbmd0aCI6MjAwLCJ0eXBlIjoic3RyaW5nIn0sInNob3J0X3RpdGxlIjp7InRpdGxlIjoiU2hvcnQgVGl0bGUiLCJtaW5MZW5ndGgiOjUsIm1heExlbmd0aCI6NTAsInR5cGUiOiJzdHJpbmcifSwic2VjdGlvbnMiOnsidGl0bGUiOiJTZWN0aW9ucyIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7ImFueU9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9GaXJzdEdyb3VwIn0seyIkcmVmIjoiIy9kZWZpbml0aW9ucy9TZWNvbmRHcm91cCJ9XX19fSwicmVxdWlyZWQiOlsidGl0bGUiLCJzaG9ydF90aXRsZSIsInNlY3Rpb25zIl19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)
<details>
<summary>Used schema</summary>
```json
{
  "title": "Root",
  "type": "object",
  "properties": {
    "pages": {
      "title": "Pages",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Page"
      }
    }
  },
  "required": [
    "pages"
  ],
  "definitions": {
    "FirstGroup": {
      "title": "FirstGroup",
      "type": "object",
      "properties": {
        "title": {
          "title": "Title",
          "minLength": 5,
          "maxLength": 200,
          "type": "string"
        },
        "description": {
          "title": "Description",
          "default": "",
          "type": "string"
        },
        "type": {
          "title": "Type",
          "default": "some_type",
          "enum": [
            "some_type"
          ],
          "type": "string"
        },
        "somefield": {
          "title": "Some field",
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 2,
            "maxLength": 50,
            "pattern": "[a-zA-Z0-9-]+"
          }
        }
      },
      "required": [
        "title",
        "somefield"
      ]
    },
    "SecondGroup": {
      "title": "SecondGroup",
      "type": "object",
      "properties": {
        "title": {
          "title": "Title",
          "minLength": 5,
          "maxLength": 200,
          "type": "string"
        },
        "description": {
          "title": "Description",
          "default": "",
          "type": "string"
        }
      },
      "required": [
        "title"
      ]
    },
    "Page": {
      "title": "Page",
      "type": "object",
      "properties": {
        "title": {
          "title": "Title",
          "minLength": 5,
          "maxLength": 200,
          "type": "string"
        },
        "short_title": {
          "title": "Short Title",
          "minLength": 5,
          "maxLength": 50,
          "type": "string"
        },
        "sections": {
          "title": "Sections",
          "type": "array",
          "items": {
            "anyOf": [
              {
                "$ref": "#/definitions/FirstGroup"
              },
              {
                "$ref": "#/definitions/SecondGroup"
              }
            ]
          }
        }
      },
      "required": [
        "title",
        "short_title",
        "sections"
      ]
    }
  }
}
```
</details>

Unfortunately, when I try to add an array inside in `somefield` then, the outer array (`sections`) gets somehow set to another value. So in this specific case, `FirstGroup` is set by default in the `sections` array. Inside `FirstGroup`, there is `somefield`, which is another array. As soon as I add a value to `somefield` the section is set to `SecongGroup`:

https://user-images.githubusercontent.com/10677263/212678297-cd1d17e7-5883-4eb9-af95-02768025d13d.mov

This behavior is a little different when there is no value given at first but then later added. Here I added the `title` a little later, and you can see that it got reset as soon as the `minLength` of the title got set. Maybe this helps a little with debugging.

https://user-images.githubusercontent.com/10677263/212678893-e2f4c4f0-c13b-43d9-8b64-26a38a7638fd.mov

Further "debugging" showed that this only happens when the fields are the same in these two groups. When the properties inside `SecondGroup` will change e.g., `title` to `myTitle` and `description` to `myDescription` then it works properly:

<details>
<summary>Working schema</summary>
```json
{
  "title": "Root",
  "type": "object",
  "properties": {
    "pages": {
      "title": "Pages",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Page"
      }
    }
  },
  "required": [
    "pages"
  ],
  "definitions": {
    "FirstGroup": {
      "title": "FirstGroup",
      "type": "object",
      "properties": {
        "title": {
          "title": "Title",
          "minLength": 5,
          "maxLength": 200,
          "type": "string"
        },
        "description": {
          "title": "Description",
          "default": "",
          "type": "string"
        },
        "type": {
          "title": "Type",
          "default": "some_type",
          "enum": [
            "some_type"
          ],
          "type": "string"
        },
        "somefield": {
          "title": "Some field",
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 2,
            "maxLength": 50,
            "pattern": "[a-zA-Z0-9-]+"
          }
        }
      },
      "required": [
        "title",
        "somefield"
      ]
    },
    "SecondGroup": {
      "title": "SecondGroup",
      "type": "object",
      "properties": {
        "myTitle": {
          "title": "Title",
          "minLength": 5,
          "maxLength": 200,
          "type": "string"
        },
        "myDescription": {
          "title": "Description",
          "default": "",
          "type": "string"
        }
      },
      "required": [
        "myTitle"
      ]
    },
    "Page": {
      "title": "Page",
      "type": "object",
      "properties": {
        "title": {
          "title": "Title",
          "minLength": 5,
          "maxLength": 200,
          "type": "string"
        },
        "short_title": {
          "title": "Short Title",
          "minLength": 5,
          "maxLength": 50,
          "type": "string"
        },
        "sections": {
          "title": "Sections",
          "type": "array",
          "items": {
            "anyOf": [
              {
                "$ref": "#/definitions/FirstGroup"
              },
              {
                "$ref": "#/definitions/SecondGroup"
              }
            ]
          }
        }
      },
      "required": [
        "title",
        "short_title",
        "sections"
      ]
    }
  }
}
```
</details>

[Playground Link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6IlJvb3QiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJwYWdlcyI6eyJ0aXRsZSI6IlBhZ2VzIiwidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvUGFnZSJ9fX0sInJlcXVpcmVkIjpbInBhZ2VzIl0sImRlZmluaXRpb25zIjp7IkZpcnN0R3JvdXAiOnsidGl0bGUiOiJGaXJzdEdyb3VwIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidGl0bGUiOnsidGl0bGUiOiJUaXRsZSIsIm1pbkxlbmd0aCI6NSwibWF4TGVuZ3RoIjoyMDAsInR5cGUiOiJzdHJpbmcifSwiZGVzY3JpcHRpb24iOnsidGl0bGUiOiJEZXNjcmlwdGlvbiIsImRlZmF1bHQiOiIiLCJ0eXBlIjoic3RyaW5nIn0sInR5cGUiOnsidGl0bGUiOiJUeXBlIiwiZGVmYXVsdCI6InNvbWVfdHlwZSIsImVudW0iOlsic29tZV90eXBlIl0sInR5cGUiOiJzdHJpbmcifSwic29tZWZpZWxkIjp7InRpdGxlIjoiU29tZSBmaWVsZCIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJtaW5MZW5ndGgiOjIsIm1heExlbmd0aCI6NTAsInBhdHRlcm4iOiJbYS16QS1aMC05LV0rIn19fSwicmVxdWlyZWQiOlsidGl0bGUiLCJzb21lZmllbGQiXX0sIlNlY29uZEdyb3VwIjp7InRpdGxlIjoiU2Vjb25kR3JvdXAiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJteVRpdGxlIjp7InRpdGxlIjoiVGl0bGUiLCJtaW5MZW5ndGgiOjUsIm1heExlbmd0aCI6MjAwLCJ0eXBlIjoic3RyaW5nIn0sIm15RGVzY3JpcHRpb24iOnsidGl0bGUiOiJEZXNjcmlwdGlvbiIsImRlZmF1bHQiOiIiLCJ0eXBlIjoic3RyaW5nIn19LCJyZXF1aXJlZCI6WyJteVRpdGxlIl19LCJQYWdlIjp7InRpdGxlIjoiUGFnZSIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InRpdGxlIjp7InRpdGxlIjoiVGl0bGUiLCJtaW5MZW5ndGgiOjUsIm1heExlbmd0aCI6MjAwLCJ0eXBlIjoic3RyaW5nIn0sInNob3J0X3RpdGxlIjp7InRpdGxlIjoiU2hvcnQgVGl0bGUiLCJtaW5MZW5ndGgiOjUsIm1heExlbmd0aCI6NTAsInR5cGUiOiJzdHJpbmcifSwic2VjdGlvbnMiOnsidGl0bGUiOiJTZWN0aW9ucyIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7ImFueU9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9GaXJzdEdyb3VwIn0seyIkcmVmIjoiIy9kZWZpbml0aW9ucy9TZWNvbmRHcm91cCJ9XX19fSwicmVxdWlyZWQiOlsidGl0bGUiLCJzaG9ydF90aXRsZSIsInNlY3Rpb25zIl19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

### Expected Behavior

The same schema should allow to add fields in `somefield` without resetting the value of the `sections`.

### Steps To Reproduce

1. Use schema as given above
2. Click <kbd>+</kbd> in `pages`
3. Click <kbd>+</kbd> in `sections`
4. Choose `FirstGroup`, which is chosen by default
5. Click <kbd>+</kbd> in `Some field`
6. Type at least 5 characters in the `Title` field inside the `FirstGroup`
7. 💥 `FirstGroup` is now `SecondGroup`

### Environment

```markdown
- OS: macOS 13.1
- Node: 16.17.1
- npm: 8.15.0
```

**Comment by heath-freenome** [comment]
Wow, this is a really interesting bug. Not entirely sure why it does what it does yet.

**Comment by JPeer264** [comment]
Ok this makes total sense.

I have no idea how it is implemented, but wouldn't it help to store somewhere if `FirstGroup` or `SecondGroup` is selected? Then the `auto-defaulting` just defaults when there is no value set (so technically only when a new one is added).

**Comment by heath-freenome** [comment]
> I have no idea how it is implemented, but wouldn't it help to store somewhere if `FirstGroup` or `SecondGroup` is selected? Then the `auto-defaulting` just defaults when there is no value set (so technically only when a new one is added).

Sometime I **feel** like I have no idea how it is implemented either :) Honestly, the auto-defaulting is pretty complex for all the various use cases and I personally would love to remove it so it doesn't have to be maintained. But that won't happen for several major versions, if ever. Is it possible to remove the `minLength` field and somehow use `pattern` matching to validate the need for the first two characters instead?
