### ISSUE TITLE
How to include the script from a CDN (getting errors)?

### ISSUE THREAD

**Issue by brollb** [rjsf-team/react-jsonschema-form#3385]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### What is your question?

When trying to upgrade from an older version, I encountered an error while trying to use the script from the CDN (following the docs [here](https://react-jsonschema-form.readthedocs.io/en/latest/#as-a-script-served-from-a-cdn)). When the script is loaded, it throws an error: `ReferenceError: exports is not defined`. ([related](https://github.com/babel/babel/issues/9187)).

Am I missing something with installation via the CDN?

**Comment by brollb** [comment]
Here is a simple html file to reproduce what I running into:
[test.zip](https://github.com/rjsf-team/react-jsonschema-form/files/10439055/test.zip)

**Comment by brollb** [comment]
Ah, I just needed to include the umd version :facepalm: 

The following url worked out of the box for me: https://unpkg.com/@rjsf/core@5.0.0-beta.16/dist/core.umd.production.min.js

**Comment by momone83** [comment]
@brollb seriously? Are you able to use the library from the CDN?

I tried using the umd version, but it doesn't work.

For example the validator is always "undefined" even importing the "@rjsf/validator-ajv8" as suggested by the documentation.

**Comment by brollb** [comment]
Yeah, my experience was pretty similar (perhaps I should've updated the issue and re-opened it). I ended up making a bundle where the validator and core packages are bundled together (basing it off the build process from the playground). I can post the build here if you are interested - let me know.

**Comment by momone83** [comment]
I think I understand, but if you can, I would appreciate it.

**Comment by brollb** [comment]
They are committed into another project here: https://github.com/webgme/webgme-taxonomy/tree/main/src/visualizers/widgets/TagCreator/lib

The JSON schema bundle can be unpacked like [this](https://github.com/webgme/webgme-taxonomy/blob/main/src/visualizers/widgets/TagCreator/TagCreatorWidget.js#L13) to get the form and validator.

**Comment by momone83** [comment]
@brollb Thanks a lot
