### ISSUE TITLE
if-then-else with enum values - branch which should display conditionally always displays for empty value

### ISSUE THREAD

**Issue by mpinter** [rjsf-team/react-jsonschema-form#3402]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

A small modification of the if-then-else example shows this - [playgound link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJhbmltYWwiOnsiZW51bSI6WyJDYXQiLCJGaXNoIl19fSwiYWxsT2YiOlt7ImlmIjp7InByb3BlcnRpZXMiOnsiYW5pbWFsIjp7ImNvbnN0IjoiQ2F0In19fSwidGhlbiI6eyJwcm9wZXJ0aWVzIjp7ImZvb2QiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsibWVhdCIsImdyYXNzIiwiZmlzaCJdfX0sInJlcXVpcmVkIjpbImZvb2QiXX19XX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==).I've remove the second `if` clause from the `allOf` section (and the required animal field as well just to be sure, but it has no effect), and the "Food" selects displays for all the animal select options except for the "Fish" one. 

For a sec thought this might be related to if-then-else inside allOf, but we're encountering the same issue even without it, this example taken from our schema, you can see the "WRITE OVERLAY INPUT" being renderend even when select is empty: [playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhbmltYWwiOiJGaXNoIiwiY2hvb3NlT25lT2YiOnt9fSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImNob29zZU9uZU9mIjp7InRpdGxlIjoiUmFkaW8gYnV0dG9uIHN0ZXAiLCJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsiY2hvb3NlT25lIl0sInByb3BlcnRpZXMiOnsiY2hvb3NlT25lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlNvbWUgcmFuZG9tIGNob29zZSIsIm9uZU9mIjpbeyJjb25zdCI6InNjcmVlbiIsInRpdGxlIjoiU2NyZWVuIn0seyJjb25zdCI6Im11bHRpcGx5IiwidGl0bGUiOiJNdWx0aXBseSJ9LHsiY29uc3QiOiJvdmVybGF5IiwidGl0bGUiOiJPdmVybGF5In1dfX0sImlmIjp7InByb3BlcnRpZXMiOnsiY2hvb3NlT25lIjp7ImNvbnN0Ijoib3ZlcmxheSJ9fX0sInRoZW4iOnsicmVxdWlyZWQiOlsib3ZlcmxheUlucHV0Il0sInByb3BlcnRpZXMiOnsib3ZlcmxheUlucHV0Ijp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IldSSVRFIE9WRVJMQVkgSU5QVVQifX19LCJlbHNlIjp7InByb3BlcnRpZXMiOnsibm90T3ZlcmxheUlucHV0Ijp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6InNvbWUgb3RoZXIgaW5wdXQifX19fX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

### Expected Behavior

Conditional branch rendering only when the condition is valid. When the input is empty it should not match a condition which has an expected value.

### Steps To Reproduce

[playground link 1](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhbmltYWwiOiJGaXNoIiwiY2hvb3NlT25lT2YiOnt9fSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImNob29zZU9uZU9mIjp7InRpdGxlIjoiUmFkaW8gYnV0dG9uIHN0ZXAiLCJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsiY2hvb3NlT25lIl0sInByb3BlcnRpZXMiOnsiY2hvb3NlT25lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlNvbWUgcmFuZG9tIGNob29zZSIsIm9uZU9mIjpbeyJjb25zdCI6InNjcmVlbiIsInRpdGxlIjoiU2NyZWVuIn0seyJjb25zdCI6Im11bHRpcGx5IiwidGl0bGUiOiJNdWx0aXBseSJ9LHsiY29uc3QiOiJvdmVybGF5IiwidGl0bGUiOiJPdmVybGF5In1dfX0sImlmIjp7InByb3BlcnRpZXMiOnsiY2hvb3NlT25lIjp7ImNvbnN0Ijoib3ZlcmxheSJ9fX0sInRoZW4iOnsicmVxdWlyZWQiOlsib3ZlcmxheUlucHV0Il0sInByb3BlcnRpZXMiOnsib3ZlcmxheUlucHV0Ijp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IldSSVRFIE9WRVJMQVkgSU5QVVQifX19LCJlbHNlIjp7InByb3BlcnRpZXMiOnsibm90T3ZlcmxheUlucHV0Ijp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6InNvbWUgb3RoZXIgaW5wdXQifX19fX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

[playground link 2](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhbmltYWwiOiJGaXNoIiwiY2hvb3NlT25lT2YiOnt9fSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImNob29zZU9uZU9mIjp7InRpdGxlIjoiUmFkaW8gYnV0dG9uIHN0ZXAiLCJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsiY2hvb3NlT25lIl0sInByb3BlcnRpZXMiOnsiY2hvb3NlT25lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlNvbWUgcmFuZG9tIGNob29zZSIsIm9uZU9mIjpbeyJjb25zdCI6InNjcmVlbiIsInRpdGxlIjoiU2NyZWVuIn0seyJjb25zdCI6Im11bHRpcGx5IiwidGl0bGUiOiJNdWx0aXBseSJ9LHsiY29uc3QiOiJvdmVybGF5IiwidGl0bGUiOiJPdmVybGF5In1dfX0sImlmIjp7InByb3BlcnRpZXMiOnsiY2hvb3NlT25lIjp7ImNvbnN0Ijoib3ZlcmxheSJ9fX0sInRoZW4iOnsicmVxdWlyZWQiOlsib3ZlcmxheUlucHV0Il0sInByb3BlcnRpZXMiOnsib3ZlcmxheUlucHV0Ijp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IldSSVRFIE9WRVJMQVkgSU5QVVQifX19LCJlbHNlIjp7InByb3BlcnRpZXMiOnsibm90T3ZlcmxheUlucHV0Ijp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6InNvbWUgb3RoZXIgaW5wdXQifX19fX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

### Environment

```markdown
rjsf playground, v5.00-beta16, happens on all browsers
```

**Comment by nickgros** [comment]
The behavior is correct with respect to how JSON Schema validation works. Your original `if` schema, shown below, will always be true unless `chooseOne` is specified and is not `"overlay"`
```
{
  "if": {
    "properties": {
      "chooseOne": {
        "const": "overlay"
      }
    }
  }
}
```

To fix this, you need to also make `chooseOne` `required`:

```
{
  "if": {
    "properties": {
      "chooseOne": {
        "const": "overlay"
      }
    },
	"required": ["chooseOne"]
  }
}
```
