### ISSUE TITLE
doesn't the minItems property support references from another property?

### ISSUE THREAD

**Issue by IngAndresRodriguez** [rjsf-team/react-jsonschema-form#3405]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

other

### What is your question?

"propertyA": {
    "type": "number",
    "title": "Example A",
    "minimum": 1
  },

"propertyB": {
        "type": "array",
        "title": "Example B",
        "uniqueItems": true,
        "minItems": { "$ref": "#/properties/propertyA" },
        "maxItems": { "$ref": "#/properties/propertyA" },
        "items": {
          "type": "string",
          "enum": ["A", "B", "C", "D", "E", "F"]
        }
      }

**Comment by heath-freenome** [comment]
@IngAndresRodriguez according to the [documentation](https://json-schema.org/understanding-json-schema/reference/array.html#length), the `minItems` and `maxItems` for an array are only allowed to be non-negative numbers. So your example is not considered a valid JSON schema
