### ISSUE TITLE
Incorrect merge of anyOf with schemaDependencies in arrays

### ISSUE THREAD

**Issue by skfarhat** [rjsf-team/react-jsonschema-form#3407]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

schema dependencies when used with oneOf and in array incorrectly merges all properties when the depended on field changes. 

Apologies if not clear, it's kind of tough to describe. The reproducer should help

### Expected Behavior

I would expect only one of the properties to be shown depending on the number of pets. 

### Steps To Reproduce

- Visit [Playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6IlNjaGVtYSBkZXBlbmRlbmNpZXMiLCJkZXNjcmlwdGlvbiI6IlRoZXNlIHNhbXBsZXMgYXJlIGJlc3Qgdmlld2VkIHdpdGhvdXQgbGl2ZSB2YWxpZGF0aW9uLiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImFycmF5T2ZDb25kaXRpb25hbHMiOnsidGl0bGUiOiJBcnJheSBvZiBjb25kaXRpb25hbHMiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9wZXJzb24ifX19LCJkZWZpbml0aW9ucyI6eyJwZXJzb24iOnsidGl0bGUiOiJQZXJzb24iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJEbyB5b3UgaGF2ZSBhbnkgcGV0cz8iOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiTm8iLCJZZXM6IE9uZSIsIlllczogTW9yZSB0aGFuIG9uZSJdLCJkZWZhdWx0IjoiTm8ifX0sInJlcXVpcmVkIjpbIkRvIHlvdSBoYXZlIGFueSBwZXRzPyJdLCJkZXBlbmRlbmNpZXMiOnsiRG8geW91IGhhdmUgYW55IHBldHM/Ijp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7IkRvIHlvdSBoYXZlIGFueSBwZXRzPyI6eyJlbnVtIjpbIk5vIl19fX0seyJwcm9wZXJ0aWVzIjp7IkRvIHlvdSBoYXZlIGFueSBwZXRzPyI6eyJlbnVtIjpbIlllczogT25lIl19LCJIb3cgb2xkIGlzIHlvdXIgcGV0PyI6eyJ0eXBlIjoibnVtYmVyIn19LCJyZXF1aXJlZCI6WyJIb3cgb2xkIGlzIHlvdXIgcGV0PyJdfSx7InByb3BlcnRpZXMiOnsiRG8geW91IGhhdmUgYW55IHBldHM/Ijp7ImVudW0iOlsiWWVzOiBNb3JlIHRoYW4gb25lIl19LCJEbyB5b3Ugd2FudCB0byBnZXQgcmlkIG9mIGFueT8iOnsidHlwZSI6ImJvb2xlYW4ifX0sInJlcXVpcmVkIjpbIkRvIHlvdSB3YW50IHRvIGdldCByaWQgb2YgYW55PyJdfV19fX19fSwidWlTY2hlbWEiOnsic2ltcGxlIjp7ImNyZWRpdF9jYXJkIjp7InVpOmhlbHAiOiJJZiB5b3UgZW50ZXIgYW55dGhpbmcgaGVyZSB0aGVuIGJpbGxpbmdfYWRkcmVzcyB3aWxsIGJlIGR5bmFtaWNhbGx5IGFkZGVkIHRvIHRoZSBmb3JtLiJ9fSwiY29uZGl0aW9uYWwiOnsiRG8geW91IHdhbnQgdG8gZ2V0IHJpZCBvZiBhbnk/Ijp7InVpOndpZGdldCI6InJhZGlvIn19LCJhcnJheU9mQ29uZGl0aW9uYWxzIjp7Iml0ZW1zIjp7IkRvIHlvdSB3YW50IHRvIGdldCByaWQgb2YgYW55PyI6eyJ1aTp3aWRnZXQiOiJyYWRpbyJ9fX0sImZpeGVkQXJyYXlPZkNvbmRpdGlvbmFscyI6eyJpdGVtcyI6eyJEbyB5b3Ugd2FudCB0byBnZXQgcmlkIG9mIGFueT8iOnsidWk6d2lkZ2V0IjoicmFkaW8ifX0sImFkZGl0aW9uYWxJdGVtcyI6eyJEbyB5b3Ugd2FudCB0byBnZXQgcmlkIG9mIGFueT8iOnsidWk6d2lkZ2V0IjoicmFkaW8ifX19fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)
- click + to add a person 
- for `Do you have any pets`, select `Yes: One`
- for `How old is your pet?*`, enter some number, e.g. `5`
- then select `Yes: More than one`
- for `Do you want to get rid of any?*` select either of the options, e.g. `true`
- check the `formData` which now contains both properties
  - `Do you want to get rid of any?`
  - `How old is your pet?`
```
formData =  {
      "Do you have any pets?": "Yes: More than one",
      "Do you want to get rid of any?": true,
      "How old is your pet?": 5
    }
```

### Environment

```markdown
- OS:
- Node:
- npm:

Playground (all)
```

**Comment by heath-freenome** [comment]
@skfarhat This is an interesting bug. While it is true that for simple anyOf/oneOf the unnecessary data gets properly removed (as of beta.18 anyway), but the logic that does that doesn't understand dependencies. As a work around, you can pass true for `liveOmit` and `omitExtraData` to get the result you want as you can see in this [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhcnJheU9mQ29uZGl0aW9uYWxzIjpbXX0sInNjaGVtYSI6eyJ0aXRsZSI6IlNjaGVtYSBkZXBlbmRlbmNpZXMiLCJkZXNjcmlwdGlvbiI6IlRoZXNlIHNhbXBsZXMgYXJlIGJlc3Qgdmlld2VkIHdpdGhvdXQgbGl2ZSB2YWxpZGF0aW9uLiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImFycmF5T2ZDb25kaXRpb25hbHMiOnsidGl0bGUiOiJBcnJheSBvZiBjb25kaXRpb25hbHMiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9wZXJzb24ifX19LCJkZWZpbml0aW9ucyI6eyJwZXJzb24iOnsidGl0bGUiOiJQZXJzb24iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJEbyB5b3UgaGF2ZSBhbnkgcGV0cz8iOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiTm8iLCJZZXM6IE9uZSIsIlllczogTW9yZSB0aGFuIG9uZSJdLCJkZWZhdWx0IjoiTm8ifX0sInJlcXVpcmVkIjpbIkRvIHlvdSBoYXZlIGFueSBwZXRzPyJdLCJkZXBlbmRlbmNpZXMiOnsiRG8geW91IGhhdmUgYW55IHBldHM/Ijp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7IkRvIHlvdSBoYXZlIGFueSBwZXRzPyI6eyJlbnVtIjpbIk5vIl19fX0seyJwcm9wZXJ0aWVzIjp7IkRvIHlvdSBoYXZlIGFueSBwZXRzPyI6eyJlbnVtIjpbIlllczogT25lIl19LCJIb3cgb2xkIGlzIHlvdXIgcGV0PyI6eyJ0eXBlIjoibnVtYmVyIn19LCJyZXF1aXJlZCI6WyJIb3cgb2xkIGlzIHlvdXIgcGV0PyJdfSx7InByb3BlcnRpZXMiOnsiRG8geW91IGhhdmUgYW55IHBldHM/Ijp7ImVudW0iOlsiWWVzOiBNb3JlIHRoYW4gb25lIl19LCJEbyB5b3Ugd2FudCB0byBnZXQgcmlkIG9mIGFueT8iOnsidHlwZSI6ImJvb2xlYW4ifX0sInJlcXVpcmVkIjpbIkRvIHlvdSB3YW50IHRvIGdldCByaWQgb2YgYW55PyJdfV19fX19fSwidWlTY2hlbWEiOnsic2ltcGxlIjp7ImNyZWRpdF9jYXJkIjp7InVpOmhlbHAiOiJJZiB5b3UgZW50ZXIgYW55dGhpbmcgaGVyZSB0aGVuIGJpbGxpbmdfYWRkcmVzcyB3aWxsIGJlIGR5bmFtaWNhbGx5IGFkZGVkIHRvIHRoZSBmb3JtLiJ9fSwiY29uZGl0aW9uYWwiOnsiRG8geW91IHdhbnQgdG8gZ2V0IHJpZCBvZiBhbnk/Ijp7InVpOndpZGdldCI6InJhZGlvIn19LCJhcnJheU9mQ29uZGl0aW9uYWxzIjp7Iml0ZW1zIjp7IkRvIHlvdSB3YW50IHRvIGdldCByaWQgb2YgYW55PyI6eyJ1aTp3aWRnZXQiOiJyYWRpbyJ9fX0sImZpeGVkQXJyYXlPZkNvbmRpdGlvbmFscyI6eyJpdGVtcyI6eyJEbyB5b3Ugd2FudCB0byBnZXQgcmlkIG9mIGFueT8iOnsidWk6d2lkZ2V0IjoicmFkaW8ifX0sImFkZGl0aW9uYWxJdGVtcyI6eyJEbyB5b3Ugd2FudCB0byBnZXQgcmlkIG9mIGFueT8iOnsidWk6d2lkZ2V0IjoicmFkaW8ifX19fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOnRydWUsImxpdmVPbWl0Ijp0cnVlfX0=)
