### ISSUE TITLE
Duplicate text input above nested oneOf

### ISSUE THREAD

**Issue by CiaranMn** [rjsf-team/react-jsonschema-form#3412]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.0.0-beta.20

### Current Behavior

When `oneOf` appears in a nested schema, a text input appears above the multi-field.

[Playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJzdHJpbmdPck51bWJlciI6eyJvbmVPZiI6W3sidHlwZSI6InN0cmluZyIsInRpdGxlIjoiU3RyaW5nIn0seyJ0eXBlIjoibnVtYmVyIiwidGl0bGUiOiJOdW1iZXIifV19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZSwic2hvd0Vycm9yTGlzdCI6InRvcCJ9fQ==)

Sample schema
```json
{
  "type": "object",
  "properties": {
    "stringOrNumber": {
      "oneOf": [
        {
          "type": "string",
          "title": "String"
        },
        {
          "type": "number",
          "title": "Number"
        }
      ]
    }
  }
}
```

<img width="531" alt="Screenshot 2023-01-30 at 09 51 35" src="https://user-images.githubusercontent.com/37743469/215444300-0adfdf5e-ca31-4a56-a362-5e231afce23d.png">

### Expected Behavior

The additional input does not appear.

### Steps To Reproduce

See playground link / sample schema

### Environment

```markdown
- OS: macOS
- Node: 16.16.0
- npm: 8.11.0
```

**Comment by heath-freenome** [comment]
Ah, this is caused by #3392, specifically the fix for #1654. I will try and figure out how to avoid this within the scope of an object while still supporting it for the main use case.

**Comment by CiaranMn** [comment]
Thanks @heath-freenome!

**Comment by saisilinus** [comment]
I have faced this issue in a project I am working on @heath-freenome . I have tried the following versions but still get the same problem:

- 5.24.13
- 6.0.0-beta.15
- 6.0.0-beta.1
- 6.0.0-beta.12

**Comment by heath-freenome** [comment]
@saisilinus Can you provide a reproducible test case?

**Comment by saisilinus** [comment]
> [@saisilinus](https://github.com/saisilinus) Can you provide a reproducible test case?

Sorry for bothering you. I have found the issue while trying to reproduce on my end. It seems that this duplication occurred because I specified `type` and `anyOf` for the same thing. Something like this:

`"doiOrWebUrl": {
      "type": "string",
      "anyOf": [
        {
          "$ref": "#/$defs/doi"
        },
        {
          "$ref": "#/$defs/webUrl"
        }
      ],
      "title": "Digital Object Identifier (DOI) or Web URL"
    }`

All I had to do was remove `type` and it worked. Thank you for your help @heath-freenome
