### ISSUE TITLE
Duplicate ajv/dist package in bundle

### ISSUE THREAD

**Issue by y-az** [rjsf-team/react-jsonschema-form#3413]
Hi!

Running a build on next.js with the bundle analyzer on produces a visualization of the packages in my bundle. It seems as if `ajv/dist` is included twice. How can I resolve this?

```
    "@rjsf/core": "^5.0.0-beta.17",
    "@rjsf/mui": "^5.0.0-beta.17",
    "@rjsf/utils": "^5.0.0-beta.17",
    "@rjsf/validator-ajv8": "^5.0.0-beta.17",
```
![Screenshot 2023-01-30 at 17 34 49](https://user-images.githubusercontent.com/11176286/215539801-8d97a943-a21a-40e8-bf2c-c19f0e989099.png)

**Comment by nickgros** [comment]
@youssefazriouil This can depend on a lot of local factors, such as your npm client and webpack configuration. First, can you see of any of the following help?
* Run `npm dedupe`
* Re-create your package-lock.json (or yarn.lock or pnpm-lock.yaml)
* Check your webpack configuration to ensure aliases are properly configured

**Comment by youssefazriouil** [comment]
Hey @nickgros thanks for your response.

- I've ran `npm dedupe`
- I've removed and recreate my package-lock.json
- I've checked my next next.config's webpack configuration but it does not contain any alias specific information

![Screenshot 2023-02-07 at 18 43 24](https://user-images.githubusercontent.com/11176286/217323286-d2bd84a6-c118-4375-9afa-522fd50b0f89.png)

Do you have any other ideas what could cause this?

**Comment by youssefazriouil** [comment]
Running Inspectpack's `DuplicatesPlugin` for webpack also finds `ajv` and `json-schema-traverse` duplicated:

```## static/chunks/672-7951bcd8c52d9575.js
ajv (Found 1 resolved, 2 installed, 2 depended. Latest 8.12.0.)
  8.12.0 ~/@rjsf/validator-ajv8/~/ajv
    myApp@0.1.0 -> @rjsf/validator-ajv8@^5.0.0-beta.17 -> ajv@^8.11.0
  8.12.0 ~/ajv-formats/~/ajv
    myApp@0.1.0 -> @rjsf/validator-ajv8@^5.0.0-beta.17 -> ajv-formats@^2.1.1 -> ajv@^8.0.0

json-schema-traverse (Found 1 resolved, 2 installed, 2 depended. Latest 1.0.0.)
  1.0.0 ~/@rjsf/validator-ajv8/~/json-schema-traverse
    myApp@0.1.0 -> @rjsf/validator-ajv8@^5.0.0-beta.17 -> ajv@^8.11.0 -> json-schema-traverse@^1.0.0
  1.0.0 ~/ajv-formats/~/json-schema-traverse
    myApp@0.1.0 -> @rjsf/validator-ajv8@^5.0.0-beta.17 -> ajv-formats@^2.1.1 -> ajv@^8.0.0 -> json-schema-traverse@^1.0.0```
    
    Any ideas?

**Comment by heath-freenome** [comment]
@youssefazriouil I have filed an issue with ajv-formats to hopefully get this fixed. Please work with them.
