### ISSUE TITLE
how to create newErrorSchema in a UI Field

### ISSUE THREAD

**Issue by ngocquang0651** [rjsf-team/react-jsonschema-form#3421]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### What is your question?

I want to create newErrorSchema in "props.onChange"  to notify error to the outside

```
const CustomField = (props: FieldProps) => {
  const onChangesSchema = (e: any) => {
    props.onChange(e.target.value)
  };
  return (
    <div>
      <p>{props.schema?.title}</p>
      <Input
        type="text"
        value={props.value}
        required={props.required}
        onChange={(event) => onChangesSchema(event)}
      />
    </div>
  );
};
```

**Comment by heath-freenome** [comment]
There is a helper class in `@rjsf/utils` called [ErrorSchemaBuilder](https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/utility-functions/#errorschema-builder-class) that you can use.

```
const CustomField = (props: FieldProps) => {
  const { idSchema, idSeparator = "_", errorSchema } = props;
  const onChangesSchema = (e: any) => {
    const { target: { value } } = e;
    const builder = ErrorSchemaBuilder(errorSchema);
    if (hasError(value)) {
      const idParts = idSchema.$id.split(idSeparator);
      // drop the root which is the first item
      idParts().shift();
      builder.addError("your error", idParts);
    }
    props.onChange(e.target.value)
  };
  return (
    <div>
      <p>{props.schema?.title}</p>
      <Input
        type="text"
        value={props.value}
        required={props.required}
        onChange={onChangesSchema}
      />
    </div>
  );
};
```

**Comment by ngocquang0651** [comment]
@If I use to livevalidate, I don't show error. how can I just use livevalidate and still get the error from ui:field?

**Comment by ngocquang0651** [comment]
> There is a helper class in `@rjsf/utils` called [ErrorSchemaBuilder](https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/utility-functions/#errorschema-builder-class) that you can use.
> 
> ```
> const CustomField = (props: FieldProps) => {
>   const { idSchema, idSeparator = "_", errorSchema } = props;
>   const onChangesSchema = (e: any) => {
>     const { target: { value } } = e;
>     const builder = ErrorSchemaBuilder(errorSchema);
>     if (hasError(value)) {
>       const idParts = idSchema.$id.split(idSeparator);
>       // drop the root which is the first item
>       idParts().shift();
>       builder.addError("your error", idParts);
>     }
>     props.onChange(value, builder.ErrorSchema);
>   };
>   return (
>     <div>
>       <p>{props.schema?.title}</p>
>       <Input
>         type="text"
>         value={props.value}
>         required={props.required}
>         onChange={onChangesSchema}
>       />
>     </div>
>   );
> };
> ```



> There is a helper class in `@rjsf/utils` called [ErrorSchemaBuilder](https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/utility-functions/#errorschema-builder-class) that you can use.
> 
> ```
> const CustomField = (props: FieldProps) => {
>   const { idSchema, idSeparator = "_", errorSchema } = props;
>   const onChangesSchema = (e: any) => {
>     const { target: { value } } = e;
>     const builder = ErrorSchemaBuilder(errorSchema);
>     if (hasError(value)) {
>       const idParts = idSchema.$id.split(idSeparator);
>       // drop the root which is the first item
>       idParts().shift();
>       builder.addError("your error", idParts);
>     }
>     props.onChange(value, builder.ErrorSchema);
>   };
>   return (
>     <div>
>       <p>{props.schema?.title}</p>
>       <Input
>         type="text"
>         value={props.value}
>         required={props.required}
>         onChange={onChangesSchema}
>       />
>     </div>
>   );
> };
> ```
if I use to livevalidate, I don't show error. how can I just use livevalidate and still get the error from ui:field?

**Comment by heath-freenome** [comment]
You would have to write a [custom validator](https://rjsf-team.github.io/react-jsonschema-form/docs/usage/validation#custom-validation-rules) that detects your field (by path) and provides the error

**Comment by heath-freenome** [comment]
@ngocquang0651 Does this make sense?

**Comment by ngocquang0651** [comment]
thank you very much, I have fixed it

**Comment by heath-freenome** [comment]
> thank you very much, I have fixed it

Awesome, feel free to close the issue.
