### ISSUE TITLE
Enum select forms do not update their value in the ui - charka-ui theme

### ISSUE THREAD

**Issue by Yoseftickx** [rjsf-team/react-jsonschema-form#3422]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

chakra-ui

### Version

5.0.1

### Current Behavior

When using the enum property with a list of simple values in the json schema. The form is rendered as expected however when selecting a value from the select dropdown the ui is never updated to show this new selected value. The form data is however updated with the selected value

### Expected Behavior

The chakra-ui select field should update its shown ui to reflect the form data.

### Steps To Reproduce

1. go to playground https://rjsf-team.github.io/react-jsonschema-form/
2. select `numbers` example
3. select chakra-ui theme
4. try to change the value of the `Number enum` field - which is a select
5. observe that the value did not change in the ui
6. observe that the value DID change in the formdata area

### Environment

```markdown
Your own playground.
```

### Anything else?
[playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJudW1iZXIiOjMuMTQsImludGVnZXIiOjQyLCJudW1iZXJFbnVtIjoyLCJpbnRlZ2VyUmFuZ2UiOjQyLCJpbnRlZ2VyUmFuZ2VTdGVwcyI6ODB9LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInRpdGxlIjoiTnVtYmVyIGZpZWxkcyAmIHdpZGdldHMiLCJwcm9wZXJ0aWVzIjp7Im51bWJlciI6eyJ0aXRsZSI6Ik51bWJlciIsInR5cGUiOiJudW1iZXIifSwiaW50ZWdlciI6eyJ0aXRsZSI6IkludGVnZXIiLCJ0eXBlIjoiaW50ZWdlciJ9LCJudW1iZXJFbnVtIjp7InR5cGUiOiJudW1iZXIiLCJ0aXRsZSI6Ik51bWJlciBlbnVtIiwiZW51bSI6WzEsMiwzXX0sIm51bWJlckVudW1SYWRpbyI6eyJ0eXBlIjoibnVtYmVyIiwidGl0bGUiOiJOdW1iZXIgZW51bSIsImVudW0iOlsxLDIsM119LCJpbnRlZ2VyUmFuZ2UiOnsidGl0bGUiOiJJbnRlZ2VyIHJhbmdlIiwidHlwZSI6ImludGVnZXIiLCJtaW5pbXVtIjo0MiwibWF4aW11bSI6MTAwfSwiaW50ZWdlclJhbmdlU3RlcHMiOnsidGl0bGUiOiJJbnRlZ2VyIHJhbmdlIChieSAxMCkiLCJ0eXBlIjoiaW50ZWdlciIsIm1pbmltdW0iOjUwLCJtYXhpbXVtIjoxMDAsIm11bHRpcGxlT2YiOjEwfX19LCJ1aVNjaGVtYSI6eyJpbnRlZ2VyIjp7InVpOndpZGdldCI6InVwZG93biJ9LCJudW1iZXJFbnVtUmFkaW8iOnsidWk6d2lkZ2V0IjoicmFkaW8iLCJ1aTpvcHRpb25zIjp7ImlubGluZSI6dHJ1ZX19LCJpbnRlZ2VyUmFuZ2UiOnsidWk6d2lkZ2V0IjoicmFuZ2UifSwiaW50ZWdlclJhbmdlU3RlcHMiOnsidWk6d2lkZ2V0IjoicmFuZ2UifX0sInRoZW1lIjoiY2hha3JhLXVpIiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZSwic2hvd0Vycm9yTGlzdCI6InRvcCJ9fQ==) 
_No response_

**Comment by nickgros** [comment]
Good catch! You are welcome to make a pull request to fix it. @heath-freenome may also take a look to see if recent changes caused a regression.
