### ISSUE TITLE
How to I customFormat if data is Object

### ISSUE THREAD

**Issue by ngocquang0651** [rjsf-team/react-jsonschema-form#3426]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### What is your question?

I can't customformat when the data is an object

**Comment by nickgros** [comment]
@ngocquang0651 Sorry, it's hard to understand what you're asking. Could you be more specific, and ideally link to a reproducible example in the playground or JSFiddle?
