### ISSUE TITLE
[Playground] formSchema onChange handler updates formData object

### ISSUE THREAD

**Issue by SimonGodefroid** [rjsf-team/react-jsonschema-form#3441]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

Typing a new object entry in the `formSchema` updates the `formData` object.

![image](https://user-images.githubusercontent.com/17337190/218047745-82a80272-9d57-4c83-89ce-5a1c7260f1f2.png)

### Expected Behavior

`formSchema` changes are only updating `formSchema` object

### Steps To Reproduce

1. On this page [https://rjsf-team.github.io/react-jsonschema-form/](https://rjsf-team.github.io/react-jsonschema-form/)
2. Type a new schema in the `JSONSchema` textarea.

https://user-images.githubusercontent.com/17337190/218048550-c8b4f197-19b0-4b76-9cb3-47561586ed98.mov

### Environment

```markdown
N.A.
```

### Anything else?

The lib's great cheers for gifting this to the world.

**Comment by heath-freenome** [comment]
While this is an interesting example, what you are showing is the way that the playground was implemented in concert with the auto-default behavior of RJSF. If it really is important to fix things so that there is a delay between typing and the automatic updating of the formData defaults based on schema, you are welcome to provide a PR against the playground.

**Comment by AnaRosaJaime** [comment]
It seems that the problem isn't in the playground but RJSF does not eliminate in the formData those renamed or eliminated properties of the JSON schema. This situation is obvious when a property with default value is renamed (e.g. firstName) but for properties that don't have default value (lastName) this is not appreciated until this value is modified in the form in the form in the form
