### ISSUE TITLE
Prev. selected oneOf schema properties removed only IF populated when schema changes

### ISSUE THREAD

**Issue by tmlstevens** [rjsf-team/react-jsonschema-form#3442]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0Iiwib25lT2YiOlt7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InVuaXF1ZS1wcm9wZXJ0eS0xIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbInN1YnNjaGVtYTEiXX0sImNvbW1vbi1wcm9wZXJ0eSI6eyJ0eXBlIjoic3RyaW5nIn19LCJyZXF1aXJlZCI6W10sImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjpmYWxzZX0seyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ1bmlxdWUtcHJvcGVydHktMiI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJzdWJzY2hlbWEyIl19LCJjb21tb24tcHJvcGVydHkiOnsidHlwZSI6InN0cmluZyJ9fSwicmVxdWlyZWQiOltdLCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2V9LHsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidW5pcXVlLXByb3BlcnR5LTMiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsic3Vic2NoZW1hMyJdfSwiY29tbW9uLXByb3BlcnR5Ijp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbXSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlfV19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=) demonstrating the issue.

### What theme are you using?

bootstrap-4

### Version

5.x

### Current Behavior

Given a oneOf schema for which the possible types are object - when user selects a different subschema, properties unique to the old/previously selected subschema are not removed unless they were populated when user selected the new/current subschema. Therefore, if a user toggles/selects through each oneOf subschema, without populating unique properties props.formData will accumulate an invalid payload. However, if user populates unique properties before selecting different subschema, those properties are removed from formData when the new subschema is selected and form loaded.

This behavior is observable when props.formData is returned to Form component's onChange handler function. Properties unique to previously selected oneOf subschema(s) that were not populated are found in the formData, with values set to undefined. Upon form submission, errors will be thrown as the submitted object contains a conglomeration of properties not conforming to any of the oneOf subschemas.

This is very similar to the issue reported in [2183](https://github.com/rjsf-team/react-jsonschema-form/issues/2183), however, with the v.5x refactor and implementation of sanitizeDataForNewSchema it seems somewhat different. Further, my proposed solution only resolves the issue in v5.x.

### Expected Behavior

I expect properties unique to old/previously selected subschema to be removed, whether populated or not, from props.fomData when new/current subschema is selected, since they are irrelevant/out-of-scope when new subschema is selected.

### Steps To Reproduce

1. go to the playground [setup](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0Iiwib25lT2YiOlt7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InVuaXF1ZS1wcm9wZXJ0eS0xIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbInN1YnNjaGVtYTEiXX0sImNvbW1vbi1wcm9wZXJ0eSI6eyJ0eXBlIjoic3RyaW5nIn19LCJyZXF1aXJlZCI6W10sImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjpmYWxzZX0seyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ1bmlxdWUtcHJvcGVydHktMiI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJzdWJzY2hlbWEyIl19LCJjb21tb24tcHJvcGVydHkiOnsidHlwZSI6InN0cmluZyJ9fSwicmVxdWlyZWQiOltdLCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2V9LHsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidW5pcXVlLXByb3BlcnR5LTMiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsic3Vic2NoZW1hMyJdfSwiY29tbW9uLXByb3BlcnR5Ijp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbXSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlfV19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)
2. observe that Option 1 is selected by default
3. do not enter data, select Option 2
4. do not enter data, select Option 3
5. populate the fields and submit the form
6. observe the errors

### Environment

```markdown
- OS: RHEL 8.6
- Node: 14.20.1
- npm: 6.14.17
```

### Anything else?

It seems to me that properties unique to old/previously selected subschema should be discarded when the new/current subschema is selected; they should not be returned in the formData. But for some reason those properties are persisted and their values set to undefined, but maybe there's a reason?

**Comment by heath-freenome** [comment]
@tmlstevens awaiting changes to your PR

**Comment by heath-freenome** [comment]
@tmlstevens Are you going to get a change to update your PR?

**Comment by tmlstevens** [comment]
I will not.
