### ISSUE TITLE
react-jsonschema-forms validator error - Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by veyronB2** [rjsf-team/react-jsonschema-form#3444]
`###` Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

bootstrap-4

### What is your question?

Hi, 
I'm trying to build dynamic forms using rjsf and having some issues with the validator.

The error message is applicable to any validation type attempt i.e. if a field is required or minLenght check.

If I disable noHtml5Validate={false} then I get a pop up telling me to populate required field. My goal is to display all errors and highlight relevant inputs in red.

However, I'm getting this error each time regardless of validation type i.e. if a field is required or checking for minLength. 

![image](https://user-images.githubusercontent.com/84079386/218581746-484447e8-49ca-491f-81ee-783a972aba5b.png)

If I disable noHtml5Validate then I get a pop up telling me to populate required field but I get no error message under the input field. There is something in the app that is causing this because when I create a new app and use the same schema and set up I get the no errors so I'm really struggling to find a solution for this issue. 

My schema:
`const testSchema = {`
`    "type": "object",`
`    "required": [`
`    "account",`
`    ],`
`    "properties": {`
`        "reference": {`
`            "type": "string",`
`            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",`
`            "nullable": true,`
`        },`
`        "account": {`
`            "type": "integer",`
`            "format": "int64",`
`            "pattern":"^(0|[1-9][0-9]*)$",`
`        }`
`    },`

`    "additionalProperties": false
`};`

`import Form from "@rjsf/bootstrap-4";`
`import validator from "@rjsf/validator-ajv8";`

`return <>`
`    { schema && <Form `
`        schema={testSchema}`
`        uiSchema={uiSchema}`
`        validator={validator}`
`        onSubmit={onSubmit}`
`        noHtml5Validate={true}`
`        formData={formData}`
`        onChange={(e)=> onChangeHandler(e.formData)}`
`    />}</>;`

Any help would be much appreciated.

**Comment by heath-freenome** [comment]
Can you please provide an example of your problem using JSFiddle, Codesandbox.io or some other tool?

**Comment by veyronB2** [comment]
Unfortunately I cant reproduce this error outside of my application so there is something in the app that seems to cause this and I've spent days looking for an answer or suggestion where to look.

**Comment by heath-freenome** [comment]
Without something to reproduce the problem, we don't know how to fix it. If you haven't provided an example in a week or so, I will just close this issue.

**Comment by heath-freenome** [comment]
@veyronB2 did you figure it out?
