### ISSUE TITLE
All of if then else warning

### ISSUE THREAD

**Issue by sercankavdir** [rjsf-team/react-jsonschema-form#3445]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### What is your question?

[Link to Playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6Ikxpc3QiLCJpdGVtcyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJrZXkiOnsidGl0bGUiOiJLZXkiLCJ0eXBlIjoic3RyaW5nIiwiZm9ybWF0Ijoic3RyaW5nIiwiZW51bSI6WyJpYXBJdGVtIiwiYnVuZGxlIl19fSwiYWxsT2YiOlt7ImlmIjp7InByb3BlcnRpZXMiOnsia2V5Ijp7ImNvbnN0IjoiaWFwSXRlbSJ9fX0sInRoZW4iOnsicHJvcGVydGllcyI6eyJ2YWx1ZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJpYXAiLCJlbnVtIjpbImEiLCJiIl0sImVudW1OYW1lcyI6WyJhc2QiLCJibm0iXX19fX0seyJpZiI6eyJwcm9wZXJ0aWVzIjp7ImtleSI6eyJjb25zdCI6ImJ1bmRsZSJ9fX0sInRoZW4iOnsicHJvcGVydGllcyI6eyJ2YWx1ZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJidW5kbGUiLCJlbnVtIjpbImMiLCJkIl0sImVudW1OYW1lcyI6WyJjdmIiLCJkZmciXX19fX1dfX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

```json
{
  "type": "array",
  "title": "List",
  "items": {
    "type": "object",
    "properties": {
      "key": {
        "title": "Key",
        "type": "string",
        "format": "string",
        "enum": [
          "iapItem",
          "bundle"
        ]
      }
    },
    "allOf": [
      {
        "if": {
          "properties": {
            "key": {
              "const": "iapItem"
            }
          }
        },
        "then": {
          "properties": {
            "value": {
              "type": "string",
              "title": "iap",
              "enum": [
                "a",
                "b"
              ],
              "enumNames": [
                "asd",
                "bnm"
              ]
            }
          }
        }
      },
      {
        "if": {
          "properties": {
            "key": {
              "const": "bundle"
            }
          }
        },
        "then": {
          "properties": {
            "value": {
              "type": "string",
              "title": "bundle",
              "enum": [
                "c",
                "d"
              ],
              "enumNames": [
                "cvb",
                "dfg"
              ]
            }
          }
        }
      }
    ]
  }
}
```
Using version: 4.2.3 but also have the same issue with v5.1.0
I am facing with the issue of: 
`could not merge subschemas in allOf:
Error: Could not resolve values for path:"properties.value.enum". They are probably incompatible. Values: 
[
  "a",
  "b"
]
[
  "c",
  "d"
]
`
It always gives the same warning even in the playground in the console

**Comment by heath-freenome** [comment]
@sercankavdir It appears that the library we are using isn't really supporting if/then/else yet.
