### ISSUE TITLE
Schema Dependency billing_address field  still present in form data even if I remove data in credit_card

### ISSUE THREAD

**Issue by aloksingh5446** [rjsf-team/react-jsonschema-form#3446]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

material-ui

### What is your question?
```
{
  "type": "object",

  "properties": {
    "name": { "type": "string" },
    "credit_card": { "type": "number" }
  },

  "required": ["name"],

  "dependencies": {
    "credit_card": {
      "properties": {
        "billing_address": { "type": "string" }
      },
      "required": ["billing_address"]
    }
  }
}
```

**Comment by heath-freenome** [comment]
@aloksingh5446 So we don't have perfect support for dependencies in our code. If you pass true for the `omitExtraData` prop on the form then `billing_address` will be removed on submit. Hope this helps
