### ISSUE TITLE
No widget "int64" for type "integer" issue with format set to int64

### ISSUE THREAD

**Issue by veyronB2** [rjsf-team/react-jsonschema-form#3448]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

bootstrap-4

### What is your question?

Hi all, 

I'm after some advice please. 

I'm building dynamic forms based on a schema which contains various format properties such as _int64, double, int32_, _uuid_ and few others and always get a message similar to the one in the subject. Without it, everything seems OK i.e. errors checking etc. 

I have managed to bypass the error message by creating a custom widget for int64 for example but then the error checking stops working for the entire form and not just the single field. 

```
import UpDownWidget from "react-jsonschema-form/lib/components/widgets/UpDownWidget.js" 

const schema = {
    "type": "object",
    "required": [
        "account",
    ],
    "properties": {
        "Reference": {
            "type": "string",
            "description": "Testing description",
            "nullable": true,
            "minLength":5,
        },
        "account": {
            "type": "integer",
            "minLength":5,
            "pattern":"^(0|[1-9][0-9]*)$",
            "format": 'int64',
        }
    },
    "additionalProperties": false
};

const customwidgets= {
       "int64": UpDownWidget,
    }

<Form schema={schema}
        widgets={ customwidgets }
        onSubmit={()=> console.log("Submitted")}
        noHtml5Validate={true}

       />
  );
```

I've tried using the play ground and I'm getting the same result unfortunately. 

Is it possible to somehow ignore format property if not, how to make error checking work with this approach if possible at all. 

My schema also contains fields exclusiveMaximum or exclusiveMinimum and I would like to ignore these as well as they seem to effect error checking as well i.e no inline errors are showing.

Any help is much appreciated

**Comment by heath-freenome** [comment]
@veyronB2 can you please provide a playground link for the issue you seeing? I tried using the schema you provided in this [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJSZWZlcmVuY2UiOiJhc2Rmc2EiLCJhY2NvdW50IjoxMjM0MzIyM30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsiYWNjb3VudCJdLCJwcm9wZXJ0aWVzIjp7IlJlZmVyZW5jZSI6eyJ0eXBlIjoic3RyaW5nIiwiZGVzY3JpcHRpb24iOiJUZXN0aW5nIGRlc2NyaXB0aW9uIiwibnVsbGFibGUiOnRydWUsIm1pbkxlbmd0aCI6NX0sImFjY291bnQiOnsidHlwZSI6ImludGVnZXIiLCJtaW5MZW5ndGgiOjUsInBhdHRlcm4iOiJeKDB8WzEtOV1bMC05XSopJCIsImZvcm1hdCI6ImludDY0In19LCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2V9LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiYm9vdHN0cmFwLTQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsInZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6dHJ1ZSwibGl2ZU9taXQiOmZhbHNlfX0=) and it seems to be working fine. Are you using the v5 release? It seems like maybe you are using the ancient 1.x and unsupported release.

**Comment by igorbrasileiro** [comment]
@heath-freenome i'm trying do something like this as @veyronB2 tried to do, but the `pattern` property isn't being considered. [example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJSZWZlcmVuY2UiOiJhc2Rmc2EiLCJhY2NvdW50IjoiYWFhYWFhIn0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsiYWNjb3VudCJdLCJwcm9wZXJ0aWVzIjp7IlJlZmVyZW5jZSI6eyJ0eXBlIjoic3RyaW5nIiwiZGVzY3JpcHRpb24iOiJUZXN0aW5nIGRlc2NyaXB0aW9uIiwibnVsbGFibGUiOnRydWUsIm1pbkxlbmd0aCI6NX0sImFjY291bnQiOnsidHlwZSI6InN0cmluZyIsIm1pbkxlbmd0aCI6NSwicGF0dGVybiI6IlxcZCoifX0sImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjpmYWxzZX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJib290c3RyYXAtNCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjp0cnVlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)
