### ISSUE TITLE
Field with property name having "/" slash are not highlighted on error

### ISSUE THREAD

**Issue by jaimesangcap** [rjsf-team/react-jsonschema-form#3452]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

antd

### Version

5.1.0

### Current Behavior

When the property name has `/` like `user/password`. Field error is not displaying properly

https://user-images.githubusercontent.com/1907740/221017380-f9da3d2b-7caa-4a5b-83bb-252590a48187.mov

### Expected Behavior

In Step 3 & 4 of reproduce step, the Password input should be in red and error message below it should show

### Steps To Reproduce

In the [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ1c2VyL3VzZXJuYW1lIjoiQ2h1Y2siLCJ1c2VyL3Bhc3N3b3JkIjoiMTIifSwic2NoZW1hIjp7InRpdGxlIjoiQSByZWdpc3RyYXRpb24gZm9ybSIsImRlc2NyaXB0aW9uIjoiQSBzaW1wbGUgZm9ybSBleGFtcGxlLiIsInR5cGUiOiJvYmplY3QiLCJyZXF1aXJlZCI6WyJ1c2VyL3VzZXJuYW1lIiwidXNlci9wYXNzd29yZCJdLCJwcm9wZXJ0aWVzIjp7InVzZXIvdXNlcm5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiVXNlcm5hbWUiLCJkZWZhdWx0IjoiQ2h1Y2sifSwidXNlci9wYXNzd29yZCI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJQYXNzd29yZCIsIm1pbkxlbmd0aCI6Nn19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiIsInVpOnBsYWNlaG9sZGVyIjoidWk6ZW1wdHlWYWx1ZSBjYXVzZXMgdGhpcyBmaWVsZCB0byBhbHdheXMgYmUgdmFsaWQgZGVzcGl0ZSBiZWluZyByZXF1aXJlZCIsInVpOmF1dG9jb21wbGV0ZSI6ImZhbWlseS1uYW1lIn0sImxhc3ROYW1lIjp7InVpOmF1dG9jb21wbGV0ZSI6ImdpdmVuLW5hbWUifSwiYWdlIjp7InVpOndpZGdldCI6InVwZG93biIsInVpOnRpdGxlIjoiQWdlIG9mIHBlcnNvbiIsInVpOmRlc2NyaXB0aW9uIjoiKGVhcnRoIHllYXIpIn0sImJpbyI6eyJ1aTp3aWRnZXQiOiJ0ZXh0YXJlYSJ9LCJwYXNzd29yZCI6eyJ1aTp3aWRnZXQiOiJwYXNzd29yZCIsInVpOmhlbHAiOiJIaW50OiBNYWtlIGl0IHN0cm9uZyEifSwidGVsZXBob25lIjp7InVpOm9wdGlvbnMiOnsiaW5wdXRUeXBlIjoidGVsIn19fSwidGhlbWUiOiJhbnRkIiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

1. Submit the form with empty password
2.  The Password input should in red border. Below the error message `must have required property 'Password'` is shown
3.  Enter at least 1 char to Password input to trigger `minLength: 6` validation. Then submit form
4. The password input is not in red border. There is no error message below the input
5. Try renaming the property `user/password` to `user_password`, Step 3 & 4 works us expected (red border + error message below)

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by heath-freenome** [comment]
@jaimesangcap So this appears to be an issue with how AJV is working with your keys. If you look at the raw AJV validator messages in your playground you'll see the following:
```
{
  "errors": [
    {
      "instancePath": "/user~1password",
      "schemaPath": "#/properties/user~1password/minLength",
      "keyword": "minLength",
      "params": {
        "limit": 6
      },
      "message": "must NOT have fewer than 6 characters",
      "schema": 6,
      "parentSchema": {
        "type": "string",
        "title": "Password",
        "minLength": 6
      },
      "data": "23"
    }
  ]
}
```
Note that the `/` is surprisingly converted to `~1` by AJV. Not sure exactly why they do that. Are you willing to file an issue against their code to get this fixed? Also, is there a reason why you need the `/`? Changing them to the `:` delimiter which AJV8 now support works fine.

**Comment by jaimesangcap** [comment]
I see. Thanks for looking into it. I'm using ClojureScript and the `/` is used to namespace the keys (common practice).

I created an issue in the AJV library. Let's see what they think about the issue

**Comment by heath-freenome** [comment]
@jaimesangcap Can you provide a reference to the AJV issue? Or maybe just close this one in favor of that one?

**Comment by jaimesangcap** [comment]
Link to the issue https://github.com/ajv-validator/ajv/issues/2226

Closing this one for now
