### ISSUE TITLE
Incorrect empty check fails on 0 range value

### ISSUE THREAD

**Issue by c-dante** [rjsf-team/react-jsonschema-form#3458]
https://github.com/rjsf-team/react-jsonschema-form/blob/8be4ef21dfb8775f58b7bc16647e59cd22fbebbc/packages/mui/src/RangeWidget/RangeWidget.tsx#L39

For ranges that include `0`, this falsy check switches the value to the default instead of the correct value.

**Comment by heath-freenome** [comment]
@c-dante Good catch, are you willing to provide a fix for the `mui` and `material-ui` packages (they have the same code)?

**Comment by c-dante** [comment]
There's another issue where the value is undefined it flips the element from begin controlled/uncontrolled and throws a lot of warnings during development. Can likely patch that, too

**Comment by c-dante** [comment]
@heath-freenome let me know what else is needed https://github.com/rjsf-team/react-jsonschema-form/pull/3465 not sure what your release process is re updating package semver

**Comment by heath-freenome** [comment]
> There's another issue where the value is undefined it flips the element from begin controlled/uncontrolled and throws a lot of warnings during development. Can likely patch that, too

Is there an issue related to this problem? If not, please create one with reproducible steps and then provide a PR if you feel up to it.
