### ISSUE TITLE
Upgrade fluent ui version to version 8

### ISSUE THREAD

**Issue by Marcinthedev** [rjsf-team/react-jsonschema-form#3463]
Are there any plans to upgrade fluent ui dependency to version 8? They already released version 9.

I would appreciate if I could use version 8 in the project

```
npm ERR! While resolving: @rjsf/fluent-ui@5.1.0
npm ERR! Found: @fluentui/react@8.105.1
npm ERR! node_modules/@fluentui/react
npm ERR!   @fluentui/react@"^8.103.2" from the root project
```

**Comment by heath-freenome** [comment]
@Marcinthedev The themes tend to be upgraded by people who need them. Are you able to do the work?
