### ISSUE TITLE
Adding classnames to input field itself instead of wrapper

### ISSUE THREAD

**Issue by CharowDEV** [rjsf-team/react-jsonschema-form#3474]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### What is your question?

Seems like I can't find a way to add classnames to the input field itself. And I'm not sure if it's possible or not. If I set the classnames like in [this example](https://react-jsonschema-form.readthedocs.io/en/v1.8.1/form-customization/#custom-css-class-names), the classnames will be added to the wrapper of the input field. 

So I'm looking for the same functionality as `'ui:rootFieldId'`, but then for classnames. Something like `'ui:rootFieldClassname': 'customClassname',`

The code:
```
import { RJSFSchema, UiSchema } from '@rjsf/utils';

export const schema: RJSFSchema = {
  title: 'Search',
  type: 'string'
};

export const uiSchema = (placeholderText: string): UiSchema => ({
  'ui:classNames': 'w-full',
  'ui:options': {
    label: false
  },
  'ui:placeholder': placeholderText,
  'ui:submitButtonOptions': {
    norender: true
  }
});

```

Already tried, without success:
```
  'ui:classNames': 'w-full',
  'ui:rootFieldClassname': 'w-full',
  'ui:input': {
    "ui:classNames": 'w-full'
  },
  'Search': {
    classNames: 'w-full',
    'ui:input': {
      classNames: 'w-full'
    }
  },
  ```

**Comment by heath-freenome** [comment]
@CharowDEV you are right, we do not support adding classnames on widgets, only the field wrappers. It's a limitation right now. If you absolutely need to add a classname onto the input, you could create a wrapper around the `BaseInputTemplate` that passes it into the template. See this [comment](https://github.com/rjsf-team/react-jsonschema-form/issues/3481#issuecomment-1460525542) for how you could do this with className.

**Comment by CharowDEV** [comment]
> @CharowDEV you are right, we do not support adding classnames on widgets, only the field wrappers. It's a limitation right now. If you absolutely need to add a classname onto the input, you could create a wrapper around the `BaseInputTemplate` that passes it into the template. See this [comment](https://github.com/rjsf-team/react-jsonschema-form/issues/3481#issuecomment-1460525542) for how you could do this with className.

Ah thanks! I wasn't sure if it was my project related or just not supported. But will check out the solution you mentioned and close this issue. Thanks again!
