### ISSUE TITLE
ui:submitButtonOptions className doesnot override

### ISSUE THREAD

**Issue by sandeepscet** [rjsf-team/react-jsonschema-form#3480]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

bootstrap-4

### Version

5.x

### Current Behavior

```
"UiSchema" : {
  "ui:submitButtonOptions": {
    "submitText": "Submit",
    "norender": false,
    "props": {
      "disabled": false,
      "className": "btn btn-primary"
    }  
}
}
```

This does not override the className, its append.
btn-info class still apply in this case `btn btn-info btn btn-primary`

### Expected Behavior

It should override the class names of submit button.
Class should be  `btn btn-primary`

### Steps To Reproduce

Load form with below UI Schema
```
"UiSchema" : {
  "ui:submitButtonOptions": {
    "submitText": "Submit",
    "norender": false,
    "props": {
      "disabled": false,
      "className": "btn btn-primary"
    }  
}
}
```
or change className to btn-primary in the UISchema tab of UI Options  (Second Button) on [playground](https://rjsf-team.github.io/react-jsonschema-form/)

### Environment

```markdown
- OS: Windows
- Node:v18.14.2
- npm:9.5.0
```

**Comment by heath-freenome** [comment]
@sandeepscet It all appears to be working. I created an [example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayJ9LCJzY2hlbWEiOnsidGl0bGUiOiJBIHJlZ2lzdHJhdGlvbiBmb3JtIiwiZGVzY3JpcHRpb24iOiJBIHNpbXBsZSBmb3JtIGV4YW1wbGUuIiwidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbImZpcnN0TmFtZSJdLCJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJGaXJzdCBuYW1lIiwiZGVmYXVsdCI6IkNodWNrIn19fSwidWlTY2hlbWEiOnsidWk6c3VibWl0QnV0dG9uT3B0aW9ucyI6eyJzdWJtaXRUZXh0IjoiU3VibWl0Iiwibm9yZW5kZXIiOmZhbHNlLCJwcm9wcyI6eyJkaXNhYmxlZCI6ZmFsc2UsImNsYXNzTmFtZSI6ImJ0biBidG4tZGFuZ2VyIn19fSwidGhlbWUiOiJib290c3RyYXAtNCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=) where I used `btn btn-danger` and it worked fine.

**Comment by sandeepscet** [comment]
@heath-freenome 
It's not working with this [jsfiddle  ](https://jsfiddle.net/spwr31of/), any wrong parameters did I use?

**Comment by heath-freenome** [comment]
> @heath-freenome It's not working with this [jsfiddle ](https://jsfiddle.net/spwr31of/), any wrong parameters did I use?

Your JSFiddle is using the ancient and unsupported 1.81 version of rjsf. We are on 5.2.0 in the playground.

**Comment by sandeepscet** [comment]
The template link has outdated include.
![image](https://user-images.githubusercontent.com/1390862/224694973-d49ea7b3-d9e9-4799-a9c3-5012e73934eb.png)

My issue was I didn't select the bootstap4 theme on the playground

@heath-freenome  Thanks for the response.

**Comment by heath-freenome** [comment]
Ah... well then we had better fix our JSFiddle template
