### ISSUE TITLE
checked boxes show field？

### ISSUE THREAD

**Issue by xyy7260** [rjsf-team/react-jsonschema-form#3482]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

antd

### Description
```
{
  "info": {
    "name": "info",
    "title": "info",
    "type": "array",
    "items": {
      "type": "string",
      "enum": [
        "name",
        "age",
        "gender",
        "height",
        "weight",
        "phone number",
        "Birthday"
      ]
    }
  }
}

```

I select name and the name field appears

e.g.  we checked('name','age','weight') 
` 
"name": {
              "type": "string"
            },
"age": {
              "type": "string"
            },
"weight": {
              "type": "string"
            },
`
e.g.  we checked('height') 
` 
"height": {
              "type": "string"
            },
`

**Comment by heath-freenome** [comment]
@xyy7260 I don't understand what you are asking. Can you please provide an example using our [playground](https://rjsf-team.github.io/react-jsonschema-form/) and give us steps that show what you are asking about?

**Comment by xyy7260** [comment]
@heath-freenome  
[playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOlsiQSIsIkIiXX0sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJGaXJzdCBuYW1lIiwidW5pcXVlSXRlbXMiOnRydWUsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIkEiLCJCIiwiQyIsIkQiXX19fSwiZGVwZW5kZW5jaWVzIjp7ImZpcnN0TmFtZSI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsiY29udGFpbnMiOnsiY29uc3QiOiJBIn0sIm5vdCI6eyJjb250YWlucyI6eyJjb25zdCI6IkIifX19LCJhLWRlc2MiOnsidHlwZSI6InN0cmluZyJ9fX0seyJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJjb250YWlucyI6eyJjb25zdCI6IkIifSwibm90Ijp7ImNvbnRhaW5zIjp7ImNvbnN0IjoiQSJ9fX0sImItZGVzYyI6eyJ0eXBlIjoic3RyaW5nIn19fSx7InByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7ImFsbE9mIjpbeyJjb250YWlucyI6eyJjb25zdCI6IkEifX0seyJjb250YWlucyI6eyJjb25zdCI6IkIifX1dfSwiYS1kZXNjIjp7InR5cGUiOiJzdHJpbmcifSwiYi1kZXNjIjp7InR5cGUiOiJzdHJpbmcifX19XX19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOndpZGdldCI6ImNoZWNrYm94ZXMifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

 
`{
  "dependencies": {

    "firstName": {
      "oneOf": [
        {
          "properties": {
            "firstName": {
              "contains": {
                "const": "A"
              },
              "not": {
                "contains": {
                  "const": "B"
                }
              }
            },
            "a-desc": {
              "type": "string"
            }
          }
        },
        {
          "properties": {
            "firstName": {
              "contains": {
                "const": "B"
              },
              "not": {
                "contains": {
                  "const": "A"
                }
              }
            },
            "b-desc": {
              "type": "string"
            }
          }
        },
        {
          "properties": {
            "firstName": {
              "allOf": [
                {
                  "contains": {
                    "const": "A"
                  }
                },
                {
                  "contains": {
                    "const": "B"
                  }
                }
              ]
            },
            "a-desc": {
              "type": "string"
            },
            "b-desc": {
              "type": "string"
            }
          }
        }
      ]
    }
  }
}
`
When there are many options oneOf, you need to write a lot，
Is there a better way to deal with it

**Comment by heath-freenome** [comment]
@xyy7260 Your example seems to work ok. As far as better way, I am not well versed in every aspect of JSON Schema and definitely haven't done much with writing the most optimal schema. I usually use this [documentation](https://json-schema.org/understanding-json-schema/index.html) as a reference when I'm trying to figure stuff out.

**Comment by xyy7260** [comment]
@heath-freenome according to [playground linc](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOlsiQSIsIkIiXX0sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJGaXJzdCBuYW1lIiwidW5pcXVlSXRlbXMiOnRydWUsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIkEiLCJCIiwiQyIsIkQiXX19fSwiZGVwZW5kZW5jaWVzIjp7ImZpcnN0TmFtZSI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsiY29udGFpbnMiOnsiY29uc3QiOiJBIn0sIm5vdCI6eyJjb250YWlucyI6eyJjb25zdCI6IkIifX19LCJhLWRlc2MiOnsidHlwZSI6InN0cmluZyJ9fX0seyJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJjb250YWlucyI6eyJjb25zdCI6IkIifSwibm90Ijp7ImNvbnRhaW5zIjp7ImNvbnN0IjoiQSJ9fX0sImItZGVzYyI6eyJ0eXBlIjoic3RyaW5nIn19fSx7InByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7ImFsbE9mIjpbeyJjb250YWlucyI6eyJjb25zdCI6IkEifX0seyJjb250YWlucyI6eyJjb25zdCI6IkIifX1dfSwiYS1kZXNjIjp7InR5cGUiOiJzdHJpbmcifSwiYi1kZXNjIjp7InR5cGUiOiJzdHJpbmcifX19XX19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOndpZGdldCI6ImNoZWNrYm94ZXMifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==) think there is too much nesting logic and I will write a lot of code in this . Is there a better way to solve the problem that the corresponding condition field appears when the multiCheckbox is checked?
Such as our options have [' A ', 'B', 'C', 'D', 'E'] multiCheckbox,users could be selected (A,B,D）, the corresponding content should appear after selection

**Comment by heath-freenome** [comment]
@xyy7260 You could always write a custom widget that implements exactly what you want for these fields, but then you are maintaining it yourself.

**Comment by xyy7260** [comment]
@heath-freenome  thank you ，

**Comment by ehennestad** [comment]
You could also quite easily write a javascript function that builds the json as a javascript object for you by looping through each of the conditions you want to add, and then save the javascript object as a json in the end

**Comment by xyy7260** [comment]
@ehennestad  [playground line](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOlsiQSIsIkIiXX0sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJGaXJzdCBuYW1lIiwidW5pcXVlSXRlbXMiOnRydWUsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIkEiLCJCIiwiQyIsIkQiXX19fSwiZGVwZW5kZW5jaWVzIjp7ImZpcnN0TmFtZSI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsiY29udGFpbnMiOnsiY29uc3QiOiJBIn0sIm5vdCI6eyJjb250YWlucyI6eyJjb25zdCI6IkIifX19LCJhLWRlc2MiOnsidHlwZSI6InN0cmluZyJ9fX0seyJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJjb250YWlucyI6eyJjb25zdCI6IkIifSwibm90Ijp7ImNvbnRhaW5zIjp7ImNvbnN0IjoiQSJ9fX0sImItZGVzYyI6eyJ0eXBlIjoic3RyaW5nIn19fSx7InByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7ImFsbE9mIjpbeyJjb250YWlucyI6eyJjb25zdCI6IkEifX0seyJjb250YWlucyI6eyJjb25zdCI6IkIifX1dfSwiYS1kZXNjIjp7InR5cGUiOiJzdHJpbmcifSwiYi1kZXNjIjp7InR5cGUiOiJzdHJpbmcifX19XX19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOndpZGdldCI6ImNoZWNrYm94ZXMifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)
There is a field with three options (A; B; C), the corresponding condition field can appear when I select (A), (B), (C) respectively or both (A,B,C), 
but no condition field will appear when I select (A,B), (B,C). Do I need to list all the attributes in [A,B,C]? Or that this multi-selection approach only supports two control logics

**Comment by xyy7260** [comment]
@ehennestad 
@heath-freenome 
 [playground line](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOlsiQSIsIkIiXX0sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJGaXJzdCBuYW1lIiwidW5pcXVlSXRlbXMiOnRydWUsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIkEiLCJCIiwiQyIsIkQiXX19fSwiZGVwZW5kZW5jaWVzIjp7ImZpcnN0TmFtZSI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsiY29udGFpbnMiOnsiY29uc3QiOiJBIn0sIm5vdCI6eyJjb250YWlucyI6eyJjb25zdCI6IkIifX19LCJhLWRlc2MiOnsidHlwZSI6InN0cmluZyJ9fX0seyJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJjb250YWlucyI6eyJjb25zdCI6IkIifSwibm90Ijp7ImNvbnRhaW5zIjp7ImNvbnN0IjoiQSJ9fX0sImItZGVzYyI6eyJ0eXBlIjoic3RyaW5nIn19fSx7InByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7ImFsbE9mIjpbeyJjb250YWlucyI6eyJjb25zdCI6IkEifX0seyJjb250YWlucyI6eyJjb25zdCI6IkIifX1dfSwiYS1kZXNjIjp7InR5cGUiOiJzdHJpbmcifSwiYi1kZXNjIjp7InR5cGUiOiJzdHJpbmcifX19XX19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOndpZGdldCI6ImNoZWNrYm94ZXMifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)
There is a field with three options (A; B; C), the corresponding condition field can appear when I select (A), (B), (C) respectively or both (A,B,C), 
but no corresponding field will appear when I select (A,B), (B,C). 
Do I need to list all the attributes in [A,B,C]? Or this option is not supported？
