### ISSUE TITLE
Getting error after importing '@rjsf/mui' in React 18.2

### ISSUE THREAD

**Issue by ashi015** [rjsf-team/react-jsonschema-form#3485]
I am using React 18.2 version.
When I try to import Form from "@rjsf/mui"; we are getting a following error
```
ERROR in ./node_modules/@rjsf/mui/dist/mui.esm.js 367:27-58
export 'TranslatableString' (imported as 'TranslatableString') was not found in '@rjsf/utils'
```

**Comment by ashi015** [comment]
@heath-freenome , `TranslatableString ` has been imported in ./node_modules/@rjsf/mui/dist/mui.esm.js But I do not see this in @rjsf/utils.
I am using the following versions
```
    "@rjsf/utils": "^5.1.0"
    "@rjsf/mui": "^5.2.1"
```

**Comment by heath-freenome** [comment]
@ashi015 It is highly recommended to keep all of `@rjsf` at the same version level because new types are added in `@rjsf/utils`. In this case the type for `TranslatableString` was added in 5.2.0

**Comment by ashi015** [comment]
Thank you for your response @heath-freenome . I updated  `@rjsf/mui `and `@rjsf/utils` to `^5.2.1` version. But now I am getting the following issue
`WrapIfAdditionalTemplate.tsx:43 Uncaught TypeError: translateString is not a function at  WrapIfAdditionalTemplate`

**Comment by ashi015** [comment]
Thank you for your response @heath-freenome . I updated all the @rjsf to "^5.2.1" .
It is working fine now.
Thank you again :)
