### ISSUE TITLE
how to get a nested schema to display more than one column of inputs

### ISSUE THREAD

**Issue by dagda1** [rjsf-team/react-jsonschema-form#3490]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

mui

### What is your question?

I have this `ObjectFieldTemplate` which works great in a non nested schema:

```ts
export function FluidFormLayout(props: ObjectFieldTemplateProps): JSX.Element {
  const { properties, description, title } = props;

  return (
    <Box marginBottom={2}>
      <Box component="h1" marginBottom={2}>
        {title}
      </Box>
      <Grid container spacing={3}>
        {properties.map(prop => (
          <Grid item xs={12} md={6} lg={4} key={prop.content.key}>
            {prop.content}
          </Grid>
        ))}
      </Grid>
      {description}
    </Box>
  );
}
```

![aa](https://user-images.githubusercontent.com/118328/224042912-1646a737-4dc1-487a-8e1c-f41bae568572.png)

But with a nested schema, I get this:

![ad](https://user-images.githubusercontent.com/118328/224044745-ad04ac13-99af-4ed8-827a-fe4adf5cc58d.png)

I need to keep the nested structure or else there will be elements with the same id and name.

The `ObjectFieldTemplate` was perfect in the non-nested example but is there anyway to stop the grouping without changing the data structure?

**Comment by heath-freenome** [comment]
It seems like you will need to build your Template do simply use grids rather than boxes and grids. I imagine that once you understand how the nesting structures work with RJSF (using the React Component inspector in the browser inspector) you'll be able to figure it out. Sorry I can't be of much more help.

**Comment by dagda1** [comment]
I ended up having to do this in my custom `ObjectFieldTemplate`

```ts
return (
  <>
    {isContainer ? (
      properties[0].content
    ) : (
      <Grid container spacing={2} className={styles.item}>
        {properties.map((element, index) =>
          element.hidden ? (
            element.content
          ) : (
            <Grid
              item
              xs={12}
              md={6}
            style={{ marginBottom: '10px' }}
          >
            {element.content}
          </Grid>
 ```

I have some logic to decide whether it is a top level key (`isContainer`) or the actual fields to create the inputs from.

I could not think of a better way.

One thing I did find surprising is that this `ObjectFieldTemplate`:

```ts
<Form
  templates={{
    ObjectFieldTemplate: FluidObjectFieldTemplate,
  }}
```

Is different than:

```ts
<Form
   uiSchema={{
     ...uiSchema,
     ['ui:ObjectFieldTemplate']: FluidObjectFieldTemplate
```

Am I right about that?  Are they different properties?

**Comment by heath-freenome** [comment]
> One thing I did find surprising is that this `ObjectFieldTemplate`:
> 
> ```ts
> <Form
>   templates={{
>     ObjectFieldTemplate: FluidObjectFieldTemplate,
>   }}
> ```
> 
> Is different than:
> 
> ```ts
> <Form
>    uiSchema={{
>      ...uiSchema,
>      ['ui:ObjectFieldTemplate']: FluidObjectFieldTemplate
> ```
> 
> Am I right about that? Are they different properties?

Yes, the first one replaces the template used everywhere whereas the second overrides the template for the root object  only.
