### ISSUE TITLE
5.2.1 has broken file uploads (schema attached)

### ISSUE THREAD

**Issue by billycrid** [rjsf-team/react-jsonschema-form#3504]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.2.1

### Current Behavior

Currently with 5.2.1, when trying to upload a file with default bootstrap configuration: after attaching a .csv file (with uiSchema specifying only .csv format allowed). after clicking Submit the field is highlighted with 'field is required'

### Expected Behavior

File should be attached to the form as previously was in 5.2.0

### Steps To Reproduce

1. checkout 5.2.1 version
2. use inputSchema: 
```
{
  "properties": {
    "uploadedFile": {
      "items": {
        "format": "data-url",
        "type": "string"
      },
      "title": "some file",
      "type": "array"
    }
  },
  "required": [
    "uploadedFile"
  ],
  "type": "object"
}
```
3. use uiSchema:
```
{
  "uploadedFile": {
    "ui:options": {
      "accept": [
        ".csv"
      ]
    }
  }
}
```
4. try to submit the form after uploading a .csv file
5. error will show as if field is not populated
6. then switch to version 5.2.0 of the lib and repeat steps and the form will submit correctly 

can be recreated in this codesandbox: https://codesandbox.io/embed/condescending-raman-fylt3x?fontsize=14&hidenavigation=1&theme=dark

### Environment

```markdown
- OS: OSX latest
- Node: 16.17.1
- npm: 8.15.0
```

**Comment by heath-freenome** [comment]
@billycrid so I just put your example into the [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ1cGxvYWRlZEZpbGUiOlsiZGF0YTp0ZXh0L2NzdjtuYW1lPW1hbmlmZXN0LmNzdjtiYXNlNjQsVTJGdGNHeGxJRWxFTEVOaGJtTmxjaUJVZVhCbENqRXdNakV3TVMxd2IzTjBMRU52Ykc5eVpXTjBZV3dnUW1WdWFXZHUiXX0sInNjaGVtYSI6eyJwcm9wZXJ0aWVzIjp7InVwbG9hZGVkRmlsZSI6eyJpdGVtcyI6eyJmb3JtYXQiOiJkYXRhLXVybCIsInR5cGUiOiJzdHJpbmcifSwidGl0bGUiOiJzb21lIGZpbGUiLCJ0eXBlIjoiYXJyYXkifX0sInJlcXVpcmVkIjpbInVwbG9hZGVkRmlsZSJdLCJ0eXBlIjoib2JqZWN0In0sInVpU2NoZW1hIjp7InVwbG9hZGVkRmlsZSI6eyJ1aTpvcHRpb25zIjp7ImFjY2VwdCI6WyIuY3N2Il19fX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=) and could not reproduce the issue. Do you have any customizations?

**Comment by billycrid** [comment]
@heath-freenome please see the defect recreated in a codesandbox URL:  https://codesandbox.io/embed/condescending-raman-fylt3x?fontsize=14&hidenavigation=1&theme=dark

hopefully this helps to recreate

**Comment by billycrid** [comment]
@heath-freenome  yeah this is exactly the issue, because of the field is validating as not being filled out, we are getting the HTML5 error suddenly which is blocking form submission even though all required fields are actually populated. Disabling Html5 Validation should not be an acceptable 'fix' for this as we still require HTML5 validation on all fields in the form. Can we not have a fix that actually resolves this HTML validation?
