### ISSUE TITLE
Unable to install "@rjsf/antd" theme to project with latest (5.3.1) Ant Design

### ISSUE THREAD

**Issue by Deemetr** [rjsf-team/react-jsonschema-form#3507]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

antd

### Version

5.x

### Current Behavior

```
npm ERR! Could not resolve dependency:
npm ERR! peer @ant-design/icons@"^4.0.0" from @rjsf/antd@5.2.1
npm ERR! node_modules/@rjsf/antd
npm ERR!   @rjsf/antd@"5.2.1" from the root project
```

### Expected Behavior

Installed ```@rjsf/antd``` package

### Steps To Reproduce

1. Create new React project (Vite)
2. Install via npm latest Ant Design ui kit (```npm install antd```)
3. install ```@rjsf/antd``` (```npm i @rjsf/antd```)

Or 
1. Clone repo ```https://github.com/Deemetr/-rjsf-antd__issue```
2. cd ```-rjsf-antd__issue```
3. ```npm i```

### Environment

```markdown
- OS: Windows 11
- Node:18.14.2
- npm:9.5.0
```

**Comment by Napalm4577** [comment]
Same here

package.json
```json
"@ant-design/icons": "^5.0.1",
"@rjsf/core": "^5.2.1",
```

When install `npm install @rjsf/antd`
```bash
npm ERR! Found: @ant-design/icons@5.0.1
npm ERR! node_modules/@ant-design/icons
npm ERR!   @ant-design/icons@"^5.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @ant-design/icons@"^4.0.0" from @rjsf/antd@5.2.1
npm ERR! node_modules/@rjsf/antd
npm ERR!   @rjsf/antd@"*" from the root project

```

**Comment by fran122157** [comment]
> @Deemetr @Napalm4577 We would love some help upgrading the `antd` theme to 5.x. As part-time volunteers who do not use `antd` theme, we have avoided doing major upgrades of it since we don't know to expect from the newer version. Bonus points if the changes needed to upgrade to the newest release continue to allow our users to use the currently supported release.

Reading [Ant Design V4 to V5 migration guide](https://ant.design/docs/react/migration-v5) it seems that the only breaking change introduced in V5 (that affects RJSF Antd theme) is the deprecation of moment.js in favor of day.js 

I think [this](https://github.com/rjsf-team/react-jsonschema-form/blob/43c7d5d8b03d430eca97f8a64216e0aa6b1b1639/packages/antd/src/components/DatePicker/index.ts) can be removed and instead use the default datepicker exposed by AntD

FYI: Just forced the installation of Antd v5 on my repo which is using RJSF v5, and everything worked out just fine.

**Comment by heath-freenome** [comment]
@fran122157 That is good information. How do the default date pickers differ? Also, are you willing to provide a PR for the fix?

**Comment by fran122157** [comment]
I have created a [PR](https://github.com/fran122157/react-jsonschema-form/pull/1) in my own fork. 

There's a change I did not see that was introduced in v5: Removal of less files in Antd codebase.

FYI: The PR is just for reference, I tried to test my changes in the playground but I have to link my local changes with the antd version the playground is using and I do not have the time right now.

Please feel free to use any of these changes

**Comment by ganshin-yaroslav** [comment]
May I help with this?

**Comment by 5idu** [comment]
@heath-freenome Is there any progress?

**Comment by heath-freenome** [comment]
@5idu Can you try the latest 5.x release, I believe https://github.com/rjsf-team/react-jsonschema-form/pull/3849 completed the work

**Comment by Gam3sFan** [comment]
I still get the error with the last version: 
```
npm ERR! While resolving: redplanetai@0.1.0
npm ERR! Found: @ant-design/icons@5.2.6
npm ERR! node_modules/@ant-design/icons
npm ERR!   @ant-design/icons@"^5.2.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @ant-design/icons@"^4.0.0" from @rjsf/antd@5.14.1
npm ERR! node_modules/@rjsf/antd
npm ERR!   @rjsf/antd@"*" from the root project
```

**Comment by heath-freenome** [comment]
@Gam3sFan thanks for catching that. I will update the peer dependencies in the patch release soon

**Comment by heath-freenome** [comment]
@Gam3sFan The release should be ready in a few hours
