### ISSUE TITLE
MUI radio widget initializes as uncontrolled when schema has no default value

### ISSUE THREAD

**Issue by tyrdavis** [rjsf-team/react-jsonschema-form#3511]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

mui

### Version

5.1.0

### Current Behavior

When using the MUI theme, a field using `RadioWidget` with no default value renders as uncontrolled. In a non-production app, there is a MUI warning logged to the console, which unfortunately can't be seen in the playground. The widget being uncontrolled causes some strange behaviors, such as it no longer responding to programmatic changes to its value. 

[Playground link with the issue](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJyYWRpbyI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJvbmUiLCJ0d28iLCJ0aHJlZSJdfX19LCJ1aVNjaGVtYSI6eyJyYWRpbyI6eyJ1aTp3aWRnZXQiOiJyYWRpbyJ9fSwidGhlbWUiOiJtYXRlcmlhbC11aS01IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

In the above playground, if you select one of the radio options, then attempt to use the programmatic reset button, the field does not reset its value due to it being uncontrolled. Compare to [this playground link using the default theme](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJyYWRpbyI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJvbmUiLCJ0d28iLCJ0aHJlZSJdfX19LCJ1aVNjaGVtYSI6eyJyYWRpbyI6eyJ1aTp3aWRnZXQiOiJyYWRpbyJ9fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==) and [this playground link using MUI but with a default defined](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJyYWRpbyI6Im9uZSJ9LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsicmFkaW8iOnsidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJvbmUiLCJlbnVtIjpbIm9uZSIsInR3byIsInRocmVlIl19fX0sInVpU2NoZW1hIjp7InJhZGlvIjp7InVpOndpZGdldCI6InJhZGlvIn19LCJ0aGVtZSI6Im1hdGVyaWFsLXVpLTUiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsInZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19) to see the widget working as expected.

### Expected Behavior

MUI's `RadioGroup` should always be controlled when instantiated by RJSF to prevent unexpected behavior.

### Steps To Reproduce

1. Use a schema with a MUI 5 `RadioWidget` and no `default` defined
2. Select a value in the form
3. Attempt to programmatically change the value of the field; this will fail

### Environment

```markdown
- OS:Ubuntu 22.04
- Node: 16.13.0
- npm: 8.1.0
```

**Comment by tyrdavis** [comment]
I believe the solution to this is to use `null` as the `RadioGroup`'s `value` when `enumOptionsIndexForValue` returns `undefined` [here](https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/mui/src/RadioWidget/RadioWidget.tsx#L44). `RadioGroup` sets itself up as uncontrolled only when `value={undefined}` on its initial mount, so I believe that should satisfy keeping the component's value empty while still being controlled.

**Comment by heath-freenome** [comment]
@tyrdavis I tried your example and the same behavior occurs for `chakra-ui`, `material-ui 4` and `material-ui 5` (it works fine for all the other themes). Would you be willing to update those three themes with your fix and push a PR?
