### ISSUE TITLE
Mui Array Field  AutoComplete not working

### ISSUE THREAD

**Issue by emrahc** [rjsf-team/react-jsonschema-form#3525]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

material-ui

### What is your question?

I have uischema for array. I can use AutoComplete with object fields. But AutoComplete not visible in array. I can see the widget in props.
 ```
 related_cpas: {
    items: {
      "ui:ObjectFieldTemplate": ResponsiveTemplateArray,
      corrective_and_preventive_control_precautions: {
        "ui:widget": "textarea",
        "ui:options": {
          rows: 3,
        },
        actions_taken: {
          "ui:widget": "textarea",
          "ui:options": {
            rows: 3,
          },
        `},`
        assigned_to: {
          "ui:widget": (props: WidgetProps) => {
            console.log("array fields props", props);
            return (
              <AutoCompleteCompanyState
                onChange={props.onChange}
              />
            );
          },
        },
       },
    },
  },
```

I have tried many things but no luck.
Thanks

**Comment by heath-freenome** [comment]
@emrahc Can you create a small example using codesandbox.io? There is not enough information for us to help.
