### ISSUE TITLE
allOf condition not being properly evaluated

### ISSUE THREAD

**Issue by meircarlos** [rjsf-team/react-jsonschema-form#3534]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

[Shared playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJhbmltYWwiOnsiZW51bSI6WyJDYXQiLCJGaXNoIl19fSwiYWxsT2YiOlt7ImlmIjp7InByb3BlcnRpZXMiOnsiYW5pbWFsIjp7ImNvbnN0IjoiQ2F0In19fSwidGhlbiI6eyJwcm9wZXJ0aWVzIjp7ImZvb2QiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsibWVhdCIsImdyYXNzIiwiZmlzaCJdfX0sInJlcXVpcmVkIjpbImZvb2QiXX19XX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

The field `food` is being shown when it should only be shown when `animal` field is set to "Cat".

### Expected Behavior

The field `food` should not be shown when `animal` field is set to "Cat".

### Environment

```markdown
The web playground
```

**Comment by nickgros** [comment]
Not a bug. If `animal` is undefined, then this subschema will always be valid.
```json
{
	"properties": {
		"animal": {
			"const": "Cat"
		}
	}
}
```

If you want this subschema to be invalid when `animal` is undefined, then you need to add `required`:

```json
{
	"properties": {
		"animal": {
			"const": "Cat"
		}
	},
	"required": ["animal"]
}
```

[Playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJhbmltYWwiOnsiZW51bSI6WyJDYXQiLCJGaXNoIl19fSwiYWxsT2YiOlt7ImlmIjp7InByb3BlcnRpZXMiOnsiYW5pbWFsIjp7ImNvbnN0IjoiQ2F0In19LCJyZXF1aXJlZCI6WyJhbmltYWwiXX0sInRoZW4iOnsicHJvcGVydGllcyI6eyJmb29kIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIm1lYXQiLCJncmFzcyIsImZpc2giXX19LCJyZXF1aXJlZCI6WyJmb29kIl19fV19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

**Comment by meircarlos** [comment]
Oh, ok. Sorry for the misunderstanding.

It made sense to me that the subschema would only be valid if the animal was set to "Cat".

Thanks! :D
