### ISSUE TITLE
how can I tell which fields are invalid in an ArrayFieldTemplate

### ISSUE THREAD

**Issue by dagda1** [rjsf-team/react-jsonschema-form#3536]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

material-ui

### What is your question?

I am implementing my own `ArrayFieldTemplate` and I would like to know which fields are invalid but the [ArrayFieldTemplateProps](https://rjsf-team.github.io/react-jsonschema-form/docs/advanced-customization/custom-templates/#arrayfielditemtemplate) only appear to have `rawErrors` but it they are always undefined.

Is there anyway to know which elements of the array are invalid?

**Comment by heath-freenome** [comment]
@dagda1 Does the `errorSchema` have what you need? It should be a nested objected keyed to fields. And for arrays, I believe the fields would be the index

**Comment by dagda1** [comment]
@heath-freenome yes, I found it.  Thanks
