### ISSUE TITLE
How can I clear Errors in an ArrayItemTemplate

### ISSUE THREAD

**Issue by dagda1** [rjsf-team/react-jsonschema-form#3538]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

material-ui

### What is your question?

I have a custom `ArrayFieldTemplate` that splits an array into steps where only 1 item is visible at a time

![aaa](https://user-images.githubusercontent.com/118328/227518388-3fe7a476-a509-4acc-b5a5-60d9db87cfca.png)

If I submit the form then all items become invalid.

Is it possible to reset the errors for certain fields.  I know there is an `ErrorSchemaBuilder` but I'm not sure how I would use that in an `ArrayFieldTemplate`.

Is it possible to use the `ErrorSchemaBuilder` in an `ArrayFieldTemplate`?

**Comment by heath-freenome** [comment]
Without know the details of your implementation, I can only speculate. It may be possible to override the `ArrayFieldItemTemplate` to cloneElement each of the children and manipulate the errors. You could also consider implementing your own `ArraySchemaField` to do what you want. Right now the `ArraySchemaField` is simply using `SchemaField`. This is very much power-user territory. I'm guessing you would wrap the `SchemaField` with your own implementation to "reset" the errors you need from the `errorSchema` and/or `rawErrors` before passing stuff into `SchemaField`.

**Comment by heath-freenome** [comment]
@dagda1 did this help solve your problem?

**Comment by dagda1** [comment]
It does thank you
