### ISSUE TITLE
Conditionally set user input in one form field as value for another form field

### ISSUE THREAD

**Issue by krutarthdarji** [rjsf-team/react-jsonschema-form#3541]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

antd

### What is your question?

Suppose there are three properties in the schema. 1. First name 2. select menu with 2 option (1. Self 2. other) 3. Generated First name.

For example user wrote "abc" in First name form field and then selected Self in the select menu. On selecting self value of the Generated First name should be set as "abc". If user selected other in select menu than user should manually type for generated first name.

Please help in building the schema for the same if it is possible.

**Comment by krutarth45** [comment]
We should not use react in this case, for example we can implement above requirement using onChange function in  some way like this but this can't be used for implementation > 
`if (e.target.value) === 'Self' {
     setFormData({...formData, generatedFirstName: firstName})
}`

Requirement is to get dynamic schema.
