### ISSUE TITLE
Content Security Policy (CSP) reporting unsafe eval usage  inside Chrome Extension V3

### ISSUE THREAD

**Issue by fstn** [rjsf-team/react-jsonschema-form#3543]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

Same as [https://github.com/rjsf-team/react-jsonschema-form/issues/1121](https://github.com/rjsf-team/react-jsonschema-form/issues/1121)

I completely blocked because I'm developing a Chrome Extension that doesn't allow CSP, any chance to precompile schema?

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by heath-freenome** [comment]
@fstn I plan on adding support for precompiled schemas before the end of April as I need it for my own purposes for exactly the same reason as you.

**Comment by fstn** [comment]
that's awesome

**Comment by rwlodarczyk-xealth** [comment]
@heath-freenome Just wondering, what is the status of this work? Still on track for end of April/early May?

**Comment by heath-freenome** [comment]
@rwlodarczyk-xealth I have a PR up right now that is laying the ground work for the precompiled schema-based validator (I needed to be able to parse schemas to extract the subschemas that are passed to the `isValid()` function of the validators). I am anticipating having this issue done in less than 2 weeks.

**Comment by fregante** [comment]
Very related, same reason:

- https://github.com/rjsf-team/react-jsonschema-form/issues/3269

**Comment by fregante** [comment]
To add some context: I think this only works if your extension has a static schema and can therefore be pre-compiled before submission to the store.

If the schema is user-provided, this won't fix the CSP issue. 

I'm hopeful in the native support of non-eval validators:

- https://github.com/rjsf-team/react-jsonschema-form/issues/3269
