### ISSUE TITLE
How to update default value conditionally?

### ISSUE THREAD

**Issue by zadama** [rjsf-team/react-jsonschema-form#3552]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

I have two fields in my form: age and displayMessage. The age field is an enum of values (18, 20, 22). When the user selects a value from age, the default value of displayMessage should update conditionally. For example, if the user selects 18, the default value of displayMessage should be "You are 18". If the user selects 20, the default value of displayMessage should be "You are 20", and so on.

I am looking for a solution to update the default values of displayMessage conditionally based on the selected value of age. This has many use cases, in particular in the scenario where you have two lists that are linked. When list A changes value list B renders a new set of values. This is obviously already possible, but what I can't seem to find is how would I update the default value of list B when list A changes?

**Comment by heath-freenome** [comment]
You could probably use a`oneOf` with three different object choices.
