### ISSUE TITLE
Broken Link for `Custom Widgets and Fields` in UISchema Page

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [rjsf-team/react-jsonschema-form#3553]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

antd

### Version

5.0.0-beta.13

### Current Behavior

Currently the link for `Custom Widgets and Fields` in [UISchema](https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/docs/docs/api-reference/uiSchema.md) doc page is broken.

It is redirecting to https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/advanced-customization/custom-widgets-fields#custom-field-components.

### Expected Behavior

It should redirect to https://rjsf-team.github.io/react-jsonschema-form/docs/advanced-customization/custom-widgets-fields

### Steps To Reproduce

- Visit [UISchema Doc](https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/uiSchema/) page
- Navigate to [UI: field](https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/uiSchema/#uifield) section
- Click on the `Custom Widgets and Fields` link

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Anything else?

I would like to work on this issue.

**Comment by heath-freenome** [comment]
@Sachin-chaurasiya Yes, please submit a fix!

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya Yes, please submit a fix!

Thanks @heath-freenome , Here is the [PR](https://github.com/rjsf-team/react-jsonschema-form/pull/3559)

**Comment by heath-freenome** [comment]
@Sachin-chaurasiya After further review, I'm thinking that the behavior you are reporting as a bug is probably not one. The `field` prop in the `UiSchema` should point to the fields section of the documentation. What makes you think that the link was wrong?

**Comment by heath-freenome** [comment]
@Sachin-chaurasiya The documentation link works fine from the deployed documentation site found here: https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/uiSchema/#uifield

**Comment by heath-freenome** [comment]
There are a lot more links on this page that are broken :(

**Comment by heath-freenome** [comment]
> > @Sachin-chaurasiya After further review, I'm thinking that the behavior you are reporting as a bug is probably not one. The `field` prop in the `UiSchema` should point to the fields section of the documentation. What makes you think that the link was wrong?
> 
> @heath-freenome , It was redirecting to [this](https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/advanced-customization/custom-widgets-fields#custom-field-components) link , which is broken.

@Sachin-chaurasiya the links in the source code .md files aren't meant to be clicked on. The source is compiled into a release and deployed [here](https://rjsf-team.github.io/react-jsonschema-form/docs). If you look at the documentation site for the [page](https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/uiSchema#uifield) you are referring to and click the link it works.

**Comment by Sachin-chaurasiya** [comment]
> > > @Sachin-chaurasiya After further review, I'm thinking that the behavior you are reporting as a bug is probably not one. The `field` prop in the `UiSchema` should point to the fields section of the documentation. What makes you think that the link was wrong?
> > 
> > 
> > @heath-freenome , It was redirecting to [this](https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/advanced-customization/custom-widgets-fields#custom-field-components) link , which is broken.
> 
> @Sachin-chaurasiya the links in the source code .md files aren't meant to be clicked on. The source is compiled into a release and deployed [here](https://rjsf-team.github.io/react-jsonschema-form/docs). If you look at the documentation site for the [page](https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/uiSchema#uifield) you are referring to and click the link it works.

@heath-freenome , I have opened an issue for this link, please see the attached recording.

https://user-images.githubusercontent.com/59080942/229696021-26117cc7-01ce-45bc-86f8-f70a2d3fd0f9.mov

**Comment by heath-freenome** [comment]
@Sachin-chaurasiya Ah! I know what is going on. For some reason the links when you click on a subsection end up with a `/` before the `#link` so the relative locations stop working. If you clear the `/#link` from the url then things are fine. I'm going to see if there is a configuration switch to prevent the `/` before the `#link`
