### ISSUE TITLE
Recursive definition no longer works in 5.4

### ISSUE THREAD

**Issue by Assumeru** [rjsf-team/react-jsonschema-form#3560]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

material-ui

### Version

5.4.0

### Current Behavior

A definition containing an array of which each array item is defined to be another instance of this definition leads to infinite recursion. Aside from the browser slowing down, a message gets logged in the console: `could not merge subschemas in allOf:
InternalError: too much recursion`.

### Expected Behavior

This same schema works fine in version 4.2, i.e. it doesn't recurse endlessly.

### Steps To Reproduce

Paste this schema into https://rjsf-team.github.io/react-jsonschema-form/

[Playground Link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJkZWZpbml0aW9ucyI6eyJAZW51bSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJuYW1lIjp7InRpdGxlIjoiTmFtZSIsInR5cGUiOiJzdHJpbmciLCJtaW5MZW5ndGgiOjF9LCJfaWQiOnsidGl0bGUiOiJWYWx1ZSIsInR5cGUiOiJudW1iZXIifSwiY2hpbGRyZW4iOnsidGl0bGUiOiJTdWJ2YWx1ZXMiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJhbGxPZiI6W3siJHJlZiI6IiMvZGVmaW5pdGlvbnMvQGVudW0ifV19fX19fSwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidmFsdWUiOnsidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsiYWxsT2YiOlt7IiRyZWYiOiIjL2RlZmluaXRpb25zL0BlbnVtIn1dfSwibWluSXRlbXMiOjF9fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

```json
{
  "definitions": {
    "@enum": {
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "type": "string",
          "minLength": 1
        },
        "_id": {
          "title": "Value",
          "type": "number"
        },
        "children": {
          "title": "Subvalues",
          "type": "array",
          "items": {
            "allOf": [
              {
                "$ref": "#/definitions/@enum"
              }
            ]
          }
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "value": {
      "type": "array",
      "items": {
        "allOf": [
          {
            "$ref": "#/definitions/@enum"
          }
        ]
      },
      "minItems": 1
    }
  }
}
```

### Anything else?

I see a few other, older issues on the tracker that look similar, but these all appear to be from before version 5. #1160 appears to be about a nearly identical schema causing a similar issue along a different code path.

**Comment by heath-freenome** [comment]
@Assumeru Wow, yeah, we might have broken infinite recursion checking in the 5.x release. I will see how easy it is to fix it in the next week or so

**Comment by estk** [comment]
The playground hangs for me with:
```json
{
  "title": "A registration form",
  "description": "A simple form example.",
  "type": "object",
  "properties": {
    "child": {
      "$ref": "#"
    }
  }
}
```

**Comment by heath-freenome** [comment]
@estk can you please write a new issue for this very extreme edge case so we can fix it?
