### ISSUE TITLE
get properties from schema

### ISSUE THREAD

**Issue by bbaduser** [rjsf-team/react-jsonschema-form#3561]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

i have schema with dependencies and formData, i want to know if there have a function to get properties render in page from schema,
such as 
const getProperties = (schema, formData?)=>{
....
return properties
}

**Comment by bbaduser** [comment]
![image](https://user-images.githubusercontent.com/120174736/229145160-b95bd146-c65c-42ad-9140-51d6bd4f8e58.png)  
is not same as 
import {  retrieveSchema } from '@rjsf/utils'
i use same paramter,but two function return different

**Comment by heath-freenome** [comment]
> ![image](https://user-images.githubusercontent.com/120174736/229145160-b95bd146-c65c-42ad-9140-51d6bd4f8e58.png) is not same as import { retrieveSchema } from '@rjsf/utils' i use same paramter,but two function return different

The `schemaUtils.retrieveSchema()` is simply a wrapper around `utils` `retrieveSchema()` that passes in the `validator` and `rootSchema` used by the `Form` If you are passing in a different `rootSchema` then I would expect to see different values

**Comment by heath-freenome** [comment]
@bbaduser There is a function in `Form` in `core` called `getFieldNames()` which you could use as an example of doing what you need. Hope this helps

**Comment by bbaduser** [comment]
first of all, thks for ur reply.   @heath-freenome 
i search `getFieldNames` it just used in `onChange` and `onSubmit`,and its not export, so I would like to share my initial requirements  with u
i created my own ObjectFieldTemplate and used properties
![image](https://user-images.githubusercontent.com/120174736/229400293-603ed8ac-5b45-4982-aada-69382edc5f33.png)

and in my project somewhere i also want to to use `properties`,but i just have `schema` and `formadata`

**Comment by heath-freenome** [comment]
You can pass anything you need using the `formContext` and access it in the `registry`
