### ISSUE TITLE
Form text field loses focus when setting state onChange, using custom field templates 

### ISSUE THREAD

**Issue by brada11en** [rjsf-team/react-jsonschema-form#3563]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.5.0

### Current Behavior

A custom object field template is defined via the form's templates prop:
Then setting the formData state object onChange causes the current form field to lose focus.

i have also used a React PureComponent for the custom ObjectFieldTemplate but produces same issue

### Expected Behavior

current field to remain in focus after setting state (as it does without defining a custom template)

### Steps To Reproduce

basic codesandbox example that demonstrates the issue:

https://codesandbox.io/s/admiring-bird-519cck?file=/src/App.js

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by ozgurrgul** [comment]
Exact same bug experience

**Comment by sheanmassey** [comment]
@brada11en  Just ran into the same issue and I was able to understand why while playing with your codesandbox example! You're recreating your template on every render, causing the all the children `inputs` of the template to be recreated. If you move your template defs up a level it works as expected: https://codesandbox.io/s/modest-firefly-o8h82h?file=/src/App.js

**Comment by heath-freenome** [comment]
@sheanmassey Great sleuthing! Thanks for answering the question.

@brada11en This is pretty much a React thing. It is highly recommended to create your own form using `withTheme()` so that you end up with the templates being defined just once. See the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs/advanced-customization/custom-themes/#templates)

**Comment by brada11en** [comment]
@sheanmassey thank you so much for working it out! appreciate it.. 🙌

@heath-freenome thanks for the info, ill refactor using this method. Thanks to you as well for your contribution to this great package 🤝

**Comment by heath-freenome** [comment]
@brada11en If this solves your problem please close this issue, thanks

**Comment by Deep-z21** [comment]
What if I want to pass custom Props to ObjectFieldTemplate, how will I do that if my templates are declared before the main page component.
