### ISSUE TITLE
Playground not rendering the form output

### ISSUE THREAD

**Issue by kunalshewale** [rjsf-team/react-jsonschema-form#3579]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

antd

### Version

5.x

### Current Behavior

Playground not rendering the JSON form output. Getting error as `Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
`

<img width="1739" alt="image" src="https://user-images.githubusercontent.com/7191378/230090425-09861272-a284-48de-a8e1-48a9dd721362.png">

### Expected Behavior

The playground should render the form

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by mclacore** [comment]
I've also been having this bug for the last couple days.
