### ISSUE TITLE
Allow custom focusOnError

### ISSUE THREAD

**Issue by Fronix** [rjsf-team/react-jsonschema-form#3580]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### Is your feature request related to a problem? Please describe.

Our forms sometimes have disabled fields that are automatically filled by doing some type of action.
Example: Address fields that are readonly but are filled if you search and select the adress, this will then automatically fill in the fields. The adress fields are required because it wouldn't make sense to have the search field required.

The problem here is that when i use `focusOnFirstError` it wont trigger on fields that are disabled or readonly.
https://github.com/rjsf-team/react-jsonschema-form/blob/ff46301dbbeb951758c5ee1b2ec0f95a459b4dfe/packages/core/src/components/Form.tsx#L691-L703

This might be a very niche issue but it's quite important from a UX standpoint.

### Describe the solution you'd like

There are different solutions that would work.

1. Let us provide our own callback for `focusOnError`, this would give the most freedom.
2. Add a check if the element is disabled/readonly and instead call `element.scrollIntoViewIfNeeded(true)` might have to use `element.scrollIntoView()` since support for IfNeeded is not complete.

**Comment by heath-freenome** [comment]
@Fronix If I had the time to do this any time soon, I would make the `focusOnFirstError` property also take a callback as an option. Something like:
```
  /** If set to true, then the first field with an error will receive the focus when the form is submitted with errors
   */
  focusOnFirstError?: boolean | (error: RJSFValidationError) => void;
```
And then change the code in `Form` to look something like:
```
if (focusOnFirstError) {
  if (typeof focusOnFirstError === 'function') {
    focusOnFirstError(schemaValidation.errors[0]);
  } else {
    this.focusOnError(schemaValidation.errors[0]);
  }
}
```
