### ISSUE TITLE
format: time not working

### ISSUE THREAD

**Issue by mekhlakapoor** [rjsf-team/react-jsonschema-form#3591]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

4.2.3

### Current Behavior

the "format":"time" in my schema is not reflected in the UI (with the time selection widget) despite it working (with the same exact schema) in the playground. Instead, it is just a text input. 

Sample schema:
```
"creation_time": {
         "title": "Creation Time",
         "description": "Time in UTC that data files were created, used to uniquely identify the data",
         "type": "string",
         "format": "time"
```
The html looks like this: 
`<input class="form-control" id="root_creation_time" label="Creation Time" required="" placeholder="00:00:00" type="text" value="">`

### Expected Behavior
expect to see time selection widget (if i inspect and manually edit the type="time" it does so correctly, but this should be automatic with the schema)
`<input class="form-control" id="root_creation_time" label="Creation Time" required="" placeholder="00:00:00" type="time" value="">`

### Steps To Reproduce

Not sure how to reproduce, because this works normally in the playground. Has anybody else experienced this issue/how did you resolve it?

### Environment

```markdown
- OS:
- Node:
- npm: 8.15.0
```

**Comment by heath-freenome** [comment]
@mekhlakapoor The time widget only exists in the 5.x world. You have indicated you are using 4.x. You will have to upgrade.
