### ISSUE TITLE
Antd theme: repeated title for select widget

### ISSUE THREAD

**Issue by AnimaLupi** [rjsf-team/react-jsonschema-form#3594]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

antd

### Version

5.x

### Current Behavior

The title of the select input widget is repeated twice for antd theme

### Expected Behavior

The title of the select input widget is displayed only once

### Steps To Reproduce

- Go to the playground
- Select "Widgets" example
- With the default theme, the title of the select input ("select box" text) is displayed once
- Switch to AndD theme
- The title of the select input ("select box" text) is displayed twice

### Environment

```markdown
- OS: N/A
- Node: N/A
- npm: N/A
```

### Anything else?

![image](https://user-images.githubusercontent.com/9193587/231102185-21641fdf-76f0-4c9a-a015-e3c3ac212a5d.png)

**Comment by anthonycaron** [comment]
The same happens for the Checkbox widget. Let's see if the next release fixes both of these issues.
