### ISSUE TITLE
Error message not showing

### ISSUE THREAD

**Issue by v1talii-dev** [rjsf-team/react-jsonschema-form#3608]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

antd

### Version

5.x

### Current Behavior

No error message displayed:
![image](https://user-images.githubusercontent.com/12966923/232471535-a8c1d715-c8cc-4ce4-805e-8dda0f461f8b.png)

For comparison, for other themes, the error message is displayed correctly:
![image](https://user-images.githubusercontent.com/12966923/232471462-c80315d3-04d7-40fa-88b3-96778265645a.png)

![image](https://user-images.githubusercontent.com/12966923/232471800-fbead7b2-b622-4e2e-8920-92a70511104b.png)

![image](https://user-images.githubusercontent.com/12966923/232471853-321acae5-8af6-4302-8330-2e0858f3e5fe.png)

### Expected Behavior

The error message is displayed next to the input field, similar to other themes.

### Steps To Reproduce

[Open playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6IjI1NS4yNTUuMjU1LnRlc3QiLCJzY2hlbWEiOnsidHlwZSI6InN0cmluZyIsImZvcm1hdCI6ImlwdjQifSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiIsInVpOnBsYWNlaG9sZGVyIjoidWk6ZW1wdHlWYWx1ZSBjYXVzZXMgdGhpcyBmaWVsZCB0byBhbHdheXMgYmUgdmFsaWQgZGVzcGl0ZSBiZWluZyByZXF1aXJlZCIsInVpOmF1dG9jb21wbGV0ZSI6ImZhbWlseS1uYW1lIn0sImxhc3ROYW1lIjp7InVpOmF1dG9jb21wbGV0ZSI6ImdpdmVuLW5hbWUifSwiYWdlIjp7InVpOndpZGdldCI6InVwZG93biIsInVpOnRpdGxlIjoiQWdlIG9mIHBlcnNvbiIsInVpOmRlc2NyaXB0aW9uIjoiKGVhcnRoIHllYXIpIn0sImJpbyI6eyJ1aTp3aWRnZXQiOiJ0ZXh0YXJlYSJ9LCJwYXNzd29yZCI6eyJ1aTp3aWRnZXQiOiJwYXNzd29yZCIsInVpOmhlbHAiOiJIaW50OiBNYWtlIGl0IHN0cm9uZyEifSwidGVsZXBob25lIjp7InVpOm9wdGlvbnMiOnsiaW5wdXRUeXBlIjoidGVsIn19fSwidGhlbWUiOiJhbnRkIiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOmZhbHNlLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGVkIjpmYWxzZSwibm9IdG1sNVZhbGlkYXRlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOnRydWUsImxpdmVWYWxpZGF0ZSI6dHJ1ZX19)

### Environment

```markdown
- OS: Windows 11
```

**Comment by heath-freenome** [comment]
Interesting catch. There seems to be a minor issue with the error being shown for antd. Good catch. This example also highlights an issue the two emotion-based themes, `chakra-ui` and `mui`.
