### ISSUE TITLE
Nested schema with optional object(s) with child required object adds optional object to form data

### ISSUE THREAD

**Issue by acarnagey** [rjsf-team/react-jsonschema-form#3617]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

mui

### Version

5.4.0

### Current Behavior

Nested schema of optional objects and then required objects, populates the form data with optional objects.
JSONSchema
```json
{
  "type": "object",
  "properties": {
    "carrier": {
      "type": "object",
      "properties": {
        "location": {
          "type": "object",
          "properties": {
            "address": {
              "type": "object",
              "properties": {
                "addressRegion": {
                  "type": "string"
                }
              }
            }
          },
          "required": [
            "address"
          ]
        }
      }
    }
  }
}
```
Results in actual form data
```json
{
  "carrier": {
    "location": {
      "address": {}
    }
  }
}
```
Shared playground: [https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJjYXJyaWVyIjp7ImxvY2F0aW9uIjp[…]2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCJ9fQ==](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJjYXJyaWVyIjp7ImxvY2F0aW9uIjp7ImFkZHJlc3MiOnt9fX19LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiY2FycmllciI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJsb2NhdGlvbiI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJhZGRyZXNzIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImFkZHJlc3NSZWdpb24iOnsidHlwZSI6InN0cmluZyJ9fX19LCJyZXF1aXJlZCI6WyJhZGRyZXNzIl19fX19fSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCJ9fQ==)

### Expected Behavior

Nested schema of optional objects and then required objects, should not populate the form data with optional objects.

Should result in since carrier is an optional object
```json
{}
```

### Steps To Reproduce

1. Go to rjsf playground https://rjsf-team.github.io/react-jsonschema-form/#
2. Click blank option to clear all the input props out
3. Populate JSONSchema with mentioned schema
4. The form data at this point should contain optional objects with no fields

### Environment

```markdown
- OS: Ubuntu 20.04.4
- Node: 16.14.2
- npm: 8.5.0
```

**Comment by heath-freenome** [comment]
@acarnagey We recognize that our defaults logic needs some fine tuning and we are currently working on a solution to this. It may take a while before we get all the tuning capabilities correct. See this [PR](https://github.com/rjsf-team/react-jsonschema-form/pull/3604) for the beginnings of this feature fixing.

**Comment by acarnagey** [comment]
Cool thanks for the update on that @heath-freenome , it is good to know that this is on the roadmap.

**Comment by heath-freenome** [comment]
@acarnagey we have a solution for you now. Use the new [emptyObjectField](https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/form-props/#emptyobjectfields) feature set to `populateRequiredDefaults`
