### ISSUE TITLE
How do I get a <select> with the correct className? (form-control, not custom-control)

### ISSUE THREAD

**Issue by hakunin** [rjsf-team/react-jsonschema-form#3619]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

bootstrap-4

```
        "@rjsf/bootstrap-4": "^5.6.2",
        "@rjsf/core": "^5.0.0-beta.17",
        "@rjsf/semantic-ui": "^5.0.0-beta.17",
        "@rjsf/utils": "^5.0.0-beta.17",
        "@rjsf/validator-ajv8": "^5.0.0-beta.17",
```

### What is your question?

This looks like a bug / feature.

When I create a select box through AnyOf, the form element does not look correctly, because it does not have the `className="form-control"` but instead has `className="custom-select"`, which Bootstrap does not know.

For example:
```
<select
  name="root_extractor" 
  aria-describedby="root_extractor__error root_extractor__description root_extractor__help"
  id="root_extractor"
  class="custom-select" // <---
>
  <option value=""></option>
  <option id="A" value="0">A</option>
  <option id="B" value="1">B</option>
  <option id="C" value="2">C</option>
</select>
```

This does not seem to happen in the demo/documentation.

Is it a bug? Is there a way to fix this in the meantime?

**Comment by hakunin** [comment]
As a workaround, I copied the bootstrap css for form-control from [here](https://github.com/twbs/bootstrap/blob/main/dist/css/bootstrap.css) into my project and renamed the class to `custom-select`.

**Comment by heath-freenome** [comment]
@hakunin You need to make ALL of the RJSF packages be on the same major/minor versions. Please upgrade to the latest 5.x version and try this again

**Comment by hakunin** [comment]
I can look into it on Monday, but I'm not sure about the background of the previous fix.
