### ISSUE TITLE
playgroud in a mess?

### ISSUE THREAD

**Issue by leinjay** [rjsf-team/react-jsonschema-form#3625]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

other

### Version

5.x

### Current Behavior

![image](https://user-images.githubusercontent.com/70647197/234508967-d2d4b1dc-6cf6-4f99-bfbb-2c5595cdd89d.png)

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by heath-freenome** [comment]
@leinjay I am not seeing any issues with the playground https://rjsf-team.github.io/react-jsonschema-form/... What browser are you using?

**Comment by leinjay** [comment]
i used chrome and ie in windows，even in the others' pc

**Comment by heath-freenome** [comment]
Are you still having a problem since I pushed the fix?

**Comment by leinjay** [comment]
I guess it might be caused by my network，i am in hongkong now. here is the console when i open the playground
![image](https://user-images.githubusercontent.com/70647197/236495163-e50206b1-7001-4ced-abc4-87aca94ee9a4.png)

**Comment by leinjay** [comment]
or, i might try to run playground locally...
