### ISSUE TITLE
Default values are not set for oneOf + ref in schema

### ISSUE THREAD

**Issue by anthonycaron** [rjsf-team/react-jsonschema-form#3633]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

antd

### Version

5.6.0

### Current Behavior

I have a schema of a `oneOf` with two options referencing two different objects.

Here is an example:

```
{
  "definitions": {
    "foo": {
      "type": "object",
      "properties": {
        "fooProp": {
          "type": "string"
        },
        "fooProp2": {
          "type": "string",
          "default": "fooProp2"
        }
      }
    },
    "bar": {
      "type": "object",
      "properties": {
        "barProp": {
          "type": "string"
        },
        "barProp2": {
          "type": "string",
          "default": "barProp2"
        }
      }
    }
  },
  "oneOf": [
    {
      "$ref": "#/definitions/foo"
    },
    {
      "$ref": "#/definitions/bar"
    }
  ]
}
```

You can try it out [here](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJkZWZpbml0aW9ucyI6eyJmb28iOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZm9vUHJvcCI6eyJ0eXBlIjoic3RyaW5nIn0sImZvb1Byb3AyIjp7InR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoiZm9vUHJvcDIifX19LCJiYXIiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiYmFyUHJvcCI6eyJ0eXBlIjoic3RyaW5nIn0sImJhclByb3AyIjp7InR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoiYmFyUHJvcDIifX19fSwib25lT2YiOlt7IiRyZWYiOiIjL2RlZmluaXRpb25zL2ZvbyJ9LHsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvYmFyIn1dfSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsInZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZWQiOmZhbHNlLCJub0h0bWw1VmFsaWRhdGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==).

### Expected Behavior

I would expect to have a default prop set for the properties that define one.

### Steps To Reproduce

1. Just go to the playground link provided in the description
2. You will be able to see that in the _formData_ we don't have the default value set

### Environment

```markdown
- OS: MacOs
- Node: 18.7.0
- npm: 8.15.0
```

**Comment by anthonycaron** [comment]
I already have a fix for it but I can't find the way to open a PR. I tried to push my branch on this repo but it's been denied. I'm not sure what is the process, I couldn't find it in the docs either. Could you tell me how to proceed @heath-freenome please ?

**Comment by heath-freenome** [comment]
@anthonycaron Fork the repo first. once you have a fork, push the branch to your fork then come to [this page](https://github.com/rjsf-team/react-jsonschema-form/pulls) and you should be able to create the PR

**Comment by anthonycaron** [comment]
Got it thanks !
