### ISSUE TITLE
Dropping bootstrap-4 support by renaming theme to react-bootstrap, using version 2

### ISSUE THREAD

**Issue by heath-freenome** [rjsf-team/react-jsonschema-form#3638]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

bootstrap-4

### Is your feature request related to a problem? Please describe.

Given that the `bootstrap-4` theme is based on the `react-bootstrap` package and we are 1 major release behind we need to deal with both of those issues at the same time.

### Describe the solution you'd like

We are planning to rename the theme in the next major release. At the same time, we will bump it to the react-bootstrap 2 version. This will be a breaking change

### Describe alternatives you've considered

Provide a `bootstrap-5` theme instead. We ruled this out because:
1. It is 99% the same code
2. Uses the same package name `react-bootstrap`
3. Is inaccurately named
4. Bootstrap "4" is no longer supported

**Comment by Dannergal** [comment]
I have a problem when I install boostrap 4 for react-schema-form:
![image](https://github.com/rjsf-team/react-jsonschema-form/assets/15927191/77de3743-9d62-4ff8-a310-012fa09987d7)

import Form from '@rjsf/bootstrap-4';

**Comment by heath-freenome** [comment]
@Dannergal Have you installed `@rjsf/utils`, `@rjsf/core` and `@rjsf/validator-ajv8`?

**Comment by Dannergal** [comment]
Hi thanks for your sopport, in this thread:
[#3729](https://github.com/rjsf-team/react-jsonschema-form/issues/3729#issuecomment-1584050619)

Is necessary to Add in your documentation:

> On the docs of react-bootstrap, they say you have to install bootstrap as well and import the css in your project. So I installed bootstrap npm install bootstrap and imported the styles like this:
@import 'bootstrap/scss/bootstrap';

**Comment by rmannibucau** [comment]
Hi,

any news? seems react-bootstrap now easily conflict with rjsf so can be good to integrate more recent versions

**Comment by nickgros** [comment]
Done in v6
