### ISSUE TITLE
Bump antd theme to latest major version

### ISSUE THREAD

**Issue by heath-freenome** [rjsf-team/react-jsonschema-form#3639]
Antd theme is one major version behind, we are on 4, the latest is 5

**Comment by heath-freenome** [comment]
Do you know whether this can be done with backwards compatibility to 4.x? If not, we'll have to begin the 6.x plan and have to do it in a beta branch

**Comment by heath-freenome** [comment]
Actually someone has taken some time to do the [work](https://github.com/fran122157/react-jsonschema-form/pull/1) in response to this issue https://github.com/rjsf-team/react-jsonschema-form/issues/3507

**Comment by koszti** [comment]
wondering if something has changed in the last two month. Has anyone made some progress to support antd 5?

**Comment by heath-freenome** [comment]
We haven't started the v6 work. Someone has already come up with what seems to be the [changes necessary](https://github.com/fran122157/react-jsonschema-form/pull/1) to get it to work with 5.x. If someone wanted to ensure those changes were backwards compatible with 4.x, then we would consider pulling it into the 5.x release of RJSF

**Comment by cr8or1** [comment]
@heath-freenome It will be backwards compatible with 4.x We really need the antd 5 to work with RJSF. Can you approve this PR?

**Comment by heath-freenome** [comment]
@cr8or1 The changes are in fork that we don't control.  You are welcome to copy that code into your own fork and push up a PR for us to review and merge. Can you do that?
