### ISSUE TITLE
playground can not display the render result

### ISSUE THREAD

**Issue by kikijiang** [rjsf-team/react-jsonschema-form#3647]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

antd

### What is your question?

![image](https://user-images.githubusercontent.com/19896985/236616691-6cb65d27-810b-436c-91f7-3990836dc540.png)

**Comment by kikijiang** [comment]
> @kikijiang Can you please provide a link to the use-case you are showing?
![image](https://github.com/rjsf-team/react-jsonschema-form/assets/19896985/a146b509-268c-4ac5-b651-4ce84cd42565)
I open playground from the entrance marked in the red box. The link of playground is "https://rjsf-team.github.io/react-jsonschema-form/"

**Comment by heath-freenome** [comment]
Is it still happening for you because I cannot figure out how to reproduce it myself. Can you perhaps, click the `Share` button and copy the link it produces and paste it here?

**Comment by kikijiang** [comment]
> Is it still happening for you because I cannot figure out how to reproduce it myself. Can you perhaps, click the `Share` button and copy the link it produces and paste it here?
![image](https://github.com/rjsf-team/react-jsonschema-form/assets/19896985/70093fd8-c91c-4b1b-970f-c4350a3fa6f2)

I inspected the elements and found that there was an additional audio tag outside. After deleting this audio tag, the issue was resolved. Moreover, I opened it in the browser's incognito mode, and it displayed correctly.
