### ISSUE TITLE
FileWidget - multiplefiles

### ISSUE THREAD

**Issue by ivarandre** [rjsf-team/react-jsonschema-form#3650]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

bootstrap-4

### Version
"@rjsf/bootstrap-4": "^5.4.0",
"@rjsf/core": "^5.4.0",
"@rjsf/utils": "^5.4.0",
5.x

### Current Behavior

https://rjsf-team.github.io/react-jsonschema-form/
Choose Bootsrap 4 as theme. 
Multiple files widget is single file widget. 

### Expected Behavior

Multiple files widget

### Steps To Reproduce

https://rjsf-team.github.io/react-jsonschema-form/
Choose Bootsrap 4 as theme. 
Shows single file widget.

### Environment
```markdown
It's the playground site. 
I have same issue on my local environment.
```

**Comment by heath-freenome** [comment]
Ouch, this is broken for all themes, not just bootstrap.
