### ISSUE TITLE
incorrect default value for an array with minItems and no default for the items

### ISSUE THREAD

**Issue by anthonycaron** [rjsf-team/react-jsonschema-form#3656]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

latest

### Current Behavior

Given this schema:
```
const schema: RJSFSchema = {
  type: 'object',
  properties: {
    optionalArray: {
      type: 'array',
      minItems: 2,
      items: { type: 'string' },
    },
  },
};
```
And given the raw form data with a value of `{}`,
I believe the resulting data after processing the default values should be `{ optionalArray: undefined }` since the `optionalArray` property is declared in the schema hence I guess we expect to have in our resulting data, but with a value of `undefined` since it's optional. `ajv` would consider the data as valid in that case.

As you can see in [the playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJvcHRpb25hbEFycmF5IjpbbnVsbCxudWxsXX0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJvcHRpb25hbEFycmF5Ijp7InR5cGUiOiJhcnJheSIsIm1pbkl0ZW1zIjoyLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIn19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGVkIjpmYWxzZSwibm9IdG1sNVZhbGlkYXRlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlLCJleHBlcmltZW50YWxfZGVmYXVsdEZvcm1TdGF0ZUJlaGF2aW9yIjp7ImFycmF5TWluSXRlbXMiOiJwb3B1bGF0ZSJ9fX0=), the value returned is:
```
{
  "optionalArray": [
    null,
    null
  ]
}
```

And when running the following test
```
it('should return partial array for an optional array property with minItems when provided with a partial array', () => {
  const schema: RJSFSchema = {
    type: 'object',
    properties: {
      optionalArray: {
        type: 'array',
        minItems: 2,
        items: { type: 'string' },
      },
    },
  };
  expect(
    computeDefaults(testValidator, schema, {
      rootSchema: schema,
      rawFormData: {},
      behaviorBitFlags: DefaultFormStateBehavior.IgnoreMinItemsUnlessRequired,
    })
  ).toEqual({ optionalArray: undefined });
});
```
in `getDefaultFormStateTest.ts`, we have the following result:
```
{
  "optionalArray": [
    undefined,
    undefined
  ]
}
```
I guess this is because I'm running this test on the latest version of the codebase and the playground might be using the latest release.
In any case, the issue is there.

### Expected Behavior

This test should pass:
```
it('should return partial array for an optional array property with minItems when provided with a partial array', () => {
  const schema: RJSFSchema = {
    type: 'object',
    properties: {
      optionalArray: {
        type: 'array',
        minItems: 2,
        items: { type: 'string' },
      },
    },
  };
  expect(
    computeDefaults(testValidator, schema, {
      rootSchema: schema,
      rawFormData: {},
      behaviorBitFlags: DefaultFormStateBehavior.IgnoreMinItemsUnlessRequired,
    })
  ).toEqual({ optionalArray: undefined });
});
```

### Steps To Reproduce

You can try it in [the playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJvcHRpb25hbEFycmF5IjpbbnVsbCxudWxsXX0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJvcHRpb25hbEFycmF5Ijp7InR5cGUiOiJhcnJheSIsIm1pbkl0ZW1zIjoyLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIn19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGVkIjpmYWxzZSwibm9IdG1sNVZhbGlkYXRlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlLCJleHBlcmltZW50YWxfZGVmYXVsdEZvcm1TdGF0ZUJlaGF2aW9yIjp7ImFycmF5TWluSXRlbXMiOiJwb3B1bGF0ZSJ9fX0=)

Or
1. fork the repo
2. run `npm i`
3. add the test I put up here in the `packages/utils/test/schema/getDefaultFormStateTest.ts` file
4. run `npm run test`

### Environment

```markdown
- OS: MacOS Ventura
- Node: 18.7.0
- npm: 8.15.0
```

**Comment by anthonycaron** [comment]
Just for context, there's a discussion regarding this [here](https://github.com/rjsf-team/react-jsonschema-form/discussions/3259).

**Comment by heath-freenome** [comment]
@anthonycaron The playground editors will convert the `[undefined, undefined]` array into `[null, null]` so that is expected behavior. Also, once we release 5.7.0 (soon!), the new `experimental_DefaultFormStateBehavior.arrayMinItems: 'requiredOnly'` flag being added to the `Form` could also fix this.

**Comment by anthonycaron** [comment]
Sure, thank you !
