### ISSUE TITLE
onAddClick creating and immediately removing array item

### ISSUE THREAD

**Issue by AshleyHolton** [rjsf-team/react-jsonschema-form#3658]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

other

### Version

5.x

### Current Behavior

Hi,

Currently using custom templates and everything works fine, however when I attempt to add a new array element via onAddClick, I see the flash of the item being added and then being immediately removed.

Reordering and delete buttons work fine so the formData is being dealt with correctly. It's just onAddClick that's a problem.

It's also odd that onChange is called 6 times when the button is clicked.

### Expected Behavior

A new item should be added to the array and onChange called once.

**Comment by nickgros** [comment]
Maybe related to #3367 but hard to say without being able to see the custom template code.

**Comment by heath-freenome** [comment]
@AshleyHolton Can you provide us with a reproducible example? Without that there is not really anyway to fix this otherwise
