### ISSUE TITLE
Custom Field “onChange" inside “array” breaks Form

### ISSUE THREAD

**Issue by teooliver** [rjsf-team/react-jsonschema-form#3682]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

bootstrap-4

### Version

5.7.2

### Current Behavior

Using a Custom Field in a property of type array seems to break the form. When trying to add an item to the array, the ui It flickers the new item in and out. If you remove the onChange function from the useEffect, the form works again and we can add items, but then of course you can’t save the field’s data.

```ts
const IdGenerator = ({ formData, schema: { title, description }, name, onChange }: FieldProps) => {
  const [val, setVal] = useState<string>("");

  useEffect(() => {
    if (formData) {
      setVal(formData);
    } else {
      const id = nanoid();
      setVal(id);
      // If we remove the onChange call we can add items to the array as expected, 
      // otherwise it flickers the new item in and out.
      onChange(id); 
    }
  }, [formData, onChange]);

  return (
    <div>
      <label htmlFor="id">ID:</label>
      <input type="text" id="id" name="id" value={val} disabled />
    </div>
  );
};


const schema: RJSFSchema = {
  "type": "object",
  "properties": {
    "categories": {
      "type": "array",
      "title": "Categories",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "title": "Id",
            "type": "string"
          },
          "text": {
            "type": "string",
            "title": "Text"
          },
        }
      }
    }
  }
}

const uiSchema: UiSchema = {
  "categories": {
    "items": {
      "id": {
        "ui:field": "idGenerator"
      }
    }
  }
};

const fields: RegistryFieldsType = { idGenerator: IdGenerator };

```

### Expected Behavior

Should be able to add Custom Field components in properties of type array.

### Steps To Reproduce

I created an SSCCE here:
https://github.com/teooliver/rjsf-sscce-custom-field-bug/blob/main/src/App.tsx

- clone the repo
- run `npm start`
- try to add a item to the form array

Obs:
I tried to create a Codesandbox, but couldn’t make the `rjsf` imports work.

### Environment

```markdown
- OS: MacOs Ventura 13.1
- Node: 16.20.0
- npm: 9.6.4
```

### Anything else?

https://github.com/rjsf-team/react-jsonschema-form/assets/45975624/83e138c3-132c-4d55-b2e8-dbc1b489f87b

**Comment by nickgros** [comment]
@teooliver thanks for the example code, it's really helpful!

Do you know if this was working for you before 5.7.x? I think this might be the same issue as in https://github.com/rjsf-team/react-jsonschema-form/issues/3367 . It's not ideal, but I think you can work around it by wrapping your `onChange` call in `setTimeout` with a short delay.

**Comment by teooliver** [comment]
@nickgros It wrapped the `onChange` call in `setTimout` with a short delay and it seems to be working. Thanks for the help.

**Comment by nickgros** [comment]
Glad to help. We'll continue tracking the main issue in #3367 .
