### ISSUE TITLE
difference between development mode (see the schema) and production mode(don't see the schema)

### ISSUE THREAD

**Issue by Jeandevweb** [rjsf-team/react-jsonschema-form#3683]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

material-ui

### Version

5.x

### Current Behavior

Hello,
I have a problem. In development mode i can see in the browser the json schema and it work.
But in production mode, after a build i can see anything.
The schema is not working and i can't see it.

Can you help me? 

Thank you

### Environment

```markdown
- OS:windows
- Node:v15.12.0
- npm:
```

**Comment by Jeandevweb** [comment]
sorry but it's a professionnal repository. 
But my package for production is in react and react-dom 16.14.0. 
`<script src="https://unpkg.com/react@16/umd/react.production.min.js"></script>
    <script src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>`

And locally it's react 17.0.2
rjsf 5 support only react 17 and other.
Is  it true?

Thanks

**Comment by nickgros** [comment]
@Jeandevweb `@rjsf/core` v5 supports both React ^16.14.0 and React 17.

**Comment by Jeandevweb** [comment]
u can see an example if the project: https://github.com/Jeandevweb/example-issue

Component use are in src/component/Plugins
