### ISSUE TITLE
Simple title strings and validation errors translation

### ISSUE THREAD

**Issue by britisharmy** [rjsf-team/react-jsonschema-form#3688]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

I have this simple code from the docs

```
import { RJSFSchema } from '@rjsf/utils';
import validator from '@rjsf/validator-ajv8';

const schema: RJSFSchema = {
  title: 'Test form',
  type: 'string',
};

render(<Form schema={schema} validator={validator} />, document.getElementById('app'));
```

How can I translate the field title labels and validation messages. 

What's the way to do it?

**Comment by heath-freenome** [comment]
@britisharmy There are a few ways you can do this. Titles can be translated in your `uiSchema` OR you could create a custom [`TitleFieldTemplate`](https://rjsf-team.github.io/react-jsonschema-form/docs/advanced-customization/custom-templates#titlefieldtemplate) that has a built-in localizer.

In terms of errors, if you merely need to translate what comes out of AJV to a different language you can use their built-in library (see the [docs](https://rjsf-team.github.io/react-jsonschema-form/docs/usage/validation#localization-l12n-support)). If you need to transform the errors into something very different you can use the [transformErrors](https://rjsf-team.github.io/react-jsonschema-form/docs/usage/validation#custom-error-messages) property on Form
