### ISSUE TITLE
change jsonSchema programatically

### ISSUE THREAD

**Issue by masoudbe** [rjsf-team/react-jsonschema-form#3703]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

Hello.
Is it possible to change jsonSchema programatically.for example change maxLength of a field at run time?

**Comment by tjbugh** [comment]
Yes. Just pass another schema to the component.

**Comment by heath-freenome** [comment]
@masoudbe Yes, changing the `schema` prop within the React component that contains the `Form` will cause the UI to update.

**Comment by masoudbe** [comment]
thanks.
