### ISSUE TITLE
anyOf form data does not update rendered form

### ISSUE THREAD

**Issue by spflueger** [rjsf-team/react-jsonschema-form#3705]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

I found inconsistent behavior of the `anyOf` field rendering, based on the specified form data. The issue is changing the form data from one anyOf branch to the other does not always seem to update and render the form correctly. 

Steps to reproduce: In the playground anyOf example, enter "idCode": "1234" in the form data. Then the form should render the second branch. Then clear the form data and enter "firstName": "asdf", and this the second branch of the form is rendered, but I'm expecting to see the first branch.

**Comment by tjbugh** [comment]
Could be the same problem as #3693

**Comment by spflueger** [comment]
Definitely related, good to mention this thanks @tjbugh. My case would be more general though, so it does not matter if its within an array or not.

**Comment by heath-freenome** [comment]
@spflueger I provided a possible fix in the other issue. If you feel adventurous give it a try and let us know if it works!

**Comment by spflueger** [comment]
@heath-freenome sweet! Will do (probably beginning of next week)

**Comment by spflueger** [comment]
@heath-freenome I just gave it a try and it looks like the fix from @cwendtxealth solves this issues as well :+1:, thanks! What are the plans for a new release?

**Comment by heath-freenome** [comment]
@spflueger it is out now. If this is working for you, can you close this issue?

**Comment by spflueger** [comment]
The fix from @cwendtxealth solves this issues as well, thanks again!
