### ISSUE TITLE
`anyOf` with structurally equivalent schemas still shows schema selector dropdown

### ISSUE THREAD

**Issue by drbild** [rjsf-team/react-jsonschema-form#3710]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

material-ui

### What is your question?

I'm trying to use `anyOf` to implement disjunction of multiple pattern constraints like this
```
{
  "title": "A single-field form",
  "type": "string",
  "anyOf": [
    {
      "pattern": "^foo.*"
    },
    {
      "pattern": "^bar.*"
    }
  ]
}
```

RJSF renders a dropdown for the user to select which `anyOf` element to apply.  

![Screenshot 2023-05-31 at 3 41 06 PM](https://github.com/rjsf-team/react-jsonschema-form/assets/1329694/fc9476ee-bbce-4d06-abce-f2e544182f8e)

This makes sense when the two schemas have different structures and needed different form elements, but in this case they don't.  Here, I'd expect to just see a single textbox.

If there's an `enum` constraint on the property as well, RJSF doesn't render the extraneous fields.  It renders just a single select input as one would expect. 

Is there a different way to implement this so RJSF can render it more appropriately?   Or can someone point me in the right direction for working on a PR to improve the behavior here?

**Comment by heath-freenome** [comment]
@drbild RJSF sees `anyOf`/`oneOf` and assumes that it is a choice selector since a large majority of the time that is the case. If you are doing something simple like that, You can force the UI to use a text input field using the `uiSchema` and specify the following to get the behavior you want:
```
{
  "ui:field": "StringField",
  "ui:fieldReplacesAnyOrOneOf": true
}
```

**Comment by heath-freenome** [comment]
Here is your example with my update in the [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6ImZvbyIsInNjaGVtYSI6eyJ0aXRsZSI6IkEgc2luZ2xlLWZpZWxkIGZvcm0iLCJ0eXBlIjoic3RyaW5nIiwiYW55T2YiOlt7InBhdHRlcm4iOiJeZm9vLioifSx7InBhdHRlcm4iOiJeYmFyLioifV19LCJ1aVNjaGVtYSI6eyJ1aTpmaWVsZCI6IlN0cmluZ0ZpZWxkIiwidWk6ZmllbGRSZXBsYWNlc0FueU9yT25lT2YiOnRydWV9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsInZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZWQiOmZhbHNlLCJub0h0bWw1VmFsaWRhdGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2UsImV4cGVyaW1lbnRhbF9kZWZhdWx0Rm9ybVN0YXRlQmVoYXZpb3IiOnsiYXJyYXlNaW5JdGVtcyI6InBvcHVsYXRlIn19fQ==)

**Comment by drbild** [comment]
Thank you @heath-freenome
