### ISSUE TITLE
Boostrap4 style error

### ISSUE THREAD

**Issue by Dannergal** [rjsf-team/react-jsonschema-form#3729]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

bootstrap-4

### Version

5.x

### Current Behavior

I follow the steps from: https://github.com/rjsf-team/react-jsonschema-form/tree/main/packages/bootstrap-4
and get this:

![image](https://github.com/rjsf-team/react-jsonschema-form/assets/15927191/19dc3491-d4fa-42fa-b4d9-fcbad90113b1)

I call the Form:
import Form from '@rjsf/bootstrap-4';

### Expected Behavior

I expected to happen the same in Demo:
https://rjsf-team.github.io/react-jsonschema-form/

<img width="708" alt="image" src="https://github.com/rjsf-team/react-jsonschema-form/assets/15927191/cefc1517-ac81-4380-b01b-f4cbb5236cc1">

### Steps To Reproduce

1. sudo yarn add react-bootstrap @rjsf/core
2. sudo yarn add @rjsf/bootstrap-4
3. import Form from '@rjsf/bootstrap-4';
4. <Form 
      schema={jsonForm.data.rjsfSchema} 
      uiSchema= {uiSchema} //{jsonForm.data.uiSchema}
      formData={jsonForm.data.formData} 
      validator={validator} 
      />
 

### Environment

```markdown
- OS: MACos Ventura Version 13.4 (22F66)
- Node: v18.14.1
- NPM: 9.3.1
- yarn: 1.22.19
  "dependencies": {
    "@rjsf/bootstrap-4": "^5.8.1",
    "@rjsf/core": "^5.8.1",
    "@rjsf/utils": "^5.8.1",
    "@rjsf/validator-ajv8": "^5.7.2",
    "axios": "^1.4.0",
    "markdown-to-jsx": "^7.2.0",
    "react": "^18.2.0",
    "react-bootstrap": "^2.7.4",
    "react-dom": "^18.2.0"
```

### Anything else?

I have the same result with:
import Form from '@rjsf/bootstrap-4';
import Form from '@rjsf/core';

![image](https://github.com/rjsf-team/react-jsonschema-form/assets/15927191/c6177953-d79c-47d9-935a-e292347adf24)

**Comment by Dannergal** [comment]
@heath-freenome I saw that you are contributor, Can you help me please?

**Comment by Dannergal** [comment]
Sure! thanks!, please I have another question about this library #3723

**Comment by Dannergal** [comment]
I share:
https://codesandbox.io/p/sandbox/bug-boostrap4-forked-sz6m69

**Comment by nkrietenbrink** [comment]
Hey! I had the same issue! On the docs of react-bootstrap, they say you have to install bootstrap as well and import the css in your project. So I installed bootstrap `npm install react-bootstrap bootstrap` and imported the styles like this:
`@import 'bootstrap/dist/css/bootstrap.min.css`

After that, the style is as expected.

**Comment by nkrietenbrink** [comment]
When you want to customize the style, you have to import `@import 'bootstrap/scss/bootstrap';`. But then I get some warnings of deprecated parameters.

**Comment by Dannergal** [comment]
Thanks @nickgros , but i cant , i have the error:
<img width="704" alt="image" src="https://github.com/rjsf-team/react-jsonschema-form/assets/15927191/be2d8f97-29dc-40df-b572-7afa04ee94a7">

**Comment by nickgros** [comment]
@Dannergal this is an issue with your build configuration, not RJSF, so we can't support you. A simple fix would be to import Bootstrap 4 CSS via CDN instead of NPM. [See Bootstrap 4 docs](https://getbootstrap.com/docs/4.0/getting-started/introduction/).
