### ISSUE TITLE
Render HTML or in description (or other label)

### ISSUE THREAD

**Issue by andersjanmyr** [rjsf-team/react-jsonschema-form#3730]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

I would like to render links and other HTML in the description.
I haven't found any way to do this. Is it possible to tell the schema to not escape the value?

**Example:**
```json
{
  "title": "Property dependencies",
  "description": "These <a href='something'>samples</a> are best viewed without live validation.",
  "type": "object"
}
```

**Comment by nickgros** [comment]
@andersjanmyr You could override the `DescriptionFieldTemplate` and use `dangerouslySetInnerHTML` (or some other HTML processor). [See docs for DescriptionFieldTemplate here](https://rjsf-team.github.io/react-jsonschema-form/docs/advanced-customization/custom-templates/#descriptionfieldtemplate).

**Comment by andersjanmyr** [comment]
@nickgros Sounds good, thanks!

**Comment by andersjanmyr** [comment]
Here's the code for future reference.

```typescript
import { FunctionComponent } from "react";

type DescriptionFieldOptions = {
  id: string;
  description: string
};

export const DescriptionFieldTemplate: FunctionComponent<DescriptionFieldOptions> = ({
  description,
    id
}) => {
  return <p id={id} dangerouslySetInnerHTML={{ __html: description }}></p>;
}
```
