### ISSUE TITLE
Specifying an empty title

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#3731]
Specifying `{title: ""}` doesn't show an empty title, but rather shows the field name instead as the title. The current workaround is to do `{title: " "}` but it would be nice to be able to specify `{title: ""}` or `{title: null}` in order to hide the title entirely. This would be a breaking change though.

Code: https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/core/src/components/fields/SchemaField.tsx#L190 and https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/core/src/components/fields/StringField.tsx#L44

**Comment by epicfaace** [comment]
Here's how I fixed it using a custom FieldTemplate:

```js
const FieldTemplate = (props: any) => {
  const { children } = props;
  const description = props.description;
  // Don't display title if it's empty.
  const displayTitle = props.displayLabel && props.label?.trim();
  return (
    <registry.templates.FieldTemplate
      {...props}
      description={null}
      displayLabel={displayTitle}
    >
      <>
        {props.displayLabel && description ? description : null}
        {children}
      </>
    </registry.templates.FieldTemplate>
  );
};

```

**Comment by heath-freenome** [comment]
@epicfaace Does using the `label: false` in the `uiSchema` also do what you are hoping for?

**Comment by epicfaace** [comment]
Oh cool I didn't realize that existed! `"ui:label": false,` did it!
