### ISSUE TITLE
Form fields auto removed when set omitExtraData true

### ISSUE THREAD

**Issue by mjogani97** [rjsf-team/react-jsonschema-form#3734]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

When setting the omitExtraData prop to true and submitting the form, the form fields will be removed from the forms.

### Anything else?

[Link of rjsf playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhcnJheURhdGEiOlt7ImZ1bGxhZGRyZXNzIjoiIn0seyJmdWxsYWRkcmVzcyI6IiJ9XX0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJhcnJheURhdGEiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJBcnJheSBkYXRhIE9taXQiLCJkZWZhdWx0IjpbeyJmdWxsYWRkcmVzcyI6IiJ9XSwiaXRlbXMiOlt7InR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6IkxvY2F0aW9uIiwicHJvcGVydGllcyI6eyJmdWxsYWRkcmVzcyI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJBZGRyZXNzIiwiZGVmYXVsdCI6IiJ9fX1dLCJhZGRpdGlvbmFsSXRlbXMiOnsidHlwZSI6Im9iamVjdCIsInRpdGxlIjoiT2xkIExvY2F0aW9uIiwicHJvcGVydGllcyI6eyJmdWxsYWRkcmVzcyI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJBZGRyZXNzIiwiZGVmYXVsdCI6IiJ9fX19fX0sInVpU2NoZW1hIjp7Imxpc3RPZlN0cmluZ3MiOnsiaXRlbXMiOnsidWk6ZW1wdHlWYWx1ZSI6IiJ9fSwibXVsdGlwbGVDaG9pY2VzTGlzdCI6eyJ1aTp3aWRnZXQiOiJjaGVja2JveGVzIn0sImZpeGVkSXRlbXNMaXN0Ijp7Iml0ZW1zIjpbeyJ1aTp3aWRnZXQiOiJ0ZXh0YXJlYSJ9LHsidWk6d2lkZ2V0Ijoic2VsZWN0In1dLCJhZGRpdGlvbmFsSXRlbXMiOnsidWk6d2lkZ2V0IjoidXBkb3duIn19LCJ1bm9yZGVyYWJsZSI6eyJ1aTpvcHRpb25zIjp7Im9yZGVyYWJsZSI6ZmFsc2V9fSwiY29weWFibGUiOnsidWk6b3B0aW9ucyI6eyJjb3B5YWJsZSI6dHJ1ZX19LCJ1bnJlbW92YWJsZSI6eyJ1aTpvcHRpb25zIjp7InJlbW92YWJsZSI6ZmFsc2V9fSwibm9Ub29sYmFyIjp7InVpOm9wdGlvbnMiOnsiYWRkYWJsZSI6ZmFsc2UsIm9yZGVyYWJsZSI6ZmFsc2UsInJlbW92YWJsZSI6ZmFsc2V9fSwiZml4ZWROb1Rvb2xiYXIiOnsidWk6b3B0aW9ucyI6eyJhZGRhYmxlIjpmYWxzZSwib3JkZXJhYmxlIjpmYWxzZSwicmVtb3ZhYmxlIjpmYWxzZX19fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7Im9taXRFeHRyYURhdGEiOnRydWUsInNob3dFcnJvckxpc3QiOiJ0b3AiLCJleHBlcmltZW50YWxfZGVmYXVsdEZvcm1TdGF0ZUJlaGF2aW9yIjp7ImFycmF5TWluSXRlbXMiOiJwb3B1bGF0ZSIsImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyJ9LCJsaXZlVmFsaWRhdGUiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

**Comment by nickgros** [comment]
Good bug catch, `toPathSchema` seems to not be working for arrays of objects. @mjogani97, would you be willing to help draft a PR to fix this?
