### ISSUE TITLE
Questions about the v4 and v5 versions.

### ISSUE THREAD

**Issue by xyy7260** [rjsf-team/react-jsonschema-form#3741]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

antd

### What is your question?

In version v4.2.3, there are a large number of form fields parameters that will not have performance problems. But there will be  #1628 "liveOmit" & "omitExtraData" that are invalid.
The v5 version has solved the [1628](https://github.com/rjsf-team/react-jsonschema-form/issues/1628) but there were performance problems with a large number of fields parameters, such as #3715 #3692

**Comment by heath-freenome** [comment]
@xyy7260 I'm not sure what question you asking?

**Comment by xyy7260** [comment]
@heath-freenome There are performance issues in v5, related to #3715 #3692.

**Comment by xyy7260** [comment]
https://github.com/rjsf-team/react-jsonschema-form/assets/23183393/ba780cc8-9440-41d5-b235-c440a1b85203
