### ISSUE TITLE
Intended use case for searching saved data

### ISSUE THREAD

**Issue by RyanKelvinFord** [rjsf-team/react-jsonschema-form#3745]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

I have implemented the RJSF form to build a large input field for data collection, in one of my projects however I just noticed that for some fields the text is not saved but a numerical representation of the text is saved, this has caused issues when attempting to search saved data in the database. 

for example this is saved to the database:
```
           "management": [
                {
                    "issue": "1",
                    "relevance": "2"
                },
                {
                    "issue": "2",
                    "relevance": "2"
                },
                {
                    "issue": "3",
                    "relevance": "2"
                }
            ]
```
And this relates to the schema:
```
"management": {
        "type": "array",
        "title": "Production Management",
        "items": {
          "type": "object",
          "properties": {
            "issue": {
              "type": "string",
              "default": "1",
              "oneOf": [
                {
                  "const": "1",
                  "title": "Ineffective equipment production capacity management"
                },
                {
                  "const": "2",
                  "title": "Ineffective scheduling and resources allocation"
                },
                {
                  "const": "3",
                  "title": "Ineffective analysis of performance data"
                }
              ]
            },
            "relevance": {
              "$ref": "#/relevance"
            }
          }
        }
      }
    }
```

The issue is these fields are not searchable from a database level and I am not sure the intended use case, should all data be returned to the front end and somehow pre-rendered so that it can be searchable, or is there some tool to compare the saved data to the schema?

**Comment by nickgros** [comment]
The JSON Schema that you provided uses the string values "1", "2", and "3" as valid options for `issue`. The `title` field in JSON Schemas is an annotation, and isn't reflected in data that adheres to the schema. See [Understanding JSON Schema](https://json-schema.org/understanding-json-schema/reference/generic.html?highlight=title#id2) for more info.

I can't prescribe an architecture for your project, but you could either make your backend service aware of the schema, or you could change the schema to store the text directly in your data objects.
