### ISSUE TITLE
Custom ObjectFieldTemplate and onChange callback

### ISSUE THREAD

**Issue by pawelkrystkiewicz** [rjsf-team/react-jsonschema-form#3755]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

other

### What is your question?

I'm adding my custom object field template and I want to call inside an `onChange` callback to set value when dropdown is clicked. **How can I do this?**

## Reasoning

Why this way? I have schema like this:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "locationShortName": {
      "title": "table.shortName",
      "type": "string"
    },
    "locationFullName": {
      "title": "table.fullName",
      "type": "string"
    },
    "color": {
      "title": "table.color",
      "type": "string"
    },
    "isActive": {
      "title": "table.isActive",
      "type": "boolean"
    },
    "responsibleEmployee": {
      "title": "table.responsibleEmployee",
      "type": "object",
      "properties": {
        "firstName": { "type": "string" },
        "lastName": { "type": "string" },
        "employeeUUID": { "type": "string" }
      }
    }
  },
  "required": [
    "locationShortName",
    "locationFullName",
    "isActive",
    "responsibleEmployee"
  ]
}

```
and `responsibleEmployee` is an object of employee definition `Employee`. I present data in UI as `Employee[]` in dropdown. Initially, I tried to use Widget for this, but widgets can't be used for `objects`. And setting here a `string` is possible - just using  `employeeUUID`, but this brings more complexity. I would need to `.find` which object is selected and set it in component's internal state.

**Alternatively, I could use widget approach IF it was possible to use it for widgets**

## Custom `ObjectFieldTemplate`

```tsx

import { AutocompleteAsync } from '@components/async-autocomplete'
import { getUiOptions, ObjectFieldTemplateProps } from '@rjsf/utils'
import { useTranslation } from 'react-i18next'

const AutocompleteAsyncTemplate = ({
  title,
  required,
  disabled,
  readonly,
  uiSchema,
  schema,
  formData,
  registry,
  formContext,
}: ObjectFieldTemplateProps) => {
  const { type, idKey } = getUiOptions(uiSchema as any)
  const [t] = useTranslation('translation')
  const l = t(title) || schema.title

  return (
    <AutocompleteAsync
      type={type as any}
      label={l}
      clearable
      value={formData}
      required={required}
      disabled={disabled}
      readOnly={readonly}
      // onChange={onChange}
    />
  )
}

export default AutocompleteAsyncTemplate

```

**Comment by nickgros** [comment]
@pawelkrystkiewicz your best bet might be to use a custom ObjectField ([docs](https://rjsf-team.github.io/react-jsonschema-form/docs/advanced-customization/custom-widgets-fields#custom-field-components)), which does receive an `onChange` prop. Will that work?
