### ISSUE TITLE
retrieveSchema API no longer resolves references from rootSchema

### ISSUE THREAD

**Issue by john-prillaman** [rjsf-team/react-jsonschema-form#3761]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

In version 5.0.0-beta.11 of the rjsf utils package the exported retrieveSchema API could be used such that references in the provided schema could be resolved from definitions in the provided rootSchema. With the recent updates which include the retrieveSchemaInternal this functionality no longer works. 
I understand that the schema form does not support resolving references from an external schema, however this functionality was available from this utils method and the interface and documentation suggests that it should allow this.
Will this functionality be available in future releases or was this never the intended use?

**Comment by heath-freenome** [comment]
@john-prillaman Can you be more clear? The definition of `retrieveSchema()` API hasn't changed at since the initial 5.0.0-beta.1 release. It still takes a `rootSchema` as it's optional third parameter. Is there some sort of bug you are experiencing?

**Comment by heath-freenome** [comment]
@john-prillaman Can you provide a reproducible example of this issue using codesandbox.io, jsfiddle or some other tool? As far as I know, passing `rootSchema` will allow the ref look ups just fine

**Comment by john-prillaman** [comment]
I can work on using a tool but in the meantime this snippet of code should demonstrate the behavior.

`  const schema = {
    type: "object",
    properties: {
      entity: {
        $ref: "#/definitions/entity"
      }
    }
  };

  const rootSchema = {
    type: "object",
    definitions: {
      entity: {
        type: "string",
        title: "Entity"
      }
    }
  };
    const resolved = retrieveSchema(validator, schema, rootSchema)
  console.log(JSON.stringify(resolved));`

Output sing the beta version:
    {"type":"object","properties":{"entity":{"type":"string","title":"Entity"}}}

Output using a newer version (seems to begin with the implementation of retrieveSchemaInternal):
    {"type":"object","properties":{"entity":{"$ref":"#/definitions/entity"}}}

As you can see in my testing I find that in the second example the reference to the definition in the rootSchema has not been resolved.

**Comment by john-prillaman** [comment]
If you need to see this in codesandbox I have an example of the previous snippet running here: 
https://codesandbox.io/s/rjfs-utils-retrieveschema-smt37m?file=/src/App.js

**Comment by aiibe** [comment]
On version 5.13.0, the problem remains. I forked @john-prillaman code, and put definitions inside the schema itself.
https://codesandbox.io/s/rjfs-utils-retrieveschema-forked-7kghz7?file=/src/App.js

**Comment by heath-freenome** [comment]
@aiibe Thanks for pointing it out. My company has a slightly different issue that I'm hoping to fix at the beginning of October so I'll also fix this one

**Comment by john-prillaman** [comment]
Awesome, thank you!

**Comment by BlackBerryID** [comment]
@heath-freenome Hello. What about fields, that appears conditionally?
Example:
![image](https://github.com/rjsf-team/react-jsonschema-form/assets/80481379/183a3fe0-6b97-4676-a49a-5e372abad4a9)
The field customerInformationSecondBlock resolves just with "$ref":
![image](https://github.com/rjsf-team/react-jsonschema-form/assets/80481379/59d373f5-f62b-4dc1-a4f6-b920547238c5)

I make call this way: retrieveSchema(validator, jsonSchema, definitionsObj, formData);

**Comment by heath-freenome** [comment]
@BlackBerryID can you create a new issue with a reproducible test case... Thanks!
