### ISSUE TITLE
Override AddButton Class

### ISSUE THREAD

**Issue by jalcock501** [rjsf-team/react-jsonschema-form#3777]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

How do I override the `AddButton` class for arrays in the `uiSchema`, I've found `submitButtonOptions` but nothing on any of the other buttons generated.

**Comment by heath-freenome** [comment]
It sounds like you want to provide your own implementation of the AddButton? If that is the case you can use the [template override](https://rjsf-team.github.io/react-jsonschema-form/docs/advanced-customization/custom-templates#addbutton) feature

**Comment by jalcock501** [comment]
Thanks.
