### ISSUE TITLE
anyOf/oneOf error not resolving $ref schema of object properties

### ISSUE THREAD

**Issue by cwendtxealth** [rjsf-team/react-jsonschema-form#3778]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.10

### Current Behavior

The top level $ref of anyOf and oneOf schemas have recently been fixed with this [PR](https://github.com/rjsf-team/react-jsonschema-form/pull/3763) but I found that a schemas properties could still have unresolved $refs, including an array.

This error occurs in two different places, when pre compiling schema and normal runtime

For compiling schemas, anyOf and OneOf are resolved in [resolveAnyOrOneOfSchemas](https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/utils/src/schema/retrieveSchema.ts#L336) and will check if the top level schema has a $ref. But the schema below causes compiling to fail because in schema property there is a unresolved $ref
```json
{
  "type": "object",
  "properties": {
    "anyOfRef": {
      "anyOf": [
        {
          "type": "object",
          "properties": {
            "values": {
              "$ref": "#/definitions/TestRef"
            }
          },
        },
        {
          "type": "boolean",
        }
      ]
    }
  },
  "additionalProperties": false,
  "definitions": {
    "TestRef": {
      "type": "string",
      "enum": ["1", "2"]
    }
  }
}
```

Here is a [playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhcnJheUFueU9mIjpbXX0sInNjaGVtYSI6eyIkaWQiOiJ0ZXN0IiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiYXJyYXlBbnlPZiI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9FcnJvckFueU9mIn19fSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlLCJkZWZpbml0aW9ucyI6eyJFcnJvckFueU9mIjp7ImFueU9mIjpbeyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0ZXN0Ijp7IiRyZWYiOiIjL2RlZmluaXRpb25zL1Rlc3RFbnVtIn19fSx7InR5cGUiOiJib29sZWFuIn1dfSwiVGVzdEVudW0iOnsidHlwZSI6InN0cmluZyJ9fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGVkIjpmYWxzZSwibm9IdG1sNVZhbGlkYXRlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlLCJleHBlcmltZW50YWxfZGVmYXVsdEZvcm1TdGF0ZUJlaGF2aW9yIjp7ImFycmF5TWluSXRlbXMiOiJwb3B1bGF0ZSIsImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyJ9fX0=) of the runtime error happening with anyOf. If you just add a element in the array you can see in the console logging 
```
react_devtools_backend_compact.js:2367 Error encountered compiling schema: Error: can't resolve reference __rjsf_rootSchema#/definitions/TestEnum from id -58dfa712
    at Object.code (index-f5505c26.js:911:62300)
    at w1e (index-f5505c26.js:911:23917)
    at index-f5505c26.js:911:18950
    at O.code (index-f5505c26.js:908:926)
    at O.block (index-f5505c26.js:908:2846)
    at Fte (index-f5505c26.js:911:18940)
    at y1e (index-f5505c26.js:911:17337)
    at ZYt (index-f5505c26.js:911:17095)
    at QYt (index-f5505c26.js:911:16744)
    at S1e.subschema (index-f5505c26.js:911:23436)
```
This is happening in [getClosestMatchingOption](https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/utils/src/schema/getClosestMatchingOption.ts#L148) where it resolves top level schema but none of a schema's properties.

For a possible solution would it make sense to also check the schemas properties if they have any $ref and resolve those as well? I can try creating a PR to fix this issue.

### Expected Behavior

Should resolve all references before checking validator isValid in anyOf/oneOf logic.

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by heath-freenome** [comment]
@cwendtxealth In that PR you referenced I went back and forth about updating `retrieveSchema()` to resolve the refs in `anyOf`/`oneOf` options in the `resolveSchema()` function. This ended up causing me more problems than I had the time to work through. And given your example, I now wish I had taken the extra time to figure it out. I welcome you taking a shot at it! Thanks!
