### ISSUE TITLE
Looks like Release 5.11.0 Failed to publish

### ISSUE THREAD

**Issue by cwendtxealth** [rjsf-team/react-jsonschema-form#3785]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

[GH Release Action](https://github.com/rjsf-team/react-jsonschema-form/actions/runs/5624534279)

**Comment by heath-freenome** [comment]
@cwendtxealth Thanks for letting us know. We will endeavor to fix this ASAP

**Comment by brajtkopf-anna** [comment]
I was wondering if you could kindly provide an estimated release date for the new version? Thank you for your time and consideration.

**Comment by heath-freenome** [comment]
I can't get 5.11.0 to publish properly. I will be publishing 5.11.1 instead, hopefully today or tomorrow

**Comment by heath-freenome** [comment]
[5.11.1](https://github.com/rjsf-team/react-jsonschema-form/releases/tag/v5.11.1) has been released
