### ISSUE TITLE
Custom classNames for oneOf selection component

### ISSUE THREAD

**Issue by KellyP5** [rjsf-team/react-jsonschema-form#3788]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

material-ui

### What is your question?

When using `oneOf`, by using the `ui:classNames` component this classname does not apply to the actual selection input component, rather it applies to the resulting field that is changed. See image below for the RJSF playground example of what I mean.

![Screenshot 2023-07-25 at 8 08 05 AM](https://github.com/rjsf-team/react-jsonschema-form/assets/33134267/82215ea2-fcb8-4608-acb1-f3300eef9570)

**Comment by heath-freenome** [comment]
The `ui:classNames` is only designed to target the outer field. Theoretically you can use CSS to target the inner `select` or you could write your own [custom field](https://rjsf-team.github.io/react-jsonschema-form/docs/advanced-customization/custom-widgets-fields#custom-field-components) and switch out the `OneOfField` with it.
