### ISSUE TITLE
Compiling schema error

### ISSUE THREAD

**Issue by AlimovSV** [rjsf-team/react-jsonschema-form#3792]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

>5.5.2

### Current Behavior

Playground [example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaWVsZCI6bnVsbH0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaWVsZCI6eyJ0eXBlIjpbImJvb2xlYW4iLCJudWxsIl0sImRlZmF1bHQiOm51bGwsIm9uZU9mIjpbeyJjb25zdCI6ZmFsc2UsInRpdGxlIjoiTm8ifSx7ImNvbnN0IjpudWxsLCJ0aXRsZSI6Ik4vQSJ9XX19fSwidWlTY2hlbWEiOnsiZmllbGQiOnsidWk6d2lkZ2V0IjoicmFkaW8ifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsIm5vSHRtbDVWYWxpZGF0ZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6dHJ1ZSwibGl2ZU9taXQiOnRydWUsImV4cGVyaW1lbnRhbF9kZWZhdWx0Rm9ybVN0YXRlQmVoYXZpb3IiOnsiYXJyYXlNaW5JdGVtcyI6InBvcHVsYXRlIiwiZW1wdHlPYmplY3RGaWVsZHMiOiJwb3B1bGF0ZUFsbERlZmF1bHRzIn0sImxpdmVWYWxpZGF0ZSI6dHJ1ZX19) displays an error in the console:

<img width="640" src="https://github.com/rjsf-team/react-jsonschema-form/assets/4921904/ea73a2e1-0938-42a4-a87c-d275603f11f7">

### Expected Behavior

The example should work without any error

### Steps To Reproduce

Open the example, click any option for `field` and check the console output.

### Environment

```markdown
- OS: 
- Node:
- npm:
```

### Anything else?

Looks like the problem with `"const": null` because with any other values (false for example) the example works fine. v5.5.2 and earlier work fine with this example but any later version display the error.

**Comment by nickgros** [comment]
Unminified stack trace:
```
Error encountered compiling schema: TypeError: schemaNode is null
    withIdRefPrefix withIdRefPrefix.ts:41
    withIdRefPrefixObject withIdRefPrefix.ts:16
    withIdRefPrefix withIdRefPrefix.ts:42
    isValid validator.ts:140
    getMatchingOption getMatchingOption.ts:90
    getFirstMatchingOption getFirstMatchingOption.ts:26
    allValidIndexes getClosestMatchingOption.ts:153
    getClosestMatchingOption getClosestMatchingOption.ts:151
    toPathSchemaInternal toPathSchema.ts:63
    toPathSchemaInternal toPathSchema.ts:89
    toPathSchema toPathSchema.ts:120
    toPathSchema createSchemaUtils.ts:276
    onSubmit Form.tsx:627
    ...
```

**Comment by AlimovSV** [comment]
@nickgros @heath-freenome Thank you for such a quick fix!

**Comment by heath-freenome** [comment]
@AlimovSV you are welcome. Sometimes the fix is so readily apparent that making it takes no time.
