### ISSUE TITLE
arrayMinItems never populate

### ISSUE THREAD

**Issue by alekseyBatuhtin** [rjsf-team/react-jsonschema-form#3796]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### Is your feature request related to a problem? Please describe.

Hi! I've met the next situation.
Schema:
```json
{
  "definitions": {
    "singleFileUploader": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "uid": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        }
      }
    }
  },
  "type": "object",
  "required": [
    "fileUploader",
    "objectOfFields"
  ],
  "properties": {
    "fileUploader": {
      "$ref": "#/definitions/singleFileUploader"
    },
    "objectOfFields": {
      "type": "object",
      "properties": {
        "firstName": {
          "title": "First Name",
          "type": "string",
          "default": "John"
        }
      }
    }
  }
}
```
uiSchema:
```json
{
  "fileUploader": {
    "ui:widget": "CustomFileUploader"
  }
}
```
`CustomFileUploader` own widget which consumes as data, an array of File meta

What I Want to get:
The user should attach a minimum 1 file:
```json
    "singleFileUploader": {
      "type": "array",
      "minItems": 1,
      ...
```
If not, the user should be notified after validation, and need to show up an error about the required file.
It is not possible with the current behavior of prefilling default values.

Let's consider different options of **defaultFormStateBehavior**.

1. Legacy:
[Link to playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaWxlVXBsb2FkZXIiOlt7fV0sIm9iamVjdE9mRmllbGRzIjp7ImZpcnN0TmFtZSI6IkpvaG4ifX0sInNjaGVtYSI6eyJkZWZpbml0aW9ucyI6eyJzaW5nbGVGaWxlVXBsb2FkZXIiOnsidHlwZSI6ImFycmF5IiwibWluSXRlbXMiOjEsIml0ZW1zIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InVpZCI6eyJ0eXBlIjoic3RyaW5nIn0sInVybCI6eyJ0eXBlIjoic3RyaW5nIn0sIm5hbWUiOnsidHlwZSI6InN0cmluZyJ9fX19fSwidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbImZpbGVVcGxvYWRlciIsIm9iamVjdE9mRmllbGRzIl0sInByb3BlcnRpZXMiOnsiZmlsZVVwbG9hZGVyIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL3NpbmdsZUZpbGVVcGxvYWRlciJ9LCJvYmplY3RPZkZpZWxkcyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidGl0bGUiOiJGaXJzdCBOYW1lIiwidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJKb2huIn19fX19LCJ1aVNjaGVtYSI6eyJmaWxlVXBsb2FkZXIiOnsidWk6dGl0bGUiOiJDdXN0b21GaWxlVXBsb2FkZXIifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsIm5vSHRtbDVWYWxpZGF0ZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZSwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjp7IjAiOiJwIiwiMSI6Im8iLCIyIjoicCIsIjMiOiJ1IiwiNCI6ImwiLCI1IjoiYSIsIjYiOiJ0IiwiNyI6ImUiLCJwb3B1bGF0ZSI6ImFsbCIsIm1lcmdlRXh0cmFEZWZhdWx0cyI6ZmFsc2V9LCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMifX19)

```javascript
<Form />
```

formData:
```json
{
  "fileUploader": [
    {}
  ],
  "objectOfFields": {
    "firstName": "John"
  }
}
```

2. emptyObjectFields - skipDefaults

[Link to playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJkZWZpbml0aW9ucyI6eyJzaW5nbGVGaWxlVXBsb2FkZXIiOnsidHlwZSI6ImFycmF5IiwibWluSXRlbXMiOjEsIml0ZW1zIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InVpZCI6eyJ0eXBlIjoic3RyaW5nIn0sInVybCI6eyJ0eXBlIjoic3RyaW5nIn0sIm5hbWUiOnsidHlwZSI6InN0cmluZyJ9fX19fSwidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbImZpbGVVcGxvYWRlciIsIm9iamVjdE9mRmllbGRzIl0sInByb3BlcnRpZXMiOnsiZmlsZVVwbG9hZGVyIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL3NpbmdsZUZpbGVVcGxvYWRlciJ9LCJvYmplY3RPZkZpZWxkcyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidGl0bGUiOiJGaXJzdCBOYW1lIiwidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJKb2huIn19fX19LCJ1aVNjaGVtYSI6eyJmaWxlVXBsb2FkZXIiOnsidWk6dGl0bGUiOiJDdXN0b21GaWxlVXBsb2FkZXIifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsIm5vSHRtbDVWYWxpZGF0ZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZSwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjp7IjAiOiJwIiwiMSI6Im8iLCIyIjoicCIsIjMiOiJ1IiwiNCI6ImwiLCI1IjoiYSIsIjYiOiJ0IiwiNyI6ImUiLCJwb3B1bGF0ZSI6ImFsbCIsIm1lcmdlRXh0cmFEZWZhdWx0cyI6ZmFsc2V9LCJlbXB0eU9iamVjdEZpZWxkcyI6InNraXBEZWZhdWx0cyJ9fX0=)

```jsx
<Form 
  experimental_defaultFormStateBehavior={{
    emptyObjectFields: "skipDefaults"
}}
/>
```
formData:
```json
{}
```

### Describe the solution you'd like

What I would like to get:
- objects and default values should be populated
- arrays don't

Example:
```jsx
<Form 
  experimental_defaultFormStateBehavior={{
    arrayMinItems: {
      populate: "never"
   }
}}
/>
```

```json
{
  "fileUploader": [], // <- validation will say "It's empty, add minimum 1 element"
  "objectOfFields": {
    "firstName": "John" // <- it's default value everything is Ok
  }
}
```

What do you think about this?

**Comment by MarekBodingerBA** [comment]
Thank you [alekseyBatuhtin](https://github.com/alekseyBatuhtin), I was just about to write about the exactly same problem, also for a custom file uploader. We also need `never` behaviour for `populate` of `experimental_defaultFormStateBehavior`.

Because of this, we've implemented custom solution that relies on [patch-package](https://github.com/ds300/patch-package) which is not optimal. You can take a look at it [here](https://github.com/bratislava/konto.bratislava.sk/blob/master/next/patches/%40rjsf%2Butils%2B5.10.0.patch).

**Comment by alekseyBatuhtin** [comment]
@MarekBodingerBA it will appear in the 5.12.0 version.

/close
