### ISSUE TITLE
How to add spellcheck="false"?

### ISSUE THREAD

**Issue by roniemartinez** [rjsf-team/react-jsonschema-form#3819]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

I currently cannot find documentation on adding `spellcheck="false"` attribute. Help is highly appreciated.

**Comment by heath-freenome** [comment]
@roniemartinez If you follow the second example in [this documentation](https://raw.github.com/), you should be able to add `spellcheck="false"` for all of your inputs.

**Comment by roniemartinez** [comment]
@heath-freenome The link is going to `raw.github.com`.

**Comment by heath-freenome** [comment]
@roniemartinez my apologies for the delay in answering... It's been a busy couple of weeks. Here is the correct documentation link: https://rjsf-team.github.io/react-jsonschema-form/docs/advanced-customization/custom-templates/#baseinputtemplate
