### ISSUE TITLE
Using oneOf does not pass validation to the next step

### ISSUE THREAD

**Issue by Vity01** [rjsf-team/react-jsonschema-form#3828]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

mui

### Version

5.x

### Current Behavior

Using OneOf is causing multiple validation errors, not just for the form which is actually viewing.
Use [this test demo link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJkZXRhaWwiOnsiaG9zdCI6ImFzZGFzZCIsInBvcnQiOjEyM30sIm5hbWUiOiJhc2QifSwic2NoZW1hIjp7InRpdGxlIjoiRmlsbCBpbmZvcm1hdGlvbiBhYm91dCBSZXNvdXJjZSIsInJlcXVpcmVkIjpbIm5hbWUiLCJkZXRhaWwiXSwicHJvcGVydGllcyI6eyJuYW1lIjp7InRpdGxlIjoiTmFtZSIsInR5cGUiOiJzdHJpbmciLCJkZXNjcmlwdGlvbiI6IlVuaXF1ZSBuYW1lIG9mIHByb2plY3QsIGFsc28gdXNlZCBhcyByZWZlcmVuY2UgSUQuIEluIG1hbnkgY2FzZXMgdGhpcyBjYW4gYmUgc2FtZSBhcyBnaXQgcmVwb3NpdG9yeSBuYW1lLiBEb2M6IGh0dHBzOi8vYmFja3N0YWdlLmlvL2RvY3MvZmVhdHVyZXMvc29mdHdhcmUtY2F0YWxvZy9kZXNjcmlwdG9yLWZvcm1hdCNuYW1lLXJlcXVpcmVkIFBhdHRlcm46IF5bYS16MC05QS1aXy4tXXsxLDYzfSQiLCJtaW5MZW5ndGgiOjEsInVpOmhlbHAiOiJFeGFtcGxlIC0gbWV0YWRhdGEtcHJveHkiLCJleGFtcGxlcyI6WyJtZXRhZGF0YS1wcm94eSJdLCJwYXR0ZXJuIjoiXlthLXowLTlBLVpfLi1dezEsNjN9JCJ9LCJkZXRhaWwiOnsidGl0bGUiOiJSZXNvdXJjZSBkZXRhaWwiLCJ0eXBlIjoib2JqZWN0IiwiZGVzY3JpcHRpb24iOiJEZXRhaWwgaW5mb3JtYXRpb24uIEJhc2VkIG9uIHR5cGUgb25lIG9mIGZvbGxvd2luZy4iLCJvbmVPZiI6W3sidHlwZSI6Im9iamVjdCIsInRpdGxlIjoiUmFiYml0TVEiLCJkZXNjcmlwdGlvbiI6IkRlc2NyaXB0aW9uIG9mIFJhYmJpdE1RIHNwZWNpZmljIHZhbHVlcyIsInJlcXVpcmVkIjpbImhvc3QiXSwicHJvcGVydGllcyI6eyJ0eXBlIjp7InRpdGxlIjoiVHlwZSIsInR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoiY29tcGFueS5jb20vcmFiYml0bXEiLCJjb25zdCI6ImNvbXBhbnkuY29tL3JhYmJpdG1xIiwidWk6d2lkZ2V0IjoiaGlkZGVuIn0sImhvc3QiOnsidGl0bGUiOiJob3N0IiwidHlwZSI6InN0cmluZyIsInVpOmhlbHAiOiJFeGFtcGxlIC0gdGxhYi1jbHVzdGVyLXByZy5ybXEuZmYuaW50LmNvbXBhbnkuY29tIiwiZXhhbXBsZXMiOlsidGxhYi1jbHVzdGVyLXByZy5ybXEuZmYuaW50LmNvbXBhbnkuY29tIl19fX0seyJ0eXBlIjoib2JqZWN0IiwidGl0bGUiOiJLYWZrYSIsImRlc2NyaXB0aW9uIjoiRGVzY3JpcHRpb24gb2YgS2Fma2Egc3BlY2lmaWMgdmFsdWVzIiwicmVxdWlyZWQiOlsiaG9zdCIsInBvcnQiXSwicHJvcGVydGllcyI6eyJob3N0Ijp7InRpdGxlIjoiaG9zdCIsInR5cGUiOiJzdHJpbmciLCJ1aTpoZWxwIjoiRXhhbXBsZSAtIC8iLCJleGFtcGxlcyI6WyIvIl19LCJwb3J0Ijp7InRpdGxlIjoicG9ydCIsIm1pbmltdW0iOjAsIm1heGltdW0iOjY1NTM1LCJ0eXBlIjoiaW50ZWdlciIsInVpOmhlbHAiOiJFeGFtcGxlIC0gOTA5MiIsImV4YW1wbGVzIjpbIjkwOTIiXX19fSx7InR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6IlBvc3RncmVTUUwiLCJkZXNjcmlwdGlvbiI6IkRlc2NyaXB0aW9uIG9mIFBvc3RncmVTUUwgc3BlY2lmaWMgdmFsdWVzIiwicmVxdWlyZWQiOlsiaG9zdCIsInBvcnQiXSwicHJvcGVydGllcyI6eyJob3N0Ijp7InRpdGxlIjoiaG9zdCIsInR5cGUiOiJzdHJpbmciLCJ1aTpoZWxwIjoiRXhhbXBsZSAtIHBnY2x1c3Rlci1wcm9kLTAwMi5mZi5pbnQuY29tcGFueS5jb20iLCJleGFtcGxlcyI6WyJwZ2NsdXN0ZXItcHJvZC0wMDIuZmYuaW50LmNvbXBhbnkuY29tIl19LCJkYXRhYmFzZSI6eyJ0aXRsZSI6ImRhdGFiYXNlIiwidHlwZSI6InN0cmluZyIsInVpOmhlbHAiOiJFeGFtcGxlIC0gbXlEQiIsImV4YW1wbGVzIjpbIm15REIiXX0sInBvcnQiOnsidGl0bGUiOiJwb3J0IiwidHlwZSI6ImludGVnZXIiLCJtaW5pbXVtIjowLCJtYXhpbXVtIjo2NTUzNSwidWk6aGVscCI6IkV4YW1wbGUgLSA1NDMyIiwiZXhhbXBsZXMiOlsiNTQzMiJdfX19LHsidHlwZSI6Im9iamVjdCIsInRpdGxlIjoiQ2Fzc2FuZHJhIiwiZGVzY3JpcHRpb24iOiJEZXNjcmlwdGlvbiBvZiBDYXNzYW5kcmEgc3BlY2lmaWMgdmFsdWVzIiwicmVxdWlyZWQiOlsiaG9zdCIsInBvcnQiXSwicHJvcGVydGllcyI6eyJob3N0Ijp7InRpdGxlIjoiaG9zdCIsInR5cGUiOiJzdHJpbmciLCJ1aTpoZWxwIjoiRXhhbXBsZSAtIGNhc3NhbmRyYS1jMDAwNS5mZi5jb21wYW55LmNvbSIsImV4YW1wbGVzIjpbImNhc3NhbmRyYS1jMDAwNS5mZi5jb21wYW55LmNvbSJdfSwiZGF0YWJhc2UiOnsidGl0bGUiOiJrZXlzcGFjZSIsInR5cGUiOiJzdHJpbmciLCJ1aTpoZWxwIjoiRXhhbXBsZSAtIG15S2V5c3BhY2UiLCJleGFtcGxlcyI6WyJteUtleXNwYWNlIl19LCJwb3J0Ijp7InRpdGxlIjoicG9ydCIsInR5cGUiOiJpbnRlZ2VyIiwibWluaW11bSI6MCwibWF4aW11bSI6NjU1MzUsInVpOmhlbHAiOiJFeGFtcGxlIC0gNzAwMCIsImV4YW1wbGVzIjpbIjcwMDAiXX19fSx7InR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6Ik15U1FMIiwiZGVzY3JpcHRpb24iOiJEZXNjcmlwdGlvbiBvZiBNeVNRTCBzcGVjaWZpYyB2YWx1ZXMiLCJyZXF1aXJlZCI6WyJob3N0IiwicG9ydCJdLCJwcm9wZXJ0aWVzIjp7Imhvc3QiOnsidGl0bGUiOiJob3N0IiwidHlwZSI6InN0cmluZyIsInVpOmhlbHAiOiJFeGFtcGxlIC0gLyIsImV4YW1wbGVzIjpbIi8iXX0sInBvcnQiOnsidGl0bGUiOiJwb3J0IiwidHlwZSI6ImludGVnZXIiLCJtaW5pbXVtIjowLCJtYXhpbXVtIjo2NTUzNSwidWk6aGVscCI6IkV4YW1wbGUgLSAzMzA2IiwiZXhhbXBsZXMiOlsiMzMwNiJdfX19LHsidHlwZSI6Im9iamVjdCIsInRpdGxlIjoiUmVkaXMiLCJkZXNjcmlwdGlvbiI6IkRlc2NyaXB0aW9uIG9mIFJlZGlzIHNwZWNpZmljIHZhbHVlcyIsInJlcXVpcmVkIjpbImhvc3QiLCJwb3J0Il0sInByb3BlcnRpZXMiOnsiaG9zdCI6eyJ0aXRsZSI6Imhvc3QiLCJ0eXBlIjoic3RyaW5nIiwidWk6aGVscCI6IkV4YW1wbGUgLSAvIiwiZXhhbXBsZXMiOlsiLyJdfSwicG9ydCI6eyJ0aXRsZSI6InBvcnQiLCJ0eXBlIjoiaW50ZWdlciIsIm1pbmltdW0iOjAsIm1heGltdW0iOjY1NTM1LCJ1aTpoZWxwIjoiRXhhbXBsZSAtIDYzNzkiLCJleGFtcGxlcyI6WyI2Mzc5Il19fX0seyJ0eXBlIjoib2JqZWN0IiwidGl0bGUiOiJNb25nb0RCIiwiZGVzY3JpcHRpb24iOiJEZXNjcmlwdGlvbiBvZiBNb25nb0RCIHNwZWNpZmljIHZhbHVlcyIsInJlcXVpcmVkIjpbImhvc3QiLCJwb3J0Il0sInByb3BlcnRpZXMiOnsiaG9zdCI6eyJ0aXRsZSI6Imhvc3QiLCJ0eXBlIjoic3RyaW5nIiwidWk6aGVscCI6IkV4YW1wbGUgLSAvIiwiZXhhbXBsZXMiOlsiLyJdfSwicG9ydCI6eyJ0aXRsZSI6InBvcnQiLCJ0eXBlIjoiaW50ZWdlciIsIm1pbmltdW0iOjAsIm1heGltdW0iOjY1NTM1LCJ1aTpoZWxwIjoiRXhhbXBsZSAtIDI3MDE3IiwiZXhhbXBsZXMiOlsiMjcwMTciXX19fSx7InR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6IlN0YXRzRCIsImRlc2NyaXB0aW9uIjoiRGVzY3JpcHRpb24gb2YgU3RhdHNEIHNwZWNpZmljIHZhbHVlcyIsInJlcXVpcmVkIjpbImhvc3QiLCJwb3J0Il0sInByb3BlcnRpZXMiOnsiaG9zdCI6eyJ0aXRsZSI6Imhvc3QiLCJ0eXBlIjoic3RyaW5nIiwidWk6aGVscCI6IkV4YW1wbGUgLSAvIiwiZXhhbXBsZXMiOlsiLyJdfSwicG9ydCI6eyJ0aXRsZSI6InBvcnQiLCJ0eXBlIjoiaW50ZWdlciIsIm1pbmltdW0iOjAsIm1heGltdW0iOjY1NTM1LCJ1aTpoZWxwIjoiRXhhbXBsZSAtIDgxMjUiLCJleGFtcGxlcyI6WyI4MTI1Il19fX0seyJ0eXBlIjoib2JqZWN0IiwidGl0bGUiOiJTMyBCdWNrZXQiLCJkZXNjcmlwdGlvbiI6IkRlc2NyaXB0aW9uIG9mIFMzIEJ1Y2tldCBzcGVjaWZpYyB2YWx1ZXMiLCJyZXF1aXJlZCI6WyJob3N0IiwiYnVja2V0Il0sInByb3BlcnRpZXMiOnsiaG9zdCI6eyJ0aXRsZSI6Imhvc3QiLCJ0eXBlIjoic3RyaW5nIiwidWk6aGVscCI6IkV4YW1wbGUgLSB0bGFiLmhjcC1wcm9kLTAxLXByZzUuaW50LmNvbXBhbnkuY29tIiwiZXhhbXBsZXMiOlsidGxhYi5oY3AtcHJvZC0wMS1wcmc1LmludC5jb21wYW55LmNvbSJdfSwiYnVja2V0Ijp7InRpdGxlIjoiYnVja2V0IiwidHlwZSI6InN0cmluZyIsIm1pbmltdW0iOjAsIm1heGltdW0iOjY1NTM1LCJ1aTpoZWxwIjoiRXhhbXBsZSAtIHNhbXBsZXMiLCJleGFtcGxlcyI6WyJzYW1wbGVzIl19fX0seyJ0eXBlIjoib2JqZWN0IiwidGl0bGUiOiJPdGhlciIsImRlc2NyaXB0aW9uIjoiRGVzY3JpcHRpb24gb2YgT3RoZXIgc3BlY2lmaWMgdmFsdWVzIiwicmVxdWlyZWQiOlsib3RoZXJQcm9wZXJ0aWVzIl0sInByb3BlcnRpZXMiOnsib3RoZXJQcm9wZXJ0aWVzIjp7InRpdGxlIjoiTGlzdCBvZiBLZXkvVmFsdWUgcHJvcGVydGllcyIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJvYmplY3QiLCJyZXF1aXJlZCI6WyJrZXkiLCJ2YWx1ZSJdLCJwcm9wZXJ0aWVzIjp7ImtleSI6eyJ0aXRsZSI6IktleSIsInR5cGUiOiJzdHJpbmcifSwidmFsdWUiOnsidGl0bGUiOiJWYWx1ZSIsInR5cGUiOiJzdHJpbmcifX19fX19XX19fSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsImV4cGVyaW1lbnRhbF9kZWZhdWx0Rm9ybVN0YXRlQmVoYXZpb3IiOnsiYXJyYXlNaW5JdGVtcyI6eyJwb3B1bGF0ZSI6InBvcHVsYXRlIiwibWVyZ2VFeHRyYURlZmF1bHRzIjpmYWxzZX0sImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyJ9fX0=). Select eg. Kafka from the select box, fill the form and Click on Submit. You will see multiple errors from multiple forms. 

### Expected Behavior

No validation error for all options.

### Steps To Reproduce

Use the demo link mentioned above.

### Environment

```markdown
- OS: All
- Node: 16
- npm:?
```

**Comment by nickgros** [comment]
@Vity01 this is not a bug in RJSF. When I click through the repro, I get this data

```json
{
  "detail": {
    "host": "asdasd",
    "port": 123
  },
  "name": "asd"
}
```

This matches more than one of your schemas in the `oneOf`, which causes it to fail. I recommend either using `anyOf` instead of `oneOf`, or adding a discriminator property that has a unique value for each `oneOf` schema.

**Comment by Vity01** [comment]
OK, Thank you very much for the analysis. I fix it.
