### ISSUE TITLE
Required property inside of allOf doesn't seem to be populated with populateAllDefaults

### ISSUE THREAD

**Issue by MarekBodingerBA** [rjsf-team/react-jsonschema-form#3832]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

Hello,

in this case, I cannot find a reason why the property `fourth` is not populated. I had similar examples running correctly, but in this case I am not able to say what's the reason and our form logic heavily relies on this.

Here is the code sample with the output:
https://runkit.com/marekbodingerba/64dd19e7e6504a0008fcb575

[Playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaXJzdCI6eyJ0eXBlIjoib2JqZWN0In0sInNlY29uZCI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0aGlyZCI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6ImRlZmF1bHQgdmFsdWUifX0sInJlcXVpcmVkIjpbInRoaXJkIl0sImFsbE9mIjpbeyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmb3VydGgiOnsidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJkZWZhdWx0IHZhbHVlIn19LCJyZXF1aXJlZCI6WyJmb3VydGgiXX1dfX0sInJlcXVpcmVkIjpbImZpcnN0Iiwic2Vjb25kIl19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjp7InBvcHVsYXRlIjoibmV2ZXIiLCJtZXJnZUV4dHJhRGVmYXVsdHMiOmZhbHNlfSwiZW1wdHlPYmplY3RGaWVsZHMiOiJwb3B1bGF0ZUFsbERlZmF1bHRzIn19fQ==)

Thank you for looking at it, it might be something simple that I am missing.

Marek

**Comment by nickgros** [comment]
This definitely looks like a bug, thanks for the report @MarekBodingerBA . I think this is a duplicate of #3599. Unfortunately, current maintainers' time is limited so we could use any help we could get on this issues. Would you be willing to investigate?

**Comment by MarekBodingerBA** [comment]
Fixed in https://github.com/rjsf-team/react-jsonschema-form/issues/3892.

Thank you.
