### ISSUE TITLE
How to use anyOf with custom fields

### ISSUE THREAD

**Issue by burks10** [rjsf-team/react-jsonschema-form#3834]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

material-ui

### What is your question?

Hi all,

I have built several custom fields and am attempting to make some of them required conditionally based on if any other custom fields are not filled in. However, the form submits even when I don't fill out either of the custom fields. 

My guess is that it has something to do with the default values maybe? Is it passing because empty string is an "ok" value?

Another guess is that it is because of the nested properties? Notice how my customField is named "phoneCustomField" and within that I have 2 more properties of "phone" and "phoneType", each tracking their own values. Is there a way to tell "anyOf", that I want it to check "phoneCustomField>phone"?

In example, the user must provide either a phone number OR an email in order to pass validation.

My schema looks something like this:
```json
{
  "type": "object",
  "anyOf": [
    {
      "required": [
        "phoneCustomField"
      ]
    },
    {
      "required": [
        "emailCustomField"
      ]
    }
  ],
  "properties": {
    "phoneCustomField": {
      "properties": {
        "phone": {
          "type": "string"
        },
        "phoneType": {
          "type": "string"
        }
      }
    },
    "emailCustomField": {
      "properties": {
        "email": {
          "type": "string"
        }
        "emailType": {
          "type": "string"
        }
      }
    }
  }
}
```

**Comment by nickgros** [comment]
@burks10 I think you're on the right track. In v5, the `phoneCustomField` object is created because it's a required object.  The behavior can be modified with the experimental property `experimental_defaultFormStateBehavior.emptyObjectFields` [see docs](https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/form-props/#emptyobjectfields). Though I'll also note that I think default form state and any/oneOf is kind of buggy right now (#3833).

You're only requiring the object to be defined, so the empty object is considered valid.

You could add `required` fields like `"required": ["phone", "phoneType"]` to the subschemas to ensure that those fields must also be filled out to be valid.

**Comment by burks10** [comment]
@nickgros thanks so much for the reply! I've made it much further since I last posted thanks to your help!

I am getting my desired functionality of "one of email or phone number must be entered", however I am getting some odd duplication and a UI artifact. Hopefully you can steer me in the right direction.

My schema now looks like this:

```json
{
  "type": "object",
  "anyOf": [
    {
      "properties": {
        "phoneCustomField": {
          "properties": {
            "phone": {
              "minLength": 1
            }
          }
        }
      }
    },
    {
      "properties": {
        "emailCustomField": {
          "properties": {
            "email": {
              "minLength": 1
            }
          }
        }
      }
    }
  ],
  "properties": {
    "phoneCustomField": {
      "properties": {
        "phone": {
          "type": "string"
        },
        "phoneType": {
          "type": "string"
        }
      }
    },
    "emailCustomField": {
      "properties": {
        "email": {
          "type": "string"
        },
        "emailType": {
          "type": "string"
        }
      }
    }
  }
}
```

My UI, however is looking like this. Note that the arrows point to the "extra" UI elements that are being rendered. There is a random dropdown that contains "Option 1" and "Option 2", which seem to correlate to the number of custom fields I have in my schema. Also, at the bottom, there is yet another (duplicate) emailCustomField...

![Screenshot 2023-08-29 at 3 48 51 PM](https://github.com/rjsf-team/react-jsonschema-form/assets/6558784/2e7d73be-9be2-44b2-94d5-8c4e54c88d1c)


I have updated my rjsf core to 5.12.1 to see if the fix done here would help me, however it didn't: https://github.com/rjsf-team/react-jsonschema-form/issues/3808

**Comment by burks10** [comment]
I found a really hacky workaround to get over this issue by simply hidding the display artifacts with the following css selector. Would love a fix for this, so I will convert this to an issue and update the original description.

```css
    'div.panel.panel-default.panel-body': {
        display: 'none'
    },
```
![Screenshot 2023-08-30 at 8 18 43 AM](https://github.com/rjsf-team/react-jsonschema-form/assets/6558784/b1dca0aa-43fb-48b4-9c6a-8425f4815721)

**Comment by nickgros** [comment]
#3841 might fix this, we'll release 5.12.2 soon and see if your custom selector is still necessary.

**Comment by dany-nonstop** [comment]
bump. This is a pretty common feature, would like to see implemented. Thanks!

add to @burks10 's issue, I have the same issue here, it seems "required" inside `anyOf`/`oneOf` is not recognized. The minimum I can replicate this issue is similarly built on the same example.

And I've verified that it's the same across all themes. The behavior is the same in the playground. This is actually valid and all validators I tested are not complaining at all, including AJV8 or Python JSON schema validators.

```json
{
  "type": "object",
  "anyOf": [
    {
      "required": [
        "phone"
      ]
    },
    {
      "required": [
        "email"
      ]
    }
  ],
  "properties": {
    "phone": {
      "type": "string"
    },
    "email": {
      "type": "string"
    }
  }
}
```

![msedge_ntSokicSCd](https://github.com/rjsf-team/react-jsonschema-form/assets/56896461/d180f1f8-859e-40ad-8882-8bd963a4a54d)

**Comment by nickgros** [comment]
This may be a better workaround: with [ui:fieldReplacesAnyOrOneOf](https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/uiSchema#uifieldreplacesanyoroneof) and `"uiField": "hidden"` you can hide this undesirable `anyOf` field. [Here's a playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJwaG9uZUN1c3RvbUZpZWxkIjp7fX0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwiYW55T2YiOlt7InJlcXVpcmVkIjpbInBob25lQ3VzdG9tRmllbGQiXX0seyJyZXF1aXJlZCI6WyJlbWFpbEN1c3RvbUZpZWxkIl19XSwicHJvcGVydGllcyI6eyJwaG9uZUN1c3RvbUZpZWxkIjp7InByb3BlcnRpZXMiOnsicGhvbmUiOnsidHlwZSI6InN0cmluZyJ9LCJwaG9uZVR5cGUiOnsidHlwZSI6InN0cmluZyJ9fX0sImVtYWlsQ3VzdG9tRmllbGQiOnsicHJvcGVydGllcyI6eyJlbWFpbCI6eyJ0eXBlIjoic3RyaW5nIn0sImVtYWlsVHlwZSI6eyJ0eXBlIjoic3RyaW5nIn19fX19LCJ1aVNjaGVtYSI6eyJ1aTpmaWVsZFJlcGxhY2VzQW55T3JPbmVPZiI6dHJ1ZSwidWk6ZmllbGQiOiJoaWRkZW4ifSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJleHBlcmltZW50YWxfZGVmYXVsdEZvcm1TdGF0ZUJlaGF2aW9yIjp7ImFycmF5TWluSXRlbXMiOnsicG9wdWxhdGUiOiJwb3B1bGF0ZSIsIm1lcmdlRXh0cmFEZWZhdWx0cyI6ZmFsc2V9LCJhbGxPZiI6InNraXBEZWZhdWx0cyIsImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyJ9fX0=).

Ideally we would be able to detect when this field is not rendered, and not require this workaround, but hopefully this is a more elegant workaround for these cases.

**Comment by heath-freenome** [comment]
@dany-nonstop @burks10 Hopefully this workaround solves your issue. If so, please close

**Comment by cgokey** [comment]
I was able to confirm this solution works perfect!   Thank you!
