### ISSUE TITLE
Mui SelectWidget: controlled/uncontrolled

### ISSUE THREAD

**Issue by Intendanto** [rjsf-team/react-jsonschema-form#3844]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

mui

### Version

5.11.1

### Current Behavior

In general, codeandbox detects 2 errors:
1. List of options in the user interface is not updated when the schema state is updated;
2. If `initialFormData` contains a `oneOf` list, that does not include the value from InitialFormData, this breaks that particular field, preventing any non-manual updates to it;

### Expected Behavior

1. Expect options list to update when schema changes;
2. Expect Select component to be prefilled with option with corresponding value from options list;

### Steps To Reproduce

[sandbox](https://codesandbox.io/s/crazy-bush-ty33r9?file=/src/Form.tsx)

### Environment

```markdown
OS: Ubuntu 22.*
Node: 18.15.0
yarn: 1.22.19
```

### Anything else?

I didn't succeed in tracking why first bug occurs (locally it disappeared for me at some point for some reason, but still relevant in attached sandbox) so I will elaborate on second one.

In [SelectWidget file](https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/mui/src/SelectWidget/SelectWidget.tsx#L68C46-L68C46) if `enumOptionsIndexForValue` didnt find current value in options list - it returns `undefined` and passes it into [mui Select](https://github.com/mui/material-ui/blob/master/packages/mui-material/src/Select/SelectInput.js#L138) . Mui, in its turn, uses [useControlled](https://github.com/mui/material-ui/blob/master/packages/mui-utils/src/useControlled/useControlled.js#L7C52-L7C52) hook to choose if component should be controlled externally or internally. As `undefined` is passed as value, this field starts using internal state and, due to realization of `useControlled`, it doesnt accept external value, stucks in that position and spams warnings in console. 

Possible solution is to pass `emptyValue` if `selectedIndexes` is `undefined` [here](https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/mui/src/SelectWidget/SelectWidget.tsx#L68). 
E.g.: 
```typescript
      value={!isEmpty && typeof selectedIndexes !== 'undefined' ? selectedIndexes : emptyValue}
```

Please, review the issue, and if it is - if I should create PR

Btw, thanks for great libs :)

**Comment by heath-freenome** [comment]
@Intendanto This fix looks like a reasonable approach. Would you be willing to make a PR to fix this in both the `@rjsf/mui` and `@rjsf/material-ui` since the code is the same in both?

Also I think there a React issue in your sandbox, because if I push the `Add Options` button and select `a`, `b`, or `c` then the `d` choice shows up in the list.

**Comment by Intendanto** [comment]
@heath-freenome 
React issue was pretty obvious - js nested objects deep links. `Object.assing` recreates only lvl 1 object, so using deep `@ramda/clone` on schema fixed it. Sandbox updated.

Yes, will create PR. I see I dont have rights to push the branch now.

**Comment by heath-freenome** [comment]
@Intendanto you will need to fork the repo and do the change on your fork, then return to PR tab and you should be able to create a PR against this repo using your fork's branch

**Comment by Intendanto** [comment]
@heath-freenome 
Ty, didnt know that
Created PR
