### ISSUE TITLE
Error message of required Field in sub property doesn't appear

### ISSUE THREAD

**Issue by rmaury** [rjsf-team/react-jsonschema-form#3867]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.13.0

### Current Behavior

Hi team, 

I have some fields included in parent/ancestor properties, they are required, and I want to show their required message when I try to submit the form.

My field is required, but when I submit it, I only have the HTML Validation who pop to say to complete the field, but I don't have the react json schema field error message under the field.

You can try it directly on the playground : https://rjsf-team.github.io/react-jsonschema-form/
"Property dependencies" part, remove "Tim" on the name's field, and submit.
No error applied, just a htmlvalidation tooltip on the field.

![2023-09-13_12-10](https://github.com/rjsf-team/react-jsonschema-form/assets/1219892/9cda6710-e546-4c0d-8188-8b3f4fb3c9b7)

=> name is included in unidirectional property and is required.

Do you have any idea ? 
Thanks ! 

### Expected Behavior

Show required/error message under the field

### Steps To Reproduce

 playground : https://rjsf-team.github.io/react-jsonschema-form/
"Property dependencies" part, remove "Tim" on the name's field, and submit.
No error applied, just a htmlvalidation tooltip on the field

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by heath-freenome** [comment]
@rmaury If you disable HTML 5 validation then the form does what you want. See this [playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ1bmlkaXJlY3Rpb25hbCI6e30sImJpZGlyZWN0aW9uYWwiOnsibmFtZSI6IkppbGwifX0sInNjaGVtYSI6eyJ0aXRsZSI6IlByb3BlcnR5IGRlcGVuZGVuY2llcyIsImRlc2NyaXB0aW9uIjoiVGhlc2Ugc2FtcGxlcyBhcmUgYmVzdCB2aWV3ZWQgd2l0aG91dCBsaXZlIHZhbGlkYXRpb24uIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidW5pZGlyZWN0aW9uYWwiOnsidGl0bGUiOiJVbmlkaXJlY3Rpb25hbCIsInNyYyI6Imh0dHBzOi8vc3BhY2V0ZWxlc2NvcGUuZ2l0aHViLmlvL3VuZGVyc3RhbmRpbmctanNvbi1zY2hlbWEvcmVmZXJlbmNlL29iamVjdC5odG1sI2RlcGVuZGVuY2llcyIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im5hbWUiOnsidHlwZSI6InN0cmluZyJ9LCJjcmVkaXRfY2FyZCI6eyJ0eXBlIjoibnVtYmVyIn0sImJpbGxpbmdfYWRkcmVzcyI6eyJ0eXBlIjoic3RyaW5nIn19LCJyZXF1aXJlZCI6WyJuYW1lIl0sImRlcGVuZGVuY2llcyI6eyJjcmVkaXRfY2FyZCI6WyJiaWxsaW5nX2FkZHJlc3MiXX19LCJiaWRpcmVjdGlvbmFsIjp7InRpdGxlIjoiQmlkaXJlY3Rpb25hbCIsInNyYyI6Imh0dHBzOi8vc3BhY2V0ZWxlc2NvcGUuZ2l0aHViLmlvL3VuZGVyc3RhbmRpbmctanNvbi1zY2hlbWEvcmVmZXJlbmNlL29iamVjdC5odG1sI2RlcGVuZGVuY2llcyIsImRlc2NyaXB0aW9uIjoiRGVwZW5kZW5jaWVzIGFyZSBub3QgYmlkaXJlY3Rpb25hbCwgeW91IGNhbiwgb2YgY291cnNlLCBkZWZpbmUgdGhlIGJpZGlyZWN0aW9uYWwgZGVwZW5kZW5jaWVzIGV4cGxpY2l0bHkuIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsibmFtZSI6eyJ0eXBlIjoic3RyaW5nIn0sImNyZWRpdF9jYXJkIjp7InR5cGUiOiJudW1iZXIifSwiYmlsbGluZ19hZGRyZXNzIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbIm5hbWUiXSwiZGVwZW5kZW5jaWVzIjp7ImNyZWRpdF9jYXJkIjpbImJpbGxpbmdfYWRkcmVzcyJdLCJiaWxsaW5nX2FkZHJlc3MiOlsiY3JlZGl0X2NhcmQiXX19fX0sInVpU2NoZW1hIjp7InVuaWRpcmVjdGlvbmFsIjp7ImNyZWRpdF9jYXJkIjp7InVpOmhlbHAiOiJJZiB5b3UgZW50ZXIgYW55dGhpbmcgaGVyZSB0aGVuIGJpbGxpbmdfYWRkcmVzcyB3aWxsIGJlY29tZSByZXF1aXJlZC4ifSwiYmlsbGluZ19hZGRyZXNzIjp7InVpOmhlbHAiOiJJdCdzIG9rYXkgdG8gaGF2ZSBhIGJpbGxpbmcgYWRkcmVzcyB3aXRob3V0IGEgY3JlZGl0IGNhcmQgbnVtYmVyLiJ9fSwiYmlkaXJlY3Rpb25hbCI6eyJjcmVkaXRfY2FyZCI6eyJ1aTpoZWxwIjoiSWYgeW91IGVudGVyIGFueXRoaW5nIGhlcmUgdGhlbiBiaWxsaW5nX2FkZHJlc3Mgd2lsbCBiZWNvbWUgcmVxdWlyZWQuIn0sImJpbGxpbmdfYWRkcmVzcyI6eyJ1aTpoZWxwIjoiSWYgeW91IGVudGVyIGFueXRoaW5nIGhlcmUgdGhlbiBjcmVkaXRfY2FyZCB3aWxsIGJlY29tZSByZXF1aXJlZC4ifX19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsibm9IdG1sNVZhbGlkYXRlIjp0cnVlLCJzaG93RXJyb3JMaXN0IjoidG9wIiwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjp7InBvcHVsYXRlIjoicG9wdWxhdGUiLCJtZXJnZUV4dHJhRGVmYXVsdHMiOmZhbHNlfSwiZW1wdHlPYmplY3RGaWVsZHMiOiJwb3B1bGF0ZUFsbERlZmF1bHRzIn19fQ==)

**Comment by rmaury** [comment]
Hi @heath-freenome , I'll try it on my project, thanks for your quick reply.

I'm not sure if it will fix my problem because in my test (and my needs), this is a select which is required and I've tried it on the playground  =>

If you add a "test" select field, and you define it required : 

 - when you submit it the first time : OK I have a message
![2023-09-18_14-50](https://github.com/rjsf-team/react-jsonschema-form/assets/1219892/9c2589d2-faea-4791-99d2-4817198337e9)

 - when you click on reset, and try to submit it a second time, no message

![2023-09-18_14-50_1](https://github.com/rjsf-team/react-jsonschema-form/assets/1219892/9f2df6a4-225a-43b9-ad63-36b81413c1da)

It's maybe just a reset bug on the playground, I'll try it in real condition

**Comment by rmaury** [comment]
@heath-freenome It doesn't work on my test and I've found why.

On the playground test, form is already set by default by (after removing Tim of the name's field): 
`{
  "unidirectional": {
  },
  "bidirectional": {
    "name": "Jill"
  }
}`

![2023-09-18_15-55](https://github.com/rjsf-team/react-jsonschema-form/assets/1219892/cc64bf6b-251f-49a4-af25-1b39c5d0024d)


Or, if I create a new form in a new project, it doesn't have prefilled values.
form is equal to {}. (So, "unidirectional" key doesn't exist ), and here is the problem :
If you remove all the data by default, and try to submit, you will not have an error message.

![2023-09-18_15-59](https://github.com/rjsf-team/react-jsonschema-form/assets/1219892/29a6e472-af97-45d1-a032-cebf95925d4a)


Maybe the problem is me ? Do you send a form by default with subcategories keys when it exist ?
If that so I could do something like formData={(defaultForm) => {...defaultForm, ...prefilledData}} ?

**Comment by heath-freenome** [comment]
both the `unidirectional` and `bidirectional` objects are not required, so if you don't provide an empty object, there will be no error

**Comment by rmaury** [comment]
Hi @heath-freenome ,
Thanks for your reply.

If you try my last example in "property dependenciues" section,  changing formData to {}, it will not show error message under field on submit (With html5 validation disabled). 
It will only show error message if formData = { unidirectional : {}} by default.

This is not the expected I suppose

**Comment by heath-freenome** [comment]
add `required: ['unidirectional']` to the outer object as a sibling to the properties and you will see it working as you expect

**Comment by rmaury** [comment]
Oh ok thanks ! 
I'll try it asap.
Thank you for your time

**Comment by rmaury** [comment]
It works ! 
Thanks a lot @heath-freenome 

Have a good day
