### ISSUE TITLE
Specific invalid type breaks Form instead of rendering `UnsupportedFieldTemplate`

### ISSUE THREAD

**Issue by jroebu14** [rjsf-team/react-jsonschema-form#3875]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

There is a bug where Form won't render the `UnsupportedFieldTemplate` and instead break the app if the schema type is an array with the first element being a string or a number e.g.:

- `{ type: "unsupported type" }` -> renders the `UnsupportedFieldTemplate`
- `{ type: ["unsupported type", "string"] }` -> renders the `UnsupportedFieldTemplate`
- `{ type: ["string", "unsupported type"] }` -> breaks the form
- `{ type: ["number", "unsupported type"] }` -> breaks the form

Live examples of this below:

**Unsupported schema type works**
- https://codesandbox.io/s/unsupportedfieldtemplate-works-r6gxgk?file=/src/App.tsx
- https://codesandbox.io/s/unsupportedfieldtemplate-works-ksfdnq?file=/src/App.tsx

**Unsupported schema type does not work**
- https://codesandbox.io/s/unsupportedfieldtemplate-does-not-work-z7cwd2?file=/src/App.tsx

### Expected Behavior

When the schema type is unsupported in any way it should render the `UnsupportedFieldTemplate` and not break the Form.

This should include e.g.:
- `{ type: ["string", "unsupported type"] }`
- `{ type: ["number", "unsupported type"] }`

### Steps To Reproduce

Create a form with the following schema

```
{
  title: "Test form",
  type: ["string", "unsupported type"]
};
```

e.g.:
- https://codesandbox.io/s/unsupportedfieldtemplate-does-not-work-z7cwd2?file=/src/App.tsx

Observe that `UnsupportedFieldTemplate` does not render and the app/Form throws an exception.

### Environment

```markdown
- OS: Mac 13.5.1
- Node: 18.6.0
- npm: 9.5.1
```

**Comment by heath-freenome** [comment]
@jroebu14 Interesting that ordering is making a difference. Is this something you are willing to try and fix? We maintainers are pretty busy with our regular jobs and have maybe 2 hours a week to spend on fixes

**Comment by jroebu14** [comment]
@heath-freenome yeh I'm happy to try and fix. I had a look and I think I know where the issue is. I'll try and post a PR very soon.
