### ISSUE TITLE
Custom template for checkbox/boolean and select

### ISSUE THREAD

**Issue by brampurnot** [rjsf-team/react-jsonschema-form#3879]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

Hi all,

I'm trying to implement custom templates since we are using tailwinds and headless components. I have noticed that the standard BaseInputTemplate is not working for checkboxes/booleans. Also, there doesn't seem to be a custom template for select elements. 

Am I missing something in the documentation or am I right in saying that this is not supported?

Thanks,
Bram

**Comment by aularon** [comment]
I believe this is doable natively by passing the custom field/widget implementation to `uiSchema`. Below is a working solution using [`rjsf-layout`](https://github.com/etabits/rjsf-layout) however.
_(You can extract the inline component to make it reusable)_

<video src="https://github.com/rjsf-team/react-jsonschema-form/assets/1493032/8e7a21b8-f8ce-447d-af2d-b57a3e8bd07d" autoplay controls loop></video>

```tsx
"use client";
import Form, { JSONSchemaObject } from "rjsf-layout";
import validator from "@rjsf/validator-ajv8";

const listItems = ["a", "b", "c"] as const;
const schema = {
  type: "object",
  properties: {
    isChosen: {
      type: "boolean",
    },
    chosenItem: {
      type: "string",
      enum: listItems,
    },
  },
} as const satisfies JSONSchemaObject;

export const CustomFields = () => (
  <Form {...{ schema, validator }} formData={{}}>
    {({ IsChosen, ChosenItem, formData }) => (
      <>
        <table>
          <tbody>
            <tr>
              <th>boolean field:</th>
              <td>
                <IsChosen>
                  {/* First inline component that handles boolean values */}
                  {({ $isChosen, setIsChosen }) => (
                    <button
                      className={$isChosen ? "active" : ""}
                      onClick={() => setIsChosen(!$isChosen)}
                    >
                      {$isChosen ? "Chosen" : "NOT chosen!"}
                    </button>
                  )}
                </IsChosen>
              </td>
            </tr>
            <tr>
              <th>list field:</th>
              <td>
                <ChosenItem>
                  {/* Second inline component that handles the items list */}
                  {({ $chosenItem, setChosenItem }) =>
                    listItems.map((item) => (
                      <button
                        key={item}
                        className={item === $chosenItem ? "active" : ""}
                        onClick={() => setChosenItem(item)}
                      >
                        {item}
                      </button>
                    ))
                  }
                </ChosenItem>
              </td>
            </tr>
          </tbody>
        </table>
        <pre>{JSON.stringify(formData)}</pre>
        <style
          dangerouslySetInnerHTML={{
            __html: "button.active{background: darkblue;color:white}",
          }}
        ></style>
      </>
    )}
  </Form>
);
```

**Comment by heath-freenome** [comment]
@brampurnot Have you checked out the documentation around using [custom widgets](https://rjsf-team.github.io/react-jsonschema-form/docs/advanced-customization/custom-widgets-fields/)? Checkboxes and booleans are in fact not using the `BaseInputTemplate` as you can see from the implementation of `BooleanField`. It seems what you are really wanting is a new custom theme. I would look at how the existing themes are built on top of the `core` library

**Comment by brampurnot** [comment]
Thanks for responses. Custom widgets are indeed the way to do it.
