### ISSUE TITLE
Default values not set inside allOf

### ISSUE THREAD

**Issue by magaton** [rjsf-team/react-jsonschema-form#3892]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

mui

### Version

5.x

### Current Behavior

Default values are not set inside `allOf`

### Expected Behavior

The default values should be set

### Steps To Reproduce

[playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJkb3dubGluZSI6eyJ0eXBlIjp7Imxpc3QiOlsicGVyc29uYWwiLCJmcm9udGxpbmUiXX19fSwic2NoZW1hIjp7InRpdGxlIjoiQ29uZmlndXJhdGlvbiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImRvd25saW5lIjp7InRpdGxlIjoiRG93bmxpbmUiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0eXBlIjp7InByb3BlcnRpZXMiOnsibGlzdCI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJwZXJzb25hbCIsImZyb250bGluZSIsImdyb3VwIl19LCJkZWZhdWx0IjpbInBlcnNvbmFsIiwiZnJvbnRsaW5lIl0sInVuaXF1ZUl0ZW1zIjp0cnVlfX0sImFsbE9mIjpbeyJpZiI6eyJwcm9wZXJ0aWVzIjp7Imxpc3QiOnsiY29udGFpbnMiOnsiY29uc3QiOiJwZXJzb25hbCJ9fX19LCJ0aGVuIjp7InByb3BlcnRpZXMiOnsicGVyc29uYWwiOnsidGl0bGUiOiJQZXJzb25hbCIsInByb3BlcnRpZXMiOnsibWluTGV2ZWwiOnsidHlwZSI6ImludGVnZXIiLCJtaW5pbXVtIjowLCJtYXhpbXVtIjowLCJkZWZhdWx0IjowfSwibmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6IlBlcnNvbmFsIERvd25saW5lIn19fX19fSx7ImlmIjp7InByb3BlcnRpZXMiOnsibGlzdCI6eyJjb250YWlucyI6eyJjb25zdCI6ImZyb250bGluZSJ9fX19LCJ0aGVuIjp7InByb3BlcnRpZXMiOnsiZnJvbnRsaW5lIjp7InRpdGxlIjoiRnJvbnRsaW5lIiwicHJvcGVydGllcyI6eyJtaW5MZXZlbCI6eyJ0eXBlIjoiaW50ZWdlciIsIm1pbmltdW0iOjAsIm1heGltdW0iOjEsImRlZmF1bHQiOjF9LCJuYW1lIjp7InR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoiRnJvbnQgRG93bmxpbmUifX19fX19LHsiaWYiOnsicHJvcGVydGllcyI6eyJsaXN0Ijp7ImNvbnRhaW5zIjp7ImNvbnN0IjoiZ3JvdXAifX19fSwidGhlbiI6eyJwcm9wZXJ0aWVzIjp7Imdyb3VwIjp7InRpdGxlIjoiR3JvdXAiLCJwcm9wZXJ0aWVzIjp7Im1pbkxldmVsIjp7InR5cGUiOiJpbnRlZ2VyIiwibWluaW11bSI6MCwibWF4aW11bSI6MTAsImRlZmF1bHQiOjB9LCJuYW1lIjp7InR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoiR3JvdXAgRG93bmxpbmUifX19fX19XX19fX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjp7InBvcHVsYXRlIjoicG9wdWxhdGUiLCJtZXJnZUV4dHJhRGVmYXVsdHMiOmZhbHNlfSwiZW1wdHlPYmplY3RGaWVsZHMiOiJwb3B1bGF0ZUFsbERlZmF1bHRzIn19fQ==)

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Anything else?

This is kind of similar to the previously reported issue and [pull request](https://github.com/rjsf-team/react-jsonschema-form/pull/1304) that should have fixed the same problem inside `oneOf` and `anyOf`.

**Comment by heath-freenome** [comment]
@magaton Looks like you found another limitation in our `allOf` and/or `if-then-else` support. Is this something you are willing to try and fix?

**Comment by magaton** [comment]
I'd rather keep my qa / user tester hat since I am not a React or front-end developer. Maybe you could state what exactly needs to be done, so somebody can pick it up easier?

**Comment by heath-freenome** [comment]
Basically our `getDefaultFormState()` code does not process `if-then-else` or `allOf` statements at the moment. Thus additional work needs to happen to support these capabilities

**Comment by suman313** [comment]
Hi @heath-freenome ,
I would like to work on this issue.
Please assign me this issue.

**Comment by nobody19921117** [comment]
> Hi @heath-freenome , I would like to work on this issue. Please assign me this issue.

Thanks for your help, I use allOf and have the same issue. I would like to subscibe this issue.

**Comment by MarekBodingerBA** [comment]
This is a duplicate of my issue: https://github.com/rjsf-team/react-jsonschema-form/issues/3832

As there is no response in my thread, I am hijacking this one. I've [managed to debug](https://github.com/rjsf-team/react-jsonschema-form/issues/3832) the reason why this happens.

As an temporary fix we created [our own fork](https://github.com/bratislava/react-jsonschema-form) with [the fix](https://github.com/bratislava/react-jsonschema-form/commit/dd61b878365aa04a81ae132df3e9af10b5637bec) and we [patch the package](https://github.com/bratislava/konto.bratislava.sk/blob/master/next/patches/README.md) to have this functionality as we rely heavily on `allOf` in our schemas.

The fix has performance implications, from our internal testing `getDefaultFormState` takes multiples of the original time. It's OK for us, but we had to implement a [custom optimization for input fields](https://github.com/bratislava/konto.bratislava.sk/blob/master/next/components/forms/widget-components/FieldBlurWrapper/FieldBlurWrapper.tsx) that commits the value on blur instead of on change.

**Comment by heath-freenome** [comment]
@MarekBodingerBA Sorry we missed responding to your original issue. Given the solution causes a performance degradation, we definitely would not want to add it as the default behavior. We would definitely be open to adding it as an opt-in feature via a new `experimental_defaultFormStateBehavior.allOf` flag. Check out the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/form-props/#experimental_defaultformstatebehavior) of this flag and let us know whether this is something you'd like to build into the main product for us? I'm guessing that it would be a simple add to your already existing [fix](https://github.com/bratislava/react-jsonschema-form/commit/dd61b878365aa04a81ae132df3e9af10b5637bec). Then you could create a new PR for use to review on the main repo.

**Comment by benjdlambert** [comment]
@heath-freenome I went ahead and threw all this in a PR. Had some questions about the configuration schema, but seems to fix this issue and my previous issue which turned out to be a duplicate.
