### ISSUE TITLE
Add field name to `WrapIfAdditionalTemplateProps`

### ISSUE THREAD

**Issue by michal-kurz** [rjsf-team/react-jsonschema-form#3896]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### Is your feature request related to a problem? Please describe.

I want to add a data-testid attribute to all my fields, as suggested in this issue: https://github.com/rjsf-team/react-jsonschema-form/issues/1108

`WrapIfAdditionalTemplate` template seemed ideal for the job - something like this:

``` typescript
const WrapIfAdditionalTemplate = (props: WrapIfAdditionalTemplateProps) => {
  return (
    <div className={props.classNames} data-testid={xyz} style={props.style}>
      {props.children}
    </div>
  )
}
```

But I believe that it is currently not possible to get the field name from `WrapIfAdditionalTemplateProps`. `WrapIfAdditionalTemplateProps.id` includes it, but I don't think it's possible to parse it from there reliably, since it also includes all parent fields with separated with `_`, so it will be impossible to deremine for fields with underscores in name.

### Describe the solution you'd like

Add field name to `WrapIfAdditionalTemplateProps` :)

This might be useful in other use-cases, also. I can implement this, if you point me to the conceptual solution.

### Describe alternatives you've considered

Perhaps I'm missing something, and it's possible to get the name from `WrapIfAdditionalTemplateProps`, or perhaps it's possible to smuggle it inside there somehow :)

I also tried importing and wrapping native `FieldTemplate` like this:
``` typescript
// const FieldTempalte = getDefaultRegistry()?.templates.FieldTemplate
templates={{
  FieldTemplate: (...props) => {
    return (
      <div data-testid={xyz}>
        <FieldTempalte {...props} />
      </div>
    )
  },
}}
```

But surprisingly, this crashes and doesn't even render, plus this would add an additional html element wrapper, which might break some of our layouts. I would prefer to just use `WrapIfAdditionalTemplateProps` :)

**Comment by heath-freenome** [comment]
@michal-kurz Why not create a customized version of the [WrapIfAdditionalTemplate](https://rjsf-team.github.io/react-jsonschema-form/docs/advanced-customization/custom-templates/#wrapifadditionaltemplate)? You can also use the [idSeparator](https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/form-props/#idseparator) property on `Form` to switch the `_` to something else (my company uses `.`) to support field names that contain `_`. Is there anything else that seems to be blocking you?

**Comment by michal-kurz** [comment]
@heath-freenome 

> You can also use the [idSeparator](https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/form-props/#idseparator) property on Form to switch the only  _ to something else

Yes, this solves my problem, didn't know you could do that, thank you very much! I'm not blocked anymore :)

> Why not create a customized version of the [WrapIfAdditionalTemplate](https://rjsf-team.github.io/react-jsonschema-form/docs/advanced-customization/custom-templates/#wrapifadditionaltemplate)?

That's what I was trying to do, if I understand you correctly. But I didn't find a way to access the field name inside my implementation of `WrapIfAdditionalTemplate`. But using the previous point, I can now modify the `idSeparator` and parse the field name from field `id`.

**Comment by heath-freenome** [comment]
Awesome! Can I close this?

**Comment by michal-kurz** [comment]
@heath-freenome Yes, I'll close, sorry.
