### ISSUE TITLE
oneOf no longer has error helper text for invalid field

### ISSUE THREAD

**Issue by bishopj15** [rjsf-team/react-jsonschema-form#3908]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

material-ui

### Version

5.13.1

### Current Behavior

oneOf field does not include the "This field is required" helper text underneath the field

### Expected Behavior

oneOf field has helper text underneath the field

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Anything else?

[Playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJtZWRpYS10eXBlIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6Ik1lZGlhIFR5cGUiLCJvbmVPZiI6W3siY29uc3QiOiJ0diIsInRpdGxlIjoiVGVsZXZpc2lvbiJ9LHsiY29uc3QiOiJwYyIsInRpdGxlIjoiQ29tcHV0ZXIifSx7ImNvbnN0IjoiY29uc29sZSIsInRpdGxlIjoiQ29uc29sZSJ9XX0sIm1hbnVmYWN0dXJlciI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJNYW51ZmFjdHVyZXIiLCJvbmVPZiI6W3siY29uc3QiOiJibXciLCJ0aXRsZSI6IkJNVyJ9LHsiY29uc3QiOiJyZWRidWxsIiwidGl0bGUiOiJSZWRidWxsIn0seyJjb25zdCI6ImhhYXMiLCJ0aXRsZSI6IkhhYXMifV19LCJuYW1lIjp7InRpdGxlIjoiTmFtZSIsInR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbIm1lZGlhLXR5cGUiLCJtYW51ZmFjdHVyZXIiLCJuYW1lIl19LCJ1aVNjaGVtYSI6eyJtZWRpYS10eXBlIjp7Im9uZU9mIjp7InVpOndpZGdldCI6InJhZGlvIn0sInVpOndpZGdldCI6InJhZGlvIn19LCJ0aGVtZSI6Im1hdGVyaWFsLXVpLTUiLCJsaXZlU2V0dGluZ3MiOnsibGl2ZVZhbGlkYXRlIjp0cnVlLCJzaG93RXJyb3JMaXN0IjoidG9wIiwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjp7InBvcHVsYXRlIjoicG9wdWxhdGUiLCJtZXJnZUV4dHJhRGVmYXVsdHMiOmZhbHNlfSwiZW1wdHlPYmplY3RGaWVsZHMiOiJwb3B1bGF0ZUFsbERlZmF1bHRzIn0sImZvY3VzT25GaXJzdEVycm9yIjp0cnVlLCJub0h0bWw1VmFsaWRhdGUiOmZhbHNlfX0=)

**Comment by nickgros** [comment]
This is possibly caused by the change in https://github.com/rjsf-team/react-jsonschema-form/pull/3795

It seems like there are some cases where we DO want to show the error message for oneOf/anyOf, like the SelectWidget case in the playground example.

**Comment by nickgros** [comment]
@cwendtxealth do you have any time to take a look at this, since you made the original change?

**Comment by cwendtxealth** [comment]
> @cwendtxealth do you have any time to take a look at this, since you made the original change?

Yeah, I should have some time beginning of next week to take a look at this
