### ISSUE TITLE
Form becomes unresponsive when "liveOmit" and "omitExtraData" props are turned on for schemas containing fixed array of objects

### ISSUE THREAD

**Issue by Rozamo** [rjsf-team/react-jsonschema-form#3909]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.13.2

### Current Behavior

I am using the following schema in the playground with `liveOmit` and `omitExtraData` turned on

```json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "properties": {
    "array": {
      "type": "array",
      "items": [
        {
          "properties": {
            "title": {
              "type": "string"
            }
          }
        }
      ]
    }
  }
}
```

Upon typing anything in the `title` input box, the focus shifts away from the input box and there is no change in the input box or the form data

### Expected Behavior

The data entered should be reflected in the `title` input box and the form data.

### Steps To Reproduce

1. Go the the [rjsf playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhcnJheSI6W3t9XX0sInNjaGVtYSI6eyIkc2NoZW1hIjoiaHR0cDovL2pzb24tc2NoZW1hLm9yZy9kcmFmdC0wNy9zY2hlbWEiLCJwcm9wZXJ0aWVzIjp7ImFycmF5Ijp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjpbeyJwcm9wZXJ0aWVzIjp7InRpdGxlIjp7InR5cGUiOiJzdHJpbmcifX19XX19fSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsImV4cGVyaW1lbnRhbF9kZWZhdWx0Rm9ybVN0YXRlQmVoYXZpb3IiOnsiYXJyYXlNaW5JdGVtcyI6eyJwb3B1bGF0ZSI6InBvcHVsYXRlIiwibWVyZ2VFeHRyYURlZmF1bHRzIjpmYWxzZX0sImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyJ9fX0=)
3. Turn on the `liveOmit` and `omitExtraData` props
4. Try to enter some data in the `title` input box
5. The focus is lost and there is no change in the input box or the form data

### Environment

```markdown
- OS: macOS 13.5.1 
- Node: 18.15.0
- npm: 9.5.0
```

### Anything else?

- [Playground link showing the issue](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhcnJheSI6W3t9XX0sInNjaGVtYSI6eyIkc2NoZW1hIjoiaHR0cDovL2pzb24tc2NoZW1hLm9yZy9kcmFmdC0wNy9zY2hlbWEiLCJwcm9wZXJ0aWVzIjp7ImFycmF5Ijp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjpbeyJwcm9wZXJ0aWVzIjp7InRpdGxlIjp7InR5cGUiOiJzdHJpbmcifX19XX19fSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsib21pdEV4dHJhRGF0YSI6dHJ1ZSwic2hvd0Vycm9yTGlzdCI6InRvcCIsImV4cGVyaW1lbnRhbF9kZWZhdWx0Rm9ybVN0YXRlQmVoYXZpb3IiOnsiYXJyYXlNaW5JdGVtcyI6eyJwb3B1bGF0ZSI6InBvcHVsYXRlIiwibWVyZ2VFeHRyYURlZmF1bHRzIjpmYWxzZX0sImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyJ9LCJsaXZlT21pdCI6dHJ1ZX19)

**Comment by Rozamo** [comment]
@epicfaace Would like to contribute here. Don't have the permission to push the branch though. Can you please help here.

**Comment by Rozamo** [comment]
@heath-freenome @nickgros Please check this.

**Comment by nickgros** [comment]
@Rozamo thanks for the report. This is definitely a bad bug! Do you have any time to investigate this? We would be happy to help point you to likely places in code and review a PR.

**Comment by Rozamo** [comment]
> @Rozamo thanks for the report. This is definitely a bad bug! Do you have any time to investigate this? We would be happy to help point you to likely places in code and review a PR.

@nickgros Yes, I do. I have identified the issue and made changes in my local repo. But I am unable to push the branch to remote. Can you please help with the permission.

**Comment by nickgros** [comment]
@Rozamo You can create a forked repository in GitHub and push your changes to your forked repo. You can then open a pull request comparing the branch on your forked repo to the RJSF main branch

**Comment by Rozamo** [comment]
Thanks @nickgros. Have created a PR https://github.com/rjsf-team/react-jsonschema-form/pull/3916 for this.

**Comment by Rozamo** [comment]
This is the draft 07 versio. In this version the `items` keyword acts as both `prefixItems` and `items` keyword of the draft 2020-12 version that you have referred. Please check the draft specific info of [the array](https://json-schema.org/understanding-json-schema/reference/array#tupleValidation) section.

**Comment by Rozamo** [comment]
@anya92 Not sure if the issue you're facing is related to this fix. I tried the schema that you provided in the earlier version (15.13.2) and its not working there also.

Also, the schema provided in the issue description is correct according to the draft 07 version which is the [default](https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/form-props/#schema) used in rjsf. Please check the `Draft-specific info` of the [Tuple validation section](https://json-schema.org/understanding-json-schema/reference/array#tuple-validation).

**Comment by heath-freenome** [comment]
@anya92 Can you create an issue for this? Please reference this thread
