### ISSUE TITLE
Error "Must be a multiple of 0.01" for Value=2000000.13

### ISSUE THREAD

**Issue by Alicezhang821** [rjsf-team/react-jsonschema-form#3917]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Version

5.x

### Current Behavior

Hello,
I used the playground https://rjsf-team.github.io/react-jsonschema-form/ to create a number field, but it failed with validation for some values like '2000000.13', error message says 'Must be a multiple of 0.01'

JSONSchema
`{ "type": "object", "title": "Number fields & widgets", "properties": { "number": { "title": "Number", "type": "number", "multipleOf": 0.01 } } }`
UISchema
`{}`
Some other values failed the validation as well, for example
39999999.12
1234599.12

Thanks in advance.

### Expected Behavior

The field should accept number like '2000000.13'

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by linde12** [comment]
ajv6 or 8? spontaneous thought is floating point error or side effect of the `multipleOfPrecision` setting but did not look deeper

**Comment by YuJianghao** [comment]
> ajv6 or 8? spontaneous thought is floating point error or side effect of the `multipleOfPrecision` setting but did not look deeper

I tried: ajv8 with `multipleOfPrecision: 4` can fix it. [ajv doc for multipleOfPrecision](https://ajv.js.org/options.html#multipleofprecision)

**Comment by heath-freenome** [comment]
@Alicezhang821 If you are experiencing this in your application, you can set the precision for the `validator-ajv6` or `validator-ajv8` using the [ajvoptionsoverrides](https://rjsf-team.github.io/react-jsonschema-form/docs/usage/validation/#ajvoptionsoverrides) capability for your validator. If it's only a `playground` issue, then we'd like close it. Thanks!

**Comment by Alicezhang821** [comment]
Thanks everyone!
