### ISSUE TITLE
Possible bug with anyOf/oneOf when the selected schema changes from type:string to type:object

### ISSUE THREAD

**Issue by lindolo25** [rjsf-team/react-jsonschema-form#3922]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

bootstrap-4

### Version

5.1.0

### Current Behavior

Given an **anyOf** or a **oneOf** composition schema with two options. First an object with one property of type string and second just a string value. When option 2 has a value (example `"adsads"`) and the dropdown is changed to the option 1. The value is set to  this: 
```json
{
  "0": "a",
  "1": "d",
  "2": "s",
  "3": "a",
  "4": "d",
  "5": "s"
}
```
It continues to keep those added properties after a value is give to option 1 string property:
```json
{
  "0": "a",
  "1": "d",
  "2": "s",
  "3": "a",
  "4": "d",
  "5": "s",
  "foo": "werwer"
}
```
Even if the `"additionalProperties": false` is set the an error will not be presented.

![image](https://github.com/rjsf-team/react-jsonschema-form/assets/34461902/25078393-fb71-42f8-b42e-a957e3608b17)

The scenario will work as expected if option 2 has another type of value, I tested [number](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6NCwic2NoZW1hIjp7ImFueU9mIjpbeyJ0aXRsZSI6Ik9wdGlvbiAxIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZm9vIjp7InR5cGUiOiJzdHJpbmcifX0sImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjpmYWxzZX0seyJ0aXRsZSI6Ik9wdGlvbiAyIiwidHlwZSI6Im51bWJlciJ9XX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJleHBlcmltZW50YWxfZGVmYXVsdEZvcm1TdGF0ZUJlaGF2aW9yIjp7ImFycmF5TWluSXRlbXMiOnsicG9wdWxhdGUiOiJwb3B1bGF0ZSIsIm1lcmdlRXh0cmFEZWZhdWx0cyI6ZmFsc2V9LCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMifX19) and [boolean](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6dHJ1ZSwic2NoZW1hIjp7ImFueU9mIjpbeyJ0aXRsZSI6Ik9wdGlvbiAxIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZm9vIjp7InR5cGUiOiJzdHJpbmcifX0sImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjpmYWxzZX0seyJ0aXRsZSI6Ik9wdGlvbiAyIiwidHlwZSI6ImJvb2xlYW4ifV19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjp7InBvcHVsYXRlIjoicG9wdWxhdGUiLCJtZXJnZUV4dHJhRGVmYXVsdHMiOmZhbHNlfSwiZW1wdHlPYmplY3RGaWVsZHMiOiJwb3B1bGF0ZUFsbERlZmF1bHRzIn19fQ==).

### Expected Behavior

After switching to the Option 1, the value should be and empty object `{}`.

### Steps To Reproduce

1. Open the [setup](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6ImFkc2FkcyIsInNjaGVtYSI6eyJhbnlPZiI6W3sidGl0bGUiOiJPcHRpb24gMSIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImZvbyI6eyJ0eXBlIjoic3RyaW5nIn19LCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2V9LHsidGl0bGUiOiJPcHRpb24gMiIsInR5cGUiOiJzdHJpbmcifV19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjp7InBvcHVsYXRlIjoicG9wdWxhdGUiLCJtZXJnZUV4dHJhRGVmYXVsdHMiOmZhbHNlfSwiZW1wdHlPYmplY3RGaWVsZHMiOiJwb3B1bGF0ZUFsbERlZmF1bHRzIn19fQ==)
2. Select Option 1
3. Type a value for "foo"

### Environment

```markdown
- OS: Fedora 38 (Workstation Edition)
- Node: v18.16.0
- npm: v9.5.1
```

### Anything else?

I narrow it down to the result of the function `schemaUtils.sanitizeDataForNewSchema(newOption, oldOption, formData)` in line 122 of the MultiSchemaField.tsx file. 

https://github.com/rjsf-team/react-jsonschema-form/blob/42e138c5d6785e84aa4500c83bf70af8c001236c/packages/core/src/components/fields/MultiSchemaField.tsx#L122

After that function is executed, `newFormData` takes that value and later on is used to update the field value in line 128. I'll update later if I'm able to find out more about this issue.

**Comment by nickgros** [comment]
Definitely something unusual happening here. Thanks for the report @lindolo25 ! If you can open a PR to fix this we would be happy to review and accept it.
