### ISSUE TITLE
Error: React does not recognize the `hideError` prop on a DOM element

### ISSUE THREAD

**Issue by ValYouW** [rjsf-team/react-jsonschema-form#3945]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

mui

### Version

5.13.6

### Current Behavior

Starting at 5.13.6 I get the following error in the console:
```
Warning: React does not recognize the `hideError` prop on a DOM element
```

I didn't investigate it further aside from the fact that this error doesn't happen on 5.13.5 and that most likely it is coming from 
`packages/mui/src/BaseInputTemplate/BaseInputTemplate.tsx` where `hideError` is not being extracted from `props`.

**Comment by heath-freenome** [comment]
@ValYouW Are you willing to provide a fix for `BaseInputTemplate` in the `mui` and `material-ui` themes (they are the same code)?

**Comment by ValYouW** [comment]
@heath-freenome Done.
