### ISSUE TITLE
Fluent UI 9: Field component only allows string as label

### ISSUE THREAD

**Issue by marcveens** [rjsf-team/react-jsonschema-form#3946]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

other

### Version

5.13.6

### Current Behavior

In `SelectWidget.tsx` there's a Fluent UI 9 `<Field />` component that only allows string or undefined as a label property. `labelValue(label, hideLabel)` provided by RJSF could also return `false` or a React component. A ts-expected-error solves it for now.

This is not an issue on implementation level, only for developers of the `fluentui-rc` package.

### Expected Behavior

The `ts-expected-error` should not be necessary.

### Environment

```markdown
- OS: macOS Sonoma
- Node: 18.14.0
- npm: 9.3.1
```

**Comment by heath-freenome** [comment]
@marcveens Looks like we found a fix. Also, since I just released `5.14.0` please push a PR that adds the new theme into the playground! Thanks

**Comment by marcveens** [comment]
Thank you guys! 

I've added a PR for adding the theme to the playground, #3951
