### ISSUE TITLE
Packages are using tsc-compiled files instead of ESM

### ISSUE THREAD

**Issue by sarenji** [rjsf-team/react-jsonschema-form#3958]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

We're trying to upgrade `@rjsf/core`, `@rjsf/utils` and `@rjsf/validator-ajv8` from 5.8.2 to 5.14.1. However, we run into a bundle error when importing `@rjsf/utils` with ESM, because Yarn cannot resolve `tslib`:

```
    .yarn/__virtual__/@rjsf-utils-virtual-221548ebb0/0/cache/@rjsf-utils-npm-5.14.1-5c751cec25-68b230fb55.zip/node_modules/@rjsf/utils/lib/schema/getMatchingOption.js:1:23:
      1 │ import { __rest } from "tslib";
```

### Expected Behavior

Ideally we should be able to import `@rjsf/utils` without error.

I dug into it a little bit and discovered that `@rjsf/utils@5.14.1` compiles its files into `.js` using `tsc`. The package then sets [`lib/index.js` as the `module` field.](https://www.runpkg.com/?@rjsf/utils@5.14.1/package.json#5), which eventually points to [a file that has `tslib` injected](https://www.runpkg.com/?@rjsf/utils@5.14.1/lib/schema/getMatchingOption.js#1).

On the other hand, [version 5.8.2 uses the compiled ESM file instead](https://www.runpkg.com/?@rjsf/utils@5.8.2/package.json#5).

Yarn protects us from [ghost dependencies](https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies), which is why we get the error.

I believe `@rjsf` could either:

1. Revert the change to the `module` field from `dist/utils.esm.js` to `lib/index.js`.
2. OR add `tslib` to the package's dependencies, if you want to continue using TypeScript-compiled files.

### Steps To Reproduce

Import `@rjsf/utils` with Yarn as the package manager.

Example repro: https://codesandbox.io/s/condescending-platform-q8wtk8?file=/src/index.js

### Environment

```markdown
- OS: Mac OS X 13.6
- Node: 18.15.0
- Yarn: 4.0.0-rc.50
```

**Comment by heath-freenome** [comment]
@zxbodya Since you made the change, do you have an idea on how to fix this?

**Comment by zxbodya** [comment]
good catch, we indeed have incorrect configuration for tsc output -- created a PR updating it
