### ISSUE TITLE
Compile Schema not resolving all anyOf/oneOf refs

### ISSUE THREAD

**Issue by cwendtxealth** [rjsf-team/react-jsonschema-form#3961]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

When compiling a schema that uses an anyOf/oneOf schema the [resolveAllReferences](https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/utils/src/schema/retrieveSchema.ts#L258) function util won't fully resolve all refs if the same ref is used multiple times in one schema object. For example
```
{
  type: 'object',
  anyOf: [{
    type: 'object',
    properties: {
      test1: {
        $ref: '#/definitions/testref'
      },
      test2: {
        $ref: '#/definitions/testref'
      }
    }
  }],
  definitions: {
    testref: {
      type: 'string'
    }
  }
}
```
`resolveAllReferences` will resolve the first ref but then because it has already resolved the first it will ignore the second leading to errors in compiled schema.

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by heath-freenome** [comment]
@cwendtxealth Can you work on the fix by doing something like this in the `resolveAllReferences()`?:

```
  if (PROPERTIES_KEY in resolvedSchema) {
    const childrenLists = []; 
    const updatedProps = transform(
      resolvedSchema[PROPERTIES_KEY]!,
      (result, value, key: string) => {
        const childList = [...recurseList];
        childrenLists.push(childList);
        result[key] = resolveAllReferences(value as S, rootSchema, childList);
      },
      {} as RJSFSchema
    );
    // flatten, uniq, merge missing into recurseList
    resolvedSchema = { ...resolvedSchema, [PROPERTIES_KEY]: updatedProps };
  }

```
