### ISSUE TITLE
Default values don't seem to be displayed when using themes

### ISSUE THREAD

**Issue by benjdlambert** [rjsf-team/react-jsonschema-form#3963]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

material-ui

### Version

5.x

### Current Behavior

It looks like there's some issues with default values not being displayed properly when using some themes. The default theme and bootstrap themes work as expected, but it looks like the material-ui / mui themes don't render the default value correctly.

### Expected Behavior

The default value renders in the input field

### Steps To Reproduce

[material-ui playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhbmltYWxJbmZvIjp7ImFuaW1hbCI6IkNhdCJ9LCJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCIsInRlbGVwaG9uZSI6IjEtODAwLUtJQ0tBU1MifSwic2NoZW1hIjp7InRpdGxlIjoiRXhhbXBsZSIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImFuaW1hbEluZm8iOnsicHJvcGVydGllcyI6eyJhbmltYWwiOnsidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJDYXQiLCJlbnVtIjpbIkNhdCIsIkZpc2giXX19LCJhbGxPZiI6W3siaWYiOnsicHJvcGVydGllcyI6eyJhbmltYWwiOnsiY29uc3QiOiJDYXQifX19LCJ0aGVuIjp7InByb3BlcnRpZXMiOnsiZm9vZCI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6Im1lYXQiLCJlbnVtIjpbIm1lYXQiLCJncmFzcyIsImZpc2giXX19LCJyZXF1aXJlZCI6WyJmb29kIl19fSx7ImlmIjp7InByb3BlcnRpZXMiOnsiYW5pbWFsIjp7ImNvbnN0IjoiRmlzaCJ9fX0sInRoZW4iOnsicHJvcGVydGllcyI6eyJmb29kIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbImluc2VjdCIsIndvcm1zIl19LCJ3YXRlciI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJsYWtlIiwic2VhIl19fSwicmVxdWlyZWQiOlsiZm9vZCIsIndhdGVyIl19fSx7InJlcXVpcmVkIjpbImFuaW1hbCJdfV19fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTpwbGFjZWhvbGRlciI6InVpOmVtcHR5VmFsdWUgY2F1c2VzIHRoaXMgZmllbGQgdG8gYWx3YXlzIGJlIHZhbGlkIGRlc3BpdGUgYmVpbmcgcmVxdWlyZWQiLCJ1aTphdXRvY29tcGxldGUiOiJmYW1pbHktbmFtZSIsInVpOmVuYWJsZU1hcmtkb3duSW5EZXNjcmlwdGlvbiI6dHJ1ZSwidWk6ZGVzY3JpcHRpb24iOiJNYWtlIHRleHQgKipib2xkKiogb3IgKml0YWxpYyouIFRha2UgYSBsb29rIGF0IG90aGVyIG9wdGlvbnMgW2hlcmVdKGh0dHBzOi8vcHJvYmFibHl1cC5jb20vbWFya2Rvd24tdG8tanN4LykuIn0sImxhc3ROYW1lIjp7InVpOmF1dG9jb21wbGV0ZSI6ImdpdmVuLW5hbWUiLCJ1aTplbmFibGVNYXJrZG93bkluRGVzY3JpcHRpb24iOnRydWUsInVpOmRlc2NyaXB0aW9uIjoiTWFrZSB0aGluZ3MgKipib2xkKiogb3IgKml0YWxpYyouIEVtYmVkIHNuaXBwZXRzIG9mIGBjb2RlYC4gPHNtYWxsPkFuZCB0aGlzIGlzIGEgc21hbGwgdGV4dHMuPC9zbWFsbD4gIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aCB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sInRoZW1lIjoibWF0ZXJpYWwtdWktNCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsIm5vSHRtbDVWYWxpZGF0ZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZSwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjoicG9wdWxhdGUiLCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMifX19)

[default theme playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhbmltYWxJbmZvIjp7ImFuaW1hbCI6IkNhdCJ9LCJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCIsInRlbGVwaG9uZSI6IjEtODAwLUtJQ0tBU1MifSwic2NoZW1hIjp7InRpdGxlIjoiRXhhbXBsZSIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImFuaW1hbEluZm8iOnsicHJvcGVydGllcyI6eyJhbmltYWwiOnsidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJDYXQiLCJlbnVtIjpbIkNhdCIsIkZpc2giXX19LCJhbGxPZiI6W3siaWYiOnsicHJvcGVydGllcyI6eyJhbmltYWwiOnsiY29uc3QiOiJDYXQifX19LCJ0aGVuIjp7InByb3BlcnRpZXMiOnsiZm9vZCI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6Im1lYXQiLCJlbnVtIjpbIm1lYXQiLCJncmFzcyIsImZpc2giXX19LCJyZXF1aXJlZCI6WyJmb29kIl19fSx7ImlmIjp7InByb3BlcnRpZXMiOnsiYW5pbWFsIjp7ImNvbnN0IjoiRmlzaCJ9fX0sInRoZW4iOnsicHJvcGVydGllcyI6eyJmb29kIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbImluc2VjdCIsIndvcm1zIl19LCJ3YXRlciI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJsYWtlIiwic2VhIl19fSwicmVxdWlyZWQiOlsiZm9vZCIsIndhdGVyIl19fSx7InJlcXVpcmVkIjpbImFuaW1hbCJdfV19fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTpwbGFjZWhvbGRlciI6InVpOmVtcHR5VmFsdWUgY2F1c2VzIHRoaXMgZmllbGQgdG8gYWx3YXlzIGJlIHZhbGlkIGRlc3BpdGUgYmVpbmcgcmVxdWlyZWQiLCJ1aTphdXRvY29tcGxldGUiOiJmYW1pbHktbmFtZSIsInVpOmVuYWJsZU1hcmtkb3duSW5EZXNjcmlwdGlvbiI6dHJ1ZSwidWk6ZGVzY3JpcHRpb24iOiJNYWtlIHRleHQgKipib2xkKiogb3IgKml0YWxpYyouIFRha2UgYSBsb29rIGF0IG90aGVyIG9wdGlvbnMgW2hlcmVdKGh0dHBzOi8vcHJvYmFibHl1cC5jb20vbWFya2Rvd24tdG8tanN4LykuIn0sImxhc3ROYW1lIjp7InVpOmF1dG9jb21wbGV0ZSI6ImdpdmVuLW5hbWUiLCJ1aTplbmFibGVNYXJrZG93bkluRGVzY3JpcHRpb24iOnRydWUsInVpOmRlc2NyaXB0aW9uIjoiTWFrZSB0aGluZ3MgKipib2xkKiogb3IgKml0YWxpYyouIEVtYmVkIHNuaXBwZXRzIG9mIGBjb2RlYC4gPHNtYWxsPkFuZCB0aGlzIGlzIGEgc21hbGwgdGV4dHMuPC9zbWFsbD4gIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aCB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsIm5vSHRtbDVWYWxpZGF0ZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZSwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjoicG9wdWxhdGUiLCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMifX19)

### Environment

```markdown
Not relevant
```

### Anything else?

Apologies if there's already an issue for this already, but don't think it's related to the already existing `allOf` `if-then-else` issues as this seems to be a theme issue rather than a core library problem?

**Comment by heath-freenome** [comment]
@benjdlambert Wow, this seems to be an issue with the `SelectWidget` implementation in the non-bootstrap themes. Thanks for finding it. Are you willing to debug the `material-ui` issue and let us know what you find? I'm guessing the bug is probably consistent across all themes?

**Comment by benjdlambert** [comment]
@heath-freenome i can for sure dig around a little bit. Thanks for pointing in a direction on where to start!

**Comment by benjdlambert** [comment]
@heath-freenome did some digging around, and it actually looks like this is just a symptom of https://github.com/rjsf-team/react-jsonschema-form/issues/3892. The values are never added to the model, so what happens is that some of the themes have a placeholder for the first item in the list. 

I will close this issue as a duplicate, and look at implementing that.
