### ISSUE TITLE
`title` keyword  does not work for some object properties 

### ISSUE THREAD

**Issue by michal-kurz** [rjsf-team/react-jsonschema-form#4000]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.6.2

### Current Behavior

With the following schema, only first property (`t`) gets its title displayed properly. The second property (`t2`) displays the property name as a title ([playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0Ijp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlRJVExFIn0sInQyIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZToiOiJUSVRMRSJ9fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGVkIjpmYWxzZSwibm9IdG1sNVZhbGlkYXRlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlLCJleHBlcmltZW50YWxfZGVmYXVsdEZvcm1TdGF0ZUJlaGF2aW9yIjp7ImFycmF5TWluSXRlbXMiOiJwb3B1bGF0ZSIsImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyJ9fX0=)):

``` json
{
  "type": "object",
  "properties": {
    "t": {
      "type": "string",
      "title": "TITLE"
    },
    "t2": {
      "type": "string",
      "title:": "TITLE"
    }
  }
}
```

This behaviour seems to be related to property name and order, and can be widely reproduced with many different keys ([example playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJzb21ldGhpbmdfZWxzZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGU6IjoiVElUTEUifSwidCI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJUSVRMRSJ9LCJ0MiI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGU6IjoiVElUTEUifSwiZm9vMTIzIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZToiOiJUSVRMRSJ9fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGVkIjpmYWxzZSwibm9IdG1sNVZhbGlkYXRlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlLCJleHBlcmltZW50YWxfZGVmYXVsdEZvcm1TdGF0ZUJlaGF2aW9yIjp7ImFycmF5TWluSXRlbXMiOiJwb3B1bGF0ZSIsImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyJ9fX0=)).

It can be circumvented via `ui:title` ([playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0Ijp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlRJVExFIn0sInQyIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZToiOiJUSVRMRSJ9fX0sInVpU2NoZW1hIjp7InQyIjp7InVpOnRpdGxlIjoiVElUTEUifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsIm5vSHRtbDVWYWxpZGF0ZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZSwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjoicG9wdWxhdGUiLCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMifX19))

### Expected Behavior

I am expecting all fields to be titled `TITLE`

### Steps To Reproduce

See the playgrounds above

### Anything else?

I'm not sure what to think of this, it seems to me like the `title` keyword is fundamentally broken in current release - so maybe I'm just missing something.

**Comment by nickgros** [comment]
Thanks for the report @michal-kurz --this is a strange issue. The issue persists across all themes, so it's probably in a shared component like SchemaField.

**Comment by nickgros** [comment]
@michal-kurz I think there's just a typo in the schema, `"title:"` should be `"title"`. Can you verify if this is the issue? 🙂

**Comment by michal-kurz** [comment]
@nickgros Yeah...  I feel pretty stupid. Both my colleague and I spent over an hour each on this 😅

Thanks for pointing it out, and sorry for wasting your time
