### ISSUE TITLE
Setting up dynamic defaults

### ISSUE THREAD

**Issue by psmolaga** [rjsf-team/react-jsonschema-form#4003]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

The default unit select value is set only on the last select

### Expected Behavior

The default value should be set on all unit selects

### Steps To Reproduce

1. Open https://codesandbox.io/p/sandbox/rjsf-defaults-fx93qv
2. Notice that only the Length Unit select has the default value
3. The Area Unit select input is empty

I'm dealing with a scenario where dynamic defaults are established depending on the context. Users can select a unit system, and using this input, we determine the default units if the unit select is blank. I've devised a solution to activate the onChange function in the SelectWidget when the unit system is modified, but I've encountered an issue. Upon further investigation, it appears that there's a complication with closures, and [onPropertyChange](https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/core/src/components/fields/ObjectField.tsx#L68-L92) fetches the outdated state. This results in only the final invocation of the onChange callback influencing the data.

### Environment

```markdown
- OS: macOS Sonoma 14.1.2
- Node: v18.16.0
- npm: v9.5.1
```

### Anything else?

https://codesandbox.io/p/sandbox/rjsf-defaults-fx93qv

**Comment by nickgros** [comment]
Sorry, the linked stackblitz doesn't load for me

**Comment by psmolaga** [comment]
Hi @nickgros, StackBlitz have some issues. I'll provide another link with the reproduction today.

**Comment by psmolaga** [comment]
@nickgros I've revised the link to the reproduction. Please focus on the useEffect within the Select Widget, specifically the onChange callback that includes the default value.

If you require further information regarding the issue, please feel free to inform me. I would be delighted to assist you.

**Comment by Stusu** [comment]
It is the same issue as #3367

**Comment by heath-freenome** [comment]
@psmolaga can you verify that this is a duplicate of #3367, and if so, please close this one?

**Comment by psmolaga** [comment]
Yes, it is a duplicate of #3367. I'm closing this issue.

@heath-freenome Are there any plans to fix this issue?

**Comment by psmolaga** [comment]
Duplicate of #3367
