### ISSUE TITLE
Multiple conditions on 1 field

### ISSUE THREAD

**Issue by JalalMiftah** [rjsf-team/react-jsonschema-form#4009]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

Hi, I have a simple form:

```
{
    "type": "object",
    "title": "test",
    "properties": {
        "videoGames": {
            "type": "string",
            "title": "Do you like video games?",
            "oneOf": [
                {
                    "title": "No",
                    "const": "No"
                },
                {
                    "title": "Yes",
                    "const": "Yes"
                }
            ],
            "default": "No"
        },
        "movies": {
          "type": "string",
          "title": "Do you like movies?",
          "oneOf": [
                {
                    "title": "No",
                    "const": "No"
                },
                {
                    "title": "Yes",
                    "const": "Yes"
                }
            ],
            "default": "No"
        }
    }
}
```

Now I would like to display a new field only if I've answered "Yes" to both. Is there an easy way to achieve that? 
Thank you

**Comment by Stusu** [comment]
Hi, it can be done with if-then. You can check how it works on this [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ2aWRlb0dhbWVzIjoiTm8iLCJtb3ZpZXMiOiJObyIsInNwb3J0IjoiTm8iLCJzcG9yIjoiTm8iLCJzcG8iOiJObyIsInNwIjoiTm8iLCJzIjoiTm8iLCJuZXdRdWVzdGlvbiI6Ik5vIiwiZmlyc3ROYW1lIjoiQ2h1Y2siLCJsYXN0TmFtZSI6Ik5vcnJpcyIsImFnZSI6NzUsImJpbyI6IlJvdW5kaG91c2Uga2lja2luZyBhc3NlcyBzaW5jZSAxOTQwIiwicGFzc3dvcmQiOiJub25lZWQiLCJ0ZWxlcGhvbmUiOiIxLTgwMC1LSUNLQVNTIn0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwidGl0bGUiOiJ0ZXN0IiwicHJvcGVydGllcyI6eyJ2aWRlb0dhbWVzIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkRvIHlvdSBsaWtlIHZpZGVvIGdhbWVzPyIsIm9uZU9mIjpbeyJ0aXRsZSI6Ik5vIiwiY29uc3QiOiJObyJ9LHsidGl0bGUiOiJZZXMiLCJjb25zdCI6IlllcyJ9XSwiZGVmYXVsdCI6Ik5vIn0sIm1vdmllcyI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJEbyB5b3UgbGlrZSBtb3ZpZXM/Iiwib25lT2YiOlt7InRpdGxlIjoiTm8iLCJjb25zdCI6Ik5vIn0seyJ0aXRsZSI6IlllcyIsImNvbnN0IjoiWWVzIn1dLCJkZWZhdWx0IjoiTm8ifX0sImFsbE9mIjpbeyJpZiI6eyJwcm9wZXJ0aWVzIjp7InZpZGVvR2FtZXMiOnsiY29uc3QiOiJZZXMifSwibW92aWVzIjp7ImNvbnN0IjoiWWVzIn19fSwidGhlbiI6eyJwcm9wZXJ0aWVzIjp7InNwb3J0Ijp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkRvIHlvdSBsaWtlIHNwb3J0PyIsIm9uZU9mIjpbeyJ0aXRsZSI6Ik5vIiwiY29uc3QiOiJObyJ9LHsidGl0bGUiOiJZZXMiLCJjb25zdCI6IlllcyJ9XSwiZGVmYXVsdCI6Ik5vIn19fX1dfSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiIsInVpOnBsYWNlaG9sZGVyIjoidWk6ZW1wdHlWYWx1ZSBjYXVzZXMgdGhpcyBmaWVsZCB0byBhbHdheXMgYmUgdmFsaWQgZGVzcGl0ZSBiZWluZyByZXF1aXJlZCIsInVpOmF1dG9jb21wbGV0ZSI6ImZhbWlseS1uYW1lIiwidWk6ZW5hYmxlTWFya2Rvd25JbkRlc2NyaXB0aW9uIjp0cnVlLCJ1aTpkZXNjcmlwdGlvbiI6Ik1ha2UgdGV4dCAqKmJvbGQqKiBvciAqaXRhbGljKi4gVGFrZSBhIGxvb2sgYXQgb3RoZXIgb3B0aW9ucyBbaGVyZV0oaHR0cHM6Ly9wcm9iYWJseXVwLmNvbS9tYXJrZG93bi10by1qc3gvKS4ifSwibGFzdE5hbWUiOnsidWk6YXV0b2NvbXBsZXRlIjoiZ2l2ZW4tbmFtZSIsInVpOmVuYWJsZU1hcmtkb3duSW5EZXNjcmlwdGlvbiI6dHJ1ZSwidWk6ZGVzY3JpcHRpb24iOiJNYWtlIHRoaW5ncyAqKmJvbGQqKiBvciAqaXRhbGljKi4gRW1iZWQgc25pcHBldHMgb2YgYGNvZGVgLiA8c21hbGw+QW5kIHRoaXMgaXMgYSBzbWFsbCB0ZXh0cy48L3NtYWxsPiAifSwiYWdlIjp7InVpOndpZGdldCI6InVwZG93biIsInVpOnRpdGxlIjoiQWdlIG9mIHBlcnNvbiIsInVpOmRlc2NyaXB0aW9uIjoiKGVhcnRoIHllYXIpIn0sImJpbyI6eyJ1aTp3aWRnZXQiOiJ0ZXh0YXJlYSJ9LCJwYXNzd29yZCI6eyJ1aTp3aWRnZXQiOiJwYXNzd29yZCIsInVpOmhlbHAiOiJIaW50OiBNYWtlIGl0IHN0cm9uZyEifSwidGVsZXBob25lIjp7InVpOm9wdGlvbnMiOnsiaW5wdXRUeXBlIjoidGVsIn19fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGVkIjpmYWxzZSwibm9IdG1sNVZhbGlkYXRlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlLCJleHBlcmltZW50YWxfZGVmYXVsdEZvcm1TdGF0ZUJlaGF2aW9yIjp7ImFycmF5TWluSXRlbXMiOiJwb3B1bGF0ZSIsImFsbE9mIjoic2tpcERlZmF1bHRzIiwiZW1wdHlPYmplY3RGaWVsZHMiOiJwb3B1bGF0ZUFsbERlZmF1bHRzIn19fQ==)
```
{
  "type": "object",
  "title": "test",
  "properties": {
    "videoGames": {
      "type": "string",
      "title": "Do you like video games?",
      "oneOf": [
        {
          "title": "No",
          "const": "No"
        },
        {
          "title": "Yes",
          "const": "Yes"
        }
      ],
      "default": "No"
    },
    "movies": {
      "type": "string",
      "title": "Do you like movies?",
      "oneOf": [
        {
          "title": "No",
          "const": "No"
        },
        {
          "title": "Yes",
          "const": "Yes"
        }
      ],
      "default": "No"
    }
  },
  "allOf": [
    {
      "if": {
        "properties": {
          "videoGames": {
            "const": "Yes"
          },
          "movies": {
            "const": "Yes"
          }
        }
      },
      "then": {
        "properties": {
          "sport": {
            "type": "string",
            "title": "Do you like sport?",
            "oneOf": [
              {
                "title": "No",
                "const": "No"
              },
              {
                "title": "Yes",
                "const": "Yes"
              }
            ],
            "default": "No"
          }
        }
      }
    }
  ]
}
```

**Comment by heath-freenome** [comment]
@JalalMiftah If your question is answered, please close

**Comment by JalalMiftah** [comment]
Thank you @Stusu !
