### ISSUE TITLE
submit is not public

### ISSUE THREAD

**Issue by popmanhe** [rjsf-team/react-jsonschema-form#4015]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

4.2.3

### Current Behavior

> Submit form programmatically
> You can use the reference to get your Form component and call the submit method to submit the form programmatically without a submit button. This method will dispatch the submit event of the form, and the function, that is passed to onSubmit props, will be called.

But actually, the submit method is private, and can not be called from outside.

### Expected Behavior

Can be called from outside. Like in the sample,  yourForm.submit();

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Anything else?

The fix is pretty simple. Just make it the public method.

Change from 
```
submit(){
...
}

```
to

```
submit=()=>{
...
}
```

The bug exists in 4.x and 5.x

**Comment by heath-freenome** [comment]
@popmanhe You just need to call it from the ref. See this [documention](https://rjsf-team.github.io/react-jsonschema-form/docs/advanced-customization/internals/#submit-form-programmatically)

**Comment by popmanhe** [comment]
I did. But as it is in the screenshot. There is simply not submit method. Because it's not a public method. 

![image](https://github.com/rjsf-team/react-jsonschema-form/assets/2193792/f1ea3ea1-5c48-4bea-976c-7e006ded39aa)

**Comment by heath-freenome** [comment]
If you look at the [playground code](https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/playground/src/components/Header.tsx#L33) we are using the method just fine. Can you just try it?

**Comment by heath-freenome** [comment]
You are also welcome to submit a PR making the change you suggested.

**Comment by nickgros** [comment]
@popmanhe programmatic submit was not added until v5.0.0 ([see changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md#v500-beta3)). Try migrating to v5

**Comment by popmanhe** [comment]
Yes, it works in v5. even if it's not a public method. I don't know why. You may not need this PR.

But according to this page, v4 also supports programmatic submit.
https://rjsf-team.github.io/react-jsonschema-form/docs/version-4.2.3/advanced-customization/internals

**Comment by nickgros** [comment]
Ah, I was mistaken. Programmatic submit was in v4, but there were issues that were fixed in v5. [This comment](https://github.com/rjsf-team/react-jsonschema-form/issues/3023#issuecomment-1240529700) describes a workaround to a similar-sounding issue. Maybe this would help you?

**Comment by codeinearts** [comment]
Leaving my two cents:

I was having issues with the programmatic submit when I got here in the first place.

Looking at the playground code @heath-freenome shared, I realized that [the docs](https://rjsf-team.github.io/react-jsonschema-form/docs/advanced-customization/internals#submit-form-programmatically) are incorrect, using `createRef` instead of `useRef`, which can cause issues across re-renders on functional components ( createRef always create a new reference )

Using the approach at [the playground code](https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/playground/src/components/Playground.tsx#L46) works for me.

Discussion https://stackoverflow.com/a/54620836

**Comment by heath-freenome** [comment]
@codeinearts If you are using the Form inside of another stateless functional component, then, yes, the `useRef` hook is the correct approach. The docs are more of a stand-alone implementation. Feel free to push a PR that enhances the documentation with a component-based example.
