### ISSUE TITLE
Adding different display name to enum then sent in form data

### ISSUE THREAD

**Issue by dowling-john** [rjsf-team/react-jsonschema-form#4023]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

I need a way to use a enum that displays a human readable option in the select and send a uuid in the form data is this possible ?

**Comment by heath-freenome** [comment]
@dowling-john See the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs/json-schema/single/#custom-labels-for-enum-fields) here

**Comment by dowling-john** [comment]
Perfect just what I was after

Thanks
