### ISSUE TITLE
Show a field by default but then hide it based on a condition

### ISSUE THREAD

**Issue by JalalMiftah** [rjsf-team/react-jsonschema-form#4042]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

Hi,

I have this [form](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJPcmcgVHlwZSI6eyJlbnVtIjpbIkFjYWRlbWljIiwiR292ZXJubWVudCIsIkNvcnBvcmF0ZSJdLCJ0eXBlIjoic3RyaW5nIn0sIkpvYiBUeXBlIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIkNoaWVmIiwiRGlyZWN0b3IiLCJTdHVkZW50IiwiTWFuYWdlciJdfX19LCJ1aVNjaGVtYSI6eyJPcmcgVHlwZSI6eyJ1aTp3aWRnZXQiOiJyYWRpbyJ9LCJKb2IgVHlwZSI6eyJ1aTp3aWRnZXQiOiJyYWRpbyJ9fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJleHBlcmltZW50YWxfZGVmYXVsdEZvcm1TdGF0ZUJlaGF2aW9yIjp7ImFycmF5TWluSXRlbXMiOnsicG9wdWxhdGUiOiJwb3B1bGF0ZSIsIm1lcmdlRXh0cmFEZWZhdWx0cyI6ZmFsc2V9LCJhbGxPZiI6InNraXBEZWZhdWx0cyIsImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyJ9fX0=)

I basically want to display "Job Type" by default but hide it if I select "Academic" in Org Type. Is there a way to achieve that? Thank you.

**Comment by heath-freenome** [comment]
@JalalMiftah You will want to use if-then-else. Here is the official documentation https://json-schema.org/understanding-json-schema/reference/conditionals#ifthenelse

**Comment by JalalMiftah** [comment]
Hi @heath-freenome , thank you for your response!

I have tried to move the "Job Type" to "then" but no luck. When the first is first rendered "Job Typee" is hidden despite the "if" condition not being met.

Here's the [new form](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJPcmcgVHlwZSI6eyJlbnVtIjpbIkFjYWRlbWljIiwiR292ZXJubWVudCIsIkNvcnBvcmF0ZSJdLCJ0eXBlIjoic3RyaW5nIn19LCJpZiI6eyJwcm9wZXJ0aWVzIjp7Ik9yZyBUeXBlIjp7ImNvbnN0IjoiQWNhZGVtaWMifX19LCJ0aGVuIjpmYWxzZSwiZWxzZSI6eyJwcm9wZXJ0aWVzIjp7IkpvYiBUeXBlIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIkNoaWVmIiwiRGlyZWN0b3IiLCJTdHVkZW50IiwiTWFuYWdlciJdfX19fSwidWlTY2hlbWEiOnsiT3JnIFR5cGUiOnsidWk6d2lkZ2V0IjoicmFkaW8ifSwiSm9iIFR5cGUiOnsidWk6d2lkZ2V0IjoicmFkaW8ifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjp7InBvcHVsYXRlIjoicG9wdWxhdGUiLCJtZXJnZUV4dHJhRGVmYXVsdHMiOmZhbHNlfSwiYWxsT2YiOiJza2lwRGVmYXVsdHMiLCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMifX19)

**Comment by JalalMiftah** [comment]
I found a way: https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJPcmcgVHlwZSI6eyJlbnVtIjpbIkFjYWRlbWljIiwiR292ZXJubWVudCIsIkNvcnBvcmF0ZSJdLCJ0eXBlIjoic3RyaW5nIn19LCJpZiI6eyJwcm9wZXJ0aWVzIjp7Ik9yZyBUeXBlIjp7ImNvbnN0IjoiQWNhZGVtaWMifX19LCJ0aGVuIjpmYWxzZSwiZWxzZSI6eyJwcm9wZXJ0aWVzIjp7IkpvYiBUeXBlIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIkNoaWVmIiwiRGlyZWN0b3IiLCJTdHVkZW50IiwiTWFuYWdlciJdfX19fSwidWlTY2hlbWEiOnsiT3JnIFR5cGUiOnsidWk6d2lkZ2V0IjoicmFkaW8ifSwiSm9iIFR5cGUiOnsidWk6d2lkZ2V0IjoicmFkaW8ifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjp7InBvcHVsYXRlIjoicG9wdWxhdGUiLCJtZXJnZUV4dHJhRGVmYXVsdHMiOmZhbHNlfSwiYWxsT2YiOiJza2lwRGVmYXVsdHMiLCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMifX19

Adding "null" as default value and adding a "dependencies" on "null"
