### ISSUE TITLE
Error with $ref: reference resolves to more than one schema

### ISSUE THREAD

**Issue by jag43** [rjsf-team/react-jsonschema-form#4048]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.
  - [x] GitHub repo 

### What theme are you using?

mui

### Version

5.16.1

### Current Behavior

When using JSON pointer $refs I'm getting an error on submission: `reference "locations.json" resolves to more than one schema`

### Expected Behavior

No error, form performs validation as expected

### Steps To Reproduce

https://github.com/jag43/rjsf-resolves-to-more-than-one-schema
1. Install the required packages by running npm install
1. Run the vite dev server with npm run dev
1. Press the form submit button
1. Open dev tools and see the error in console

### Environment

```markdown
- OS: Windows 10 22H2
- Node: v18.18.0
- npm: 9.8.1
```

**Comment by magaton** [comment]
I think you need to declare reference to location.json differently, not using /#defs prefix.

See this [comment](https://github.com/ajv-validator/ajv/issues/1426#issuecomment-774766648) with explanation how ajv works

**Comment by jag43** [comment]
Thanks for your reply, according to the RJSF docs on [Schema definitions and references
](https://rjsf-team.github.io/react-jsonschema-form/docs/json-schema/definitions)

> Note that this library only supports local definition referencing. The value in the $ref keyword should be a [JSON Pointer](https://tools.ietf.org/html/rfc6901) in URI fragment identifier format.

After reading the [json schema docs for `$id`](https://json-schema.org/understanding-json-schema/structuring#dollarid) I noticed it says this:

> When the $id keyword appears in a subschema, it means something slightly different. See the [bundling](https://json-schema.org/understanding-json-schema/structuring#bundling) section for more.

I don't fully understand why but after removing the `$id` from the sub-schema (in `$defs`) it appears to be working now

**Comment by magaton** [comment]
Yes, this is exactly what is explained in the comment I referenced.
Also see this [issue](https://github.com/ajv-validator/ajv/issues/1426)

**Comment by heath-freenome** [comment]
@jag43 Has this issue been resolved? If so, please close

**Comment by jag43** [comment]
Yes I've resolved this thank you for your help
