### ISSUE TITLE
How to get the json path in an InputTemplate?

### ISSUE THREAD

**Issue by Minekonst** [rjsf-team/react-jsonschema-form#4059]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

Hey, I have a (I hope) simple question.
I have made a custom input template but cannot figure out how to get the path in the schema. I am aware that BaseInputTemplateProps have an id field which almost does what I want. The problem with that field is that I have properties in my schema which use underscore for their property names. Therefore I cannot distinguish for an id of "root_a_b" whether it means `{a: {b: "SomeValue"}}` or `{a_b: "SomeValue}`. Is there a way for example to change the default delimiter of the id to something else than underscore or is there another way to achieve that?

**Comment by magaton** [comment]
Yes, you can define idPrefix and idSeparator in Form definition:

  /** To avoid collisions with existing ids in the DOM, it is possible to change the prefix used for ids;
   * Default is `root`
   */
  idPrefix?: string;
  
  /** To avoid using a path separator that is present in field names, it is possible to change the separator used for
   * ids (Default is `_`)
   */
  idSeparator?: string;

**Comment by Minekonst** [comment]
Oh ok, that is way easier than I expected. Thank you very much!
