### ISSUE TITLE
Push an error from a widget

### ISSUE THREAD

**Issue by abemedia** [rjsf-team/react-jsonschema-form#4069]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

bootstrap-4

### What is your question?

I have a custom widget which needs to have its own validation. Is it possible to push an error from a widget to the form's extraErrors for the current field?

The use-case is a widget for an oauth token field which displays a "Connect" button that opens an external provider's oauth flow. If the user does not grant permission the field needs to be marked as invalid and display the error.

**Comment by userAdityaa** [comment]
Hi, I think i can solve this problem. But can you provide me with a code snippet of the custom field.

**Comment by abemedia** [comment]
Thanks! I basically have a widget which wraps a component that can take on `onError` prop which is called whenever there's an error and want to pass this error to RJSF.

```ts
import { WidgetProps } from '@rjsf/utils';
import { OAuthEditor } from '../../OAuthEditor/OAuthEditor';

export function OAuthWidget({ value, onChange, options }: WidgetProps<string>) {
  const onError = (error: Error) => console.error(error); // <- I'd like to pass this error to RJSF.
  return (
    <OAuthEditor
      onChange={onChange}
      onError={onError}
      value={value}
    />
  );
}

**Comment by userAdityaa** [comment]
Actually the ParentComponent passes a handleError function to OAuthWidget via the onError prop. When an error occurs in OAuthWidget, it calls onError, which logs the error to the console and then calls handleError to pass the error up to ParentComponent.

const onError = (error: Error) => {
    console.error(error);
    onError(error);
  };
  
 This might solve your issue. I am not able to recreate your environment so, you can only check this logic. I have done some searches on this problem. Hope it might help.

**Comment by abemedia** [comment]
The issue is that RJSF widgets to my knowledge have no way to push an error to the form. The only way I can think of is a little hacky such as using a react context to sore the error in and using that further up the chain to pass it to the forms extra error.

I was kind of hoping for a native way to push an error into the form though.

**Comment by heath-freenome** [comment]
@abemedia The `FieldProps` supports updating the `errorSchema` in its `onChange()` handler. Have you considered switching your custom widget to be a field instead? That way in your `uiSchema` rather than using `ui:widget` to pick up your custom widget, you would use `ui:field` instead.

**Comment by abemedia** [comment]
@heath-freenome I didn't realise fields have that second parameter on `onChange`. This is exactly what I was looking for!
Thank you very much!
