### ISSUE TITLE
[chakra-ui] ui:options rows not applied for `textarea` element

### ISSUE THREAD

**Issue by ldirer** [rjsf-team/react-jsonschema-form#4070]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

chakra-ui

### Version

5.x

### Current Behavior

Using a `uiSchema` to set the number of rows of a textarea works as expected with many themes, but not with chakra-ui.

Example uiSchema:  
```
{
  "longText": {
    "ui:widget": "textarea",
    "ui:rows": 10
  }
}
```

### Expected Behavior

A textarea with 10 rows is expected when the ui schema specifies it, as in the playground link below.

### Steps To Reproduce

[Playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJsb25nVGV4dCI6Im9uY2UgdXBvbiBhIHRpbWUuLi4ifSwic2NoZW1hIjp7InRpdGxlIjoiQSByZWdpc3RyYXRpb24gZm9ybSIsImRlc2NyaXB0aW9uIjoiQSBzaW1wbGUgZm9ybSBleGFtcGxlLiIsInR5cGUiOiJvYmplY3QiLCJyZXF1aXJlZCI6WyJsb25nVGV4dCJdLCJwcm9wZXJ0aWVzIjp7ImxvbmdUZXh0Ijp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkxvbmcgdGV4dCIsImRlZmF1bHQiOiIifX19LCJ1aVNjaGVtYSI6eyJsb25nVGV4dCI6eyJ1aTp3aWRnZXQiOiJ0ZXh0YXJlYSIsInVpOnJvd3MiOjEwfX0sInRoZW1lIjoiY2hha3JhLXVpIiwibGl2ZVNldHRpbmdzIjp7fX0=)

### Anything else?

Looks like a one line change, I prefer to open an issue first but happy to offer a PR.

**Comment by heath-freenome** [comment]
@ldirer You are correct, the `TextareaWidget` does not, in fact, pluck out the `rows` from the `options` variable being passed in. And we would gladly take a PR that fixes this
