### ISSUE TITLE
If/then/else shows a field despite dependent condition not met

### ISSUE THREAD

**Issue by JalalMiftah** [rjsf-team/react-jsonschema-form#4089]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

Hi, 

I have this form : [Playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJjb3VudHJ5Ijp7ImVudW0iOlsiQ2FuYWRhIiwiVVNBIiwiVUsiXX19LCJhbGxPZiI6W3siaWYiOnsicHJvcGVydGllcyI6eyJjb3VudHJ5Ijp7ImNvbnN0IjoiVVNBIn19LCJyZXF1aXJlZCI6WyJjb3VudHJ5Il19LCJ0aGVuIjp7InByb3BlcnRpZXMiOnsic3RhdGUiOnsiZW51bSI6WyJBbGFiYW1hIiwiQ2FsaWZvcm5pYSIsIlV0YWgiXX19fX0seyJpZiI6eyJwcm9wZXJ0aWVzIjp7InN0YXRlIjp7ImNvbnN0IjoiQWxhYmFtYSJ9fSwicmVxdWlyZWQiOlsic3RhdGUiXX0sInRoZW4iOnsicHJvcGVydGllcyI6eyJBbGFiYW1hIG9yZ3MiOnsidHlwZSI6InN0cmluZyJ9fX19XX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJleHBlcmltZW50YWxfZGVmYXVsdEZvcm1TdGF0ZUJlaGF2aW9yIjp7ImFycmF5TWluSXRlbXMiOnsicG9wdWxhdGUiOiJwb3B1bGF0ZSIsIm1lcmdlRXh0cmFEZWZhdWx0cyI6ZmFsc2V9LCJhbGxPZiI6InBvcHVsYXRlRGVmYXVsdHMiLCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMifX19)

I want to show "state" if "country" is "USA", and if "state" is "Alabama" I want to show another field "Alabama orgs".

That behaves correctly until I switch the "country" to "Canada", the field "Alabama orgs" is still present despite "state" not being there anymore.

Is there an easy way to solve that that doesn't involve combining conditions of "state" inside the condition for "Alabama orgs"? I tried to set a dummy field to "false" in the "then" but I'm not getting the desired output.

Thanks for the help!

**Comment by MarekBodingerBA** [comment]
It's because the data is still there, there are two fixes:
1) Turn on "Omit extra data" and "Live omit".
2) Strengthen the second condition by adding check for whether "country" is "USA" too.

I suggest the latter even if you apply start using data omit.

**Comment by JalalMiftah** [comment]
Thanks for the response Marek, the main issue is that I can have an arbitrary list of conditions (allOf/anyOf) for an arbitrary list of fields. I guess no escaping building my own dependency tree...
