### ISSUE TITLE
Ability to disable $ref resolution

### ISSUE THREAD

**Issue by RPiAwesomeness** [rjsf-team/react-jsonschema-form#4101]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

mui

### What is your question?

We are using RJSF and want the ability to disable ref resolution. Is that available? I haven't been able to find it mentioned in the docs nor in reading over the props/form config.

**Comment by heath-freenome** [comment]
@RPiAwesomeness What are you trying to accomplish? The `$ref` resolution feature is built deep into the code and is essential for how it operates.

**Comment by RPiAwesomeness** [comment]
Basically we were hoping there would be a way to disable the requirement to have all refs resolved and just leave fields with a placeholder of some type. But we've found workarounds in the meantime, given that this isn't an option currently!
