### ISSUE TITLE
`@rjsf/mui` has issues with the dark theme

### ISSUE THREAD

**Issue by markmssd** [rjsf-team/react-jsonschema-form#4118]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

mui

### Version

5.17.1

### Current Behavior

When using `@rjsf/material-ui`, with `light` or `dark` theme, there is also no issues.

When using `@rjsf/mui` with `light` theme, there is no issues. However, when using 

However, when using `@rjsf/mui` with `dark` theme, there is some issues, as shown in the screenshots.

✅ Light theme:
<img width="1182" alt="Screenshot 2024-03-06 at 7 10 43 PM" src="https://github.com/rjsf-team/react-jsonschema-form/assets/5899024/f6f0dce4-d01f-4d61-be16-193e7ab961bf">

❌ Dark theme:
<img width="1179" alt="Screenshot 2024-03-06 at 7 10 50 PM" src="https://github.com/rjsf-team/react-jsonschema-form/assets/5899024/7a03ac7a-cd1b-4961-8f42-135b22243e31">

### Expected Behavior

`@rjsf/mui`  should be compatible with `dark` theme as well. For example, the title/texts should have white colour when using `dark` theme.

### Steps To Reproduce

I have created a minimal reproducible example here: https://github.com/markmssd/rjsf-mui-dark-theme.

Clone and install dependencies:
```
git clone git@github.com:markmssd/rjsf-mui-dark-theme.git
cd rjsf-mui-dark-theme
yarn install
```

Run the app and open `http://localhost:5173/` in your browser:
```
yarn dev
```

Use the theme switcher to switch between `light` and `dark` theme, and you can observe that the dark theme has a few issues (for example dark text on dark background).

### Environment

```markdown
- OS: MacOS
- Node: 20.11.0
- npm: 10.2.4
- yarn: 1.22.21
```

### Anything else?

SSCCE: https://github.com/markmssd/rjsf-mui-dark-theme

**Comment by nickgros** [comment]
We would welcome pull request(s) to fix this. Maybe it would be as simple as using the `theme.palette.text.primary` where the style is misapplied

**Comment by nickgros** [comment]
@markmssd are you willing to make this change? We would be happy to review

**Comment by markmssd** [comment]
@nickgros I've tried to reproduce it in the Playground so I can fix it, however I can't there 🤔 Here's the change I did to get the dark theme: https://github.com/markmssd/react-jsonschema-form/blob/main/packages/playground/src/components/DemoFrame.tsx#L100-L108.

However in the Playground, the title and the checkbox are rendering without issues:

<img width="674" alt="Screenshot 2024-03-08 at 8 43 41 PM" src="https://github.com/rjsf-team/react-jsonschema-form/assets/5899024/f8cfd5dd-4d43-4419-94cb-7323ddd20d69">

I wonder if I'm doing something wrong in my repro repo when I'm using it: https://github.com/markmssd/rjsf-mui-dark-theme/blob/main/src/SchemaForm.tsx? 🤔

**Comment by markmssd** [comment]
For some reason, having an outer wrapper on the RJSF Mui form fixes the issue. It seems to be an MUI thing, because I found this solution in another project unrelated to RJSF. I guess we can close this issue then, thanks @nickgros !

```
<Paper elevation={0}>
  <RJSFForm {...props} />
</Paper>
```
