### ISSUE TITLE
Filenames have an ugly "</strong>" printed next to them.

### ISSUE THREAD

**Issue by joachimhagheim** [rjsf-team/react-jsonschema-form#4120]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

Any

### Version

5.17.1

### Current Behavior

List of files that have been uploaded contains extra "\</strong>" element. Presumably there is either never a starting "\<strong>" or the "\<strong>" just ends immediately, leaving one extra. The text for the filename is also not bold, it is probably supposed to be bold. Theme does not seem to matter.
![image](https://github.com/rjsf-team/react-jsonschema-form/assets/47362824/17f2c699-2b2f-4b2e-b925-59192dc3ce73)

### Expected Behavior

I expect it not to look terrible.

### Steps To Reproduce

Literally just add this at the bottom of the "simple" playground project, underneath "telephone":

`,
    "attachments": {
      "type": "array",
      "title": "Attachments",
      "items": {
        "type": "string",
        "format": "data-url"
      }
    }
`
Again the theme does not seem to matter, all the ones i've tried have been broken. Well, the functionality works, it just looks terrible. 

### Environment

```markdown
Your playground. My project. And presumably anywhere else.
```

**Comment by heath-freenome** [comment]
@joachimhagheim Given that we are a small group of volunteers, we really can't fix everything little thing. Are you willing to debug and fix this? The `FileInfo` widget is using the `translateString()` implementation with markdown... If you want to fix this easily (hopefully), in the `@rjsf/utils` package and find the [enum.ts](https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/utils/src/enums.ts#L73) and change `<strong>` and `</strong>` to the associated markdown (`**`) I believe this should fix it.

**Comment by joachimhagheim** [comment]
@heath-freenome Your suggested fix seems to work for me locally.

**Comment by heath-freenome** [comment]
@joachimhagheim can you provide a PR with the fix for everyone?
