### ISSUE TITLE
How can I cite this?

### ISSUE THREAD

**Issue by sdmiller93** [rjsf-team/react-jsonschema-form#4149]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

I am creating a figure showing our JSON schema and its ability to create forms and instances and we have been using your tool (https://rjsf-team.github.io/react-jsonschema-form/) to validate. We wanted to use a screen capture and cite it. Can you provide a proper reference to use?

**Comment by nickgros** [comment]
I looked into it and a maintainer does need to create the repo, but first an owner needs to permit sharing repo information with Zenodo.

@epicfaace can you help with this?

**Comment by epicfaace** [comment]
I just approved the Zenodo request!

**Comment by sdmiller93** [comment]
Thank you!






-----------

Sierra D. Miller

Bioinformaticist | https://www.nist.gov/people/sierra-miller
Genome Editing Program<https://www.nist.gov/programs-projects/nist-genome-editing-program> | Biomarker & Genomic Sciences Group<https://www.nist.gov/mml/bbd/bioassay-methods>
Material Measurement Laboratory<https://www.nist.gov/mml> | Division 644.04<https://www.nist.gov/mml/bbd>
U.S. National Institute of Standards & Technology<https://www.nist.gov/>


Upcoming Out of Office Dates:
Friday, June 7th
Tentative: ~July 22-26



From: Ashwin Ramaswami ***@***.***>
Date: Friday, April 5, 2024 at 10:51 PM
To: rjsf-team/react-jsonschema-form ***@***.***>
Cc: Miller, Sierra D. (Fed) ***@***.***>, Mention ***@***.***>
Subject: Re: [rjsf-team/react-jsonschema-form] How can I cite this? (Issue #4149)

I just approved the Zenodo request!

**Comment by nickgros** [comment]
@epicfaace Thank you! I see that the integration is now approved for the organization, but I still cannot see the repo in Zenodo even after refreshing the list. Per the [Zenodo FAQ](https://help.zenodo.org/faq/), "In order to see and archive your organizational repositories on Zenodo you will need to have "Admin" permissions on said repository", so I cannot add it. 

Could you follow the [GitHub docs steps](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content) to add the repo to Zenodo?

**Comment by epicfaace** [comment]
It should be added now! 
<img width="569" alt="image" src="https://github.com/rjsf-team/react-jsonschema-form/assets/1689183/fbd2ee61-225b-437f-b107-ae01e388baa7">

**Comment by nickgros** [comment]
I see our releases being published [here](https://zenodo.org/records/12667165), so I am going to close this issue. @sdmiller93 please feel free to open a new issue.
