### ISSUE TITLE
Publish v6 release candidate with support for Bootstrap 5

### ISSUE THREAD

**Issue by davidebriani** [rjsf-team/react-jsonschema-form#4162]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

bootstrap-4

### What is your question?

It seems a good amount of work has been done to support react-boostrap, including Bootstrap 5: #3974.
The tracking issue #3638 also reports the task as done. 
However that is not yet published as an NPM package that can be used by projects.
Is it possible to publish a v6 pre-release so that RJSF can be tried and tested with Bootstrap 5? Or is there an estimate for when it will be published?

I manually tried the v6 branch on [a real-world project](https://github.com/astarte-platform/astarte-dashboard) and it seems to be working fine. We would love to migrate the project to Bootstrap 5 soon, and eventually polish the small imperfections along the way.

**Comment by nickgros** [comment]
I'll see if I can set up a prerelease in the next few weeks. We have other plans for v6 that are far away, so I don't think we are close to a non-beta/rc version.

**Comment by wilson777** [comment]
@nickgros did this pre-release get released? if so, please provide NPM link, if not, could you please update on status of v6 and/or a pre-release version? thanks! :)

**Comment by nickgros** [comment]
@wilson777 Thanks for the reminder. Sorry, life got in the way. I just published v6.0.0-alpha.0 to npm. We still have quite a few housekeeping items we want to take care of in v6, so no ETA on a full release yet. Please feel free to create new issues if there are problems with the prerelease.
