### ISSUE TITLE
Empty item in selectbox for enum is not visible

### ISSUE THREAD

**Issue by Vity01** [rjsf-team/react-jsonschema-form#4197]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

material-ui

### Version

5.x

### Current Behavior

Although the enum property in the model is nullable and not required, empty value for selection is missing.

Nowadays there is no easy way for user to deselect already selected value. We use 'blank space' as an empty item and it's barely visible and also it's not a perfect engineering solution.

It's working for other than Material-UI 
eg: working combobox: 
In  [RJSF demo](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCIsInRlbGVwaG9uZSI6IjEtODAwLUtJQ0tBU1MifSwic2NoZW1hIjp7InRpdGxlIjoiQSByZWdpc3RyYXRpb24gZm9ybSIsImRlc2NyaXB0aW9uIjoiQSBzaW1wbGUgZm9ybSBleGFtcGxlLiIsInR5cGUiOiJvYmplY3QiLCJyZXF1aXJlZCI6WyJmaXJzdE5hbWUiLCJsYXN0TmFtZSJdLCJwcm9wZXJ0aWVzIjp7ImN0b1RlYW0iOnsidWk6ZW1wdHlWYWx1ZSI6IiIsIm51bGxhYmxlIjp0cnVlLCJhbGxvd0VtcHR5VmFsdWUiOnRydWUsImVudW0iOlsic2hhcmVkIiwiZWdhIiwiaW5mcmEiLCJoaXBwbyIsImNicyIsInRscCIsInRpcyIsInRpIl19LCJhcmVhIjp7InVpOmVtcHR5VmFsdWUiOiIiLCJudWxsYWJsZSI6dHJ1ZSwidHlwZSI6InN0cmluZyIsImVudW0iOlsibHVmdCIsImJyb3dzZXIiLCJidXNpbmVzcy1pbnRlbGxpZ2VuY2UiLCJidXJnZXIiLCJkYXRhLWdvdmVybmFuY2UiLCJzZWN1cml0eSIsImNzaXMiLCJjdG8iLCJpZGVudGl0eSIsImVkZ2UtZGMiLCJqdW1wc2hvdCIsImNjbGVhbmVyIiwiY3VzdG9tZXItZGF0YS1wbGF0Zm9ybSIsImV4cGVyaW1lbnRhdGlvbi1wbGF0Zm9ybSIsInNtYiIsIm90aGVyIl19LCJsYXN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJMYXN0IG5hbWUifSwiYWdlIjp7InR5cGUiOiJpbnRlZ2VyIiwidGl0bGUiOiJBZ2UifSwiYmlvIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkJpbyJ9LCJwYXNzd29yZCI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJQYXNzd29yZCIsIm1pbkxlbmd0aCI6M30sInRlbGVwaG9uZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJUZWxlcGhvbmUiLCJtaW5MZW5ndGgiOjEwfX19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIiwidWk6cGxhY2Vob2xkZXIiOiJ1aTplbXB0eVZhbHVlIGNhdXNlcyB0aGlzIGZpZWxkIHRvIGFsd2F5cyBiZSB2YWxpZCBkZXNwaXRlIGJlaW5nIHJlcXVpcmVkIiwidWk6YXV0b2NvbXBsZXRlIjoiZmFtaWx5LW5hbWUiLCJ1aTplbmFibGVNYXJrZG93bkluRGVzY3JpcHRpb24iOnRydWUsInVpOmRlc2NyaXB0aW9uIjoiTWFrZSB0ZXh0ICoqYm9sZCoqIG9yICppdGFsaWMqLiBUYWtlIGEgbG9vayBhdCBvdGhlciBvcHRpb25zIFtoZXJlXShodHRwczovL21hcmtkb3duLXRvLWpzeC5xdWFudGl6b3IuZGV2LykuIn0sImxhc3ROYW1lIjp7InVpOmF1dG9jb21wbGV0ZSI6ImdpdmVuLW5hbWUiLCJ1aTplbmFibGVNYXJrZG93bkluRGVzY3JpcHRpb24iOnRydWUsInVpOmRlc2NyaXB0aW9uIjoiTWFrZSB0aGluZ3MgKipib2xkKiogb3IgKml0YWxpYyouIEVtYmVkIHNuaXBwZXRzIG9mIGBjb2RlYC4gPHNtYWxsPkFuZCB0aGlzIGlzIGEgc21hbGwgdGV4dHMuPC9zbWFsbD4gIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aCB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsIm5vSHRtbDVWYWxpZGF0ZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZSwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjoicG9wdWxhdGUiLCJhbGxPZiI6InNraXBEZWZhdWx0cyIsImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyJ9fX0=)

For default theme, you can see an empty available item
![image](https://github.com/rjsf-team/react-jsonschema-form/assets/2512959/28f6f11a-2944-4436-9bf8-18f0b180ac2b)

Not not for the MaterialUI:
![image](https://github.com/rjsf-team/react-jsonschema-form/assets/2512959/51b5ec4e-db69-4da3-9408-e8d8e2e75c26)
[RJSF DEMO - bug](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCIsInRlbGVwaG9uZSI6IjEtODAwLUtJQ0tBU1MifSwic2NoZW1hIjp7InRpdGxlIjoiQSByZWdpc3RyYXRpb24gZm9ybSIsImRlc2NyaXB0aW9uIjoiQSBzaW1wbGUgZm9ybSBleGFtcGxlLiIsInR5cGUiOiJvYmplY3QiLCJyZXF1aXJlZCI6WyJmaXJzdE5hbWUiLCJsYXN0TmFtZSJdLCJwcm9wZXJ0aWVzIjp7ImN0b1RlYW0iOnsidWk6ZW1wdHlWYWx1ZSI6IiIsIm51bGxhYmxlIjp0cnVlLCJhbGxvd0VtcHR5VmFsdWUiOnRydWUsImVudW0iOlsic2hhcmVkIiwiZWdhIiwiaW5mcmEiLCJoaXBwbyIsImNicyIsInRscCIsInRpcyIsInRpIl19LCJhcmVhIjp7InVpOmVtcHR5VmFsdWUiOiIiLCJudWxsYWJsZSI6dHJ1ZSwidHlwZSI6InN0cmluZyIsImVudW0iOlsibHVmdCIsImJyb3dzZXIiLCJidXNpbmVzcy1pbnRlbGxpZ2VuY2UiLCJidXJnZXIiLCJkYXRhLWdvdmVybmFuY2UiLCJzZWN1cml0eSIsImNzaXMiLCJjdG8iLCJpZGVudGl0eSIsImVkZ2UtZGMiLCJqdW1wc2hvdCIsImNjbGVhbmVyIiwiY3VzdG9tZXItZGF0YS1wbGF0Zm9ybSIsImV4cGVyaW1lbnRhdGlvbi1wbGF0Zm9ybSIsInNtYiIsIm90aGVyIl19LCJsYXN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJMYXN0IG5hbWUifSwiYWdlIjp7InR5cGUiOiJpbnRlZ2VyIiwidGl0bGUiOiJBZ2UifSwiYmlvIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkJpbyJ9LCJwYXNzd29yZCI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJQYXNzd29yZCIsIm1pbkxlbmd0aCI6M30sInRlbGVwaG9uZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJUZWxlcGhvbmUiLCJtaW5MZW5ndGgiOjEwfX19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIiwidWk6cGxhY2Vob2xkZXIiOiJ1aTplbXB0eVZhbHVlIGNhdXNlcyB0aGlzIGZpZWxkIHRvIGFsd2F5cyBiZSB2YWxpZCBkZXNwaXRlIGJlaW5nIHJlcXVpcmVkIiwidWk6YXV0b2NvbXBsZXRlIjoiZmFtaWx5LW5hbWUiLCJ1aTplbmFibGVNYXJrZG93bkluRGVzY3JpcHRpb24iOnRydWUsInVpOmRlc2NyaXB0aW9uIjoiTWFrZSB0ZXh0ICoqYm9sZCoqIG9yICppdGFsaWMqLiBUYWtlIGEgbG9vayBhdCBvdGhlciBvcHRpb25zIFtoZXJlXShodHRwczovL21hcmtkb3duLXRvLWpzeC5xdWFudGl6b3IuZGV2LykuIn0sImxhc3ROYW1lIjp7InVpOmF1dG9jb21wbGV0ZSI6ImdpdmVuLW5hbWUiLCJ1aTplbmFibGVNYXJrZG93bkluRGVzY3JpcHRpb24iOnRydWUsInVpOmRlc2NyaXB0aW9uIjoiTWFrZSB0aGluZ3MgKipib2xkKiogb3IgKml0YWxpYyouIEVtYmVkIHNuaXBwZXRzIG9mIGBjb2RlYC4gPHNtYWxsPkFuZCB0aGlzIGlzIGEgc21hbGwgdGV4dHMuPC9zbWFsbD4gIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aCB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sInRoZW1lIjoibWF0ZXJpYWwtdWktNSIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsIm5vSHRtbDVWYWxpZGF0ZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZSwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjoicG9wdWxhdGUiLCJhbGxPZiI6InNraXBEZWZhdWx0cyIsImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyJ9fX0=)

### Expected Behavior

Empty item should available also for MaterialUI

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by kevinmichaelchen** [comment]
It would be great if deselection and nullable enums were supported.
