### ISSUE TITLE
File Upload "No file chosen" issue

### ISSUE THREAD

**Issue by SwapnilWankhedeMerit98** [rjsf-team/react-jsonschema-form#4205]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

<img width="443" alt="Capture2" src="https://github.com/rjsf-team/react-jsonschema-form/assets/170604413/e67023b5-4ba1-4a59-bb54-65cef34ac2d4">

Why even if file is selected, it shows that text No file chosen. Isn't there any fix to hide or remove that?

**Comment by nickgros** [comment]
As a workaround, you may be able to accomplish this with your own widget override + CSS: https://stackoverflow.com/a/17949302

We'd definitely consider a pull request that fixes this!

**Comment by SwapnilWankhedeMerit98** [comment]
Okay. Sure. Thank you.

**Comment by SwapnilWankhedeMerit98** [comment]
Closing this as I have got the clarity
