### ISSUE TITLE
`pathSchema` prop in templates

### ISSUE THREAD

**Issue by jroebu14** [rjsf-team/react-jsonschema-form#4217]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### Is your feature request related to a problem? Please describe.

Is it possible to get the current `pathSchema` in templates similar to how you get the current `idSchema`?

For example, in a template, if the `idSchema` prop is `"root_x_y_z"` then the `pathSchema` prop would be `"x.y.z"`.

### Describe the solution you'd like

I'd like `pathSchema` as a prop provided to all template components.

**Comment by heath-freenome** [comment]
@jroebu14 using the idSchema, you can extract the path fairly simply by setting the [idSeparator](https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/form-props/#idseparator) prop on the `Form` to be `.` and then slicing out the `root.`

**Comment by jroebu14** [comment]
> @jroebu14 using the idSchema, you can extract the path fairly simply by setting the [idSeparator](https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/form-props/#idseparator) prop on the Form to be . and then slicing out the root.

@heath-freenome this is a good solution. I'll go with this. Thanks very much!
