### ISSUE TITLE
Regression: readOnly not working in 5.18.5

### ISSUE THREAD

**Issue by rap1ds** [rjsf-team/react-jsonschema-form#4236]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.18.5

### Current Behavior

Boolean fields with `readOnly: true` are enabled, i.e. user is able to click the checkbox

### Expected Behavior

Boolean fields with `readOnly: true` should be disabled, i.e. user should not be able to click the checkbox

### Steps To Reproduce

1. Open [this Playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmb28iOnRydWUsImJhciI6ZmFsc2V9LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZm9vIjp7InR5cGUiOiJib29sZWFuIiwicmVhZE9ubHkiOnRydWV9LCJiYXIiOnsidHlwZSI6ImJvb2xlYW4ifX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjp7InBvcHVsYXRlIjoicG9wdWxhdGUiLCJtZXJnZUV4dHJhRGVmYXVsdHMiOmZhbHNlfSwiYWxsT2YiOiJza2lwRGVmYXVsdHMiLCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMifSwicmVhZG9ubHkiOmZhbHNlfX0=)
2. Click the "foo" checkbox

Expected: Checkbox can't be clicked

Actual: Checkbox can be clicked. The data value changes.

### Environment

```markdown
This seems to be regression bug.

I noticed this bug when I upgraded RJSF from 5.6.2 -> 5.18.5.

Then I did a bit more bisecting and noticed that 5.18.4 works fine.

So the issue occurs when upgrading from 5.18.4 -> 5.18.5. Maybe [this PR](https://github.com/rjsf-team/react-jsonschema-form/pull/4212)?
```

**Comment by rap1ds** [comment]
That was a fast fix! Thank you! 🙏🍬

**Comment by rap1ds** [comment]
It looks like this issue isn't fixed in 5.18.6, even though the CHANGELOG says it should be fixed in that version.

I upgraded from 5.18.4 -> 5.18.6 and noticed that the regression bug was still there.

I checked from [NPM the code](https://www.npmjs.com/package/@rjsf/core/v/5.18.6?activeTab=code) of `SchemaField.tsx` of the newest 5.18.6 version and saw that it did not contain the fix. Maybe there was an error in the NPM release?

**Comment by nickgros** [comment]
Sorry about that @rap1ds ... it looks like the tag was applied to the wrong commit: https://github.com/rjsf-team/react-jsonschema-form/blob/v5.18.6/packages/core/src/components/fields/SchemaField.tsx

@heath-freenome Let's push another release (either 5.18.7 or 5.19.0) soon so we can properly publish this fix

**Comment by rap1ds** [comment]
No worries! Thanks for a fast fix!
