### ISSUE TITLE
XSS when rendering `uiSchema` validation error message

### ISSUE THREAD

**Issue by davidli16** [rjsf-team/react-jsonschema-form#4254]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

HTML tags inside JSON schema property names are output as HTML when rendered in error messages.

### Expected Behavior

HTML tags are disallowed or escaped when rendering JSON property names in error messages.

### Steps To Reproduce

1. Define a JSON schema

```
{
    "type": "object",
    "properties": {
        "xss<iframe srcdoc={'<script>alert(document.domain)</script>'}>": {
            "type": "string",
            "title": "Comment<a>link</a>"
        }
    },
}
``` 

2. Define a UI schema

```
{
  "xss": {
    "ui:widget": "textarea"
  },
  "ui:order": [
    "test"
  ]
}
```

3. The root schema is included in the error message and rendered as HTML.

### Anything else?

**Solution:** Pass in `disableParsingRawHTML` to the `<Markdown>` component to prevent HTML from being rendered in the error message. https://github.com/rjsf-team/react-jsonschema-form/blob/7f54d45cafeb50864ffb5002f8f924860cb78942/packages/core/src/components/fields/ObjectField.tsx#L267

[Playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCIsInRlbGVwaG9uZSI6IjEtODAwLUtJQ0tBU1MifSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InhzczxpZnJhbWUgc3JjZG9jPXsnPHNjcmlwdD5hbGVydChkb2N1bWVudC5kb21haW4pPC9zY3JpcHQ+J30+Ijp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkNvbW1lbnQ8YT5saW5rPC9hPiJ9fSwidW5ldmFsdWF0ZWRQcm9wZXJ0aWVzIjpmYWxzZX0sInVpU2NoZW1hIjp7InhzcyI6eyJ1aTp3aWRnZXQiOiJ0ZXh0YXJlYSJ9LCJ1aTpvcmRlciI6WyJ0ZXN0Il19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsInZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZWQiOmZhbHNlLCJub0h0bWw1VmFsaWRhdGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2UsImV4cGVyaW1lbnRhbF9kZWZhdWx0Rm9ybVN0YXRlQmVoYXZpb3IiOnsiYXJyYXlNaW5JdGVtcyI6InBvcHVsYXRlIiwiYWxsT2YiOiJza2lwRGVmYXVsdHMiLCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMifX19)

**Comment by heath-freenome** [comment]
@davidli16 Thanks for the issue and the fix. One small update to the PR and we will merge and close this issue.
