### ISSUE TITLE
Support MUI v6

### ISSUE THREAD

**Issue by glebcha** [rjsf-team/react-jsonschema-form#4283]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

mui

### What is your question?

[MUI team released v6](https://mui.com/blog/material-ui-v6-is-out/) with some breaking changes that potentially require review.
Basic scenario will require an update of peer dependencies with the latest MUI v6 packages.

Workaround for npm is to override peer dependencies in package.json:

```
"overrides": {
    "@rjsf/mui": {
      "@mui/material": "^6.0.1",
      "@mui/icons-material": "^6.0.1"
    }
  }
```

**Comment by heath-freenome** [comment]
@glebcha Since my company will be upgrading to Mui v6 I will likely be adding that theme here as well since we use `@rjsf`

**Comment by pnaik07** [comment]
Currently, we use MUIv5. We are planning upgrade the entire UI for v6. Most of our code is v6 compatible. However, If we install @mui v6, rjsf is breaking. Is there a better fix to this?

**Comment by heath-freenome** [comment]
> Currently, we use MUIv5. We are planning upgrade the entire UI for v6. Most of our code is v6 compatible. However, If we install @mui v6, rjsf is breaking. Is there a better fix to this?

How is exactly is it breaking?

**Comment by heath-freenome** [comment]
@pnaik07 Also, with the release of `5.21.0` we've added support for MUI v6, please try it out
