### ISSUE TITLE
Is it possible to replace theme's buttons entirely?

### ISSUE THREAD

**Issue by CarlosAmaral** [rjsf-team/react-jsonschema-form#4288]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

bootstrap-4

### What is your question?

Hi, as the example below, we have a + button in some cases that's produced by the UI library react-jsonschema is using. Is it possible to completely override this component?

![Screenshot 2024-09-02 at 3 02 15 PM](https://github.com/user-attachments/assets/441bb385-4ea3-41a0-892b-0b63573090d2)

**Comment by nickgros** [comment]
@CarlosAmaral have you tried to override the `ButtonTemplates` ([docs link](https://rjsf-team.github.io/react-jsonschema-form/docs/advanced-customization/custom-templates/#buttontemplates))? I think the particular button in your screenshot is the `AddButton`.

**Comment by CarlosAmaral** [comment]
@nickgros awesome, thank you! I was unaware of this spec.
