### ISSUE TITLE
Validation behavior with dependent fields

### ISSUE THREAD

**Issue by BlackBerryID** [rjsf-team/react-jsonschema-form#4311]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.21.1

### Current Behavior

onSubmit: validate all fields
onChange: dependent fields aren't validated (as a result these fields loose error state)

### Expected Behavior

onChange doesn't make dependent fields with errors loose thier error state if they haven't been changed

### Steps To Reproduce

1. Open example: https://playcode.io/2018348
2. Choose **yes** in "showSecondBlock" field
3. Click on submit button (secondBlock's fileds got errors)
4. Go to "name" field of firstBlock object
5. Type some text (secondBlock's fields loose thier errors)

**Comment by nickgros** [comment]
@BlackBerryID I don't see the same issue in [this equivalent playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdEJsb2NrIjp7fSwic2Vjb25kQmxvY2siOnt9LCJzaG93U2Vjb25kQmxvY2siOiJZZXMifSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJyZXF1aXJlZCI6WyJzaG93U2Vjb25kQmxvY2siXSwicHJvcGVydGllcyI6eyJzaG93U2Vjb25kQmxvY2siOnsidHlwZSI6InN0cmluZyIsIm9uZU9mIjpbeyJjb25zdCI6IlllcyJ9LHsiY29uc3QiOiJObyJ9XX0sImZpcnN0QmxvY2siOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvaW5mbyJ9fSwiZGVmaW5pdGlvbnMiOnsiaW5mbyI6eyJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsibmFtZSIsInN1cm5hbWUiXSwicHJvcGVydGllcyI6eyJuYW1lIjp7InR5cGUiOiJzdHJpbmcifSwic3VybmFtZSI6eyJ0eXBlIjoic3RyaW5nIn19fX0sImRlcGVuZGVuY2llcyI6eyJzaG93U2Vjb25kQmxvY2siOnsiaWYiOnsicHJvcGVydGllcyI6eyJzaG93U2Vjb25kQmxvY2siOnsiY29uc3QiOiJZZXMifX19LCJ0aGVuIjp7InByb3BlcnRpZXMiOnsic2Vjb25kQmxvY2siOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvaW5mbyJ9fX19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJtdWkiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsImV4cGVyaW1lbnRhbF9kZWZhdWx0Rm9ybVN0YXRlQmVoYXZpb3IiOnsiYXJyYXlNaW5JdGVtcyI6eyJwb3B1bGF0ZSI6InBvcHVsYXRlIiwibWVyZ2VFeHRyYURlZmF1bHRzIjpmYWxzZX0sImFsbE9mIjoic2tpcERlZmF1bHRzIiwiZW1wdHlPYmplY3RGaWVsZHMiOiJwb3B1bGF0ZUFsbERlZmF1bHRzIn0sImxpdmVWYWxpZGF0ZSI6dHJ1ZSwibm9IdG1sNVZhbGlkYXRlIjp0cnVlfX0=)

Does the issue still happen if you treat the `Form` component as fully controlled? i.e. store `formData` in a `useState` and update it using the `onChange` prop

**Comment by BlackBerryID** [comment]
@nickgros The problem was in rjsf version 5.15.0. In onChange callback old value of **retrievedSchema** was passed to **this.validate** (instead of new one in **_retrievedSchema** variable).
![image](https://github.com/user-attachments/assets/5b533796-8e34-43d9-9168-d118b0511692)


Solution: I bumped rjsf version to 5.21.1 and everything works fine.

P.S. I found unused variable and created PR (https://github.com/rjsf-team/react-jsonschema-form/pull/4320)
