### ISSUE TITLE
Array defaults don't work at the root of the schema.

### ISSUE THREAD

**Issue by abdalla-rko** [rjsf-team/react-jsonschema-form#4335]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.21.2

### Current Behavior

Array defaults don't work at the root of the schema.

### Expected Behavior

Array defaults should work at the root of the schema and not only when it's nested.

### Steps To Reproduce

1. Click [here ](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6W10sInNjaGVtYSI6eyJ0eXBlIjoiYXJyYXkiLCJtaW5JdGVtcyI6NCwiZGVmYXVsdCI6WyJSYXBoYWVsIiwiTWljaGFlbGFuZ2VsbyJdLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6IlVua25vd24ifX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGVkIjpmYWxzZSwibm9IdG1sNVZhbGlkYXRlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlLCJleHBlcmltZW50YWxfZGVmYXVsdEZvcm1TdGF0ZUJlaGF2aW9yIjp7ImFycmF5TWluSXRlbXMiOnsiMCI6InAiLCIxIjoibyIsIjIiOiJwIiwiMyI6InUiLCI0IjoibCIsIjUiOiJhIiwiNiI6InQiLCI3IjoiZSIsInBvcHVsYXRlIjoicG9wdWxhdGUiLCJtZXJnZUV4dHJhRGVmYXVsdHMiOmZhbHNlfSwiYWxsT2YiOiJza2lwRGVmYXVsdHMiLCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMiLCJtZXJnZURlZmF1bHRzSW50b0Zvcm1EYXRhIjoidXNlRm9ybURhdGFJZlByZXNlbnQifSwibGl2ZVZhbGlkYXRlIjp0cnVlfX0=)open the demo with array at the root of the schema
2. You'll notice that defaults are not applied.
3. Click [here ](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0dXJ0bGVzIjpbIlJhcGhhZWwiLCJNaWNoYWVsYW5nZWxvIiwiVW5rbm93biIsIlVua25vd24iXX0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0dXJ0bGVzIjp7InR5cGUiOiJhcnJheSIsIm1pbkl0ZW1zIjo0LCJkZWZhdWx0IjpbIlJhcGhhZWwiLCJNaWNoYWVsYW5nZWxvIl0sIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoiVW5rbm93biJ9fX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsIm5vSHRtbDVWYWxpZGF0ZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZSwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjp7IjAiOiJwIiwiMSI6Im8iLCIyIjoicCIsIjMiOiJ1IiwiNCI6ImwiLCI1IjoiYSIsIjYiOiJ0IiwiNyI6ImUiLCJwb3B1bGF0ZSI6ImFsbCIsIm1lcmdlRXh0cmFEZWZhdWx0cyI6ZmFsc2V9LCJhbGxPZiI6InBvcHVsYXRlRGVmYXVsdHMiLCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMifSwiZm9jdXNPbkZpcnN0RXJyb3IiOmZhbHNlfX0=)to open the demo with nested array.
4. You'll notice that defaults are applied when the array is nested and not at the root of the schema.

### Environment

```markdown
- OS: macOS
- Node: 22.1.0
- npm: 10.7.0
```

**Comment by heath-freenome** [comment]
@abdalla-rko Another interesting bug with our defaulting code. Are you able to fix this for us?

**Comment by abdalla-rko** [comment]
This is not an issue. It was not applying the defaults because the `formData` has an empty array and the array `mergeExtraDefaults` was not enabled. But there is an issue when you enable the `mergeExtraDefaults` and you have `formData` as an empty array, the `default` on the root of the array schema doesn't get applied and only applies the `default` from the `items` property (see [demo](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6W10sInNjaGVtYSI6eyJ0eXBlIjoiYXJyYXkiLCJtaW5JdGVtcyI6NCwiZGVmYXVsdCI6WyJSYXBoYWVsIiwiTWljaGFlbGFuZ2VsbyJdLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6IlVua25vd24ifX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGVkIjpmYWxzZSwibm9IdG1sNVZhbGlkYXRlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlLCJleHBlcmltZW50YWxfZGVmYXVsdEZvcm1TdGF0ZUJlaGF2aW9yIjp7ImFycmF5TWluSXRlbXMiOnsiMCI6InAiLCIxIjoibyIsIjIiOiJwIiwiMyI6InUiLCI0IjoibCIsIjUiOiJhIiwiNiI6InQiLCI3IjoiZSIsInBvcHVsYXRlIjoicG9wdWxhdGUiLCJtZXJnZUV4dHJhRGVmYXVsdHMiOnRydWV9LCJhbGxPZiI6InNraXBEZWZhdWx0cyIsImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyIsIm1lcmdlRGVmYXVsdHNJbnRvRm9ybURhdGEiOiJ1c2VGb3JtRGF0YUlmUHJlc2VudCJ9LCJsaXZlVmFsaWRhdGUiOnRydWV9fQ==)). If `formData` is undefined or null, it will apply the `default` from the root schema and `items.default` and the root `default` will take precedence over item `default`.
