### ISSUE TITLE
Validation regression starting from version 5.20.0+

### ISSUE THREAD

**Issue by AlimovSV** [rjsf-team/react-jsonschema-form#4343]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.21.2

### Current Behavior

If `formData` changes externally and `liveValidate` is true, errors are not re-validated based on the new formData. Version 5.19.4 works fine. This issue causes a problem in the scenario where the data is stored in an external storage and the schema has widgets that open dialogs that change the data using redux actions. In this case, the user sees the field filled in, but in an invalid state.

### Expected Behavior

Errors should be actual against form data

### Steps To Reproduce

- Open [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsiZmlyc3ROYW1lIl0sInByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkZpcnN0IG5hbWUifX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsIm5vSHRtbDVWYWxpZGF0ZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0Ijp0cnVlLCJleHBlcmltZW50YWxfZGVmYXVsdEZvcm1TdGF0ZUJlaGF2aW9yIjp7ImFycmF5TWluSXRlbXMiOiJwb3B1bGF0ZSIsImFsbE9mIjoic2tpcERlZmF1bHRzIiwiZW1wdHlPYmplY3RGaWVsZHMiOiJwb3B1bGF0ZUFsbERlZmF1bHRzIiwibWVyZ2VEZWZhdWx0c0ludG9Gb3JtRGF0YSI6InVzZUZvcm1EYXRhSWZQcmVzZW50In0sImxpdmVWYWxpZGF0ZSI6dHJ1ZX19). You will see one field with required error (because formData.firstName is empty).
- Paste the form data:
```json
{
  "firstName": "123"
}
```
- You will see that First name field will contains the `123` but the field still invalid.

<img width="800" src="https://github.com/user-attachments/assets/f83f3d70-0791-4919-ac3a-23ef2b21dda9" />

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by AlimovSV** [comment]
Looks like the problem is caused by [commit](https://github.com/rjsf-team/react-jsonschema-form/commit/4d3094c54cb70ff96a5d6a8b49114d7a9814d972#diff-704dadefdc8b52ac02d6712540e5734214e9699c66d1d673ded1c57e96df9303L424-R435)

**Comment by heath-freenome** [comment]
@abdalla-rko It looks like a commit of your is causing a regression. Can you look at it?
