### ISSUE TITLE
Consider reverting "Make fields with const pre-fiiled and readonly"

### ISSUE THREAD

**Issue by MarekBodingerBA** [rjsf-team/react-jsonschema-form#4344]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.22.0

### Current Behavior

The recent implementation of prefilled, readonly fields for const values, introduced by https://github.com/rjsf-team/react-jsonschema-form/pull/4326, has led to a regression impacting various use cases.

In my opinion, this change is a regression as it alters expected behaviors in forms where user interaction is required. There are legitimate scenarios where fields with const values should not be readonly, such as (see playground):
 - confirmation fields where users must manually enter a specific text,
 - agree to terms by interacting with a checkbox.
 
Attempting to override the prefilled value with `default` does not work as expected, further complicating form configuration. The implementation should not automatically control whether a field is readonly. Flexibility should be provided to developers to define this behavior based on the specific use case.

### Expected Behavior

Developers should have the option to configure whether a const field is prefilled and readonly or requires user input.

### Steps To Reproduce

1. Open the [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJib29sZWFuQWdyZWVtZW50Ijp0cnVlLCJzdHJpbmdDb25maXJtYXRpb24iOiJyZWFjdC1qc29uLXNjaGVtYS1mb3JtIn0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsiYm9vbGVhbkFncmVlbWVudCIsInN0cmluZ0NvbmZpcm1hdGlvbiJdLCJwcm9wZXJ0aWVzIjp7ImJvb2xlYW5BZ3JlZW1lbnQiOnsidGl0bGUiOiJJIGFncmVlIHdpdGggdGVybXMgYW5kIGNvbmRpdGlvbnMiLCJ0eXBlIjoiYm9vbGVhbiIsImNvbnN0Ijp0cnVlLCJkZWZhdWx0IjpmYWxzZX0sInN0cmluZ0NvbmZpcm1hdGlvbiI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJJbiBvcmRlciB0byByZW1vdmUgdGhlIHJlcG9zaXRvcnksIHdyaXRlICdyZWFjdC1qc29uc2NoZW1hLWZvcm0nIGJlbG93IiwiY29uc3QiOiJyZWFjdC1qc29uc2NoZW1hLWZvcm0iLCJkZWZhdWx0IjoiIn19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiIsInVpOnBsYWNlaG9sZGVyIjoidWk6ZW1wdHlWYWx1ZSBjYXVzZXMgdGhpcyBmaWVsZCB0byBhbHdheXMgYmUgdmFsaWQgZGVzcGl0ZSBiZWluZyByZXF1aXJlZCIsInVpOmF1dG9jb21wbGV0ZSI6ImZhbWlseS1uYW1lIiwidWk6ZW5hYmxlTWFya2Rvd25JbkRlc2NyaXB0aW9uIjp0cnVlLCJ1aTpkZXNjcmlwdGlvbiI6Ik1ha2UgdGV4dCAqKmJvbGQqKiBvciAqaXRhbGljKi4gVGFrZSBhIGxvb2sgYXQgb3RoZXIgb3B0aW9ucyBbaGVyZV0oaHR0cHM6Ly9tYXJrZG93bi10by1qc3gucXVhbnRpem9yLmRldi8pLiJ9LCJsYXN0TmFtZSI6eyJ1aTphdXRvY29tcGxldGUiOiJnaXZlbi1uYW1lIiwidWk6ZW5hYmxlTWFya2Rvd25JbkRlc2NyaXB0aW9uIjp0cnVlLCJ1aTpkZXNjcmlwdGlvbiI6Ik1ha2UgdGhpbmdzICoqYm9sZCoqIG9yICppdGFsaWMqLiBFbWJlZCBzbmlwcGV0cyBvZiBgY29kZWAuIDxzbWFsbD5BbmQgdGhpcyBpcyBhIHNtYWxsIHRleHRzLjwvc21hbGw+ICJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoidXBkb3duIiwidWk6dGl0bGUiOiJBZ2Ugb2YgcGVyc29uIiwidWk6ZGVzY3JpcHRpb24iOiIoZWFydGggeWVhcikifSwiYmlvIjp7InVpOndpZGdldCI6InRleHRhcmVhIn0sInBhc3N3b3JkIjp7InVpOndpZGdldCI6InBhc3N3b3JkIiwidWk6aGVscCI6IkhpbnQ6IE1ha2UgaXQgc3Ryb25nISJ9LCJ0ZWxlcGhvbmUiOnsidWk6b3B0aW9ucyI6eyJpbnB1dFR5cGUiOiJ0ZWwifX19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsInZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZWQiOmZhbHNlLCJub0h0bWw1VmFsaWRhdGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2UsImV4cGVyaW1lbnRhbF9kZWZhdWx0Rm9ybVN0YXRlQmVoYXZpb3IiOnsiYXJyYXlNaW5JdGVtcyI6InBvcHVsYXRlIiwiYWxsT2YiOiJza2lwRGVmYXVsdHMiLCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMiLCJtZXJnZURlZmF1bHRzSW50b0Zvcm1EYXRhIjoidXNlRm9ybURhdGFJZlByZXNlbnQifX19).

**Comment by heath-freenome** [comment]
@MarekBodingerBA According to the [spec](https://json-schema.org/understanding-json-schema/reference/const#constant-values) a const value for a field restricts that field to have one value (i.e. it can never be changed). Is the idea that const for optional fields should not prefill? Also, you could use the `uiSchema` to force the field to be `readonly: false` I believe.  Did you want to add an experimental flag that doesn't prefill const values? Let's talk about this some more.

**Comment by nickgros** [comment]
If you can prefill your form data, you could do [something like this](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJib29sZWFuQWdyZWVtZW50Ijp0cnVlLCJzdHJpbmdDb25maXJtYXRpb24iOiJyZWFjdC1qc29uLXNjaGVtYS1mb3JtIn0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsiYm9vbGVhbkFncmVlbWVudCIsInN0cmluZ0NvbmZpcm1hdGlvbiJdLCJwcm9wZXJ0aWVzIjp7ImJvb2xlYW5BZ3JlZW1lbnQiOnsidGl0bGUiOiJJIGFncmVlIHdpdGggdGVybXMgYW5kIGNvbmRpdGlvbnMiLCJ0eXBlIjoiYm9vbGVhbiIsImNvbnN0Ijp0cnVlLCJkZWZhdWx0IjpmYWxzZX0sInN0cmluZ0NvbmZpcm1hdGlvbiI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJJbiBvcmRlciB0byByZW1vdmUgdGhlIHJlcG9zaXRvcnksIHdyaXRlICdyZWFjdC1qc29uc2NoZW1hLWZvcm0nIGJlbG93IiwiY29uc3QiOiJyZWFjdC1qc29uc2NoZW1hLWZvcm0iLCJkZWZhdWx0IjoiIn19fSwidWlTY2hlbWEiOnsiYm9vbGVhbkFncmVlbWVudCI6eyJ1aTpyZWFkb25seSI6ZmFsc2V9LCJzdHJpbmdDb25maXJtYXRpb24iOnsidWk6cmVhZG9ubHkiOmZhbHNlfX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsIm5vSHRtbDVWYWxpZGF0ZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZSwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjoicG9wdWxhdGUiLCJhbGxPZiI6InNraXBEZWZhdWx0cyIsImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyIsIm1lcmdlRGVmYXVsdHNJbnRvRm9ybURhdGEiOiJ1c2VGb3JtRGF0YUlmUHJlc2VudCJ9fX0=) to get the behavior you're looking for.

**Comment by heath-freenome** [comment]
Ah wait, we also made the field readonly if const was specified. Perhaps that is what you are asking to roll-back?

**Comment by MarekBodingerBA** [comment]
@heath-freenome While I understand the spec's requirements, there might be legitimate use cases, such as an "I Agree" checkbox that should ultimately be checked true but not initially. How would you handle such a case?

Regarding "readonly": What's the standard for this library? Are other data types automatically set to readonly based on the schema, or is this the only case? If it's the only case, it should be considered whether this behavior is wanted for others or if there are other instances and it's consistent with the library's expected behavior.

@nickgros We unfortunately cannot prefill our form data due to the highly dynamic nature of our forms. We actually use `getDefaultFormState` on the backend to prefill the data before page rendering.

I think there are three options:

- Revert this change (probably not desired by others)
- Create a custom flag that won't prefill defaults for constants
- Make it respect defaults (`{const: true, default: false}`), though I'm unsure if this complies with the spec

What are your thoughts?

Thanks for all your work on this.

**Comment by MarekBodingerBA** [comment]
@heath-freenome Perfect! Would it make sense to support `{const: true, default: false}` also, or is it something that doesn't really fit?

**Comment by heath-freenome** [comment]
That would break the [spec](https://json-schema.org/understanding-json-schema/reference/const) since `const` indicates that it is the only value a field can have
