### ISSUE TITLE
<title>add support for muiv6

### ISSUE THREAD

**Issue by dberardo-com** [rjsf-team/react-jsonschema-form#4350]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

material-ui

### Is your feature request related to a problem? Please describe.

MUI v6 is out, i am not sure if there is any breaking change concerning rjsf but it would be nice to see it supported

**Comment by heath-freenome** [comment]
@dberardo-com `@rjsf/mui` already supportes MUI v6. Enjoy!
