### ISSUE TITLE
Error not propagated when raising errors from a custom widget or field

### ISSUE THREAD

**Issue by guilhermecastros** [rjsf-team/react-jsonschema-form#4382]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

Error messages are not being propagated correctly for json object schemas. 

For instance I have these two schemas, when I raise a custom error with `schema2` it works nice as expected & described on the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs/advanced-customization/custom-widgets-fields/#raising-errors-from-within-a-custom-widget-or-field). But when I do the same, but for `schema` which has a type `object` it doesn't work.

```
export const schema: RJSFSchema = {
  properties: {
    Test: {
      type: "number",
      title: "Test 1",
    },
    Test2: {
      type: "number",
      title: "Test 2",
    },
  },
  type: "object",
};
```

```
export const schema2: RJSFSchema = {
  type: "string",
  default: "hello",
};
```

I have created the following playground that allows you to play & to check the current behavior ⬇️ 

https://codesandbox.io/p/sandbox/rjsf-custom-error-ql66mh?workspaceId=7d9d1079-911b-4954-9a3d-7c3de5279f0c

![image](https://github.com/user-attachments/assets/4081fa86-c542-49e4-91fe-46cc810c7a83)

![image](https://github.com/user-attachments/assets/64438dab-9c30-4d86-b419-04af55781d15)

### Expected Behavior

Custom errors should show regardless of the schema used, which means it should show on both described scenarios.

### Steps To Reproduce

1. Open playground.
2. You will see that I am rendering two schemas.
3. Type something on each field
4. You will see that for the schema of type `object`, no error is shown.

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilhermecastros** [comment]
I believe this issue is related to https://github.com/rjsf-team/react-jsonschema-form/pull/4188. Maybe @abdalla-rko knows more about this?

**Comment by heath-freenome** [comment]
@guilhermecastros Thanks for finding this. We have a bug in our `NumberField` which I will be fixing soon
