### ISSUE TITLE
When in a customValidate function, how do I get the expanded form schema?

### ISSUE THREAD

**Issue by gnalvesteffer** [rjsf-team/react-jsonschema-form#4410]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

fluent-ui

### What is your question?

Hi, I'm trying to implement a custom validation function and need to access the expanded form schema. The `retrieveSchema` function sounds like what I want, but I haven't had any luck getting it to return anything but the exact same form schema I passed into it: https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/utility-functions#retrieveschemat--any-s-extends-strictrjsfschema--rjsfschema-f-extends-formcontexttype--any

I need the expanded version of the schema that has the dependencies, conditions, etc already resolved so I can do something in my validation like checking a conditional set of properties that are only presented when another boolean field is true, but without this, it looks like I would have to try to resolve this myself by somehow evaluating the conditions in oneOfs and such, which seems very error-prone if I were to do it myself.

**Comment by heath-freenome** [comment]
@gnalvesteffer are you passing the `formData` in properly so that `retrieveSchema()` knows which dependency/condition to use?

**Comment by gnalvesteffer** [comment]
> @gnalvesteffer are you passing the `formData` in properly so that `retrieveSchema()` knows which dependency/condition to use?

Hi @heath-freenome, sorry for the late reply, but yes, in my `customValidate` function I have access to the incoming `formData` and I'm passing that in alongside the form schema to the `retrieveSchema` function. Let me put together a simple sample to share a reproduction of this issue. Will post it here once it's ready.

Also for reference, here are my project's dependencies:
```json
    "@fluentui/react-components": "^9.54.15",
    "@rjsf/core": "^5.20.1",
    "@rjsf/fluentui-rc": "^5.20.1",
    "@rjsf/utils": "^5.20.1",
    "@rjsf/validator-ajv8": "^5.18.4",
    "@uiw/react-textarea-code-editor": "^3.1.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
```

**Comment by gnalvesteffer** [comment]
Here is a sample I've put together to reproduce this: https://codesandbox.io/p/sandbox/q3hs27

See `App.tsx:L106` for the retrieveSchema usage. I am also logging the `formData` and the `retrieveSchema` result to the console, triggered on form submission.

Example:
![image](https://github.com/user-attachments/assets/b747cc3d-22cd-458d-bd2f-12eb3e30adca)

I'd expect the `retrieveSchema` result to have the "expanded" schema with the dependencies resolved, where in this example it should merge the dependency that was used into the properties:
![image](https://github.com/user-attachments/assets/e00e722e-587f-4174-93f8-4b6f0c93c058)

**Comment by gnalvesteffer** [comment]
After reading [this comment](https://github.com/rjsf-team/react-jsonschema-form/issues/3995#issuecomment-1847802000) explaining the behavior of `retrieveSchema`, I was able to resolve the expanded schema with the following:
```ts
export default function getExpandedSchema(validator: AJV8Validator, schema: RJSFSchema, rootSchema: RJSFSchema, data: any) {
    const resolvedSchema = retrieveSchema(validator, schema, rootSchema, data);
    if (resolvedSchema.properties) {
        Object.keys(resolvedSchema.properties).forEach((key) => {
            if (data[key] !== undefined) {
                const propertySchema = resolvedSchema.properties[key];
                const resolvedPropertySchema = retrieveSchema(validator, propertySchema, rootSchema, data[key]);
                Object.assign(resolvedSchema.properties[key], resolvedPropertySchema);
                getExpandedSchema(validator, resolvedPropertySchema, rootSchema, data[key]);
            }
        });
    }
    return resolvedSchema;
}
```

**Comment by gnalvesteffer** [comment]
Figured it out with the following solution: https://github.com/rjsf-team/react-jsonschema-form/issues/4410#issuecomment-2529106810
