### ISSUE TITLE
Add computed fields ?

### ISSUE THREAD

**Issue by leplatrem** [rjsf-team/react-jsonschema-form#45]
Would it be the scope of this library to be able to specify small routines to compute default values of fields ?

Our use-cases is to be able to set the current date/time in a (hidden) field.

**Comment by Natim** [comment]
I remember this was done in the formbuilder to compute the field id from the label.

**Comment by n1k0** [comment]
Do you guys have a dream API in mind for this here?

**Comment by Natim** [comment]
UISchema set to something like:

```
{
   "slug": {"populate_from": "title"},
}
```

**Comment by leplatrem** [comment]
After discussion:

* We should keep this library as minimalist and focused as possible
* For the created date use-case, it is possible to use the `onSubmit()` function to alter the final object 
* For the slug use-case, the idea would be to introduce a `onFieldChange` hook that can alter the field value (or others fields)

```js
      <Form schema={schema}
            uiSchema={uiSchema}
            onFieldChange=(name, value, data) => {
               return {...data, name: slugify(data['title'])};
            } />

```

**Comment by n1k0** [comment]
> `onFieldChange=(name, value, data) => {`

To be noted, we should allow intercepting any deeply nested changed updated here.

**Comment by apkoponen** [comment]
Jdorns Json-editor uses the templates for this:

https://github.com/jdorn/json-editor#templates

**Comment by n1k0** [comment]
Hmm, nice though most often you're likely to want a little more than just templating... functions are probably better for advanced computations :)

**Comment by apkoponen** [comment]
Yup, templates do have their limitations.

**Comment by maartenth** [comment]
> `onFieldChange=(name, value, data) => {`

Could I help with implementing this feature? I'm currently working on a project where this would be very welcome.

How do you see this in combination with the current `onChange()` function? Would all fields call onFieldChange instead, or both? And which one would come first?

**Comment by maartenth** [comment]
@n1k0 Bumping this question because you probably missed my comment above. :)

**Comment by n1k0** [comment]
Form `onChange` should work as before, but reflect computed field values in `formData`.

As mentioned before, the trickiest part imo is to find a nice API for hooking into deeply nested fields. Using strings to identify these isn't an option in my world. All I can see atm is to introduce yet another new `hooks` prop which would be an objet registering nested hook functions: 

```jsx
const schema = {
  type: "object",
  properties: {
    foo: {
      type: "object",
      properties: {
        bar: {type: "string"}
      }
    }
  }
} 

const hooks = {
  foo: {
    bar: (value) => value + "!"
  }
}

render(<Form hooks={hooks}/>)
```

We'll have to be careful with precedence here though.

Thoughts?

**Comment by maartenth** [comment]
Thank you for your reply and your thoughts. I will try to find a more elegant API.

**Comment by knilink** [comment]
How about
```jsx
//SchemaField.js  
function getFieldComponent(schema, uiSchema, fields) {
   //....
   return (uiSchema["ui:enhancer"] || a=>a)(FieldComponent);
}
```

```jsx
import propsMapper from "recompose/propsMapper";
//...
const uiSchema = {
  title: {
    'ui:enhancer': propsMapper(({value, onChange, ...rest})=>({
      onChange: value => onChange(slugify(value)),
      value: unslugify(value),
      ...rest
    }))
  }
};
```

For this case, I personally prefer simply
```jsx
import propsMapper from "recompose/propsMapper";
import TextWidget from "react-jsonschema-form/TextWidget";

const uiSchema = {
  title: {
    'ui:widget': propsMapper(({value, onChange, ...rest})=>({
      onChange: value => onChange(slugify(value)),
      value: unslugify(value),
      ...rest
    }))(TextWidget)
  }
};
```

**Comment by n1k0** [comment]
It would feel odd to add data processing logic to *uiSchema*, which has always been intended to deal with presentation only. 

Also, I'm still pretty much convinced that post-processing data could (and should) be achieved in the form's `onSubmit` event handler.

**Comment by elisechant** [comment]
@n1k0 I would agree. I normalize payload before post. Or you might be able to use a controlled component to compute inline?

I feel like these solutions are pretty heavy on perf?

**Comment by acouch** [comment]
Anyone find a decent solution for this? If I intercept the state change similar to https://github.com/Kinto/formbuilder/blob/8ceae7585108c3fe8d0ed64882f9d856cf2ef9e7/formbuilder/components/EditableField.js#L43-L62 my slug field is always one character behind.

**Comment by lovato** [comment]
@OliverColeman I am having the VERY SAME issue you had. And your suggestion fixed my problem. Thanks man.

**Comment by Matnard** [comment]
This is how I got it to work.
```
export const CustomObjectField = (props: FieldProps) => {
  const {
    schema,
    uiSchema,
    idSchema,
    formData,
    errorSchema,
    onChange,
    onBlur,
    onFocus,
    registry,
    disabled,
    readonly,
    name,
  } = props;

  const { fields } = registry;
  const { ObjectField } = fields;

  return (
    <ObjectField
      schema={schema}
      uiSchema={uiSchema}
      idSchema={idSchema}
      formData={formData}
      errorSchema={errorSchema}
      onChange={(obj) => {
        const newObj = structuredClone(obj);

        newObj["total"] =
          newObj["a"] +
          newObj["b"] +
          newObj["c"] +
          newObj["d"];

        onChange(newObj);
      }}
      onBlur={onBlur}
      onFocus={onFocus}
      registry={registry}
      disabled={disabled}
      readonly={readonly}
      name={name}
    />
  );
};
```
