### ISSUE TITLE
Error list disappears when updating a field in error

### ISSUE THREAD

**Issue by n1k0** [rjsf-team/react-jsonschema-form#482]
Sample form https://jsfiddle.net/x79eop03/ 

1. type a single char in the `name` field
2. submit the form
3. type another char in the same field

The top error list disapears as soon as the second character is entered, which shouldn't happen, especially with the `liveValidate` prop not being leveraged. This doesn't happen with a formData state wrapper: https://jsfiddle.net/vj172c7s/1/

**Comment by Reggino** [comment]
I guess something went wrong with the jsfilddles: both examples contain the same code.

**Comment by n1k0** [comment]
Thanks for noticing. Updated the second fiddle with the right code https://jsfiddle.net/vj172c7s/1/

**Comment by n1k0** [comment]
May be related to #486.

**Comment by knilink** [comment]
Form.js line 72, status === "editing".

If formData is provided, then
onChange -> formData in props changed -> componentWillReceiveProps -> getStateFromProps -> {status: 'initial'}

Let's differentiate controlled an uncontrolled formData to end this pain. : )

**Comment by n1k0** [comment]
> Let's differentiate controlled an uncontrolled formData to end this pain. : )

Agreed. You seem to have a clear picture of what should be done, so don't hesitate to give it a shot!
