### ISSUE TITLE
datetime-local is being silently cast to UTC

### ISSUE THREAD

**Issue by ben-freenome** [rjsf-team/react-jsonschema-form#496]
### Description

The 'DateTimeWidget' object (and AltDateTimeWidget) use appear to allow the user to input local date/time information. That information is then cast into UTC via `new Date(date)`. This negates the `-local` portion of the `datetime-local` input object spec.

### Steps to Reproduce

1. create a datetime object while not in UTC tz
2. view resulting Date object in Inspector. time will have been implicitly cast to UTC, not local timezone.

#### Expected behavior

DateTimeWidget (or a new DateTimeLocal widget, for backwards compatibility) should implicitly use the local timezone instead of converting to UTC.

#### Actual behavior

DateTimeWidget automatically converts input time to UTC, ignoring the `-local` portion of the `datetime-local` input object spec.

### Version

0.41

**Comment by n1k0** [comment]
I think this has officially become a documentation issue. A docs PR would be greatly appreciated ;)

**Comment by kentplaza** [comment]
I facing same problem which the datetime picker post the date value in +0.00

**Comment by nabilfreeman** [comment]
I also ran into this problem.

I worked around it in an extremely convoluted way - use datetime strings, I replaced the `+01:00` component of the dates with `Z` so they would appear correctly in the form, and then converted them back on submit. 

It would be nice if you could simply specify the locale to the datetime widget (I'm using `alt-datetime`)

**Comment by glasserc** [comment]
If you're using `+01:00`, you probably aren't handling DST. I don't know what timezone you're in, but if I were a betting man, I would bet that you were in a timezone that observes DST.

I agree that the current situation is suboptimal, though.
