### ISSUE TITLE
Feature request: allow custom required field symbol

### ISSUE THREAD

**Issue by hanars** [rjsf-team/react-jsonschema-form#540]
### Prerequisites

- [ x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Required fields are always indicated with an \*. It would helpful to allow any string to be used instead, such as "(*)" or an empty string for no indicator

### Version

0.45.0

**Comment by glasserc** [comment]
I'm sympathetic to the idea of allowing customization of how we display these things, but I feel like this is pretty thoroughly covered already by the ability to provide a `FieldTemplate`, and I am hesitant to add too many mechanisms for customization for fear of overwhelming complexity.
