### ISSUE TITLE
Hiding the label for nested object field using uiSchema

### ISSUE THREAD

**Issue by vamsiampolu** [rjsf-team/react-jsonschema-form#578]
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

I'm [linking to the playground](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCJ9LCJzY2hlbWEiOnsidGl0bGUiOiJBIHJlZ2lzdHJhdGlvbiBmb3JtIiwiZGVzY3JpcHRpb24iOiJBIHNpbXBsZSBmb3JtIGV4YW1wbGUuIiwidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbImZpcnN0TmFtZSIsImxhc3ROYW1lIl0sInByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkZpcnN0IG5hbWUifSwibGFzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiTGFzdCBuYW1lIn0sIm1vcmUiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiYWdlIjp7InR5cGUiOiJpbnRlZ2VyIiwidGl0bGUiOiJBZ2UifSwiYmlvIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkJpbyJ9LCJwYXNzd29yZCI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJQYXNzd29yZCIsIm1pbkxlbmd0aCI6M319fX19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIn0sIm1vcmUiOnsidWk6b3B0aW9ucyI6eyJsYWJlbCI6ZmFsc2V9LCJwYXNzd29yZCI6eyJ1aTp3aWRnZXQiOiJoaWRkZW4ifSwiYmlvIjp7InVpOndpZGdldCI6ImhpZGRlbiJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoiaGlkZGVuIn19fX0=
) as this is only related to the schema and does not involve any code

#### Expected behavior

I would like to completely hide a nested object field using the `uiSchema`, I expected to be able to hide it using

```json
{
  "more": {
     "ui:widget": "hidden"
   }
}
```

Instead I have to hide each field in the nested field manually, once all fields are hidden, it still displays the label. To hide the label, I expect that setting `label` to false will work:

```json
{
   "more": {
      "ui:options": {
         "label": false
      },
      "prop": {
         "ui:widget": "hidden"
      }
  }
}
```

#### Actual behavior

This config needs me to set `title` on schema to `empty string` and then set all widgets to hidden as well:

```json
{
   "schema": {
    "more": {
       "type":"object",
      "title": "",
        "properties": {
            
       }
     }
  },
  "uiSchema": {
     "more":{
            
      }
  }
}
```

Is it possible for the form to recognize if an object field is not the root field and hide every field using `ui:hidden` as well as allowing for hiding individual widgets?

**Comment by glasserc** [comment]
Hi, thanks for your question. At the present time, react-jsonschema-form doesn't support hiding anything more complicated than a single input field. We'd be interested in reviewing a PR that added this feature in a clean way. You can look at #322/#324 for ideas if you would like to implement this yourself.

**Comment by epicfaace** [comment]
I believe this is now supported in the latest version of rjsf.
