### ISSUE TITLE
Converting source to TypeScript?

### ISSUE THREAD

**Issue by KurtPreston** [rjsf-team/react-jsonschema-form#583]
Would you consider a Pull Request converting react-jsonschema-form to TypeScript?

**Comment by zhang-ning** [comment]
+1 TypeScript

**Comment by glasserc** [comment]
Not at the present time, although I guess that could change later. (If it does, I'll reopen.)

**Comment by loganvolkers** [comment]
@glasserc interesting discussions about the Jest typescript migration https://news.ycombinator.com/item?id=18918038

**Comment by epicfaace** [comment]
I wouldn't mind, honestly, though it would be a large rewrite to do so.

**Comment by thijssteel** [comment]
I'd be willing to help with this.
However, i suck at everything webpack and compiler related. If someone has time to get me started with that I believe a full conversion should be possible in a couple of days work.

**Comment by chanceaclark** [comment]
This is the :dream:. Let me know if you need some help as well.

**Comment by sbusch** [comment]
@epicfaace is this a goal for v2?

We are heavily using TypeScript and are currently maintaining a patched set of TS definitions to have *some* (quite inexact) type safety for our custom fields and widgets. A native TS implementation with good type coverage will be a huge step not only for us, but IMO for the project (stability, types as documentation, confidence when doing some refactorings, see my latest comment at #1286)

So I also offer my help for this migration, and support in case of problems.

**Comment by epicfaace** [comment]
Yeah, let's make it a goal for v2. @sbusch could you send over whichever of your TS definitions might be helpful? I think starting with those as well as the DefinitelyTyped definitions would give us a good starting point with which to add the rest of the types needed.

**Comment by thijssteel** [comment]
https://github.com/wix-incubator/as-typed

do you guys think this might be useful?

**Comment by jacqueswho** [comment]
we could possibly use [tsdx](https://tsdx.io/)

**Comment by heath-freenome** [comment]
An effort has begun to convert the `@rjsf/core` package to typescript in the upcoming v5 version

**Comment by KurtPreston** [comment]
@heath-freenome Nice! I am no longer using this project, but it's great to hear that the TypeScript conversion is underway.

**Comment by ksbrar** [comment]
@heath-freenome If you're still looking for extra hands, would be interested in participating!

**Comment by heath-freenome** [comment]
@ksbrar We've managed to complete the conversion of the `core` package to Typescript but would love help with the `antd` theme

**Comment by heath-freenome** [comment]
We are 100% typescript in the 5.x
