### ISSUE TITLE
Add onFocus event support for inputs

### ISSUE THREAD

**Issue by gapipro** [rjsf-team/react-jsonschema-form#624]
### Description
I would like to have support for onFocus event on input fields. This way you can control classNames or some other behaviour when input gets focused. 

#### Expected behavior
When input gets focused onFocus callback is called.

**Comment by knilink** [comment]
Not sure about the actual scenario, there are many ways(custom fields/widgets, extend builtin fields/widgets, custom templates) to customize the onFocus.
[Here](https://codepen.io/anon/pen/pwVWRL) is an example of using CustomTemplate.

**Comment by glasserc** [comment]
Has this been addressed now that #657 has been released?

**Comment by epicfaace** [comment]
This should be fixed now
