### ISSUE TITLE
Different JSON error paths with custom validate function

### ISSUE THREAD

**Issue by theengineear** [rjsf-team/react-jsonschema-form#627]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

JSON error paths do not start at root `instance` with custom `validate` function.

The custom function in this case is:

```javascript
function validate (formData, errors) {
    return errors;
}
```

### Steps to Reproduce

Checkout this Fiddle. https://jsfiddle.net/aseier/j4gu1715/

In the above fiddle:

1. Add a `tag` to each form (there are two)
2. Enter any non-integer value (E.g., "foo").
3. Click submit.

#### Expected behavior

I'd expect the errors to be *the exact same* for the case where there *is* custom validation and where there *is not* custom validation.

E.g., `instance.tags[0] is not of a type(s) integer` for both.

#### Actual behavior

The custom validation errors seem to only include the *last* path part.

E.g., instead of `instance.tags[0] is not of a type(s) integer`, you get: `0: is not of a type(s) integer`.

### Version

`react-jsonschema-form@0.49.0`

### Praise

Thanks for managing this project. It's super helpful!

**Comment by bingo-lumity** [comment]
Well it's already mentioned in validate.js near the last line:

> The errors list produced [from the custom validation] is not fully compliant with the format exposed by the jsonschema lib, which contains full field paths and other properties.

I don't know the intent for having a different structure depending on whether a custom validation function is used or not.

**Comment by baohouse** [comment]
Well it's already mentioned in validate.js near the last line:

> The errors list produced [from the custom validation] is not fully compliant with the format exposed by the jsonschema lib, which contains full field paths and other properties.

I don't know the intent for having a different structure depending on whether a custom validation function is used or not.

**Comment by heath-freenome** [comment]
With the extraction of the validators, a user can now plug in their own. Also it is up to the user to properly encode the errors in the custom validation function. Moreover, with the full conversion to typescript, the errors were standardized. Closing this as I don't believe it is a bug.
