### ISSUE TITLE
Add `minRemovable` options

### ISSUE THREAD

**Issue by mfulton26** [rjsf-team/react-jsonschema-form#635]
RJSF supports [`addable`](https://github.com/mozilla-services/react-jsonschema-form#addable-option) and [`removable`](https://github.com/mozilla-services/react-jsonschema-form#removable-option) options but does not currently support hiding the remove buttons when `minItems` is met. I propose the following option (or similarly named one) be added:

#### `minRemovable` option

A remove button is shown by default even when the number of items is less than or equal to `minItems`. You can turn this off with the `minRemovable` option in `uiSchema`:

```jsx
const uiSchema = {
  "ui:options":  {
    minRemovable: false
  }
};

**Comment by mfulton26** [comment]
I've since learned that the add button is not shown once `maxItems` is worth so I've updated this issue to only add a `minRemovable` option.

**Comment by glasserc** [comment]
Hmm. I didn't realize we don't show an add button once we reach `maxItems`. (I even [wrote about it](https://github.com/mozilla-services/react-jsonschema-form#philosophy) in the README.) Personally, I would have said we should show buttons in all cases. I agree that some users want to prevent users from "coloring outside of the lines", as it were, but I feel like such a granular option as `minRemovable` is too granular -- in general, I would expect a developer to either want none of the safety guards, or all of them. So I would prefer to see a larger-grain option, perhaps at the root of the uiSchema, that adds all of the safety possible. What do you think about that? I understand it's a more invasive change, but I think it's a more holistic approach.

**Comment by mfulton26** [comment]
Yeah, I like that. I'm currently involved more heavily in some other projects at the moment but when I circle back to the one where we're using rjsf I'll take a look at a more in depth change (unless someone beets me to it).
