### ISSUE TITLE
[Question] Dynamic titles for array fields

### ISSUE THREAD

**Issue by joshhornby** [rjsf-team/react-jsonschema-form#649]
### Prerequisites

- [ x ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

I am looking into a way of generating dynamic titles for items in an Array Field. In my current schema I have two `array` fields so only want to target one with the custom dynamic titles.

In this case each title should be a day of the week, this data is coming from the `formData` being passed in. So each `object` in the `array` would have a title. 

My questions are:

1) Is it possible to render a dynamic title based off a property?
2) If not, how can I define a custom template for only one `array` field at a time?

Thanks

**Comment by shortwavedave** [comment]
I also need this feature - is there any way to accomplish this?

**Comment by epicfaace** [comment]
1. There is currently no way defined by JSON Schema to change the schema based on the data. [There is a proposal for the `$data` keyword](https://github.com/json-schema-org/json-schema-spec/issues/51), but it looks like it's still in discussion and may or may not be standardized.

If the form data is based on a property that is not part of the array element, you _could_ do something with dependencies though. For example:

```
{
    "type": "object",
    "defintions": {
        "b": {"type": "array", "items": {"type": "string"}}
    },
    "properties": {
        "a": {"type": "string"}  
    },
    "dependencies": {
        "a": {
            "oneOf": [
                {
                    "properties": {
                        "a": {"const": "Option1"},
                        "b": {"$ref": "#/definitions/b", "title": "Title based on Option1"}
                    }
                },
                {
                    "properties": {
                        "a": {"const": "Option2"},
                        "b": {"$ref": "#/definitions/b", "title": "Title based on Option2"}
                    }
                }
            ]
        }
    }
}
```

2. You can define a custom template for a single array element by using `ui:ArrayFieldTemplate` as mentioned in https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/#array-field-template.

**Comment by epicfaace** [comment]
Closing this issue, but feel free to reopen it if you have any additional questions!

**Comment by vxb1766** [comment]
@epicfaace I have a similar issue. how do I add title for array items?
https://codepen.io/veena-balasubramanya-gmail-com/pen/xxPJxoW
When I click plus, I want the title to show as test1, test2, test3
