### ISSUE TITLE
Allow more customization

### ISSUE THREAD

**Issue by herzaso** [rjsf-team/react-jsonschema-form#683]
### Prerequisites

- [x ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Currently, there is no simple way to support a horizontal form (2 columns where the first is the label and the second is the field).
In bootstrap, in order to do it, you have to supply a `form-horizontal` className to the `form` tag (that's doable today by passing a className to `Form`) but more importantly, you have to wrap the widget with a `div` (today, only some widgets are wrapped) and supply classNames to the `label`, the wrapping widget `div` and in our case, probably the other `div`s also (the error, help, etc.)

Although this feature is specific to horizontal forms, adding such ability will provide a better granularity over customization of the form.

Also, for simplicity, this needs to be in the schema level as well as in the widget level

**Comment by SivaGanesh56** [comment]
Any progress on this?
