### ISSUE TITLE
autoSelect

### ISSUE THREAD

**Issue by Y-Less** [rjsf-team/react-jsonschema-form#744]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

There is already `autoFocus`, so that when a field appears the cursor is in it.  `autoSelect` would also be very helpful, so that when the field appears all the text in it is already selected for deletion.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

#### Expected behavior

Setting a schema of `{ 'ui:autoSelect': true }` highlights all the text in an input field when it renders.

#### Actual behavior

Nothing.

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by epicfaace** [comment]
@Y-Less are you interested in making a PR for this?
