### ISSUE TITLE
Fieldset preventing flexbox styling 

### ISSUE THREAD

**Issue by ttbarnes** [rjsf-team/react-jsonschema-form#762]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme)

### Description

Currently, the form is wrapped with a `fieldset` element:

```
<div class="form-group field field-object">
  <fieldset>
    ...
  </fieldset>
</div>
```

This is great, and semantic, however this can prevent some styling with flex. Flex cannot be applied to a fieldset, and so you cannot use flex to render the form layout as desired.

It would be great to have an optional prop that would change this fieldset to a div or something similar.

Just an initial idea - probably a better way to handle this. Any thoughts? I could do a PR.

**Comment by matiaslarsson** [comment]
@ttbarnes Until that optional prop is available a workaround is to use the `customFields` form prop to override for example the `ObjectField` with a custom object field using divs instead of fieldsets but it's a lot of duplicated code for such a small change.

**Comment by paintedbicycle** [comment]
I have run into the "Flexbox / CSS-Grid in Chrome" issue, where chrome does not allow them on Fieldset elements.

So, I'd like to change the Fieldset in all my forms to something else...basically just swap <fieldset> for a <div> or <section>.

I find the docs on this very confusing. Can anyone point me to docs or specific info on how to do this? I'm confused with all the terminology around overriding defaults fields, or creating custom fields, custom widgets and custom components.

For example:

1. If I'm to create my own, I'm not sure what the default ones look like so I could just copy them and then remove / change certain elements, while passing all the same props, etc.
2. Would changing the fields be considering overriding or creating custom?
3. Would it be a field, a widget or a component?
4. If I wanted to remove a bunch of extra wrapper / empty divs at the same time, how would I do that?

Thanks,

Paul

**Comment by paintedbicycle** [comment]
OK I have found a workaround

This is the default object field template (from https://github.com/mozilla-services/react-jsonschema-form/blob/174e136af4fe728eb79e92594733ea729f3d659f/src/components/fields/ObjectField.js)

```
function ObjectFieldTemplate(props) {
  const canExpand = function canExpand() {
    const { formData, schema, uiSchema } = props;
    if (!schema.additionalProperties) {
      return false;
    }
    const { expandable } = getUiOptions(uiSchema);
    if (expandable === false) {
      return expandable;
    }
    // if ui:options.expandable was not explicitly set to false, we can add
    // another property if we have not exceeded maxProperties yet
    if (schema.maxProperties !== undefined) {
      return Object.keys(formData).length < schema.maxProperties;
    }
    return true;
  };

  const { TitleField, DescriptionField } = props;
  return (
    <fieldset id={props.idSchema.$id}>
      {(props.uiSchema['ui:title'] || props.title) && (
        <TitleField
          id={`${props.idSchema.$id}__title`}
          title={props.title || props.uiSchema['ui:title']}
          required={props.required}
          formContext={props.formContext}
        />
      )}
      {props.description && (
        <DescriptionField
          id={`${props.idSchema.$id}__description`}
          description={props.description}
          formContext={props.formContext}
        />
      )}
      {props.properties.map(prop => prop.content)}
      {canExpand() && (
        <AddButton
          className="object-property-expand"
          onClick={props.onAddClick(props.schema)}
          disabled={props.disabled || props.readonly}
        />
      )}
    </fieldset>
  );
}
```

If you change the fields to a `<div>` or anything else and then use this as a custom object (from https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/#object-field-template) like this:

```
          <Form
            schema={formSchema}
            uiSchema={formUiSchema}
            formData={this.state.formData}
            onChange={this.handleChange}
            onBlur={this.handleBlur}
            onSubmit={this.handleSubmit}
            **ObjectFieldTemplate={ObjectFieldTemplate}**
          >
          </Form>

```

With the important bit being the custom object field template that you've included in your component and referenced in the form.

**Comment by epicfaace** [comment]
This `fieldset` issue is pretty annoying. It would make sense to change `fieldset` to `div` elements when we release V2.

**Comment by ivarprudnikov** [comment]
FYI `flex` on `fieldset` is working in Firefox 46+, Safari, IE10-11

It would also be useful to know what exactly cannot be achieved why `flex` on `fieldset`. Could anyone provide a real world example?

**Comment by JoshVazq** [comment]
@ivarprudnikov  basically `flex` is ignored by `fieldset`.
Right now I think that only chrome have this behaviour ([stackoverflow](https://stackoverflow.com/questions/28078681/why-cant-fieldset-be-flex-containers)).

**Comment by alihusic** [comment]
@ivarprudnikov `display:grid` is also ignored on `fieldset` in Chrome and Edge

**Comment by ivarprudnikov** [comment]
@JoshVazq could you come up with a real world example so that it is easy to see and test it?

**Comment by alihusic** [comment]
@ivarprudnikov 
![image](https://user-images.githubusercontent.com/15199823/75444243-62a77f00-5963-11ea-8b27-ae28b2149164.png)

A typical use case for this would be a part of the form which should contain 2 inline styles as shown on this image.

Creating custom widgets would be an overkill for larger forms, this can be solved by replacing `fieldset` with `div` in the library and setting its display to `grid` with 2 columns via overriding `ObjectFieldTemplate` and setting a custom class name for a certain part of the form. The next step would be adding custom class names in the ui schema which would set the fields to the first or second column (using `grid-column-start` and `grid-column-end`).

However, it would be very beneficial to at least have a prop which would use `div` instead of `fieldset` and thus avoid overriding `ObjectFieldTemplate`.

**Comment by paintedbicycle** [comment]
Chrome is fixing this bug. 

https://bugs.chromium.org/p/chromium/issues/detail?id=375693#c80

**Comment by shacco** [comment]
27-04-2020 still anoying. What is the purpose of the fieldset. please remove it.pleeeaseee

**Comment by paintedbicycle** [comment]
Chromium has now fixed this, though it hasn't landed in the browser just yet: https://bugs.chromium.org/p/chromium/issues/detail?id=375693#c80

**Comment by paintedbicycle** [comment]
This is no longer an issue in later versions of Chrome. Fieldset can take flex styles perfectly fine now.

**Comment by epicfaace** [comment]
That's great -- so let's just close this issue in that case!
