### ISSUE TITLE
Schema dependency Failed prop type ERROR

### ISSUE THREAD

**Issue by marvz73** [rjsf-team/react-jsonschema-form#772]
### Prerequisites

- [x] I have read the [documention](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme)

### Description
When using schema dependencies, it causes an error.

### Steps to Reproduce

```
var schema = {
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "credit_card": { "type": "string" }
  },
  "required": ["name"],
  "dependencies": {
    "credit_card": {
      "properties": {
        "billing_address": { "type": "string" }
      }
    }
  }
}

```

#### Actual behavior

When I try to enter a value in dependency field this error shows up:

> warning.js:33 Warning: Failed prop type: The prop `id` is marked as required in `BaseInput`, but its value is `undefined`.
>     in BaseInput (created by TextWidget)
>     in TextWidget (created by Unknown)
>     in Unknown (created by StringField)
>     in StringField (created by SchemaField)
>     in div (created by DefaultTemplate)
>     in DefaultTemplate (created by SchemaField)
>     in SchemaField (created by ObjectField)
>     in fieldset (created by DefaultObjectFieldTemplate)
>     in DefaultObjectFieldTemplate (created by ObjectField)
>     in ObjectField (created by SchemaField)
>     in div (created by DefaultTemplate)
>     in DefaultTemplate (created by SchemaField)
>     in SchemaField (created by Form)
>     in form (created by Form)
>     in Form

### Version

1.0.0

**Comment by redixhumayun** [comment]
Yeah, having the same issue. The problem seems to be that an id is not being generated for each of the new fields that are being added as part of the dependency schema.

**Comment by desirelabs** [comment]
Hello, same issue here. How do you manage to manually add the id ?

**Comment by redixhumayun** [comment]
Hey, submitted a PR for this, [#778](https://github.com/mozilla-services/react-jsonschema-form/pull/778)
Please take a look. This is a very important feature for us, and we need it back as soon as possible

**Comment by heilgar** [comment]
Hi, somebody found how fix that issue?

When I use the < Form />, its works for me, but I'm using SchemaField, instead of Form, so can't find a way how to fix ` The prop id is marked as required in BaseInput, but its value is undefined.`

**Comment by anudeesh** [comment]
Any update on this issue? I am having a similar issue with dynamic schema dependency. The schema is not getting modified with the change of formData.

**Comment by heilgar** [comment]
Hi @anudeesh, I found some workaround, have a look on Form component  at my form-builder repo
