### ISSUE TITLE
Bug in removing form elements of type array

### ISSUE THREAD

**Issue by monday1994** [rjsf-team/react-jsonschema-form#822]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

In form of type array when I try to remove first element it always remove last one.
This situation only occurs when I use fields of type file.

SCHEMA
{  
   "title":"Presentation",
   "type":"array",
   "items":{  
      "type":"object",
      "properties":{  
         "name":{  
            "type":"string",
            "title":"image name"
         },
         "file":{  
            "type":"string",
            "title":"file",
            format: "data-url",
         }
      }
   }
}

What is more weird when form is being submitted it returns correct data threw formData object.

#### Expected behavior

When I click remove button in form of type array it should remove correct element from form.

#### Actual behavior

If we have 2 (or more) images in form and try to remove the first then 2nd is being removed for some reason
![black1](https://user-images.githubusercontent.com/11651737/35348989-06a28980-013a-11e8-97b0-119587a8af68.png)
![black2](https://user-images.githubusercontent.com/11651737/35348937-e3fbef02-0139-11e8-902e-32f6c36d50f0.png)
### Version

1.0.0

**Comment by monday1994** [comment]
Any suggestions ?

**Comment by elieux** [comment]
This is a React thing, see [Uncontrolled Components](https://reactjs.org/docs/uncontrolled-components.html#the-file-input-tag).  React is unable to change the value of `<input type=file />`.  Combined with DOM reuse, it means the value is stuck in place until the input is re-rendered (e.g. by removing all rows and then adding a new one).  IMO it would be more obvious if React tried to at least reset the value if it can't set the correct one. `formData` seems to be updated independently and might end up holding the correct values.

A solution would be to use a widget that keeps the state outside of DOM.
