### ISSUE TITLE
Default checkbox field ignores ui:title and ui:description

### ISSUE THREAD

**Issue by alexfiedler** [rjsf-team/react-jsonschema-form#827]
### Prerequisites

- [x ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

The default checkbox field for boolean forms does not respect the `ui:title` or `ui:description` fields making it difficult to overwrite.

### Steps to Reproduce

1. Ignored UI values
Given a schema of:
```
{
  "title": "Boolean Title",
  "description": "Boolean Description",
  "type": "boolean"
}
```
And a UI Schema of:
```
{
  "ui:title": "Overwrite Boolean Title",
  "ui:description": "Overwite Boolean Description"
}
```
#### Behavior 

The form only displays the title from the description.

#### Expected behavior

It should display the `ui:title` and the `ui:description` as well.

2. Repeated title and description

Given a schema of:
```
{
  "title": "Boolean Title",
  "description": "Boolean Description",
  "type": "boolean"
}
```
And a UI Schema of:
```
{
  "ui:title": "Overwrite Boolean Title",
  "ui:description": "Overwite Boolean Description",
  "ui:widget": "checkbox"
}
```
#### Behavior 

The form only displays the the title, the description, the ui title, the ui description and the title.

#### Expected behavior

It should display only the `ui:title` and the `ui:description`.

### Version

1.0.0

**Comment by epicfaace** [comment]
Reproducible JSFiddle: https://jsfiddle.net/epicfaace/xh0uyLjn/

**Comment by CauchyAbel** [comment]
This should not be hard to fix, I did encounter the same issue.

**Comment by epicfaace** [comment]
@CauchyAbel it's labeled "good first issue" for a reason -- would you like to fix it? 😉

**Comment by CauchyAbel** [comment]
I would fix it during free time since I know this is a long live issue and not that critical, LOL

I did came across this myself so I knew :)

**Comment by cbuv** [comment]
this issue seems to be default behavior for rjsf default boolean field

In SchemaField.js: L273 - L275
```
  if (schema.type === "boolean" && !uiSchema["ui:widget"]) {
    displayLabel = false;
  }
```
perhaps you need to override this to avoid breaking change?

**Comment by siddharths00** [comment]
Building on the answer that @cbuv wrote, I believe that just adding "ui:widget":"checkbox" to uiSchema wouldn't be enough to solve the issue. However, something along the lines of the following might help us.

```
if (schema.type === "boolean" && uiSchema["ui:widget"]) {
    displayLabel = false;
  }
```
Notice that instead of  `!uiSchema["ui:widget"]` we have `uiSchema["ui:widget`, which will not display the label from Schema if we have a uiSchema label to override it. Perhaps this is all we require.

**Comment by adefrutoscasado** [comment]
Im facing this problem. Is it solved yet? Any workaround?

**Comment by heath-freenome** [comment]
Wow, still and issue in 5.x, but it differs across the various themes. See this [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6IkJvb2xlYW4gVGl0bGUiLCJkZXNjcmlwdGlvbiI6IkJvb2xlYW4gRGVzY3JpcHRpb24iLCJ0eXBlIjoiYm9vbGVhbiJ9LCJ1aVNjaGVtYSI6eyJ1aTp0aXRsZSI6Ik92ZXJ3cml0ZSBCb29sZWFuIFRpdGxlIiwidWk6ZGVzY3JpcHRpb24iOiJPdmVyd2l0ZSBCb29sZWFuIERlc2NyaXB0aW9uIn0sInRoZW1lIjoic2VtYW50aWMtdWkiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlLCJzaG93RXJyb3JMaXN0IjoidG9wIn19)
