### ISSUE TITLE
Allow arbitrary ordering of schema object properties

### ISSUE THREAD

**Issue by donalmurtagh** [rjsf-team/react-jsonschema-form#828]
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme)

### Description

I'm aware that `ui:order` can be used to specify an order in which the fields should be displayed. However, given a schema such as:
```json
{
  "type": "object",
  "properties": {
    "husband": {
      "type": "object",
      "properties": {
        "firstName": {
          "type": "string"
        },
        "surname": {
          "type": "string"
        }
      }
    },
    "wife": {
      "type": "object",
      "properties": {
        "firstName": {
          "type": "string"
        },
        "surname": {
          "type": "string"
        }
      }
    }
  }
}
```
There does not seem to be any way to order the properties as follows, even though this order includes all properties of the schema:

1. `husband.firstName`
1. `wife.firstName`
1. `wife.surname`
1. `husband.surname`

It appears that `ui:order` only supports the following

1. Rendering all the `husband.*` properties in any order followed by all the `wife.*` properties in any order
2. Rendering all the `wife.*` properties in any order followed by all the `husband.*` properties in any order

### Proposal

Extend the syntax of `ui:order` to support dot-notation, e.g.
```json
"ui:order": [
  "husband.firstName",
  "wife.firstName",
  "wife.surname",
  "husband.surname"
]
```

This could be further improved by adding explicit/implicit wildcard support, e.g.

```json
"ui:order": [
  "husband.firstName",
  "wife",
  "husband.surname"
]
```
or
```json
"ui:order": [
  "husband.firstName",
  "wife.*",
  "husband.surname"
]
```
### Versions

- react-jsonschema-form 1.0.0
- React 16.2.0

**Comment by mrclay** [comment]
It would be handy to have a schema-transformer toolkit that could reshape schemas/formData to change form UX and reverse the transformation after.

**Comment by epicfaace** [comment]
Interesting idea. For the case in which you have

```
"ui:order": [
  "husband.firstName",
  "wife.firstName",
  "wife.surname",
  "husband.surname"
]
```

Where would the title of the "husband" object field show up?

Additionally, if we apply a class to `husband` using `classNames`, how would that class be rendered? As of now it would create a parent element for `husband` which has that particular class, then render the properties of husband into that parent element.

**Comment by kenisteward** [comment]
@epicfaace I'm kinda piggy backing onto this but is there a current way to put arbitrary sections with said fields into it?

e.g.  from the example I'd want to make a FirstName section with husband and wife first names and a LastName section with husband and wife last name.

I thought i had found an issue that referred to doing something like that but I can't find it.

**Comment by epicfaace** [comment]
@kenisteward there currently isn't a way to do that, unless either 1) you use a custom ObjectFieldTemplate or 2) the data schema itself looks like:
```
firstName: {
    husband: { type: "string" },
    wife: { type: "string" },
},
lastName: {
    husband: { type: "string" },
    wife: { type: "string" },
}
```
