### ISSUE TITLE
Use field titles instead of field keys in error list template

### ISSUE THREAD

**Issue by donalmurtagh** [rjsf-team/react-jsonschema-form#831]
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

The error list template that shows all errors above the form, uses the following format

```
fieldKey: errorMessage
```
For example
> dateOfBirth: is a required property

Although it is possible to customise `errorMessage`, there does not seem to be any way to customise `fieldKey`. Personally, I think the field's title should be used by default instead of the key. 

For example, if the above field's title is set in either the `schema` or `uiSchema` to "Date of birth", then the error message that should appear (above the form) is:

```
Date of birth: is a required property
```
I realise that changing the default would be a breaking change, but is there a way I can use field titles instead of field keys? Using a custom [error list template](https://github.com/mozilla-services/react-jsonschema-form#error-list-template) doesn't seem to help, because the error messages have already been constructed by the time this component is invoked.

### Version

1.0.0

**Comment by brendan-jefferis** [comment]
You can set the key to be the title and this works, but in my opinion is not ideal.

```
const schema = {
  "type": "object",
  "properties": {
    "My password": {
      "type": "string",
      "minLength": 3
    }
  }
}

const uiSchema = {
  "My password": {
    "ui:widget": "password"
  }
}
```

This gives nice validation messages...

`My password: should NOT be shorter than 3 characters`

But at the expense of having to define the field title in two places

**Comment by donalmurtagh** [comment]
@brendan-jefferis in your example you've changed the field key to match the field title, but the error message is still using the field key.
