### ISSUE TITLE
How to get anyOf field value on change?

### ISSUE THREAD

**Issue by qasimalbaqali** [rjsf-team/react-jsonschema-form#835]
### Prerequisites

- [ x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I'm trying to populate an anyOf string input depending on another anyOf string input field. I want to detect the enum that has been chose in the anyOf #1 field so I would send an http request to fetch the data of the input that I have chose and to populate the #2 anyOf field.

The onChange method doesn't provide the value of the anyOf input field that have been changed. How would I do such thing?

### Current Schema

```
const schema = {
            title: "Create new discount",
            type: "object",
            required: ["pool_id", "start", "end", "amount_off", "timeslot_id"],
            properties: {
                pool_id: {
                    type: "string",
                    title: "Pool",
                    anyOf: this.state.pools
                },
                start: {
                    type: "string",
                    title: "Start Date",
                    format: "date"
                },
                end: {
                    type: "string",
                    title: "End Date",
                    format: "date"
                },
                amount_off: {
                    type: "integer",
                    title: "Amount Off"
                },
            },
            dependencies: {
                pool_id: {
                    properties: {
                        timeslot_id: {
                            type: "string",
                            title: "Time Slot",
                            anyOf: this.state.timeslots
                        }
                    }
                }
            }
        }
```

### Version

^1.0.0

**Comment by epicfaace** [comment]
You might just need to call onChange and compare the entire new formData with the old formData you are storing in the state, to see which fields has been changed.

Closing this issue as it's been a while, but feel free to reopen it if you have any additional questions.
