### ISSUE TITLE
Validation misbehaves for array of objects and minItems + uniqueItems rules

### ISSUE THREAD

**Issue by adrian-wierzbicki** [rjsf-team/react-jsonschema-form#847]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Combination of 
* Array of objects
* minItems > 1
* uniqueItems: true

Produces incorrect(or at least unexpected) validity state at the very first render. As far as I could investigate, `minItems: 2` makes the form compute a list of 2 default items, and since `default === default` it breaks on uniqueItems validation. The only reliable workaround I could think of is providing an empty array in `formData`.

### Steps to Reproduce

Example schema and formData on [Playground](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0ZXN0Ijp7InR5cGUiOiJhcnJheSIsInVuaXF1ZUl0ZW1zIjp0cnVlLCJtaW5JdGVtcyI6MiwiaXRlbXMiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidGVzdCI6eyJ0eXBlIjoic3RyaW5nIn19fX19fSwidWlTY2hlbWEiOnt9fQ==).

#### Expected behavior

The field's validation returns `should NOT have less than 2 items` error.

#### Actual behavior

The field's validation returns `should NOT have duplicate items (items ## 0 and 1 are identical)` error.

### Version

1.0.0

**Comment by mrclay** [comment]
Workaround: `default: [],`

**Comment by adrian-wierzbicki** [comment]
I have made a new playground to test `default: []`: [here](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0ZXN0Rm9ybURhdGEiOltdfSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJkZWZpbml0aW9ucyI6eyJ0ZXN0QXJyYXkiOnsidHlwZSI6ImFycmF5IiwidW5pcXVlSXRlbXMiOnRydWUsIm1pbkl0ZW1zIjoyLCJpdGVtcyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0ZXN0Ijp7InR5cGUiOiJzdHJpbmcifX19fX0sInByb3BlcnRpZXMiOnsidGVzdERlZmF1bHQiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJUZXN0IHdpdGhvdXQgJHJlZiBhbmQgYGRlZmF1bHQ6IFtdYCIsImRlZmF1bHQiOltdLCJ1bmlxdWVJdGVtcyI6dHJ1ZSwibWluSXRlbXMiOjIsIml0ZW1zIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InRlc3QiOnsidHlwZSI6InN0cmluZyJ9fX19LCJ0ZXN0Rm9ybURhdGEiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJUZXN0IHdpdGhvdXQgJHJlZiBhbmQgYGZvcm1EYXRhOiBbXWAiLCJkZWZhdWx0IjpbXSwidW5pcXVlSXRlbXMiOnRydWUsIm1pbkl0ZW1zIjoyLCJpdGVtcyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0ZXN0Ijp7InR5cGUiOiJzdHJpbmcifX19fSwidGVzdFJlZiI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy90ZXN0QXJyYXkiLCJ0aXRsZSI6IlRlc3Qgd2l0aCAkcmVmIn0sInRlc3RSZWZEZWZhdWx0Ijp7IiRyZWYiOiIjL2RlZmluaXRpb25zL3Rlc3RBcnJheSIsInRpdGxlIjoiVGVzdCB3aXRoICRyZWYgYW5kIGBkZWZhdWx0OiBbXWAiLCJkZWZhdWx0IjpbXX19fSwidWlTY2hlbWEiOnt9fQ==)

Observations:
* When you define your array directly in a field, `default: []` will not produce expected value(it seems it makes array of `[undefined, undefined]` which get invalidated on `uniqueItems` check - to workaround it you must provide `formData: { field: [] }`
* When you define your array in `definitions` and reference it in you field, `default: []` seem to work as expected

**Comment by prakharsrivas** [comment]
Even i'm facing similar issue with minItems 
If I'm passing "minItems" more 1. Its start showing me " Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout."
Even in test JSON structure i'm sharing correct array of object
