### ISSUE TITLE
Dependencies yields spurious validation error: "... should NOT have additional properties"

### ISSUE THREAD

**Issue by krallin** [rjsf-team/react-jsonschema-form#848]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

When using a [dynamic](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#dynamic) that includes a "controlled" property (i.e. one that shows up only if the "controlling" property is set to a specific value), then if the controlled property is an object, it fails validation. 

The form reports the controlled property is invalid because it has extra fields, but those fields are actually defined in the schema (presumably, if they weren't, then the form wouldn't even draw that field).

### Steps to Reproduce

[Shared playground repro](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJjb250cm9sbGluZ1Byb3BlcnR5Ijoid2l0aENvbnRyb2xsZWQiLCJjb250cm9sbGVkUHJvcGVydHkiOnsibmVzdGVkQ29udHJvbGxlZFByb3BlcnR5IjoxfX0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJjb250cm9sbGluZ1Byb3BlcnR5Ijp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbImRlZmF1bHQiLCJ3aXRoQ29udHJvbGxlZCJdLCJkZWZhdWx0IjoiZGVmYXVsdCJ9fSwicmVxdWlyZWQiOlsiY29udHJvbGxpbmdQcm9wZXJ0eSJdLCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2UsImRlcGVuZGVuY2llcyI6eyJjb250cm9sbGluZ1Byb3BlcnR5Ijp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7ImNvbnRyb2xsaW5nUHJvcGVydHkiOnsiZW51bSI6WyJkZWZhdWx0Il19fX0seyJwcm9wZXJ0aWVzIjp7ImNvbnRyb2xsaW5nUHJvcGVydHkiOnsiZW51bSI6WyJ3aXRoQ29udHJvbGxlZCJdfSwiY29udHJvbGxlZFByb3BlcnR5Ijp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im5lc3RlZENvbnRyb2xsZWRQcm9wZXJ0eSI6eyJ0eXBlIjoiaW50ZWdlciJ9fSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlfX0sInJlcXVpcmVkIjpbImNvbnRyb2xsZWRQcm9wZXJ0eSJdfV19fX0sInVpU2NoZW1hIjp7fX0=) 

Schema:

```
{
  "type": "object",
  "properties": {
    "controllingProperty": {
      "type": "string",
      "enum": [
        "default",
        "withControlled"
      ],
      "default": "default"
    }
  },
  "required": [
    "controllingProperty"
  ],
  "additionalProperties": false,
  "dependencies": {
    "controllingProperty": {
      "oneOf": [
        {
          "properties": {
            "controllingProperty": {
              "enum": [
                "default"
              ]
            }
          }
        },
        {
          "properties": {
            "controllingProperty": {
              "enum": [
                "withControlled"
              ]
            },
            "controlledProperty": {
              "type": "object",
              "properties": {
                "nestedControlledProperty": {
                  "type": "integer"
                }
              },
              "additionalProperties": false
            }
          },
          "required": [
            "controlledProperty"
          ]
        }
      ]
    }
  }
}
```

#### Expected behavior

`nestedControlledProperty` can be set and the form is valid.

#### Actual behavior

The form fails validation with:

```
['controlledProperty'] should NOT have additional properties
```

### Version

`1.0.1`.

**Comment by akshenk8** [comment]
The additionalProperties can be removed if the AJV library is passed appropriate [removeAdditional option](https://github.com/epoberezkin/ajv#filtering-data). The consequent effects will have to be tested.
