### ISSUE TITLE
Simple Example, First Name, not live

### ISSUE THREAD

**Issue by Crisfole** [rjsf-team/react-jsonschema-form#859]
### Description

On the example page: https://mozilla-services.github.io/react-jsonschema-form/ The first name field is not being validated live.

### Steps to Reproduce

 1. Delete Chuck's first name.
 2. Notice the validation doesn't happen immediately.
 3. Delete Chuck's last name.
 4. Notice the validation *does* happen immediately.

#### Expected behavior

The page itself claims it validates all the fields live.

#### Actual behavior

It does *not* validate the first name field live

### Version

Whatever's currently (10:27AM EST, 3/5/2018) running on github.io

**Comment by Crisfole** [comment]
It looks like the 'empty value' is not working nicely with the 'required' status.

**Comment by epicfaace** [comment]
I believe this is because the `default` value of firstName is equal to `Chuck`. It should be triggering neither HTML5 validation nor live validation, (while currently it's triggering HTML5 validation), so this is a bug.
