### ISSUE TITLE
Merge branch `knilink-error-schema-array` broken widgets with multiple `onChange` arguments

### ISSUE THREAD

**Issue by ojab** [rjsf-team/react-jsonschema-form#866]
### Steps to Reproduce

1. Make a widget that calls `this.props.onChange('123', ['123'])`
2. Use that widget for `type="string"` 

It works in rjsf-1.0.0, but fails with `Uncaught TypeError: Cannot use 'in' operator to search for '__errors' in 123` after https://github.com/mozilla-services/react-jsonschema-form/commit/a398bcfd5d775466036e2d1f14fd31b3cc85ab78 (i. e. in 1.0.1/1.0.2).

It's breaking change that should not happen in `patch` version update.

I'm using custom rjsf widgets to wrap other components and `onChange={this.props.onChange}`, and https://ant.design/components/tree-select/, for example, calls `function(value, label, extra)`.

**Comment by heath-freenome** [comment]
There appears to be a fix for this merged 2 years ago. closing
