### ISSUE TITLE
ajv dependency size

### ISSUE THREAD

**Issue by jbalboni** [rjsf-team/react-jsonschema-form#869]
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Hey all, 

First off, I wanted to thank you all for this library. We use it for a bunch of forms on vets.gov and it made our process for building forms so much faster and more stable than it was before. I made some contributions a year or so ago and it was also a very smooth and friendly process, so thank you for that as well!

We're using a fairly old version, so when I went to upgrade as part of our initial look at React 16, I noticed that you had recently switched from jsonschema to ajv. I can see the benefits of ajv, but one of the reasons we've avoided it on vets.gov for other things is that it's a fairly large library. It looks like the size of the minified bundle nearly doubled with the first version of react-jsonschema-form to incorporate it.

One of our big issues is the size of our bundled JS, so I've been trying to make sure we keep our dependencies from growing too large. The inclusion of ajv means that we'll probably end up forking this library instead of continuing to use this one, especially given that we've already replaced most of the fields and widgets with our own, and haven't encountered any specific issues with jsonschema.

I'm hesitant to suggest you switch back to jsonschema (or make it pluggable), since I can see the reasons for it, but we thought it was worth mentioning that it's an issue for us.

**Comment by edi9999** [comment]
Yes, I also care about bundle size in general, you don't want to have subdependencies that take a large size of your bundle size. 

I'm also for having a pluggable validation engine instead of forcing to use ajv, but I don't know rjsf well enough to know how easy that could be changed.

**Comment by sbmsr** [comment]
Any updates on this? I'm a fan of the library, and shared it on reddit, where some folks raised this  concern. I worry this alone impairs adoption of such an awesome tool.

**Comment by nickgros** [comment]
The validator will be decoupled from `@rjsf/core` in v5 thanks to work by @heath-freenome. If you want to add a validator to the repo, or recognize optimizations that can be made, please file an issue or even better, create a PR.

**Comment by heath-freenome** [comment]
The v5 beta is released, checkout the [5.x migration guide(https://react-jsonschema-form.readthedocs.io/en/latest/5.x%20upgrade%20guide/) and let us know whether this helps

**Comment by heath-freenome** [comment]
Closing the issue as users can now plug in their own validator if necessary
