### ISSUE TITLE
Why is `onReorderClick` passed to ArrayField items, rather than to the parent ArrayField?

### ISSUE THREAD

**Issue by micahscopes** [rjsf-team/react-jsonschema-form#872]
I'm trying to implement a drag and drop, sortable interface with an ArrayFieldTemplate.  The drag/drop library I'm using (react-sortable-hoc) lets you set an event handler at the parent container level.  Why isn't there a parent level interface to reordering ArrayField children accessible from ArrayFieldTemplate?

**Comment by fantapop** [comment]
@micahscopes did you ever get this working?

**Comment by epicfaace** [comment]
Good point, this would be a good feature. Additionally,  also for onDropIndexClick.
