### ISSUE TITLE
onFocus, onBlur currently not supported by all fields/widgets

### ISSUE THREAD

**Issue by pieplu** [rjsf-team/react-jsonschema-form#881]
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

onfocus, and onBlur function props are not supported by all fields and widgets. Exemple:
- [fileWidget](https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/components/widgets/FileWidget.js)
-  [CheckboxesWidget](https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/components/widgets/CheckboxesWidget.js)
- [CheckboxWidget](https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/components/widgets/CheckboxWidget.js)
- Maybe other

### Steps to Reproduce

1. Create a schema with a boolean field, and/or string filed with enum, and/or a string with format 'data-url'
2. Render a Form, with onFocus and/or onBlur function props
3. Focus on fields (with tab key or click)

#### Expected behavior

onFocus and onBlur function called on each field

#### Actual behavior

The function passing to props is never called

### Version

^1.0.1

**Comment by edi9999** [comment]
Indeed, thanks for this issue. 

Do you have time to create a PR ?

**Comment by pieplu** [comment]
Yes! but I can't now.
I think on the next month (may).

**Comment by kunal28889** [comment]
Has anyone started work on this issue ?

**Comment by llamamoray** [comment]
I guess not, but PRs welcome :)

**Comment by epicfaace** [comment]
This should be supported by nearly all widgets / fields now, so closing
