### ISSUE TITLE
hide title on checkboxes widget

### ISSUE THREAD

**Issue by mammad2c** [rjsf-team/react-jsonschema-form#886]
Hi,
How to disable `title` in Array ? 

schema:
```
"multipleChoicesList": {
      "type": "array",
       // "title": "A multiple choices list",
      "items": {
        "type": "string",
        "enum": [
          "foo",
          "bar",
          "fuzz",
          "qux"
        ]
      },
      "uniqueItems": true
    },
```

schemaUi :
```
"multipleChoicesList": {
"ui:widget": "checkboxes",
		"ui:options": {
			label: false,
			title: false,
			inline: true
		}
}
```

but a title always drop with  "multipleChoicesList" text. How can I disable title?

**Comment by swapnil95** [comment]
+1 for this. I am also facing the same issue. @mammad2c did you find a solution for this?

**Comment by epicfaace** [comment]
You can give it a className such as `hidden-title`, and then in your css do:

```
.hidden-title label.control-label {
  display: none;
}
```

See this fiddle for an example: https://jsfiddle.net/epicfaace/kvu1gxct/

**Comment by epicfaace** [comment]
You can actually use the `ui:label` option to hide labels by default. https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/uiSchema/#label

**Comment by hhkkyy** [comment]
I'll say that's a bug in packages\utils\src\schema\getDisplayLabel.ts
```
export default function getDisplayLabel<
  T = any,
  S extends StrictRJSFSchema = RJSFSchema,
  F extends FormContextType = any
>(
  validator: ValidatorType<T, S, F>,
  schema: S,
  uiSchema: UiSchema<T, S, F> = {},
  rootSchema?: S,
  globalOptions?: GlobalUISchemaOptions
): boolean {
  const uiOptions = getUiOptions<T, S, F>(uiSchema, globalOptions);
  const { label = true } = uiOptions;
  let displayLabel = !!label;
  const schemaType = getSchemaType<S>(schema);

  if (schemaType === 'array') {
    displayLabel =
      isMultiSelect<T, S, F>(validator, schema, rootSchema) ||
      isFilesArray<T, S, F>(validator, schema, uiSchema, rootSchema) ||
      isCustomWidget(uiSchema);
  }

  if (schemaType === 'object') {
    displayLabel = false;
  }
  if (schemaType === 'boolean' && !uiSchema[UI_WIDGET_KEY]) {
    displayLabel = false;
  }
  if (uiSchema[UI_FIELD_KEY]) {
    displayLabel = false;
  }
  return displayLabel;
}
```
In the codes above, the method getDisplayLabel which decides if a field should render its lable and description(I don't understand why they share the same flag) does not respect ui:options.label while it's a multi-select,files array or custom widget. An multi-select/radio/checkbox is regarded as isMultiSelect, as a result none of them respect ui:options.label.


Using className such as hidden-title is definitely a bad practice, it may work but if this is the suggested way, what's ui:options.label for?

RJSF use the name of property as its default label while title, ui:options.title or such parameters are not set, I think it'll be much better having a global setting for this behavior which decides if to use property key as a default label or simply hides label while no other parameters are set
