### ISSUE TITLE
Missing validation message for required array

### ISSUE THREAD

**Issue by donalmurtagh** [rjsf-team/react-jsonschema-form#900]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Given a schema such as

```
  const schema = {
    type: 'object',
    properties: {
      evidence: {
        type: "array",
        minItems: 1,
        title: "Evidence",
        items: {
          type: "string",
          format: "data-url"
        }
      }
    },
    required: ['evidence']
  };
```
Validation fails if the form is submitted without opening the file selection dialog, but a validation message is not shown in the uI

### Steps to Reproduce

1. Open [this JSFiddle demo](https://jsfiddle.net/650mm7bo/6/)
2. Press the Submit button 
3. Validation will fail, but a validation message is not shown in the UI

On the other hand if you follow these steps

1. Open [this JSFiddle demo](https://jsfiddle.net/650mm7bo/6/)
2. Click the "Choose Files" button and select a file
3. Click the "Choose Files" button again and then click the Cancel button to remove the file selected in the previous step
4. Press the Submit button 
5. Validation fails, and a validation message is shown in the UI

In both cases no files were selected, however steps 2 & 3 in the second test case initialize the property to an empty array.

Thererfore, a way to workaround this problem is to set

```
<Form schema={schema} showErrorList={false} uiSchema={uiSchema} formData={{evidence: []}}/>
```

#### Expected behavior

If the form is submitted without any files, a validation message should always be shown

#### Actual behavior

A validation message is not shown in the first test case outlined above

### Version

1.0.3

**Comment by glasserc** [comment]
Isn't the lack of an error message because you have `showErrorList=false`?

**Comment by glasserc** [comment]
Oh, no, sorry, I misunderstood what's going on. So, I guess the two error behaviors are because the data in the first case is an empty string. That's a bit strange. I'd be interested in reviewing a fix.

**Comment by donalmurtagh** [comment]
> Isn't the lack of an error message because you have showErrorList=false?

No, that just prevents the list of all errors from appearing above the field. I'm referring to the error message that appears under a field when it's invalid.

**Comment by donalmurtagh** [comment]
> So, I guess the two error behaviors are because the data in the first case is an empty string.

No, in the first case the model is completely empty, i.e. `{}`. The validation message that is generated is "0: should be string", but this message is not shown in the UI. In my opinion there are 2 problems here:

1. `evidence` is a required property, so the validation message should be "address: is a required property"
2. The validation message should be displayed in the UI

**Comment by heath-freenome** [comment]
As of version 5.x this appears to be fixed as shown by this [Playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJldmlkZW5jZSI6eyJ0eXBlIjoiYXJyYXkiLCJtaW5JdGVtcyI6MSwidGl0bGUiOiJFdmlkZW5jZSIsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJmb3JtYXQiOiJkYXRhLXVybCJ9fX0sInJlcXVpcmVkIjpbImV2aWRlbmNlIl19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)
