### ISSUE TITLE
Support for input 'autocomplete' attribute?

### ISSUE THREAD

**Issue by uwolfer** [rjsf-team/react-jsonschema-form#906]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description

It looks like setting `autocomplete` attribute for inputs is not supported (without writing a custom component).

It would help to improve usability of forms. See for example a nice [Google Developer](https://developers.google.com/web/fundamentals/design-and-ux/input/forms/#recommended_input_name_and_autocomplete_attribute_values) post.

### How to implement
I think it could be added like `autofocus` [got added](https://github.com/mozilla-services/react-jsonschema-form/commit/316258ea5f9ef8b0c03c9e4db991029e2c164428). Is this the best way to do it?

**Comment by prydonius** [comment]
+1 this would be awesome

**Comment by eberkund** [comment]
Yea this would be awesome and straightforward to add IMO.

I think the best approach would be allow something like this in the UI schema:

    {
      "firstName": {
        "ui:autofocus": true,
        "ui:emptyValue": "",
        "ui:autocomplete": "fname"
      }
    }

**Comment by epicfaace** [comment]
Yes, anyone interested in writing a PR for this?

**Comment by epicfaace** [comment]
@levilian interested in making a PR for this?

**Comment by epicfaace** [comment]
@levilian

**Comment by james-gc** [comment]
@epicfaace this feature is done in my PR with  [commit](https://github.com/mozilla-services/react-jsonschema-form/pull/1262/commits/e05a53da042030cd9705376b090cf80c06efe0f7)

**Comment by epicfaace** [comment]
@james-gc thanks for your PR! Do you mind putting those changes for ui:autocomplete in a separate PR? That will help us to approve it faster!
