### ISSUE TITLE
customise attributes of file widget's input field

### ISSUE THREAD

**Issue by donalmurtagh** [rjsf-team/react-jsonschema-form#907]
When a `<input type="file">` field is added to a form via the [FileWidget](https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/components/widgets/FileWidget.js) the following markup is generated for the input field:

```html
          <input
            ref={ref => (this.inputRef = ref)}
            id={id}
            type="file"
            disabled={readonly || disabled}
            onChange={this.onChange}
            defaultValue=""
            autoFocus={autofocus}
            multiple={multiple}
          />
```
This allows very limited options for customising the attributes of the `<input>` field. For example, 
[HTML media capture](https://www.w3.org/TR/html-media-capture/) specifies that this input field

    <input type="file" name="image" accept="image/*" capture="user">

will (on a mobile device) allow a user to choose an image from their gallery or produce an image by taking a photo with the phone's self-facing camera. However, it doesn't seem possible to add these attributes using the present `FileWidget`.

**Comment by epicfaace** [comment]
You should be able to solve this by adding a custom widget. Feel free to add a PR which specifies certain attributes in `<input type="file">` from `ui:options` though.

**Comment by epicfaace** [comment]
Related to #226.
