### ISSUE TITLE
Unable to input text, check boxes, etc.

### ISSUE THREAD

**Issue by jinglemansweep** [rjsf-team/react-jsonschema-form#936]
### Prerequisites

- [/] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [/] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
I have the following form...

    const schema = {
        title: 'VS Index',
        type: 'object',
        required: [],
        properties: {
            filters: {
                type: 'string',
                title: 'Filters'
        },
        aggregates: {
            type: 'string',
            title: 'Aggregates'
        }
    }

    class VSIndexContainer extends Component<Props, State> {
        render() {
            return (
                <div styleName="container">
                    <h1>VS Index</h1>
                    <Form schema={schema} />
                </div>
            );
       }
    }

When the form is rendered, I have two text fields, but when I try to type in them, the onChange event is fired, but the underlying formData values are unchanged and the UI appears to be "read-only".

### Steps to Reproduce

1. Create form as above
2. Render Form class
3. Inputs are read-only, you cannot type in them.

#### Expected behavior

Should be able to type in the form.

#### Actual behavior

Form appears to be read-only

### Version

1.0.3

**Comment by doncesarts** [comment]
Hi  @jinglemansweep ,
You are missing one `}` in your definition of the schema. 

Try 

```
const schema = {
    title: 'VS Index',
    type: 'object',
    required: [],
    properties: {
        filters: {
            type: 'string',
            title: 'Filters'
          },
        aggregates: {
            type: 'string',
            title: 'Aggregates'
        }
    }
}

class VSIndexContainer extends Component<Props, State> {
    render() {
        return (
            <div styleName="container">
                <h1>VS Index</h1>
                <Form schema={schema} />
            </div>
        );
   }
}
```

**Comment by jinglemansweep** [comment]
That was a typo I made when pasting and formatting the comment. The schema and UI schema are valid JSON.

It appears that key inputs are causing the parent container component to re-render, overwriting the forms state.

I added:

    shouldComponentUpdate() {
      return false;
    }

... to the parent container and it works now, but is this really necessary?
