### ISSUE TITLE
Enhancement: Allow rawErrors to be an Array of PropTypes.any

### ISSUE THREAD

**Issue by doncesarts** [rjsf-team/react-jsonschema-form#941]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
I am facing the following scenario: 
I need to transform and translate error messages, this is done trough the function `transformErrors` [custom-error-messages](https://github.com/mozilla-services/react-jsonschema-form/blob/66ab17a72b9dec7fd2bc7bd21785f27557cc0b49/README.md#custom-error-messages)

1. To translate the message I am using  [react-intl](https://github.com/yahoo/react-intl).
2. The function `transformErrors` can not be wrapped with `react-intl` , so `transformErrors` returns an array of translatable messages (objects) , instead of strings. 
3. Error messages are translated in a custom `Error` component. 
3. There are errors in the console complaining about the type. 
4. This errors could be avoid if rawErrors  hare ` Array of PropTypes.any`

The documentation for [rawErrors](https://github.com/mozilla-services/react-jsonschema-form/blob/66ab17a72b9dec7fd2bc7bd21785f27557cc0b49/README.md#field-template) says as following:

> If you want to handle the rendering of each element yourself, you can use the props rawHelp, rawDescription and rawErrors.

Defining `rawErrors` to only accept strings limits the full potential of customisations.  I will be willing to do a pull request with this changes. 

#### Expected behavior
No warnings in the console. 

`   
 rawErrors: PropTypes.arrayOf(PropTypes. any),
`

#### Actual behavior

```
    rawErrors: PropTypes.arrayOf(PropTypes.string),

Warning: Failed prop type: Invalid prop `rawErrors[0]` of type `object` supplied to `StringField`, expected `string`.
```

**Comment by epicfaace** [comment]
@doncesarts yes, makes sense, please feel free to make a PR with these changes
