### ISSUE TITLE
Support HTML and Markdown input types.

### ISSUE THREAD

**Issue by burtonator** [rjsf-team/react-jsonschema-form#955]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

It seems that HTML and markdown data isn't supported. Would be really nice to have these as supported widgets. '

I'm trying to get SimpleMD to work with it and while it initially works via react-simplemde-editor there are some bugs with form validation.

**Comment by eberkund** [comment]
Can this be done with a custom field template or something?

**Comment by burtonator** [comment]
I can post my code.. it's not amazing as I'm not a React expert yet. 

I'm using SimpleMD
