### ISSUE TITLE
Prevent form Submission on Enter

### ISSUE THREAD

**Issue by sneu012** [rjsf-team/react-jsonschema-form#970]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Is there any way I could prevent form submission on pressing ENTER?

**Comment by doncesarts** [comment]
Hi @sneu012 , this might help you #839.
