### ISSUE TITLE
Checkbox using DescriptionField not from Registry

### ISSUE THREAD

**Issue by theluk** [rjsf-team/react-jsonschema-form#973]
I noticed that the CheckboxWidget is importing and using the DescriptionField.

Why?

Also, if I supply a custom DescriptionField to the Form via the fields prop, the DescriptionField in the CheckboxWidget does not change properly, right? 

https://github.com/mozilla-services/react-jsonschema-form/blob/b2e57779b3b2be6893a1b44156e1024016b9b8aa/src/components/widgets/CheckboxWidget.js#L20

**Comment by epicfaace** [comment]
@theluk it looks like the title and description are in the following locations in a checkbox ([playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOnRydWUsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCJ9LCJzY2hlbWEiOnsidGl0bGUiOiJBIHJlZ2lzdHJhdGlvbiBmb3JtIiwiZGVzY3JpcHRpb24iOiJBIHNpbXBsZSBmb3JtIGV4YW1wbGUuIiwidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbImZpcnN0TmFtZSIsImxhc3ROYW1lIl0sInByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7ImRlc2NyaXB0aW9uIjoiRGVzY3JpcHRpb24iLCJ0eXBlIjoiYm9vbGVhbiIsInRpdGxlIjoiVGl0bGUiLCJkZWZhdWx0IjoiQ2h1Y2sifSwibGFzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiTGFzdCBuYW1lIn0sImFnZSI6eyJ0eXBlIjoiaW50ZWdlciIsInRpdGxlIjoiQWdlIn0sImJpbyI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJCaW8ifSwicGFzc3dvcmQiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiUGFzc3dvcmQiLCJtaW5MZW5ndGgiOjN9LCJ0ZWxlcGhvbmUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiVGVsZXBob25lIiwibWluTGVuZ3RoIjoxMH19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoidXBkb3duIiwidWk6dGl0bGUiOiJBZ2Ugb2YgcGVyc29uIiwidWk6ZGVzY3JpcHRpb24iOiIoZWFydGhpYW4geWVhcikifSwiYmlvIjp7InVpOndpZGdldCI6InRleHRhcmVhIn0sInBhc3N3b3JkIjp7InVpOndpZGdldCI6InBhc3N3b3JkIiwidWk6aGVscCI6IkhpbnQ6IE1ha2UgaXQgc3Ryb25nISJ9LCJkYXRlIjp7InVpOndpZGdldCI6ImFsdC1kYXRldGltZSJ9LCJ0ZWxlcGhvbmUiOnsidWk6b3B0aW9ucyI6eyJpbnB1dFR5cGUiOiJ0ZWwifX19fQ==)):

![image](https://user-images.githubusercontent.com/1689183/54482325-e1f97c80-47fe-11e9-81f7-fbcecfc91f83.png)
