### ISSUE TITLE
onChange specific field

### ISSUE THREAD

**Issue by xero88** [rjsf-team/react-jsonschema-form#981]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Hello,
Is there a way to know with the onChange callback, which field has been updated ?
Thank you

**Comment by manahga** [comment]
This functionality is not present by default. However, I was able to customize the SchemaField component to achieve the desired functionality.

See the following issue for details: #651

**Comment by CarlFMateus** [comment]
Hello,

I wanted to ask if you have already worked on this type of requirement. I would really appreciate it. @xero88 do you know if you already have a different solution on this?
