### ISSUE TITLE
schema-dependencies not playing nice with variable length arrays

### ISSUE THREAD

**Issue by ggerber** [rjsf-team/react-jsonschema-form#985]
### Prerequisites

- [x ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I have a form that has schema dependencies. It consists of two fields: "pattern_type" (a dropdown) and "multipliers" (array of numbers).

The pattern_type dropdown determines the type of multiplier array (each type can have different array lengths).

It seems that once the multiplier array field has been instantiated to a certain length, it cannot be updated, when you select a different pattern_type from the dropdown.

I get this error:
          Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined
            at retrieveSchema (modules.js?hash=c1a3516f70fb27416db342df32c467b736690727:48343)
            at modules.js?hash=c1a3516f70fb27416db342df32c467b736690727:44851
            at Array.map (<anonymous>)
            at ArrayField.renderFixedArray (modules.js?hash=c1a3516f70fb27416db342df32c467b736690727:44849)
            at ArrayField.render (modules.js?hash=c1a3516f70fb27416db342df32c467b736690727:44623)
            at finishClassComponent (react-dom.development.js:13771)
            at updateClassComponent (react-dom.development.js:13733)
            at beginWork (react-dom.development.js:14402)
            at performUnitOfWork (react-dom.development.js:16441)
            at workLoop (react-dom.development.js:16480)

### Steps to Reproduce

I'm providing a JSFiddle demonstrating the issue here: https://jsfiddle.net/pms2ebzn/

#### Expected behavior

When I switch between pattern_type enum's, the multiplier array should adjust itself, based on the dependency rule.

MONTHLY should show an array with 3 items (January, February, March).
DAILY should show an array with 2 items (Sunday, Monday).

Also switching from DAILY (that has 2 items) to MONTHLY, should not truncate the array to only two items (January, February).

#### Actual behavior

Depending on whether the form is instantiated with "MONTHLY" or "DAILY" pattern_type, I can switch the between the mulitplier array fields. It seems that if the form was instantiated with an array that has more elements than the alternative array options, then an error occurs.

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by adamduncan** [comment]
@ggerber Did you ever get to the bottom of this?
