### ISSUE TITLE
automatic tests in browserstack

### ISSUE THREAD

**Issue by graingert** [rjsf-team/react-jsonschema-form#990]
There's been a few issues with running the code in IE11, it would be good to get tests running in IE, with eg karma+BrowserStack (or similar) I think it's free for open source?

**Comment by loganvolkers** [comment]
There are some caveats, but yes it looks like BrowserStack has an open source program if a maintainer wants to sign up: https://www.browserstack.com/open-source

Based on a cursory glance at `package.json` it looks like the bigger project would just be setting up Karma.

**Comment by epicfaace** [comment]
I've submitted a request with browserstack.
