### ISSUE TITLE
Remove value from formData when property is removed (not required)

### ISSUE THREAD

**Issue by zrzka** [rjsf-team/react-jsonschema-form#992]
### Description

I'm trying to achieve something like this:

* if `enable` property is `true`, it MUST contain `ssid` property
* if `enable` property is `false`, it MUST NOT contain `ssid` property

### Steps to Reproduce

1. Open this [example](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6IkNvbmZpZ3VyYXRpb24iLCJkZXNjcmlwdGlvbnMiOiJEZXBlbmRlbmNpZXMgZXhhbXBsZXMiLCJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsiZW5hYmxlIl0sInByb3BlcnRpZXMiOnsiZW5hYmxlIjp7InRpdGxlIjoiRW5hYmxlIFdpRmk/IiwidHlwZSI6ImJvb2xlYW4iLCJkZWZhdWx0IjpmYWxzZX19LCJkZXBlbmRlbmNpZXMiOnsiZW5hYmxlIjp7Im9uZU9mIjpbeyJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2UsInByb3BlcnRpZXMiOnsiZW5hYmxlIjp7ImVudW0iOlt0cnVlXX0sInNzaWQiOnsidGl0bGUiOiJOZXR3b3JrIFNTSUQiLCJ0eXBlIjoic3RyaW5nIn19LCJyZXF1aXJlZCI6WyJzc2lkIl19LHsiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7ImVuYWJsZSI6eyJlbnVtIjpbZmFsc2VdfX19XX19fSwidWlTY2hlbWEiOnt9fQ==)
2. Enable WiFi
3. Fill in SSID
4. Disable WiFi
5. Error `['ssid'] should NOT have additional properties` appears

If the link in 1. wont work, here's the [schema](https://gist.github.com/zrzka/7dd4028e312dd0b1afe0e93e2d81e050).

#### Expected behavior

No `['ssid'] should NOT have additional properties` error. I expect that there will be no `ssid` value in `formData` when I disable WiFi.

#### Actual behavior

Keeps `ssid` in `formData` and raising `['ssid'] should NOT have additional properties` error.

**Comment by loganvolkers** [comment]
I believe this is related to #902 and #848.

I believe there is a longstanding issue when using `"additionalProperties": false`
