### ISSUE TITLE
Autocomplete login on mobile?

### ISSUE THREAD

**Issue by lokaltrav** [rjsf-team/react-jsonschema-form#993]
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I have a login form with an email and a password. Autocomplete works perfectly and behaves normally on desktop. However, on mobile, it doesn't recognize that the values are valued (both are marked as required and even though they will visually appear to be filled out, the form gives me warnings that they are both required and need to be filled out (maybe the autocomplete didn't fire all the events to set the behind-the-scenes values?). Most users are not able to understand that they need to manually type it in since it is already filled in (manual re-entry will work) so our login form doesn't auto-fill properly on mobile. Is there a workaround?

### Steps to Reproduce

1. 
```
const schema = {
  title: '',
  type: 'object',
  required: ['email', 'password'],
  properties: {
    email: {
      type: 'string',
      title: 'Email',
      format: 'email',
    },
    password: {
      type: 'string',
      title: 'Password',
      minLength: 8,
    },
  },
};

const uiSchema = {
  password: {
    'ui:widget': 'password',
  },
};
```
2. Have filled out the form previously.
3. Load on mobile and autocomplete and attempt submission (tested using Chrome on laptop and mobile). Form will show errors on submission.

You can see this behavior at:
https://www.lokaltravel.com/login

Reminder: you will first need to register for the site, login manually once successfully, logout and next login attempt use Chrome's auto-complete rather than manual entry.

#### Expected behavior

I'd expect the desktop autocomplete behavior and the mobile behavior to be the same.

#### Actual behavior

Mobile will show fields as being filled out but will error as though they weren't. (Desktop works perfectly)

### Version

1.0.3

**Comment by eenagy** [comment]
Similar issue on Firefox. Autocomplete fields will be empty until onChange handle doesn't run.

**Comment by dfdumaresq** [comment]
I have a similar problem with fields on several of my forms. Their values will be displayed on the mobile devices but the onChange does not fire and their values will not be submitted when the Submit button is tapped.
