### ISSUE TITLE
uiSchema option 'ui:enumDisabled' not working where type=array

### ISSUE THREAD

**Issue by drewwills** [rjsf-team/react-jsonschema-form#996]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

In my JSON Schema, I have a structure of `type="array"` where the available choices are listed in an `enum`.  I would like to apply `ui:enumDisabled` to one of the elements in the `enum`, but (when I do) it doesn't seem to have an effect on the form.

### Steps to Reproduce

Here is my JSON Scema...

```
  {
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$id": "http://localhost:8090/communication-preferences.json",
    "title": "Communication Preferences",
    "description": "Please review your information that we have on file to make sure that our records are up-to-date.  Failure to provide current information can cause our self service not to work for you.",
    "type": "object",
    "properties": {
      "channels": {
        "$id": "/properties/channels",
        "description": "The following messaging services are available for you to subscribe.  Some services are available at multiple campuses;  your primary campus will be selected by default.",
        "type": "object",
        "properties": {
          "taco_truck": {
            "$id": "/properties/channels/taco_truck",
            "title": "Taco Truck",
            "description": "This service keeps you informed about where to find tacos on campus",
            "type": "object",
            "properties": {
              "locations": {
                "$id": "/properties/channels/taco_truck/locations",
                "type": "array",
                "items": {
                  "type": "string",
                  "enum": [
                    "Fresno City College",
                    "Clovis Community College",
                    "Reedley College"
                  ]
                },
                "uniqueItems": true
              }
            }
          }
        }
      }
    }
  }
```
and here is my uiSchema...

```
  {
    "channels": {
      "taco_truck": {
        "locations": {
          "ui:widget": "checkboxes",
          "ui:options": {
            "inline": true
          },
          "ui:enumDisable": [
            "Reedley College"
          ]
        }
      }
    }
  }
```

#### Expected behavior

I expect the `Reedley College` checkbox located at `/channels/taco_truck/locations` to be disabled (but it isn't).

#### Actual behavior

The form looks correct -- and it correctly produces JSON -- but the `Reedley College` checkbox is editable by users.

### Version

```
"react-jsonschema-form": "^1.0.3"
```

**Comment by loganvolkers** [comment]
Looks like this doesn't exist in the Checkboxes widget, I believe it would require a small change to [this line](https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/components/widgets/CheckboxesWidget.js#L23)

In the short term you could [create a custom widget](https://github.com/mozilla-services/react-jsonschema-form#custom-widgets-and-fields) for your application based on the checkboxes widget.

In the long term, I'm sure a PR would be welcome.

Also, I noticed a small typeo in your example `enumDisable` should be `enumDisabled` (notice the missing trailing `d`)

**Comment by drewwills** [comment]
Thanks for the look and the tips.

BTW, we organized a [Java Platform back-end for this component](https://github.com/drewwills/fbms) based on Spring Boot, Spring Data (JPA), Spring Security, and Open ID Connect.  It's Apache 2.
