### ISSUE TITLE
Schema Dependencies Merged Incorrectly

### ISSUE THREAD

**Issue by arahansen** [rjsf-team/react-jsonschema-form#998]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

When merging schema with dependencies, enums are appended instead of replaced.

### Steps to Reproduce

1. Visit [this playground example](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0eXBlMSI6IkZPTyJ9LCJzY2hlbWEiOnsidGl0bGUiOiJBIHJlZ2lzdHJhdGlvbiBmb3JtIiwiZGVzY3JpcHRpb24iOiJBIHNpbXBsZSBmb3JtIGV4YW1wbGUuIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidHlwZTEiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiVHlwZSAxIiwiZW51bSI6WyJGT08iLCJCQVIiLCJCQVoiXX0sInR5cGUyIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlR5cGUgMiIsImVudW0iOlsiR1JFRU4iLCJCTFVFIiwiUkVEIl19fSwiZGVwZW5kZW5jaWVzIjp7InR5cGUxIjp7InByb3BlcnRpZXMiOnsidHlwZTEiOnsiZW51bSI6WyJGT08iXX0sInR5cGUyIjp7ImVudW0iOlsiR1JFRU4iXX19fX19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX19)
2. Select "FOO" for Type 1
3. Notice form presents errors `enum should NOT have duplicate items`

![image](https://user-images.githubusercontent.com/8746094/43650867-be525ec4-96f5-11e8-96ef-60808df52faa.png)

#### Expected behavior

The form should have no errors as I expect the list of valid enums to be _replaced_ with `["FOO"]`. Not that `"FOO"` will be appended to list of enums. This appears to be occurring in [`mergeSchemas util`](https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/utils.js#L473)

#### Actual behavior

merged schema should consist only of a single enum. This is the behavior I see when validating the schema on https://www.jsonschemavalidator.net/.

output:
![image](https://user-images.githubusercontent.com/8746094/43651167-7f6404dc-96f6-11e8-8089-7a2b6a5dfcda.png)

But the schema created by react-jsonschema-form contains 4 enums, with two being duplicate: `["FOO", "BAR", "BAZ", "FOO"]`

### Version
1.0.4

**Comment by MatejMazur** [comment]
Have you already found any reason why this is happening? I've found out that this problem appears even in the tests (only rewritten from Mocha to Jest) in my fork (not sure why they pass in original repo).

![image](https://user-images.githubusercontent.com/20944757/44391432-230f0400-a530-11e8-9adc-ce953e5dd6f1.png)

**Comment by MatejMazur** [comment]
Tests aren't working correctly. Specifically [these two tests wrongly return "success"](https://github.com/mozilla-services/react-jsonschema-form/blob/aadbbe9701c4db9df761e86f0280e1ecafc509f8/test/Form_test.js#L1407-L1443) but they should fail. I don't know Mocha (I use Jest) so someone shoul repair these tests.

And this change should solve this issue:
in [`utils.js`](https://github.com/mozilla-services/react-jsonschema-form/blob/aadbbe9701c4db9df761e86f0280e1ecafc509f8/src/utils.js#L525)
```diff
- return mergeSchema(
+ return mergeObjects(
    schema,
    retrieveSchema(dependentSchema, definitions, formData)
  );
```

Tests have to be repair by somebody else because I am using rewritten tests with Jest and there these two tests were failing as they should.

Hope it helps!

**Comment by MatejMazur** [comment]
That's weird.. [this line should care of this](https://github.com/mozilla-services/react-jsonschema-form/blob/aadbbe9701c4db9df761e86f0280e1ecafc509f8/src/utils.js#L521).

**Comment by epicfaace** [comment]
This might be related to #1162 .

**Comment by celso-slalom** [comment]
Debuggin this problem, the culprit is [here](https://github.com/mozilla-services/react-jsonschema-form/blob/aadbbe9701c4db9df761e86f0280e1ecafc509f8/src/utils.js#L228). mergeObjects is concatenating ["BLUE"] to ["BLUE", "GREEN", "RED"]

**Comment by epicfaace** [comment]
Hmm, thanks for investigating @celso-slalom . It looks like the concatArrays option was added in this commit: https://github.com/mozilla-services/react-jsonschema-form/commit/933f057344873ad6aae3c086d50b5467814b28f3

I may be wrong, but I believe this option was added in order to combine errors that come from ajv + errors that are custom added for the same field? For example, if the errorSchema coming from ajv looks something like this:

```
{
        "first_name": {
          __errors: ["error1"],
        }
    }
```

And then the errorSchema generated from the custom validate function looks like this:

```
{
        "first_name": {
          __errors: ["error2"],
        }
    }
```

Then mergeObjects should return the following errorSchema:

```
```
{
        "first_name": {
          __errors: ["error1", "error2"],
        }
    }
```
```

**Comment by celso-slalom** [comment]
Hi @epicfaace, I really appreciate your answer. I've created [this fiddle](https://repl.it/@celso_slalom/react-jsonschema-formissues998) pointed to my fork of react-jsonschema-form. Based on your comments above, toggling concatArrays=true [here](https://github.com/mozilla-services/react-jsonschema-form/blob/aadbbe9701c4db9df761e86f0280e1ecafc509f8/src/utils.js#L532) doesn't seem to affect validation. Can you please confirm if that's the case so I can create a PR? 

Thanks!

**Comment by epicfaace** [comment]
@celso-slalom I've added a test that fails when you toggle concatArrays to false in the place you mentioned: https://github.com/mozilla-services/react-jsonschema-form/pull/1306

I think the solution for this is, when concatArrays is true, one needs to discard duplicate elements when performing the concat. Would you be able to make a PR fixing this? https://github.com/mozilla-services/react-jsonschema-form/blob/aadbbe9701c4db9df761e86f0280e1ecafc509f8/src/utils.js#L228

**Comment by epicfaace** [comment]
@celso-slalom ?

**Comment by tsunamiq** [comment]
Are there any updates to this issue? We're running into the same problem with multiple enums being generated through the form.

**Comment by travisdahl** [comment]
+1 also stuck with this issue. Any news?
